### ISSUE TITLE
NaN% in metrics donut chart tooltip

### ISSUE THREAD

**Issue by vreon** [lensapp/lens#100]
**Describe the bug**
If metrics are unavailable, the tooltip for the Memory stacked donut chart displays `NaN%` as the Usage value. (For CPU, the tooltip displays `0%` as the Usage value, which I suppose is also not technically accurate...)

**To Reproduce**
1. Select a cluster where metrics are not available
2. Hover over the Memory donut chart
3. Tooltip displays `NaN%`

**Expected behavior**
Expected to see `N/A` or `0%` for Usage in tooltip

**Screenshots**
![Screenshot_2019-11-29_22-39-58](https://user-images.githubusercontent.com/52548/69897277-a9eb8880-12fe-11ea-8b4b-f9b13b972c41.png)

**Environment (please complete the following information):**
- Lens Version: 2.6.5
- OS: Linux
- Installation method (e.g. snap or AppImage in Linux): AppImage
 
**Logs:**
n/a

**Kubeconfig:**
n/a

**Additional context**
NaN :wink:

**Comment by aleksfront** [comment]
Bug has been fixed and will be available in upcoming release.
