### ISSUE TITLE
Selecting a cluster by search

### ISSUE THREAD

**Issue by the-gigi** [lensapp/lens#1011]
**What would you like to be added**:

A text box to select clusters. As you type to narrow your search a dropdown shows the clusters that match your current input and you can select the cluster you want. The matching can be wild curd, regex or fuzzy search.

**Why is this needed**:

I work regularly with tens of clusters that I need to switch between (multiple types of clusters, each type in multiple geographical regions and staging and production clusters in each region).

The icons on the sidebar are super cool, but I have to scroll down the list and hover over each icon to discover the cluster I want. With 20+ clusters this is super tedious.

**Environment you are Lens application on:**

- Kubernetes distribution: GKE
- Desktop OS: macOS Catalina

**Comment by Nokel81** [comment]
Now that 5.0 is out (and 5.2 should be released next week) there is now the ability to setup hotbars. However, we could add the ability to execute entity actions from the command dialog, would that be a good workflow for you?
