### ISSUE TITLE
Lens 3.6.x seems to lose connection and present errors, requiring manual reconnects

### ISSUE THREAD

**Issue by longwa** [lensapp/lens#1019]
Since moving to the 3.6.x release, whenever I switch back to Lens after a while, I'll have a screen full of errors like this:

![image](https://user-images.githubusercontent.com/361184/94948271-0edab680-04ad-11eb-966d-1fcd36a1b63b.png)

The prior version seemed to be able to gracefully handle connection issues. 

I can click Reconnect and it will restore whatever I was on before.

**To Reproduce**
1. Be connected for awhile
2. Maybe simulate some kind of intermittent connection loss (although I'm not seeing anything specific like Wifi drop or anything like that). Other applications with persistent connections such as SQL tools seem fine.

**Expected behavior**
Ideally, it would be able to tolerate a small connection blip without user intervention.

**Environment (please complete the following information):**
- Lens Version: 3.6.5
- OS: 10.14.6
 

**Additional context**
We are using OIDC authentication, which has a key that expires every few hours and must be refreshed. Lens 3.6.0 and later seems to be able to handle that now (the old version did not). It's possible that is contributing to the issues when the key expires, it loses the Watch and fails until a refresh token is sent and the key is updated.

**Comment by longwa** [comment]
More evidence to support that it fails when the access token expires:

![image](https://user-images.githubusercontent.com/361184/94959914-0049ca80-04c0-11eb-9789-428350e86c76.png)

All I had to do was click reconnect and it worked fine.

**Comment by Nokel81** [comment]
Is this this a problem with 4.1.4?
