### ISSUE TITLE
Adding MS Windows Support To Lens Exec Command

### ISSUE THREAD

**Issue by dmitarb** [lensapp/lens#102]
**What would you like to be added**:
I have been using Lens on MacOS for a while now and think it excellent. When I exec into a Windows pod it uses `kubectl exec -i -t -n default win-webserver-8648d6f7b8-g6jzm -c windowswebserver "--" sh -c "((clear && bash) || (clear && ash) || (clear && sh))"` and fails.
To fix this is it possible for you to query the type of pod it is and if its windows to add powershell in the command in place of sh e.g. `kubectl exec -i -t -n default win-webserver-8648d6f7b8-g6jzm -c windowswebserver "--" powershell`

**Why is this needed**:
To support MS Windows Pods

**Environment you are Lens application on:**

- Kubernetes distribution: EKS
- Desktop OS: MacOS

**Comment by jakolehm** [comment]
Fixed in #136.

**Comment by dmitarb** [comment]
@jakolehm Is it possible to also add for MacOS which uses the command pwsh to start Powershell?
