### ISSUE TITLE
Lens never quits on macOS Catalina 10.15.7

### ISSUE THREAD

**Issue by aairom** [lensapp/lens#1021]
When I want to quit and close Lens application on my Mac by Lens/Quit Lens menu, the app never quits. I still see the Lens app icon as running and I'm ought to use the "force quit" action.

**Comment by andrei-dascalu** [comment]
I'm also on 10.15.7, but can't see this happening. Lens > Quit, right click > Quit, they work.

**Comment by piotrgo** [comment]
Lens does not quit for me too. Doesn't even show "Force quit". I have to kill the app either from Activity Monitor or terminal.
MacOS: 10.15.7
Lens: 3.6.7
Electron: 9.1.2
Chrome: 83.0.4103.122

**Comment by aairom** [comment]
> Lens does not quit for me too. Doesn't even show "Force quit". I have to kill the app either from Activity Monitor or terminal.
> MacOS: 10.15.7
> Lens: 3.6.7
> Electron: 9.1.2
> Chrome: 83.0.4103.122

so this is a pattern. I uninstalled and reinstalled and still the same.

**Comment by zheli** [comment]
Same here :( Always have to force quit Lens on Catalina.

**Comment by ruizmarlon** [comment]
If you recently did that upgrade please confirm that lens has access to the kube.yml.  Catalina changed security settings and this may be the cause.  IMHO Lens can't access the kube.yml file any longer which causes it to stay stuck on "connecting".

I opened this issue after my upgrade to Catlina: https://github.com/lensapp/lens/issues/1316

**Comment by Nokel81** [comment]
Is this still an issue on 4.1.4? I am on catalina and quitting Lens does what I expect it to do.

**Comment by dindurthy** [comment]
Definitely still an issue. I've gotten used to force quitting from activity monitor, but it won't exit otherwise. I'm on 10.15.7 and using Lens 4.2.4.

**Comment by Nokel81** [comment]
@dindurthy Can you post a video of you trying to quit lens using `Lens > Quit`?
