### ISSUE TITLE
Lens web version

### ISSUE THREAD

**Issue by magusd** [lensapp/lens#1037]
**What would you like to be added**:
I'd like to be able to budnle lens inside my cluster as a web app alongside other good stuff like prometheus and grafana.

**Why is this needed**:
1 - I've got data sensitive on-prem clusters that do not expose an endpoint to the internet and firewall rules are super strict. 
2 - My dev environment is kubernetes based, so I'd like to enable my developers to easily see stuff inside kubernetes without much knowledge
3- Kubernetes dashboard is not nearly as good an option, but will be the default if this is not possible

**Environment you are Lens application on:**
production, staging, development

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
https://k3s.io/

- Desktop OS: docker, web app

**Comment by staser** [comment]
Good to have =)

**Comment by matti** [comment]
here you go https://github.com/supervisor-com/lens-web

**Comment by edgora-ai** [comment]
> here you go https://github.com/supervisor-com/lens-web

Great work, It is a desktop version run in a docker, is it possible to run a native html in browser?

**Comment by miskun** [comment]
We (Team Lens) have no plans to support web browsers with Lens. If there is a need for something like that, we suggest to look at workarounds like https://github.com/supervisor-com/lens-web instead. Or use other solutions designed for web browsers.

**Comment by tommy-couzens** [comment]
Anyone have something that has had a commit in the last 6 years?
