### ISSUE TITLE
Cluster Warnings panel reports "No Issues Found" when not connected

### ISSUE THREAD

**Issue by codytrey** [lensapp/lens#104]
**Describe the bug**
When on the Cluster page, the Warnings section changes to "No Issues Found" if cluster is disconnected for some reason

**To Reproduce**
1. Go to Cluster Overview
2. Cause network disconnect (reboot k8s master, disconnect client networking, etc)
3. See error

**Expected behavior**
Should report that is not connected to the cluster

**Environment (please complete the following information):**
- Lens Version: 2.6.5
- OS: Windows 10 Version 1803

**Comment by jakolehm** [comment]
I think this is already fixed.
