### ISSUE TITLE
Switch fast to all-namespaces

### ISSUE THREAD

**Issue by yagilm** [lensapp/lens#1040]
**What would you like to be added**:
Easily go back to "all-namespaces". (maybe "uncheck all namespaces", or "all namespaces")

**Why is this needed**:
When selecting a/some namespace(s) to perform a task or check someting you need to uncheck them all to go to the default (all-namespaces). When working with many namespaces you would need to scroll endlessly and uncheck everything.

**Environment you are Lens application on:**
- Kubernetes distribution: multiple
- Desktop OS: Linux, Gnome

**Comment by ixrock** [comment]
@yagilm you can do it easily, just click to `Filtered` + `Reset`:

![image](https://user-images.githubusercontent.com/6377066/95320426-1f6ea080-08a2-11eb-910b-9577bcb7cc0e.png)

**Comment by yagilm** [comment]
Oh my.. totaly missed that.
thanks @ixrock and thanks @lens_team!

**Comment by adammw** [comment]
This wasn't clear for me as well especially when the "currently applied filters" is hidden by default, any reason not to have "All namespaces" in the dropdown menu?
