### ISSUE TITLE
3.6.7 Fails to Connect to EKS [breaking]

### ISSUE THREAD

**Issue by bpatton00** [lensapp/lens#1048]
Simply put 3.6.7 MacOS fails to connect to EKS Clusters.  

-  double checked all kubeconfig's etc  
-  rolled back to 3.6.5 and it works fine.

**Comment by nevalla** [comment]
Do you get some error?

**Comment by bpatton00** [comment]
Nothing of note, I think eventually it popped up with a connection failure but currently using the older version and unable to take time to reproduce sorry.  We are EKS 1.17 if that helps.

**Comment by ruizmarlon** [comment]
@bpatton00 did you try using the kubeconfig from a terminal to make sure you can reach the cluster outside of AWS?

**Comment by ruizmarlon** [comment]
@bpatton00 Tested with lens MacOS `3.6.7` eks `v1.17.9-eks-4c6976` and it worked.  I am using an aws account that does not require a session token.

**Comment by bpatton00** [comment]
I checked again, same issue.  You can see it spinning above and the kubectl cli showing that it is indeed connected just fine.
![image](https://user-images.githubusercontent.com/16670262/95636509-fb9f8c00-0a54-11eb-912e-6f3473102490.png)

reinstalled version 3.6.5 and working
![image](https://user-images.githubusercontent.com/16670262/95636672-5638e800-0a55-11eb-8275-c6d04b2129c7.png)

**Comment by ruizmarlon** [comment]
Thank you for providing that info.

**Comment by rafilkmp3** [comment]
how you can choose AWS credentials to enable lens auth to EKS ?

**Comment by midN** [comment]
Seeing same issue for the past month

**Comment by midN** [comment]
I can confirm this has been fixed for me in 3.6.9

**Comment by jakolehm** [comment]
@midN thanks for the update! Let's close this as it seems to be fixed.

**Comment by bpatton00** [comment]
Yes, it is corrected -- apologies as I thought I had already closed it for you.
