### ISSUE TITLE
Add LimitRange in the configuration section

### ISSUE THREAD

**Issue by zenkraker** [lensapp/lens#1057]
**What would you like to be added**:
I like to have a new field inside the configuration section, where I can visualize and modify my LimitRange kind.
**Why is this needed**:
There are Quotas but LimitRange adds more flexibility in the resources management

**Environment you are Lens application on:**

- Kubernetes distribution: AKS
- Desktop OS: Lens for Windows

**Comment by Nokel81** [comment]
Limit Ranges are present under the configuration section. If you are not seeing them it is because your cluster doesn't have rbac permissions to list them.
