### ISSUE TITLE
How do we update Cluster Metrics feature?

### ISSUE THREAD

**Issue by shinebayar-g** [lensapp/lens#106]
1. Lens is shipped with custom prometheus stack. In case of there is update available (hope you'll maintain these images right?) how do we update those stack?

2. What's the correct way to update prometheus stack values? Let's say I modified this prometheus stack values quite heavily (requests, limits, volumes, args, configmaps etc). What would happen when there is new update available and update?
Will my edited values overwritten? If that's the case, we'd need edit values option before installation, instead of single "Install" button.

**Comment by matti** [comment]
I think you should install your own prometheus there and configure lens to use it. I'd consider this built-in thing as "demo"

**Comment by jnummelin** [comment]
>  how do we update those stack?

Once we bundle more recents prom stack versio into the app, there'll be a "Upgrade" button in the cluster settings.

>  Let's say I modified this prometheus stack values quite heavily (requests, limits, volumes, args, configmaps etc). What would happen when there is new update available and update?

As there's currently no mechanisms in the app to customize the prometheus stack, you'd get all the modifications overwritten. Sounds like you probably are better of with running prometheus via Helm chart or the prometheus operator. Prom operator allow probably the best ways to customize the stack.

> I'd consider this built-in thing as "demo"

Demo might not be the right word, but it is intended for people to get started easily. The end result of that is pretty close what you'd get with the stable Helm chart without any customizations.

**Comment by shinebayar-g** [comment]
Thanks for the answers folks!

**Comment by jnummelin** [comment]
Closing as the questions has been answered.
