### ISSUE TITLE
Lens Hangs on Preferences Page

### ISSUE THREAD

**Issue by jim-docker** [lensapp/lens#1060]
**Describe the bug**
Lens becomes unresponsive while interacting with Kubectl Binary fields. I've seen this twice but cannot easily reproduce. Before it hangs, the "Download kubectl binaries" checkbox begins selecting and deselecting repeatedly, on its own, without user participation.

I've also noticed that the default directory and path strings (placeholder) in the "Directory for binaries" and "Path to Kubectl binary" fields are not selectable or editable, but do disappear when you start typing.

**To Reproduce**
Unknown. Activities before the hang include adding 3 clusters from default kubeconfig, browsing for an icon for one of the clusters, opening terminals in 2 of the clusters (and running `kubectl version`), drag and drop the cluster icons, then open the Preferences page and click on the "Directory for binaries" field, and other kubectl relevant fields

**Expected behavior**
always be responsive

**Environment (please complete the following information):**
- Lens Version: 3.6.7
- OS: OSX
- Installation method: dmg 
 
**Additional context**
logging this bug so it is documented. Could be impacted by changes according to #1059

**Comment by Nokel81** [comment]
Could be related to some desync between the renderer and main loading and unloading the user store. Causing both to repeatedly try and save their own version and then read back a different one.

**Comment by Nokel81** [comment]
Have you seen this recently? Those components have recently been refactored, so I think we can probably close this.

**Comment by rmoreas** [comment]
I just installed the latest version and it's still an issue. Not possible to change directory for binaries.

**Comment by Nokel81** [comment]
Oh I think this will be fixed in 5.2 because of https://github.com/lensapp/lens/pull/3616

**Comment by jakolehm** [comment]
Closing because #3616 should have fixed this.
