### ISSUE TITLE
Failed to create endpoint for service lens-metrics/kube-state-metrics: endpoints "kube-state-metrics" already exists

### ISSUE THREAD

**Issue by viceice** [lensapp/lens#1061]
**Describe the bug**
When install lens metrics i get the following kubernetes warning: `Failed to create endpoint for service lens-metrics/kube-state-metrics: endpoints "kube-state-metrics" already exists`. Using k3s v1.18.9+k3s1 on ubuntu 18.04.5.

**To Reproduce**
1. connect to k3s cluster
2. Click on cluster settings
3. Install metrics feature
4. Close settings
5. refresh cluster dashboard
6. see warning

**Expected behavior**
No such warning on install.

**Screenshots**
![image](https://user-images.githubusercontent.com/1798109/95551818-cae73480-0a0b-11eb-95de-3630c75c1b28.png)

**Environment (please complete the following information):**
- Lens Version:3.6.7
- OS: Windows Server 2016
- Installation method (e.g. snap or AppImage in Linux): `cinst lens`
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
no logs
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
Is this still a problem with 4.1.4? It seems like metrics is still working for you.
