### ISSUE TITLE
Refactor cluster metadata detection away from cluster class

### ISSUE THREAD

**Issue by nevalla** [lensapp/lens#1069]
Now cluster object is resolving every kind of metadata from the Kubernetes cluster (distribution, node count etc). Would be nice to refactor these out of cluster object so we could have different kind of detectors that will store metadata for the cluster.

For example we could have different detectors that will detect different Kubernetes distributions, or the infrastructure where the cluster is running. In future these detectors can come also from extensions, so every cloud provider could write them own detectors. 

Detector detects single metadata for the cluster, for example is the cluster AWS EKS cluster. If it detects that the cluster is an EKS cluster it will return `distribution=eks` metadata. If it does not detect the specific thing, it does not return any metadata.

Detector registry contain all detectors and it will run all detectors agains cluster periodically. It will store results to metadata property for the cluster in cluster store.

**Comment by Nokel81** [comment]
So this would imply that the detectors are responsible for knowing the name of the metadata. This does raise a question related to merging of metadata fields. If one has a detector that produces `{ "name": "foobar", value: 5 }` and another detector that produces `{ "name": "foobar", value: 6 }` what should the registry store into the cluster store?

**Comment by Nokel81** [comment]
Does it makes sense for the metadata to be in the cluster store or in a separate store? Not all things that require clusters need access to the metadata (iirc).

**Comment by nevalla** [comment]
> So this would imply that the detectors are responsible for knowing the name of the metadata. This does raise a question related to merging of metadata fields. If one has a detector that produces `{ "name": "foobar", value: 5 }` and another detector that produces `{ "name": "foobar", value: 6 }` what should the registry store into the cluster store?

I think we can create some priorities, for example in tree detectors will have higher priority. Then we just need to choose is the first or the last the winner. If extension wants to detect something and use later that information in other part of the extension I think we should encourage to use some sort of naming convention.

**Comment by Nokel81** [comment]
My biggest concern would be for something like distribution since I remember talking about having different distributions being detected by different detectors.

**Comment by nevalla** [comment]
Even we store the values with different name, we still want to display detected distribution in cluster settings. So eventually we have to decide what is the most relevant value. So not going to lock the end solution here, but we need to some mechanism to filter distribution out from cluster metadata.

**Comment by nevalla** [comment]
Fixed in #1106
