### ISSUE TITLE
User Mode Enhancement

### ISSUE THREAD

**Issue by shinebayar-g** [lensapp/lens#107]
**What would you like to be added**:

Just noticed, if I install **User Mode** in cluster settings, non-admin users will be able to see see all namespaces. This is basically exposing all namespaces in my cluster thus ruining my multi tenancy. I'd suggest instead of exposing list namespace api, we could use namespace option in kube config file.

```yaml
- context:
    cluster: development
    namespace: frontend
```

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...] Pharos 1.14.9
- Desktop OS: <the OS Lens app runs on in your case> Ubuntu 18.04.3 LTS

Edit: Just tested namespace field when importing kubernetes config. It's working.

**Comment by jakolehm** [comment]
> Edit: Just tested namespace field when importing kubernetes config. It's working.

Yes, it should work. Closing this as "User Mode" really needs to grant list namespaces rights (note: Lens only shows namespaces where user has access to).

**Comment by shinebayar-g** [comment]
> (note: Lens only shows namespaces where user has access to).
But `kubectl` doesn't.
