### ISSUE TITLE
Cluster Health Charts and Node Panel Do Not Load in 2.6.6 

### ISSUE THREAD

**Issue by DavidHoerster** [lensapp/lens#108]
**Describe the bug**
I upgraded from 2.6.2 to 2.6.6. Afterwards, Lens does not display my AKS cluster (K8s version 1.15.3) "Cluster" charts (Master/Worker CPU/Memory) or the Nodes panel. All that is displayed is the rotating circle icon. I have another AKS cluster (1.14.8) and it loads fine. I have more pods deployed to the 1.15.3 cluster and the 1.15.3 cluster also has two node pools associated with it.

I want Lens to display all of the information for my 1.15.3 cluster as it does for my 1.14.8 cluster. It used to work prior to upgrading to 2.6.6. Even uninstalling and then installing the older 2.6.2 does not work for the 1.15.3 cluster. (I'm assuming there's still something hanging around

**To Reproduce**
1. Open Lens running version prior to 2.6.6
2. Notice will pop up stating a new update will install on restart
3. Restart Lens; update will kick in
4. Connect to already connected K8s cluster (mine is running 1.15.3) and some panels either take a long time to load or never load (like Nodes and Cluster).

**Expected behavior**
I expect all panels and charts to load in a reasonable amount of time

**Screenshots**
![image](https://user-images.githubusercontent.com/782317/70282424-ba32b600-178b-11ea-820b-9731780ce4e6.png)

**Environment (please complete the following information):**
- Lens Version: 2.6.6
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): MSI
 
**Logs:**
No logs

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
 // don't think it's this as I'm able to connect via kubectl to my clusters without issue

```

**Additional context**
n/a

**Comment by jakolehm** [comment]
@DavidHoerster does both clusters have similar Prometheus setup?

**Comment by stevehipwell** [comment]
I'm seeing the same thing on EKS (K8s v1.14.7). The metrics panel is showing *Metrics not available at the moment* and the usage value on **CPU** & **Memory** is *N/A* while **Pods** usage is set to *0*.

**Comment by DavidHoerster** [comment]
> @DavidHoerster does both clusters have similar Prometheus setup?

Interesting, but the cluster that isn't rendering *does* have Prometheus set up. The other cluster that does render everything does not have Prometheus set up.

**Comment by rbudiharso** [comment]
I'm having this problem too. Also on EKS with kubernetes version v1.14.7.

**Comment by camilb** [comment]
This fixed the issue for me: https://github.com/lensapp/lens/blob/master/troubleshooting/custom-prometheus.md

**Comment by sudaxl** [comment]
Have a similar problem .Instructions at https://github.com/lensapp/lens/blob/master/troubleshooting/custom-prometheus.md 
are not clear where ot make changes for a custom Prometheus installation

**Comment by nevalla** [comment]
Lens should detect installed prometheus automatically. Please re-open if this is still the issue.
