### ISSUE TITLE
use other label for nodeshell feature

### ISSUE THREAD

**Issue by breizh5729** [lensapp/lens#1091]
**Describe the bug**

i would like use a node shell feature but actualy a node shell use an settings with 
nodeselector = kubernetes.io/hostname and not match because it's not exactly a name of the server. 

actually this label is already set and i don't want to overwrite it for several reasons. 

is't possible to use an other label for the nodeselector.

**Comment by koshkin-ccna** [comment]
Bumping the issue. This is a case for EKS node group instances which already have labels like "kubernetes.io/hostname=ip-10-420-1-86". 
Node-shell pod fails with error message  " didn't match node selector'"

`Event: node-shell-2d8831c4-ab11-4999-82aa-d2320a186cc4.1646ba4bc28ac239
Created
32s ago (2020-11-12T09:59:11Z)
Name
node-shell-2d8831c4-ab11-4999-82aa-d2310a186cc4.1646ba4bc28ac239
Namespace
kube-system
Message
0/3 nodes are available: 3 node(s) didn't match node selector.
Reason
FailedScheduling
Source
default-scheduler
First seen
0s ago
Last seen
0s ago
Count
Type
Warning`

**Comment by Nokel81** [comment]
closing in favour of #1857
