### ISSUE TITLE
Support for Helm Prometheus Stack

### ISSUE THREAD

**Issue by reski-rukmantiyo** [lensapp/lens#1095]
**What would you like to be added**:
Currently i've been using this stack since it's already pass stable and official from prometheus-community.

**Why is this needed**:
I dont one more component (lens prometheus) for function that already there

**Environment you are Lens application on:**
Using Lens for Windows

**Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]**
Using K8s v1.18 with Kubespray

**Desktop OS: <the OS Lens app runs on in your case>**
Windows 10

**Comment by kkreso** [comment]
Lens already supports pre-installed Prometheus, try changing the settings for your cluster:

![image](https://user-images.githubusercontent.com/12595159/96372196-1c0ecb00-1166-11eb-9326-d7c5f77c3883.png)

**Comment by bunjamins** [comment]
It does work, but with the depricated helm prometheus-operator install, autodetect worked.  Now with the current prometheus-stack install autodetect doesn't work, tried on both 4.1.4 and the latest alpha.

**Comment by bunjamins** [comment]
I suppose I could also mention that the setting that works for me (where prometheus-stack was installed in default namespace) is default/prometheus-operated:9090

so i think the service name is what changed, to "prometheus-operated" if that helps

edit: the prometheus operator query format still works

**Comment by Nokel81** [comment]
Closing as it now is reported to work.
