### ISSUE TITLE
[Feature] Add function find logs inside logging screen

### ISSUE THREAD

**Issue by PhanSon95** [lensapp/lens#1099]
**What would you like to be added**:
- Find text available inside logging POD

**Why is this needed**:
- When number of lines log is too big (100k lines) , when I want to find information which debug on application , but to find that line which print log , I have to scroll, scroll and scroll until see that log by eyes
- If have find feature, It will be easier to handle logging

**Environment you are Lens application on:**
- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: MacOS

**Comment by mznet** [comment]
@PhanSon95 I really need this feature. I had to use `kubetctl` and `grep` commands to find the lines which i was looking for instead lens. Lens will be more fantastic if find feature will be implemented.

**Comment by aleksfront** [comment]
@PhanSon95 @mznet Search logs feature already implemented, feel free to try this out! We need your feedback.
It's available in beta releases of Lens 4.0.0 https://github.com/lensapp/lens/releases and will also be in stable RC version.

Log search preview
![airflow logs](https://user-images.githubusercontent.com/9607060/99487836-3a8c0000-2978-11eb-957c-5104396ce506.png)

**Comment by mznet** [comment]
@aleksfront I downloaded the beta version and just checked the feature. That's really cool. But it could be better to filter lines i'm looking for like `grep`. The filtering feature specfically would be more effective when monitoring specific request coming in nginx log.

**Comment by aleksfront** [comment]
@mznet Such filtering are also on the todo list for log improvements as well as few others. Stay up to date!
