### ISSUE TITLE
run lens on master by default

### ISSUE THREAD

**Issue by matti** [lensapp/lens#11]
for example when doing a cordon+drain and lens happens to be on the same node --> boom.

lens is critical to pharos cluster management and I think it should be on master by default.

**Comment by chrisjohnson** [comment]
It seems like the namespace should have first-class treatment in the UI, as a dropdown right in the top of the window. The namespace filter in the resource lists could be removed in favor of a top-level one (i.e. if you change namespace in the top, the resource list will update to match).

This would influence the namespace used in the terminal windows as well as any actions you perform such as your scenario of cordon+drain. It would also apply to the "Overview" tab, filtering all the metrics and events by namespace chosen.
