### ISSUE TITLE
Stale resources

### ISSUE THREAD

**Issue by creckord** [lensapp/lens#1110]
**Describe the bug**
Since a couple of releases ago (my guess would be since 3.6.0, but I didn't really track this), Lens frequently shows outdated resource states.

Just today I wanted to check some pods to see if they were updated. Lens was already running and connected to the cluster, but in a different view. I changed over to the Pods view and filtered by namespace to see the pods in question.

In the overview table, they showed up as running 54w. Clicking on each of the pods gave me the same info, as well as a running image version of 10.x.x. The reality was however that the pods were recreated 11h ago and ran with a new image version 11.x.x. When I realized that through kubectl and switched back to Lens, the state in the still open Pods view had adjusted to the correct values.

I've seen similar issues with all kinds of resources - services, pvcs, various crds (such as traefik ingressroutes, elasticsearch, ...).

**Environment (please complete the following information):**
- Lens Version: 3.6.6
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): Chocolatey

**Comment by matti** [comment]
#1100

**Comment by matti** [comment]
#1100

**Comment by creckord** [comment]
> #1100

Good to know that I'm not alone. It's not just the Pods view for me though...

**Comment by matti** [comment]
yeah it's not, I was just using pods as an example since my video showed that. it's *all* the resources.

**Comment by matti** [comment]
also posting the video from the another issue here https://www.youtube.com/watch?v=AFKR80qHD8g&feature=youtu.be
