### ISSUE TITLE
Add ability to change default editor when launching embedded terminal (or add vim/emacs key bindings?)

### ISSUE THREAD

**Issue by kcalmond** [lensapp/lens#1115]
**What would you like to be added**:
A user preference for which editor is launched when opening up the embedded editor: vim, emacs, etc.

**Why is this needed**:
Let's users use the editor they are most comfortable/efficient with. 

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
All
- Desktop OS: <the OS Lens app runs on in your case>
All

**Comment by Nokel81** [comment]
Currently we don't actually launch an editor (per se). We use an in-browser editor: https://ace.c9.io. Though we might switch to the one that VScode uses.

**Comment by Nokel81** [comment]
We have switched to monaco.
