### ISSUE TITLE
Display cluster names in the cluster vertical bar

### ISSUE THREAD

**Issue by afeblot** [lensapp/lens#1119]
**What would you like to be added**:

I would like cluster names to be displayed below cluster icons (or as a replacement of cluster icons) in the cluster vertical bar. 
If multiple mode are to be supported, an option might be added to select how this is displayed (only icon, only name, both icon+name)

**Why is this needed**:

As mentioned in #1011, icons are super cool, but when having more than a couple clusters, finding the proper one is painful with only icons, as you can only hover over each icon to display its name until you find the proper cluster.

**Environment you are Lens application on:**

Not relevant, I think.

**Comment by Andrei-Paul** [comment]
Even some initials overlaid on the icon would help.
They could be generated from the cluster context name or optionally imputed by the user.

**Comment by Nokel81** [comment]
Fixed by #2153

**Comment by Nokel81** [comment]
We now, by default, display a short form of entity names for icons. And with https://github.com/lensapp/lens/issues/3498 you will be able to specify an alternative short name. Will those two things be good enough?

**Comment by afeblot** [comment]
I think they will.
Thanks a lot.

**Comment by Nokel81** [comment]
Excellent, I will close this request then and you can follow that linked issue for any updates.
