### ISSUE TITLE
Add any custom repo helm chart

### ISSUE THREAD

**Issue by pomazanbohdan** [lensapp/lens#112]
Add any custom repo helm chart

**Comment by jakolehm** [comment]
This should be already possible via helm cli.

**Comment by pomazanbohdan** [comment]
> This should be already possible via helm cli.

In 3.0.0?

**Comment by jakolehm** [comment]
I think since 2.7.0.

**Comment by sT331h0rs3** [comment]
`helm env` used in [helm-repo-manager.ts](https://github.com/lensapp/lens/blob/master/src/main/helm-repo-manager.ts) only works for Helm 3.
@jakolehm, probably it would be better to try to parse `helm repo list` after `helm env` failed, WDYT?

**Comment by jakolehm** [comment]
> `helm env` used in [helm-repo-manager.ts](https://github.com/lensapp/lens/blob/master/src/main/helm-repo-manager.ts) only works for Helm 3.
> @jakolehm, probably it would be better to try to parse `helm repo list` after `helm env` failed, WDYT?

Lens currently supports only Helm3. Not sure how we could support both Helm2 and Helm3 easily.

**Comment by bhanuc** [comment]
The IDE can also have an integrated search ui, which could be just a wrapper over https://hub.helm.sh and once a chart is installed, it could have a simple info view(with links to their respective pages in the UI) and a simple uninstall button. I can volunteer for the work if required.

**Comment by pomazanbohdan** [comment]
I meant the option, the text box for the URL with the add button, and let this add to the ENV

**Comment by gbritton** [comment]
> The IDE can also have an integrated search ui, which could be just a wrapper over https://hub.helm.sh and once a chart is installed, it could have a simple info view(with links to their respective pages in the UI) and a simple uninstall button. I can volunteer for the work if required.

The latest UI appears to implement much of this, though the ability to add a custom helm repo doesn't seem to be there.  From the Preferences, you can add repos from the hub, and from the main UI in the "charts" view, you can search all configured repos.  It would perhaps be better if there were a way to either jump to this preference or otherwise manage configured repos from the chart view (and perhaps limit searches to a selected repo, though that's a separate issue).

I would expect the the resolution of this issue to be: ability add a helm repo by typing a name + URL in the UI, and perhaps a clarifying labale in the UI that the dropdown list of available repos comes from the Hub.  Workaround (as described above) is to add the repo with helm via the command line.

**Comment by mudged** [comment]
From the point of view of companies with private internal Helm Repositories - it would be nice to be able to add a custom Helm Repo. These are sometimes secured so there would be need to be a way of adding credentials as well.

Alternatively, could the UI reuse the configured repos (with credentials) from the Helm tool? This way it wouldn't have to manage credentials itself.

**Comment by DesistDaydream** [comment]
> > The IDE can also have an integrated search ui, which could be just a wrapper over https://hub.helm.sh and once a chart is installed, it could have a simple info view(with links to their respective pages in the UI) and a simple uninstall button. I can volunteer for the work if required.
> 
> The latest UI appears to implement much of this, though the ability to add a custom helm repo doesn't seem to be there. From the Preferences, you can add repos from the hub, and from the main UI in the "charts" view, you can search all configured repos. It would perhaps be better if there were a way to either jump to this preference or otherwise manage configured repos from the chart view (and perhaps limit searches to a selected repo, though that's a separate issue).
> 
> I would expect the the resolution of this issue to be: ability add a helm repo by typing a name + URL in the UI, and perhaps a clarifying labale in the UI that the dropdown list of available repos comes from the Hub. Workaround (as described above) is to add the repo with helm via the command line.

`ability add a helm repo by typing a name + URL in the UI` is a very good way.
The dropdown list is also a good experience

**Comment by Nokel81** [comment]
![Screen Shot 2021-03-23 at 3 43 58 PM](https://user-images.githubusercontent.com/8225332/112208310-9698b680-8bee-11eb-8c38-41e1c5460605.png)

This is currently possible. Has been since #1368

**Comment by cmar0027** [comment]
> This is currently possible. Has been since #1368

This is not working for me, I'm smashing the Add button but nothing happens. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/52538393/205516452-c1705191-d580-4798-9615-2ab4aa988802.png)

**Comment by Nokel81** [comment]
@ChristianMarchetta that is a bug that was fixed in https://github.com/lensapp/lens/pull/6692

Release should go out tomorrow (Monday) with the fix.
