### ISSUE TITLE
How to refresh (without reload the full page)?

### ISSUE THREAD

**Issue by fzyzcjy** [lensapp/lens#1126]
**What would you like to be added**:
Give a button/hotkey to refresh, i.e. re-fetch the latest state. Currently I only find "reload" in the menu which will restart the whole app. But I want something that will only fetch the latest state of the currently viewing pod/service/...

**Why is this needed**:
After some operations, we want to see whether it works. By manually triggering refresh, we can know the latest situation.

**Environment you are Lens application on:**

- Kubernetes distribution: not related
- Desktop OS: macos

**Comment by Nokel81** [comment]
Reloading just actually restart the whole app, just the view. We are working to improve the refresh rate of data, while balancing not loading too often and bogging down large clusters.

**Comment by fzyzcjy** [comment]
@Nokel81 Thanks for the reply!

> while balancing not loading too often and bogging down large clusters.

A specific case that is very often happened: We deployed some resources which create some pods (say, a Deployment). Then we want Lens to frequently refresh, because we want to know it as soon as its readiness probe is ok. However, Lens seems to only refresh for at least half a minute or a minute. Thus, we have to manually refresh over and over again to see the latest update.

In addition, IMHO, creating a "refresh" button (only re-fetch the data) may not be too hard ;) Just add a few lines of code: Instead of call `fetchTheData` periodically, just call it manually.

This seems not to have been addressed, so maybe this issue open?

**Comment by Nokel81** [comment]
Lens uses the kubernetes watch apis (except for initial load). So unless your kubernetes distro stops sending back updates I don't think that Lens could get changes faster. If you have a specific example (with video would be great) then a full bug report would be most appreciated.

**Comment by fzyzcjy** [comment]
@Nokel81 Aha interesting! I will observe whether force refreshing makes it faster or not, and will report a bug if so.
