### ISSUE TITLE
Incorrect memory and CPU usage report for nodes

### ISSUE THREAD

**Issue by pieterclaerhout** [lensapp/lens#113]
**Describe the bug**

When you look at the memory usage for the nodes in a cluster, the calculated percentages seem to be incorrect (especially when compared to the output of `kubectl top nodes`).

In our cluster, we have 3 nodes having 8 GB of RAM memory each.

When you look at the output of `kubectl top nodes`, it reports the following:

```
NAME                          CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
twx-weu-cluster02-pool-wtnl   532m         13%    4334Mi          55%       
twx-weu-cluster02-pool-wtnn   452m         11%    4749Mi          60%       
twx-weu-cluster02-pool-wtnx   438m         10%    3390Mi          43%       
```

If you open the node details in Lens (or the node list), you'll see that the percentages shown under memory are showing something different…

**To Reproduce**
1. Go to Nodes
2. Check the memory usage for a node
3. Compare that with the output of `kubectl top nodes` and see that they are showing different values…

**Expected behavior**

I would expect the values to be same in both cases…

**Screenshots**

<img width="1573" alt="Screenshot 2020-01-02 at 14 31 43" src="https://user-images.githubusercontent.com/74731/71669350-ac615800-2d6c-11ea-9997-47652c324563.png">

<img width="2152" alt="Screenshot 2020-01-02 at 14 28 30" src="https://user-images.githubusercontent.com/74731/71669349-abc8c180-2d6c-11ea-8cd8-4866d28abd89.png">

<img width="1573" alt="Screenshot 2020-01-02 at 14 31 56" src="https://user-images.githubusercontent.com/74731/71669351-ac615800-2d6c-11ea-9235-81546a75847e.png">

**Environment (please complete the following information):**
- Lens Version: 2.7.0
- OS: OSX

**Comment by lindhe** [comment]
+1 I agree this is confusing.

For me, the CPU and memory usage is showing the requests for the pods, not the actual usage that `kubectl top` shows.

I vote that you change the title from "memory usage" to "CPU and memory usage"

**Comment by longwa** [comment]
For us, the nodes are VM's running on top of a physical ESXi node. Lens is showing the CPU and Memory of the underlying physical node instead of what is allocated to the kubernetes worker node. This causes the percentages to be way lower as the physical obviously has way more resources.

Running `kubectl top nodes` returns the correct numbers and percentages.

**Comment by Nokel81** [comment]
Related: #2097 

Attempted to be fixed in: #2098

**Comment by danderbury** [comment]
Any update on this?

**Comment by mcpappas** [comment]
FYI, I finally circled back on my PR #2098 when I saw there were others interested so hopefully it will make it into master soon.

**Comment by Nokel81** [comment]
fixed by https://github.com/lensapp/lens/pull/2098
