### ISSUE TITLE
Refactor PageRegistration to separate registries/interfaces

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#1130]
Currently we have single `PageRegistration` that does too many things. We should split this, for example:

- `GlobalPageRegistration` for global pages
- `ClusterPageRegistration` for in-cluster pages
- `ClusterMenuRegistration` for registering in-cluster menus

**Comment by ixrock** [comment]
@jakolehm what is "in-cluster menu"? I don't see that current `page-registry.ts` related to that somehow.. or is it something totally new?

**Comment by jakolehm** [comment]
> @jakolehm what is "in-cluster menu"? I don't see that current `page-registry.ts` related to that somehow.. or is it something totally new?

With "in-cluster menu" I meant something similar to `CLUSTER = "cluster-view-scope"`.
