### ISSUE TITLE
How to add a helm repo 

### ISSUE THREAD

**Issue by IJOL** [lensapp/lens#1133]
Hi All:

Nice software, very useful..

But (there is always a but) i don't understand how is supposed a new repo is added to be able to search for a chart, I only see the stable chart repo, which is good but nowhere as useful than others, I go to preferences page a try to add the a repo  but to no avail,  typingin the box doesn't finds anything, I remember from a previous install that there was a list of repos one can search.. but.. mine seems empty.. Any help will be aprecciatted i know is my lack knowledge, but wasted some many hours in this.. so better ask for help,

**Comment by nevalla** [comment]
Hi! Lens tries to fetch available Helm repositories from Helm hub and that does not work anymore (#1089). We will fix the issue in the next patch release (#1090). However, you can add helm repos also from the command line, so all repositories that are added manually should be available in Lens app too.

**Comment by Nokel81** [comment]
You can add custom helm repos in settings.

**Comment by dberardo-com** [comment]
is this still possible in the latest version ?

**Comment by Nokel81** [comment]
Yes
