### ISSUE TITLE
UI for enabling/disabling extensions

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#1134]
Lens needs an UI where user can enable/disable extensions. Note: extensions mentioned in Lens app package.json are always enabled.

UI should be accessible via "Lens -> Extensions" menu item (it should be after "Preferences").

**Comment by nevalla** [comment]
We should probably hide bundled extensions that are defined in package.json

**Comment by nevalla** [comment]
So on UI I think we are interested in extensions that are located in `localFolderPath` (~/.k8slens/extensions). All extensions that are located under that dir are enabled by default now. 

Most likely `ExtensionManager` class should have method that will return all extensions that are located in `localFolderPath`.
