### ISSUE TITLE
Lens hangs when click on the folder button when creating a new cluster

### ISSUE THREAD

**Issue by IJOL** [lensapp/lens#1135]
Hi.All:

When i try to create a new cluster by finding kubeconfig in the filesystem by clicking on the folder button, lens hangs badly, I need to restart the system to be able to use lens again, killing the seems to be not sufficient,and my Desktop suddenly changes to an empty one..

My system is ubuntu 16 with latest updates applied, I use standard ubuntu 16 desktop install

**Comment by nevalla** [comment]
is this happening on snap or appimage version?

**Comment by IJOL** [comment]
snap


Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega

**Comment by Nokel81** [comment]
Are you able to provide a gif of this happening?

**Comment by Nokel81** [comment]
Closing as that button no longer exists.
