### ISSUE TITLE
How Copy/Paste works in lens terminal windows

### ISSUE THREAD

**Issue by IJOL** [lensapp/lens#1139]
Hi, All:

When i open any kind of terminal inside Lens, local or remote, Copy/Paste doesn't work, neither using Ctrl-V nor didn't have as normal terminal windows a menu with paste command, so how can one avoid typing such long repositories names from lens..

**Comment by IJOL** [comment]
Gasp, just seen the edit menu, sorry for the noise

**Comment by spyro2000** [comment]
EDIT menu works, but STRG+V doesn't. Neither does right-click.

**Comment by JapuDCret** [comment]
@spyro2000 
CTRL+Shift+V works for pasting
CTRL+C works for copying

**Comment by emoxam** [comment]
In many [command-line interface](https://en.wikipedia.org/wiki/Command-line_interface) environments, control+C is used to [abort](https://en.wikipedia.org/wiki/Abort_(computing)) the current task and regain user control.
So it should not be ctrl+c. But copy on select will be great!

**Comment by denisbaca1** [comment]
SHIFT+Insert worked for me.

**Comment by hojiang-ssnc** [comment]
SHIFT+Insert worked for me, thanks @denisbaca1
