### ISSUE TITLE
S3 Link Down on Homepage

### ISSUE THREAD

**Issue by shyim** [lensapp/lens#114]
https://kontena-lens-desktop.s3-eu-west-1.amazonaws.com/Lens-Setup-2.7.0.exe

````
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>B0C5706D6DAC5D16</RequestId>
<HostId>
C2gvDx1CESEDPyHTFgMyGnCgQR8HR1OM1aemyXBRabwn5MbhVTL94ezs8oKfLwGCopTMt4s/U5I=
</HostId>
</Error>
```

**Comment by torjue** [comment]
Kontena has ceased operations: https://blog.kontena.io/farewell/

**Comment by danihodovic** [comment]
![image](https://user-images.githubusercontent.com/5557301/190502296-ae4a1972-9ee7-476c-a14b-0ce0df767d04.png)
