### ISSUE TITLE
Kontena has ceased operations. Any plans to open source Lens?

### ISSUE THREAD

**Issue by torjue** [lensapp/lens#115]
Kontena has ceased operations, as stated here: https://blog.kontena.io/farewell/.

Any plans to open source Lens?

**Comment by DaveSlinn** [comment]
Can anyone from Kontena update?

**Comment by miskun** [comment]
Hi all! At the moment we, ex team Kontena can not do anything. We are not allowed to touch the source code or compile anything from it. Now, we are trying to get legal rights to this source code so that we can a) make it open source to avoid this kind of situations in the future; and b) make it better (if we can; let's get rid of that login for starters). This is very annoying situation at the moment.

**Comment by DaveSlinn** [comment]
Thanks for the update @miskun!  Just knowing there is a plan is helpful.  Good luck!

**Comment by jicowan** [comment]
Totally bummed that Kontena has ceased operations.  Lens was (and is) and great tool for managing k8s clusters.

**Comment by DaveSlinn** [comment]
Same.  We've gone back to the standard kubernetes dashboard for now, but after having used Lens, it's just not as good.

**Comment by steveww** [comment]
I'm really missing Lens, please open source it. It was (is) the best tool for K8s.

**Comment by jicowan** [comment]
https://github.com/kubenav/kubenav is the closest thing that I've found so far.

**Comment by mozai** [comment]
If we're trading tips on alternatives, [kube-commander](https://github.com/AnatolyRugalev/kube-commander) gives a Midnight Commander / text terminal experience with "kubectl" as the only dependency.  Kontena Lens is still my first choice, but when I have to squeeze into a bastion host's text terminal to reach the cluster, kube-commander saves me much typing.

**Comment by kallisti5** [comment]
Kontena went out of business.   There are efforts to open source the Lens app... but it sounds like legally they can't yet.  (I'm not affiliated with Kontena, just a bystander)

You can download the app here:
https://github.com/kontena/lens/releases

The login doesn't work, you can hack around the broken login via:

* Library/Application\ Support/Lens/config.json (MacOS X)
* ./.config/Lens/config.json (Linux)

Set the following config.json:
```
{
	"lastSeenAppVersion": "2.7.0",
	"__internal__": {
		"migrations": {
			"version": "2.7.0"
		}
	},
	"preferences": {
		"colorTheme": "dark",
		"allowTelemetry": false
	},
	"token": "AAAAA",
	"user": {
		"username": "cooluser",
		"first-name": "",
		"last-name": "",
		"email": "myemail@gmail.com",
		"company": "google",
		"url": null,
		"location": "",
		"bio": "",
		"notifications": [
			"newsletter"
		],
		"is-partner": true,
		"user-avatar-src": "https://www.gravatar.com/avatar/9ed1e9439badc6b6034815e8219e3712",
		"verified": true,
		"is-customer": true,
		"lens-invitation-used": true
	},
	"eulaAccepted": true,
```

**Comment by cgunston** [comment]
In case anyone needs it, the config.json for Windows is here -

%appdata%/Lens/config.json

**Comment by ryedin** [comment]
Lens is by FAR the best UI based kube management app I've come across.

Open sourcing it, or hell, even make _just_ Lens a product would be really cool/smart/awesome (I'd pay $5-10/mo just for Lens, basically forever)

**Comment by ryedin** [comment]
@jicowan haven't seen kubenav before. Looks very similar to Octant, which I think is my #2 after Lens. 

The killer features in Lens are the easy multi-cluster management, quick access to pod-level logs, and the integrated shell experience for executing `sh` against a running pod really quickly (wonderful for troubleshooting). 

Octant has some of that (but not all), but also has one other really nice thing, which is instantly being able to create port-forwarding tunnels into pods in the cluster (again very nice for troubleshooting).

RIP Lens.

**Comment by Goodsmileduck** [comment]
When I was looking for such app to manage kubernetes, I wasn't able to find Lens. 

So I found a developer to start making such app. We finished our first alpha-beta-gamma version, so others also could try it, but don't expect much from it. It's only able to show resources, and delete them. But we going to develop as much as we can. And I actually need it in my own daily work. 

So just check it guys - https://kuberneto.com and let me know if you have comments or suggestions. Sorry app file is not signed and notarized yet, I'm going do that in next few days at least for MacOS.

P.S. I'm still using Lens, it's a nice app and we going to reuse some UI tricks from it.
P.P.S. I'm looking for junior js developer to load him with small tasks for app development. Drop me message if you are the one or you know someone.

**Comment by matti** [comment]
@ryedin what about https://www.infra.app ? what are your thoughts on it? (I think Lens is better)

**Comment by miskun** [comment]
Yes. There is plans to make Lens available again. More info on Kontena community slack channel. https://kontenacommunity.slack.com/archives/C1U90NQN8/p1583158112020800?thread_ts=1583158112.020800&cid=C1U90NQN8

**Comment by dacahill7** [comment]
Is there a better way to join the Slack to see that post than the link in the Readme? Since kontena.io is down, there isnt an easy way to join.

**Comment by jakolehm** [comment]
@dacahill7 try [this link](https://join.slack.com/t/kontenacommunity/shared_invite/enQtOTc5NjAyNjYyOTk4LWU1NDQ0ZGFkOWJkNTRhYTc2YjVmZDdkM2FkNGM5MjhiYTRhMDU2NDQ1MzIyMDA4ZGZlNmExOTc0N2JmY2M3ZGI)

**Comment by ryedin** [comment]
@matti haven't seen that one yet. I'll have to check it out. looks Lens-inspired. Does it have the shell integration? I find myself using that feature in Lens way more than I thought I was going to at first.

**Comment by ryedin** [comment]
@jakolehm thank you!

wonderful news

**Comment by alicetoreno** [comment]
@matti I've been following the 2 founders behind infra.app for many years. I've been their user since their first tool, Kitematic. I also helped them beta test when they started docker for mac. They've always managed to keep their app easy and simple.

**Comment by GranularSystems** [comment]
infra.app appears to be mac only though.

**Comment by strigona-worksight** [comment]
> infra.app appears to be mac only though.

https://twitter.com/InfraApp/status/1235248477560545281
>Hey! We do have plans for both Linux and Windows versions.

**Comment by miskun** [comment]
c&p from Kontena Community slack channel:
![image](https://user-images.githubusercontent.com/524154/76630496-cb3c5180-6548-11ea-9f1b-b504cde1cf9b.png)
Lens 3.0 will be released today / this weekend + it'll be 100% open source under MIT license.

**Comment by jakolehm** [comment]
Source code is now available: https://github.com/lensapp/lens
