### ISSUE TITLE
Bundle webpack/ts configuration to npm package

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#1153]
We should bundle "best-practice" webpack/typescript config to our npm package.

**Comment by chenhunghan** [comment]
I think this can be included in the generator template, I linked this issue to https://github.com/lensapp/lens/issues/1296

**Comment by chenhunghan** [comment]
The "best practice" webpack config is now bundled in the generator template, https://github.com/lensapp/generator-lens-ext/tree/main/generators/app/templates/ext-ts

There is no need to include in our npm?

**Comment by chenhunghan** [comment]
I will close this as was included in the commits to master already https://github.com/lensapp/generator-lens-ext/tree/main/generators/app/templates/ext-ts
