### ISSUE TITLE
Certificate expired ?

### ISSUE THREAD

**Issue by fgallese** [lensapp/lens#116]
While trying to use this application, I receive an error `RequestError: Error: certificate has expired`.

Sniffing on the network traffic, I can see that the application tries to connect with https://cloud-api.kontena.io/ which has an expired certificate (expired on Monday, January 13, 2020 at 9:41:04 AM).

**Comment by fgallese** [comment]
Nevermind, just saw the farewell message on the blog https://blog.kontena.io/farewell/ :(

**Comment by gadelkareem** [comment]
alternatives?

**Comment by webmutation** [comment]
:( so sad

**Comment by miskun** [comment]
Kontena Lens is available again. There is no need for sign-up or login anymore. All dependencies to Kontena Inc operated backend services have been stripped out. The project is also 100% open source under MIT license. The source code is released on Github at https://github.com/lensapp/lens and the latest version is available from https://github.com/lensapp/lens/releases

**Comment by vhscom** [comment]
> There is no need for sign-up or login anymore. [....] The project is also 100% open source [...].

That was true, for a while. But the information provided is no longer accurate.
