### ISSUE TITLE
Provide easy way for extensions to store files

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#1179]
Each extension should have their own "sandbox" where files are actually stored.

**Comment by Nokel81** [comment]
I think that this issue needs a bit more fleshing out as to the exact specifications.

Some questions that come to mind are:

1. How would an extension have access/create to these files? 
2. By "sandbox" does that mean that other extensions shouldn't be able to access them or even Lens itself?
3. Are these persistent files between restarts of the application?

**Comment by jakolehm** [comment]
1. Extension runs with the same privileges as Lens itself, basically it can write anywhere on the filesystem
2. It's not a real sandbox, just a folder where an extension can safely write without having to worry about messing other extensions
3. Yes

Basically we just need to provide convenience here.
