### ISSUE TITLE
Could not register, Website Down!

### ISSUE THREAD

**Issue by fscaptain** [lensapp/lens#118]
Try to use Kontena-Lens, but could not register, since Website ist Down

**Comment by bygui86** [comment]
ehi guys what's happening?
on the link kontena.io I found another website :(

**Comment by ebparkhub** [comment]
kontena is out of business, ceased operation.  check a few issues down for more details.  The summary is that there are workarounds to the registration it seems (haven't tried it personally), and while there is a legal hold on the source, the development team seems to be hoping that it will be liberated.

**Comment by miskun** [comment]
Kontena Lens is available again. There is no need for sign-up or login anymore. The project is also 100% open source under MIT license. The source code is released on Github at https://github.com/lensapp/lens and the latest version is available from https://github.com/lensapp/lens/releases

**Comment by loganbfisher** [comment]
This is amazing.  This tool is awesome you guys rock!!!!
