### ISSUE TITLE
Build script in hello-world-extension is incorrect for use with npm

### ISSUE THREAD

**Issue by stefcameron** [lensapp/lens#1198]
In the new hello-world-extension, the dev script is incorrect: Should be `npm run build -- --watch`, [see line 9](https://github.com/lensapp/hello-world-extension/blob/main/package.json#L9)

And I feel it would be much more intuitive to also have a `start` script, which could be `npm run dev` if you still want a `dev` script, or you could rename `dev` to `start`.

Then it's simpler: `npm start` to run the extension in "build watch" mode for development.

**Comment by stefcameron** [comment]
I would also recommend adding a `clean` script and redefining the `build` script:
```
"clean": "rm -rf ./dist",
"build": "npm run clean && webpack --config webpack.config.js"
```
You could also drop the `--config webpack.config.js` part in the `build` script since that's also the default config file Webpack looks for.

Webpack doesn't clean its output directory before (re)building, so it's best to make sure it's clean. Otherwise, you could end-up with old files in there that cause conflicts you don't expect.

**Comment by chenhunghan** [comment]
I don't have write permission to https://github.com/lensapp/lens-extension-samples so this is on hold, @jakolehm please help!
