### ISSUE TITLE
Lens must be restarted in order to load an extension for the first time

### ISSUE THREAD

**Issue by stefcameron** [lensapp/lens#1199]
The [your first extension](https://docs.k8slens.dev/latest/extensions/get-started/your-first-extension/) docs, as well as the README in the [hello world extension](https://github.com/lensapp/hello-world-extension), suggest that merely reloading the Lens window is enough to see the extension loaded.

But that's not the case with 4.0 alpha 2: Lens only seems to look at the `~/.k8slens/extensions` dir on start-up, and never again.

So when loading an extension for the first time, Lens must currently be restarted (quit the app, start it up again).

Once this is done, and the extension is updated, then it's only necessary to reload the Lens window (i.e. with `CMD+R`).

If it's a bug that Lens doesn't look for new extensions on window reload, then please fix that. Otherwise, please update the docs accordingly...

**Comment by Nachasic** [comment]
Thank you for submitting this issue! It looks like this was fixed in #1230
