### ISSUE TITLE
DX for extensions can be improved on "your first extension"

### ISSUE THREAD

**Issue by stefcameron** [lensapp/lens#1200]
The [your first extension](https://docs.k8slens.dev/latest/extensions/get-started/your-first-extension/) docs page has instructions that say you have to constantly copy/paste your repo into `~/.k8slens/extensions/some-dir` every time you make a change, and then reload the Lens window.

That's a bad DX, can be greatly improved, and actually works fine today (with 4.0 alpha 2) to make a symlink to the source/repo in the `~/.k8slens/extensions` directory, which gets around having to copy/paste build output constantly, especially when running the extension in `build --watch` mode, which is likely what you want to do when developing the extension.

So the steps would be:

1. Clone the extension repo anywhere on your system.
2. Go into `~/.k8slens/extensions` and create a symlink to your repo: `ln -s /src/my/repo my-extension`
3. In your repo direction from (1), start dev mode: `npm run dev` (which will watch for source changes and re-build).
4. Restart Lens to load the extension for the first time (see #1199 why Lens must be _restarted_, not just reloaded).

Now, every time you update source, just `CMD+R` in Lens to reload the window to see changes.

**Comment by stevejr** [comment]
@stefcameron - docs have been updated. Closing this issue.
