### ISSUE TITLE
Not able add two clusters with same name which are in two different subscriptions 

### ISSUE THREAD

**Issue by praveenadigoppula** [lensapp/lens#1205]
I have two clusters with same name but those are in two different subscriptions because of that i am not able to add two cluster side by side. i have to overwrite one after other. kindly let me the solution or workaround if it has any. thanks in advance

ex:-
Subscription Name:  **something1**
az aks get-credentials --resource-group "**abc-xyz-RG**" --name **abc-xyz-AKS**

Subscription Name:  **something2**
az aks get-credentials --resource-group "**abc-xyz-RG**" --name **abc-xyz-AKS**

Regards,
Praveen A.

**Comment by kgelinas** [comment]
this is more a Azure question but you can use multiple file
az aks get-credentials --resource-group "abc-xyz-RG" --name abc-xyz-AKS --file path.to.kube/config-US1
az aks get-credentials --resource-group "abc-xyz-RG" --name abc-xyz-AKS --file path.to.kube/config-US2
and use both file if the same name create issues in lens maybe use different workspace will work

**Comment by Nokel81** [comment]
Might be related to #200, I assume this is still a problem with 4.1.4?

**Comment by Nokel81** [comment]
Closing as this is an azure question and the solution is to use several files. Furthermore you should be able to use sync to have both clusters active at the same time.
