### ISSUE TITLE
Cluster Settings - Metrics feature link is incorrect

### ISSUE THREAD

**Issue by stevejr** [lensapp/lens#1210]
**Describe the bug**
The link under Cluster Settings -> Features -> Metrics is incorrect now that the extensions api branch has been merged into the master branch. 

The current link points to https://github.com/lensapp/lens/tree/master/src/features/metrics which does not exist anymore.

**Comment by bukowa** [comment]
Where is the correct link?

**Comment by malkir** [comment]
The only `01-namespace.yaml` appears to be the new metrics location under extensions, the URL should be updated to:

https://github.com/lensapp/lens/tree/master/extensions/metrics-cluster-feature/resources

**Comment by Nokel81** [comment]
This has been fixed by #1585
