### ISSUE TITLE
App crash applying an ingress

### ISSUE THREAD

**Issue by ayooki** [lensapp/lens#1223]
**Describe the bug**
I got an app crash log when trying to apply and ingress resource

**To Reproduce**
1. Go to 'Ingress'
2. Select and existing ingress and select edit
3. Paste the ingress yaml config then click Save & Close

**Expected behavior**
The ingress config should save or return an error if the config was incorrect

**Screenshots**
![image](https://user-images.githubusercontent.com/48291680/98113524-b3c92480-1e9b-11eb-8fa2-553215108e64.png)

**Environment (please complete the following information):**
- Lens Version: 3.6.7
- OS: Windows 10 version 1909
- Installation method (e.g. snap or AppImage in Linux): downloaded the msi from github
![image](https://user-images.githubusercontent.com/48291680/98113852-26d29b00-1e9c-11eb-868f-8a6ce0f4da5d.png)
 
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
Is this still a problem in 4.1.4?

**Comment by nicohouillon** [comment]
I can see the same error when editing Ingress Kind from `extensions/v1beta1` to `networking.k8s.io/v1`  
running Kubernetes 1.17 and Lens 4.2.4 on Windows 10 Home .

**Comment by Nokel81** [comment]
Fixed by https://github.com/lensapp/lens/pull/2426 which blocks editing the `apiVersion`
