### ISSUE TITLE
Option to install an extension from filesystem/url

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#1227]
Extension page should have a mechanism for installing an extension from local filesystem package or from an URL (both tar.gz npm packages)

**Comment by ixrock** [comment]
@jakolehm should we also consider option to "select a folder" installation with unpacked extension?
https://www.electronjs.org/docs/api/dialog#dialogshowopendialogsyncbrowserwindow-options (`openDirectory: true`)

**Comment by jakolehm** [comment]
> @jakolehm should we also consider option to "select a folder" installation with unpacked extension?
> https://www.electronjs.org/docs/api/dialog#dialogshowopendialogsyncbrowserwindow-options (`openDirectory: true`)

IMHO not needed, extension developers can still use `~/.k8slens/extensions/<folder>` .

**Comment by ixrock** [comment]
_Sneak-peak screenshots:_

<img width="1255" alt="Screenshot 2020-11-19 at 19 51 57" src="https://user-images.githubusercontent.com/6377066/99712039-30b6e980-2aab-11eb-9ca2-aee7b4696a04.png">
<img width="1255" alt="Screenshot 2020-11-19 at 19 52 04" src="https://user-images.githubusercontent.com/6377066/99712047-33b1da00-2aab-11eb-86a8-f2c39a5dc1c9.png">
<img width="1255" alt="Screenshot 2020-11-19 at 19 52 14" src="https://user-images.githubusercontent.com/6377066/99712051-34e30700-2aab-11eb-9a1a-2def3db3a121.png">
<img width="1147" alt="Screenshot 2020-11-19 at 21 06 14" src="https://user-images.githubusercontent.com/6377066/99712054-357b9d80-2aab-11eb-8a6c-18802262cdbe.png">
