### ISSUE TITLE
Specify a namespace to work with

### ISSUE THREAD

**Issue by a-b-v** [lensapp/lens#1229]
**What would you like to be added**:
I try to access k8s cluster with OIDC user with one permitted namespace, and lens show me nothing. Can I submit to lens working namespace similar to kubectl -n mynamespace?

**Why is this needed**:
Users without cluster-wide permittions can't use lens

**Environment you are Lens application on:**

- Kubernetes distribution: 1.19.3
- Desktop OS: Ubuntu 18.04

**Comment by aleksfront** [comment]
Relates to #702 
Relates to #486

**Comment by jakolehm** [comment]
Fixed in #702
