### ISSUE TITLE
Namespace selection dropdown enhancement

### ISSUE THREAD

**Issue by kavishdahekar** [lensapp/lens#1231]
**What would you like to be added**:
Regarding the dropdown that allows selection of a namespace : once you select a namespace its marked as "checked", but if you want to unmark it you have to scroll all the way to find it and click it again. Or I have to type and search for it again before clicking and unmarking it.
It would be easier if the selected namespaces are moved to the top of the dropdown so its easy to see which ones are selected and also easy to uncheck them.

**Why is this needed**:
Improve usability in cases where there are a large number of namespaces to deal with.

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...] EKS
- Desktop OS: macOS (Catalina)

**Comment by smark91** [comment]
Another enhancement would be to avoid reset the scroll of the namespace dropdown so it will be more easy to select multiple namespace adiacent.
Currently you need to scroll down all the time.

**Comment by aleksfront** [comment]
@smark91 The issue you described currently fixed and will be available in version 4.1.0.

**Comment by matglas** [comment]
Both the mention of @smark91 and the request from @kavishdahekar are not yet addressed.

**Comment by kavishdahekar** [comment]
Thanks for pointing it out @matglas.
@aleksfront I'm currently on 4.2.5 and I still see the issues I mentioned initially.
