### ISSUE TITLE
Shell not working if working directory not exists.

### ISSUE THREAD

**Issue by ossipsasha** [lensapp/lens#125]
**Describe the bug**
"Pod shell" and "Node shell" console hangs if terminal working directory not exists.

**To Reproduce**
1. Create "xxx" local directory
2. Go to cluster settings
3. Set "Terminal Working Directory" as "xxx"
4. Delete directory "xxx"
5. Go to nodes or pods. Select any and press "Exec" button
6. Console just hangs on "Connecting..."

**Expected behavior**
Probably it should use some default working directory.
Or show user friendly error to set proper working directory.

**Environment (please complete the following information):**
- Lens Version: 3.01
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux): Setup.exe

**Comment by Nokel81** [comment]
Tested this on macOS, also a problem there.

**Comment by Nokel81** [comment]
Furthermore it seems like the working directory option is used for both node shells, pod shells, and local shells. Which IMO seems like an over-site.
