### ISSUE TITLE
Isolate global styles from extensions

### ISSUE THREAD

**Issue by aleksfront** [lensapp/lens#1251]
Currently there are global styling affecting extensions, for example `cluster-manager.scss`
```
.ClusterManager main>* {
    position: absolute;
    left: 0;
    top: 0;
    right: 0;
    bottom: 0;
    display: flex;
    background-color: var(--mainBackground);
}
.ClusterManager main>*>* {
    flex: 1;
}
```
It provides unwanted side-effects for extension developers so they have no choice to overide some of them with a bunch of unnecessary properties with `!important` rule.

We need to find a way to isolate all global styling like layout, fonts and others from extension or provide necessary minimum amount of them.

**Comment by ixrock** [comment]
Maybe we should isolate extensions inside shadow-dom somehow?
https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM

**Comment by stefcameron** [comment]
> Maybe we should isolate extensions inside shadow-dom somehow?
> https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM

That's an interesting idea, however, while the Shadow DOM encapsulates styles defined within it so they don't leak out, it doesn't prevent external styles from affecting its internal elements. Here's a [sandbox](https://codesandbox.io/s/admiring-lalande-p4p2o) that implements a custom element that uses a Shadow DOM. The `styles.css` defines the body font as bold, and this affects the internal Shadow DOM elements.

**Comment by ixrock** [comment]
@stefcameron probably we must reset styles to prevent leaking from outside like this:

```scss
// top-root element
.MyExtension { 
  all: initial;  
  // all other styles below
 }
```
And don't forget to isolate styles for extension itself with `:host { inner extension's style } <-- this is loaded inside shadow-dom`

**Comment by aleksfront** [comment]
As @stefcameron mentioned in https://github.com/lensapp/lens/pull/1331#pullrequestreview-528334560 we should be responsible of isolating new styles to maximum level and get rid of selectors like `* >` etc. In that case only few basic ones described in `app.scss` would affect extensions and can easily be overwritten in rare cases.
@ixrock And there's no point of using shadow DOM for now at least, since it only encapsulates styles inside but not preventing global ones to affect inner contents.
