### ISSUE TITLE
Install metrics feature - Prometheus manifest link broken (404)

### ISSUE THREAD

**Issue by hkotka** [lensapp/lens#1253]
**Describe the bug**
On cluster settings view, under Features - Metrics, there is a link to preview Prometheus stack manifest file, but the link leads to 404 not found (https://github.com/lensapp/lens/tree/master/src/features/metrics).

**Screenshots**
![kuva](https://user-images.githubusercontent.com/1362650/98344729-57d9d980-201c-11eb-9fab-1615dfbe39e3.png)

**Environment (please complete the following information):**
- Lens Version: 3.6.7
- OS: Windows 10

**Comment by nevalla** [comment]
Correct link should point to https://github.com/lensapp/lens/tree/master/extensions/metrics-cluster-feature/resources

**Comment by oliverkane** [comment]
Just stopped to report I have this issue as well.  Searched, found this matching ticket, so I won't create another.  If I get time after dayjob today, I'll see if I can't patch this.

**Comment by dwaynebradley** [comment]
I just saw this in 4.0.0-rc.1 as well.
