### ISSUE TITLE
Extension package.json should describe publisher

### ISSUE THREAD

**Issue by nevalla** [lensapp/lens#1261]
Extension's `package.json` should describe `publisher` field which is used to identify the extension in the format of `@<publisher>/<name>`

**Comment by chenhunghan** [comment]
I think this can be included in the generator template, I linked this issue to https://github.com/lensapp/lens/issues/1296

**Comment by chenhunghan** [comment]
@nevalla this is included in the generator template https://github.com/lensapp/generator-lens-ext/blob/main/generators/app/templates/ext-ts/package.json#L5, this issue can be closed?

**Comment by jakolehm** [comment]
@chenhunghan what's the status here?

**Comment by chenhunghan** [comment]
@jakolehm it's included in the generator template https://github.com/lensapp/generator-lens-ext/blob/main/generators/app/templates/ext-ts/package.json#L5 I am not sure is this enough to close this.

**Comment by jakolehm** [comment]
I think this is "done" because both generator and extension anatomy docs have this information.
