### ISSUE TITLE
Export `@k8slens/extensions` for writing extension unit tests

### ISSUE THREAD

**Issue by chenhunghan** [lensapp/lens#1262]
**What would you like to be added**:

Export modules of `@k8slens/extensions` (currently has only `.d.ts`) for development/testing purposes only.

**Why is this needed**:

To be able to write unit tests for extensions.

Currently test throws

```
Cannot find module '@k8slens/extensions' from 'page.tsx'

Require stack:
 page.tsx
 page.test.tsx

> 1 | import { LensRendererExtension, Component } from "@k8slens/extensions";
```

**Comment by Nokel81** [comment]
I don't understand, is this meaning for in-tree extensions or other extensions? There is the `make build-extension-types` target which compiles the `@k8slens/extensions` package and vscode picks up the typings well enough for me.

**Comment by chenhunghan** [comment]
It's for other extensions. For extension developers to write test against their own extension.

**Comment by chenhunghan** [comment]
so, when I as an extension developer and has a component like this:

```tsx
import { LensRendererExtension, Component } from "@k8slens/extensions";
import { CoffeeDoodle } from "react-open-doodles";
import path from "path";
import React from "react"

export function ExampleIcon(props: Component.IconProps) {
  return <Component.Icon {...props} material="pages" tooltip={path.basename(__filename)}/>
}

export class ExamplePage extends React.Component<{ extension: LensRendererExtension }> {
  render() {
    const doodleStyle = {
      width: "200px"
    }
    return (
      <div className="flex column gaps align-flex-start">
        <div style={doodleStyle}><CoffeeDoodle accent="#3d90ce" /></div>
        <p>Hi world!</p>
        <p>File: <i>{__filename}</i></p>
      </div>
    )
  }
}
```

and want to unit test this component, I try to write test like this

```tsx
import React from 'react';
import { render } from '@testing-library/react';
import '@testing-library/jest-dom/extend-expect'

import { ExamplePage } from "./page";

test('two plus two is four', () => {
    const { container } = render(<ExamplePage extension={this} />);
    expect(container).toBeInstanceOf(HTMLElement);
});
```

The test throws 
```
Cannot find module '@k8slens/extensions' from 'page.tsx'
```

I think it's because `@k8slens/extensions` doesn't really export any modules, it has just `.d.ts`.

**Comment by chenhunghan** [comment]
Reopened because https://github.com/lensapp/generator-lens-ext/pull/13#issuecomment-732209669
