### ISSUE TITLE
Prometheus metrics not working on K8S 1.16.x+

### ISSUE THREAD

**Issue by jcardoso-bv** [lensapp/lens#127]
**Describe the bug**
Prometheus container/pod metrics are not correctly scraped when using Lens with an existing Prometheus server and a Kubernetes 1.16.x+ cluster.

**To Reproduce**
1. Go to Lens
2. Click on any pod
3. Scroll up to metrics and note that only limits/requests are displayed or no metrics at all

**Expected behavior**
Lens should show container/pods metrics on a Kubernetes 1.16.x+ cluster with a self-hosted Prometheus server

**Environment (please complete the following information):**
- Lens Version: 3.0.1
- OS: 10.14.6
- Installation Method: GitHub release
 
**Additional context**
I can fix Lens temporarily with the following Terminal workaround:

```
gsed -i 's/container_name!=/container!=/g' "/Applications/Lens.app/Contents/Resources/static/build/client/app.js"
gsed -i 's/pod_name=~/pod=~/g' "/Applications/Lens.app/Contents/Resources/static/build/client/app.js"
```

I would prefer this being an app fix/toggle depending on the detected Kubernetes cluster version.

**Comment by kodelint** [comment]
@jcardoso-bv I having the same issue. I tried your approach but no luck

**Comment by zeeZ** [comment]
To provide some more info, `pod_name` and `container_name` labels coming from the kubelet were deprecated in 1.14 in favor of `pod` and `container`, then removed in 1.16: https://github.com/kubernetes/kubernetes/blob/release-1.16/CHANGELOG/CHANGELOG-1.16.md#metrics-changes

**Comment by DarkBlaez** [comment]
Has this been addressed. I'm using K3os (k3s) and get the following on a fresh install of K3os/K3s and Lens

Metrics are not available due to missing or invalid Prometheus configuration.
Right click cluster icon to open cluster settings.

Thanks

**Comment by jcardoso-bv** [comment]
v3.3.1 has been released and this still hasn't been solved. What gives? Getting tired of using my workaround everytime Lens gets updated.
