### ISSUE TITLE
MacOS - "The application “Lens.app” can’t be opened."

### ISSUE THREAD

**Issue by richstokes** [lensapp/lens#128]
Anything special we need to do? It doesn't show up in the security preferences to override or anything 

MacOS ver 10.15.3

**Comment by TheKangaroo** [comment]
Edit: Actually the Lens-3.0.1.dmg worked for me. The Lens-3.0.1-mac.zip showed the `The application “Lens.app” can’t be opened.` message.

~~Same issue here. (Same MacOS Ver.)~~
:(

**Comment by jakolehm** [comment]
@richstokes could you test `.dmg` version?

**Comment by richstokes** [comment]
Yes sir. The .dmg version seems to work!

**Comment by jakolehm** [comment]
MacOS security features probably block the zip working from outside of "Applications" folder.

**Comment by richstokes** [comment]
I originally did copy the app from the zip to the Applications folder

**Comment by TheKangaroo** [comment]
@jakolehm yes same for me. I copied the unziped file to my Applications folder too, but it still did not work.

**Comment by miskun** [comment]
@jakolehm is there any benefit of serving the zip + dmg versions of Lens app?

**Comment by jakolehm** [comment]
In the past zip was easier for testing new versions but it seems that zip does not work anymore (with recent MacOS versions). We might wan't to drop zip from future builds.

**Comment by x3ro** [comment]
I ran into the same problem. Turns out the Lens binary in `Lens.app/Contents/MacOS` was not executable. After `chmod +x` it did start but macOS then reported that the app is damaged. This feels different from when macOS refuses to run something for security reasons. Could something have changed in your build process? 🤔 Or maybe macOS used to do some automatic fixing of apps that were somehow malformed.

(not that I particularly care about the zip version, I just downloaded it because it was the first in the list)

**Comment by vikas027** [comment]
[dmg](https://github.com/lensapp/lens/releases/download/v3.4.0/Lens-3.4.0.dmg) works fine on the latest Mac OS (10.15.5)

**Comment by Nokel81** [comment]
Furthermore, if you remove the `com.apple.quarantine` label then it reports:

```
dyld: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Users/nokel81/Downloads/Lens.app/Contents/MacOS/Lens
  Reason: no suitable image found.  Did find:
	/Users/nokel81/Downloads/Lens.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Users/nokel81/Downloads/Lens.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1
[1]    21765 abort      Contents/MacOS/Lens
```

I suggest we remove shipping the zip, or change it so that it is a zip of the dmg

**Comment by Nokel81** [comment]
Closing as we are no longer hosting zip's
