### ISSUE TITLE
Crash on Disconnect 4.0.0 Alpha 4

### ISSUE THREAD

**Issue by webmutation** [lensapp/lens#1289]
version 4.0.0 alpha 4 upon disconnecting from a cluster it throws the following error.

![image](https://user-images.githubusercontent.com/761367/98583640-fa1bea80-22c4-11eb-8cb9-c6839b40f718.png)

**Comment by matti** [comment]
#1333

**Comment by jakolehm** [comment]
Should be fixed in #1414
