### ISSUE TITLE
Cant load prometheus metrics on portable mode

### ISSUE THREAD

**Issue by webmutation** [lensapp/lens#1290]
Since I cannot run the installer due to having no permissions in corporate laptop I unzip the application into a folder where I have permissions. I am able to connect to the cluster, however I am not able to get any metrics with the following error

```
[EXTENSION-LOADER]: can't load extension main at C:\Users\duartda\AppData\Roaming\Lens\node_modules\lens-metrics-cluster-feature\dist\renderer.js: Error: Cannot find module 'C:\Users\duartda\AppData\Roaming\Lens\node_modules\lens-metrics-cluster-feature\dist\renderer.js'
Require stack:
- electron/js2c/renderer_init
```

**Comment by webmutation** [comment]
It would seem that the path is not relative in this case, would it be possible to make the path relative?

**Comment by Nokel81** [comment]
Lens requires access to the roaming folders to persist data. So I am pretty sure you will need access to that to even run Lens.
