### ISSUE TITLE
Unable to use Checkbox component in a repeating list

### ISSUE THREAD

**Issue by stefcameron** [lensapp/lens#1293]
I believe there's a bug with using the Checkbox component (in an extension) in a repeating list because the [Checkbox](https://github.com/lensapp/lens/blob/70a8982c9f6396107f92aeced465620761d90726/src/renderer/components/checkbox/checkbox.tsx#L39) does not apply the `key` prop to its root element. Instead, it just spreads ALL props on its inner `<input>`.

I have defined my list like this:
```jsx
      <CheckList className="flex column gaps">
        {clusters.sort(compareClusters).map((cluster) => (
          <Component.Checkbox
            key={cluster.id}
            label={`${cluster.namespace} / ${cluster.name}`}
            disabled={addingClusters}
            checked={isClusterSelected(cluster)}
            onChange={(checked) => handleClusterSelect(checked, cluster)}
          />
        ))}
      </CheckList>
```

The result is a list of checkboxes, but their checked/unchecked state is off. It doesn't match what the data says it should be.

If I swap the Checkbox component for a plan "checkbox" input:
```jsx
      <CheckList className="flex column gaps">
        {clusters.sort(compareClusters).map((cluster) => (
          <label key={cluster.id}>
            {`${cluster.namespace} / ${cluster.name}`}
            <input
              type="checkbox"
              checked={isClusterSelected(cluster)}
              onChange={(event) => handleClusterSelect(event.target.checked, cluster)}
            />
          </label>
        ))}
      </CheckList>
```

Then the checkboxes work with state as expected. Note the `key` prop is on the `<label>`, not the `<input>`...

**Comment by stefcameron** [comment]
If I'm correct about this, then this issue likely applies to many more Lens components that destructure props in the same way...

**Comment by ixrock** [comment]
@stefcameron you should use `value={boolean}` instead of `checked={boolean}`

**Comment by stefcameron** [comment]
> @stefcameron you should use `value={boolean}` instead of `checked={boolean}`

Thanks, that worked. Unexpected, since checkboxes use the `checked` attribute, but I finally saw in the implementation of Lens' component that it passes `value` into `checked` internally. At first, it looked like the `key` was the issue, but in my test, I was setting `checked`, whereas `checked` on `Component.Checkbox` was resulting in `value=undefined` and messing-up the checked state (always `undefined` and therefore not in the DOM, and therefore default, which is always `false`).

**Comment by stefcameron** [comment]
Can't wait for the component documentation...

**Comment by ixrock** [comment]
@stefcameron best documentation is a source code :D

**Comment by stefcameron** [comment]
Touché 😉
