### ISSUE TITLE
Output List Control

### ISSUE THREAD

**Issue by ErykVoelkerKodiak** [lensapp/lens#1294]
I think it would be a good feature to allow users to change and update the information output lists. For example, I would like to include the node a pod is running on in the **Workloads > Pods** output. I would also like to be able to move list items around so that information more pertinent to my job role (IT Admin) could be closer to the pod name (e.g. node name, pod state, etc.).

**Comment by Nokel81** [comment]
Thanks for the request!

Node name is currently displayed. 

As for the other issues ASKs we have https://github.com/lensapp/lens/issues/601. I think we should also support being able to rearrange the order of the columns so I have opened https://github.com/lensapp/lens/issues/3884.

Finally there is also https://github.com/lensapp/lens/issues/709 which mentions Pod IPs, so if you are intersest you can follow that too (though it is blocked on resizing).
