### ISSUE TITLE
Ability to Silence or Clear Warnings

### ISSUE THREAD

**Issue by ErykVoelkerKodiak** [lensapp/lens#1295]
It would be nice to be able to clear or silence alarms and/or warnings that place a counter on the cluster icon. After one has checked on the issue and deemed that there is no action required (e.g. a node was rebooted), the counter is not cleared. This requires constant checking and could result in an issue being missed because the notifications are ignored.
![image](https://user-images.githubusercontent.com/56043419/98619157-80313480-22b7-11eb-9f07-ef3251435d0c.png)
![image](https://user-images.githubusercontent.com/56043419/98619241-b078d300-22b7-11eb-8320-fa633b6277aa.png)

**Comment by rsmets** [comment]
@ErykVoelkerKodiak if you go to the Events tab within the cluster you can remove the warnings (which result in the red counter icons) one by one. I am pretty sure this is what you are requesting?

**Comment by Nokel81** [comment]
Going to mark this as resolved since it is possible.
