### ISSUE TITLE
Lens unusable: connection to cluster closed seconds after being established

### ISSUE THREAD

**Issue by jrmyr** [lensapp/lens#1302]
**Describe the bug**
When I start Lens I get connected to the cluster and can browse around for about 20 seconds. Then, Lens looses the connection and shows an "ETIMEDOUT" error. Pressing the "Reconnect" button ends again with no connection and the "ETIMEDOUT" error.
When I restart Lens, I get connected, but again only for about 20 seconds.
This makes Lens unusable.
A reinstallation via brew cask did not fix the problem.

**To Reproduce**
The problem appears (also for a colleague) with version 3.6.7. I have no further information how to reproduce the issue with other installations as I don't know what might trigger this behavior.

**Expected behavior**
No connection closings to the cluster. :-) 

**Screenshots**
I attach a screenshot with the developer tools open. Maybe this can help. There are some connections with timeouts (though I don't understand what they are for):
![grafik](https://user-images.githubusercontent.com/11019052/98651441-8caaa100-233a-11eb-8656-e2bc328b29cb.png)

**Environment (please complete the following information):**
- Lens Versions: 3.6.7, 3.6.8, 4.0.0-alpha.4
- OS: MacOS Catalina 10.15.7
- Installation method: brew cask
 
**Logs:**
I don't know where I can get the logs from. :-/

**Kubeconfig:**
The config has not changed for weeks while the connection issues are new.

Please tell me what additional info you need / would like to have. I am happy to provide them.
Thanks in advance for your help.

**Comment by jrmyr** [comment]
Additional note: I tried to download an older version of Lens to overcome the issue. But Lens always updates itself to the latest version (3.6.7) which then has the issue again.

**Comment by jrmyr** [comment]
The issue is not solved in version 3.6.8 - I just cross-checked. Other tools like `kubectl` or `k9s` still work with the same clusters.

**Comment by nevalla** [comment]
Please could you tell more about the kubernetes cluster, what distro do you use and what is the authentication method?

**Comment by jrmyr** [comment]
I log via user/client-certificate. The login itself seems not the problem as it works for some seconds.
```
-->  ku version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:05:26Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

For the distro I will come back to you ASAP.

**Comment by jrmyr** [comment]
Now I got the info: it's vanilla Kubernetes v1.15.10

**Comment by jrmyr** [comment]
Meanwhile it seems the problem are either due to a bad internet connection or misconfigured network routes.

However, it would be interesting to know more about the failed connections (see screenshot); some details might help for future investigations.

**Comment by Nokel81** [comment]
Is this related to #1022? Namely, do you have a antivirus that might be blocking the connection?

**Comment by jrmyr** [comment]
@Nokel81: Maybe. Meanwhile it's working again and I can't cross-check with my setup back than as I am using Big Sur and Lens 4.X.X now.
