### ISSUE TITLE
kube.yml exception handling, file has been removed or is not found

### ISSUE THREAD

**Issue by ruizmarlon** [lensapp/lens#1316]
**Describe the bug**
If the kube.yml is deleted or is no longer reachable Lens is not aware.  It appears to try to connect to an endpoint that has no configuration.

**To Reproduce**
1. Add cluster using `kube.yml`
2. Click on newly added cluster to verify connectivity
3. Close Lens and it should gracefully quit
4. While Lens is not running, delete the `kube.yml`
5. Re-launch cluster and click on the cluster recently added
6. Observe the permanent connecting graphic, it should never get past this screen
7. Quit Lens it will not quit
8. Try adding a new cluster File->Add Cluster (see screenshot for java error)
9. Force quit Lens
10. Re-launch Lens
11. Remove cluster associated with missing kube.yml
12. Quit->Force Quit
13. Re-launch Lens and all is well again

**Expected behavior**
Expect that Lens will have a defense for situations where the kube.yml is not found/reachable and alert the user of the condition. This condition should not impact the usage for the app or other clusters.

**Screenshots**

![connecting](https://user-images.githubusercontent.com/43421777/98747764-2fd4d800-2386-11eb-89d6-a18a08cfdf01.gif)

<img width="416" alt="java_error_add_cluster" src="https://user-images.githubusercontent.com/43421777/98746735-0dda5600-2384-11eb-9069-4ce9a30c37cd.png">

**Environment (please complete the following information):**
- Lens Version: 3.8.6
- OS: [e.g. OSX]  MacOS 10.15.7 (19H15)
- Installation method (e.g. snap or AppImage in Linux): Image
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Uncaught Exception:
TypeError: Object has been destroyed
    at De.navigate (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:110727)
    at s (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:107355)
    at click (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:108106)
    at MenuItem.click (electron/js2c/browser_init.js:65:1624)
    at Function.executeCommand (electron/js2c/browser_init.js:73:1102)
```
**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
N/A
```

**Additional context**
In my case I upgraded to Catalina OS and the security file access permisions changes were most likely the cause IMHO.

**Comment by Nokel81** [comment]
@nevalla I have figured out the source of this bug but I would like some feedback on what I should do to mitigate it.

Options that I have come up with:

1. Remove the cluster and display an error the user with what has happened.
2. Don't remove the cluster, but put it into a "do not connect" mode and then notify the user
3. Just notify the user and let the error and loading screen act as the "do not connect" mode.

Personally I am leaning towards number 2 as it is the least destructive while still preventing `type errors` and `UnhandledPromiseRejectionWarning` from showing up (which in the future would quit the program)

**Comment by nevalla** [comment]
Yes. I'm thinking the same. The Ideal end result would be that user will know what is wrong and he or she has option to fix the issue or remove the cluster manually.
