### ISSUE TITLE
Lens metrics

### ISSUE THREAD

**Issue by thomas-nesser** [lensapp/lens#1332]
**Describe the bug**
Using Lens to install Prometheus, but no metrics is shown. 

**To Reproduce**
1. Install metrics

**Expected behavior**
See the metrics

**Screenshots**
![image](https://user-images.githubusercontent.com/1116444/98816435-f3a68380-2428-11eb-8cbb-1165468c40ab.png)

Opening Prometheus from pod:
![image](https://user-images.githubusercontent.com/1116444/98816809-7e877e00-2429-11eb-8806-9eb512de9793.png)

**Environment (please complete the following information):**
- Lens Version: 3.6.7
- OS:  Windows 10
- Installation method (e.g. snap or AppImage in Linux): 
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
From Developer Tools:
{"cpuUsage":{"status":"RequestError: Error: socket hang up","data":{"result":[]}},"cpuRequests":{"status":"RequestError: Error: socket hang up","data":{"result":[]}},"cpuLimits":{"status":"RequestError: Error: socket hang up",......}}}
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**
The environment is Azure Kubernetes Services (1.18.8). Lens worked before we had to upgrade the cluster. Have tried to uninstall metrics and reinstall. Changed from "Auto detect" to "Lens" and back again.

**Comment by Nokel81** [comment]
Is this still a problem with 4.1.4?

**Comment by thomas-nesser** [comment]
No, it started working again in 4.1.2 I think. Did a remove and install of metrics.

**Comment by Nokel81** [comment]
Thanks for the response.

**Comment by marghidanu** [comment]
Nope, this is not working in 5.3.4.

**Comment by Nokel81** [comment]
@marghidanu Please open new issues instead of commenting on old closed ones.
