### ISSUE TITLE
sort statefulset pods from 0 to .....n

### ISSUE THREAD

**Issue by matti** [lensapp/lens#134]
1. scale statefulset to 10
2. see pod-0, pod-1, ..., pod-10
3. scale statefulset to 1000
4. see pod-0, pod-1, pod-10, pod-100, pod-101.....

imo would make sense to "keep" the sort and not do it lexiographically

screenshot related:
![Lens](https://user-images.githubusercontent.com/3893/76878766-f5aa4980-687d-11ea-9b94-4da0bc018e73.png)

**Comment by matti** [comment]
https://github.com/lensapp/lens/blob/4aaf470c18900fffed25abaddf3523556b1ec11e/dashboard/client/components/%2Bworkloads-pods/pods.tsx#L75-L84

**Comment by Nokel81** [comment]
I think just properly handling names of the form `^[0-9]+.*$` and `^.*[0-9]+$` would be the best solution.
