### ISSUE TITLE
Enforce semicolons via eslint rules

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#1349]

**Comment by Nokel81** [comment]
Should this be separate or should it be also fixed in #730 ?

**Comment by panuhorsmalahti** [comment]
We can fix this is in a piecemeal fashion as that PR has been open for quite a long time.

**Comment by Nokel81** [comment]
Probably a better idea, maybe each change should be a single PR. I'll close that one.

**Comment by nevalla** [comment]
Fixed by #1450
