### ISSUE TITLE
terminal always connecting state...

### ISSUE THREAD

**Issue by fanux** [lensapp/lens#137]
![image](https://user-images.githubusercontent.com/8912557/76933325-d36d0600-6927-11ea-8e38-fb5d3c0303de.png)

The board is work fine except the terminal.

Always at connecting state, can't use..

**Comment by nevalla** [comment]
Please could you elaborate your environment:
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux):

**Comment by fanux** [comment]
MacBook Pro (15-inch, 2017)  10.14.6
Using the release page dmg file to install.

**Comment by nobodybut** [comment]
me too！

**Comment by cherishs001** [comment]
me too!

**Comment by nevalla** [comment]
Please could you tell the Kubernetes version of the cluster. Just wondering could the issue be that Lens is not able to fetch the correct kubectl binary.

**Comment by nobodybut** [comment]
1.14.5，when I upgrade to 1.15.5，it's work!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Lauri Nevala"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月25日(星期三) 下午2:43
收件人:&nbsp;"lensapp/lens"<lens@noreply.github.com&gt;;
抄送:&nbsp;"陈泰名"<hackersilent@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [lensapp/lens] terminal always connecting state... (#137)





 
Please could you tell the Kubernetes version of the cluster. Just wondering could the issue be that Lens is not able to fetch the correct kubectl binary.

**Comment by nevalla** [comment]
Tested this with Minikube and Kubernetes 1.14.5. On the first run of terminal, Lens app will download correct version of kubectl binary and user will see `connecting...` but after the download is finished terminal will become active. How long did you wait the terminal to become active?

**Comment by fanux** [comment]
@nevalla some user in China can't access to the download addr I think..

**Comment by nobodybut** [comment]
aha,I can access anywhere.Even though I am in China......

**Comment by fanux** [comment]
@nobodybut yeah, but not everyone luckily as you

**Comment by jakolehm** [comment]
I think we should either a) automatically detect fastest mirror b) make mirror user configurable.

At least Azure provides a kubernetes mirror in China: http://mirror.azure.cn/kubernetes/

**Comment by jakolehm** [comment]
Azure.cn mirror does not have `kubectl` binaries for MacOS 😢

**Comment by iazunna** [comment]
I have this same issue on MacOS, how do i fix it? I have tried installing the latest version yet it does the same thing
