### ISSUE TITLE
Support context-sensitive cluster page menu item extensions

### ISSUE THREAD

**Issue by stefcameron** [lensapp/lens#1375]
The Extensions API should support context-sensitive cluster page menu items.

For example, only showing (and/or enabling) a menu item based on a condition, which could be anything interesting, including:

- the state of the cluster,
- the type of cluster,
- the origin (i.e. vendor) of the cluster,
- etc.

**Comment by jakolehm** [comment]
I think this is already possible, see related documentation PR https://github.com/lensapp/lens/pull/1422.

**Comment by Nokel81** [comment]
This seems to be now considered a bug (see #1422 )

**Comment by stefcameron** [comment]
@jakolehm 
> I think this is already possible, see related documentation PR #1422.

I don't really see that as _obvious_ in #1422. That PR is showing me how to react to an observable property, but there's also the other piece of whether or not Lens will remember extra metadata I might add (can I even add extra metadata?) to a cluster object I add into the store -- between quit and restart too -- such that after a restart, when my extension loads, and a cluster gets selected, that metadata is still there.

If this is also already handled by Lens, it would be really important to point out. Otherwise, I feel like the only way I could add context-sensitive cluster menu items is if I had clusters anew every time I load Lens, because that's the only way my extension can come to know that a cluster with a specific ID is indeed a "special" cluster.

Or my extension would have to store all that state itself.

Either way, I think this is an important piece of the puzzle that many will be wondering about, and should be clearly documented somewhere.

**Comment by Nokel81** [comment]
So this is not possible, and needs to have some design work attached to it. See my comment (https://github.com/lensapp/lens/issues/1432#issuecomment-733039997)

**Comment by stefcameron** [comment]
@Nokel81 Thanks for the update. `LensRendererExtension.isEnabledForCluster()` from #1489 is a step in the right direction, however neither does it, nor does #1432, address the metadata part of the problem. Now I can have my extension decide if it's cluster pages should be enabled for a given cluster, however, unless my extension is the one that added that cluster, and therefore knows about it -- and has also used its own custom "way" of storing metadata for that cluster -- my extension _still_ cannot reliably decide whether it should be enabled for that cluster or not. I suppose it can be left up to an extension to store its cluster metadata somewhere on disk, but for light-weight metadata associated with the primary object type in Lens (the cluster), it seems a bit heavy-handed.

Unless, of course, there's already a way of doing this with custom properties in the kubeconfig file already saved on disk that Lens seems to read at least once after every app restart. (I'm not an expert on kubeconfig files, so looking for advice here, not making a suggestion...) And if this is the case, does Lens load the custom properties into its `Cluster` object that gets passed to `isEnabledForCluster()` such that an extension could access them, or is the extension left to parse and read the kubeconfig on its own, and can the path be determined from the Cluster object?

**Comment by Nokel81** [comment]
The way we are planning on supporting this is having the extensions set up their own stores and this is already supported.

**Comment by stefcameron** [comment]
> The way we are planning on supporting this is having the extensions set up their own stores and this is already supported.

Are you saying there's no work to be done for this? I'm not sure how to interpret your statement. 😄  Today, can an extension set up its own stores, and are those stores saved by Lens and restored _somehow_? Is that documented somewhere?

**Comment by Nokel81** [comment]
Yes that is correct an extension can set up its own stores. The guide is not there yet (see https://docs.k8slens.dev/latest/extensions/guides/stores (which currently 404s)). 

The [custom-reasource-page](https://github.com/lensapp/lens-extension-samples/blob/master/custom-resource-page/src/certificate-store.ts) example extension uses the `KubeObejectStore` but there is also the [ExtensionStore](https://docs.k8slens.dev/latest/extensions/api/classes/_core_api_stores_.extensionstore/).

**Comment by Nokel81** [comment]
The above docs aren't very good yet but we are working on them.

**Comment by jakolehm** [comment]
@stefcameron @Nokel81 ExtensionStore is also used in the telemetry extension: https://github.com/lensapp/lens/blob/master/extensions/telemetry/src/telemetry-preferences-store.ts

**Comment by jakolehm** [comment]
@stefcameron extension can also store metadata to `cluster.metadata` .

**Comment by stefcameron** [comment]
OK, this is sounding good! Glad to know the team is working on the store-related docs.

So just by adding stuff to `cluster.metadata`, does that automatically get persisted by Lens in the cluster store, or does an extension still have to create its own store?

**Comment by Nokel81** [comment]
@stefcameron Nope, `cluster.metadata` is automatically persisted. We don't guarantee that we won't override items in metadata that extensions store there. But if you prefix your keys with something long and unique to your extension it should™️ be fine.

**Comment by Nokel81** [comment]
Closing as this is now possible using #5800
