### ISSUE TITLE
It is hard to distinguish names in the Workspaces menu.

### ISSUE THREAD

**Issue by matthewhembree** [lensapp/lens#1378]
**What would you like to be added**:
Add distinguishing colored text or icons to the Workspaces menu.

**Why is this needed**:
I have uniform naming for my workspaces (CSP region). This makes the text shapes very similar. When combined with the low contrast grey on grey text, it's very hard to read and identify a particular workspace at a glance. Mirroring the benefits of the colorful cluster icons would be helpful.

**Environment you are Lens application on:**

- Kubernetes distribution: EKS, GKE, AKS, KOps
- Desktop OS: MacOS

Thanks!

**Comment by Nokel81** [comment]
This is related to an unsupported version of Lens. Please open a new issue if this continues to happen with the latest (4.1.4) version.
