### ISSUE TITLE
Add Ready status column in the Deployment view

### ISSUE THREAD

**Issue by rajivml** [lensapp/lens#1385]
HI,

While viewing the deployment, can you please add Ready status as well, because right now lens shows all the pods as Running even though they are not ready yet (0/1) 

![image](https://user-images.githubusercontent.com/46923567/99178226-eba35800-2736-11eb-93d9-4bae267d2649.png)

![image](https://user-images.githubusercontent.com/46923567/99178233-f9f17400-2736-11eb-9123-b38ace08b11e.png)

**Comment by vshakirova** [comment]
Hi. I'm going to implement this feature if you don't mind 😊
