### ISSUE TITLE
Issue with quit the lens

### ISSUE THREAD

**Issue by janavenkat** [lensapp/lens#1391]
**Describe the bug**
A trying to quit the lens in normal way it doesn't work i have to do force quit in Activity manager everytime

**To Reproduce**
1. Open Lens
2. press command + Q to quit the lens it suppose to quit lens but it doesn't

**Expected behavior**
It will quit the lens

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 3.6.8
- OS: MacOS big sur (even this happen before in earlier MacOs )

 
![lens](https://user-images.githubusercontent.com/28565699/99236144-19e86c80-27f7-11eb-87b6-bf00ed1bd73d.png)

**Comment by nevalla** [comment]
We have changed the closing behavior in `v4.0.0` where application will be closed with force, so this should not be issue there anymore (closing with force introduced some other issues though).

**Comment by ixrock** [comment]
@nevalla what the new issues in `v4`? 

By default in `v4` app is not closed fully with `Cmd+Q` (when tray isn't disabled in the app setting, if so => possible to close with `Cmd+Q` (from window focus). 
Otherwise from top menu `Lens -> Quit App` and/or from tray-menu when enabled).

**Comment by matti** [comment]
I've been force quitting my lens for last 3-4 weeks now.

**Comment by jakolehm** [comment]
@matti did you see this also in 4.0.0 alpha/beta?

**Comment by nevalla** [comment]
> @nevalla what the new issues in `v4`?
> 
for example https://github.com/lensapp/lens/issues/1356 and https://github.com/lensapp/lens/issues/1333

**Comment by janavenkat** [comment]
after updating to new version `3.6.9` its work's fine
