### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by JadeQin** [lensapp/lens#1393]
**Describe the bug**
when I open the app, it shows a error and can not open the main windows.

**Screenshots**
![image](https://user-images.githubusercontent.com/1001227/99255788-652e6980-284f-11eb-8fd7-5fe5b6b6b80c.png)

**Environment (please complete the following information):**
- Lens Version: 3.6.8
- OS: OSX 11.0.1

**Comment by nevalla** [comment]
Thanks for reporting this. Something seems to block connection to Lens backend. I think we need to verify this is not any Big Sur issue.

**Comment by JadeQin** [comment]
> Thanks for reporting this. Something seems to block connection to Lens backend. I think we need to verify this is not any Big Sur issue.

I found that when I open proxifier.app，it will show the error.

**Comment by vandreykiv** [comment]
With proxifier app it shows that connection to localhost refused. Anyway
profixier is not very stable on big sur but even without it it still
not working

**Comment by Nokel81** [comment]
Related to #1022. Closing in favour of #2390.
