### ISSUE TITLE
Configured namespaces are not reloaded into main cluster view

### ISSUE THREAD

**Issue by juv** [lensapp/lens#1396]
**Describe the bug**
Hi, I am currently trying out https://github.com/lensapp/lens/pull/702

When I add namespaces in the settings tab and switch back into the main cluster view, I can not see the list of namespaces which I added. Right-clicking the cluster, disconnecting and reconnecting does not fix this issue. What helps is to restart the Lens application entirely.

**To Reproduce**
1. Go to a cluster settings page
2. Add a few namespaces
3. Go back to the main cluster view or disconnect from the cluster and reconnect
4. Configured namespaces are not visible in the drop-down menu
5. Close Lens entirely and restart
6. List of configured namespaces in the main cluster view is now correct

**Expected behavior**
Namespace list will be updated once the settings are changed

**Environment (please complete the following information):**
- Lens Version: 4.0.0-alpha5
- OS: [e.g. OSX] Windows 10
- Installation method (e.g. snap or AppImage in Linux): Github binary download

**Comment by Nokel81** [comment]
Fixed by #2193
