### ISSUE TITLE
Add params field to page registration (extension api)

### ISSUE THREAD

**Issue by jim-docker** [lensapp/lens#1399]
As of 4.0.0-beta.3 if an extension developer wants to register a page that accepts parameters they must be added via route-path notation in the `id` field. Since navigating to a page with parameters is done by passing a TS object, like
```typescript
  extension.navigate(pageId: string?, params?: P)
```
or via the `target` field in a page menu registration
```typescript
      target: {
        pageId: "example/:exampleId",
        params: {
          exampleId: "456" // page-menu url: "/extension/lens-hello-world/example/456"
        }
      },
```
then it would be more natural to define a `params` object in the page registration, instead of via a route-path encoded in the `id` field.

Being able to specify the page and routing like this would free the developer from needing to know the route-path syntax (I presume most developers will only care about navigating to pages, optionally passing/receiving parameters, and don't care about the specific route path):
```typescript
export default class ExampleExtension extends LensRendererExtension {
  clusterPages: Interface.PageRegistration[] = [
    {
      id: "example",
      params: {
        exampleId: "0",
      }
      components: {
        Page: () => <ExamplePage extension={this}/>,
      }
    },
  ]
  clusterPageMenus: Interface.PageMenuRegistration[] = [
    {
      target: {
        pageId: "example",
        params: {
          exampleId: "456" // page-menu url: "/extension/lens-hello-world/example/456"
        }
      },
      title: "Example Extension",
      components: {
        Icon: ExampleIcon
      }
    }
  ]
}
```
`id` and `pageId` are simply ids when used in this context

This requires 
- adding an optional `params` field to the `PageRegistration` interface, through which each param can be defined and given a default value (perhaps an 'optional' flag?)
- adding logic under the hood to check for a `params` field and if one is specified then treat the `id` field as just an id and build the route-path onto it from the `params` field. If the `params` field is not present then treat the `id` field as (possibly) a route-path (current behaviour), for advanced users who need to control the route path specification.
- adding a method to `LensRendererExtension` to parse the url to retrieve the parameters so a page object can call it to easily get them (without needing to understand the route-path syntax) Maybe this already exists?

**Comment by jakolehm** [comment]
Moved to `4.1.0` milestone.

**Comment by stefcameron** [comment]
What I would add to this proposal is my suggestion for passing the params as props to the component that the page will render: https://github.com/lensapp/lens/pull/1651#discussion_r538678950
