### ISSUE TITLE
Workspace entry tab doesn't save workspace name

### ISSUE THREAD

**Issue by chenhunghan** [lensapp/lens#1404]
**Describe the bug**

Workspace entry tab doesn't save workspace name

**To Reproduce**
1. Go to 'Workspace entry' (left-bottom corner)
2. Click on 'Workspace'
3. Click on 'New Workspace'
4. Click on 'Save'
5. Doesn't save as expected

**Expected behavior**

Save workspace name

**Screenshots**

![Screen Recording 2020-11-17 at 11 32 11](https://user-images.githubusercontent.com/1474479/99344158-618bf880-28ca-11eb-9ce3-0bb595f7036c.gif)

**Environment (please complete the following information):**
- Lens Version: 4.0.0 beta.3
- OS: OSX Big Sur
- Installation method (e.g. snap or AppImage in Linux): Download .dmg
 
**Logs:**

from renderer process
```
mobx.module.js:1838 [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Reaction@383]' TypeError: e.toJSON is not a function
    at workspace-store.ts:210
    at Array.map (<anonymous>)
    at r.value (workspace-store.ts:210)
    at base-store.ts:85
    at mobx.module.js:2163
    at ce (mobx.module.js:775)
    at e.track (mobx.module.js:1809)
    at g (mobx.module.js:2162)
    at e.onInvalidate (mobx.module.js:2150)
    at e.runReaction (mobx.module.js:1775)
e.reportExceptionInDerivation @ Lens.js:2
2mobx.module.js:1838 [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Reaction@383]' TypeError: e.toJSON is not a function
    at workspace-store.ts:210
    at Array.map (<anonymous>)
    at r.value (workspace-store.ts:210)
    at base-store.ts:85
    at mobx.module.js:2163
    at ce (mobx.module.js:775)
    at e.track (mobx.module.js:1809)
    at g (mobx.module.js:2162)
    at e.onInvalidate (mobx.module.js:2150)
    at e.runReaction (mobx.module.js:1775)
```

**Additional context**

Error is from here https://github.com/lensapp/lens/blob/master/src/common/workspace-store.ts#L210

**Comment by aleksfront** [comment]
Duplicates #1403

**Comment by chenhunghan** [comment]
Duplicates #1403, closed this.
