### ISSUE TITLE
Do not generate new documentation version for "pre-releases"

### ISSUE THREAD

**Issue by msa0311** [lensapp/lens#1408]
**What would you like to be added**:
Add a check to GH-Action which ensures that the documentation is not generated for "pre-releases" after GA release of Lens 4.0.0.

**Why is this needed**:
Reduce the amount of visible tags in documentation to not confuse readers.

**Environment you are Lens application on:**
- docs.k8slens.dev

**Developer Hint**:
Just remove the comments in .github/workflows/main.yml line 55 and 60 to skip doc generation for pre-releases.

**Comment by Nokel81** [comment]
Why is the issue marked as a blocker for 4.0.0 when the issue description explicitly says that it is post 4.0.0 work?
