### ISSUE TITLE
CRD parsing error for Strimzi 0.20 KafkaTopic

### ISSUE THREAD

**Issue by vmmelnikov** [lensapp/lens#1412]
**Describe the bug**
After install Strimzi 0.20 (https://strimzi.io) parsing error was appeared on KafkaTopic

**To Reproduce**
1. Go to 'Custom Resource/kafka.strimzi.io'
2. See error on main panel

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/506392/99368652-77022200-28cc-11eb-8d1f-70069ac77dd8.png)

**Environment (please complete the following information):**
- Lens Version: 3.6.8
- OS: [e.g. OSX] Ubuntu 20.04
- Installation method (e.g. snap or AppImage in Linux): snap

**Comment by Nokel81** [comment]
Is this still a problem? I can not reproduce this in 4.1.4.
