### ISSUE TITLE
Reduce animation duration or completely turn off

### ISSUE THREAD

**Issue by cyluss** [lensapp/lens#1418]
**What would you like to be added**:
A way to control animation duration (shorter or completely none) across the app.

**Why is this needed**:
I find the animation is too eye-catchy when navigating through pages/panes/tabs.
e.g. Animation in overview page is fine but I want them to be shorter. When panes switch and search boxes get focus, none.

**Environment you are Lens application on:**
N/A because this is on usability or accessability.

**Comment by Nokel81** [comment]
Can you give an example of an animation that takes too long?

**Comment by cyluss** [comment]
@Nokel81 In 'Add clusters' view, try to hover tab titles, 'Select kubeconfig file' and 'Paste as text'. Tab title text highlights instantly, but 'active' indicator does not. They have css property as `transition` as `width 250ms`. 
It feels snappy after disabling the transition in dev tools.
