### ISSUE TITLE
Allow filtering of pods by IP address

### ISSUE THREAD

**Issue by NikolayMetchev** [lensapp/lens#1421]
**What would you like to be added**:
I would like to be able to filter/lookup pods by IP Address. Possibly other attributes that are currently not easily accessible in the UI

**Why is this needed**:
I was investigating a problem with our DB and it told me the ip address of the problematic query. I needed to then map that t a K8s pod

**Environment you are Lens application on:**
Production

- Kubernetes distribution: EKS
- Desktop OS: MacOS

**Comment by jakolehm** [comment]
Fixed in #1445
