### ISSUE TITLE
Rolling Restarts

### ISSUE THREAD

**Issue by RyanW8** [lensapp/lens#1424]
**What would you like to be added**:

Ability to perform rolling restarts of resources (i.e `kubectl rollout restart <resource_type> <name>`)

**Why is this needed**:

Would be a useful feature to have

**Environment you are Lens application on:**

Kubernetes deployed with KubeSpray on Premise.
Windows

**Comment by johnyb** [comment]
This is already documented as #498, I guess?

**Comment by Nokel81** [comment]
Closing in favour of #498
