### ISSUE TITLE
Add Container Cloud Entry form doesn't appear on Windows 10 v4 Beta 3 of Lens

### ISSUE THREAD

**Issue by mirantisbard** [lensapp/lens#1426]
After upgrading from v4 Beta 2 to v4 Beta 3 on a Windows 10 platform, the display of the Add Cloud Clusters Entry form fails to appear.

**To Reproduce**
1. Install lens-extension-cc on v4 Beta 2 of Lens. Selecting the Add Cloud Clusters button displays the entry form
![AddCloudCluster-EntryForm-Beta2](https://user-images.githubusercontent.com/16943599/99450910-47f0ae00-28d6-11eb-9b04-5d3fb4d0b52c.png)

2. Upgrade Lens v4 Beta 2 (where the add container cloud form works) to v4 Beta 3 on a Windows 10 OS.
3. Click on Add Cloud Clusters, a blank screen is displayed. 
![AddCloudCluster-BlankScreen-Beta3](https://user-images.githubusercontent.com/16943599/99451606-4a073c80-28d7-11eb-8ca6-c004887f5f45.png)

3. The Trace in the DeveloperTool looks like this: 
![AddCloudCluster-BlankScreen-DevTool-Beta3](https://user-images.githubusercontent.com/16943599/99451824-a2d6d500-28d7-11eb-9560-12477a89cdda.png)

4. See error on exit: 
![Error-Message-at-exit](https://user-images.githubusercontent.com/16943599/99451848-ac603d00-28d7-11eb-80cd-52d1b339479b.png)

**Expected behavior**

**Screenshots**
See above.

**Environment (please complete the following information):**
- Lens Version: v4 Beta 3
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): NPM
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
please see attached
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
N/A
```

**Additional context**
I think it's a GUI issue...

**Comment by Nokel81** [comment]
Is this still an issue with 4.1.4? I haven't heard any more problems with windows?

**Comment by Nokel81** [comment]
Just tested on 4.1.4, this is working.
