### ISSUE TITLE
Lens-4.0.0-beta.3-mac.zip has permission issues

### ISSUE THREAD

**Issue by chenhunghan** [lensapp/lens#1429]
**Describe the bug**

So I was brave enough to upgrade to Big Sur, and did a fresh installation of Lens.

I download `Lens-4.0.0-beta.3-mac.zip`, unzip with (Apple's) Archive Utility. And drop it to `/Applications`, click the icon and got this.

<img width="270" alt="Screenshot 2020-11-18 at 13 53 06" src="https://user-images.githubusercontent.com/1474479/99493122-a63a9100-29a9-11eb-83f2-6b450a6bdab2.png">

After some Googling, I have tried solutions [here](https://developer.apple.com/forums/thread/666611), but doesn't help.

Then I use old fashion

```bash
chmod +x /Applications/Lens.app/Contents/MacOS/Lens
```

This does help, but got another error related to Electron like
https://github.com/postmanlabs/postman-docs/issues/1731
https://github.com/postmanlabs/postman-app-support/issues/7039

The solutions they purpose doesn't apply to my case, as I unzip it using (Apple's) Archive Utility.

Then I tried `chmod +x /Applications/Lens.app/Contents/Frameworks/Electron\ Framework.framework/Electron\ Framework`

Still no luck, other errors, so I gave up, downloaded the `.dmg` instead of `.zip`, DMG file works without problems.

Maybe we should warn user about potential permission problems with `.zip` on Big Sur.

**To Reproduce**
1. Download `Lens-4.0.0-beta.3-mac.zip`,
2. Unzip with (Apple's) Archive Utility
3. Open the Lens app.
4. See permission error

**Expected behavior**

.zip should work just like .dmg

**Environment (please complete the following information):**
- Lens Version: 4.0.0 beta.3
- OS: OSX Big Sur 11.0.1 (20B29)
- Installation method (e.g. snap or AppImage in Linux): download zip
 
**Logs:**

Logs from Console.app when I see "You do not have permission to open the application"
```
Nov 18 14:00:45 MacBook-Pro com.apple.xpc.launchd[1] (com.apple.mdworker.shared.0E000000-0400-0000-0000-000000000000[25232]): Service exited due to SIGKILL | sent by mds[75]
Nov 18 14:00:48 MacBook-Pro com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.electron.kontena-lens.3375160.3375458(502)> [7973]
Nov 18 14:00:48 MacBook-Pro com.apple.xpc.launchd[1] (application.com.electron.kontena-lens.3375160.3375458[25237]): Could not find and/or execute program specified by service: 13: Permission denied: /Applications/Lens.app/Contents/MacOS/Lens
Nov 18 14:00:48 MacBook-Pro com.apple.xpc.launchd[1] (application.com.electron.kontena-lens.3375160.3375458[25237]): Service setup event to handle failure and will not launch until it fires.
Nov 18 14:00:48 MacBook-Pro com.apple.xpc.launchd[1] (application.com.electron.kontena-lens.3375160.3375458[25237]): Service exited with abnormal code: 78
```

Log from terminal when I use `open Lens.app`

```
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10826 "kLSNoLaunchPermissionErr: User doesn't have permission to launch the app (managed networks)" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=2508, NSUnderlyingError=0x7fecd0f21120 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x7fecd0f229c0 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed with error: 111}}}}}
```

**Comment by jakolehm** [comment]
~@chenhunghan does `.dmg` work?~ (oops, didn't notice that you tested dmg).

**Comment by jakolehm** [comment]
Zip file is currently not supported for a fresh installation, it's used for auto-update.

**Comment by chenhunghan** [comment]
ah, ok. I can close this I guess.
