### ISSUE TITLE
Text selection overlaps the original text in the terminal

### ISSUE THREAD

**Issue by vshakirova** [lensapp/lens#1430]
**Describe the bug**
Text selection overlaps the original text in the terminal using the light theme.

**To Reproduce**
1. Switch to the light lens theme
2. Click on the terminal
3. Try to select some text
4. See text selection overlaps the original text

**Expected behavior**
The original text should be visible

**Environment (please complete the following information):**
- Lens Version: 4.0.0-beta3
- macOS
 
<img width="910" alt="Screen Shot 2020-11-17 at 2 44 54 PM" src="https://user-images.githubusercontent.com/38247153/99507995-869d6b80-299d-11eb-95df-4a9b3904b3b0.png">

**Comment by vshakirova** [comment]
If you don't mind I can change `"terminalSelection"` from `#bfbfbf` to "#bfbfbf8a".

<img width="578" alt="Screen Shot 2020-11-18 at 1 18 19 PM" src="https://user-images.githubusercontent.com/38247153/99510457-8a7ebd00-29a0-11eb-893b-8d9637bb1371.png">

**Comment by jakolehm** [comment]
@aleksfront wdyt?
