### ISSUE TITLE
Observable fields in extension types aren't reacted to

### ISSUE THREAD

**Issue by Nokel81** [lensapp/lens#1432]
**Describe the bug**
Several fields within extension related types (e.g. `LensExtension` or `LensMainExtension`) are marked as `@observable` (currently shallowly). However, if they are changed during execution of the extension (meaning the time between `onActivate` is called and `onDeactivate` is called) it does not propagate. 

For instance, if an extension sets the `appMenus` field to an array and then later modifies it (say by calling `.pop()` on the field), there is no change to the corresponding app menu.

**To Reproduce**
The following code does not work as expected:
```typescript
class MyExtension extends LensMainExtension {
    clusterPageMenus = [
        {
          target: { pageId: "example", params: {} },
          title: "Example Extension",
          components: {
            Icon: ExampleIcon,
          }
        }
      ]

    async onActivate() {
        console.log("hello world")
        setTimeout(() => {
          this.clusterPageMenus.pop()
        }, 5000)
      }
}
```

**Expected behavior**
The "Example Extension" menu should be visible for the first 5000ms of the extensions' lifetime and then disappear

**Comment by Nokel81** [comment]
I have done some investigation and talked with @jakolehm about what this issue is actually supposed to represent. 

We seemed to come to the conclusion that there are several parts that really should be discussed separately.
- Jari opened #1489 for the maximal case where an entire extension doesn't make sense to be activated for a specific cluster (example: an AWS extension shouldn't be shown to a cluster running on azure)
- The ability for some items to not be shown to some clusters (example: how we currently render custom resources)

## Point 2 (expounded):
Through my investigation it has become clear that we cannot reasonably expect the extension developers to use just a shallowly observable array for entries. An extension developer could, in theory, try to react to the current cluster being changed and change out the array when that happens. However, given how obtuse that workflow is. I don't think we should spend a lot of time trying to make it work. 

Also during my investigation, I realized that the none of the observable arrays were being observed. They were all being read from once and then put into their respective registries. This has a twofold problem. It does not lend itself to being observed very easily and, second, it doesn't lend itself to the original array changing underneath it. With the current design you would have to remove all the old items and then add all the new items back again.

### Proposed Solution:
My solution to both of the above problems is to make all of the arrays non-observable and truly optional (even removing the default values). Thus moving forward if an extension wants a fixed set of entries then they can still set the array. However, this allows us to add the ability to define optional `render*(curCluster: Cluster): *[]` methods. To facilitate this we would need to remove all extension registries (except the main extensions registry). And all the current registry functionality would be either added to the extensions registry as methods or as free functions. This would allow us to read from each of the extensions every time we do a re-render.

### App Menus:
The above solution does not work for the app menu (or even for the tray, but I don't think we currently support adding to that). This is because it is not controlled by mobx or react, but is an electron API. I propose that we have a hook that is passed into `onActivate` that can be called when the extension wants to update the app menu, which we then subsequently read either the array or the `generateAppMenu(curCluster: Cluster): MenuRegistration[]` function.

**Comment by Nokel81** [comment]
Marking as 4.1.0 as it still requires some design work and won't be worked on until after 4.0.0 GA

**Comment by stefcameron** [comment]
Thanks for this deep investigation! I'm glad issues have been identified. I'm don't fully understand the proposed solution because I don't know enough about the internals of Lens yet. On app menus, I believe they should be context-sensitive as well, somehow, someway, but probably more like whether the menu item is enabled or disabled given the current context, rather than being completely added/removed. That seems more like traditional OS menu item behavior to me.

**Comment by ixrock** [comment]
> My solution to both of the above problems is to make all of the arrays non-observable and truly optional (even removing the default values). Thus moving forward if an extension wants a fixed set of entries then they can still set the array. However, this allows us to add the ability to define optional render*(curCluster: Cluster): *[] methods. To facilitate this we would need to remove all extension registries (except the main extensions registry). And all the current registry functionality would be either added to the extensions registry as methods or as free functions. This would allow us to read from each of the extensions every time we do a re-render.

Sounds cumbersome imho.. 
Why not use something like this for auto-detection changes in registries? @jakolehm wdyt?

```ts
  loadOnMain() {
    logger.debug(`${logModule}: load on main`);
    this.autoInitExtensions(async (extension: LensMainExtension) => {
      const registeredItems = new Map<MenuRegistration, Function | IReactionDisposer>();

      autorun(() => {
        // Auto-register items (extension.appMenus must be @observable.shallow array)
        extension.appMenus.forEach(menuInit => {
          if (!registeredItems.has(menuInit)) {
            registeredItems.set(menuInit, registries.menuRegistry.add(menuInit));
          }
        });
        // Auto-remove items when extension.appMenus modified from anywhere
        Array.from(registeredItems).forEach(([menuInit, dispose]) => {
          if(!extension.appMenus.includes(menuInit)) {
            registeredItems.delete(menuInit);
            dispose();
          }
        });
      })

      return [];
    });
  }
```

**Comment by Nokel81** [comment]
@ixrock We want the ability for some of these to be cluster depended so having them be "observable" seems like trying to fit a square peg into a round hole. 

Furthermore, I really don't see the benefit of having these registries at all. We have access to them in the `ExtensionRegistry` so why copy references around?

**Comment by ixrock** [comment]
> We want the ability for some of these to be cluster depended

```ts
  appMenus = [
    {
      filter: (cluster: Cluster | any) => true,  // possible solution, not implemented
      ...otherInitParams,
    }
  ];
```

>  so having them be "observable" seems like trying to fit a square peg into a round hole.

Observability here only for automation and it adds more flexibility imho..

**Comment by Nokel81** [comment]
How is an `observable` array better than `computed`?

**Comment by ixrock** [comment]
> How is an `observable` array better than `computed`?

Didn't get how it's related to the topic? 
It's not better, it's just a derivation from `observable` with required observability and new data format..

**Comment by Nokel81** [comment]
My proposed solution would have the extension author have an `@computed renderClusterPageMenus(activeCluster: Cluster): ClusterPageMenu[] { ... }` which is called in the render function of the cluster page menus.

Then we leave it up to react and mobx to figure out when they should be called again.

**Comment by Nokel81** [comment]
Closing as the fields are no longer marked as observable. Will make a new issue about possible future design considerations.
