### ISSUE TITLE
Support localization within extensions

### ISSUE THREAD

**Issue by ixrock** [lensapp/lens#1449]
Figure out how to extract and consume i18n strings.
Mostl probably it will require extension to have additional package dependencies:
```
    "@lingui/babel-preset-react": "^2.9.1",
    "@lingui/cli": "^3.0.0-13",
    "@lingui/loader": "^3.0.0-13",
    "@lingui/macro": "^3.0.0-13",
    "@lingui/react": "^3.0.0-13",
```
To be able to compile localization files before consuming (via `npm` or Lens).

**Comment by jakolehm** [comment]
Not needed, see #1874 .
