### ISSUE TITLE
Document extensions as TypeScript only

### ISSUE THREAD

**Issue by panuhorsmalahti** [lensapp/lens#1460]
Add a note to the documentation that officially we only support extensions written in TypeScript at the moment.

**Comment by Nokel81** [comment]
This isn't strictly true, but we only have typescript demos at the moment.

**Comment by yellow-straw-hat** [comment]
I can help and add this note

**Comment by Nokel81** [comment]
@yellow-straw-hat Thanks for the offer, but I think we should actually close this as it isn't actually true. We just use typescript in all of our examples
