### ISSUE TITLE
Lens Not Responding 

### ISSUE THREAD

**Issue by bvandorf** [lensapp/lens#148]
Lens.exe keeps going nonresponsive after open for a while 

Open Lens and connect to cluster and wait

![image](https://user-images.githubusercontent.com/11463065/77367197-9fc71d00-6d27-11ea-84dc-ae081493853b.png)
![image](https://user-images.githubusercontent.com/11463065/77367210-a81f5800-6d27-11ea-86da-bcf9253b7a86.png)
![image](https://user-images.githubusercontent.com/11463065/77367241-ba00fb00-6d27-11ea-9169-a74d4d71fe0b.png)
![image](https://user-images.githubusercontent.com/11463065/77367249-bec5af00-6d27-11ea-8776-2acd7d4e4e49.png)

- Lens Version: 3.0.1
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): Installer

**Comment by jakolehm** [comment]
Most likely already fixed.
