### ISSUE TITLE
Missing shared libraries

### ISSUE THREAD

**Issue by ploef** [lensapp/lens#1492]
**Describe the bug**
Missing shared libraries starting Lens AppImage in WSL 2. This did work before.

**To Reproduce**

1. Download AppImage using wget
2. Make AppImage executable using chmod +x
3. Start AppImage
4. Result:

./Lens-3.6.8.AppImage
/tmp/.mount_Lens-3yf1igY/kontena-lens: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory

**Expected behavior**
Lens is started

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 3.6.8 and 3.6.9
- OS: Windows 10 using WSL2 (Ubuntu)
- Installation method: AppImage

**Comment by MeghanaSrinath** [comment]
I'm facing the same issue as well with the latest version of Lens too. Is there anyone who can look into this issue?

**Comment by Swetad90** [comment]
I'm facing the error on 3.6.9 version as well. Can anyone name the version that worked before using AppImage?

**Comment by Nokel81** [comment]
Does WSL come with gtk and XClient? I don't remember WSL2 supporting GUIs without the user setting up X themselves.

**Comment by jakolehm** [comment]
IMHO not an issue with Lens itself. WSL2 does not currently support GUI apps (but I think they are working on it).
