### ISSUE TITLE
Support custom plugins

### ISSUE THREAD

**Issue by nitinsh99** [lensapp/lens#1503]
**What would you like to be added**:
Ability to add third party custom plugins

**Why is this needed**:
For example, I would like to create a plugin that can capture java heap dump from a container.

**Environment you are Lens application on:**
3.6.9

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
AKS
- Desktop OS: <the OS Lens app runs on in your case>
MacOS

**Comment by Nokel81** [comment]
This is currently being worked on in the extensions API that will be released in version 4.0.0
