### ISSUE TITLE
Saving State in Preferences Store

### ISSUE THREAD

**Issue by ericksondelacruz** [lensapp/lens#1508]
**Describe the bug**
I am trying to to create an appPreferences extension and storing state in preferences-store. I based my code to telemetryPreferences but I am having a problem with configName.

Also, when I try to disable telemetry in app preferences it is not working. Basically that's my basis to create an app preferences extension.

**To Reproduce**
1. Recreate telemetry to create appPreferences extension
2. In name-store.ts
3. Scroll down to configName

**Expected behavior**
No error, build success.

**Screenshots**
<img width="398" alt="Screen Shot 2020-11-25 at 8 56 16 AM" src="https://user-images.githubusercontent.com/41985228/100168471-4d647e80-2efc-11eb-808e-d5ed325e7a91.png">
<img width="405" alt="Screen Shot 2020-11-25 at 8 56 21 AM" src="https://user-images.githubusercontent.com/41985228/100168491-581f1380-2efc-11eb-997a-ba2119512f4c.png">

**Environment (please complete the following information):**
- Lens Version: 4.0.0-beta.4
- OS: Catalina
- Installation method (e.g. snap or AppImage in Linux): dmg
 

**Additional context**
Disabling telemetry not working.

**Comment by nevalla** [comment]
There was an issue regarding saving the state in preferences store. The value was saved but it does not reflect on UI. This is fixed in `master` now (#1555).

**Comment by ericksondelacruz** [comment]
Thank you!
