### ISSUE TITLE
Provide example on how to save state in clusterStore, workspaceStore, ExtensionStore.

### ISSUE THREAD

**Issue by ericksondelacruz** [lensapp/lens#1509]
**What would you like to be added**:
Example on how to save state in clusterStore, workspaceStore and ExtensionStore

**Why is this needed**:
To guide Lens extension developer

**Environment you are Lens application on:**

- Kubernetes distribution: EKS
- Desktop OS: Catalina

**Comment by nevalla** [comment]
Thanks for reporting this. We will definitely provide some examples. What kind of state do you have in your mind?

**Comment by ericksondelacruz** [comment]
Globally accessible state for example state if it is enabled, is logged in, so on. I think it will be a good start for Lens extension developers.

**Comment by Nokel81** [comment]
This is currently available: https://docs.k8slens.dev/latest/extensions/guides/stores/

The stores will save your state for you.
