### ISSUE TITLE
Page not found is displayed if open extension is deleted

### ISSUE THREAD

**Issue by panuhorsmalahti** [lensapp/lens#1519]
**Describe the bug**
If the user is viewing a page created by the extension but the extension is deleted, "Page not found" is displayed to the user.

**To Reproduce**
1. Open extension page
2. Delete the extension folder
3. Wait until extension is disabled and deleted

**Expected behavior**
The user is redirected to another page.

**Actual behavior**
The user is displayed "Page not found"

**Comment by Nokel81** [comment]
Duplicate of #1247
