### ISSUE TITLE
Add eslint CI pipeline triggered by PR

### ISSUE THREAD

**Issue by chenhunghan** [lensapp/lens#1531]
**What would you like to be added**:

A CI pipeline reports eslint results.

**Why is this needed**:

PR author/reviewer don't need to run `eslint` locally

**Comment by chenhunghan** [comment]
candidate: https://github.com/github/super-linter

**Comment by panuhorsmalahti** [comment]
I thought our build pipeline already runs eslint?

**Comment by chenhunghan** [comment]
ah, yes, it does run `make lint`, but I think a separate pipeline will be better, allows for faster iteration when author or reviewer can see the linting result instead of waiting for ~15 mins build?

**Comment by jakolehm** [comment]
@chenhunghan yes, separate pipeline (preferrably in GH actions) would be better.
