### ISSUE TITLE
Manage a cluster with no access to namespace listing nor default one

### ISSUE THREAD

**Issue by NemesisMate** [lensapp/lens#1535]
**What would you like to be added**:
Be able to manage workloads on clusters where namespace listing is forbidden (as listing the default one is) and only access to determined namespaces is allowed (managed by "Rancher projects"). To achieve this, a list of namespaces where access is allowed could be added.

Right now, the application doesn't show any warn/error in the terminal (just info logs) but there is nothing listed in any section, as seen in the image.

![Screenshot_20201126_093911](https://user-images.githubusercontent.com/2411239/100327208-43f61780-2fcb-11eb-82b6-7cb6b75849c6.png)

**Why is this needed**:
Because right now, the application is useless under this cluster circumstances.

**Environment you are Lens application on:**

- Kubernetes distribution: Rancher
- Desktop OS: Ubuntu 19.10

**Comment by juv** [comment]
I think this should be possible since 4.0.0-alpha.5, see https://github.com/lensapp/lens/issues/486 and https://github.com/lensapp/lens/pull/702

**Comment by NemesisMate** [comment]
Right,I don't know how I missed those,I must just have filtered by open issues.
I'll check the latest rc and come back with a resolution.
Thanks for pointing it out.

**Comment by NemesisMate** [comment]
I can confirm that with the latest rc (4.0.0-rc.1) is working fine, thanks
