### ISSUE TITLE
Global page is blank

### ISSUE THREAD

**Issue by jim-docker** [lensapp/lens#1560]
Nothing is displayed for a simple page like this:
```
export class HelpPage extends React.Component<{ extension: LensRendererExtension }> {
  render() {
    return (
      <div>
        <p>Help yourself</p>
      </div>
    )
  }
}

export function HelpIcon(props: Component.IconProps) {
  return <Component.Icon {...props} material="help"/>
}

```
![image](https://user-images.githubusercontent.com/40840436/100558283-cf95cf80-327b-11eb-87e3-a28256458d25.png)

Is there more styling or something that needs to be set for the page content?

These are the extension elements set in the renderer extension:
```
  globalPages = [
    {
      id: "help",
      components: {
        Page: HelpPage,
      }
    }
  ];

  globalPageMenus = [
    {
      target: { pageId: "help" },
      title: "Help",
      components: {
        Icon: HelpIcon,
      }
    },
  ];

```

The global page in the generator example is also blank
mac, linux, 4.0.0-rc.1

**Comment by chenhunghan** [comment]
as far as I remember, use `PageLayout` to wrap the global page helps. Might be a CSS issue (z-index?)

```
import { Component } from "@k8slens/extensions";
const { PageLayout } = Component;

const GlobalPage = (): JSX.Element =>
  <PageLayout>
    <div key={"wrapper"}>
    </div>
  </PageLayout>
```

**Comment by aleksfront** [comment]
@chenhunghan Yes, I've used a negative `z-index` to solve this issue https://github.com/lensapp/lens/pull/1565

**Comment by chenhunghan** [comment]
blank page in generator template is another issue (not CSS) but because I forgot to `bind(this)`, see https://github.com/lensapp/lens/issues/1568
