### ISSUE TITLE
TypeError: Cannot read property 'initMainWindow' of undefined

### ISSUE THREAD

**Issue by chenhunghan** [lensapp/lens#1567]
**Describe the bug**
 
Uncaught exception in main process when first launching Lens. Close the crashed Lens and relaunch resolve the issue.

**To Reproduce**
1. Launch
2. See error

**Expected behavior**
No exception, exception is bad for health

**Screenshots**
<img width="270" alt="Screenshot 2020-11-26 at 19 04 33" src="https://user-images.githubusercontent.com/1474479/100580335-b3983980-3320-11eb-9c24-698fff4f0703.png">

**Environment (please complete the following information):**
- Lens Version: 4.0.0-rc.1
- OS: OSX Big Sur
- Installation method (e.g. snap or AppImage in Linux): Download .dmg
 
**Logs:**
Can't see the log because can't open development tool

**Additional context**

Only happens when I haven't opened for a while, like for a day or two. Relaunch the app helps, won't see the exception for the next few hours.

**Comment by panuhorsmalahti** [comment]
I've seen this also.

**Comment by jakolehm** [comment]
@chenhunghan is it possible that Lens was running as a tray icon before you launched it?

**Comment by chenhunghan** [comment]
@jakolehm not sure, I saw this every morning but couldn't reproduce for a day, will try next morning.

**Comment by panuhorsmalahti** [comment]
This error happens if the application is run twice from e.g. `yarn dev`. Perhaps there was another instance of Lens running in the background.

**Comment by Nokel81** [comment]
I cannot seem to reproduce it on macos Catalina, and I don't want to upgrade yet so that we still have a few developers on both platforms for a bit.

**Comment by rodriguez-facundo** [comment]
Same setup, was able to reproduce consistently. This worked for me: 

- remove ~/Library/Application\ Support/lens, 
- delete lens app
- re-install.

**Comment by wangdaqian08** [comment]
> Same setup, was able to reproduce consistently. This worked for me:
> 
> * remove ~/Library/Application\ Support/lens,
> * delete lens app
> * re-install.

I have tried with these steps, no working, I also download the 3.6.x versions, when launching the app, no UI shows at all.

**Comment by wangdaqian08** [comment]
Have the same issue on version 4.0.0

Tried the older version 3.6.x.
When the app starts, no windows show at all, I can only see the Lens icon in the dock. Click on the icon, no action at all.
Don't know how to debug.
