### ISSUE TITLE
Extension API: not this.navigate.bind(this) causes exception

### ISSUE THREAD

**Issue by chenhunghan** [lensapp/lens#1568]
**Describe the bug**

Extension developer needs to `.bind(this)` when pass `navigate` as component props. Not really a bug but this need to be documented => remember to `bind(this)` when passing `LensRendererExtension` methods.

**To Reproduce**

1. Extension developer has a renderer extension structured like this:
```tsx
import { LensRendererExtension, Interface, Component } from "@k8slens/extensions";
import React from "react"

const GlobalPageMenuIcon = ({ navigate }: { navigate?: () => void }): JSX.Element => (
  <Icon
    onClick={() => navigate()}
  />
)
export default class RendererExtension extends LensRendererExtension {
globalPageMenus: Interface.PageMenuRegistration[] = [
    {
      title: "To Extension Global Page",
      components: {
        Icon: (): JSX.Element => <GlobalPageMenuIcon navigate={this.navigate} />,
      }
    }
  ]
}
```
clicking the <GlobalPageMenuIcon /> will throw this
<img width="744" alt="Screenshot 2020-11-30 at 15 24 18" src="https://user-images.githubusercontent.com/1474479/100581826-46d26e80-3323-11eb-9853-a202f1948920.png">

Exception is from
<img width="436" alt="Screenshot 2020-11-30 at 15 25 56" src="https://user-images.githubusercontent.com/1474479/100582043-96b13580-3323-11eb-8ab3-d12860b9f591.png">

2. if pass `this.navigate` props with `.bind(this)`
```
components: {
        Icon: (): JSX.Element => <GlobalPageMenuIcon navigate={this.navigate.bind(this)} />,
}
```

No exception.

**Expected behavior**

Should be documented?

**Environment (please complete the following information):**
- Lens Version: 4.0.0-rc.1
- OS: Big Sur
- Installation method (e.g. snap or AppImage in Linux): .dmg

**Comment by chenhunghan** [comment]
remind me of React's (in)famous `.bind(this)` https://reactjs.org/docs/faq-functions.html

**Comment by jakolehm** [comment]
It's also possible to use `Navigation.navigate` on renderer (`import { Navigation } from "@k8slens/extensions"`). Might be easier.

**Comment by Nokel81** [comment]
@jakolehm would removing this method be better? And instead have the following method?

```typescript
class LensRendererExtensions extends LensExtension {
  getPageUrl<P>(pageId?: string, params: Partial<P> = {}): string {
    const extensionId = this.name;
    return getExtensionPageUrl({ extensionId, pageId, params });
  }
}
```

That way it will always be called and there won't be a need to be bound? Or at least the most obvious use case of `() => Navigation.navigate(this.getExtensionPageUrl())` "just works"? I will make a PR with this as the solution for the time being.

**Comment by jakolehm** [comment]
@chenhunghan @Nokel81 why don't we pass the whole extension object instead of `navigate` function? That should solve this problem, right?

**Comment by Nokel81** [comment]
I guess so, but I don't know if there is a way to pass `this` in JSX. I think that this is purely a programming error and binding function is a well known (imo) necessity in JS/TS. So I think we should just close this. WDYT @jakolehm ?

**Comment by chenhunghan** [comment]
Probably can close it, just think it's more friendly if we remind extension developer that `this.navigate` uses `this.name` so it's necessary to `bind`, I think React Doc did this pretty well, one of the reason it's so popular, I guess.

**Comment by jakolehm** [comment]
> I guess so, but I don't know if there is a way to pass `this` in JSX. 

I think there is a way, see: https://github.com/lensapp/lens/blob/master/extensions/example-extension/renderer.tsx#L11

> I think that this is purely a programming error and binding function is a well known (imo) necessity in JS/TS. So I think we should just close this. WDYT @jakolehm ?

Yeah, we can close this. If this becomes a big issue for extension developers we can add FAQ/Troubleshooting section under "Extension Development" where we describe this.
