### ISSUE TITLE
Checksum

### ISSUE THREAD

**Issue by gybfefe** [lensapp/lens#157]
SHA512 mismatch with latest-linux.yml
Run shasum -a 512 Lens-3.0.1.AppImage or sha512sum Lens-3.0.1.AppImage
and the result is different from the checksum given in latest-linux.yml.
I've downloaded 3 times and the values always the same for shasums, but different from the given in yml

**Comment by jakolehm** [comment]
See https://github.com/electron-userland/electron-builder/issues/3913

**Comment by jakolehm** [comment]
Posted link explains how electron-builder creates the checksum.
