### ISSUE TITLE
Extension API statusBarItems doesn't register status bar items

### ISSUE THREAD

**Issue by chenhunghan** [lensapp/lens#1571]
**Describe the bug**

I have an extension using `statusBarItems` api <https://docs.k8slens.dev/master/extensions/capabilities/common-capabilities/#status-bar-items>. but no icons are shown on the status bar after I launch Lens.

Can't see the status bar item in DOM tree as well, so I guess is not a CSS issue but related to extension manage/loader?

**To Reproduce**
1. Open Lens
2. No status bar item

**Expected behavior**

An icon on status bar.

**Screenshots**

<img width="259" alt="Screenshot 2020-11-30 at 16 45 54" src="https://user-images.githubusercontent.com/1474479/100594379-91101b80-3334-11eb-85eb-808362e94de6.png">

**Environment (please complete the following information):**
- Lens Version: 4.0.0-rc.1
- OS: Big Sur
- Installation method (e.g. snap or AppImage in Linux): .dmg
 
**Logs:**

No error logs in developer tools console.

**Additional context**

The source code of my extension
```tsx
import { LensRendererExtension, Interface, Component } from "@k8slens/extensions";
import React from "react"

const { Icon } = Component;

const StatusBarItemIcon = ({ navigate }: { navigate?: () => void }): JSX.Element => (
  <Icon
    material="link"
    interactive
    style={{
      color: "rgb(255, 255, 0)"
    }}
    onClick={() => navigate()}
  />
)

export default class RendererExtension extends LensRendererExtension {
  statusBarItems: Interface.StatusBarRegistration[] = [
    {
      item: (): JSX.Element => <StatusBarItemIcon navigate={this.navigate.bind(this)} />,
    }
  ]
}
```

**Comment by chenhunghan** [comment]
I found that this work as expected, the icon shows up
```jsx
statusBarItems = [
    {
      item: <StatusBarItemIcon />
    }
  ]
```
but this won't
```jsx
statusBarItems = [
    {
      item: () => <StatusBarItemIcon />,
    }
  ]
```

**Comment by Nokel81** [comment]
Investigation: I see the following error in the console.

```
LensDev.js:425516 Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
    in div (created by BottomBar)
    in div (created by BottomBar)
    in div (created by BottomBar)
    in BottomBar (created by ClusterManager)
    in div (created by ClusterManager)
    in ClusterManager (created by Context.Consumer)
    in Route (created by LensApp)
    in Switch (created by LensApp)
    in ErrorBoundary (created by LensApp)
    in Router (created by LensApp)
    in I18nProvider (created by LensApp)
    in LensApp
```

So this leaves a question, should be call these if they are functions or should we disallow functions?

**Comment by Nokel81** [comment]
So this leaves a question, should be call these if they are functions or should we disallow functions?

**Comment by Nokel81** [comment]
I am going to go with allowing functions, and preemptively fix other locations (if I find any).

**Comment by Nokel81** [comment]
The other option is to make it a component which should fix the typing (I think).

**Comment by Nokel81** [comment]
Which now looking at other things is more in line with our other APIs.

**Comment by chenhunghan** [comment]
I think if we tell extension developer `.item` is type `React.ReactNode`, we need to support component as a function e.g.`()=> <Icon /> `, otherwise we need to change the type to disallow function

**Comment by ixrock** [comment]
> I think if we tell extension developer `.item` is type `React.ReactNode`, we need to support component as a function e.g.`()=> <Icon /> `, otherwise we need to change the type to disallow function

Actually it's already `React.ReactNode`, but what's the problem with it?

_Current interface:_
```ts
export interface StatusBarRegistration {
  item?: React.ReactNode;
}
```

**Comment by Nokel81** [comment]
It is a react node yes, but we were using it as a react child.

**Comment by ixrock** [comment]
> It is a react node yes, but we were using it as a react child.

And?
```ts
type ReactNode = ReactChild | ReactFragment | ReactPortal | boolean | null | undefined;
```

**Comment by Nokel81** [comment]
Maybe the "proper" solution was to use `<item />` instead. I don't remember if we tried that...

**Comment by ixrock** [comment]
Proper solution would be to make:

```ts
export interface StatusBarRegistration {
  item?: React.ReactNode | React.ComponentType<any>;
}
```

and re-use in `render()` like: `isReactNode(item) ? item : <item/>`

NB: `isReactNode` is helper function from `src/renderer/utils/isReactNode.ts`

**Comment by Nokel81** [comment]
ah cool. Then I would say make a small PR then.
