### ISSUE TITLE
Set frequency of updates/data fetching

### ISSUE THREAD

**Issue by probenx** [lensapp/lens#1588]
**What would you like to be added**:
Setting for fetching frequency.

**Why is this needed**:
I was asked by my manager to either stop using Lens or set it to update change the update frequency.

**Environment you are Lens application on:**

- Kubernetes distribution: AKS
- Desktop OS: Ubuntu 20.04

**Comment by jakolehm** [comment]
@probenx which update frequency you mean?

**Comment by probenx** [comment]
@jakolehm Well the message was very vague in that regard, I will try to get more info.
What are the different ones?

**Comment by probenx** [comment]
Here is the complaint that I got @jakolehm :
The past couple days we have been hitting CPU alerts from the api servers.  It queries the API server so often that it can overload and queue requests from others.  For users your coreid has more hits than all other users combined by a large margin.  Then when we check api calls lens hit more times (~5000) than any other calls this was in a 15 minute window.

**Comment by jakolehm** [comment]
@probenx which version of Lens is this?

**Comment by probenx** [comment]
@jakolehm 3.6.9

**Comment by Nokel81** [comment]
This has been fixed in 4.1 by only querying the selected namespaces (which defaults to only `default`). We don't actually do polling, we use the kube watch API.
