### ISSUE TITLE
Make cluster available to cluster-related extension elements

### ISSUE THREAD

**Issue by jim-docker** [lensapp/lens#1626]
`ClusterFeature` class has abstract methods that provide the cluster as a parameter like:
```
abstract async install(cluster: Cluster): Promise<void>;
```
so when developers implement cluster features they have the pertinent cluster object at hand when they implement the methods.

Elements like `clusterPages`, and `kubeObject{Menu|Detail}Items` are also cluster-dependent but don't have similar direct access to the relevant cluster object. They could get the active cluster from the clusterStore but it would be better if they were somehow "told" which cluster was relevant.

**Comment by Nokel81** [comment]
Related to #1432 and #2245 since that PR allows for passing in a cluster instance to a function.

**Comment by jakolehm** [comment]
Closing because we don't have `ClusterFeature` anymore.
