### ISSUE TITLE
Create developer scripting console

### ISSUE THREAD

**Issue by wkonitzer** [lensapp/lens#1653]
**What would you like to be added**: Python like developer scripting console, so I can iterate and adjust all objects deiplayed in Lens quickly

**Why is this needed**:
Useful for querying and updating objects across large cluster sets

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: <the OS Lens app runs on in your case>

**Comment by Nokel81** [comment]
I am going to mark this as a duplicate of https://github.com/lensapp/lens/issues/686 since it covers the same use case
