### ISSUE TITLE
Add SHA256 information on release assets

### ISSUE THREAD

**Issue by srbala** [lensapp/lens#1664]
**What would you like to be added**:

Add `SHA256` of each uploaded assets part of release for install verifications

**Why is this needed**:

This will help to validate published assets prior to install/use.

**Environment you are Lens application on:**

All user environments

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]

OpenShift, Docker for Desktop, Rancker

- Desktop OS: <the OS Lens app runs on in your case>

Windows 10, Mac

**Comment by Nokel81** [comment]
Fixed by #2252 (if I understand what you are asking for).
