### ISSUE TITLE
Support for Cronjobber and TZCronJob

### ISSUE THREAD

**Issue by adam8797** [lensapp/lens#1679]
**What would you like to be added**:
Cronjobber adds support for timezones to core, and it would useful to see these. No real additional functionality would be needed, maybe a discriminator column for the type.

**Why is this needed**:
Currently when using Cronjobber, Lens will show 0 cronjobs which is misleading, since Cronjobber uses the TZCronJob type

**Environment you are Lens application on:**

- Kubernetes distribution: N/A (I don't manage this cluster)
- Desktop OS: Windows 10

**Comment by Nokel81** [comment]
Are you not able to view them under the CRD view?

**Comment by Nokel81** [comment]
Making as duplicate of https://github.com/lensapp/lens/issues/883
