### ISSUE TITLE
new resource creation is behind "terminal"

### ISSUE THREAD

**Issue by matti** [lensapp/lens#168]
As a user you would expect that this would open a new terminal:

<img width="462" alt="Lens" src="https://user-images.githubusercontent.com/3893/77819948-6f94cb00-70e7-11ea-91c6-c63ec3b4b374.png">

but surprise surprise:
![image](https://user-images.githubusercontent.com/3893/77819966-8d623000-70e7-11ea-98f7-49599f01783b.png)

**Comment by Nokel81** [comment]
This is working as intended. I would agree that it is misleading if it said "New Terminal".
