### ISSUE TITLE
Text escape bug: UI shows don&apos;t

### ISSUE THREAD

**Issue by cep21** [lensapp/lens#1680]
**Describe the bug**
See screenshot.  Should be `don't` not `don&apos;t`
![image](https://user-images.githubusercontent.com/20358/101391228-e12d3780-3878-11eb-9082-ff42b3317379.png)

**To Reproduce**
1. Install latest 4.0 windows client
2. Add cluster
3. Go to cluster settings
4. Read text for "accessible Napespaces"

**Expected behavior**
Escaped correctly

**Screenshots**

**Environment (please complete the following information):**
- Lens 4.0
- OS: Windows
- Installation method From github releases

**Comment by wgitscht** [comment]
this has been fixed by https://github.com/lensapp/lens/commit/2543e4aec7051c7d4187c212c4ce5da54dd6fa68

**Comment by pashevskii** [comment]
@nevalla The issue has been fixed and merged, could you please close this one?
