### ISSUE TITLE
Lens 4.0.0 not showing Workloads sections without Admin privileges

### ISSUE THREAD

**Issue by Arnonrgo** [lensapp/lens#1682]
**Describe the bug**
I have a K8s cluster where I only have privileges on  some namespaces (I can list all)
with Lens 3.6.x I only see "my" namespaces but I can access all the "workloads" related tabs (pods, jobs etc.)
with Lens 4.0.0 I can see all the namespaces but I don't see any info on the "workloads"
On another cluster where I have full admin rights everything looks normal

 section
**To Reproduce**
use Lens 4 in a cluster with partial permissions

**Expected behavior**
be able to see and use all the features on workloads I can control

**Screenshots**
![lens4 0 0](https://user-images.githubusercontent.com/531800/101409556-baa5e580-38e6-11eb-84fa-e07af0aa061e.png)
![lens3 6 x](https://user-images.githubusercontent.com/531800/101409562-bd083f80-38e6-11eb-95ec-73dccc2143c0.png)

**Environment (please complete the following information):**
- Lens Version: 4.0.0
- OS: OSX BigSur
- Installation method (e.g. snap or AppImage in Linux): dmg from git release page

**Comment by kounelios13** [comment]
Same thing happened to me . I have installed Lens via AppImage. In my case the AppImage auto updated and upon restart I had no access to my deployment info. I had to redownload the pre v4 app image and mark it as readonly to prevent autoupdates

**Comment by jakolehm** [comment]
@Arnonrgo first screenshot is from 4.0.0 and second from 3.6.x?

**Comment by Arnonrgo** [comment]
@jakolehm yes. Also, it doesn't help if you choose a namespace that you do have permissions on (the user has list access on namespaces and more permissions like deploy on a few namespaces)

**Comment by jakolehm** [comment]
@Arnonrgo Lens 3.6 actually had a bug that triggered "correct" behaviour on these clusters. Both 3.6 and 4.0 will resolve RBAC access similarly but 3.6 did show only namespaces that had access to pods (which is not correct behaviour plus resolving access to pods causes huge load to clusters with big number of namespaces). It seems that we need to add more intelligence to this logic (maybe based on number of namespaces).

**Comment by Arnonrgo** [comment]
@jakolehm right - we did notice that namespaces were not showing despite people having list namespaces privileges. However while the previous bug was an annoyance, this one is making lens unusable. 
You probably noticed but just in case - it only happens on the workloads tab (e.g. "services" works fine)

**Comment by jakolehm** [comment]
@Arnonrgo just to make sure: first screenshot shows "auth" as the first namespace, is it so that you don't have access to pods in that namespace (for example using kubectl)?

**Comment by Arnonrgo** [comment]
@jakolehm Right, on that cluster I only have pods access to the 3 namespaces in the second screenshot.
e.g.
kubectl get pods -n default
Error from server (Forbidden): pods is forbidden: User "a.." cannot list resource "pods" in API group "" in the namespace "default"

**Comment by Arnonrgo** [comment]
The workaround mentioned on bug#1700 https://github.com/lensapp/lens/issues/1700#issuecomment-741856445 seems to solve the issue for me

**Comment by Nokel81** [comment]
I think the problem here is that Lens is only checking permissions against the first namespace it finds, if this happens to be a namespace that you don't have access to then this is what happens. 

related to #745

**Comment by jakolehm** [comment]
#1830 should fix this.

**Comment by marvinosswald** [comment]
@jakolehm this isn't fixed in 4.0.6, the workaround proposed by #1700 works though
