### ISSUE TITLE
Cannot collapse/expand individual custom resource groups

### ISSUE THREAD

**Issue by arzarif** [lensapp/lens#1685]
**Describe the bug**
In 4.0.0, collapsing/expanding individual CR groups in the Custom Resources blade doesn't work. Attempting to collapse a single CR group collapses the entire Custom Resources blade. This appears to be a regression from 3.6.X, where it was possible to expand/collapse individual CR groups.

**To Reproduce**
1. Go to 'Custom Resources'
2. Click on any custom resource group to collapse it individually

**Expected behavior**
Expand collapse individual CR groups

**Screenshots**
Clicking on the arrow encircled in red below:
<img width="1831" alt="Screen Shot 2020-12-07 at 5 53 55 PM" src="https://user-images.githubusercontent.com/7546084/101428391-777f4e80-38b5-11eb-84de-334eb366ae46.png">

...collapses the entire Custom Resources blade:
<img width="1832" alt="Screen Shot 2020-12-07 at 5 54 58 PM" src="https://user-images.githubusercontent.com/7546084/101428400-7cdc9900-38b5-11eb-9c5a-03341fbf5e36.png">

**Environment (please complete the following information):**
- Lens Version: 4.0.0
- OS: MacOS 11

**Comment by jakolehm** [comment]
@aleksfront most likely a regression from #1638 ?

**Comment by a8j8i8t8** [comment]
This is still the case in version 4.0.1.

Cheers,
~Ajit
