### ISSUE TITLE
Stop auto updating AppImage

### ISSUE THREAD

**Issue by kounelios13** [lensapp/lens#1689]
**Describe the bug**
When running Lens from the AppImage format if you are not on the latest version the AppImage will auto update and there is nothing to my knowledge that can prevent that . This leads to issues such as this : #1682. It would be better to provide a way to disable this behaviour

**To Reproduce**
1. Download an app image prior to version 4
2. Run
3. Wait for a couple of minutes 
4. A message that says that lens will be updated on the next restart
5.  The app image has been updated

**Expected behavior**
Users should be able to configure whether they want lens to autoupdate or not

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 3.6.9
- OS: PopOS
- Installation method (e.g. snap or AppImage in Linux): AppImage

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by zapp2me** [comment]
+1 for this. As someone working in a managed corporate Windows environment without admin rights I now get an admin promt everytime I close Lens.

**Comment by cSNiHab** [comment]
+1
The new version does not work properly so now I have to figure out which URL to block so it cannot auto update

**Comment by kounelios13** [comment]
@cSNiHab if you find this url please let me know

**Comment by namatsawin** [comment]
+1

**Comment by cSNiHab** [comment]
> @cSNiHab if you find this url please let me know

I was able to prevent the automatic update by (on os x) setting the Application/Lens 3.6.9 package directory to read-only

**Comment by kounelios13** [comment]
Hello . Is there any progress on that ? I cannot find a way to stop it . Even by setting the AppImage as read only after a couple of minutes I get a new update notification. When I close Lens the original AppImage has been updated

**Comment by Nokel81** [comment]
I believe that this should now be fixed, because of https://github.com/lensapp/lens/pull/1941 you can now stay on a version if you would like to.
