### ISSUE TITLE
Automatically start Lens on login should default to disabled

### ISSUE THREAD

**Issue by mbentley** [lensapp/lens#1697]
**What would you like to be added**:
In Lens 4.0.0, it looks like the option to start on login (`Automatically start Lens on login`) was added and enabled by default.  I don't mind the option but to have it enabled by default is a big heavy handed, especially without giving the user an option to opt out upon upgrading.

**Why is this needed**:
When I boot my computer, the first thing I am typically doing is not looking at k8s.  I open it when I need it, and close it when I am done.

**Environment you are Lens application on:**
macOS Big Sur 11.0.1

**Comment by ixrock** [comment]
> especially without giving the user an option to opt out upon upgrading

You can turn it off at the **Preferences** page:
![image](https://user-images.githubusercontent.com/6377066/103007649-73e9f980-453c-11eb-8414-d194247d4bc0.png)

**Comment by mbentley** [comment]
Correct but it is enabled by default which is poor behavior for an application in my opinion. Ask me if I want to enable it in a tool tip, allow me to dismiss that tool tip and that's as far as anyone should go.  Unless it is a tool that I need running by default like a background service that actually does something when I am not interactively using it, I don't want it running.  Today, Lens serves zero value to me when I am not interacting with it.

**Comment by juv** [comment]
+1 @mbentley 

I don't think Lens should _default_ to putting itself into the autostart
