### ISSUE TITLE
Wrong data about CPU, DISK, PODS usage per node

### ISSUE THREAD

**Issue by serjo77** [lensapp/lens#1699]
**Describe the bug**
Wrong data about CPU, DISK, PODs usage per node

**To Reproduce**
1. Go to a cluster
2. Click on the node
3. Click on graf selector Cpu, Disk, Pods
4. See the wrong data

**Screenshots**
![image](https://user-images.githubusercontent.com/4243996/101487895-81618a00-3967-11eb-8b97-f9ea9770dd9f.png)
![image](https://user-images.githubusercontent.com/4243996/101488029-b1a92880-3967-11eb-9213-9f8ba536c2cf.png)

**Environment (please complete the following information):**
- Lens Version: kontena-lens                     4.0.0                       144
- OS: Ubuntu 20.4
- Installation method (e.g. snap or AppImage in Linux): snap

**Comment by matti** [comment]
seeing this also:

![2020-12-08 at 15 48](https://user-images.githubusercontent.com/3893/101491862-eec3e980-396c-11eb-9b52-737290cd7a06.jpg)

```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           11Gi       531Mi       7.9Gi       4.0Mi       3.3Gi        10Gi
Swap:            0B          0B          0B
```

**Comment by alekskar** [comment]
Same for us. After upgrade to v4.0.x node metrics shows wrong graphs

**Comment by ms2008** [comment]
v4.0.6, still not right
