### ISSUE TITLE
create new secret

### ISSUE THREAD

**Issue by matti** [lensapp/lens#17]
missing new button

**Comment by aleksfront** [comment]
What new button did you mention? Secret could be created from Dock panel from yaml file as any other k8s resource. The big plus button used across lens for items that require dialogs.

**Comment by matti** [comment]
The big plus button that requires dialog. Creating secrets with yamls is horrible.

**Comment by ixrock** [comment]
@matti  
What kind of secret's type the dialog should support? Only `Opaque` is enough?
It seems the Secret can have the following types with some optional requirements to be created:

```
SecretTypeOpaque SecretType = "Opaque" // no special requirements
SecretTypeServiceAccountToken SecretType = "kubernetes.io/service-account-token" // requires 2 extra metadata.annotations fields to create the secret
SecretTypeDockercfg SecretType = "kubernetes.io/dockercfg"
SecretTypeDockerConfigJson SecretType = "kubernetes.io/dockerconfigjson"
SecretTypeBasicAuth SecretType = "kubernetes.io/basic-auth"
SecretTypeSSHAuth SecretType = "kubernetes.io/ssh-auth"
SecretTypeTLS SecretType = "kubernetes.io/tls"
SecretTypeBootstrapToken SecretType = "bootstrap.kubernetes.io/token"
```

**Comment by matti** [comment]
opaque would be a good start
