### ISSUE TITLE
How to prevent auto-update to 4.0? Breaks cluster access!

### ISSUE THREAD

**Issue by spyro2000** [lensapp/lens#1701]
**Describe the bug**
Lens 4.0.0 is breaking our cluster communication.

![image](https://user-images.githubusercontent.com/8479925/101490636-ed8dbf00-3962-11eb-997a-e371454d4f85.png)

I downgraded to 3.6.9 and everything worked again. But as lens tends to show outdated data after some while (see https://github.com/lensapp/lens/issues/1102) I  have to restart it every 1-2 hours. But then it just auto-updates to the broken 4.0.0 again. I found no setting to prevent Lens from doing that.

**To Reproduce**
1. Downgrade to 3.6.9
2. Restart lens
3. Watch it auto-update

**Expected behavior**

Toggle to prevent auto-update.

**Screenshots**

See above

**Environment (please complete the following information):**
- Lens Version: 3.6.9 / 4.0.0
- OS: Win10-x64
- Installation method (e.g. snap or AppImage in Linux): Installer

**Comment by nevalla** [comment]
The error that is seen in the screenshot is coming from kubectl proxy and don't see any obvious reason why this is failing in 4.0 but not in 3.6. Are there any references to `azure` auth provider on Kubeconfig?

**Comment by spyro2000** [comment]
Hi @nevalla,

There are multiple references in my kube config file like this:

![image](https://user-images.githubusercontent.com/8479925/101500237-79591880-396e-11eb-906c-e75ded09576c.png)

It works just fine with kubectl but not in Lens (4.0.0). Preferences suggest that Lens downloads it's own kubectl version but in fact it doesn't change anything when I rename the whole "resources" directory.

**Comment by nevalla** [comment]
If you change in App preferences Lens to use kubctl binary found on your machine, is it working then?

**Comment by spyro2000** [comment]
Thank you, I will check bis, but again, how to prevent the update-update?

**Comment by nevalla** [comment]
Unfortunately it's not possible atm, but we are working on it!

**Comment by spyro2000** [comment]
Ok, thanks, that's good to here. Found out the following:

- When I remove the cluster from the sidebar and then recreating it with 3.6.9 it keeps working with 4.0.0 (as long as the token stays valid). Could be related to https://github.com/lensapp/lens/issues/1702

**Comment by davidshare** [comment]
How does someone turn off the automatic updates feature?

**Comment by Nokel81** [comment]
Fixed by #1941
