### ISSUE TITLE
No Auth Provider found for name "azure"

### ISSUE THREAD

**Issue by mcbenjemaa** [lensapp/lens#1702]
**Describe the bug**
After upgrading Lens to the latest release 4.0.0
Lens Cannot get token 

**To Reproduce**
 '...' upgrade Lens to the latest release 4.0.0 and use config for an AKS RBAC based cluster.

**Expected behavior**

**Screenshots**
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/15221272/101490875-43626700-3963-11eb-831e-2992a9d12d77.png)

**Environment (please complete the following information):**
- Lens Version: 4.0.0
- OS: windows

**To Fix**
```
    _ "k8s.io/client-go/plugin/pkg/client/auth/azure"
```

**Comment by nevalla** [comment]
@medmedchiheb please could you check from the process list what is the path of the kubectl binary that Lens is using and report it here?

**Comment by spyro2000** [comment]
Sure:

![image](https://user-images.githubusercontent.com/8479925/101881035-2496e700-3b94-11eb-933f-8d73f5a6d279.png)

**Comment by jakolehm** [comment]
Does this still happen with the latest 4.0 version?

**Comment by nevalla** [comment]
@medmedchiheb Do you see this with the latest 4.0 version?

**Comment by jakolehm** [comment]
Cannot reproduce. Let's reopen if we see this again.
