### ISSUE TITLE
apps charts broken

### ISSUE THREAD

**Issue by matti** [lensapp/lens#1703]
4.0.0

![2020-12-08 at 15 47](https://user-images.githubusercontent.com/3893/101491687-b91f0080-396c-11eb-8f72-dd89fa3d1eae.jpg)

**Comment by nevalla** [comment]
Helm stable repo is deprecated. If you still want to use it please run `helm repo add stable https://charts.helm.sh/stable --force-update` in a command line or remove the current stable repository and add it again with the new url.

**Comment by jakolehm** [comment]
I think we can close this because it's not Lens fault.
