### ISSUE TITLE
After auto-update 4.0, I can no longer access my K8s cluster.

### ISSUE THREAD

**Issue by tgates-nalej** [lensapp/lens#1705]
I'm on MacOs.  I normally invoke Lens from the command line using the Z-shell alias:

± % alias lens 
lens='open -a /Applications/Lens.app'

So that it can pick up shell environment variables, like AWS_PROFILE.

This worked fine prior to Lens version 4.0, but now with Lens 4.0 I get the messages:

Authentication proxy started
Invalid credentials

As a workaround, is there a way I can go back to the previous version?

Thanks,
-tom

**Comment by spyro2000** [comment]
same here

**Comment by nevalla** [comment]
Tried to reproduce this by exporting my AWS credentials on my command line and opening Lens as you mentioned and everything worked fine. If you open Lens with `DEBUG=true` do you see any additional errors or hints that could reveal anything?

**Comment by tgates-nalej** [comment]
@nevalla  I opened Lens with `DEBUG=true` but it didn't give any additional information.

**Comment by fjvela** [comment]
Same here, opened lens in debug mode on windows and no error are show in logs.

**Comment by jdomag** [comment]
same here

**Comment by trentmurray** [comment]
I've got the same issue. When using assumed roles AWS this is vital. Stopped for a couple of days ago.

Just noticed this error:

Can't find working API for the Kubernetes resource ingresses

Does the new version require a minimum kubectl CLI version?

**Comment by nevalla** [comment]
I've tried to reproduce this but so far no luck and we have not really touched this part in `4.0` release but obviously something is causing broken. Please could you elaborate your environment as much as possible. What OS X version do you have? Are you all using `zsh` or is this happening on other shells too? If you could test with other than AWS cluster (for example Minikube) can you see your environment variables correctly in Lens terminal?

**Comment by panuhorsmalahti** [comment]
"Can't find working API for the Kubernetes resource ingresses"

This error is likely harmless. If once your cluster is accessible you're not seeing ingress resources, we can take another look about (this particular error).

**Comment by tgates-nalej** [comment]
My environment:

MacOS Catalina Version 10.15.7

% uname -a
Darwin MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

 % zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)

**Comment by tgates-nalej** [comment]
Is there a way I can go back to the previous version?

**Comment by tgates-nalej** [comment]
Is anyone looking into this problem?  Is there a way I can go back to the previous version?

**Comment by nevalla** [comment]
@tgates-nalej is the cluster connection working if you specify environment variable in Kubeconfig file?

```
user:
  exec:
    ...
    env:
      - name: AWS_PROFILE
        value: <profile>
```

**Comment by nevalla** [comment]
> Is there a way I can go back to the previous version?

You can go back to 3.6 series by downloading latest release from that version and not closing the app. But we definitely need to fix this issue too.

**Comment by tgates-nalej** [comment]
@nevalla Adding the env AWS_PROFILE to my Kubeconfig file did not fix this problem.

**Comment by trentmurray** [comment]
@nevalla  - Where in the code does Lens check for updates and auto-update? I'd like to fork from 3.6 and remove that code until this issue is resolved.

**Comment by jakolehm** [comment]
Could someone here share a kubeconfig that does not work with Lens 4.0 but works in Lens 3.6.9? (please remove all secrets before sharing it)

**Comment by tgates-nalej** [comment]
@jakolehm  My obscured kubeconfig is attached.

[sdo-operator.kubeconfig.example.zip](https://github.com/lensapp/lens/files/5703376/sdo-operator.kubeconfig.example.zip)

**Comment by nevalla** [comment]
config looks legit to me and similar that is working for me. How about if you run `DEBUG_PROXY=true lens`?  This should output logs from kubectl proxy server to dashboard. Do you see requests coming to auth proxy properly? Like `/version` request. Do you see any errors that auth proxy might return?

**Comment by tgates-nalej** [comment]
Len 4.0.3 seems to have fixed my problem.

**Comment by tgates-nalej** [comment]
@nevalla  I got the following, but it eventually connected using Lens 4.0.3:

1221 07:51:29.889987 20104 proxy_server.go:88] /version matched ^.*
I1221 07:51:29.890001 20104 proxy_server.go:88] 5aa4c896f54df32186c62c511673791e.gr7.us-east-1.eks.amazonaws.com matched 5aa4c896f54df32186c62c511673791e.gr7.us-east-1.eks.amazonaws.com
I1221 07:51:29.890006 20104 proxy_server.go:128] Filter accepting GET /version 5aa4c896f54df32186c62c511673791e.gr7.us-east-1.eks.amazonaws.com

I1221 07:51:29.890027 20104 upgradeaware.go:253] Request was not an upgrade
I1221 07:51:29.890054 20104 round_trippers.go:423] curl -k -v -XGET -H "X-Forwarded-For: 127.0.0.1" -H "Accept: application/json" -H "User-Agent: kubectl/v1.17.11 (darwin/amd64) kubernetes/ea5f00d" 'https://5AA4C896F54DF32186C62C511673791E.gr7.us-east-1.eks.amazonaws.com/version'
I1221 07:51:29.890091 20104 round_trippers.go:443] GET https://5AA4C896F54DF32186C62C511673791E.gr7.us-east-1.eks.amazonaws.com/version in 0 milliseconds
I1221 07:51:29.890097 20104 round_trippers.go:449] Response Headers:
2020/12/21 07:51:29 http: proxy error: write tcp 192.168.1.29:63245->54.221.57.115:443: write: can't assign requested address

I1221 07:51:29.935684 20353 loader.go:375] Config loaded from file: /Users/tgates/.kube/sdo-operator.kubeconfig

F1221 07:51:29.936744 20353 proxy.go:160] listen tcp 127.0.0.1:63213: bind: address already in use

proxy exited with code: 255

502 - undefined

**Comment by jakolehm** [comment]
> F1221 07:51:29.936744 20353 proxy.go:160] listen tcp 127.0.0.1:63213: bind: address already in use


@tgates-nalej is it possible that something was blocking that port? If yes -> kubectl didn't see that and took reserved port by accident.

**Comment by trentmurray** [comment]
I had to remove the old Lens Application from MacOS, then reinstall 4.06  - works now.

**Comment by dzmitry-lahoda** [comment]
i used k9s, and it worked. installed lens. first time it did not connect. creds gone from my file system. i redo all again. lens connected. but than again became broken. and broken same location of creds as k9s uses. so it seems lens breaks credentials each time i use it. will not use. on windows 10.

**Comment by jakolehm** [comment]
@dzmitry-lahoda how did you add a cluster to Lens?

**Comment by Nokel81** [comment]
Any update @dzmitry-lahoda ?

**Comment by dzmitry-lahoda** [comment]
we do not have so many resources so i stick to `k9s` for now. as soon as the cluster will grow, will check lens again.

**Comment by Nokel81** [comment]
Okay thanks for the response. I am going to close this issue then as the original poster's problem has been solved. Please don't hesitate to open a new issue if you run into problems when you try Lens again.
