### ISSUE TITLE
logs view goes funky on resize

### ISSUE THREAD

**Issue by matti** [lensapp/lens#1706]
4.0.0

![2020-12-08 at 17 31](https://user-images.githubusercontent.com/3893/101503941-55e89a80-397b-11eb-851d-82c4ebe9a3f1.jpg)

**Comment by jakolehm** [comment]
@matti which macOS version do you have? (I cannot reproduce on MacOS / Big Sur).

**Comment by matti** [comment]
macos catalina.

Can't repro now either, has something to do with resizing and/or multiple tabs running terminals / logs.

**Comment by aleksfront** [comment]
I will check this out.

**Comment by castaf** [comment]
Same here : macOS Catalina 10.15.7 and Lens 4.0.1

**Comment by castaf** [comment]
> Same here : macOS Catalina 10.15.7 and Lens 4.0.1

Always the same issue with Lens 4.0.2
