### ISSUE TITLE
Install an extension from a NPM registry url

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#1707]
For example if user wants to install `@mirantis/lens-extension-cc` it could be done by giving an URL http://registry.npmjs.com/@mirantis/lens-extension-cc  (which returns a json object that Lens can use for resolving latest tarball URL).

**Comment by panuhorsmalahti** [comment]
Branch `hackweek-protocol-handler` contains most of the implementation for this.

**Comment by Nokel81** [comment]
Decided in favour of only supporting installing extensions by name and optional version instead.
