### ISSUE TITLE
Deployment Scale Button Minus (-) Bug

### ISSUE THREAD

**Issue by hodolomax** [lensapp/lens#1719]
In Deployment replication scale popup window, there is + and - buttons added near slider (v4.0.0). Minus button doesn't scale down 1 to 0 . I can't see any error devoloper console or network activity. Please check this function. 

Watch in the action
https://youtu.be/Dbj2Lfd6CAw

**Comment by chenhunghan** [comment]
my bad, I thought deployment can't scale to 0.
