### ISSUE TITLE
logs: export entire logfile

### ISSUE THREAD

**Issue by kilpatty** [lensapp/lens#1722]
My lens was just auto-upgraded to version 4.0.0. Previously I was able to select "View entire logfile" when looking at logs for a specific pod, and then I could save that file somewhere for me to inspect it. 

In 4.0.0 when I select save logs it only saves what is currently in my view. In order to access the rest of the logs I have to scroll up constantly for each new 100-200 lines to load.

I'm not sure if I am just missing this functionality or if it was removed, but if removed could we please get back the "show 1000, 10,000, all logs" helpers? It was one of the most useful features in Lens for me

EDIT: Additionally, is there a way to block auto-upgade from occurring? Downgrading to ~3 so that I can use this feature again, but have to repeat this process once the auto-upgrade kicks in.

**Comment by OneB1t** [comment]
Im also missing this feature, it will be nice to have something like "download entire log for current container/download entire log for previous container" and "stream complete log"

**Comment by mverleun** [comment]
I would be nice to have a 'download all logs' button

**Comment by Nokel81** [comment]
Closing this issue as there is currently a "Download All Logs" button for pod logs.

**Comment by AykutCevik** [comment]
> Closing this issue as there is currently a "Download All Logs" button for pod logs.

Where is it actually? Looking at #4803 we can't find it.
