### ISSUE TITLE
Switching from/to Lens on macOS causes UI slowdown

### ISSUE THREAD

**Issue by msnelling** [lensapp/lens#1725]
**Describe the bug**
The app suffers serious performance issues that are triggered when I switch between apps on macOS 11

**To Reproduce**
1. Open Lens.
2. Performance seems ok.
3. Switch another app to foreground, say a browser.
4. Switch back to Lens.
5. UI performance is horrendous.

**Expected behavior**
Switching between apps shouldn't affect Lens UI performance.

**Screenshots**
N/A.

**Environment (please complete the following information):**
- Lens Version: 4.0.1
- OS: macOS 11
- Installation method (e.g. snap or AppImage in Linux): Download from Github then autoupdated to 4.0 and then to 4.0.1. Issue present in both 4.0 and 4.0.1

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
Unsure how to dow this.

**Kubeconfig:**
N/A

**Additional context**

**Comment by Nokel81** [comment]
Is this still an issue on 4.1.4?

**Comment by msnelling** [comment]
@Nokel81 It looks to be resolved in this release... thanks!
