### ISSUE TITLE
Cannot view HPA details

### ISSUE THREAD

**Issue by giannisioannou-tomtom** [lensapp/lens#1749]
**Describe the bug**
Selecting any HPA resource under "Configuration" displays an empty side panel (details panel)

**To Reproduce**
1. Go to a running cluster
2. Click on Configuration
3. Click on HPA
4. Select any HPA resources

**Expected behavior**
That the details panel of the HPA resource is shown correctly

**Environment (please complete the following information):**
- Lens Version: 4.0.1
- OS: Ubuntu
- Installation method (e.g. snap or AppImage in Linux): snap

**Comment by aleksfront** [comment]
Duplicate of #1743 
Will be fixed in #1745
