### ISSUE TITLE
Apple Silicon Build

### ISSUE THREAD

**Issue by zinozzino** [lensapp/lens#1756]
**What would you like to be added**:
Provide an Apple Silicon Build (darwin-arm64).

**Why is this needed**:
I want to manage my kubernetes cluster on new M1 Macbook Air.

**Environment you are Lens application on:**

- Kubernetes distribution: mostly EKS
- Desktop OS: macOS 11.0.1

**Reference**
- https://www.electronjs.org/blog/apple-silicon
- https://www.electronjs.org/blog/electron-11-0

**Comment by jakolehm** [comment]
I have been hearing that Lens works on Apple Silicon (although not natively). Did you hit into issues there?

**Comment by stunthamster** [comment]
@jakolehm It works fine, but Electron apps tend to be very slow on M1 macs due to the factors outlined in the apple-silcon blog entry above. AFAIK, you get this 'for free' when upgrading to electron-11, albeit while requiring another build target (Although I'm no expert on this, so happy to be corrected).

I'd be happy to see an M1 build, but for now, Lens works on my M1 Mac, Albeit with some performance penalty.

**Comment by jakolehm** [comment]
@stunthamster understood, let's see if we can upgrade to electron-11 after we get #1888 merged.

**Comment by slayerjain** [comment]
@jakolehm were we able to upgrade to Electron 11? Looks like that PR has been merged.

**Comment by bartoszhernas** [comment]
Hi, is there any planned work on M1 version of Lens? Can I somehow help if no one is working on it? (we've updated our Electron app to include separate ARM build, the process was fairly easy)

**Comment by mologie** [comment]
Kinda confusing: The download page shows "Download for Mac OS (Universal)" but the download is indeed just an Intel application. Just leaving that info here for those wondering why Lens runs so slow even though it was an apparently universal download.

**Comment by ameeno** [comment]
I am bumping this because this feature seems to have been forgotten by the devs. I have been watching each update with bated breath but nope, not even Beta 5.0 or the alpha's have any Darwin ARM64 (Apple M1) support.


ANd since Lens is a often used app of mine and I have an M1 Mac, It makes me sad that this was not made a priority by the team.

**Comment by gnomeria** [comment]
> Kinda confusing: The download page shows "Download for Mac OS (Universal)" but the download is indeed just an Intel application. Just leaving that info here for those wondering why Lens runs so slow even though it was an apparently universal download.

I really agree with this. It just seems misleading to put it with `(Universal)` text. Usually developers would name their updated apps that supported arm64 with `universal` to differentiate apps that would run non-natively.

![image](https://user-images.githubusercontent.com/3047437/116640580-1e63a480-a995-11eb-8978-d6298c8c5ebc.png)

**Comment by Nokel81** [comment]
Thanks for the note about it not being Universal we should change that asap. We have run into some difficulties upgrading our electron version. So that is the main point blocking this.

**Comment by andrei-dascalu** [comment]
It would be great to have M1 support. If there's mapower needed, I may be able to help though it's been a while since my last Electron encounter.

**Comment by wbe7** [comment]
Hello! Already working on a build for ARM? This is very important for all Mac owners with an M1 chip. The problem is that the Lens build on x86 runs through Rosseta and uses swap all the time. The constant use of swap has a very negative effect on the resource of our ssd drives. We kindly ask you to release the ARM version of Lens as soon as possible! I don't want to give up such a great tool because of the ssd feature. Many thanks!

**Comment by auzhva** [comment]
Hi,

To bump an issue.

On cluster with medium-to-high number of pods (like 1500+ pods) Lens on M1 is sluggish as hell.

Really looking forward for this upgrade!

Thank you,

**Comment by hugginsio** [comment]
Any updates from the team on the move up to Electron 11/12? (#3008)

**Comment by Nokel81** [comment]
Yup, we are currently working on the upgrade. We have had to investigate alternative integration testing libraries as Spectron no longer seems to be working. This is why it has taken a long time.

**Comment by dicolasi** [comment]
For the record, Lens now crashes on new installation with a M1 chip.

**Comment by andrei-dascalu** [comment]
Does it? Which build? I'm running a fresh install of 5.1.3-latest.20210722.1 on Air M1

**Comment by developerdino** [comment]
> For the record, Lens now crashes on new installation with a M1 chip.

I'm having the same issue every time I try to start it up as well. Reinstalled latest version last night and it worked for a bit then this morning same problem. I was trying to reconnect to a new EKS cluster, it hung, so I closed it and started it up again and it crashes on start up now.

**Comment by nevalla** [comment]
Latest 5.2 beta has M1 version available: https://api.k8slens.dev/binaries/beta-arm64.dmg

**Comment by isaac-mcfadyen** [comment]
There seems to be an error with the M1 build link (looks like it gives an Access Denied error; maybe not marked with an ACL of public-read in S3?).

**Comment by manat** [comment]
I can download using the above link yesterday. But for now, I think they've just recently released [5.2.0](https://github.com/lensapp/lens/releases/tag/v5.2.0).

https://api.k8slens.dev/binaries/Lens-5.2.0-latest.20210908.1.dmg

**Comment by hugginsio** [comment]
On my machine, the latest 5.2.0 release still runs as Intel and not natively as the beta did. Is anyone else seeing this behavior?

**Comment by isaac-mcfadyen** [comment]
@manat That link works. Thanks!

**EDIT:** It looks like that link leads to an Intel-only build, not an ARM/Universal build.  
  
@kjhx I think they only released it through a beta channel (the link that no longer works).

**Comment by baozitao** [comment]
> 

Is there any progress on arm version ？

**Comment by hugginsio** [comment]
> > 
> 
> 
> 
> Is there any progress on arm version ？

ARM downloads for macOS are available on https://k8slens.dev.

**Comment by baozitao** [comment]
> 

is it work on raspberry pi? M1 and macos is a special version of arm.

**Comment by Nokel81** [comment]
@baozitao It will not work on a raspberry, not only because of the different arch but also because of the different OS

**Comment by baozitao** [comment]
@Nokel81 is there any trouble in some components? I'm want to  complie it for arm

**Comment by Nokel81** [comment]
You could try, I am just saying that the apple silicon build won't work for you

**Comment by jweak** [comment]
> @Nokel81 is there any trouble in some components? I'm want to complie it for arm

@baozitao Check out this issue. You might need this workaround
https://github.com/lensapp/lens/issues/4600
