### ISSUE TITLE
connecting... clusters locks up UI

### ISSUE THREAD

**Issue by matti** [lensapp/lens#1757]
4.0.1, mac

![image](https://user-images.githubusercontent.com/3893/101920244-3e581e80-3bd4-11eb-915e-fef64bc038da.png)

**Comment by matti** [comment]
so like nothing can be clicked, have to quit lens

**Comment by MattFellows** [comment]
I get this too - everytime I restart my machine lens refuses to connect to the clusters untill I remove them all and restart lens, then re-add the clusters.  If I leave it too long before I do this, the UI locks up and I have to restart lens, before I can delete all my clusters, and re-add them

MacOS 10.15.7 (Catalina)
Lens: 4.0.8
Electron: 9.3.5
Chrome: 83.0.4103.122
Node: 12.14.1

**Comment by Nokel81** [comment]
Is this still happening on 4.1.4? If so, some logs would be useful

**Comment by Nokel81** [comment]
Closing as not able to reproduce on any recent version.
