### ISSUE TITLE
An extension cannot reliably ask Lens to activate a cluster

### ISSUE THREAD

**Issue by stefcameron** [lensapp/lens#1759]
After some hacking, this seems to work, although it doesn't _always_ work (not sure why):
```javascript
  Store.clusterStore.activeClusterId = clusterId;
  extension.navigate(`/cluster/${clusterId}`);
```

I noticed that `clusterStore` does not provide a `setActive(clusterId)` similar to `workspaceStore.setActive(wsId)` where the latter, when called, activates the workspace AND switches to it.

On the surface, it would be seem logical to have `clusterStore.setActive(clusterId)`, and when called, Lens activates the cluster AND switches the view to it.

Note that today, just doing `Store.clusterStore.activeClusterId = clusterId` will only _activate_ (or at least, seem to) the cluster (by putting a white square behind its icon in the left sidebar, like what happens when you click the icon), however it does NOT also navigate to that cluster.

**Comment by stefcameron** [comment]
@Nokel81 and @jim-docker FYI

**Comment by jim-docker** [comment]
Can you set Store.clusterStore.activeClusterId in an extension in 4.0.0? I get
```
Cannot assign to 'activeClusterId' because it is a read-only property.
```

**Comment by stefcameron** [comment]
Seems to be working OK: https://github.com/Mirantis/lens-extension-cc/blob/master/src/cc/store/ClusterActionsProvider.js#L356

I haven't noticed that -- but maybe that's a TypeScript error? I'm running JS in this case.

https://github.com/lensapp/lens/blob/master/src/extensions/stores/cluster-store.ts#L20-L29 shows there's a getter and a setter, so not sure why you'd have trouble.

Just doing that alone isn't "enough" for me, though. Still have to call `extension.navigate()`

**Comment by jim-docker** [comment]
Ah, I was using rc version of the extensions api, builds with 4.0.2, as you know :)

**Comment by Nokel81** [comment]
I have a branch (https://github.com/lensapp/lens/tree/issue-1759) with my changes. I'll be putting up a PR tomorrow some time.

**Comment by stefcameron** [comment]
> I have a branch (https://github.com/lensapp/lens/tree/issue-1759) with my changes. I'll be putting up a PR tomorrow some time.

@Nokel81 Reminder about ^^^ 🙂

**Comment by Nokel81** [comment]
@stefcameron thanks for the reminder, I was on PTO. There is a few items I want to clean up before making that change directly.
