### ISSUE TITLE
Kubernetes 1.20 has stopped propagating `selfLink`

### ISSUE THREAD

**Issue by nevalla** [lensapp/lens#1767]
**Describe the bug**

Kubernetes api server has stopped propagating `selfLink` (https://github.com/kubernetes/kubernetes/pull/94397) so Lens needs to use some other mechanism to detect/parse correct api for the resource. 

Related to #1711

**Comment by nevalla** [comment]
To reproduce `minikube start --kubernetes-version=1.20.0`

**Comment by tece81** [comment]
any idea how to solve this issue?
very interested!

**Comment by tece81** [comment]
as a work-around for us end-users found this:
https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/25#issuecomment-742616668

**Comment by ixrock** [comment]
@tece81 fix is coming! https://github.com/lensapp/lens/pull/1804

**Comment by jakolehm** [comment]
Fixed in #1804
