### ISSUE TITLE
Prompt for auto-update

### ISSUE THREAD

**Issue by panuhorsmalahti** [lensapp/lens#1768]
Changes the auto-update to not be automatic.

* If a new version is found during the application runtime, the user is asked _once_ in a prompt, e.g. "New version available. Would you like to update"?
* Adds auto-update section to e.g. Preferences page, which displays a button to update if a version is available.

Fixes #1701, #1689 and the groundwork for #1601.

**Comment by panuhorsmalahti** [comment]
This should be fairly straightforward to implement: https://www.electron.build/auto-update

**Comment by Nokel81** [comment]
I am targeting this at 3.6.10 so that users don't have to not quit lens to stay at that version. Will then cherry pick it to master.

**Comment by jakolehm** [comment]
Fixed in #1831.

**Comment by Nokel81** [comment]
No, there is still a PR open for 4.1

**Comment by jakolehm** [comment]
@Nokel81 ok, I'll change milestone.

**Comment by Nokel81** [comment]
finished by #1941 (though I still need to forward port the UI changes from 3.6 to that PR)
