### ISSUE TITLE
keyboard shorcuts

### ISSUE THREAD

**Issue by matti** [lensapp/lens#177]
- cmd+n for new cluster

**Comment by jakolehm** [comment]
Probably we want to have something like k9s shortcuts.

**Comment by MichaelSp** [comment]
Oh yes please! I need desperately!

**Comment by pcj** [comment]
Any progress here?  Seems like keyboard shortcuts are not getting the love they deserve :)

**Comment by matti** [comment]
no progress, no love

**Comment by Nokel81** [comment]
Closing in favour of https://github.com/lensapp/lens/issues/7583 as one unified request
