### ISSUE TITLE
Custom Helm Repos

### ISSUE THREAD

**Issue by ghost** [lensapp/lens#1770]
**What would you like to be added**:
GUI support for adding custom Helm repos via HTTP or GIT.

**Why is this needed**:
It's available in Rancher 2.5 via the Cluster Explorer. Feature gap in Lens.

**Environment you are Lens application on:**

- Kubernetes distribution: K3s
- Desktop OS: Darwin

**Comment by nevalla** [comment]
Fixed in #1368.

**Comment by ghost** [comment]
Missed the Pull. Fantastic. Thanks.
