### ISSUE TITLE
Alerts on pod failure

### ISSUE THREAD

**Issue by hemant-bhosale** [lensapp/lens#1783]
How can we the alerts for the pod in lens?

**Comment by nevalla** [comment]
Please could you elaborate a bit what kind of alerts do you mean?

**Comment by hemant-bhosale** [comment]
in lens we can see the pod status if its running or not. and lets say after new deployment pod went to failed state or shows some error, can I trigger alert that this pod is not running?

**Comment by Nokel81** [comment]
I believe that this would be best suited as an extension that can react to the status changes of kube objects.

**Comment by Nokel81** [comment]
Which is currently possible by querying the exported `PodsStore`.
