### ISSUE TITLE
Prometheus with route-prefix

### ISSUE THREAD

**Issue by ilkinmammadzada** [lensapp/lens#1787]
We have used reverse proxy (nginx-ingress) to expose our Prometheus (stable/prometheus-operator). 

Route-Prefix (/prom) was added to Prometheus URL: **http://prometheus-operator-prometheus:9090/prom**

Now Lens could not to connect Prometheus. 

Is there any way to connect Prometheus with use route-prefix?

**Comment by nevalla** [comment]
Did you try with `<namespace>/<service>:<port>/route-prefix` ?

**Comment by ilkinmammadzada** [comment]
Yes, I have tested it before.
This was cleared automatically when i "refreshed" page.

I tested it again after your comment and click other inputs then this was saved.
It works, thanks a lot!
