### ISSUE TITLE
visual differentiation (background color, custom css etc)

### ISSUE THREAD

**Issue by matti** [lensapp/lens#18]
to visually differentiate "prod" vs "qa" lenses

**Comment by aleksfront** [comment]
Could you elaborate the issue? What do you mean by `prod` and `qa` lenses?

**Comment by matti** [comment]
like if you have two pharos cluster - it is easy to accidentally use wrong lens because they look the same

**Comment by matti** [comment]
did it again (used wrong lens)

**Comment by Nokel81** [comment]
New issue for tracking this is https://github.com/lensapp/lens/issues/5287
