### ISSUE TITLE
Running Lens as a browser application

### ISSUE THREAD

**Issue by MeghanaSrinath** [lensapp/lens#1814]
We have developed an application and would like to integrate Lens with it. The idea is to launch Lens in a web browser from our application UI on click of a button. As of now, we can see Lens runs as desktop application. Can this be achieved?

**Comment by matti** [comment]
see https://github.com/supervisor-com/lens-web

**Comment by matti** [comment]
also #1037

**Comment by nevalla** [comment]
At this moment we don't plan to provide a browser version, so I'm closing this.
