### ISSUE TITLE
RBAC user with restricted user permission stoped listing pods in 4.x

### ISSUE THREAD

**Issue by shettyjm** [lensapp/lens#1820]
**Describe the bug**
I have created a user using [Permission Manager](https://github.com/sighupio/permission-manager). It is listing the pods just fine in the Lens version3.6. Kubectl get pods using this restricted permission user is showing listing the pods as well.

After auto-updating to 4.0.4, suddenly stopped working. 

See the attachment for more info.

**To Reproduce**
1. Create a user with limited RBAC permission using the Permission Manager.
2. Download the kubeconfig file for the  Permission Manager user
3. Add cluster using Lens 3.6 and kubeconfig from step 3
4. See the pod listing under lens UI Workloads-Pods
5. Try the same using Lens 4.0..4

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 4.0.4
- OS:  Mac OSX
- Installation method (e.g. snap or AppImage in Linux):

<img width="1279" alt="lns bug 2" src="https://user-images.githubusercontent.com/13169826/102720127-49cbd980-42a7-11eb-9de3-0f61d87686d4.png">
<img width="1280" alt="lens 4 0 4 bug " src="https://user-images.githubusercontent.com/13169826/102720130-4c2e3380-42a7-11eb-8dc2-951c4f853fc1.png">

**Comment by jirayuk** [comment]
I have issue too Y_Y

**Comment by f0rcas** [comment]
Have a same issue too, permission manager + lens 4.0.4 not working.

**Comment by jakolehm** [comment]
Have you tried [4.0.5](https://github.com/lensapp/lens/releases/tag/v4.0.5)?

**Comment by f0rcas** [comment]
Yes, doesn't work

**Comment by mpanchap** [comment]
Same issue!

**Comment by wccropper** [comment]
Experiencing this same issue.

**Comment by Nokel81** [comment]
Fixed by #2003

**Comment by f0rcas** [comment]
Checked on version 4.0.8, it works correctly
