### ISSUE TITLE
Connecting to a cluster bind: address already in use

### ISSUE THREAD

**Issue by matti** [lensapp/lens#184]
sometimes when switching back-n-forth between clusters:

![Lens](https://user-images.githubusercontent.com/3893/78033114-a0d2fc80-736e-11ea-875d-6327ac0e3524.png)

it doesn't seem to do anything, it connects successfully anyway.

**Comment by Nokel81** [comment]
Is this still a problem? I haven't seen this before.

**Comment by matti** [comment]
daily, but it just looks ugly - doesnt really do any harm

**Comment by Nokel81** [comment]
Might this have been fixed by https://github.com/lensapp/lens/pull/2692 which removes a race condition on specifying ports?

**Comment by Nokel81** [comment]
Is this still a problem?

**Comment by matti** [comment]
havent seen it anymore
