### ISSUE TITLE
Extension API for providing accessible namespaces for a cluster

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#1843]
**What would you like to be added**:

An extension API that allows an extension to provide list of accessible namespaces for a user/cluster.

**Why is this needed**:

Some Kubernetes distros have their own methods (usually CRDs) where accessible namespaces are described. It's not possible (or meaningful) for Lens to support all of these different cases -> extensions could provide this list.

**Comment by Nokel81** [comment]
Fixed by https://github.com/lensapp/lens/pull/3487
