### ISSUE TITLE
How to quick access to context project

### ISSUE THREAD

**Issue by nvthuong1996** [lensapp/lens#1844]
I have many project helm. 
Each project has a context for me to start typing command. Ex: source/project-x/k8s/, source/project-y/k8s/. Every time I open a terminal I have to cd into context. It takes time
Is there a quicker way to deal with that

**Comment by nevalla** [comment]
You can set Working directory in cluster settings, this might help a bit. Any suggestions how to improve this further?

**Comment by nvthuong1996** [comment]
thank you. i seen
