### ISSUE TITLE
Lens App is running in background. i am not able to view GUI

### ISSUE THREAD

**Issue by siva5974** [lensapp/lens#1845]
**Describe the bug**
Lens app is running in background i am not able to view GUI

**To Reproduce**
1. Click the Lens App in windows

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
- OS: Windows 10 version 1607
- Installation method (e.g. snap or AppImage in Linux): exe file

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
No logs as such
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

I checked the task manager, app looks to run in background. type renderer looks to be missing for lens process.
![image](https://user-images.githubusercontent.com/73332952/102966714-6e79b880-4516-11eb-9177-5663adfdb459.png)

**Comment by rmerkl** [comment]
I have the same issue with Windows 10 Pro 20H2 and Lens 4.0.6.
I see 3 Lens background services but no GUI when starting Lens.

**Comment by kaiffeetasse** [comment]
Same Issue here, even after reinstallation...
![image](https://user-images.githubusercontent.com/31049574/106738342-17d4c380-6618-11eb-8e0e-9c328e38f58f.png)

**Comment by siva5974** [comment]
I managed to fix this issue. Just deleted the **Appdata** created in my profile and reinstalled it.
C:\Users\XXXXXXXX\AppData\Roaming\Lens
