### ISSUE TITLE
Colorblind friendly metrics graph

### ISSUE THREAD

**Issue by mikaelkundert** [lensapp/lens#1852]
As a [colorblind](https://en.wikipedia.org/wiki/Color_blindness) I have trouble to see the difference between `Usage` and `Limits`.

![image](https://user-images.githubusercontent.com/93661/102994349-8f96d500-4527-11eb-94ce-3d124d4d7731.png)

I would expect get labels when hovering, but instead I have values labeled with colored boxes. That is inaccessible UX.

**What would you like to be added**:
* Add label when hovering the chart with the value, so that you see the color, label and the value

**Why is this needed**:
* Accessibility
* It will be [mandatory anyways in future](https://ec.europa.eu/social/main.jsp?catId=1202)

**Environment you are Lens application on:**

- Kubernetes distribution: Minikube
- Desktop OS: Ubuntu 20.04 LTS

**Comment by Nokel81** [comment]
Nominating for 5.0.0
