### ISSUE TITLE
Allow Lens Extensions to access Cluster Distribution Detector

### ISSUE THREAD

**Issue by juv** [lensapp/lens#1853]
**What would you like to be added**:
Allow Lens Extensions to access Cluster Distribution Detector
https://github.com/lensapp/lens/blob/master/src/main/cluster-detectors/distribution-detector.ts 

**Why is this needed**:
Lens Extensions might need to access information about the detected K8s distribution, e.g. to limit/enrich displayed information for certain distributions

**Comment by jakolehm** [comment]
This data is already available via `cluster.metadata["distribution"]`, (https://docs.k8slens.dev/v4.0.6/extensions/api/classes/_core_api_stores_.cluster/#metadata).

**Comment by juv** [comment]
That works indeed, thanks
