### ISSUE TITLE
hide menu bar icon

### ISSUE THREAD

**Issue by schmurfy** [lensapp/lens#1858]
**What would you like to be added**:
I would like to have the option to disable the menu bar icon, I have enough useful icon there and having Lens there has no point for me.

**Why is this needed**:
I just don't want it there :)

**Environment you are Lens application on:**

- Kubernetes distribution: irrelevant
- Desktop OS: OSX Big sur

**Comment by quantumsheep** [comment]
Is there any news on this?

**Comment by sanguino** [comment]
+1

**Comment by mscholze** [comment]
+1

**Comment by andytson-inviqa** [comment]
This will also be even more of an issue for M1 Pro/Max Macbooks.

Personally I have too many menu bar icons already. I don't want Lens to be a hideable app, just a regular app where clicking the red button closes it

**Comment by anhnvme** [comment]
+1

**Comment by whitingj** [comment]
+1 Please let me remove it

**Comment by jvaclavovic** [comment]
+1

**Comment by rbudiharso** [comment]
+1

**Comment by william-seaton** [comment]
+1

**Comment by dorianok** [comment]
+1

**Comment by nikmel2803** [comment]
+1
Especially relevant for MacBook with notch

**Comment by persus** [comment]
+1

**Comment by persus** [comment]
+1

**Comment by bencooper222** [comment]
+1

**Comment by snauhaus** [comment]
+1

**Comment by gerasimov-studio** [comment]
+1

**Comment by schmurfy** [comment]
now that you are rolling out your paid subscription you could at least let us remove that fu***ng icon !

**Comment by subos2008** [comment]
This is on page 1 of the issues list [sorted by comments](https://github.com/lensapp/lens/issues?q=is%3Aissue+is%3Aopen+sort%3Acomments-desc) - and **could be fixed very easily**.

**Comment by persus** [comment]
This menu bar item is not a feature, it's an annoyance. It would be a feature if one could configure it.

But much more annoying than this non-feature is this ignorance of the manufacturer. I am a product owner by profession and the satisfaction of my users is one of the most important goals.

I am very surprised that for such a simple thing, they don't respect the wishes of their users.

**Comment by DobleV55** [comment]
+1 any update?

**Comment by keys1234249** [comment]
+1 please let us remove the icon, its not very useful.

**Comment by bcb44** [comment]
Bump

**Comment by jannotti-glaucio** [comment]
+1 any update?

**Comment by Storager** [comment]
+1
In Silicon versions the notification bar is too small to spend the space like this. Apple oficially recommends to remove all the unnesessary icons. So give us such an option with your product. Or it is a paid option?

**Comment by itssimon** [comment]
+1 - Bumping and creating more noise so this gets attention.

**Comment by keys1234249** [comment]
+1 Bump, would really make a lot of people happy.

**Comment by gerasimov-studio** [comment]
More than two years have passed... Tell me honestly, is this your principled position - to leave a useless icon in such a small space on a MacBook Pro?

**Comment by miroslav-chandler** [comment]
+1

**Comment by filipvh** [comment]
+1

**Comment by actuallykane** [comment]
Fully paid product and yet too cheap to do anything. Also intentionally being malicious to open source alternatives (e.g. OpenLens and the default extensions now being seperate) really does show where your priorities lie.

**Comment by dkozhuhar** [comment]
+1 
PLease do this

**Comment by omermishania** [comment]
+1

**Comment by bohdantverdyi** [comment]
+1 Bumping

**Comment by junjie-landing** [comment]
+11111

**Comment by roger-carlsberg** [comment]
+1

**Comment by OvidiuMihalcea** [comment]
3 years later and still nothing for such a easy to implement feature? Wow!

**Comment by nicolamacoir** [comment]
+1

**Comment by todouu** [comment]
+1

**Comment by hirenpanchal1608** [comment]
+1

**Comment by jkroepke** [comment]
> 3 years later and still nothing for such a easy to implement feature? Wow!

Because the development of OpenLens has been stopped.

**Comment by schmurfy** [comment]
I switched to k9s and nothing is moving here so I am going to close this issue.

**Comment by cornzz** [comment]
+1

**Comment by VigneshwaranVenugopal** [comment]
+1

**Comment by modosm** [comment]
+1
