### ISSUE TITLE
k3os/k3s Cluster and Node stats not registering

### ISSUE THREAD

**Issue by gustaveherbst** [lensapp/lens#186]
Not sure if this a bug or not, perhaps it's just with the way Prometheus is being setup by default on a fresh install of k3os (k3s)

Message:
Metrics are not available due to missing or invalid Prometheus configuration.
Right click cluster icon to open cluster settings.

The service is exposed with traefik by default:
traefik-prometheus on port 9100 (ClusterIP)

Perhaps I am just doing this wrong, however, some advice or next steps would be appreciate since I would imagine as k3os starts to gain this might come up more often. I want to document the steps so others can benefit.

Thanks
DB

**Comment by jakolehm** [comment]
Did you set correct "Prometheus service address" via cluster settings?

**Comment by hamid-elaosta** [comment]
I came across Lens on HN today. I also cannot get the metrics to work with K3s built in metrics. 

I've configured  the service address to; `kube-system/traefik-prometheus:9100` which I've confirmed is correct in my cluster, but Lens still doesn't succeed in retrieving the metrics.

**Comment by mazay** [comment]
I have a similar issue. The Prometheus address is correct but it still shows:
```Metrics are not available due to missing or invalid Prometheus configuration. Right click cluster icon to open cluster settings.```

**Comment by gustaveherbst** [comment]
I had just scroll down and install the lens-prometheus option to get it to work. It does not interfere with the metric-server running but I'd like to understand further why this is not working natively with k3os

**Comment by fabiodcorreia** [comment]
I install prometheus-server and then I got the server metrics, I think the traefik-prometheus is just to send metrics from traefik to prometheus

**Comment by remkolems** [comment]
Installed latest release v3.4.0 and I also experienced similar issues. Very intrigued by this app! Looks stunning and easy. 

@DarkBlaez or @fabiodcorreia What exactly are the steps to solve this? What did you do precisely? Where do I scroll down? ==> Never mind. See my update below.

**Update 11 May 2020**
- Background information @ https://github.com/lensapp/lens/blob/master/troubleshooting/custom-prometheus.md

**Procedure how to solve**
1.  Open Lens
2. Right mouse click on cluster
![image](https://user-images.githubusercontent.com/45675902/81566507-45e3ea80-939b-11ea-9657-6199d008b50b.png)
3. Select Settings
4. Scroll down to Features
5. Install Metrics
See here @ https://github.com/lensapp/lens/tree/master/src/features/metrics
![image](https://user-images.githubusercontent.com/45675902/81566699-87749580-939b-11ea-9acc-0b7db77d30e2.png)
6. After install
![image](https://user-images.githubusercontent.com/45675902/81566890-cefb2180-939b-11ea-89d7-f6334eda5c32.png)
7. Close frame window (upper right corner)
![image](https://user-images.githubusercontent.com/45675902/81567001-f8b44880-939b-11ea-957f-b6ffd82699d8.png)
8. (Re) Connect to cluster by clicking on cluster icon.
9. Result (yes!)

![image](https://user-images.githubusercontent.com/45675902/81567107-1e415200-939c-11ea-93cf-5bfdfd673161.png)

**Comment by Nokel81** [comment]
Did anyone try specifying the existing prometheus settings?
