### ISSUE TITLE
Workspaces - user configurable order for list

### ISSUE THREAD

**Issue by ruizmarlon** [lensapp/lens#1861]
**What would you like to be added**:
Add the ability to reorder workspace list from `Workspaces` page
Example solution: "up"/'down" arrow on each line to reorder the list

**Why is this needed**:
Users need the ability to organize their workspace based on personal workflow and display preferences

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...] MKE, k0s
- Desktop OS: <the OS Lens app runs on in your case> MacOS Catalina 10.15.7

**Comment by jakolehm** [comment]
Workspace is replaced by Catalog.
