### ISSUE TITLE
Metrics are not available due to missing or invalid Prometheus configuration

### ISSUE THREAD

**Issue by kqsantacruz** [lensapp/lens#188]
**Describe the bug**
Fresh install of the most recent application (3.1.0), all seems to goes fine but metrics do not render. I pressed the 'Install' button under the 'Settings -> Features -> Metrics' area in our cluster. Everything seemed to go just fine (we're on GKE, Kernel Version | v1.15.9-gke.22). 

<img width="800" alt="Screen Shot 2020-03-31 at 10 31 07 AM" src="https://user-images.githubusercontent.com/9202012/78063675-73258d80-7345-11ea-8001-8e6b2eb7d947.png">

Both the kube-state-metrics deployment and prometheus statefulset seem to be up and running just fine, but:

<img width="551" alt="Screen Shot 2020-03-31 at 11 48 06 AM" src="https://user-images.githubusercontent.com/9202012/78063741-88022100-7345-11ea-9dbf-2ccac759301a.png">

I've scoured the Slack and Bug reports, but can't seem to find a solution. Mostly I'm not sure where to look to troubleshoot this further.

**To Reproduce**
1. Press the Install button under 'Settings -> Features -> Metrics'
2. Wait for everything to install
3. (optionally) restart Lens

**Expected behavior**
Metrics and charts to render in various places throughout the app.

**Screenshots**

**Environment (please complete the following information):**
- K8: Kernel Version | v1.15.9-gke.22
- Lens Version: 3.1.0
- OS: MacOS 10.12.6
- Installation method Direct download and run
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:

> /Downloads/Lens.app/Contents/MacOS/Lens
info: Checking for update
info: Update for version 3.1.0 is not available (latest version: 3.1.0, downgrade is disallowed).

(Then when pressing the install button)
starting to render resources...
processing file: ~/Lens.app/Contents/Resources/features/metrics/01-namespace.yml
raw file loaded
using as raw, no HB detected
processing file: ~/Lens.app/Contents/Resources/features/metrics/02-configmap.yml.hb
raw file loaded
processing HB template
HB template done
processing file: ~/Lens.app/Contents/Resources/features/metrics/03-service.yml
raw file loaded
using as raw, no HB detected
processing file: ~/Lens.app/Contents/Resources/features/metrics/03-statefulset.yml.hb
raw file loaded
processing HB template
HB template done
processing file: ~/Lens.app/Contents/Resources/features/metrics/04-rules.yml
raw file loaded
using as raw, no HB detected
processing file: ~/Lens.app/Contents/Resources/features/metrics/05-clusterrole.yml
raw file loaded
using as raw, no HB detected
processing file: ~/Lens.app/Contents/Resources/features/metrics/05-service-account.yml
raw file loaded
using as raw, no HB detected
processing file: ~/Lens.app/Contents/Resources/features/metrics/06-clusterrole-binding.yml
raw file loaded
using as raw, no HB detected
processing file: ~/Lens.app/Contents/Resources/features/metrics/10-node-exporter-ds.yml.hb
raw file loaded
processing HB template
HB template done
processing file: ~/Lens.app/Contents/Resources/features/metrics/11-node-exporter-svc.yml
raw file loaded
using as raw, no HB detected
processing file: ~/Lens.app/Contents/Resources/features/metrics/12-kube-state-metrics-clusterrole.yml
raw file loaded
using as raw, no HB detected
processing file: ~/Lens.app/Contents/Resources/features/metrics/12.kube-state-metrics-sa.yml
raw file loaded
using as raw, no HB detected
processing file: ~/Lens.app/Contents/Resources/features/metrics/13-kube-state-metrics-clusterrole-binding.yml
raw file loaded
using as raw, no HB detected
processing file: ~/Lens.app/Contents/Resources/features/metrics/14-kube-state-metrics-deployment.yml.hb
raw file loaded
processing HB template
HB template done
processing file: ~/Lens.app/Contents/Resources/features/metrics/14-kube-state-metrics-svc.yml
raw file loaded
using as raw, no HB detected
shooting manifests with: "~/Application Support/Lens/binaries/kubectl/1.15.10/kubectl" apply --kubeconfig /var/folders/5j/wmclf6_16h995js0m0hxv9sm0000gn/T//6u94vabmyu3-wuwm3d3scq-kubeconfig -o json -f /private/var/folders/5j/wmclf6_16h995js0m0hxv9sm0000gn/T/25f8021313e61608acc1a4fd2f0cfca8

**Comment by dany-phantom** [comment]
This happens to me in a GKE cluster as well.
Is there something blocking api service proxies in GKE?

**Comment by davi5e** [comment]
Maybe related, but can Lens use the default `metrics-server` created in the kube-system namespace if Resource consumption metering is enabled in the GKE cluster?

**Comment by Nokel81** [comment]
Is this still a problem with 4.1.4?

**Comment by matteovivona** [comment]
To "temporarily" workaround this issue with my private cluster, I added a firewall rule on port 9090

**Comment by Nokel81** [comment]
Closing in favour of #1731

**Comment by albertosouza** [comment]
> To "temporarily" workaround this issue with my private cluster, I added a firewall rule on port 9090

This woked for me, private GKE cluster and kube-prometheus-stack with lens auto detect setting.

**Comment by nanirover** [comment]
experiencing the same issue in Azure AKS, the lens is not showing any metrics. (CPU, Memory, Disk)
Error: Metrics are not available due to missing or invalid Prometheus configuration.

Prometheus is running fine on our end, we are able to pull metrics and Successfully integrated with Grafana.
Thanks in Advance.

**Comment by nanirover** [comment]
experiencing the same issue in Azure AKS, Lens is unable to pull any metrics
Error: Metrics are not available due to missing or invalid Prometheus configuration
Prometheus is running fine on our end, we are able to pull metrics and Successfully integrated with Grafana

**Comment by algojack** [comment]
experiencing same issue on AWS EKS with latest lens 6.1.12:
Lens: 2022.11.101953-latest
Extension API: 6.1.19
Electron: 19.1.5
Chrome: 102.0.5005.167
Node: 16.14.2

**Comment by abarqawi** [comment]
@nanirover i solved it on AKS by installing prom using this on default ns and it start working !

helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install prometheus prometheus-community/kube-prometheus-stack

![image](https://user-images.githubusercontent.com/16225699/215329858-a38e1bff-cca2-4a11-b079-046a6049ec8d.png)

**Comment by choyshaowei** [comment]
> helm install prometheus prometheus-community/kube-prometheus-stack

this works for AWS EKS too

**Comment by boomam** [comment]
I use the same helm chart as noted by @abarqawi, 
Using as default, the metrics show in Lens.
However if i redeploy, with a values.yaml that sets pod logging to warning, adds persistent storage and disables Grafana, as soon as the alert manager pvc gets deployed, I lose the metrics in Lens again.
Very strange.

**##EDIT 1**
Correction, the pod metrics show - but cluster/node metrics do not.

**##EDIT 2**
Correction again, the cluster metrics just showed for me after i re-added columns under nodes for cpu/mem - that bit could be coincidence though in all fairness.
Maybe they only display after an hour or so's worth of data?

**Comment by NapalmCodes** [comment]
I am having the same problem with prometheus installed via operator and functional with grafana etc. I did have my cluster off so I am curious if its a data volume situation or not as described above.

> To "temporarily" workaround this issue with my private cluster, I added a firewall rule on port 9090

What kind of firewall rule are we talking about here @matteovivona ? I am on windows so are we saying in windows firewall or maybe port forwarding on my home network?

**Comment by mbehm** [comment]
I'm again having this issue despite grafana, prometheus and everything else working totally fine. At least make the error message more descriptive so I could try to figure out what is wrong again. 

I can proxy the same prometheus address through Lens and query the metrics just fine, everything in the cluster eg. grafana and autoscalers etc. that rely on the metrics work just fine, it's just Lens going "Metrics are not available due to missing or invalid Prometheus configuration.".

**Comment by luis-fnogueira** [comment]
> @nanirover i solved it on AKS by installing prom using this on default ns and it start working !
> 
> helm repo add prometheus-community https://prometheus-community.github.io/helm-charts helm repo update helm install prometheus prometheus-community/kube-prometheus-stack
> 
> ![image](https://user-images.githubusercontent.com/16225699/215329858-a38e1bff-cca2-4a11-b079-046a6049ec8d.png)

This has worked on OCI.

**Comment by gimlichael** [comment]
What eventually solved my issue was this command on the host:

```
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -F
```

For reference; this was on an ARM based VPS provided by Oracle Cloud Infrastructure (OCI).

**Comment by ashishmahamuni21** [comment]
in my case, i found that there are 2 installations of Prometheus, one is in my monitoring namespace and second one is in default namespace.
deleted one of the old service resolved.
