### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by aleksfront** [lensapp/lens#1883]
Annoying error popping up in the console every time lens starts/reloads.

<img width="595" alt="maximum call stack" src="https://user-images.githubusercontent.com/9607060/103339557-b3f83180-4a92-11eb-8152-6057f2c6c46f.png">

**Comment by Nokel81** [comment]
I haven't noticed this recently. Is this still a problem?

**Comment by Nokel81** [comment]
Fixed by #2963

**Comment by mrnonz** [comment]
Hello @Nokel81 Still found on
```
Lens: 2024.1.300751-latest
Extension API: 6.10.33
Electron: 27.2.4
Chrome: 118.0.5993.159
Node: 18.17.1
````

![Screenshot 2024-03-06 at 10 35 19](https://github.com/lensapp/lens/assets/9113726/1cd5f51a-25f9-45d6-8bf1-a0938fbd2523)

**Comment by rishenco** [comment]
I have this issue too. Any workaround yet?
