### ISSUE TITLE
How to add helm stable helm repo

### ISSUE THREAD

**Issue by maithanhtan** [lensapp/lens#1886]
Hi,
I had try to find the way to add stable helm repo: https://charts.helm.sh/stable in lenapp
But seem the helm repo list do not have this repo

- Is there anyway i can add it
- Can we show the repo url in helm repo list for easy detect the repo we will used to add

Thanks

**Comment by pashevskii** [comment]
Hi, It should be resolved in 4.1.0 version, [the commit](https://github.com/lensapp/lens/pull/1368)
