### ISSUE TITLE
Pod status is wrong when pod is being terminated

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#1893]
**Describe the bug**

Pod shows "Container creating" status when pod is being terminated.

**To Reproduce**

Scale down deployment via terminal and watch pod list view/status column.

**Comment by jgrasett** [comment]
I've noticed this as well during a release deployment today.

**Comment by cristianorvf** [comment]
I can verify this is true.
**Cluster**
v1.19.10+k3s1

**Lens**
Lens: 4.2.2
Electron: 9.4.0
Chrome: 83.0.4103.122
Node: 12.14.1

**Comment by Nokel81** [comment]
@cristianorvf Are you able to provide an screenshot, we don't (or no longer) have the text `"Container creating"` in our repo and I cannot seem to reproduce this.

**Comment by cristianorvf** [comment]
> @cristianorvf Are you able to provide an screenshot, we don't (or no longer) have the text `"Container creating"` in our repo and I cannot seem to reproduce this.

Hi @Nokel81, of course.

Cluster software: v1.19.10+k3s1 installed via k3sup with no options (vanilla) 

[Video of command line](https://youtu.be/nlSryIyuvTc)

[Video of lens](https://youtu.be/xp7_KPOClJM)

![Screen Shot 2021-04-20 at 12 33 27](https://user-images.githubusercontent.com/7475439/115423973-a21ed380-a1d4-11eb-88a5-5f681224b806.png)

MD5 (Lens-4.2.2.dmg) = 805fa36e14f91f761519a2d152953e22

But most important, the final outcome IS OK, meaning, pods are terminated correctly etc.. might be a UI thing only.

**Comment by Nokel81** [comment]
Almost certainly a UI thing, since we generate those strings. Thanks for the reproduction steps.
