### ISSUE TITLE
Accessing Terminal or Pod Shell remains connecting

### ISSUE THREAD

**Issue by christmagro** [lensapp/lens#1900]
When opening a terminal or Shell Pod it remains connecting and never connects, on same machine using Kubectl on cmd to access terminal worked without any issues thus permissions are definitely not an issue. This functionality was working few weeks ago and stopped working after updating 4.0.5, however going back to older versions didn't work. I followed another similar issue thread https://github.com/lensapp/lens/issues/137. I followed thread suggestions and I am running K8 version 1.16.15-gke.4300 and binaries are correctly downloaded. I have removed cluster an re-added onto lens without success. I am running on Windows 10.

Your help would be greatly appreciated
![IssueWithTerminal](https://user-images.githubusercontent.com/2184974/103651643-36d12e80-4f62-11eb-8f61-e9ce52b57ddb.png)
![IssueWithShell](https://user-images.githubusercontent.com/2184974/103651646-3769c500-4f62-11eb-9465-c00013230621.png)

**Comment by jim-docker** [comment]
Does this happen only with the K8 version 1.16.15-gke.4300/Windows 10 combination?

**Comment by christmagro** [comment]
Tried to connect with a different cluster version (1.19.5), with same issue. Problems seems reside when application tries to open the CMD terminal on windows from lens (i.e. issue is not related with the connection to the cluster but just the terminal is failing thus the Kubctl command is not being executed since terminal is not available. In fact all other functions such logs, deployments, creating resource, etc all work fine)

**Comment by christmagro** [comment]
Just an update from my end, updated Docker on my machine and also reinstalled Chrome (not sure if this has to do) and Lens terminal is now working correctly and also managing to connect with any POD. So issue was resolved hope this can be of help for anyone facing same/similar problem

**Comment by jim-docker** [comment]
Thanks @christmagro !
