### ISSUE TITLE
Lens not showing all menus

### ISSUE THREAD

**Issue by strus38** [lensapp/lens#1904]
Using Lens 4.0.6 on Windows the application does not display all the sub-menus
![image](https://user-images.githubusercontent.com/5890515/103782555-e4fad800-5037-11eb-8a7a-508c85769559.png)

Missing: 'Endpoints', 'Ingresses', 'Network policies', Events, namespaces, etc...

1. The cluster is accessed via jump hosts from a windows workstation
2. Open the port to have access from Windows to the target cluster
ssh -L 6443:localhost:6443 -J user@jumpserver root@masterk8s
3. Open Lens and configure to remove the certificate check and point to https://localhost:6443

**Expected behavior**
The standard menu of Lens with all content as in 4.0.1 for exemple.

**Comment by jim-docker** [comment]
Are there RBAC restrictions in your cluster? This is a common side effect if so.

**Comment by strus38** [comment]
Well, it seems to be a temporary issue. I have retried on a newly deployed
cluster and it is fine now.

Le lun. 11 janv. 2021 à 15:16, Jim Ehrismann <notifications@github.com> a
écrit :
