### ISSUE TITLE
Apps/Chart menu won't display charts used within the cluster

### ISSUE THREAD

**Issue by strus38** [lensapp/lens#1910]
**Describe the bug**
Lens 4.0.6 windows

**To Reproduce**
1. deploy some helm charts in the cluster from local files (no repositories)
2. go in apps/Chart
3. Nothing is displayed
![image](https://user-images.githubusercontent.com/5890515/103903738-92372400-50fc-11eb-826d-f3cdcf569271.png)

**Expected behavior**
I would expect all charts to be displayed
probably based on what is available from the labels: app.kubernetes.io/managed-by=Helm

**Environment (please complete the following information):**
- Lens Version: 4.0.6
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux): Windows installer

**Logs:**
no logs available

**Additional context**
There is no known way to enter a list of Helm registry to look for.

**Comment by jim-docker** [comment]
Helm charts deployed from local files won't show up on this page. Are the deployments shown under the releases tab?

**Comment by strus38** [comment]
yes they do:
![image](https://user-images.githubusercontent.com/5890515/104278556-1563cb80-54a9-11eb-941c-349da8701441.png)

So I guess the behovior is then 'normal'?

**Comment by jim-docker** [comment]
Yes, the charts that you would see under the "Charts" tab correspond to those from the selected repos ("File" -> "Preferences" -> Helm
