### ISSUE TITLE
node-shell pods are pending

### ISSUE THREAD

**Issue by matti** [lensapp/lens#192]
when opening node-shells and deleting nodes the pods are left behind trying to schedule for a deleted node

**Comment by vleungcrypto** [comment]
I am the same issue on my eks.  Before the solution come out, is there any manual way to solve this problem?  Thanks.

**Comment by matti** [comment]
delete the pods

**Comment by vleungcrypto** [comment]
I tried delete the pods, but it will recreate after 2 minutes.

**Comment by matti** [comment]
aah, they are created by some controller, check which controller creates them and delete that? Job maybe?

**Comment by vleungcrypto** [comment]
I can't find the related controller on Lens.  The source code shows it use k8sApi.createNamespacedPod() to create the pod

```
await k8sApi.createNamespacedPod("kube-system", pod).catch((error) => {
      logger.error(error)
      return false
    })

```
(https://github.com/lensapp/lens/blob/master/src/main/node-shell-session.ts#L57-L93)

**Comment by doryanmzr** [comment]
is it possible to delete those pods? I have the same issue

**Comment by vleungcrypto** [comment]
I have tried delete those pods manually, but it will be re-created after 2 mins.  I can't figure out any controller for those pods.

> is it possible to delete those pods? I have the same issue

**Comment by Nokel81** [comment]
I would like to ask for some clarification. What do you mean by "node-shell"s. Do you mean opening the terminal within lens for a node? Because when I do that I do not have access to `kubectl` so I cannot delete any pods. Or do you mean that while such shell is open, if you then go and try and delete a pod kubernetes continues to try and schedule the pods.

Thank you.

**Comment by matti** [comment]
Uh, I think we all need clarification on your clarification.

So node shell is the nsenter feature of lens where you can start a root shell in a node. These nsenter pods are left behind.

**Comment by Nokel81** [comment]
I think some pictures might help us. I have looked up what `nsenter` is and believe that we are talking about the same thing.

<img width="1527" alt="Screen Shot 2020-06-19 at 9 15 07 AM" src="https://user-images.githubusercontent.com/8225332/85289541-a0299e00-b465-11ea-83a8-c65bc25845e2.png">

<img width="1527" alt="Screen Shot 2020-06-19 at 9 18 12 AM" src="https://user-images.githubusercontent.com/8225332/85136591-d371f000-b20d-11ea-9af6-666f3f039b9b.png">

From what I understand the terminal window in the second screenshot is using `nsenter`. I am just having trouble understanding what you mean by "left behind"

**Comment by lehno** [comment]
Im unable to delete this pod as well

**Comment by Nokel81** [comment]
Do you mean that you cannot delete the pod after closing the tab?

**Comment by lehno** [comment]
After restarting k8s lens, it seems it stopped trying to install the pod on a non-existing node. Thanks

**Comment by Nokel81** [comment]
This has been fixed in the `vue_react_migration` branch.
