### ISSUE TITLE
Visible Items Should Reflect Actual Cluster State

### ISSUE THREAD

**Issue by ghost** [lensapp/lens#1921]
**Describe the bug**
Sometime over the last two weeks a Lens update seems to have caused issues presenting the actual current state of the cluster. To view the accurate current state of Pods, for example, I now have to click a different menu item then click Pods again to come back and see what I was looking at before was incorrect. I first noticed this problem using `watch` and seeing that Lens is consistently out of date when left viewing just one screen.

**To Reproduce**
1. Launch a Pod with K3d
2. Give the Pod an Init Container
3. View Pods in Lens
4. Restart Init Container from CLI and observe Lens Pod status go stale.

**Expected behavior**
A more accurate representation of my cluster state, even if this is only a K3d issue.

**Screenshots**
n/a

**Environment (please complete the following information):**
- Lens Version: 4.0.6
- OS: Darwin
- Installation method (e.g. snap or AppImage in Linux): AppImage

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by matti** [comment]
happens in GKE as well multiple times a day

**Comment by Nokel81** [comment]
@balibebas Is this still a problem in `4.1.3`? There were some fixes to how Lens pulls data in the `4.1` release.

Note: this still requires `watch` permissions.

**Comment by ghost** [comment]
I'm AFK but let's assume it was fixed and let the issue tracker do its thing. Thanks to the authors for this great project.
