### ISSUE TITLE
crash on edit resource (every time)

### ISSUE THREAD

**Issue by matti** [lensapp/lens#1923]
https://www.youtube.com/watch?v=K3FuI-T-xeM&feature=youtu.be

edit resource, try to duplicate it

**Comment by aleksfront** [comment]
@matti I can not reproduce the issue, services updated as expected. Could you provide a bit more information? It happens anywhere else but services? Can you also reproduce it in dev environment to see a bit more verbose error output?

**Comment by jakolehm** [comment]
@matti does this happen only with kube 1.20.x?

**Comment by aleksfront** [comment]
@matti Can you repeat this steps to see what object is received after you hit "Save" button in `Edit Resouce` tab?
1. Open up devtools (`Cmd+Shift+I`).
2. Go to Services page.
3. Edit your service as you did before.
4. Open Network tab in devtools and find watch request.
5. Open `EventStream` tab and copy `Data` field contents with object you just edited.

https://user-images.githubusercontent.com/9607060/104173370-b81f3a00-5416-11eb-83dc-1bd257ce0fe3.mov
