### ISSUE TITLE
Starting two local terminal sessions freezes app

### ISSUE THREAD

**Issue by ghost** [lensapp/lens#193]
**Describe the bug**

When I start a (local) terminal session, exit, and try to start another one, the app completly freezes and must be killed.

When I start a local terminal session, start another one, exit the second one and exit the first one,  the app completly freezes and must be killed.

**To Reproduce**

1. Start lens
2. Select a Cluster
3. Click on + button on bottom line, choose "Terminal session"
4. A windows command prompt appears.
5. Close the Terminal tab by clicking on X
6. One more, click on + button on bottom line, choose "Terminal session"

In the tab that appears now, it just says "Connecting ..." and "Closed by "" (code: 1006)" after some time. Lens becomes fully unresponsive.

Or

3. Click on + button on bottom line, choose "Terminal session"
4. A windows command prompt appears.
3. Click on + button on bottom line, choose "Terminal session"
4. A second tab with windows command prompt appears.
5. Close the second Terminal tab by clicking on X
6. Close the first Terminal tab by clicking on X

**Expected behavior**

Users should be able to open and close as many terminal tabs as they want.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 3.1.0
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux):  setup.exe

Note: I have the new Windows Terminal (https://github.com/microsoft/terminal) installed.

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:

Nothin special is in the log, just the startup blurb:

```
info: Checking for update
info: Update for version 3.1.0 is not available (latest version: 3.1.0, downgrade is disallowed).
```

**Comment by jakolehm** [comment]
Does this still happen?

**Comment by ghost** [comment]
Just checked. This does not happen any more. As both windows terminal as well as lens received a gazillion updates since april, this bug seems to have been vanished somehow.
