### ISSUE TITLE
Pods, Cpu and Memory charts not loading in Nodes tab

### ISSUE THREAD

**Issue by ilikosha** [lensapp/lens#1931]
Hi i have couple very strange issue
1. When you open Nodes tab -> select your node -> and scroll down to tab Pods, Cpu and Memory charts not loading. But other charts in Cluster tab or if you directly open Pods(Except Filesystem charts(this is second issue)) working fine.
2. When you open Pods and then select Filesystem tab i get message "Metrics not available at the moment" but when i open Persistence volume claim i see Disk usage chart.

Kubernetes v1.20.0
Prometheus:v2.23.0
node-exporter:v1.0.1
kube-state-metrics:v1.9.7

**Comment by ilikosha** [comment]
added screenshots for questions
1.
![](https://i.ibb.co/CmFVxNd/error.jpg)
</img>

2.
![](https://i.ibb.co/g7ttMK5/error2.jpg)
</img>

**Comment by nevalla** [comment]
1. Pod metrics in node details are fetched from metrics api and requires metrics-server (some legacy still here). Those needs to be converted to use prometheus.

2. Pod file system is different metric than PVC disk usage. It uses `container_fs_usage_bytes` prometheus metric. How did you install prometheus?

**Comment by ilikosha** [comment]
> 1. Pod metrics in node details are fetched from metrics api and requires metrics-server (some legacy still here). Those needs to be converted to use prometheus.
> 2. Pod file system is different metric than PVC disk usage. It uses `container_fs_usage_bytes` prometheus metric. How did you install prometheus?

Hi nevalla thank you for you assistance.
I used the manifests that Lens recommend in Features tab (before install button).

_Enable timeseries data visualization (Prometheus stack) for your cluster. Install this only if you don't have existing Prometheus stack installed. You can see preview of manifests [here](https://github.com/lensapp/lens/tree/master/extensions/metrics-cluster-feature/resources)._

And install it all .

**Comment by ilikosha** [comment]
Lens 4.0.7
Still not working.
Noticed that all working with kubernetes v1.19.2 and less (node-exporter v1.0.1 and kube-state-metrics v1.9.7).
All problems appeared when i upgrade my cluster on v1.20.0 (node-exporter v1.0.1 and kube-state-metrics v1.9.7)

**Comment by ilikosha** [comment]
I found the root of the problem.
Had a minute of free time and i started to invistigate errors in Developer tools in Lens
And found only one error when i open tabs.
cancelableFetch.ts:33 GET http://7868991a-8750-434d-8f17-062bdaf946c9.localhost:23019/api-kube/apis/metrics.k8s.io/v1beta1/pods 404 (Not Found)

I decide to compare with old cluster and whoila! There no error like this

i opened cli and start check api
kubectl describe apiservice v1beta1.metrics.k8s.io
old cluster return to me

    Name:         v1beta1.metrics.k8s.io
    Namespace:
    Labels:       <none>
    Annotations:  <none>
    API Version:  apiregistration.k8s.io/v1
    Kind:         APIService

but new cluster do not returned to me anything.
i google it and found that metrics.k8s.io its a part of ... metrics server and i forgot to install that.

**Comment by richardthombs** [comment]
> 1. Pod metrics in node details are fetched from metrics api and requires metrics-server (some legacy still here). Those needs to be converted to use prometheus.
> 2. Pod file system is different metric than PVC disk usage. It uses `container_fs_usage_bytes` prometheus metric. How did you install prometheus?

Is there any estimate for when this information will be pulled from prometheus instead? I would rather not install metrics server and prometheus on my tiny home cluster :)
