### ISSUE TITLE
ZIP Release: invalid macOS application signature, permissions and contents.

### ISSUE THREAD

**Issue by 0x2b3bfa0** [lensapp/lens#1932]
**Describe the bug**

The zipped prebuilt application for macOS has some corrupted files.

**To Reproduce**
1. Go to https://github.com/lensapp/lens/releases/tag/v4.0.6
2. Download [`Lens-4.0.6-mac.zip`](https://github.com/lensapp/lens/releases/download/v4.0.6/Lens-4.0.6-mac.zip)
3. Extract the file.
4. Double-click on the application.

**Expected behavior**

The application should open.

**Actual behavior**

A finder dialog pops up stating that _«The application "Lens" can't be opened»_.

**Environment (please complete the following information):**
- Lens Version: 4.0.6
- OS: macOS Catalina 10.15.7
- Installation method: ZIP file.

**Logs**
```console
$ /···/Lens.app/Contents/MacOS/Lens
zsh: permission denied: /···/Lens.app/Contents/MacOS/Lens
$ chmod 755 "$_" && "$_"
dyld: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /···/Lens.app/Contents/MacOS/Lens
  Reason: no suitable image found.  Did find:
	/···/Lens.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/···/Lens.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1
zsh: abort      /···/Lens.app/Contents/MacOS/Lens
```

**Comment by 0x2b3bfa0** [comment]
Can't reproduce with the DMG release, it looks like the only affected artifact is the ZIP file.

**Comment by jakolehm** [comment]
@0x2b3bfa0 MacOS zip is used only for auto-updates.

**Comment by 0x2b3bfa0** [comment]
Thank you, @jakolehm. Wouldn't be great to add some special suffix to these files to avoid mistakes to first-time users?

**Comment by 0x2b3bfa0** [comment]
Thank you, @jakolehm! Mystery solved!
