### ISSUE TITLE
Cluster events timestamps

### ISSUE THREAD

**Issue by ghost** [lensapp/lens#1939]
**What would you like to be added**:

In the cluster tab, at the bottom there's the latest events. While it's possible to click on each to get the timestamp, it would be nice if a column displaying it was added.

**Why is this needed**:

Quality of life improvement

**Environment you are Lens application on:**

- Kubernetes distribution: AKS
- Desktop OS: macOS

**Comment by nevalla** [comment]
I agree, it will definitely make life easier. Perhaps just to add `Age` column like Workload Overview has?

**Comment by ghost** [comment]
Age would work. As long as we can sort by newer for example. Just having a way of knowing when something happened. Say you get alerted of an issue, you check the state of the cluster and you can see quickly if an event was trigged recently or 3 days ago.
