### ISSUE TITLE
Can't get metrics working

### ISSUE THREAD

**Issue by korjavin** [lensapp/lens#1942]
**Describe the bug**
Whatever settings I use for promql backend, metrics are failed to read.
Grafana reads well at the same time.

Perhaps the problem is that I use prometheus-in-place replacement VictoriaMetrics, and it can't be detected through expected services or whatever.

Please, give us an opportunity to specify just url to promql-endpoint, without autodetect-magic.

like https://mydomain.tld/path/to/api

**Screenshots**
![image](https://user-images.githubusercontent.com/148765/104234584-b1b7af00-5464-11eb-81cf-68436bc0366f.png)

**Environment (please complete the following information):**
- Lens Version: 4.0.6
- OS: Debian linux
- Installation method (e.g. snap or AppImage in Linux): AppImage

**Comment by nevalla** [comment]
At this moment Lens can fetch metrics only via service running inside the cluster. Is VictoriaMetrics running inside the cluster? If yes then you can point to fetch metrics by setting `<namespace>/<service>:<port>/path/to/api`

**Comment by korjavin** [comment]
Yes. it works inside the cluster, and i tried to provide <namespace>/<service>:<port>/path/to/api but still something is wrong.

Can't get it working and don't understand how to debug/log it.

**Comment by korjavin** [comment]
![image](https://user-images.githubusercontent.com/148765/104319780-69df6900-54f2-11eb-9672-1f807e4fe4ec.png)
![image](https://user-images.githubusercontent.com/148765/104319815-79f74880-54f2-11eb-9c82-ff6747b96e44.png)

**Comment by korjavin** [comment]
```
# curl -X POST 10.8.3.209:8481/select/0/prometheus/api/v1/query?query=up

```

works perfectly from "inside the cluster".

**Comment by nevalla** [comment]
what does, for example, `curl -X POST 10.8.3.209:8481/select/0/prometheus/api/v1/query?query=container_cpu_usage_seconds_total` return? Just thinking if the metrics do not contain all the labels Lens is expecting.

**Comment by korjavin** [comment]
Perhaps you are right.

So, it could be  kube-state-metrics daemon then ?

**Comment by korjavin** [comment]
Seems so. I think I have to close this one.

**Comment by schmurfy** [comment]
@korjavin did you manage to solve this issue ? and if so, how ?
I installed kube-state-metrics from the lens manifests alongside victoriametrics but I don't have these metrics

**Comment by korjavin** [comment]
Nope, I couldn't. This part seems broken.

**Comment by schmurfy** [comment]
after digging a bit more I found how to solve it, the issue is that you need a specific config to instruct vmagent to read metrics from kubernetes (these come from cadvisor which is inside the kubelet process served by kubernetes service api), I found it here: https://github.com/VictoriaMetrics/operator/blob/185e3d1c5b47215606ac24b966d09740685f6439/docs/quick-start.MD#vmnodescrape

After adding this entity (I am using the operator) I now have the metrics !

Edit: switching from prometheus to VictoriaMetrics feels a bit like assembling a puzzle, you need to find every pieces and how they fit until you got everything back... At least now I understand each part of my monitoring.

**Comment by vainkop** [comment]
> after digging a bit more I found how to solve it, the issue is that you need a specific config to instruct vmagent to read metrics from kubernetes (these come from cadvisor which is inside the kubelet process served by kubernetes service api), I found it here: https://github.com/VictoriaMetrics/operator/blob/185e3d1c5b47215606ac24b966d09740685f6439/docs/quick-start.MD#vmnodescrape
> 
> After adding this entity (I am using the operator) I now have the metrics !
> 
> Edit: switching from prometheus to VictoriaMetrics feels a bit like assembling a puzzle, you need to find every pieces and how they fit until you got everything back... At least now I understand each part of my monitoring.

@schmurfy Can you describe in more detail how did you fix it?

I can see the code you've referenced in the current version of VM helm chart https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml#L651 but Lens is not showing anything.

**Comment by schmurfy** [comment]
@vainkop do you see some metrics or none ?
In my case I had all pod metrics and cluster metrics but was missing only the node metrics

**Comment by vainkop** [comment]
> @vainkop do you see some metrics or none ?
> In my case I had all pod metrics and cluster metrics but was missing only the node metrics

I see no metrics on the main cluster page, which usually shows requests/limits. Only a standard error is shows which I usually see when smth is wrong with Prometheus stack.

**Comment by schmurfy** [comment]
check that your prometheus install is fine, port forward the prometheus port and query the  `/metrics` endpoints

**Comment by vainkop** [comment]
> check that your prometheus install is fine, port forward the prometheus port and query the `/metrics` endpoints

Well it is kind of fine since I can see all metrics inside grana dashboards which come with VM helm chart.

I'm trying to use VM helm chart & subcharts without any modifications so I'm using this one for VM stack installation:
https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack

I've changed only this part https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml#L564-L597
Enabled ingress, adjusted urls, enabled tls & it works ok.
The rest I've left unchanged.
The current version is 0.3.3. Too bad tags or releases aren't used in this repo.

Here's how I ran it:
```
kubectl config set-context --current --namespace=monitoring
helm repo add grafana https://grafana.github.io/helm-charts
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo add vm https://victoriametrics.github.io/helm-charts/
helm repo update
helm install vm vm/victoria-metrics-k8s-stack -f=helm-values.yml
```

Probably many things changed in this chart since you tried did. Do you have a chance to use up to date version & share which parameters you're using?

Btw I'm running on EKS 1.21 on Ubuntu nodes

**Comment by korjavin** [comment]
For me, VM stack and lens don't work together.

Whatever I put as metric url, it works for curl, but not for lens.

**Comment by schmurfy** [comment]
I am using the victoriametrics operator with `node-exporter` and `kube-state-metrics` installed directly from yaml manifests so it will be hard to compare our setups xD

What I did is look at lens source code for the exact metrics queried on prometheus, port forward your prometheus/victoriametrics port, query `/metrics` (or look in grafana in explore) and make sure they are available.

Once you do that check that your cluster monitoring configuration in Lens is correct, I had to set it to Helm and provide the service by hand which in my case is: `monitoring-system/vmsingle-vmsingle:8429`

Once that was done I disconnected and connected back to the cluster and I had my graphs (Lens does not use the new metrics config until your restart or reconnect to the cluster).

**Comment by vainkop** [comment]
> I am using the victoriametrics operator with `node-exporter` and `kube-state-metrics` installed directly from yaml manifests so it will be hard to compare our setups xD
> 
> What I did is look at lens source code for the exact metrics queried on prometheus, port forward your prometheus/victoriametrics port, query `/metrics` (or look in grafana in explore) and make sure they are available.
> 
> Once you do that check that your cluster monitoring configuration in Lens is correct, I had to set it to Helm and provide the service by hand which in my case is: `monitoring-system/vmsingle-vmsingle:8429`
> 
> Once that was done I disconnected and connected back to the cluster and I had my graphs (Lens does not use the new metrics config until your restart or reconnect to the cluster).

Sounds like switching to helm & pointing to the vm service should work. I'll try & report.

**Comment by korjavin** [comment]
Perhaps it works for vm-single.

For my cluster-version of VM  I tried everything.
![image](https://user-images.githubusercontent.com/148765/128903241-f959575f-2ed7-44da-95dc-6931e816b893.png)

I know that it's a correct service in settings, but it still doesn't work.

**Comment by vainkop** [comment]
> > I am using the victoriametrics operator with `node-exporter` and `kube-state-metrics` installed directly from yaml manifests so it will be hard to compare our setups xD
> > What I did is look at lens source code for the exact metrics queried on prometheus, port forward your prometheus/victoriametrics port, query `/metrics` (or look in grafana in explore) and make sure they are available.
> > Once you do that check that your cluster monitoring configuration in Lens is correct, I had to set it to Helm and provide the service by hand which in my case is: `monitoring-system/vmsingle-vmsingle:8429`
> > Once that was done I disconnected and connected back to the cluster and I had my graphs (Lens does not use the new metrics config until your restart or reconnect to the cluster).
> 
> Sounds like switching to helm & pointing to the vm service should work. I'll try & report.



> I am using the victoriametrics operator with `node-exporter` and `kube-state-metrics` installed directly from yaml manifests so it will be hard to compare our setups xD
> 
> What I did is look at lens source code for the exact metrics queried on prometheus, port forward your prometheus/victoriametrics port, query `/metrics` (or look in grafana in explore) and make sure they are available.
> 
> Once you do that check that your cluster monitoring configuration in Lens is correct, I had to set it to Helm and provide the service by hand which in my case is: `monitoring-system/vmsingle-vmsingle:8429`
> 
> Once that was done I disconnected and connected back to the cluster and I had my graphs (Lens does not use the new metrics config until your restart or reconnect to the cluster).

Switching `Lens > Setting > Prometheus > Use pre-installed Prometheus service for metrics. Please refer to the guide for possible configuration changes. Prometheus installation method. > Helm` + `monitoring/vmsingle-vm-victoria-metrics-k8s-stack:8429` worked for me but only partly: I can see requests/limits & capacity now but not the Usage & the main Metrics windows is saying **Metrics not available at the moment**
![image](https://user-images.githubusercontent.com/28118190/128906319-178367fe-d0b3-4688-96db-54edfddb9334.png)
![image](https://user-images.githubusercontent.com/28118190/128906371-aa0ea776-7db4-4586-adb4-884ea0083ceb.png)

**Comment by korjavin** [comment]
It's because requests/limits don't depend on prometheus/VM. Part of k8s
describe.

**Comment by vainkop** [comment]
> It's because requests/limits don't depend on prometheus/VM. Part of k8s describe.

It depends on metrics server which I have installed before Prometheus stack or VM stack & it worked until I removed community kube-prometheus-stack & installed VM.
VM installs it's own `vm-kube-state-metrics` but Prometheus stack does the same with `kube-prometheus-stack-kube-state-metrics`
I see no errors in logs.

That's how I've installed the "original" metrics-server initially:
```
kubectl config set-context --current --namespace=kube-system
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm upgrade -i metrics-server bitnami/metrics-server --set apiService.create=true
```


But I can see those metrics if I open any individual deployment or a node including Usage.

![image](https://user-images.githubusercontent.com/28118190/128908968-2ff874f1-1ed4-4d59-8573-c3132ba24f75.png)
![image](https://user-images.githubusercontent.com/28118190/128909156-57008aeb-fd1a-4b1e-94ca-042ded6b4157.png)

![image](https://user-images.githubusercontent.com/28118190/128908861-8d7b0016-2b03-4852-b5d4-83bc1a5e69e2.png)
![image](https://user-images.githubusercontent.com/28118190/128908925-8965f4d7-1d32-496f-80bc-192a7035fc07.png)

**Comment by vainkop** [comment]
And that's what I see in kubernetes-compute-resources-cluster Grafana dashboard which came with VM & I didn't configure
![image](https://user-images.githubusercontent.com/28118190/128909446-a3ba7152-69b0-4150-b248-6bb86d79cdd2.png)

**Comment by vainkop** [comment]
Here's the gist with my helm-values.yml in case someone needs it: https://gist.github.com/vainkop/d8ed28f85f3b87fa53ec4269ad13b460#file-victoriametrics-helm-values-yml

The only lines which I changed from the original chart are those: https://gist.github.com/vainkop/d8ed28f85f3b87fa53ec4269ad13b460#file-victoriametrics-helm-values-yml-L564-L600
