### ISSUE TITLE
Optimize width of display columns

### ISSUE THREAD

**Issue by ghost** [lensapp/lens#1943]
Column width is sometimes not well optimized, as shown here on the Endpoints panel:

<img width="1146" alt="lens-fs8" src="https://user-images.githubusercontent.com/65664227/104269676-d138f100-54d1-11eb-81c1-d6dd7bf21e41.png">

**What would you like to be added**:
Ability to modify column width by double-clicking between columns

**Why is this needed**:
UX

**Environment you are Lens application on:**

- Kubernetes distribution: k3s
- Desktop OS: Darwin

**Comment by Nokel81** [comment]
Duplicate of #601
