### ISSUE TITLE
Re-opening Lens doesn't use the latest AWS ENV

### ISSUE THREAD

**Issue by mcooknu** [lensapp/lens#1953]
Lens fails to change AWS context when switching AWS Accounts via AWS SSO.

(AWS SSO process places AWS_* ENV vars with new tokens etc)

**To Reproduce**
1. To access eks cluster, I have to first go through AWS SSO and obtain a valid, temporary set of credentials which is done using MacOS Terminal.  

2. In the same Terminal, once AWS SSO is successful, I set KUBECONFIG and kubectl works fine and allows access to the cluster.  

3. If I then launch Lens from the terminal, open -a Lens, Lens will start up and successfully use the kubeconfig and access the cluster for the duration of the AWS SSO session (many hours).

So far so good.

4. If I close Lens GUI, move to a different AWS SSO account/session in same or different Terminal and relaunch Lens, then Lens is still 'tied' to the original AWS environment and will not access an EKS cluster under another account and fail due to AWS IAM permissions.

To remedy this, I have to kill all "Lens" related processes ("Lens","Lens Helper") and then steps 1-3 work for the new AWS Account.  This makes switching between kubectl configs very labourious unless they all exist within the same AWS Account.  I cannot compare two EKS clusters from two different AWS Accounts at the same time either.

**Expected behavior**
Lens to track AWS Account creds and SSO sessions against each KUBECONFIG or maintain association with the Terminal ENV from which it was launched.  I suspect on it's first launch Lens is maintaining some sort of environment across multiple Lens GUI launches.

**Environment (please complete the following information):**
- Lens Version: Latest.
- OS: MacOS Big Sur

Any clear advice on multi-AWS Account support using SSO would be very helpful.  I think this is a different use-case from the other threads on Okta/SSO and understand Lens application probably doesn't want to implement SSO but I think it would help if it could maintain the AWS ENV somehow with a set of kubectl configs.

**Comment by jim-docker** [comment]
you can try to add AWS_PROFILE and AWS_REGION into env property in kubeconfig
    exec:
      args:
      - ...
      command: aws-iam-authenticator
      env:
      - name: AWS_PROFILE
        value: dev
      - name: AWS_REGION
        value: us-east-1

**Comment by Nokel81** [comment]
That is also because of the Lens tray icon so just closing the Lens window doesn't actually quit the whole of Lens.

**Comment by RiskyAdventure** [comment]
Noekl thank you for leaving that comment, I was unable to get lens working w/ AWS SSO due to the tray icon, this saved me a lot of troubleshooting.

**Comment by Nokel81** [comment]
You are very welcome. Hopefully some of the features in 5.0.0 will help with keeping AWS ENVs synced.

**Comment by Nokel81** [comment]
Closing this as the dehaviour is consistent with the current design.
