### ISSUE TITLE
Lens GUI continues to navigate kubernetes entities despite no longer having a connection to cluster

### ISSUE THREAD

**Issue by mcooknu** [lensapp/lens#1954]
Several times, I've found the GUI looks responsive and I can navigate through teh various kubernetes entities and components, even pods.  But it has some how lost connectivity to the cluster. 

The only tail-tail sign is when you attempt to open the log console to a Pod and you are met with no logs and failure message.

On start up it is very obvious when Lens can't connect to the cluster.  Once connected, it seems less obvious that it's in fact offline.

I have not found a pattern as to when it looses connectivity.  To remedy this I usually have to close Lens down and re-open it... then it goes through it's connection routine.

**Comment by jim-docker** [comment]
Lens checks the connection approximately every 30s, presumably you are waiting that long. How is the connectivity is lost?

**Comment by mcooknu** [comment]
Yes, waiting longer than 30secs.  Usually return to Lens within ~10-15mins intervals.  I've noticed this issue when using a VPN.  The host computer's connection remains up/working but VPN may be connected/disconnected throughout the day due to various reasons.  This is on a MacOS using Cisco VPN.

**Comment by jim-docker** [comment]
It's odd that Lens doesn't detect that it becomes disconnected. Instead of remedying by restarting Lens, does it work to right-click on the cluster icon, pick "Disconnect", then left-click on the cluster icon to re-initiate the connection?

Also, seeing some logs may be useful (run
```
DEBUG=true /Applications/Lens.app/Contents/MacOS/Lens
```
in a console to see logs)

**Comment by mcooknu** [comment]
Yes, disconnect and reconnect usually works. I will see if I can get more logs.

**Comment by Nokel81** [comment]
Any update?
