### ISSUE TITLE
Passing in environment variables to built in helm doesn't seem to work

### ISSUE THREAD

**Issue by parak** [lensapp/lens#1962]
**Describe the bug**
In order to use private GCS repositories, I'm leveraging helm-gcs plugin which in turn relies on an environment variable called GOOGLE_APPLICATION_CREDENTIALS to read a service account credentials file.

After setting the environment variable in the command line and calling the Lens embedded helm3 from directly from a shell I was able to add the plugin, the repository, and view/download the helm charts as expected. However, while Lens also showed all the charts in the repository afterwards, clicking on any one of them results in an indefinitely spinning icon in the popup window that should be showing the chart information.

In the network debug window an authentication error (google: could not find default credentials) is seen identical to what is seen if the previously mentioned environment variable is unset. So far I tried setting a system wide environment variable as well as launching Lens from the command line with the variable set, but both produce the same result.

Is there a way to verify that the environment variable is correctly set when Lens calls helm3 internally, or to set it? Thanks!

**Expected behavior**
Embedded helm3 uses environment variables.

**Environment (please complete the following information):**
- Lens Version: 4.06
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): Direct download

**Comment by jim-docker** [comment]
Does it work if you set these environment variables globally for when Lens starts?

**Comment by fzalila** [comment]
> Does it work if you set these environment variables globally for when Lens starts?

This is what I did and it perfectly resolves the issue.  💯

**Comment by parak** [comment]
Having a bit of a hard time replicating this for some reason this time around - it seems that application default credentials that get me into the cluster also will work with helm without needing the environment variable, but if I run into something that requires specifically a service account I'll revisit this again then. Thanks!
