### ISSUE TITLE
Custom installation path

### ISSUE THREAD

**Issue by PhilRanzato** [lensapp/lens#1968]
**What would you like to be added**:

Ability to change default installation path

**Why is this needed**:

To install in a custom drive

**Environment you are Lens application on:**

- Kubernetes distribution: []
- Desktop OS: Windows

**Comment by carlreid** [comment]
This is needed in my case also, since I can install development tools in a special folder that won't be blocked by enterprise rules. A workaround for me was to install as normal then copy everything from the default path to my special folder and run it that way.

**Comment by jakolehm** [comment]
Fixed in #1978
