### ISSUE TITLE
Using Cordon with multiple clusters always uses one cluster

### ISSUE THREAD

**Issue by brobichaud** [lensapp/lens#1969]
**Describe the bug**
I have two clusters registered in Lens and it does not appear to be correctly setting up console windows for each cluster. It always seems to have them associated with the first listed cluster.

**To Reproduce**
1. Setup Lens to have two clusters registered
2. Select cluster 1
3. View a node and choose to cordon it
4. A console window opens and performs the correct action
5. Select cluster 2
6. View a node and choose to cordon it
7. A console window opens and it tries to cordon a node on cluster 1

It appears the second console window is still pointing at Cluster 1. This is hugely dangerous as it is applying a change you asked for and confirmed, but on the wrong cluster.

**Expected behavior**
For each console window that opens to be pointing at the api server of the correct cluster.

**Screenshots**
N/A

**Environment (please complete the following information):**
- Lens Version: 4.0.6
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): Windows installer

**Logs:**

**Kubeconfig:**
They appear to be well formed as all UI operations work correctly on each cluster. It is only command windows that seem to fail.

**Additional context**
Not sure if it is relevant but we do run Windows nodepools on our clusters and in this case we were acting on nodes in these Windows nodepools.

**Comment by nevalla** [comment]
Is Lens terminal connecting to a wrong cluster if you open Lens terminal and execute some kubectl commands, like `kubectl get nodes` or `kubectl get pods`?

**Comment by brobichaud** [comment]
Indeed just opening a terminal in both clusters within Lens and then running kubectl get pod shows the same results, both from the first cluster. So it appears terminal windows in general are not setting up the correct kubeconfig file.

**Comment by Nokel81** [comment]
When trying to reproduce this on `master` I was unsuccessful. Is this still a problem in 4.1?

**Comment by brobichaud** [comment]
Yeah I have v4.1.3 and I just tried a simple test.

1. In lens select a cluster
2. In lens open the terminal at the bottom of the Lens screen
3. In that terminal window type: kubectl get pod

I have two clusters and no matter which cluster I choose I get the same list of pods, which belong to the first cluster in my list.

I wonder if there is an issue in how I have my Windows environment variables setup. I do have a kubeconfig variable setup for my user acct so that if I open any random windows console it is pointing at the cluster config for that first cluster. Does lens not override that variable when opening a terminal? If not how does lens know where the cluster config is?

**Comment by Nokel81** [comment]
Can you run `env` in your cluster. We are always overriding the `KUBECONFIG` envvar before creating the shell session and on my computer (macOS) I see that the variable is indeed pointing to some file in the `tmp` dir. What do you see?

**Comment by brobichaud** [comment]
Running the command below from a Lens terminal window when either cluster is selected results in the same value, which is pointing at the first cluster.

`$env:kubeconfig`

This seems to be the crux of the problem. The variable is not being properly overridden for some reason. As an experiment I removed the kubeconfig env variable that is set as a User environment variable in Windows, restarted Lens and now if I open terminals in both clusters I see different values in each (pointing at a temp folder), and kubectl commands work correctly.

So it seems the problem is that if I have kubeconfig set as a User env variable then Lens is not properly overriding it. I need this variable set so that when I open a cmd window it is ready to go.

Note I am able to manually override the variable within the Lens terminal using this command and it works fine:

`$env:kubeconfig = 'c:\cloudtools\k8s-clusters\uswest.env'`

Any thoughts on why the variable is not being overridden?

**Comment by Nokel81** [comment]
Looking at the code I really don't know why is wouldn't be overridden. I will try do some more digging on a windows machine

**Comment by Nokel81** [comment]
I really cannot seem to reproduce this even on my windows machine. I have tried setting environment variables in "git bash" and the windows ENV var helper (both user and system while). I have not observed this behaviour at all (they all cordon/uncordon the correct node).

Would you mind uploading a video showing this behaviour? If it is pervasive then it should be possible to set it up using fake clusters for the demo.

**Comment by brobichaud** [comment]
I'm not using WSL so I would assume any use of git bash is not likely to repro this. I was able to repro it on two different machines using these steps:

1. Open the Windows env variables control panel (click Start, type env, choose "Edit the System Environment Variables")
2. Click the "Environment Variables" button
3. Click New in the "User variables for" section
4. Enter a variable name of kubeconfig and Value of whatever you like
5. Save all changes and exit the control panel
6. Completely exit Lens if it was running
7. Start lens and open a terminal window

**Comment by Nokel81** [comment]
is that `kubeconfig` or `KUBECONFIG`?

**Comment by brobichaud** [comment]
Hmm, that is a very interesting question. I had been using all lowercase, but I just tried switching it to upper case and Lens now does the right thing. This somehow seems to be the key!

Oddly, I can set it to any mix of casing and kubectl works just fine from a normal command line. But in Lens it seems to only work correctly if I set it to all upper case.

**Comment by Nokel81** [comment]
Okay excellent thanks. Since `kubectl` accepts any, I think so should Lens. Will make a PR.
