### ISSUE TITLE
No Scroll bar on left nav

### ISSUE THREAD

**Issue by MiteshNWT** [lensapp/lens#1971]
No Scroll bar when we have many clusters added

![image](https://user-images.githubusercontent.com/5683305/104767194-c2547780-5739-11eb-8baa-f356f869cc13.png)

- Lens Version: 4.0.6
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux): Exe Installation

**Comment by jim-docker** [comment]
Is the issue that you can't fully see the last cluster icon in the list? (Otherwise you can scroll using mousewheel, etc)

**Comment by Nokel81** [comment]
Just tested on windows 10 with Lens 4.0.6. I was able to scroll the cluster menu and fully see all of the added cluster icons.

**Comment by jim-docker** [comment]
@MiteshNWT, can you provide more context? About how many clusters? Is it just the last cluster that is "clipped"? Did you resize the lens window? Anything special about your Windows setup?

**Comment by MiteshNWT** [comment]
Thanks for looking in this . Now I am able to scroll with mouse wheel . It was working earlier . Probably my computer ran out of resources or something.

**Comment by MiteshNWT** [comment]
I remember it now . Actually when you are just using Laptop Track Pad and not have access to mouse wheel then its un scrollable , better to put scroll bar on this menu

**Comment by Nokel81** [comment]
Oh for laptops that don't have "two finger to scroll"?

**Comment by jim-docker** [comment]
Two finger swipe up and down on track pad is supported on Windows/Mac/Linux for scrolling the clusters menu on the left nav.
