### ISSUE TITLE
Crash on MacOS Catalina 

### ISSUE THREAD

**Issue by cathy-kim** [lensapp/lens#1975]
**Describe the bug**

When launching Lens on MacOS Catalina, my macPro turned off. 

```
panic(cpu 6 caller 0xffffff801eec054f): assertion failed: (MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start == cfq->q_end) || (!MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start != cfq->q_end), file: /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.10/bsd/net/content_filter.c, line: 1067
Backtrace (CPU 6), Frame : Return Address
0xffffffa403ba3730 : 0xffffff801e71961d 
0xffffffa403ba3780 : 0xffffff801e853ac5 
0xffffffa403ba37c0 : 0xffffff801e84564e 
0xffffffa403ba3810 : 0xffffff801e6bfa40 
0xffffffa403ba3830 : 0xffffff801e718ce7 
0xffffffa403ba3930 : 0xffffff801e7190d7 
0xffffffa403ba3980 : 0xffffff801eec00bc 
0xffffffa403ba39f0 : 0xffffff801eec054f 
0xffffffa403ba3a00 : 0xffffff801ead683e 
0xffffffa403ba3a40 : 0xffffff801ead6b58 
0xffffffa403ba3bd0 : 0xffffff801ead5048 
0xffffffa403ba3c20 : 0xffffff801ead1e6e 
0xffffffa403ba3c80 : 0xffffff801ec59c19 
0xffffffa403ba3cd0 : 0xffffff801ecd193b 
0xffffffa403ba3df0 : 0xffffff801eca64fc 
0xffffffa403ba3e20 : 0xffffff801ec9faf0 
0xffffffa403ba3ee0 : 0xffffff801ec9f8b0 
0xffffffa403ba3f40 : 0xffffff801ed83237 
0xffffffa403ba3fa0 : 0xffffff801e6c0206 

BSD process name corresponding to current thread: com.broadcom.mes
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
19H114

Kernel version:
Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64
Kernel UUID: A477D537-F87E-3978-8D7F-A84B7C02E62E
Kernel slide:     0x000000001e400000
Kernel text base: 0xffffff801e600000
__HIB  text base: 0xffffff801e500000
System model name: MacBookPro16,1 
System shutdown begun: NO

```

**To Reproduce**

Just turn on VPN and launch Lens.
Then the mac will turn off and show this message after rebooting. 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by maraslibay** [comment]
Bende anlam veremiyorum iki günden beti hesabıma erişemiyorum  en son
skatele edildiniz diye email aldım bugünde hesabıma giren kişi kendi
hesabını açık bırakmış polkadota erişimim olmadığı için kendi hesabım
oldugunu zannettigim için kapattım sorun benim hesaba giren kişide olayın
çözülmesini istiyorum zararımında karşılanmasını talep ediyorum

17 Oca 2021 Paz, saat 11:36 tarihinde Cathy Kim <notifications@github.com>
şunu yazdı:

**Comment by lorr756** [comment]
candy crush app imports bug from apple games

**Comment by jim-docker** [comment]
What do you mean by start VPN? Cn you start Lens from the command line to see if there are more details?
`DEBUG_PROXY= true /Applications/Lens.app/Contents/MacOS/Lens`
similar to #1805?

**Comment by dedyks** [comment]
i encounter the same issue, this is related to **Symantec Endpoint Protection (EDIT v. ~~15.3~~ 14.3.1)**. In my case, because the Lens autostart is enabled, my mac OS crash every restart. right now im searching a way to disable the autostart first.

**Comment by jim-docker** [comment]
Can you start your mac in safe mode, and then remove or rename the `~/Library/Application Support/Lens` folder, and try starting again? Removing that folder should clear the Lens autostart

**Comment by dedyks** [comment]
yes i able to boot on safe mode, disable lens autostart and restart normally, however starting Lens with SEP v 14.3.1 is still crashing the OS. Before i upgrade the Symantec Endpoint Protection, it was on v. 14.3 , the lens run with no issue
My System is:
macos catalina 10.15.7

**Comment by Nokel81** [comment]
Is this related to #2390 ?

**Comment by Nokel81** [comment]
Closing as I don't think there is anything we can do about this. It is probably a bug in SEP given that it is a kernel panic and Lens doesn't add any kernel modules outside of any that Electron would use.

**Comment by sp0cket** [comment]
@Nokel81 So that's seems to be Electron bug? Is there any issue related to this bug?  Other Electron app like Visual Studio Code didn't cause same bug

**Comment by Nokel81** [comment]
I think the current version of vscode uses a slightly older (13.5 vs 13.6) release of electron. But we also have a lot more iframes and proxies being used internally to our application. I just don't think that we have the resources to fix this, especially because the file where the crash occured is `/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.10/bsd/net/content_filter.c` which isn't ours
