### ISSUE TITLE
Improve preferences layout

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#1983]
- left menu should acts as shortcuts to different sections
- all extension registered preferences should be under "Extensions"
- new back/close button

Mockup:
![image (1)](https://user-images.githubusercontent.com/1446224/105025079-82510580-5a55-11eb-92c4-cba13a4a8217.png)

**Comment by aleksfront** [comment]
@Nokel81 This can be added into 4.2.0 milestone when https://github.com/lensapp/lens/pull/2304 will be reviewed.

**Comment by Nokel81** [comment]
Finished without changing the close/back button.
