### ISSUE TITLE
Wizard & Namespace-select exports

### ISSUE THREAD

**Issue by ycamper** [lensapp/lens#1991]
**What would you like to be added**: Export `wizard` and `namespace-select` components for use in plugins (`src/extensions/renderer-api/components.ts`)

**Why is this needed**: I've already seen pull requests for `wizard` here: https://github.com/lensapp/lens/pull/1784 but for some reason, this change never seemed to make it into a release even though it was merged.

**Environment you are Lens application on:** N/A

- Kubernetes distribution: N/A
- Desktop OS: N/A

**Comment by jim-docker** [comment]
This is targeted for 4.1 release

**Comment by Nokel81** [comment]
Fixed by #1880 and #1784
