### ISSUE TITLE
Incorrect latest release 3.6.10 when 4.0.7 it's available

### ISSUE THREAD

**Issue by piraces** [lensapp/lens#1993]
I think there is a problem when tagging new latest versions in GitHub.
When releasing the new version 4.0.7, it is not tagged as latest. Instead of this, a new version 3.6.10 is tagged as latest.

When users try to download Lens for first time from https://k8slens.dev/. They are redirected to the 3.6.10 version, which may be incorrect.

Also, when trying to update the current version of lens or letting it autoupgrade, does not detect the new version.

**Comment by nevalla** [comment]
Thanks. We are aware of this and we'll try to fix this ASAP.

**Comment by jakolehm** [comment]
Should be fixed now.
