### ISSUE TITLE
Updating v3.6.10 to latest version is flaky

### ISSUE THREAD

**Issue by jim-docker** [lensapp/lens#2006]
When Lens 3.6.10 starts, although the log shows an update is available

```
info: Checking for update
info: Found version 4.0.8 (url: Lens-4.0.8-mac.zip, Lens-4.0.8.dmg)
```
no notification pops up asking what to do with the update. This was noticed after installing v3.6.10 over top of v4.0.6, on mac and windows. This behaviour seems intermittent, sometimes the notification dialog does appear.

Similarly, when the dialog appears, and the "Yes, on quit" option is selected, and Lens is restarted, it is not updated as expected (notification dialog appears again). Retrying (once or twice) eventually results in successful update.

**Comment by Nokel81** [comment]
I am going to close this as I don't think we plan on continuing support for v3
