### ISSUE TITLE
node-shell : Failed to pull image "docker.io/alpine:3.12"

### ISSUE THREAD

**Issue by Art-Man** [lensapp/lens#2007]
**Describe the bug**

node-shell-888ce968-f3b4-4b86-9bd6-ba4487a37604

Failed to pull image "docker.io/alpine:3.12": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:46565->[::1]:53: read: connection refused

**To Reproduce**
when k8s cluster network cann't connect to internat, k8s only can connect to local harbor registry，can not pull the internet image docker.io/alpine:3.12

**Code In**
in this code file:  lens/src/main/node-shell-session.ts  line 78, have this line  image: "docker.io/alpine:3.12", 

**Solve Suggestion**
Is this can make a config  to solve the problem;

or use K8S DaemonSet YAML, I can change the DaemonSet YAML in runtime to solve the problem;

**Comment by mlai** [comment]
We hit a similar issue. 

We can only pull images from our internal docker registry. `node-shell` cannot work with the hard-coded registry `docker.io`. Better to make it configurable.

**Comment by MichaelSp** [comment]
yes, please make that a configuration option especially since:

```
Failed to pull image "docker.io/alpine:3.12": rpc error: code = Unknown desc = Error response from daemon: 
toomanyrequests: You have reached your pull rate limit. 
You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

**Comment by vshakirova** [comment]
Hi guys, I'd like to ask. Do you also need the ability to attach a secret to a Pod in case of a private registry? Or you have preconfigured access and it is enough to have the ability to change the image only?

**Comment by Art-Man** [comment]
Recommended to refer to the mode of monitoring installation. Through the apply Deployment or DaemonSet yaml file, if someone has special needs, he can directly modify the yaml file or modify the  Deployment or DaemonSet yaml file then apply it;

**Comment by MichaelSp** [comment]
@vshakirova I think image, registry(-mirror) and registry secrets would be optimal!

In my case I only need to set the mirror without secrets: https://docs.docker.com/registry/recipes/mirror/#configure-the-docker-daemon but i could also change the image to use the mirror: `<mirror>/docker.io/alpine:3.12`

**Comment by vshakirova** [comment]
> Recommended to refer to the mode of monitoring installation. Through the apply Deployment or DaemonSet yaml file, if someone has special needs, he can directly modify the yaml file or modify the Deployment or DaemonSet yaml file then apply it;

Sorry, could you please a bit elaborate? Do you want to have the ability to change a yaml file directly in cluster settings(using a pod template)? Or it should be an additional option?

**Comment by Art-Man** [comment]
commended to refer https://github.com/lensapp/lens/tree/master/extensions/metrics-cluster-feature/resources

**Comment by Art-Man** [comment]
> > Recommended to refer to the mode of monitoring installation. Through the apply Deployment or DaemonSet yaml file, if someone has special needs, he can directly modify the yaml file or modify the Deployment or DaemonSet yaml file then apply it;
> 
> Sorry, could you please a bit elaborate? Do you want to have the ability to change a yaml file directly in cluster settings(using a pod template)? Or it should be an additional option?

commended to refer like https://github.com/lensapp/lens/tree/master/extensions/metrics-cluster-feature/resources
