### ISSUE TITLE
[4.0.8] Cannot list namespaces/pods without using "accessible namespaces" even with list namespaces role

### ISSUE THREAD

**Issue by LaurentDumont** [lensapp/lens#2010]
**Describe the bug**
It seems that this is something that multiple people are experiencing and one of the cause seems to be the inability to list namespaces. In my case, I am able to list all namespaces but is owner of just a few of those.

My kubectl user can list all namespaces in the cluster (but doesn't have access to all of them). I would expect Lens to reduce the view to at least the ones I have the right level of permissions over.

To workaround that, I need to add each of the namespace manually which is a bit tedious.

**To Reproduce**
1. Open Lens
2. Stay on the Worksloads -- Overview page.
3. Nothing appears.

Same behavior in the namespaces page. I can see a 200 OK response for namespaces I have access to but they are not displayed.

The following error is shown in the Dev console
```
kube-object.ts:59 Uncaught (in promise) TypeError: Cannot read property 'items' of undefined
    at Function.value (kube-object.ts:59)
    at e.value (kube-api.ts:274)
    at async Promise.all (2487b353-b1eb-4306-ac8a-29d0aebbb5d9.localhost:49373/index 0)
```

**Expected behavior**
 I would expect Lens to reduce the view to at least the ones I have the right level of permissions over.

**Screenshots**
![image](https://user-images.githubusercontent.com/8936473/105538801-f55eb400-5cc1-11eb-9693-c0e8ec47379e.png)

**Environment (please complete the following information):**
- Lens Version: 4.0.8
- OS: Mac OS Catalina 10.15.7
- AppImage

**Comment by jim-docker** [comment]
should be fixed by #2003
