### ISSUE TITLE
App not able to open in Windows without notice

### ISSUE THREAD

**Issue by Kevin-Li-Webjet** [lensapp/lens#2012]
**Describe the bug**
Windows version not able to open anymore without any notice.

**How the issue looks like?**
Hey guys, Lens in my PC not working from a few days ago. I can't get it work after spent hours on it.  There are 3 tasks in Task Manager showing like normal, but you can't actually see any application running in the Taskbar of Windows. 

**What I did?**
I am trying to uninstall and install different versions, also with "Run As admin" on/off, which not helped.  I am trying to look at if any logs in the "Windows Event Viewer -> Custom Views", and found below Warning whenever I kill the thread in Task Manager and try reopen Lens

`
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
`
I am not sure if I have this Warning before because Lens was working fine in my PC, I was tried to follow instruction change owner of {2593F8B9-4EAF-457C-B68A-50F6B8EA6B54} and {15C20B67-12E7-4BB6-92BB-7AFF07997402} in "regedit" and grant access, which get rid of the Warning.  But unfortunately, the issue didn't resolved.

**To Reproduce**
I am not sure just not working in my Windows PC anymore

**Expected behavior**
I expected Lens would be able to have alert box say what's going on, or at least has logs somewhere so I can debug

**Environment (please complete the following information):**
- Lens Version: 3.96+ or 4+
- OS: Windows 10 Pro (Version 1909  OS build 18363.1316)
- Installation method (e.g. snap or AppImage in Linux):  via EXE file

**Comment by Kevin-Li-Webjet** [comment]
Also the clean-start (Disable all non-Microsoft services in "msconfig") not help

**Comment by jim-docker** [comment]
Was Lens ever working for you? Did this start happening after an update?

**Comment by Kevin-Li-Webjet** [comment]
> Was Lens ever working for you? Did this start happening after an update?

Hi Jim, yes, it was working great in the past few months, it seems happening after installing a Windows patch

**Comment by jim-docker** [comment]
Hi Kevin, I have tried installing/updating/uninstalling Lens on a Windows 10 Pro (Version 1909 OS build 18363.1316) system with no issues. Is your PC in a corporate environment, any restrictions on what can be installed where? Does Lens uninstall cleanly?

**Comment by Kevin-Li-Webjet** [comment]
> Hi Kevin, I have tried installing/updating/uninstalling Lens on a Windows 10 Pro (Version 1909 OS build 18363.1316) system with no issues. Is your PC in a corporate environment, any restrictions on what can be installed where? Does Lens uninstall cleanly?

Thanks Jim, The PC is my personal laptop, no restrictions. When you say "uninstall cleanly", do you mean double-clicked "uninstall", if yes then yes. I am wondering is anywhere else I can found logs .etc  So I can help with debugging

https://ibb.co/Q8V9rnK
I can only see it running, but no UI appear

**Comment by jim-docker** [comment]
Look in `C:\Users\{username}\AppData\Roaming\Lens\Lens\logs`

**Comment by Kevin-Li-Webjet** [comment]
Hi Jim, 

Thanks for your tips

Problem fixed by remove entire folder "C:\Users\{username}\AppData\Roaming\Lens"
logs itself not have any error information, just saying Lens is started, latest version .etc
I would recommend if we should remove that folder when user "uninstall" 

Cheers,
