### ISSUE TITLE
Error updating beta/release-candidate charts values

### ISSUE THREAD

**Issue by hilariocoelho** [lensapp/lens#2014]
**Describe the bug**
Since version 4.x that I can’t update chart values with beta/release-candidates charts version… Is there any way you can support such versions? Or is this behaviour intended?
In the following attachments I show you the error I get. I also attached an HAR file with the request and it’s response.

**To Reproduce**
1. Install a chart with a beta/release-candidate version
2. Update chart values
3. See the error

**Expected behavior**
Chart values updated

**Screenshots**
<img width="985" alt="Screenshot 2021-01-22 at 14 30 51 (1)" src="https://user-images.githubusercontent.com/5185271/105697264-45c15600-5efc-11eb-8368-856a009a3a6f.png">

**Environment (please complete the following information):**
- Lens Version: 4.0.8
- OS: MacOS 10.15.7

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
[localhost.har.zip](https://github.com/lensapp/lens/files/5866072/localhost.har.zip)

**Comment by jim-docker** [comment]
Are there are common helm charts we can use to try to reproduce this?

**Comment by hilariocoelho** [comment]
```bash
helm repo add agones https://agones.dev/chart/stable
helm install agones/agones --version 1.11.0-rc --generate-name
```

Then if you try to update values via Lens app you will get an error where it says it can't find /agones: "Error: path "/agones" not found"

But if you try with a stable version it all works as expected:
```bash
helm install agones/agones --version 1.11.0 --generate-name
```

**Comment by hilariocoelho** [comment]
@aleksfront 
It seems like 4.1.0 Lens version already fixed this issue :)
