### ISSUE TITLE
Support using kubectl available on PATH

### ISSUE THREAD

**Issue by Audrius-GR** [lensapp/lens#202]
**What would you like to be added**:
Add support for using kubectl available on the path

**Why is this needed**:
It seems that the application tries to extract (not clear where from?) version of kubectl to match the cluster.

The group policy/anti-malware software installed by the company seem to prevent that, and results in a 0 byte executable.
I know for a fact that the kubectl available on the path works with all the clusters in question.
Furthermore, this machine is not able to reach out to the internet.

**Environment you are Lens application on:**
- Kubernetes distribution: Local
- Desktop OS: W10

**Comment by jakolehm** [comment]
I think we need to add an option for using bundled (local) kubectl. Now by default Lens tries to download matching kubectl version from the official download servers.

**Comment by Nokel81** [comment]
Fixed by #800
