### ISSUE TITLE
Support running without helm

### ISSUE THREAD

**Issue by Audrius-GR** [lensapp/lens#203]
**What would you like to be added**:
The application should not break if it can't download help, and should support running in helm-free mode.

**Why is this needed**:
Again, machine I am trying to use this application on is offline, and it seems Lens blows up repeatedly on trying to extract files and resolve get.helm.sh DNS addresses when switching between views.

I don't think the application fundamentally depends on helm to function, and should be usable without it.

**Environment you are Lens application on:**
- Kubernetes distribution: Local
- Desktop OS: W10

**Comment by jakolehm** [comment]
Should be fixed.
