### ISSUE TITLE
[UX] Open Lens, should be the first item in the applet menu

### ISSUE THREAD

**Issue by arthurzenika** [lensapp/lens#2032]
**What would you like to be added**:

A number of times while attempting to open Lens from the applet menu, I open the "About Lens".

**Why is this needed**:

UX - having About Lens at the end of the list (before "Quit App")  would be better. 

**Environment you are Lens application on:**

- Kubernetes distribution: n/a
- Desktop OS: Ubuntu

**Comment by miskun** [comment]
Sounds like good UX improvement!
