### ISSUE TITLE
Logging drop down menu points to wrong container

### ISSUE THREAD

**Issue by vrkk** [lensapp/lens#2038]
**Describe the bug**
When viewing logs of multicontainer pods the UI points to the wrong container logging by default. 

**To Reproduce**
The drop down menu next to the pod name lets you choose the container logging you want to view:
![image](https://user-images.githubusercontent.com/53277208/106129335-10b13f80-6158-11eb-9050-46fee8038ae4.png)
However when choosing the second container in the drop down menu (hippo) the logging of the top container (apache) is opened by default. So within the logging UI you have to choose the correct container again.
![image](https://user-images.githubusercontent.com/53277208/106129608-4f46fa00-6158-11eb-9d98-a7848f5d268c.png)

**Expected behavior**
Logging drop down menu should point to the correct container logging,.

**Environment (please complete the following information):**
- Lens Version: 4.06
- OS: Mac OS Big Sur 11.1
- Installation method (e.g. snap or AppImage in Linux): brew install

**Comment by aleksfront** [comment]
Fixed in #1984 along with generic logs view additions.
