### ISSUE TITLE
Feature request: Load autocomplete in terminal by default

### ISSUE THREAD

**Issue by Richard87** [lensapp/lens#2049]
**What would you like to be added**:
I want Lens to automatically load autocomplete when using bash or zsh as shell.

**Why is this needed**:
kubectl completion is pretty slow, so it's annoying to use it for all unrelated terminals. But in Lens the purpose is almost always to work with kubectl.

**Environment you are Lens application on:**
Fedora 33 with zsh

```sh
source <(kubectl completion zsh)
# *or*
source <(kubectl completion bash)
```

**Comment by jim-docker** [comment]
Can you set this up in your own configuration?

**Comment by Richard87** [comment]
I used to, but it so slow that I disabled it universally. I would love to have it only in Lens' terminal since I need it here anyway :)

**Comment by Hcreak** [comment]
Has this issue been resolved?

**Comment by Richard87** [comment]
Not as of 2022.10.181357-latest :)

**Comment by Nokel81** [comment]
If you want you can use the fact that we set the `TERM_PROGRAM` to be `lens` in the environment. You can check this in your `.zshrc` file or `.bashrc` file.

**Comment by Richard87** [comment]
Ah cool, that will solve my issue! Thanks :)

**Comment by Hcreak** [comment]
```
if [[ $TERM_PROGRAM = Lens ]]; then
  autoload -Uz compinit && compinit
  source <(kubectl completion zsh)
fi
```
