### ISSUE TITLE
Changing cluster icon crashes app

### ISSUE THREAD

**Issue by antHogis** [lensapp/lens#205]
**Describe the bug**
Trying to change the icon of a cluster crashes

**To Reproduce**
1. Right-click cluster
2. Click on 'settings'
3. Scroll down to 'Cluster Icon'
4. Click on 'Browse for new icon'...

**Expected behavior**
I expected to be able to set the icon from an image file, or some preset images.

**Environment**
- Lens Version: 3.1.0
- OS: Manjaro i3 Community Edition (Linux version 5.4.28-1-MANJARO (builder@b32771fd1c24) (gcc version 9.3.0 (Arch Linux 9.3.0-1)))
- Installation method: snap
 
**Logs:**
```
(process:18243): Gtk-WARNING **: 11:06:28.546: Locale not supported by C library.
	Using the fallback 'C' locale.
info: SNAP env is defined, updater is disabled

(kontena-lens:18243): Gtk-WARNING **: 11:07:07.009: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
[1]    18243 abort (core dumped)  kontena-lens

```

**Comment by Nokel81** [comment]
Is this still a problem in Lens 4.1.4? We have changed how we are dealing with these icons.

**Comment by Nokel81** [comment]
Closing as we cannot reproduce this.
