### ISSUE TITLE
Enable right-click paste in terminal

### ISSUE THREAD

**Issue by shazada** [lensapp/lens#2050]
**What would you like to be added**:
Enable right-click paste in terminal like any other terminal out there

**Why is this needed**:
It's trange to go in the menu --> Edit --> Paste

**Environment you are Lens application on:**
Kubernetes cluster
- Kubernetes distribution: Rancher
- Desktop OS: Windows 10

**Comment by jim-docker** [comment]
Hi @shazada we'll keep this in the backlog. At least Ctrl-V works to paste in the terminal. I guess you prefer mouse, and consistency?

**Comment by spyro2000** [comment]
CTRL+V doesn't work for me, too (Windows). Can only paste with EDIT command menu.

**Comment by jim-docker** [comment]
Ctrl+shift+V should work. We'll look at cleaning things up for this and #2135

**Comment by tece81** [comment]
+1

**Comment by spyro2000** [comment]
Still not working, neither right-click nor shortcuts. Is this really so hard to fix?

**Comment by teamtitangithub** [comment]
This is major ..please fix

**Comment by charanm1985** [comment]
Same issue

**Comment by fritz-net** [comment]
also enable right click copy since shift+ctrl+c is not working nor clicking left like in powershell

**Comment by jweak** [comment]
Terminal copy on select and paste on right-click is done in the  #3904 

Which will add this preference
<img width="784" alt="image" src="https://user-images.githubusercontent.com/774344/136550263-d33b5790-b3a1-4065-a63e-20d8185b3612.png">

It's been released in the [5.3.0-alpha.0]( https://github.com/lensapp/lens/releases/tag/v5.3.0-alpha.0).
