### ISSUE TITLE
Show error message if no items loaded in ItemListLayout

### ISSUE THREAD

**Issue by aleksfront** [lensapp/lens#2060]
If there's an error occured while loading `stores` and `dependentStores` within `ItemListLayout` component, loader keeps spinning without any notification.

We must show "Failed to load items" message instead of spinner or inside popped notification.

![load store items failed](https://user-images.githubusercontent.com/9607060/106582301-e6df8a80-6554-11eb-91f0-1b8ed30a5f6d.png)
![continous spinner](https://user-images.githubusercontent.com/9607060/106582329-ed6e0200-6554-11eb-8b7c-7fe09c7a5926.png)

Also, we can customize such error message to allow parent component or extension to inform user in a descriptive manner.

**Comment by Nokel81** [comment]
This might be fixed by #2003. Is there an easy way for me to check?

**Comment by Nokel81** [comment]
Fixed by #2548
