### ISSUE TITLE
oauth2: expired refresh-token required delete/add entire cluster to work again

### ISSUE THREAD

**Issue by ThorstenKunz** [lensapp/lens#207]
**Describe the bug**
Authentication Proxy does not read changed refresh tokens for oauth2 authentication.

**To Reproduce**
1. add a cluster that is using oauth2 for authentication and has a valid id and/or refresh token in kubeconfig.
2. wait until the refresh token has expired
3. try to connect. It will show "http: proxy error: failed to refresh token: oauth2: cannot fetch token: 401"
4. now get a new refresh token and put it into your kubeconf
5. click on "Reconnect". It will still show the same error.
6. restart the entire application. It will still show the same error.
7. Remove the entire cluster and add it again. Now it works and the new refresh token is used

**Expected behavior**
1. if the refresh token has an "exp" payload timestamp indicating is has expired then show an error message tp the user that tells the user to get a new token somehow
2. if the user then clicks on "Reconnect" Lens should re-read the token from kubeconf to check if it was replaced by a new token and/or refresh-token that is not expired. It should not be necessary to delete and add the entire cluster to achieve this.

**Environment (please complete the following information):**
- Lens Version: 3.1.0
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): installer

**Comment by BrianVanEtten** [comment]
I have the same exact problem. Have to manually remove and add clusters each day.
Version: 3.1.0
OS: OSX Catalina

**Comment by intpp** [comment]
same

**Comment by Nokel81** [comment]
Related to #200
