### ISSUE TITLE
lens stays open, not visible in cmd+tab

### ISSUE THREAD

**Issue by matti** [lensapp/lens#2075]
![2021-02-03 at 10 33](https://user-images.githubusercontent.com/3893/106719714-4f893e80-660b-11eb-88d7-f7e874f0fc78.jpg)

alt+tab does not show it

**Comment by jim-docker** [comment]
Hi, what's the context? I see this behaviour when the Lens window is closed but Lens is still active (in the tray). Seems consistent with other apps (like docker desktop)

**Comment by Nokel81** [comment]
Duplicate of #1906
