### ISSUE TITLE
Lens app not showing a UI after homebrew installation

### ISSUE THREAD

**Issue by kelvin-neo** [lensapp/lens#2076]
Tried to re-install Lens (Version 4.0.8) using homebrew on MacOS Big Sur version 11.2.
This resulted in the bug shown below where the toolbar at the top is visible but UI doesn't launch.
<img width="1787" alt="Screen Shot 2021-02-03 at 5 15 14 pm" src="https://user-images.githubusercontent.com/78223661/106725548-76179b80-6644-11eb-9b79-3daec5bc7144.png">

Any idea on how to go about debugging this?

**Comment by jim-docker** [comment]
Hi, can you open the dev tools? (View -> Toggle Developer Tools)

**Comment by kelvin-neo** [comment]
> Hi, can you open the dev tools? (View -> Toggle Developer Tools)

Unfortunately no, after clicking on it, nth happens.

**Comment by jim-docker** [comment]
View -> Reload ? Or try this https://github.com/lensapp/lens/issues/2093#issuecomment-775263038, which is a similar issue

**Comment by nevalla** [comment]
Could there be any shell script that is blocking Lens to sync shell environment on launch, like in this case: https://github.com/lensapp/lens/issues/33#issuecomment-773961288

**Comment by kelvin-neo** [comment]
> View -> Reload ? Or try this [#2093 (comment)](https://github.com/lensapp/lens/issues/2093#issuecomment-775263038), which is a similar issue

Tried the afore-mentioned fix and it worked perfectly. Thanks!
