### ISSUE TITLE
Can't change PTYSHELL to wsl.exe, powershell.exe is hardcoded?

### ISSUE THREAD

**Issue by dex4er** [lensapp/lens#2087]
**Describe the bug**
I use wsl for kubernetes tools. I don't have even kubectl for Windows installed.

I try to override SHELL or PTYSHELL environment variable to `wsl.exe` and still `powershell.exe` is spawned.

**To Reproduce**
1. Go to pods list
2. Click on 'Pod shell'

**Expected behavior**
bash should be started

**Environment (please complete the following information):**
- Lens Version: 4.0.8
- OS: Windows 10 with WSL2 and Ubuntu 20.04

**Comment by jim-docker** [comment]
Do you mean to use the wsl shell in the Lens terminal? Or are you actually expecting the pod container to be able to run it?

**Comment by dex4er** [comment]
Yes, I want to use wsl.exe instead of powershell.exe in Lens terminal. Currently this 2nd is hard-coded and I can't use anything else.
