### ISSUE TITLE
Cannot connect to Kubernetes API without proxy

### ISSUE THREAD

**Issue by chiyiliao** [lensapp/lens#2088]
**Describe the bug**
There are http_proxy, https_proxy and no_proxy setting in environment.
And then set ip of kubenetes API Server to no_proxy.
Lens still connect to Kubenetes API Server through proxy.

**To Reproduce**
1. Set http_proxy, https_proxy and no_proxy in ~/.bash_profile
2. Launch Lens

**Expected behavior**
Lens should connect to kubenetes API server without proxy, and connect to other http server with proxy.

**Screenshots**

When connect to the cluster, Lens show below message in the screen:

------------------------------
kind-kind
Authentication proxy started

\<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd"> \<html>\<head> \<meta type="copyright" content="Copyright (C) 1996-2015 The Squid Software Foundation and contributors"> \<meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8"> <title>ERROR: The requested URL could not be retrieved\</title> \<style type="text/css">
...
------------------------------

**Environment (please complete the following information):**
- Lens Version: 4.0.8
- OS: MaxOS Mojave - 10.14.6
- Installation method (e.g. snap or AppImage in Linux): Upgrade Lens from old version to 4.0.8.

**Additional context**
Lens can connect to kubenetes successful when I remove http_proxy/https_proxy/no_proxy setting from ~/.base_profile.
But Charts of Apps cannot work well.

**Comment by chiyiliao** [comment]
Solved...

Lens works well when I add 127.0.0.1 and localhost to no_proxy environment variable.

**Comment by mhoria** [comment]
Until a fixed will be provided, I downgraded to version 5.4.1 where port forward works as expected.
