### ISSUE TITLE
Definition of "restart deployment" in Deployment panel?

### ISSUE THREAD

**Issue by fzyzcjy** [lensapp/lens#2090]
**What would you like to be added**:
I wonder what is the definition of "restart deployment" in Deployment panel? I have searched k8s doc without finding a command named "restart deployment". Thanks!

(The second button in this panel: )

![image](https://user-images.githubusercontent.com/5236035/107182784-5dc6c880-6a18-11eb-95b2-b032fc44125e.png)

![image](https://user-images.githubusercontent.com/5236035/107182773-556e8d80-6a18-11eb-945b-1616a28cbcb0.png)

**Why is this needed**:
N/A

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...] hosted
- Desktop OS: macos

**Comment by jim-docker** [comment]
Lens patches the spec which causes kubernetes to recreate the resources, in essence restarts the deployment. It is analogous to a (>1.15) `kubectl rollout restart`.
