### ISSUE TITLE
Memory metrics are misleading and not consistent with kubectl.

### ISSUE THREAD

**Issue by mcpappas** [lensapp/lens#2097]
**Describe the bug**
The Cluster and Node Memory metrics are not intuitive. The statistics shown are using `kube_node_status_capacity` instead of `kube_node_status_allocatable` which can be highly misleading for certain cloud providers/node VM sizes (due to provider specific resource reservations described [here](https://learnk8s.io/allocatable-resources)). In my circumstance using Azure Kubernetes Service with Standard_B2s results in a reported utilization of ~55% when it is actually ~98% according to `kubectl describe node`. This difference makes it very difficult to understand why a cluster would report `insufficient memory` when scheduling pods. Memory consumption relative to the cluster or node's total Allocatable Memory is a much more useful metric for most users who are generally only concerned with the resources available for consumption by pods/workloads. This is supported by kubectl's default reporting of node memory (i.e. relative to the allocatable memory).

**To Reproduce**
1. Connect to a cloud hosted cluster (I am familiar with Azure, but any cluster with non-negligible built-in per-node resource reservation should suffice)
2. Install the prometheus extension in Lens on the cluster.
3. Deploy a pod with a substantial memory request (e.g. 1-2GB).
3. View the memory pie chart for the cluster in Lens.
4. Observe the reported memory request percentage.
5. Run `kubectl describe node` against the same cluster
6. Observe that the reported memory request percentage is different than in step 4.

**Expected behavior**
For the memory request metrics to reflect memory available for use by Pods (the allocatable memory), not total memory capacity.

**Screenshots**
Screenshots of the views reporting memory capacity .
Memory Pie Chart in the Cluster view:
![image](https://user-images.githubusercontent.com/39843989/107272772-3114b000-6a1c-11eb-9a06-700ead63169f.png)
Memory Bar Chart in the Nodes list:
![image](https://user-images.githubusercontent.com/39843989/107272724-1fcba380-6a1c-11eb-8761-1b4b2f007b48.png)

**Environment (please complete the following information):**
- Lens Version: 4.0.8
- OS: Windows 10 64-bit
- Installation method (e.g. snap or AppImage in Linux): Windows setup exe.

**Comment by danderbury** [comment]
Did you get anywhere with this? We've just spotted the same and it took us a while to work out why we were getting reported issues with out clusters when the graphs look good.
