### ISSUE TITLE
Firefox UI bug

### ISSUE THREAD

**Issue by HristoA** [lensapp/lens#21]
Sub menu for different items is missing on all pages when is opened from Firefox. In Chrome work normally 

**Firefox:**
![image](https://user-images.githubusercontent.com/20325836/61517414-da95ea00-aa0f-11e9-8f1d-090b5f54e9b8.png)
**Chrome:**
![image](https://user-images.githubusercontent.com/20325836/61517467-fc8f6c80-aa0f-11e9-90f0-a8fac2dcef72.png)

**Comment by ixrock** [comment]
Can't reproduce it latest Lens and Firefox..
