### ISSUE TITLE
Using the windows installer it should be possible to choose the install location

### ISSUE THREAD

**Issue by christianscharr** [lensapp/lens#2102]
**What would you like to be added**:

Let user decide where to install Lens during installation process, e.g. custom directory or at least a choice between "per user" or "per machine". Looking at https://www.electron.build/configuration/nsis this should be totally possible and not that difficult to achieve.

**Why is this needed**:

Especially in corporate environments there are software distribution systems which work with different technical users to distribute and install software. So installing Lens the way the installer works at the moment leads to an installation under one of these technical users and making in impossible to use for the end-user.

**Environment you are Lens application on:**

- Kubernetes distribution: custom k8s
- Desktop OS: Windows 10 64-bit

**Comment by jim-docker** [comment]
duplicate of #1968? Should be fixed in 4.1

**Comment by christianscharr** [comment]
Yes, indeed seems to duplicate the mentioned issue. So I will wait for 4.1 being released, tested beta some minutes ago and seems to work as desired.
