### ISSUE TITLE
App obsessive registering in Login items on MacOS

### ISSUE THREAD

**Issue by Moskovych** [lensapp/lens#2107]
**Describe the bug**
After update or reboot Lens automatically add to login items.

**To Reproduce**
1. Use Lens as is and update
2. Reboot
3. Verify `Users & Groups -> Login items`

**Expected behavior**
When I delete application from login items I suspect it should remain with my choice and not be back until I change my decision.

**Screenshots**
<img width="491" alt="Screenshot 2021-02-09 at 18 54 59" src="https://user-images.githubusercontent.com/10400095/107399053-f50b4900-6b08-11eb-89f3-1416f5d35961.png">

**Environment (please complete the following information):**
- Lens Version: 4.0.8
- OS: MacOS Catalina (10.15.7)
- Installation method (e.g. snap or AppImage in Linux): `brew`

**Logs:**
N/A

**Kubeconfig:**
N/A

**Additional context**
N/A

**Comment by Nokel81** [comment]
There is a user setting called "Auto start-up" if you turn that off then Lens will remove itself from the login items and won't set it there again until you turn it on.
