### ISSUE TITLE
Deleted clusters still remain in the menu icon

### ISSUE THREAD

**Issue by wkonitzer** [lensapp/lens#2117]
**Describe the bug**
Deleted clusters still remain in the "menu icon -> clusters -> workspace"

**To Reproduce**
- Open lens
- Delete a cluster in the main app window
- Go to "menu icon -> clusters -> workspace" and observe deleted cluster is still there

**Expected behavior**
Deleted cluster should be removed from the menu icon

**Screenshots**
<img width="1395" alt="Screen Shot 2021-02-10 at 12 58 52 PM" src="https://user-images.githubusercontent.com/8270303/107557982-e3c14b80-6b9f-11eb-8519-24f689683440.png">
<img width="1408" alt="Screen Shot 2021-02-10 at 12 59 28 PM" src="https://user-images.githubusercontent.com/8270303/107557993-e754d280-6b9f-11eb-8887-10511a97023f.png">

**Environment (please complete the following information):**
- Lens Version: 4.0.8
- OS: [e.g. OSX] OSX 10.15.7
- Installation method (e.g. snap or AppImage in Linux): mac install

**Comment by jim-docker** [comment]
may be fixed by #2048

**Comment by Nokel81** [comment]
Is fixed by #2048

**Comment by drakgoku** [comment]
Maybe it's not fixed. I can't delete a cluster.
