### ISSUE TITLE
Secrets not shown in Pod Detail Panel

### ISSUE THREAD

**Issue by moreinhardt** [lensapp/lens#2118]
**Describe the bug**
I used to be able to see secrets that are loaded into a pod in the pod detail panel. Albeit, they were hidden and only revealed after an additional click.
Now I don't see them anymore at all although they are correctly loaded into the pod.

**To Reproduce**
1. Inject a secret into a pod with
```
          envFrom:
            - secretRef:
                name: my-secret
```
2. Click on the pod detail view
3. Look at the `Environment` section
4. See that there is no secret

**Expected behavior**
Used to be able to see the secrets (albeit garbled).

**Environment (please complete the following information):**
- Lens Version: 4.0.7 (also happens on edge version `4.1.0-beta.2`)
- OS: Ubuntu 20.04
- Installation method: snap

**Comment by jim-docker** [comment]
Do you have any kubernetes RBAC controls set? Have you changed how you inject the secret?

**Comment by moreinhardt** [comment]
Thank you for getting back this quickly!

> Do you have any kubernetes RBAC controls set? Have you changed how you inject the secret?

This is a gitlab-managed cluster. So there is a lot of RBAC magic going on I suppose. I don't understand this completely tbh. However, that's not new and the secrets display in lens used to work just fine with this cluster.

Also, no, I did not change how I inject the secret. While the pods may have been rebuilt some of the secrets are already >30 days old.

Were you able to reproduce this? I really hope it's not just some specific case due to my setup...

**Comment by jim-docker** [comment]
Since 4.0, Lens adheres to the RBAC configuration, so that could explain the disappearance of the secrets from Lens's display. Also, #2044 fixed an issue with `secretRef`. It might not help, but it is part of Lens 4.1, which should be out in the next day or two.
Otherwise if you can, for test purposes, relax the RBAC, or access the cluster with an admin context, you could confirm if the reason is due to  Lens's stricter adherence to RBAC.

**Comment by nevalla** [comment]
Secrets that are defined in `envFrom` property are not rendered on pod details. Created PR #2167 to fix this.
