### ISSUE TITLE
high CPU usage in idle

### ISSUE THREAD

**Issue by borgez** [lensapp/lens#2119]
**Describe the bug**
high CPU usage in idle (background)

**To Reproduce**
1. open lens
2. have 3-4 cluster config, some of them offline, all disconnected
2. go to another app like cmd

**Expected behavior**
CPU usage running low

**Screenshots**
![image](https://user-images.githubusercontent.com/2155999/107598420-afe13700-6c2e-11eb-8b8e-419f21769338.png)

**Environment (please complete the following information):**
- Lens Version: 4.0.8
- OS: win 10

**Comment by borgez** [comment]
related #1733, but it for one process

**Comment by Nokel81** [comment]
maybe related #1725

**Comment by juv** [comment]
I have the same problem on Windows 10, Lens version 4.2.1.
When I restart Lens, it is all fine again. 

I have the feeling that it _might_ be related to my temporary credentials running out and Lens trying to reconnect/refresh resources with those not-anymore-valid credentials, ending up in an excessive retry loop or similar

**Comment by Nokel81** [comment]
@juv That is a very good idea as to why this might be happening. Thanks for the information.

**Comment by Edelf** [comment]
Same problem here.
Mainly after hibernating my PC

**Comment by Nokel81** [comment]
@Edelf does it go away after regenerating your credentials?

**Comment by Edelf** [comment]
It goes away if I restart Lens.
Haven't tried running " gcloud container clusters get-credentials " while this occours. Will do next time

**Comment by juv** [comment]
I got Lens version 4.2.1 sitting at 80-90% cpu usage without it doing anything, all clusters are disconnected:

![image](https://user-images.githubusercontent.com/8269353/118477506-09b23b00-b70f-11eb-8fe1-4d1d72b979de.png)

![image](https://user-images.githubusercontent.com/8269353/118477486-0323c380-b70f-11eb-824c-bf7e55245381.png)

After pressing the [X] button in the top right of the cluster overview screen, the CPU usage is reset and Lens works again "as expected". After a few minutes, roughly 5, the main window appears to have high CPU usage again. My Lens is basically idling, one cluster (the AWS one) is connected, one Pod logs is being followed in the background. 

![image](https://user-images.githubusercontent.com/8269353/118478184-de7c1b80-b70f-11eb-9e24-a11250bd9435.png)

I disconnected all clusters again as shown in the second screenshot. Lens is still sitting at ~28-40% CPU usage despite having all clusters disconnected:
![image](https://user-images.githubusercontent.com/8269353/118478385-184d2200-b710-11eb-8c23-6358a9fabb1c.png)

After pressing the [X] button in the top right of the cluster overview screen again, Lens is now **not** showing the "back to normal" behaviour as before when I pressed that button. It's using a high percentage of my CPUs, despite every cluster being disconnected.

![image](https://user-images.githubusercontent.com/8269353/118478503-43d00c80-b710-11eb-8995-9a423c1f3ca0.png)

After closing Lens entirely, restarting it, connecting to two clusters (AWS + Openshift), refresh my AWS credentials, click around in AWS cluster resources / loading data, all appears to be normal for now (working as expected for 10 minutes after starting Lens as of this writing). CPU usage is low and only spikes when disconnecting/reconnecting to a cluster or switching views from _cluster 1_ to _cluster 2_.

Is there any way to troubleshoot this further?

**Comment by Edelf** [comment]
Having the exact same problem as @juv 
![image](https://user-images.githubusercontent.com/9094216/119543855-06f7bb80-bd89-11eb-9320-acb49cfa2965.png)

All GKE clusters disconnected.

Going into View -> Reload solves the problem.

Only one extension installed: @jakolehm/lens-extension-gke-sync
Lens version:
![image](https://user-images.githubusercontent.com/9094216/119544229-68b82580-bd89-11eb-83ac-1953f6834426.png)

**Comment by juv** [comment]
I have the feeling that this might be related to proxy settings instead of temporary credentials. Are you using a proxy @Edelf?

**Comment by juv** [comment]
When my AWS credentials have expired, I can see that lens is still doing _roughly_ 50 requests per 10 seconds eventhough they all end up in an "unauthorized" response. Cluster status is still "disconnected" at that point. So this rather excessive retry loop might actually be something that causes this CPU usage issue?

![image](https://user-images.githubusercontent.com/8269353/121657321-98ad3b80-caa0-11eb-96b7-12e8dda8931b.png)

**Comment by Nokel81** [comment]
Thanks for the devtools screenshot, that helps a lot with narrowing this down.
