### ISSUE TITLE
Large amount of fetch requests when selecting namespaces

### ISSUE THREAD

**Issue by aleksfront** [lensapp/lens#2125]
Every time an item is clicked inside namespace dropdown, large amount of fetch requests executed - items loaded for different stores and for each selected namespace accordingly. So things getting really slow as amount of selected namespaces increases.

https://user-images.githubusercontent.com/9607060/107629254-e3de4b80-6c72-11eb-80af-a1c8c0111494.mp4

Expected behavior: load nothing when choosing namespaces from dropdown.

**Comment by Nokel81** [comment]
I think that this is desired behaviour. Though we shouldn't be cancelling any requests if you only choose another namespace from the drop down (only add new requests).

**Comment by aleksfront** [comment]
Can you elaborate this a bit more? Why we ever need to load/reload something if we just trying to filter out current list view? And I assume that's not expected behavior at least in part of ui sloweness. More namespaces you selected, the slower ui would be.

**Comment by jakolehm** [comment]
Is this already fixed?

**Comment by Nokel81** [comment]
It might be yes given the changes I made to subscribing
