### ISSUE TITLE
Namespace select does not show namespaces in realtime

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#2126]
**Describe the bug**

Namespace selector will not show modifications to namespaces in realtime. I think this is a regression in 4.1.

**To Reproduce**
1. Go to "Workloads / Pods"
2. Open terminal
3. Run "kubectl create ns test-1"
3. Open namespace selector
4. "test-1" namespace is missing (will appear after a while)

**Comment by Nokel81** [comment]
Namespace selector also doesn't track `accessibleNamespaces` at all (after initial load)

**Comment by jakolehm** [comment]
Fixed in #2138
