### ISSUE TITLE
No hover effects for header elements

### ISSUE THREAD

**Issue by aleksfront** [lensapp/lens#2159]
Any hover effects doesn't properly applied to all header elements (top line with cluster name and cluster menu). It seems that something placed on top of them and covers most of their height.

https://user-images.githubusercontent.com/9607060/108056014-cd186a00-7061-11eb-8ac0-5d01e206e636.mp4

**Comment by ixrock** [comment]
@aleksfront not sure if it's fixable since it's blocked by this element which is have even `pointer-events: none`

![image](https://user-images.githubusercontent.com/6377066/113141908-f6b4db80-9232-11eb-8a1a-ffd3a8704ee8.png)

**Comment by Nokel81** [comment]
This has been resolved by recent changes to the UI
