### ISSUE TITLE
Persist the last selected namespace(s)

### ISSUE THREAD

**Issue by mboutet** [lensapp/lens#2166]
**What would you like to be added**:

Persist the last selected namespace(s) (including "All namespaces") in order for the choice to be kept between restarts and reloads. This is a only a problem since v4.1.0.

If this is too difficult to implement, an alternative could be to set the namespace(s) to select in the cluster's settings.

**Why is this needed**:

My network connection sometimes momentarily drops resulting in a reload of Lens and the loss of the selected namespaces. This can lead to missed events in the cluster since they are not shown when in the default namespace. 

Ever since 4.1.1, I find myself constantly making sure that the correct namespaces are selected. (Of course, I have other monitoring and alerting in place. However, there can be delays in the alerts and some unforeseen events might not be covered by them).

**Environment you are Lens application on:**

- Kubernetes distribution: AKS
- Desktop OS: macOS 10.15.7 (19H15)

**Comment by matthewmgr** [comment]
Please, to make this application useful again, MAKE THIS CHANGE.  I monitor, literally, 30+ clusters and every time I toggle between clusters I have to select, for every area, "All Namespaces" because we intentionally do not use default. 

Alternately...  and actually preferred for me, default to "All Namespaces".  Why would you limit what you're viewing?

**Comment by rittneje** [comment]
Agreed, I feel this change in 4.1.0 is a complete misfeature. It's pretty rare that we would even put something in the default namespace. People who want to see only the default namespace should be forced to explicitly select it in the first place, and then it could be persisted.

**Comment by rflume** [comment]
Wouldn't it probably be best to do both:
1. Set "All namespaces" as default value ...
2. ... **and** add a user option to persist last selected namespace(s per area)?
