### ISSUE TITLE
Lens 4.1 breaking on Ubuntu

### ISSUE THREAD

**Issue by williamsp** [lensapp/lens#2170]
**Describe the bug**
Unable to use & load any section after upgrading to Lens-4.1.0.x86_64 on Ubuntu.

**To Reproduce**

1. Run an old version of Lens (e.g. 4.0.8)
1. Wait until being auto-updated to 4.1.0
1. Start Lens
1. Open Developer console to see the error

**Expected behavior**
All sections should load the Kubernetes related resources properly

**Screenshots**
![gambar](https://user-images.githubusercontent.com/3760416/108197450-f7932180-714c-11eb-8ca7-7d060e1048e1.png)

**Environment (please complete the following information):**
- Lens Version: Lens-4.1.0.x86_64
- OS: Ubuntu 16.04
- Installation method: AppImage

**Logs:**
```
info: 🚀 Starting Lens from "/.config/Lens"
info: Checking for update
info: [STORE]: LOADED from /.config/Lens/config.json
info: [STORE]: LOADED from /.config/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /.config/Lens/lens-workspace-store.json
info: [STORE]: LOADED from /.config/Lens/lens-extensions.json
info: [STORE]: LOADED from /.config/Lens/lens-filesystem-provisioner-store.json
info: [CLUSTER-MANAGER]: init cluster {"id":"ba91420e-74d5-4fc9-9a75-fd9c958a6f39","name":"dev","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: LensProxy server has started at http://localhost:46717
info: [EXTENSION-DISCOVERY] loading extensions from /.config/Lens
info: [CLUSTER]: "dev" init success {"id":"ba91420e-74d5-4fc9-9a75-fd9c958a6f39","context":"dev","apiUrl":"https://www.xxx.yyy"}
```

**Additional context**
No problem found when running version 4.0.8. The problem: the app is updating itself automatically, and there are no ways to prevent it in this version (Issue #1689). So, it will delete the original image, and to be able to use it I must redownload the old version image which will be deleted again later after I quit using the app.

Network response when requesting `http://ba91420e-74d5-4fc9-9a75-fd9c958a6f39.localhost:43393/api-kube/apis/apps/v1/deployments?`:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "deployments.apps is forbidden: User \"system:serviceaccount:xxx:yyy\" cannot list resource \"deployments\" in API group \"apps\" at the cluster scope",
  "reason": "Forbidden",
  "details": {
    "group": "apps",
    "kind": "deployments"
  },
  "code": 403
}
```
Similar response returned for other URLs as well.

**Comment by fargue** [comment]
I'm having exact same issue on MacOS 11.2.1(20D74) Big Sur

**Comment by jakolehm** [comment]
@williamsp @fargue could you share any details of RBAC permissions?

**Comment by fargue** [comment]
> @williamsp @fargue could you share any details of RBAC permissions?

Could you let me know what you'd like to see?  I'm not sure how to dump RBAC permissions.

**Comment by larsschilling** [comment]
I'm having exact same issue on MacOS 11.2.1(20D74) Big Sur

**Comment by jim-docker** [comment]
Can you try adding the cluster again to Lens? Or even renaming `~/.config/Lens` (`~/Library/Application\ Support/Lens` on mac) and restarting Lens, to see if it is related to updating.

**Comment by larsschilling** [comment]
unfortunately, renaming or deleting (`~/Library/Application\ Support/Lens` )  did not work for me. the error is still there. 
[localhost-1613574688146.log](https://github.com/lensapp/lens/files/5996589/localhost-1613574688146.log)

What catches my eye is the line : `console.js:124 error: Can't find working API for the Kubernetes resource ingresses`
But I don't know if the 403 error is a result of that

**Comment by ag1989** [comment]
Same Issue for MacOS 10.15.7 can't connect anymore to my clusters :(
