### ISSUE TITLE
`TableId` uniqueness should be guaranteed on runtime

### ISSUE THREAD

**Issue by Nachasic** [lensapp/lens#2171]
Lens uses `tableId` parameter for `<ItemListLayout>` component to identify tables. Right now this parameter is a simple `string` that is set by developers in each relevant view component:
![Screen Shot 2021-02-17 at 4 09 42 PM](https://user-images.githubusercontent.com/22235527/108216990-bc3c2700-713b-11eb-8856-ce3d287b9efe.png)
Uniqueness of these IDs is not verified or enforced on runtime in any way.

Since `<ItemsListLayout>` component is used with extensions, this might introduce bugs with persistent table configurations handled by `UserStore`. We should introduce a way for developers to ensure uniqueness of `tableId`s they're using, e.g. through extension-specific namespaces.

**Comment by Nokel81** [comment]
I guess we also need a notion of owning an ID since we cannot just track which IDs are currently being used since it might not have rendered the `<ItemsListLayout>` yet.

**Comment by ixrock** [comment]
> Since `<ItemsListLayout>` component is used with extensions, this might introduce bugs with persistent table configurations handled by `UserStore`. We should introduce a way for developers to ensure uniqueness of `tableId`s they're using, e.g. through extension-specific namespaces.

Can't spot re-export of `ItemListLayout` in `src/extensions/renderer-api/components.ts`? So it seems it's not used with extensions? Anyway, adding some validator in runtime to check id-s won't hurt :)

**Comment by Nokel81** [comment]
Its props is but that is because of `KubeItemListLayout`

**Comment by ixrock** [comment]
> Its props is but that is because of `KubeItemListLayout`

Right, it's implicitly re-exported in `src/extensions/renderer-api/components.ts` with kube-object bundle:

```
export * from "../../renderer/components/kube-object";
```

**Comment by Nokel81** [comment]
@Nachasic What exactly do you want to prevent? Two different components using the same `TableId`? What if the two instances are never "alive" at the same time, what if the extension one loaded before Lens's one?

Might it be better to just prefix any extension's use of `TableId` with the Extension's name?
