### ISSUE TITLE
Lens not connecting to clusters after upgrade to v4.1.0

### ISSUE THREAD

**Issue by vkatukam** [lensapp/lens#2176]
**Describe the bug**
I have upgraded the version from 4.0.8 to 4.1.0, Lens is not connecting to my clusters, but when I go back to previous version it is working fine, seems to be an issue with New version of 4.1.0

![image](https://user-images.githubusercontent.com/46891707/108323255-74290d00-71ec-11eb-81ff-4961e1ce0aa0.png)

**Comment by vkatukam** [comment]
In this case, i don't want to upgrade to the latest version automatically, any suggestion on how to stop automatic upgrades.

**Comment by ayakimchuk322** [comment]
For me, on Windows, closing the Lens with X button does not update Lens on the next start up.
However, if closing via File - Exit - it will update on the next start up.

**Comment by williamsp** [comment]
> In this case, i don't want to upgrade to the latest version automatically, any suggestion on how to stop automatic upgrades.

Block `github-releases.githubusercontent.com` in etc/hosts.
