### ISSUE TITLE
KUBECONFIG environment-var missing from the Terminal-process

### ISSUE THREAD

**Issue by ninlil** [lensapp/lens#2180]
**Describe the bug**
kubectl in terminal have no access to the kubeconfig-file

**To Reproduce**
Steps to reproduce the behavior (on Windows 10 with WSL as shell)
1. export SHELL=wsl.exe
2. Select a cluster and open the Terminal
3. type 'kubectl clutser-info' (or anything else that accesses the cluster)
4. see "unable to access" or similar error

Reason: the KUBECONFIG is not set to the clusters kubeconfig in the terminal-process.

**Expected behavior**
the env var KUBECONFIG pointing to the file the cluster is using

**Screenshots**
(none)

**Environment (please complete the following information):**
- Lens Version: 4.1.1
- OS: Windows 10 with WSL2
- Installation method: local user in custom folder

**Logs:**
(N/A)

**Kubeconfig:**
(N/A)

**Additional context**
It's great to actually be able to use WSL as the shell, and I know there are some path-translations that need to happen because of using WSL as SHELL, but please fix this issue.

**Comment by nevalla** [comment]
Created PR #2198 to fix this. Meanwhile, you can add `KUBECONFIG/up` to `WSLENV` in Windows environment variables (or create that env variable if missing).
