### ISSUE TITLE
Put back namespace easy removal (bug ?)

### ISSUE THREAD

**Issue by UnleashSpirit** [lensapp/lens#2191]
Hello,

With the last version, we lost a "function" that I often used.
I don't know its name, even if it had one, but I think put it back would be good

In the overview panel, there was a list of selected namespaces, each one with a cross to remove it from filter.
The last version remove this possibility and I find tedious to use the dropdown list of all namespace to find the one selected to remove it
It was here (I don't have screenshot of previous version)
![image](https://user-images.githubusercontent.com/6216968/108487244-57014680-729f-11eb-8c6b-bbd1938b3ee9.png)

Info version
![image](https://user-images.githubusercontent.com/6216968/108487002-0984d980-729f-11eb-9827-4b43ad73f00a.png)

**Comment by coala-svn** [comment]
Keep in mind that it is not about "easy removal" only: before the 4.1.0 it was easy to see information on objects in which namespaces are displayed in all the "Workload" tabs. I would consider it is not an "enhancement" but a "bug": previously available information is not available after the update to 4.1.0+ and I am planning on switching back to the previous version only because of that.

If possible - please reconsider the labeling.

**Comment by jim-docker** [comment]
The nature of refactoring to improve performance when there are many namespaces has resulted in the loss of this feature. We will discuss internally how we can restore it (It may look different in the UI)

**Comment by UnleashSpirit** [comment]
Hi, an idea to restore this could be grouping selected namespaces at the top of the dropdown list ?
Like that it also be available, in all menu (pods, deployment, services, ...)

**Comment by Nokel81** [comment]
@UnleashSpirit Is this still desired? In the current version of lens (5.2 and perhaps 5.1) by default only selects one at a time (with the ability to select several and deselect ones individually). We also now sort the selected namespaces to the top of the dropdown.

**Comment by UnleashSpirit** [comment]
Hi @Nokel81 , just tried it looks good to me.
I had to figure out how to select multiple NS, just use CTLR + Click, it feels natural
And sorting with top selected is enough
Thank you :)

Lens 5.2.0-20210908.1
