### ISSUE TITLE
Errors when adding authenticated helm repositories

### ISSUE THREAD

**Issue by venkatamutyala** [lensapp/lens#2196]
**Describe the bug**
I am unable to add an authenticated helm repository

**To Reproduce**
1. Go to 'Preferences'
2. Click on 'Add Custom Helm Repo'
3. Enter Helm repo name `yolo`
4. Enter Helm repository URL `https://nexus.yolo.com/repository/helm-int`
5. Enter username 
6. Enter password
7. Click on 'Add'
6. See the error of being unauthorized in the top right of the window.

**Expected behavior**
I expected to be able to add my helm repo without errors

**Environment (please complete the following information):**
- Lens Version: 4.1.2
- OS: MacOS 11.2.1 (20D74)
- Installation method (e.g. snap or AppImage in Linux):
Downloaded straight from the releases page in github

**Logs:**

```
Adding helm branch yolo has failed: Error: looks like "https://nexus.yolo.com/repository/helm-int" is not a valid chart repository or cannot be reached: failed to fetch https://nexus.yolo.com/repository/helm-int/index.yaml : 401 Unauthorized
```

**Additional context**
I can add public unauthenticated helm repositories without any issues. I also verified my credentials are valid.
yolo.com is purely fictional. I removed my identifying domain

**Comment by Nokel81** [comment]
I would like to confirm that the following command does succeed on your system:

```
helm add repo "yolo" "https://nexus.yolo.com/repository/helm-int" --username "username" --password "password"
```

**Comment by Nokel81** [comment]
I cannot reproduce this using a local basic-auth helm repo (using helm's `chartmuseum`). @VenkataMutyala more information would be appreciated.

**Comment by Nokel81** [comment]
Removing from milestone as I cannot reproduce this. Please reopen or open a new issue if you continue to have this issue.
