### ISSUE TITLE
Cannot upgrade to 4.1.2 from 4.1.0

### ISSUE THREAD

**Issue by rittneje** [lensapp/lens#2197]
I have Lens 4.1.0 installed on my MacBook. Every time I open it, I get prompted to upgrade to 4.1.2. But if I click "Yes", Lens just exits, and nothing happens.

![image](https://user-images.githubusercontent.com/28784688/108555330-58446a80-72c3-11eb-990a-d6711a4eca2a.png)

Here are the relevant logs:

info: [UPDATE-CHECKER]: User chose to update now
info: Downloading update from Lens-4.1.2-mac.zip, Lens-4.1.2.dmg
info: Update has already been downloaded to /Users/jrittner/Library/Application Support/Caches/kontena-lens-updater/pending/Lens-4.1.2-mac.zip).
info: / requested
info: /1613765018199-2569.zip requested
info: /1613765018199-2569.zip requested by Squirrel.Mac, pipe /Users/jrittner/Library/Application Support/Caches/kontena-lens-updater/pending/Lens-4.1.2-mac.zip
info: APP:QUIT
warn: No update available, can't quit and install
error: Error: Error: No update available, can't quit and install
    at MacUpdater.quitAndInstall (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:185:24)
    at /Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:108165
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
2021-02-19 15:03:38.764 Lens[41134:15853864] Download completed to: file:///Users/jrittner/Library/Caches/com.electron.kontena-lens.ShipIt/update.N5eNPLA/1613765018199-2569.zip

**Comment by brian-arms** [comment]
I'm seeing the same behavior: Lens on MacOS Big Sur was not able to update to 4.1.1 or 4.1.2.

**Comment by nevalla** [comment]
Please download a fresh installer package from GitHub and do the manual install. Version 4.1.2 contains the fix for this auto-update issue on MacOS.
