### ISSUE TITLE
Separate Cluster Roles and Cluster Role Bindings

### ISSUE THREAD

**Issue by rittneje** [lensapp/lens#2199]
**What would you like to be added**:

Separate Cluster Roles and Cluster Role Bindings from Roles and Role Bindings under "Access Control".

**Why is this needed**:

For consistency. It is counterintuitive that these are combined today, since they are technically separate resource types.

**Environment you are Lens application on:**

- Kubernetes distribution: EKS 1.16
- Desktop OS: macOS 10.15.7

**Comment by jim-docker** [comment]
The cluster role and cluster role bindings are lumped together with the role and role bindings, by default the cluster ones are shown at the top. We can consider adding a type column to the listing to help with the distinction.

**Comment by rittneje** [comment]
That seems pretty counterintuitive and inconsistent to me. You should move them into separate items under "Access Control", since they are technically a separate resource type.

**Comment by jim-docker** [comment]
Yes, I think that is reasonable. But right now you don't have to switch to the CLI to see them.

**Comment by rittneje** [comment]
I've changed the issue title and description in light of this.
