### ISSUE TITLE
Copying fields from overlay should not include newline

### ISSUE THREAD

**Issue by rittneje** [lensapp/lens#2200]
**What would you like to be added**:

When copying a field from the overlay, don't include a trailing newline.

**Why is this needed**:

Sometimes I need to copy-paste a field (such as Name or Namespace) from the overlay in order to construct a CLI command. To do this, I triple click to select (on macOS), and then copy and paste. However, this always includes a trailing newline, so when I paste it into the terminal, it tries to execute the half-formed command.

**Environment you are Lens application on:**

- Kubernetes distribution: n/a
- Desktop OS: macOS 10.15.7

**Comment by Nokel81** [comment]
Would you be able to upload a short video demonstrating the problem. Is this when searching pod logs?

**Comment by rittneje** [comment]
When I copy-paste the highlighted text (triple click then cmd + C, cmd + V), it includes a trailing newline.

![image](https://user-images.githubusercontent.com/28784688/110357964-da45ca80-8009-11eb-8170-dbcaa076580b.png)

So for example, if I intend to type `kubectl get pod <PASTE> -n kube-system`, this happens instead, since the terminal triggers the command when the newline is pasted.
```
$ kubectl get pod cluster-autoscaler-7f5f7777c9-4g7mk
Error from server (NotFound): pods "cluster-autoscaler-7f5f7777c9-4g7mk" not found
```

**Comment by Nokel81** [comment]
Thanks I was just not sure what you meant by "overlay". This is enough to go on.

**Comment by Nokel81** [comment]
Changing this to 5.0.0. 

So @rittneje from our investigation, the OS is adding that newline when you triple click (or sometimes when you drag to highlight). We can do some preventative measures but from a data perspective that newline isn't there.
