### ISSUE TITLE
Lens doesn't pickup new namespaces

### ISSUE THREAD

**Issue by shinebayar-g** [lensapp/lens#2206]
**Describe the bug**
I had Lens open and created new namespace. Lens doesn't show this new namespace.

**To Reproduce**
1. Open Lens
2. Create namespace
3. You cannot find it in namespace select dropdown menu until you close lens and open it again.

**Expected behavior**
Select namespace successfully.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 4.1.2
- OS: Windows
- Installation method: Windows installer

**Logs:**

**Kubeconfig:**

**Additional context**

**Comment by jim-docker** [comment]
Hi, I can't reproduce (works fine for me on Windows, Lens 4.1.2). Do you have RBAC restrictions set? What name are you using for the new namespace?

**Comment by shinebayar-g** [comment]
Hi, new namespace was called `qcx` I've cluster administrator role. This was EKS cluster. 

Surprisingly I can't reproduce too. I guess this was some network hiccup. Sorry for the noise.

/close
