### ISSUE TITLE
Drawer or Modal popup gets recreated when it is connected to Mobx

### ISSUE THREAD

**Issue by hansiemithun** [lensapp/lens#2208]
**Description**
Drawer or Modal popup gets recreated when it is connected to Mobx or redux and this behavious is seen greater version of 4.0.8.

**To Reproduce**

Call a AddDialog box from addorremove property using KubeObjectList.

Mount the AddDialog inside the same file. Trigger the open from KubeListTableControls i.e add icon with mobx. It opens and stays for sometime and gets closed after few seconds. This is happening after >4.0.8 versions.

The behaviour is same Drawer component as well

**Expected behavior**
The drawer which is opened or modal popup should not be closed and the values inside should be retained.

**Comment by Nokel81** [comment]
Do you mean the `KubeObjectListLayout` component? If so there is no `AddDialog` "box". There is `addRemoveButtons` as a prop of `KubeObjectListLayout` but is a fixed component that is about rendering `+` and `-` buttons in the bottom right.

Would you mind providing more precise details, perhaps even code and a short video? Thanks.

**Comment by hansiemithun** [comment]
@Nokel81 - From the below short video clip of 30seconds, you will see the drawer is getting closed and opened again by itself after 20 seconds. 

https://user-images.githubusercontent.com/3661669/108976628-ba2f1680-76ad-11eb-940e-ad51ef48f302.mp4


The code is as simple as secrets.tsx page

  ```
@observer
   class VirtualNetworkCore extends React.Component<IVirtualNetworkProps> {
       ....
       addRemoveButtons={{
              onAdd: () => AddSecretDialog.open(),
              addTooltip: 'Create new Secret',
            }}
          />
        </Component.TabLayout>
        <AddSecretDialog />
    }
```
**AddSecretDialog component**
```
import React from 'react';

import { Component } from '@k8slens/extensions';
import { observable } from 'mobx';
import { observer } from 'mobx-react';


@observer
class AddSecretDialog extends React.Component {
  @observable public static isOpen = false;

  public static open() {
    AddSecretDialog.isOpen = true;
  }

  public render() {
    return (
      <div>
        <Component.Drawer
          open={AddSecretDialog.isOpen === true ? true : false}
          onClose={() => console.log('close called..')}
          title={'Test Title'}
        >
          <h1>Hello World! - 6</h1>
        </Component.Drawer>
      </div>
    );
  }
}

export default AddSecretDialog;

```

**Lens version in use:** 
![Screenshot 2021-02-24 at 2 40 39 PM](https://user-images.githubusercontent.com/3661669/108977168-47726b00-76ae-11eb-8d10-f5f1d3fbb3ac.png)

**Package dependencies FOR YOUR INFORMATION** 

 ```
 "dependencies": {
    "@k8slens/extensions": "4.0.0-beta.3",
    "antd": "4.8.4",
    "dayjs": "1.10.4",
    "k8s-api": "1.2.19",
    "lodash": "4.17.20",
    "react-dom": "17.0.1",
    "react-jsonschema-form": "1.8.1",
    "react-router": "5.2.0",
    "rjsf-antd": "0.1.5-alpha.17",
    "mobx": "^5.15.7",
    "mobx-observable-history": "^1.0.3",
    "mobx-react": "^6.2.2"
  },
  "devDependencies": {
    "@ant-design/compatible": "1.0.8",
    "@ant-design/icons": "4.5.0",
    "@rjsf/antd": "2.3.0",
    "@rjsf/core": "2.4.2",
    "@types/lodash": "4.14.108",
    "@types/node": "12.0.0",
    "@types/react": "16.9.35",
    "@types/react-jsonschema-form": "1.7.4",
    "@types/react-redux": "^7.1.16",
    "@types/redux": "^3.6.0",
    "@types/redux-devtools-extension": "^2.13.2",
    "css-loader": "5.0.1",
    "husky": "4.3.7",
    "prettier": "2.1.1",
    "pretty-quick": "3.1.0",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-observable": "^1.2.0",
    "sass": "1.32.0",
    "sass-loader": "10.0.2",
    "style-loader": "2.0.0",
    "stylelint": "12.0.0",
    "stylelint-config-prettier": "8.0.0",
    "stylelint-config-standard": "19.0.0",
    "stylelint-scss": "3.13.0",
    "ts-loader": "8.0.4",
    "tslint": "5.20.1",
    "tslint-config-prettier": "1.18.0",
    "tslint-eslint-rules": "4.1.1",
    "tslint-loader": "3.6.0",
    "tslint-no-circular-imports": "0.3.0",
    "tslint-plugin-prettier": "2.0.1",
    "tslint-react": "3.2.0",
    "tslint-react-hooks": "2.2.1",
    "tslint-staged": "0.1.3",
    "typescript": "4.0.3",
    "webpack": "4.44.2",
    "webpack-cli": "3.3.11"
  },
```

Also updated  "@k8slens/extensions": "4.0.0-beta.3" to latest version to match lens, but still no luck. Please check

**Other Environment Versions** 

**Environment:** Mac
**Node Version:** v12.17.0
**NPM Version:** 6.14.4

**Comment by hansiemithun** [comment]
One more demo video where the data is not retained and lost:
https://user-images.githubusercontent.com/3661669/109012739-58d06d00-76d8-11eb-9059-690b7880db38.mp4

**Comment by hansiemithun** [comment]
Any update on this, this is an absolute show stopper and blocker to proceed with
