### ISSUE TITLE
Lens Error: Could not find a free port for the cluster proxy

### ISSUE THREAD

**Issue by matti** [lensapp/lens#221]
![overlay_navigate_countup_sh_—_amplifier_master_and_Superapp](https://user-images.githubusercontent.com/3893/78504353-47efd380-7775-11ea-93a2-7a38950a6348.png)
 
Don't know how I did this but the lens won't start and always dies with this message. I think I need to reboot.

**Comment by jakolehm** [comment]
Port finder got update in v3.4.0. Let's reopen if this pops up again.

**Comment by jheld** [comment]
Happening for me now (unsure if it's the same root cause).

on mac os x, 10.15.4, lens version: 3.4.0 (3.4.0.20200509.5)

I restarted my computer the day before and today I tried to reopen lens (I didn't update the OS, just did a restart).

**Comment by durch** [comment]
Also seeing this on 3.6.9
