### ISSUE TITLE
Not loaded Workloads tab

### ISSUE THREAD

**Issue by xdeveloper** [lensapp/lens#2212]
![image](https://user-images.githubusercontent.com/988712/108880059-94046a80-760a-11eb-9d2f-f111fd03a675.png)

Can reproduce on latest version.

Works OK on 4.0.6. version.

**Comment by xdeveloper** [comment]
![image](https://user-images.githubusercontent.com/988712/108880332-dded5080-760a-11eb-835f-a43233798798.png)

**Comment by Nokel81** [comment]
Any logs from "View > DevTools > Console" would be great.

**Comment by xdeveloper** [comment]
![Uploading image.png…]()

**Comment by xdeveloper** [comment]
![image](https://user-images.githubusercontent.com/988712/108966574-02870e00-7687-11eb-9cec-27c0a926cccf.png)

**Comment by xdeveloper** [comment]
Only this version works OK on my PC (windows 10):   Lens-Setup-4.0.0-rc.2

**Comment by xdeveloper** [comment]
![image](https://user-images.githubusercontent.com/988712/108977053-d5d7f400-7690-11eb-89f8-649684b320c1.png)

**Comment by xdeveloper** [comment]
and this (on the first run of Lens)

**Comment by jim-docker** [comment]
Do you have RBAC set up on this cluster?

**Comment by Nokel81** [comment]
Is this still happening?

**Comment by servo1x** [comment]
Users who do not have access to the default namespace and only have access to specific namespaces aren't able to render anything in workloads in v4.2.1, they do not have cluster resource (nodes, etc) access either. This use to work before - where they could just see the resources in the namespace they had access to.

**Comment by Nokel81** [comment]
@servo1x Do they have list namespace permissions? If not can you get them to add the namespaces they have access to under cluster settings > accessible namespaces.

**Comment by servo1x** [comment]
Thanks @Nokel81, that seems to work. It might be helpful to be able to manually specify the accessible namespaces when adding a cluster.

**Comment by Nokel81** [comment]
Agreed that that might be useful, in 4.2.0 we added a notification when the cluster doesn't have list namespaces permissions to direct the user to add them. 

I am going to mark this as closed since you have gotten it working and we have the functionality for manually listing accessible namespaces. If you would like to see that UI change please create a new enhancement request.
