### ISSUE TITLE
cmd + k does not clear the terminal

### ISSUE THREAD

**Issue by d-expired** [lensapp/lens#2214]
**Describe the bug**
When I press cmd + k in the terminal window, nothing happens. The default behaviour on Mac to clear a terminal is `cmd + k`. This works in the default terminal, in iTerm etc...

**To Reproduce**
1. Open the terminal
2. kubectl get all -A
3. cmd + k
4. See it do nothing...

**Expected behavior**
I expect the terminal to be cleared.

**Environment (please complete the following information):**
- Lens Version: 4.1.2
- OS: [e.g. OSX] OSX 10.15.7 (19H524)
- Installation method (e.g. snap or AppImage in Linux): brew install lens

**Comment by jim-docker** [comment]
Did you try Ctrl+L (or Ctrl+shift+L)?

**Comment by d-expired** [comment]
Ctrl+L is the same as typing "clear". If you scroll up the text from the previous commands/outputs are still there. There is a big difference between the two.

_Taken from Superuser.com:_
`One difference is that Cmd+K clears the scrollback buffer as well as the screen. Ctrl+L only clears the screen, effectively moving what is on it "up" into the scrollback buffer.`

`Another difference is that Ctrl+L is performed by the process running inside Terminal. For instance, bash will clear the screen and redraw the prompt, including any unfinished command there. Other programs might not do anything, or might refresh the screen without clearing it.`

`Cmd+K, on the other hand, is performed by Terminal itself, regardless of what's running in the window, so it might hide the output from the program.`
