### ISSUE TITLE
Garbled graphics with external 4K monitor

### ISSUE THREAD

**Issue by torbjornvatn** [lensapp/lens#222]
**Describe the bug**
The graphics is all garbled on my MacBook when connected to an external monitor.
If I open the app without the monitor connected it looks OK, even if I reconnect the monitor afterwards.

**To Reproduce**
When first opening the app and the MacBook is connected to an external 4K monitor via USB-C

**Screenshots**
<img width="1442" alt="Screenshot 2020-04-06 at 10 11 43" src="https://user-images.githubusercontent.com/4453/78537270-80cc8e80-77ef-11ea-8a6e-0bc69cc28abe.png">

**Environment (please complete the following information):**
- Lens Version: 3.2.0-rc.1
- OS: MacOS 10.15.4

**Comment by mapyr** [comment]
@torbjornvatn I have MBPro and USB-C->HDMI 4k monitor and I have the same problem.
This is hardware / macOS problem. I saw this artifact couple times with another software, not only with Lens.

**Comment by adamgreenhalgh** [comment]
I am seeing this too with a 4k monitor over a usb-c connection
