### ISSUE TITLE
Windows installer fails

### ISSUE THREAD

**Issue by jim-docker** [lensapp/lens#2222]
**Describe the bug**
Trying to update to 4.1.3 on Windows from 4.1.2. Picking "Yes, now" leads to the installer running, presenting the "Choose Installation Options" dialog. Clicking "Next" shows the "Installing" dialog, which seems to disappear before completing. Nothing else happens. Lens does not appear in the Windows "Apps & features". Lens can be started (from recent apps) but it is still version 4.1.2

Installation works if you select "Yes, later", quit lens and then wait to see that 4.1.3 is installed (in "Apps & features")

- Lens Version: 4.1.2
- OS: [e.g. OSX] Windows
- Installation method (e.g. snap or AppImage in Linux): Windows installer

https://user-images.githubusercontent.com/40840436/109068363-c3c07a80-76bd-11eb-8840-82f60cfd035d.mov

Maybe there should be no installation options allowed when updating?

**Comment by bielitom** [comment]
Upgrade Lens using manually downloaded installation package, when Lens is fully closed

**Comment by Nokel81** [comment]
Fixed by #2232 (the solution is to get Lens to quit)
