### ISSUE TITLE
Dark edit recourse area in light color theme

### ISSUE THREAD

**Issue by rigmad-old** [lensapp/lens#2224]
**Describe the bug**
Dark edit resource area in light color theme.

**To Reproduce**
1. Go to edit any recourse 

**Expected behavior**
All elements of interface are equal.

**Screenshots**
![2021-02-25 120200](https://user-images.githubusercontent.com/16268791/109121973-6120ba80-7761-11eb-95f9-e4e05a244cbb.png)

**Environment (please complete the following information):**
- Lens Version: 4.1.3 (in 4.1.0 - 4.1.2 same problem, in 4.0.8 work fine)
- OS: Windows 10
- Installation method: from installer

**Comment by jim-docker** [comment]
We had the terminal originally matching the theme but some found it unusable in light mode. We may add finer theme configuration in the future (theme extension perhaps).

**Comment by Nokel81** [comment]
Related to #1166
