### ISSUE TITLE
Can't see application window

### ISSUE THREAD

**Issue by jyami-kim** [lensapp/lens#2225]
**Describe the bug**
I install lens(macOS) application. But Lens application window doesn't appear.

**To Reproduce**
1. I downloaded https://github.com/lensapp/lens/releases/tag/v4.1.3 > Lens-4.1.3.dmg
2. and installed and launched application
3. But Lens window did not appear

**Expected behavior**
window does not appear even clicked application.

**Screenshots**
![image](https://user-images.githubusercontent.com/26458200/109123335-0ef58e80-778d-11eb-8d3e-6bc575379ffd.png)
![image](https://user-images.githubusercontent.com/26458200/109123427-2d5b8a00-778d-11eb-80e4-ae9f644c5114.png)
![image](https://user-images.githubusercontent.com/26458200/109123442-30ef1100-778d-11eb-82af-9d9a8706f4ed.png)
![image](https://user-images.githubusercontent.com/26458200/109123489-3e0c0000-778d-11eb-92d0-f53bffd6be41.png)
![image](https://user-images.githubusercontent.com/26458200/109123451-33ea0180-778d-11eb-8204-afb6b884daa4.png)

**Environment (please complete the following information):**
- Lens Version: 4.1.3
- OS: mac OS
![image](https://user-images.githubusercontent.com/26458200/109123548-51b76680-778d-11eb-9894-52204cec7b7a.png)
- Installation method (e.g. snap or AppImage in Linux): https://github.com/lensapp/lens/releases/tag/v4.1.3 > dmg

**Comment by jim-docker** [comment]
same as or similar to #2195

**Comment by jyami-kim** [comment]
@jim-docker 
I also have ``info: APP:ACTIVATE {"hasVisibleWindows":false}`` log.
Therefore I also reinstall lens as homebrew.

Thank you for your help :) now I resolve this issue.
