### ISSUE TITLE
Group filtering does not work in Custom Resources

### ISSUE THREAD

**Issue by fabfianda** [lensapp/lens#2228]
**Describe the bug**
Under the Custom Resources / Definitions panel the group filtering has no effect.

**To Reproduce**
1. Go to Custom Resources -> Definitions
2. Click on filter (top right) and select any group name
4. Custom Resources list does not change 

**Expected behavior**
List to show just resources for the group selected.

**Environment (please complete the following information):**
- Lens Version: 4.1.1
- OS: Ubuntu 20.04.2 
- Installation method (e.g. snap or AppImage in Linux): AppImage

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Ran from the command line but no logs generated.
```

**Comment by pashevskii** [comment]
The deal in `get items() ` of components/item-object-list/item-list-layout.tsx. It needs to be refactored. I'll take this ticket

**Comment by pashevskii** [comment]
https://github.com/lensapp/lens/pull/2123 fixes this issue
