### ISSUE TITLE
Able to stop a port-forward from Lens

### ISSUE THREAD

**Issue by lucj** [lensapp/lens#2230]
**What would you like to be added**:

The possibility to have a better control on port-forward.
When clicking on a port, a port-forward is run and the a new tab is open in the browser. 

<img width="379" alt="Capture d’écran 2021-02-23 à 22 00 09" src="https://user-images.githubusercontent.com/182406/109154120-23765e80-776e-11eb-8d8e-a4e57c1fe280.png">

To know if a node-port is running we need to check the OS processes which is not really convenient.

**Environment you are Lens application on:**

- Kubernetes distribution: common to all environments

- Desktop OS: common to all OSes

**Comment by jim-docker** [comment]
fixed by #3922
