### ISSUE TITLE
Protocol handlers for common app views

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#2236]
- landing page (initial view)
- cluster view
- cluster settings
- extensions
- add cluster

**Comment by nelsondani** [comment]
> - landing page (initial view)
> 33.000___****___]()
> - cluster view
> 
> - cluster settings
> 
> - extensions
> 
> - add cluster

**Comment by nelsondani** [comment]
> - landing page (initial view)
> 23.000[_**[]()**_]()
> - cluster view
> 
> - cluster settings
> 
> - extensions
> 
> - add cluster
