### ISSUE TITLE
Regression 4.0.8 -> 4.1.3 Cannot list helm releases on OpenShift 3.11

### ISSUE THREAD

**Issue by Xaseron** [lensapp/lens#2239]
**Describe the bug**
After the upgrade from 4.0.8 to 4.1.3 i cannot get information about my Helm Releases.
The spinner spins forever.

**To Reproduce**
1. Click on Apps
2. Click on Releases
3. Spinner spins forever

**Expected behavior**
List of my Helm Releases

**Environment (please complete the following information):**
- Lens Version: 4.1.3
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux):
exe

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```
Any hints how i can get log output for this issue?

**Comment by jim-docker** [comment]
https://docs.k8slens.dev/v4.1.3/faq/#where-can-i-find-application-logs

You can also start Lens from the bash or powershell console  (`~/AppData/Local/Programs/Lens/Lens.exe`). Set `DEBUG=true` in your environment to get more verbose logs. Observe log output in the console window.

**Comment by Xaseron** [comment]
log:
```
[31merror[39m: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\mcwr\\AppData\\Local\\Programs\\kontena-lens\\resources\\app.asar\\static\\build\\main.js:1:144588)\n    at ProxyServer.emit (C:\\Users\\mcwr\\AppData\\Local\\Programs\\kontena-lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\mcwr\\AppData\\Local\\Programs\\kontena-lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:223:5)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"}
[31merror[39m: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\mcwr\\AppData\\Local\\Programs\\kontena-lens\\resources\\app.asar\\static\\build\\main.js:1:144588)\n    at ProxyServer.emit (C:\\Users\\mcwr\\AppData\\Local\\Programs\\kontena-lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\mcwr\\AppData\\Local\\Programs\\kontena-lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:223:5)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"}
[31merror[39m: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\mcwr\\AppData\\Local\\Programs\\kontena-lens\\resources\\app.asar\\static\\build\\main.js:1:144588)\n    at ProxyServer.emit (C:\\Users\\mcwr\\AppData\\Local\\Programs\\kontena-lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\mcwr\\AppData\\Local\\Programs\\kontena-lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:223:5)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"}
[31merror[39m: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\mcwr\\AppData\\Local\\Programs\\kontena-lens\\resources\\app.asar\\static\\build\\main.js:1:144588)\n    at ProxyServer.emit (C:\\Users\\mcwr\\AppData\\Local\\Programs\\kontena-lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\mcwr\\AppData\\Local\\Programs\\kontena-lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:223:5)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"}
[32minfo[39m: [WINDOW-MANAGER]: Loading Main window from url: http://localhost:52150 ...
[32minfo[39m: [CLUSTER]: activate {"id":"02af59d0-8850-4793-88a1-da0dce492527","name":"TOPSECRET","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
[32minfo[39m: [CLUSTER]: bind events {"id":"02af59d0-8850-4793-88a1-da0dce492527","name":"TOPSECRET","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
[32minfo[39m: [CLUSTER]: reconnect {"id":"02af59d0-8850-4793-88a1-da0dce492527","name":"TOPSECRET","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
[32minfo[39m: [STORE]: LOADED from C:\Users\mcwr\AppData\Roaming\Lens\config.json
[32minfo[39m: [STORE]: LOADED from C:\Users\mcwr\AppData\Roaming\Lens\lens-workspace-store.json
[32minfo[39m: [STORE]: LOADED from C:\Users\mcwr\AppData\Roaming\Lens\lens-cluster-store.json
[32minfo[39m: [STORE]: LOADED from C:\Users\mcwr\AppData\Roaming\Lens\lens-extensions.json
[32minfo[39m: [STORE]: LOADED from C:\Users\mcwr\AppData\Roaming\Lens\lens-filesystem-provisioner-store.json
[32minfo[39m: [WORKSPACE-STORE] requesting initial state sync
[32minfo[39m: [CLUSTER-STORE] requesting initial state sync
[32minfo[39m: [CLUSTER-STORE] start to listen (1)
[32minfo[39m: [WORKSPACE-STORE] starting to listen state events
[32minfo[39m: [EXTENSION]: enabled kube-object-event-status@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-metrics-cluster-feature@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-node-menu@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-pod-menu@0.1.0
[32minfo[39m: [STORE]: LOADED from C:\Users\mcwr\AppData\Roaming\Lens\extension-store\lens-survey\preferences-store.json
[32minfo[39m: [EXTENSION]: enabled lens-survey@0.1.0
[32minfo[39m: [STORE]: LOADED from C:\Users\mcwr\AppData\Roaming\Lens\extension-store\lens-telemetry\preferences-store.json
[32minfo[39m: [EXTENSION]: enabled lens-telemetry@0.1.0
[32minfo[39m: [LENS-VIEW]: init dashboard, clusterId=02af59d0-8850-4793-88a1-da0dce492527
[32minfo[39m: [LENS-VIEW]: waiting cluster to be ready, clusterId=02af59d0-8850-4793-88a1-da0dce492527
[31merror[39m: Can't find working API for the Kubernetes resource ingresses
[32minfo[39m: [KUBE-AUTH]: out-channel "kube-auth:02af59d0-8850-4793-88a1-da0dce492527" {"data":"Authentication proxy started\n","meta":{"id":"02af59d0-8850-4793-88a1-da0dce492527","name":"TOPSECRET","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}}
[32minfo[39m: [LENS-VIEW]: loaded from http://02af59d0-8850-4793-88a1-da0dce492527.localhost:52150/
[32minfo[39m: [STORE]: LOADED from C:\Users\mcwr\AppData\Roaming\Lens\config.json
[32minfo[39m: [STORE]: LOADED from C:\Users\mcwr\AppData\Roaming\Lens\lens-workspace-store.json
[32minfo[39m: [STORE]: LOADED from C:\Users\mcwr\AppData\Roaming\Lens\lens-cluster-store.json
[32minfo[39m: [STORE]: LOADED from C:\Users\mcwr\AppData\Roaming\Lens\lens-extensions.json
[32minfo[39m: [STORE]: LOADED from C:\Users\mcwr\AppData\Roaming\Lens\lens-filesystem-provisioner-store.json
[32minfo[39m: [WORKSPACE-STORE] requesting initial state sync
[32minfo[39m: [CLUSTER-STORE] requesting initial state sync
[32minfo[39m: [CLUSTER-STORE] start to listen (5)
[32minfo[39m: [WORKSPACE-STORE] starting to listen state events
[32minfo[39m: [APP]: Init dashboard, clusterId=02af59d0-8850-4793-88a1-da0dce492527, frameId=5
[32minfo[39m: [EXTENSION]: enabled kube-object-event-status@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-metrics-cluster-feature@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-node-menu@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-pod-menu@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-survey@0.1.0
[32minfo[39m: [STORE]: LOADED from C:\Users\mcwr\AppData\Roaming\Lens\extension-store\lens-telemetry\preferences-store.json
[32minfo[39m: [EXTENSION]: enabled lens-telemetry@0.1.0
[32minfo[39m: [WINDOW-MANAGER]: Main window loaded
```

**Comment by Xaseron** [comment]
From the developer tools when i try to access the releases:
![grafik](https://user-images.githubusercontent.com/1352894/109967483-c6d8ed80-7cf1-11eb-8a8f-7f8701a4747c.png)

I don't get these errors in 4.0.8

**Comment by jim-docker** [comment]
I can reproduce this with RBAC restrictions. Do you have RBAC applied for your kube context?

**Comment by jim-docker** [comment]
We did some digging, tried 4.0.8 for an RBAC-limited kube context. The spinner does not spin forever but the releases list is empty. The reason being that Helm v3 uses [secrets as storage for release information](https://v3.helm.sh/docs/faq/#secrets-as-the-default-storage-driver) Thus if there are no permissions for secrets the Helm releases cannot be determined. 
We have some code changes coming in one of the next patch or minor releases to fix the spinner and give a better notification of the issue but if your cluster (context) doesn't have secrets permissions you still won't be able to see the Helm releases.

**Comment by Xaseron** [comment]
What do you mean by `RBAC-limited kube context`. The cluster has RBAC. The kube config gets generated by `oc login`

With the update to 4.1.4 Lens go unuseable. I don't get any ouput just a blank page:
![grafik](https://user-images.githubusercontent.com/1352894/110486061-9081e080-80ec-11eb-8838-6b50565f6a5e.png)

When i try to reload the page i get this exception:
![grafik](https://user-images.githubusercontent.com/1352894/110486137-a5f70a80-80ec-11eb-98b9-730b669cf8e3.png)

**Comment by jim-docker** [comment]
This could be a "bad kubeconfig" issue. We hoped we fixed these issues with 4.1.4. Does `oc login` produce a different (name or path) kubeconfig file?
Does Lens start properly if you rename `C:\Users\mcwr\AppData\Roaming\Lens`? (don't delete it if you want to keep your Lens clusters config, which should still work with 4.1.3)

Regarding the Helm releases issue, if you don't have get/list RBAC permissions for secrets (specifically helm release secrets) then Lens cannot show any Helm releases

**Comment by Xaseron** [comment]
> This could be a "bad kubeconfig" issue. We hoped we fixed these issues with 4.1.4. Does `oc login` produce a different (name or path) kubeconfig file?

i do `oc login` in WSL and have the .kube/config symlinked
```sh
 % ls -la .kube
lrwxrwxrwx 1 mcwr mcwr 23 Sep 10 15:37 .kube -> /mnt/c/Users/mcwr/.kube
```

> Does Lens start properly if you rename `C:\Users\mcwr\AppData\Roaming\Lens`? (don't delete it if you want to keep your Lens clusters config, which should still work with 4.1.3)

Nope it just wents blank after authentication.

> Regarding the Helm releases issue, if you don't have get/list RBAC permissions for secrets (specifically helm release secrets) then Lens cannot show any Helm releases

I can do oc/kubectl get secrets and also describe each secret.

**Comment by Nokel81** [comment]
So just to clarify. You can view the cluster. But when you go to the helm releases page nothing shows up? This is probably fixed by #2262

**Comment by Xaseron** [comment]
@Nokel81 I can view Deployments and every native Kubernetes resource. But on the Helm release page the spinner spins forever and this is the error from the developer view:

![grafik](https://user-images.githubusercontent.com/1352894/113677463-e5018700-96bd-11eb-8ce6-d115dc93782e.png)

I've tested it with 4.2.0 and problem still persists.

**Comment by tonycpsu** [comment]
Same issue here.  Have to downgrade to 4.0.8 to install new Helm releases.  To add insult to injury, it automatically installs 4.2.0 without asking me.

**Comment by Nokel81** [comment]
I have marked this as 4.2.1 (actually 4.2.2 since 4.2.1 is out tomorrow and I don't think fixes this).

**Comment by Nokel81** [comment]
I think this is fixed by #2262. If this is still an issue after 4.2.1 is released, please re open.

**Comment by Xaseron** [comment]
Problem still persists:

![grafik](https://user-images.githubusercontent.com/1352894/114358534-4e2c4300-9b73-11eb-9c45-5cfce36b4923.png)

**Comment by Nokel81** [comment]
Can you provide which helm chart releases? Because those errors are returned from `helm` (helm3) CLI directly.

**Comment by Xaseron** [comment]
What do you mean by helm chart releases? The charts are self developed. How can i find out which helm version Lens uses?

**Comment by Nokel81** [comment]
Lens uses helm3 .

Specifically 3.4.2

**Comment by Nokel81** [comment]
Can you please post the `xd` error message?

**Comment by Xaseron** [comment]
I did some tests with the cli. Are you doing a `helm list -A`? Because this is not possible because of the OpenShit hardening:
```sh
mcwr@W4DEUMSY9003400 ~ % helm list
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                                                                                                                                 APP VERSION
dynatrace-agent         pnp-sdc-test    4               2021-03-09 15:22:35.194882 +0100 CET    deployed        dynatrace-agent-20210309.0937.44                                                                                                                      latest
sdc-db                  pnp-sdc-test    1               2021-03-03 17:41:26.772728 +0100 CET    deployed        mongodb-10.7.2                                                                                                                                        4.4.4
simplenodeapp-stefan    pnp-sdc-test    1               2021-04-12 05:38:48.631291979 +0000 UTC deployed        simplenodeapp-20210412.0736.53-stefan                                                                                                                 20210412.0736.53-stefan
testdb                  pnp-sdc-test    1               2021-03-02 11:29:43.325066 +0100 CET    deployed        mongodb-10.7.1                                                                                                                                        4.4.4
testdb3                 pnp-sdc-test    1               2021-03-11 10:34:54.9286745 +0100 CET   deployed        mongodb-10.10.1                                                                                                                                       4.4.4
mcwr@W4DEUMSY9003400 ~ % helm list -A
Error: list: failed to list: secrets is forbidden: User "SECRETUSER" cannot list secrets at the cluster scope: no RBAC policy matched
```
Disclaimer i masked my user in the error

**Comment by Nokel81** [comment]
Yes we do, we do the following: `helm ls --output json --all-namepsaces --kubeconfig <path/to/kubeconfig>`

**Comment by Nokel81** [comment]
So I guess the solution would be to have the `NamespaceSelectFilter` be respected for releases as well.

However, as that error message states you will need secrets permissions.

**Comment by Xaseron** [comment]
The OpenShit cli creates a context for each namespace. It doesn't make sense to query `--all-namespaces`. You cannot access other namespaces.

**Comment by Xaseron** [comment]
> 
> 
> Yes we do, we do the following: `helm ls --output json --all-namepsaces --kubeconfig <path/to/kubeconfig>`

Which command was used in the 4.0.8 release?

**Comment by Nokel81** [comment]
Same command, hasn't changed in over 6 months

**Comment by Xaseron** [comment]
> 
> 
> Can you please post the `xd` error message?

![grafik](https://user-images.githubusercontent.com/1352894/114405025-8dc05280-9ba6-11eb-95e5-e6a3bb4b22d1.png)

**Comment by Nokel81** [comment]
So that seems like we cannot access your self hosted charts, which is why we don't display anything.

So if you list by namespace, does that work for you?

**Comment by Xaseron** [comment]
Yes, `helm list` for the current namespace works fine.

`helm list -A` fails with the RBAC error.

My idea would be if `kubectl get namespaces` fails then helm should never use `--all-namespaces` option.

**Comment by Nokel81** [comment]
The problem with that is Lens doesn't know which namespace to use. That is why I suggested respecting the `NamespaceSelectFilter`.

The other problem with switching away from `--all-namespaces` on failure is that (as seen above) it might be related to other issues (like the listing of secrets).

**Comment by Xaseron** [comment]
kubectl get secrets works fine.

The correct namespace appears: 
![grafik](https://user-images.githubusercontent.com/1352894/114407313-8dc15200-9ba8-11eb-8ada-4ca1883f0579.png)

That could be a possible solution.

What else could be the breaking change in 4.1.0?

**Comment by Nokel81** [comment]
I don't know I do see the bug in the code. We seem to be incorrectly special casing releases. Will reopen this and submit a fix. Thanks for all the information.

FYI #2262 will also make this slightly less "black-boxy" in the future.

**Comment by Nokel81** [comment]
@Xaseron Would you be able to try out #2515? Just clone this repo and checkout that branch and run `make dev`.

**Comment by Xaseron** [comment]
javascript dependency hell:
```
% make dev            
yarn install
yarn install v1.22.10
[1/5] Validating package.json...
error kontena-lens@4.2.1: The engine "node" is incompatible with this module. Expected version ">=12 <13". Got "15.14.0"
error Found incompatible module.
```

**Comment by jim-docker** [comment]
node version between 12 and 13 is required to build Lens. If you can easily switch (with e.g. `nvm`) then try it, otherwise probably easier to wait for Lens 4.2.2, which should be coming soon.

**Comment by Xaseron** [comment]
@Nokel81 the issue is fixed ❤️ 
Thank you very much and keep on evolving this awesome tool :-)

**Comment by Nokel81** [comment]
You are most welcome!!
