### ISSUE TITLE
Two charts refer to an arbitrary repository

### ISSUE THREAD

**Issue by fzalila** [lensapp/lens#2250]
**Describe the bug**
I have two repositories: a public `public_repo` and a private `private_repo`. In each one, I have a chart named `chart`. 
Before 4.1.13 version, in the Charts table I have
Name  Description Version App Version Repository
`chart`     .................................................`public_repo`
`chart`     .................................................`private_repo`

Since 4.1.13, both charts refer to **only** one repository. So I obtain the following:
`chart`     .................................................`public_repo`
`chart`     .................................................`public_repo `

When  I removed the `public_repo `, I obtained 

`chart`     .................................................`private_repo`
`chart`     .................................................`private_repo `

**Expected behavior**
Name  Description Version App Version Repository
`chart`     .................................................`public_repo`
`chart`     .................................................`private_repo`

**Environment (please complete the following information):**
- Lens Version: 4.1.13
- OS: OSX

**Comment by Nokel81** [comment]
I have managed to reproduce this.
