### ISSUE TITLE
Add Button required for lens cluster pages (like namespace addbutton)

### ISSUE THREAD

**Issue by pmdawood** [lensapp/lens#2251]
**What would you like to be added**:

Today all the cluster pages has edit and remove functionality available but "Add/Create" functionality not available.so we wanted the add/create functionality for all cluster pages.

**Why is this needed**:
we want to add a new node to the cluster to achieve this via lens app we have required node creation functionality.same way this functionality will useful for other pages also.

**Environment you are Lens application on:**
Mac and Linux OS

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]

- Desktop OS: <the OS Lens app runs on in your case>

**Comment by jim-docker** [comment]
This is functionality that we would expect could be added through an extension, since the implementation details would be specific to the k8s distribution, etc.

**Comment by Nokel81** [comment]
As @jim-docker said, Lens won't (definitely in the near future) deal with the adding of nodes due to the divers distributions and their associated requirements.
