### ISSUE TITLE
Overview reports failed Jobs as Successful

### ISSUE THREAD

**Issue by subos2008** [lensapp/lens#226]
In the overview:
![image](https://user-images.githubusercontent.com/1282285/78648579-0fa2df00-78b4-11ea-9929-2a8538d78a23.png)

On the Jobs pane:

![image](https://user-images.githubusercontent.com/1282285/78648630-221d1880-78b4-11ea-9f00-d2ddf7a9cd49.png)

**Expected behavior**
I'm presuming jobs marked with the condition 'failed' should be red on the overview?

- Lens Version: 3.1.0
- OS: OSX 10.14.6

**Comment by nitishvu** [comment]
I am using latest code and its  working fine in mac os.

Jobs pane:
----------

<img width="1353" alt="Screenshot 2020-04-07 at 6 32 07 PM" src="https://user-images.githubusercontent.com/24861433/78672758-b44a0e80-78fe-11ea-9d8a-7afdc7dcbc8a.png">

overview:
<img width="1417" alt="Screenshot 2020-04-07 at 6 31 25 PM" src="https://user-images.githubusercontent.com/24861433/78672782-bca24980-78fe-11ea-80be-f5e899a258e3.png">

Lens Version: Latest code from master branch
OS: MAC OS 0.15.4

**Comment by subos2008** [comment]
It did strike me as an unlikely bug to get missed. 

Perhaps it's an edge case, digital ocean's dashboards were reporting the Job as failed.

I'm happy to provide more info if anyone can think of what might be relevant.

I noticed the (individual) Job pane reports the job as having `Completions: 1`, where the Job index page (list of Job's) says `0/1` in the Completions column.

**Comment by subos2008** [comment]
Or maybe I should update to a build of master and re-test...

**Comment by nitishvu** [comment]
thats how kubernets api is working.

when we try to get jobs:

<img width="750" alt="Screenshot 2020-04-07 at 8 08 30 PM" src="https://user-images.githubusercontent.com/24861433/78682699-f3cb2780-790b-11ea-81e9-b716e1146569.png">

when we describe specifc job its is showing ` Completions:    1`
I know completions means number of pods created.

may be someone here can comment or we should ask this question in kubernets repo.

**Comment by jakolehm** [comment]
@subos2008 does issue still exist?

**Comment by subos2008** [comment]
If you want to auto-close it I can re-open it if I see it again.
