### ISSUE TITLE
Lens won't open on latest MacOS update (BigSur 11.2.2)

### ISSUE THREAD

**Issue by elig-salt** [lensapp/lens#2278]
**Describe the bug**
I open the app, nothing happens. The process seems to be running but no UI present.
I killed Lens and LensHelper, re-opened and same thing.

**To Reproduce**
1. Open Lens on MacOS BigSur 11.2.2
2. The app shouldn't start

**Environment (please complete the following information):**
- Lens Version: 4.1.3
- OS: [e.g. OSX] MacOS BigSur 11.2.2
- Installation method (e.g. snap or AppImage in Linux):

**Comment by tgates-nalej** [comment]
I have the same problem.

**Comment by tgates-nalej** [comment]
Even older version of Lens does not work on MacOS BigSur 11.2.

**Comment by elig-salt** [comment]
Resolved for me in 4.1.4
