### ISSUE TITLE
Port-forward not refreshed after pod is recreated

### ISSUE THREAD

**Issue by sergialonsaco** [lensapp/lens#2282]
**Describe the bug**
When a pod is recreated by a deployment (or similar)and is accessed from a port-forward, it doesn't work as the port is the same one as before the pod was recreated. It should be refreshed with a new port.

**To Reproduce**
1. Instantiate a pod with a port to access
2. Verify portforward works correctly
3. Kill the pod and wait until kubernetes recreates it again
4. Try to access again to the portforward

**Expected behavior**
It should create a portforward with a new port that allows it to access to the new recreated port.

**Environment (please complete the following information):**
Lens: 4.1.4
Electron: 9.4.0
Chrome: 83.0.4103.122
Node: 12.14.1
Os: macos Big Sur

Sorry I couldn't find any logs about this.
Thanks

**Comment by jim-docker** [comment]
related to #2230, we may need a port management UI

**Comment by sergialonsaco** [comment]
hey @jim-docker, any news on this port management UI? Thanks!! 😄

**Comment by jim-docker** [comment]
Hi @sergialonsaco, unfortunately we are busy with Lens 5.0 and port management improvements have not been officially planned yet. Perhaps in a month or two.

**Comment by sergialonsaco** [comment]
hey @jim-docker, I see that Lens5 has been released, and I just wonder if this port management UI has been considered for the near future?

**Comment by jim-docker** [comment]
Hi @sergialonsaco, not yet but supporting port-forwarding or, generally, secure "service exposure" is important to us. We have had some discussion recently about whether kubectl's port-forward functionality is robust enough, given that it is primarily intended for debugging, or should Lens offer something more robust to do an equivalent thing.

**Comment by ryanbrainard** [comment]
This is the workaround I've been using in the meantime to at least kill the port-forwards so Lens can re-create them. A bit of a shotgun approach, but it works.

```sh
ps aux | grep port-forward | awk '{print $2}' | xargs kill
```

**Comment by sergialonsaco** [comment]
hey @jim-docker, any updates on port-forwarding on Lens? Thanks in advance

**Comment by darkpixel** [comment]
Did you mean to close this @sergialonsaco ?
