### ISSUE TITLE
Certificates, Issuers, Cluster Issuers panes under Configuration aren't working

### ISSUE THREAD

**Issue by jeka** [lensapp/lens#229]
There are options under Configuration for Certificates, Issuers, Cluster Issuers.
I wonder what is their purpose since these are not standard k8s resources and have no place in the menu if there is no cert-manager running in the cluster.
Right now, if you click on any of these options an empty busy pane is showing.
But even if there is a cert-manager installed in the cluster the result is the same.

- Lens Version: 3.2.0-rc.2
- OS: Linux
- Installation method: AppImage

**Comment by jeka** [comment]
Actually, glancing at the code problem seems to be that cert-managers API base is hardcoded to ```certmanager.k8s.io/v1alpha1```, but cert-manager changed the API a long time ago to version ```cert-manager.k8s.io/v1alpha2```.

For reference:
https://cert-manager.io/docs/reference/api-docs/

**Comment by nevalla** [comment]
Lens can display CRDs so maybe this section is redundant nowadays?
