### ISSUE TITLE
Error while adding cluster(s): User Exec command "aws" not found on host. Please ensure binary is found in PATH or use absolute path to binary in Kubeconfig

### ISSUE THREAD

**Issue by leandroholanda** [lensapp/lens#2290]
**Describe the bug**
I'm trying to **add a CLUSTER** to my LENS, but I'm having this error, even though I have AWS in PATH, as shown in the images below:
![image](https://user-images.githubusercontent.com/12778603/110185537-629d5300-7df1-11eb-9821-c6383bdf8346.png)

When I try add cluster, I get this error:
"Error while adding cluster(s): User Exec command "aws" not found on host. Please ensure binary is found in PATH or use absolute path to binary in Kubeconfig"
But I checked my PATH and my KUBECTL and is there:
![image](https://user-images.githubusercontent.com/12778603/110185659-b0b25680-7df1-11eb-8516-477dcfbd2da5.png)

**To Reproduce**
1. I Install the program (.exe) fresh install in the standard folrder.
2. Open Lens
3. Click on ADD CLUTER
4. Try to save 

**Expected behavior**
Cluster added

**Screenshots**
![image](https://user-images.githubusercontent.com/12778603/110186243-6205bc00-7df3-11eb-80be-6ff75aebcdd5.png)
AWS is working fine.
Kubectl too.

**Environment (please complete the following information):**
- Lens Version: I tried 4.1.2 , 4.1.3 , 4.1.4.
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): .EXE File.

**Logs:**
I cann't found that logs.

**Kubeconfig:**
![image](https://user-images.githubusercontent.com/12778603/110185746-f2db9800-7df1-11eb-977c-8c20394c2662.png)

**Additional context**
I will tell you, step by step what I DO:
1. I create a config with that command:
![image](https://user-images.githubusercontent.com/12778603/110185827-31715280-7df2-11eb-9c39-599bb4901c75.png)
2. Second I selected:
![image](https://user-images.githubusercontent.com/12778603/110185866-51087b00-7df2-11eb-8fc9-0b7ca393f4a8.png)
3. Then I go to Lens do add CLUSTER and a I get this error: 
![image](https://user-images.githubusercontent.com/12778603/110185919-6e3d4980-7df2-11eb-8193-8755db7c43ed.png)

I tried to use kubectl in terminal do bring to me some information, and is working fine. The problem is in LENS program.
Please someone can help me.
Thanks.

**Comment by darkn3rd** [comment]
There's no way to INJECT values that I can tell with Lens, so there can be these issues:

* it `aws` is bootstraps from `pyenv` environment (or other python version manager), then it will not be able to pick up aws without loading the `pyenv` environment.  Even if the full path is used, the python environment that `aws` needs may not be there.
* if `aws` command to get a token for access to EKS cluster requires a particular `AWS_PROFILE`, such as mycompany-prod, then this will fail.

**Comment by jim-docker** [comment]
Does it work if you use the absolute path to aws in your kubeconfig?

**Comment by leandroholanda** [comment]
> There's no way to INJECT values that I can tell with Lens, so there can be these issues:
> 
> * it `aws` is bootstraps from `pyenv` environment (or other python version manager), then it will not be able to pick up aws without loading the `pyenv` environment.  Even if the full path is used, the python environment that `aws` needs may not be there.
> * if `aws` command to get a token for access to EKS cluster requires a particular `AWS_PROFILE`, such as mycompany-prod, then this will fail.

1- It's not the case, because we're not using `aws` with `pyenv` .
2 - And EKS cluster no requires a particular `AWS_PROFILE` .

**Comment by leandroholanda** [comment]
> Does it work if you use the absolute path to aws in your kubeconfig?

I tried use absolute PATH in kubeconfig too. Not working at all.
And I tried using absolute PATH in `aws` too, did not work.

**Comment by leandroholanda** [comment]
About **Logs:**  I found that In logs, is that an error?? And is related?

![image](https://user-images.githubusercontent.com/12778603/110959042-12138180-832c-11eb-8f87-dc8d18453a50.png)

**Comment by memelet** [comment]
I see this same problem on linux. I have installed aws via brew. 
```
$ echo $PATH
/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:...
```
```
$ which aws 
/home/linuxbrew/.linuxbrew/bin/aws
```

The only way (so far) I could get this to work was to create links in /usr/local/bin.

**Comment by bitisuvanje** [comment]
On Windows, assuming you have a default AWS profile configured, use the absolute path of the aws.exe in your .kube config like:

`command: "C:\\Program Files\\Amazon\\AWSCLIV2\\aws.exe"`

**Comment by leandroholanda** [comment]
> On Windows, assuming you have a default AWS profile configured, use the absolute path of the aws.exe in your .kube config like:
> 
> `command: "C:\\Program Files\\Amazon\\AWSCLIV2\\aws.exe"`

I tried in config file, don't work.

**Comment by sanjaykulkarni04** [comment]
@jim-docker Can you please help me how to resolve this issue?

@leandroholanda Was your issue resolved? If yes how? Can you please assist me?

Thanks,
Sanjay

**Comment by jim-docker** [comment]
@sanjaykulkarni04 have you tried the absolute path workaround suggested above? Meanwhile we'll try to investigate further for 5.0.0

**Comment by sanjaykulkarni04** [comment]
> @sanjaykulkarni04 have you tried the absolute path workaround suggested above? Meanwhile we'll try to investigate further for 5.0.0

@jim-docker Yes, already tried. But no luck

Thanks,
Sanjay

**Comment by sanjaykulkarni04** [comment]
@jim-docker and @team after installing latest updates my issue has been resolved. Thank you so much.

Regards,
Sanjay
