### ISSUE TITLE
Preference to show workspace owner in status bar (and command palette)

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#2294]
**What would you like to be added**:

Option in Preferences to add workspace "owner" prefix. 

Example (if option enabled and workspace is owned by "GKE-Sync"):
![image](https://user-images.githubusercontent.com/1446224/110335373-6f59bb00-802c-11eb-82c6-6b1a567de2c1.png)

**Comment by Nokel81** [comment]
Closing in favour of #2383
