### ISSUE TITLE
Pods Usage Zero on EKS 1.19

### ISSUE THREAD

**Issue by NArnott** [lensapp/lens#2319]
**Describe the bug**
I just upgraded our AWS EKS/K8s to version 1.19, and now the Pods Usage on the Cluster tab reports zero, even though that is not true. I tried uninstalling/reinstalling Lens-Metrics, but it didn't fix anything. All the other metrics appears to be working.

**Expected behavior**
Pods Usage reports the actual number of pods.

**Screenshots**
![image](https://user-images.githubusercontent.com/198647/110817062-2cc0fa00-8249-11eb-9257-0748ee2bdf77.png)

**Environment:**
- Lens Version: 3.6.7
- OS: Windows 10

**Comment by Nokel81** [comment]
Have you tried upgrading to a newer version of Lens? Furthermore, there might be some changes to how we are doing cluster metrics in 4.2 (depending on getting the PR merged) so that might help as well.

**Comment by NArnott** [comment]
Oh wow, I didn't realize I was so far behind. Lens used to update automatically, so yes, I'm pretty behind. Looks like upgrading did the trick.

**Comment by Nokel81** [comment]
There were lots of people asking about halting automatic updates so in `3.6.10` and `4.1.0` we turned them off and made it so that there is a notification asking the user if they want to update.
