### ISSUE TITLE
helm bundling breaks lens 3.2.0-rc2

### ISSUE THREAD

**Issue by DanielSel** [lensapp/lens#232]
**Describe the bug**
Apperently the download and extraction of helm3 seems to break lens under windows. WIth the new release I am unable to open terminals and I get nasty error messages everytime I change a view. Uninstall and clean reinstall did not fix things.

**To Reproduce**
1. Install lens 3.2.0-rc2 under Windows
2. Connect to any cluster
3. Open a Terminal
4. See screenshot

**Expected behavior**
A terminal window to open.

**Screenshots**
![https://user-images.githubusercontent.com/11678387/78876915-5af1f480-7a50-11ea-9782-67db85706203.png](https://user-images.githubusercontent.com/11678387/78876915-5af1f480-7a50-11ea-9782-67db85706203.png)

**Environment (please complete the following information):**
- Lens Version: **3.2.0-rc2**
- OS: **Windows**
- Installation method (e.g. snap or AppImage in Linux): **Installer from Github Release**
 
**Logs:**
```
info: Checking for update
error: Error while initializing undefined
info: Downloading helm.exe 3.1.2 from https://get.helm.sh/helm-v3.1.2-windows-amd64.tar.gz to C:\Users\SEL\AppData\Local\Programs\kontena-lens\resources\helm3.exe\helm3.exe-v3.1.2-windows-amd64.tar.gz
error: connect ETIMEDOUT 152.199.21.175:443 {"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"152.199.21.175","port":443}
warn: watch ended: Error: socket hang up
```

**Additional context**
This is most likely a proxy issue, since Lens apprently does not respect the proxy setting for downloading helm and therefore tries to connect directly, which doesn't work in our corporate environment.

However, this should not break the core functionality of the application (I don't even necessarily need helm support)

**Comment by jakolehm** [comment]
Sounds like a blocker for `3.2.0`. Thanks for reporting this!
