### ISSUE TITLE
Add configurate to use custom kube-state-metrics

### ISSUE THREAD

**Issue by smling** [lensapp/lens#2333]
**What would you like to be added**:
Similar to use custom Prometheus, add configurate to use custom kube-state-metrics to monitor K8S.

**Why is this needed**:
As we use another APM tools to monitor EKS, so service already running, but we cannot use our existing one. It might duplicate if create another for LENS used and increase cost if run in cloud-based platform;

**Environment you are Lens application on:**

- Kubernetes distribution: EKS
- Desktop OS: Windows 10

**Comment by jim-docker** [comment]
Lens doesn't communicate with kube-state-metrics directly (Lens uses prometheus only). You can install a custom prometheus setup using, for example, helm. Or do I misunderstand your use case?

**Comment by smling** [comment]
> Lens doesn't communicate with kube-state-metrics directly (Lens uses prometheus only). You can install a custom prometheus setup using, for example, helm. Or do I misunderstand your use case?

Known that you will create your own `kube-state-metrics` in your namespace. We already have `kube-state-metrics` in another namespace and want to re-use it. So similar to custom prometheus, we would like to use our custom `kube-state-metrics`.

**Comment by Nokel81** [comment]
Related to #1865

**Comment by jakolehm** [comment]
Fixed in #2714
