### ISSUE TITLE
Search queries

### ISSUE THREAD

**Issue by biqas** [lensapp/lens#2338]
**What would you like to be added**:
Search query history and if switching between screens the possibility to preserve the search query.

**Why is this needed**:
Switching between screens during analysis need to preserve the state which was left.

**Environment you are Lens application on:**

- Kubernetes distribution: [AKS, Minikube]
- Desktop OS: Windows 10

**Comment by vshakirova** [comment]
jfi: similar request https://github.com/lensapp/lens/issues/271

**Comment by Nokel81** [comment]
duplicate of #271
