### ISSUE TITLE
Port-Forward Enhancements

### ISSUE THREAD

**Issue by mrseanr** [lensapp/lens#2340]
**What would you like to be added**: 
Better port-forwarding tools.  It's common to open multiple port-forwards to multiple pods. In the current implementation, there is no way to know if a pod has an active forward. Also, if a forward needs to be stopped, the whole Lens App needs restarting. Lastly, not all forwards are HTTP related, opening a browser is convenient for most, however a customize button to allow mapping from host to local and suppress the browser opening would be productive.

**Why is this needed**:
The Lens App has become a daily driver for K8s management, however, regular usage of port forwards to perform tasks is cumbersome. Often reverting to command line to perform multiple port forwards.  Adding a bit of instrumentation to the UI, showing active forwards, enable stopping a forward, and customization of a forward, would be hugely beneficial.

**Environment you are Lens application on:**

- Kubernetes distribution: Common to all 
- Desktop OS: Common to all

**Comment by jim-docker** [comment]
related: #2282, #2230, #542, #541

**Comment by sherifabdlnaby** [comment]
Bump 👍🏻 Our Development teams are using Lens + K9S, where k9S use case is mostly for port-forwarding. Having everything in one tool will be very helpful.
