### ISSUE TITLE
missing graphs

### ISSUE THREAD

**Issue by schmurfy** [lensapp/lens#2341]
I know that my issue is not with lens itself but I don't know where to ask, sorry.

I switched from prometheus to VictoriaMetrics and got back most of the graphs by configuring `kube-state-metrics`, `node-exporter` and querying `kubelet` metrics through the `kubernetes` service but I am still missing a few and I have no idea why, as far as I know I now have all the metrics used by lens available (all the one listed there: https://github.com/lensapp/lens/blob/c4eb9ba39a090fb16da2436608dedd65045b71de/src/main/prometheus/lens.ts)

I am missing the main cluster page graph(s):
![screenshot_691](https://user-images.githubusercontent.com/2983/111301016-fec92480-8651-11eb-8607-bcbd5a9ed6dd.png)

the small version for nodes but when clicking on a node I have the full graphs shown which is weird since I would have thought they were the same datasource:
![screenshot_694](https://user-images.githubusercontent.com/2983/111301221-3afc8500-8652-11eb-8c46-dffe0e8162b7.png)

Any help on what I could be missing would be greatly appreciated.

**Comment by Srokap** [comment]
I have similar issue, but it seems to be intermittent. I'm running microk8s with it's default prometheus operator deployment. I tried pointing to operator service directly to rule out some weird autodiscovery bug. Directly pointing doesn't solve the problem.

![image](https://user-images.githubusercontent.com/1339628/111395444-26090b80-86bd-11eb-947b-a512bbf15be8.png)

Initially I just were missing the metric for requested cpu/memory, but after reboot of the system I am missing current cpu/memory from pie charts. Intrestingly enough, the memory value sometimes shows up and sometimes it's just N/A.

I tried looking at metrics queries in https://github.com/lensapp/lens/blob/master/src/main/prometheus/operator.ts in case I would be missing some data metric, but it doesn't appear to be the case.

![image](https://user-images.githubusercontent.com/1339628/111395718-c9f2b700-86bd-11eb-8964-46c51f73674b.png)

I do seem to be missing `kube_pod_container_resource_limits` metrics from prometheus, but the cpuUsage metric seems to always have data points and I thought the logic was supposed to [just grab last point](https://github.com/lensapp/lens/blob/2e2283bcc947c47e62a15a56c77cbfe88d69c888/src/renderer/components/%2Bcluster/cluster-pie-charts.tsx#L26)?

![image](https://user-images.githubusercontent.com/1339628/111396993-8a799a00-86c0-11eb-9837-9b616b215f97.png)

EDIT:
After running for a while I stopped seeing the issue. Could it be that missing data points in the middle of the series were breaking something?
![image](https://user-images.githubusercontent.com/1339628/111398068-04ab1e00-86c3-11eb-9d53-441dfd986d5d.png)

**Comment by jim-docker** [comment]
Thanks for the reports, I believe we have tried VictoriaMetrics but had limited success. Also, the prometheus operator issues might be dependent on its version(?) We have a few other issues submitted around metrics, and we have more support planned on the roadmap (#1865)

**Comment by Srokap** [comment]
Operator is definitely responsible for missing requests/limits metrics, but it doesn't explain intermittent Usage metrics. My guess would be that something is up with logic for getting last data point when metric is missing points in the middle, but I am not sure how to drill down deep enough with developer console alone.

**Comment by schmurfy** [comment]
provided that all the collectors are the same VictoriaMetrics expose the same api as prometheus so I am a bit puzzled as to why only these graphs are missing.

**Comment by Srokap** [comment]
Generally, my prometheus was missing `kube_pod_container_resource_limits` metric, but instead had only `kube_pod_container_resource_limits_cpu_cores` and `kube_pod_container_resource_limits_memory_bytes`. 

I just upgraded my `kube-state-metrics` exporter from `gcr.io/k8s-staging-kube-state-metrics/kube-state-metrics:v1.9.7` to `gcr.io/k8s-staging-kube-state-metrics/kube-state-metrics:v1.9.8` and I can see requests/limits info on both cluster and individual pods now.

![image](https://user-images.githubusercontent.com/1339628/112149925-cb514180-8bdf-11eb-9408-c8c914f4d0bf.png)

![image](https://user-images.githubusercontent.com/1339628/112149907-c55b6080-8bdf-11eb-8c0e-bfe8fad7f528.png)

**Comment by Nokel81** [comment]
So is this problem resolved now?

**Comment by schmurfy** [comment]
nope, mine is still there, still no clue why those graphs are missing.

**Comment by Nokel81** [comment]
Does anything in #180 help?

**Comment by tkriviradev** [comment]
We have stats for pods, but not for workers.

**Comment by schmurfy** [comment]
Sorry I did not had the chance to check that again sooner due to health issues, I tried again and found https://github.com/lensapp/lens/blob/33c405bdcf86ff755069ce50a21efbf10985810e/troubleshooting/custom-prometheus.md which helped me solve my issue, I was not addind the `kubernete_node` field on metrics from `node-exporter`, now everything shows up :)
