### ISSUE TITLE
"Managed" Clusters can be edited 

### ISSUE THREAD

**Issue by msa0311** [lensapp/lens#2359]
**Describe the bug**
I'd assume that if a cluster is managed (has ownerRef) that its not possible for the user to edit settings. Currently when opening the settings menu from the left hand menu or the cluster overview the settings can be changed.

**To Reproduce**
1. Use an Extension to set a cluster to be "managed" (create cluster through store with ownerRef)
2. Click on Cluster Badge -> Settings
3. Edit
4. See that cluster settings have changed on eg. cluster overvie

**Expected behavior**
All cluster settings should be disabled if cluster is managed by extension

**Comment by jim-docker** [comment]
We need more discussion on extension and user responsibilities/permissions etc

**Comment by jakolehm** [comment]
Should we close this now that Lens has Catalog?

**Comment by Nokel81** [comment]
Yes I think so.
