### ISSUE TITLE
random UI "lockup" in 4.2.0-rc.1

### ISSUE THREAD

**Issue by jim-docker** [lensapp/lens#2368]
Dashboard randomly becomes unresponsive to user input. I was experiencing this on mac for dev builds of https://github.com/lensapp/lens/pull/2355, and possibly master. I eventually experienced it on Windows for released version 4.2.0-rc.1 as seen in the video. The app menus are responsive so it may be a problem with renderer process?

https://user-images.githubusercontent.com/40840436/111848537-a8721500-88e1-11eb-8f03-c014f1d50e15.mov

**Comment by jakolehm** [comment]
@jim-docker is this still valid?

**Comment by jim-docker** [comment]
haven't experienced it in a while, will open a new issue if I see it again
