### ISSUE TITLE
Make generic pages to look consistent

### ISSUE THREAD

**Issue by aleksfront** [lensapp/lens#2371]
Generic pages like **Add cluster**, **Cluster Settings**, **Extensions**, **Preferences** should look same, use equal headings, colors, paddings etc. Also, navigation must be added to settings.

![preferences](https://user-images.githubusercontent.com/9607060/111973173-47c81f80-8b0f-11eb-9d01-6c1036cfdc20.png)
![settings](https://user-images.githubusercontent.com/9607060/111973183-4991e300-8b0f-11eb-93c6-fc451e42e1d2.png)

**Comment by jakolehm** [comment]
@aleksfront I think we can close this?

**Comment by aleksfront** [comment]
No longer relevant for Lens 6.2.4.
