### ISSUE TITLE
Warnings panel on Cluster tab sorts by Age lexically rather than numerically

### ISSUE THREAD

**Issue by mfoo** [lensapp/lens#2382]
**Describe the bug**
In the Cluster overview tab of Lens there is a Warnings panel with an Age column, and the UI allows us to sort by age.

I have a few warnings of ages 16 seconds, 2 minutes, 3 days, and 50 seconds, and sorting them by Age produces

- 16 seconds
- 2 minutes
- 3 days
- 50 seconds

So it seems to be sorting lexically by the text value rather than numerically by timestamp.

**Expected behavior**
In the example above I would expect the order to be:

- 16 seconds
- 50 seconds
- 2 minutes
- 3 days

**Screenshots**
I've split this into two screenshots. I cannot change the height of the warnings panel and I have a bunch of warnings around the 3 days mark, so neither screenshot looks out of place alone. Proof can be seen in the lack of the 55m and 57m entries in one screenshot. The descending option should start with my oldest events (measured in days).

| ![Screenshot from 2021-03-24 10-23-04](https://user-images.githubusercontent.com/194503/112295440-d1046100-8c8b-11eb-9c68-8e9a886aef3b.png) | ![Screenshot from 2021-03-24 10-23-16](https://user-images.githubusercontent.com/194503/112295444-d19cf780-8c8b-11eb-8709-8ec330f216e6.png) |

**Environment (please complete the following information):**
- Lens Version: 4.1.4
- OS: Ubuntu 20.04
- Installation method (e.g. snap or AppImage in Linux): snap

**Comment by jim-docker** [comment]
This should be fixed by #2182, coming in Lens 4.2 (there is a release candidate available: https://github.com/lensapp/lens/releases/tag/v4.2.0-rc.2)

**Comment by mfoo** [comment]
Ah, excellent, thanks! I searched for "sort" and "age" but only in open issues.
