### ISSUE TITLE
Generic Entity Catalog

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#2383]
## Summary

This feature allows Lens to provide a list of all available services from multiple sources (via extensions).

## Motivation

Currently Lens only understands Kubernetes Clusters and those have tight relationship with Workspaces. This has several issues:

- extensions need to sync & persist both clusters and workspaces
- no discovery mechanism, everything needs to be written to disk
- extensions cannot easily introduce new service types (external services: databases, loadbalancers etc.)

### Goals

- an API that allows to register different items to Catalogue. These items should not be persisted, they only live in-memory.
- possibility to map Catalogue item to a menu ("hotbar")
- Simple table view to list all catalogue items and interact with them
- remove Workspace logic

### Non-goals

- Fancy UI (see separate issue/story)
- implement real-world extensions that uses the API

### Terminology

* `Catalog` - flat list of `Entities`
* `Entity` - an item in `Catalog`
* `EntityDefinition` - describes a structure and metadata for `Entity`
* `Hotbar` - a menu where user can attach entities from `Catalog`
* `HotbarItem` - a relation between `Hotbar` and `Entity` instance with optional parameters

We propose a new in-memory observable list called `Catalog` which represents a list of all available entities for a user. 
`Entities` are not persisted which should help with syncing from external sources. Each entity always belongs to `EntityDefinition`. 

#### Local kubeconfigs

I have multiple kubeconfigs/contexts to different clusters (local minikube, GKE, EKS, AKS). I want to easily discover and connect to them. I want to pin frequently used clusters to a hotbar for easy access & switching. I don't want to hunt down kubeconfigs from different folders.

#### External services

In addition to local kubeconfigs I have logged in to a cloud service (called X) and I have an extension installed that supports the same cloud service. I want to see a catalogue with all services available to me: locally configured kubernetes clusters, remote kubernetes clusters from X and any additional services that extension allows me to discover.

### Design Details

Example Catalog interfaces:

```ts
interface Entity {
  apiVersion: string;
  kind: string;
  metadata: {
    name: string;
    description: string;
    source: string;
    labels: {
      [key: string]: string;  
    }
    [key: string]: string | object;
  }
  status: {
    phase: string;
    reason: string;
    message: string;
  }
  [key: string]: any;
}

interface Catalog {
  addEntity: (entity: Entity) => void;
  removeEntity: (entity: Entity) => void;
  getEntities: () => Entity[];
  getEntitiesForDefinition: (def: EntityDefinition) => Entity[];
}

interface EntityDefinitionRegistry {
  addDefinition: (def: EntityDefinition) => void;
  removeDefinition: (def: EntityDefinition) => void;
  getDefinitions: () => EntityDefinition[];
  getDefinitionForEntity(entity: Entity) =>> EntityDefinition;
}

interface EntityDefinition {
  apiVersion: string;
  kind: string;
  metadata: {
    name: string;
    description: string;
    [key: string]: string;
  }
  spec: {
    group: string;
    versions: EntityDefinitionVersion[]
  }
  addEventListener: (event: "run" | "contextMenuOpen", (entity: Entity, params?: any) => Promise<void>) => void;
}

interface EntityDefinitionColumn {
  /* name is a human readable name for the column. */
  name: string;
  /* description is a human readable description of this column. */
  description: string;
  /* priority is an integer defining the relative importance of this column compared to others. Lower numbers are considered higher priority. Columns that may be omitted in limited space scenarios should be given a priority greater than 0. */
  priority: number;
  /* format is an optional OpenAPI type definition for this column. */
  format?: string;
}

interface EntityDefinitionVersion {
  name: string;
  additionalPrinterColumns: EntityDefinitionColumn[];
}

```

Example Hotbar interfaces:

```ts
interface Hotbar {
  apiVersion: "menu.k8slens.dev/v1alpha1";
  kind: "Hotbar"
  metadata: {
    uid: string;
    name: string;
    [key: string]: string;
  }
  spec: {
    items: HotbarItem[];
  }
}

interface HotbarItem {
  apiVersion: "menu.k8slens.dev/v1alpha1";
  kind: "HotbarItem"
  metadata: {
    name: string;
    uid: string;
    references: {
      entity: {
        name: string;
        kind: string;
      }
    };
    params: {
      [key: string] = string;
    }
  }
}
```

## UI Mockup

![image (5)](https://user-images.githubusercontent.com/1446224/112303359-dc17bb00-8ca4-11eb-9636-dd95bd146b67.png)

- Left menu lists `HotbarItems`
- Catalog left menu (categories) lists `EntityDefinitions`
- Table lists entities from selected `EntityDefinition`

**Comment by jim-docker** [comment]
`HotBar` interface could have a `catalogFilter` field that allows creators to limit what their users can see in the catalog (just certain entity types, entities with specific labels, etc.)

Also, although some may find it too long, I'd prefer `CatalogItem` over `Entity`, since it makes the connection clear

**Comment by jakolehm** [comment]
> `HotBar` interface could have a `catalogFilter` field that allows creators to limit what their users can see in the catalog (just certain entity types, entities with specific labels, etc.)
> 

Idea was that a "filter" can be described in `HotbarItem` params. `Hotbar` itself is just a list of user defined items (that point to entities).

> Also, although some may find it too long, I'd prefer `CatalogItem` over `Entity`, since it makes the connection clear

What would `EntityDefinition` be called if `Entity` is `CatalogItem`?

**Comment by jim-docker** [comment]
> > `HotBar` interface could have a `catalogFilter` field that allows creators to limit what their users can see in the catalog (just certain entity types, entities with specific labels, etc.)
> 
> Idea was that a "filter" can be described in `HotbarItem` params. `Hotbar` itself is just a list of user defined items (that point to entities).
> 

I was thinking in addition to that, as a sort of absolute filter (can't make it broader for that HotBar).

> > Also, although some may find it too long, I'd prefer `CatalogItem` over `Entity`, since it makes the connection clear
> 
> What would `EntityDefinition` be called if `Entity` is `CatalogItem`?

`CatalogItemDefinition`  (which is why some might think it is too long)

**Comment by jim-docker** [comment]
Should we have a catalog rule construct that specifies how entities are added? An extension would register a rule (callback) and Lens would apply the registered rules when it is ready for the catalog to be populated (and updated?) Not sure if we need such an intermediary, just asking.

**Comment by Nokel81** [comment]
Closing as the base implementation is present.
