### ISSUE TITLE
Zoom affecting non-selected cluster view

### ISSUE THREAD

**Issue by roobert** [lensapp/lens#239]
**Describe the bug**
When using Zoom in/out with multiple clusters, the view is changed for a cluster that is not currently selected and being observed.

**To Reproduce**
1. Add two clusters
2. Go to the second cluster
3. Zoom In
4. Go to the first cluster
5. Zoom in further
6. Observe that on the currently selected view, the size doesn't change
7. Select the first cluster
8. Notice that the view has changed since last being observed

**Expected behavior**
Zoom In/Zoom Out should affect the currently selected cluster view.

**Environment (please complete the following information):**
- Lens Version:
3.1.0
- OS:
OS X

- Installation method (e.g. snap or AppImage in Linux): 
Downloaded/Installed via website

**Comment by jakolehm** [comment]
Fixed in v3.6.
