### ISSUE TITLE
Chosen namespaces is not remembered when Lens application is closed and restarted

### ISSUE THREAD

**Issue by mih-kopylov** [lensapp/lens#2396]
**Describe the bug**

**To Reproduce**
1. Connect to cluster
2. Open Pods menu item
2. See **"Default"** namespace is chosen in filter
3. Switch to **All Namespaces**
4. Disconnect from cluster (right mouse button on cluster icon)
5. Quit Lens application
6. Start Lens application
7. Connect to the same cluster
8. Open Pods menu item
9. See **"Default"** namespace is chosen in filter

**Expected behavior**
The namespace in filter is remembered between application restarts

**Screenshots**
![image](https://user-images.githubusercontent.com/6898003/112593168-279ea600-8e18-11eb-87a1-e56ffdc4f29a.png)
![image](https://user-images.githubusercontent.com/6898003/112593202-3422fe80-8e18-11eb-9d31-7226c0698ce2.png)

**Environment (please complete the following information):**
- Lens Version: 4.1.4
- OS: Windows 10
- Installation method: Binary installer downloaded from Github

**Comment by jim-docker** [comment]
Thanks for your report. This is coming in Lens 4.2 (https://github.com/lensapp/lens/pull/2279)
