### ISSUE TITLE
how to adjust lens timezone?

### ISSUE THREAD

**Issue by lengxugz** [lensapp/lens#2397]
**What would you like to be added**:
how to adjust lens timezone?
add some settings in cluster configuration about timezone

**Why is this needed**:
k8s log time and the host time default using utc , i changed host timezone ,but change noting in lens.

**Environment you are Lens application on:**

- Kubernetes distribution: [kubernetes 1.20.5]
- Desktop OS: <Windows>

**Comment by jim-docker** [comment]
Are you just referring to the log times? What result do you see with kubectl? Are you asking that Lens change the time reported in the logs/through the kube api/etc?

**Comment by ArthurKnoep** [comment]
In my case it's not only the log times but all time displayed by lens:

Here an example on coredns:

```
$ kc describe pods -n kube-system coredns-788f5b4fc-lctlr 
Name:                 coredns-788f5b4fc-lctlr
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 pool-staging-314o5/10.114.0.8
Start Time:           Tue, 06 Apr 2021 15:14:48 +0200
Labels:               k8s-app=kube-dns
                      pod-template-hash=788f5b4fc
Annotations:          kubectl.kubernetes.io/restartedAt: 2021-04-06T15:14:48+02:00
Status:               Running
....
```
Note that start time is displayed with my correct timezone (+0200, CEST)

And here is what I get using Lens
![Capture d’écran de 2021-04-06 15-19-11](https://user-images.githubusercontent.com/27413532/113717065-86eb9880-96eb-11eb-9eee-ae62e7006ccf.png)
The field `Created` is still right but is written as Zulu time which is quite difficult to read (especially if you live in an area with a large time difference)

Also, interestingly, the annotation `kubectl.kubernetes.io/restartedAt` is still displayed with the correct timezone on Lens
