### ISSUE TITLE
Lens making too many network call even when the UI is closed

### ISSUE THREAD

**Issue by nitinsh99** [lensapp/lens#2399]
**Describe the bug**
We have been seeing huge number of network calls made by lens. I assume it does heavy polling against cluster but the issue is that even when the I close the app, network traffic continues. i.e when app is closed but the lens icon is still visible in mac os system tray at the top

**To Reproduce**
1. Open lens
2. Open activity monitor on mac > network 
3. Notice the network traffic
3. Now close the lens app by clicking on red close button in the lens app ( do not force quite from system tray)
4. Open activity monitor on mac > network 
5. You will notice there is still a lot of network activity.

**Expected behavior**
When the UI is closed the background lens process shouldn't spam cluster

**Screenshots**
Following network activity by lens when ui is not even running
<img width="868" alt="Screen Shot 2021-03-26 at 10 29 45 AM" src="https://user-images.githubusercontent.com/1389212/112646956-646d9b80-8e1e-11eb-8ac8-74129d01a266.png">

**Environment (please complete the following information):**
- Lens Version: 4.1.5
- OS: max os x 10.15.6
- DMG

**Comment by jim-docker** [comment]
I think this is working as intended. If you disconnect all your clusters in Lens before closing the UI window do you still see network activity after closing the UI? If you don't want any network activity you should disconnect your clusters or you can just close the tray...

**Comment by systemmonkey42** [comment]
I just wanted to say I didn't notice the network activity specifically, but the very high cpu usage.

My laptop starts to run hot and rapidly drains the battery if I close the UI but don't exit the tray icon.

I am on version 5.2.4 on Windows, so its clearly a different scenario.  When it happens again I'll create a new issue with screenshots.

**Comment by deB4SH** [comment]
Hi all,
I'm also experiencing the issue explained by @systemmonkey42 - after a while of usage lens generates a lot of background noise that results in a high cpu usage - on my i7-7820HQ up to 25-30% cpu usage...
