### ISSUE TITLE
Use Tauri instead of Electron

### ISSUE THREAD

**Issue by themegaphoenix** [lensapp/lens#2403]
**What would you like to be added**:
I would like Electron to be replaced with Tauri
https://github.com/tauri-apps/tauri

**Why is this needed**:
Electron uses Chrome's V8, which is resource intensive. Tauri is much more lightweight (see the comparison in Tauri GitHub page)
Less resources will mean that it is faster and a more responsive app. Support for Android and IOS is also planned for it

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: <the OS Lens app runs on in your case>
N/A

**Comment by jim-docker** [comment]
Thanks for bringing this to our attention, if we were just starting out it would be considered, we'll keep it in mind for the future.

**Comment by ogarcia** [comment]
@jim-docker Tauri has just released its [version 1.0](https://tauri.app/blog/tauri_1_0). Perhaps now is the time for an in-depth review of this?
