### ISSUE TITLE
Add protocol route to install an extension

### ISSUE THREAD

**Issue by leenamba** [lensapp/lens#2422]
**What would you like to be added**:
Be able to install an extension via the protocol handler.
Example is to combine #1288 and #1707

**Why is this needed**:
This would allow extension developers to simply provide a URL to install their extension.

**Comment by jim-docker** [comment]
fixed by #2394

**Comment by stefcameron** [comment]
@jim-docker What is the URL format to trigger Lens to prompt to install an extension? `lens://main/...`? #2394 doesn't mention, at least not in description or discussions, about `lens://` support. #2394 just sounds like support for pasting an `https://npmjs.com/packages/...` link into the input where you would also put a path to a tarball.

**Comment by jim-docker** [comment]
> @jim-docker What is the URL format to trigger Lens to prompt to install an extension? `lens://main/...`? #2394 doesn't mention, at least not in description or discussions, about `lens://` support. #2394 just sounds like support for pasting an `https://npmjs.com/packages/...` link into the input where you would also put a path to a tarball.

@Nokel81 added support for it in #2394, however it doesn't seem to be merged(?) @Nokel81 ?

**Comment by Nokel81** [comment]
The final will be something like `lens://app/extension/@mirantis/lens-extension-cc?version=2.1.2` with the version not being specified implying latest non-prerelease.

**Comment by stefcameron** [comment]
> The final will be something like `lens://app/extension/@mirantis/lens-extension-cc?version=2.1.2` which the version not being specified implying latest non-prerelease.

OK, cool! Thank you! This is awesome! 😎
