### ISSUE TITLE
disabling search via ctrl-f in macOS

### ISSUE THREAD

**Issue by kyeyeon** [lensapp/lens#2423]
**What would you like to be added**:
remove ctrl-f key for search on macOS

**Why is this needed**:
In macOS, the search function works for both ctrl-f and cmd-f. As a result, when using vim in the terminal, it conflicts with the key to move to the next page.
In the case of Google Chrome, the search function in macOS only works with the cmd-f keys, but the ctrl-f keys do not.

**Environment you are Lens application on:**
macOS Big Sur: 11.2.3
Lens: 4.1.5

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: <the OS Lens app runs on in your case>

**Comment by ches** [comment]
See also #2011
