### ISSUE TITLE
Use custom fonts on editor. 

### ISSUE THREAD

**Issue by esguerrag** [lensapp/lens#2427]
**What would you like to be added**:
The experience with the integrated shell lacks readability when the resources are required to be edited. 

**Why is this needed**:
The ability to change the font allows improving the UX and makes the user more comfortable.

**Environment you are Lens application on:**

- Kubernetes distribution: N/A
- Desktop OS: Ubuntu 20.04

**Comment by helhindi** [comment]
+1 for this. Unable to render Powerline fonts correctly in Lens Terminal

**Comment by RaananHadar** [comment]
+1 Notely, not just the editor, the font in the terminal is also very important and is too small by default for me at least. Having the ability to change it would increase the usability of the terminal

**Comment by Nokel81** [comment]
This has been implemented via #5414 and when we switched to using monaco editor
