### ISSUE TITLE
Node-shell  Stopped working in v4.2.0

### ISSUE THREAD

**Issue by sachincool** [lensapp/lens#2433]
**Describe the bug**
Node-shell Stopped working, 

**To Reproduce**
1. Go to Nodes in any cluster
2. Click on Shell Icon at the top
3. See error

```
W0401 22:41:27.588552   56494 loader.go:223] Config not found: undefined
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Terminal will auto-close in 15 seconds ...
```
FYI, I'm using a remote Cluster
Version: 4.2.0

**Comment by daviddesmet** [comment]
Same is happening to me after updating to 4.2.0

**Comment by dineshbhor** [comment]
Maybe related to this: https://github.com/lensapp/lens/pull/2194
After I set `Terminal Shell Path` to `/bin/zsh`(I use zsh) it started working...
Lens version: `Lens: 4.2.0`
