### ISSUE TITLE
Add Accessible Namespaces notification shown too often

### ISSUE THREAD

**Issue by jim-docker** [lensapp/lens#2436]
Occasionally the "Add Accessible Namespaces" notification appears unexpectedly (no RBAC set, user has namespace get/list permissions). This alone may be acceptable, under some circumstances the namespace query may fail(?) But the notification should not continually pop up after being dismissed. The namespace query should be checked again and the notification redisplayed only if it fails again.

<img width="1440" alt="Screen Shot 2021-04-01 at 7 07 33 PM" src="https://user-images.githubusercontent.com/40840436/113373900-e176a480-9339-11eb-9c22-3922adf02385.png">

Lens 4.2.0, any OS

**Comment by Nokel81** [comment]
It is only displayed when the check fails. I'll add a check to make sure that it fails multiple times before displaying.
