### ISSUE TITLE
Unable to open shell after upgrading to 4.2.0

### ISSUE THREAD

**Issue by kcak11** [lensapp/lens#2445]
**Describe the bug**
After I upgraded LENS 4.2.0, I am unable to open any shell using LENS IDE for my GKE or Baremetal Clusters.
I downgraded to 4.1.5 and it works again.

Getting the below error when trying to open a node shell from the menu:
![image](https://user-images.githubusercontent.com/703559/113546991-ba0a2b00-960a-11eb-8a0a-3c9b34931f25.png)

**To Reproduce**
1. Go to 'Nodes'
2. Click on a particular node
3. Try to open the 'Node shell'
4. See error as in screenshot above.
5. The same problem is noticed for both GKE and Baremetal Clusters. with 4.1.5 it works fine.

**Expected behavior**
Should open the shell for the corresponding node.

**Screenshots**
![image](https://user-images.githubusercontent.com/703559/113547195-0eada600-960b-11eb-8486-b8df26efc126.png)

**Environment (please complete the following information):**
- Lens Version: 4.2.0 (works fine with 4.1.5)
- OS: MacOS Catalina 10.15.7
- Installation method (e.g. snap or AppImage in Linux):

**Comment by sp0cket** [comment]
duplicate https://github.com/lensapp/lens/issues/2433

**Comment by Nokel81** [comment]
Closing in favour of #2433
