### ISSUE TITLE
New "workspace overview" page hides custom icons for cluster selection

### ISSUE THREAD

**Issue by rallydan** [lensapp/lens#2450]
**Describe the bug**
I cannot close the workspace overview when not connected to any cluster, but I can't select the cluster I want because my custom icons cannot be seen on this page.

**To Reproduce**
1. Open lens, workspace overview appears
2. Click on X in top right corner
3. Workspace overview does not close

**Expected behavior**
When I close the workspace overview, I should be returned to my workspace, which shows my custom icons so that I can select the correct cluster to connect to.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 4.2.0
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): Disk image

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by jim-docker** [comment]
You can click on a cluster in the workspace overview to go to the cluster's dashboard. Also, FYI Lens 5.0 will revamp cluster access/overview
