### ISSUE TITLE
Add support to disconnect from cluster using workspace overview

### ISSUE THREAD

**Issue by rallydan** [lensapp/lens#2452]
**What would you like to be added**:
Add support for disconnecting from a cluster using the workspace overview

**Why is this needed**:
The new workspace overview makes it easy to see which clusters you are connected to. In order to disconnect, you have to first click on the cluster, then right click on the icon to select Disconnect. This would be much easier if the ⋮ menu on the workspace overview included Disconnect as an option.

**Environment you are Lens application on:**

- Kubernetes distribution: EKS
- Desktop OS: OSX

**Comment by jim-docker** [comment]
Thanks, this is something we missed, but we will address this as part of our cluster/overview revamping in 5.0
