### ISSUE TITLE
Automatically fold defined manifests paths in editor

### ISSUE THREAD

**Issue by npiganeau** [lensapp/lens#2461]
**What would you like to be added**:

It would be interesting to have a configuration option to automatically fold defined manifests paths in editor.

**Why is this needed**:

Typically `metadata.managedFields` key is :
- present on all manifests, 
- often a very long key that forces to scroll a lot
- useless for most users in most use cases

The idea is that one can define in configuration a list of paths such as `metadata.managedFields` that will be automatically folded when a yaml editor is opened and encounters them. 

**Environment you are Lens application on:**

- Kubernetes distribution: bare metal (microk8s)
- Desktop OS: Ubuntu focal

**Comment by MichaelSp** [comment]
duplicate #2765
