### ISSUE TITLE
Option for theme to match system theme

### ISSUE THREAD

**Issue by cerebrate** [lensapp/lens#2478]
**What would you like to be added**:

An option to allow the Lens theme to match the system theme (on systems where there is such a concept).

**Why is this needed**:

It's a fairly trivial request, but I have my system configured to switch automatically between the light theme (during the day) and dark theme (during the night), which I find more restful for my eyes. (Especially when needing to fix something in the small hours, when a sudden burst of light theme can be... disconcerting, to say the least.) Given that this is automated, it would be most convenient for me if all applications allowing light/dark theming had the option to follow along with these changes to the system theme.

**Environment you are Lens application on:**

- Kubernetes distribution: k3s 1.20.4_+k3s1
- Desktop OS: Windows 10

**Comment by mehmetsefabalik** [comment]
any updates?

**Comment by ryan6416** [comment]
Looking for this as well.

**Comment by inistor** [comment]
Also interested in this
