### ISSUE TITLE
Application crashed

### ISSUE THREAD

**Issue by grvprasadyadav** [lensapp/lens#2482]
![image](https://user-images.githubusercontent.com/46757489/114135221-d8b93c00-9900-11eb-8f2b-78525aa15d2a.png)

Application has been crashed

**Comment by Nokel81** [comment]
What version is this, what OS are you using?

Next time please follow the issue template.

**Comment by riba2101** [comment]
have the same issue:

macOS Big Sur
11.2.3 (20D91)

happend after update to:
Lens: 4.2.3
Electron: 9.4.0
Chrome: 83.0.4103.122
Node: 12.14.1
© 2021, Mirantis, Inc.

**Comment by riba2101** [comment]
fixed it by deleting ` rm /Users/de164039/Library/Application\ Support/Lens/lens-local-storage/f7572392-1156-404f-bd4b-2518933e9d9f.json `

**Comment by Nokel81** [comment]
@grvprasadyadav has this happened again recently? If so, would you mind sharing your `lens-local-storage/*.json` file?

**Comment by Nokel81** [comment]
Fixed by #3361
