### ISSUE TITLE
Update extension API examples

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#2492]
https://github.com/lensapp/lens-extension-samples

**Comment by Nokel81** [comment]
Closing as this has been completed

**Comment by bukowa** [comment]
Extension installed following tutorial https://api-docs.k8slens.dev/v5.3.4/extensions/guides/generator/ results:
![934f53d50f0d0d26e7bce8a044f26f83](https://user-images.githubusercontent.com/38087302/152060646-8a9dbdd2-564d-4763-b438-5b93177229f5.png)

**Comment by Nokel81** [comment]
@bukowa thanks for the notification. That certainly should be fixed.
