### ISSUE TITLE
Enter accessible namespaces when adding a cluster

### ISSUE THREAD

**Issue by servo1x** [lensapp/lens#2528]
**What would you like to be added**: When adding a cluster, users should be able to specify the accessible namespaces they have access to and be able to select the namespace they want as the default.

**Why is this needed**: Users can have limited permissions via RBAC, ie they are not granted list all namespaces and can only access the resources in a specific namespace. It can be very confusing for a user to add a cluster and not see anything under workloads because it defaults to the `default` namespace where they might not have any permissions to it and then they have to add their namespaces after adding the cluster.

**Environment you are Lens application on:**

- Kubernetes distribution: On Prem
- Desktop OS: MacOS

**Comment by ThomasDetemmerman** [comment]
Is this what you are looking for: Right click on your cluster > settings > Accessible Namespaces

**Comment by servo1x** [comment]
Yeah - I am just suggesting, when a user adds a new cluster - they should be able to add accessible namespaces for that cluster at the same time.

**Comment by Nokel81** [comment]
Closing due to 5.0.0 not having a complex C&P menu any more and not having a manual adding of clusters besides that.
