### ISSUE TITLE
Compact view is not working in 5.0.0-alpha.1

### ISSUE THREAD

**Issue by stevejr** [lensapp/lens#2546]
**Describe the bug**
Open up a cluster view in Lens and press the compact view button. The main nav bar doesn't compact but the cluster view shifts over to the left underneath it.

**To Reproduce**
As described above.

**Expected behavior**
Compact view should minimise the main nav bar

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.0.0-alpha.1
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): `make dev`

**Comment by jim-docker** [comment]
Does it work if you stop hovering (move the mouse away)?

**Comment by Nokel81** [comment]
Closing due to this working as intended.
