### ISSUE TITLE
Sort by age is broken for HPA tab

### ISSUE THREAD

**Issue by jdevalk2** [lensapp/lens#2550]
I see there was a problem with sort-by-age that was broken ID #2414

I just upgraded to 4.2.2 which addresses this issue (listed in release notes) and I can report on Windows 10 installation, it looks still broken for HPA.

Most of my tabs sort by age after this fix, but I noticed HPA under Configuration still does not sort on Age column.

Expectation:
Expect sort by age functionality to work the same across all tabs, including Configuration/HPA

**Comment by Nokel81** [comment]
Thanks for the report, @jdevalk2. Funnily enough sorting by age has never worked.
