### ISSUE TITLE
Manual Refresh Option

### ISSUE THREAD

**Issue by kferrone** [lensapp/lens#256]
**What would you like to be added**:
A manual refresh option. Basically a button when clicked forces Lens to manually refresh the data on screen. This would be nice to have just for the satisfaction of knowing for sure the displayed info is up to date. 

**Why is this needed**:
Often times I have to disconnect the cluster and then reconnect to see a change I made. For whatever reason, it is inconsistent when I need to do this. As of writing this I ran a helm release which creates a configmap for a pre-install job. I knew the configmap was created but it was not showing up in the GUI. To get it to show up I had to disconnect and reconnect for it to be displayed. 

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
EKS 1.15

- Desktop OS: 
MacOS Catalina

lens v3.2.0

**Comment by matti** [comment]
not what you are asking for, but are you aware that you can press reload (cmd+r) in mac, win/linux something else

**Comment by arohter** [comment]
cmd+r refresh didn't seem to help when I tried it.  I believe it was ConfigMaps and Secrets.  Only way to get it properly refreshed was a cluster Disconnect/Reconnect.   Probably a bug hiding in there somewhere.  I will repost if/when I see this behavior again.

**Comment by arohter** [comment]
Stale ConfigMaps reproduced today - via a simple helm update - neither the pop-up gui view, nor terminal Edit view showed the most recent resource version:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: device-service
  uid: 82db3157-a329-4c89-94ca-5d9b8ac5717e
  resourceVersion: '60934240'
  creationTimestamp: '2020-04-10T05:14:56Z'
```

vs a `$ kubectl get configmaps device-service -o yaml` cmd:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: device-service
  uid: 82db3157-a329-4c89-94ca-5d9b8ac5717e
  resourceVersion: "62675019"
  creationTimestamp: "2020-04-10T05:14:56Z"
```

Also note that View - Force Reload *did indeed* refresh with the proper newer version displayed.

**Comment by steveww** [comment]
I've also seen stale ConfigMaps. It appears to only happen when the ConfigMap was created/updated via a Helm chart, regular kubectl apply refreshes OK.

**Comment by kferrone** [comment]
@matti I was unaware of `cmd+r`. I'll give it a shot next time I come across the issue. However I have noticed it is only the config maps and secrets when Helm installs them which others have already noted as an issue.

**Comment by kferrone** [comment]
@matti I tried the `cmd+r` option but it totally refreshes Lens and is basically a quicker way to disconnect and reconnect. When I `cmd+r` it takes me back to the main cluster dashboard and removes all my filters and resets any terminals I had open. I still would like a simpler refresh on just the section I am viewing at the moment and not the entire app.
