### ISSUE TITLE
.deb version of Lens 4.2 will not install on Ubuntu via Software Manager

### ISSUE THREAD

**Issue by jjainschigg-r** [lensapp/lens#2572]
**To reproduce**
Download .deb package (4.2 or prior versions) to Ubuntu (18.04 LTS, 20.04 LTS) desktop. Attempt to install using (default method) Software Manager. Installation fails with "unknown file type."

**Expected behavior**
Lens installs.

**Workaround**
Download .deb file and install manually with sudo dpkg -i <filename.deb>

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 4.2
- OS: [e.g. OSX] Ubuntu 18.04 LTS, 20.04 LTS
- Installation method (e.g. snap or AppImage in Linux): Debian package

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
@Nachasic any ideas?

**Comment by jim-docker** [comment]
@jjainschigg-r , it worked for me, on Ubuntu 20.04. I right-clicked on `Lens-4.2.2.amd64.deb`, "Open with other application", then "Software Install".

**Comment by Nokel81** [comment]
Closing as not reproducible. I just tried with v5.2.5 as well
