### ISSUE TITLE
Can't connect to existing prometheus service if prometheus has --web.route-prefix configured

### ISSUE THREAD

**Issue by vestayin** [lensapp/lens#258]
**Describe the bug**
Within my k8s cluster, I have existing prometheus running and that prometheus container has `--web.route-prefix=/prometheus` argument on startup by some reason. That is to say the pod didn't listen to root path of `http://service-ip:port/` but `http://service-ip:port/prometheus`. As the result, Lens app couldn't connect to my existing prometheus to retrieve metrics for k8s cluster.

I compared requests between lens installed prometheus and my prometheus. Below are request to lens installed prometheus service.

<img width="834" alt="image" src="https://user-images.githubusercontent.com/23701239/79410283-80dc4380-7fd2-11ea-9509-45bc3b50759f.png">

While here was my prometheus. There difference between was service url prefix `/prometheus`

<img width="838" alt="image" src="https://user-images.githubusercontent.com/23701239/79410409-e92b2500-7fd2-11ea-840c-4029974749aa.png">

In addition, I've tried to configure that prefix through Lens settings of `Prometheus service address`. But it failed that the text box was restricted only with `namespace/service:port` pattern without any url prefix parameter.

**To Reproduce**
1. Add a cluster with existing prometheus.
2. Click` settings` of cluster and configure `prometheus service address`.
3. Go to cluster again to check `Overview` of cluster.
4. No metrics showed.

**Expected behavior**
Somehow, Lens supports Prometheus service not just expose through url root path `http://service-ip:port/` but with defined url prefix like `http://service-ip:port/prefix/`

**Screenshots**
Configured custom prometheus service

<img width="728" alt="image" src="https://user-images.githubusercontent.com/23701239/79410942-38258a00-7fd4-11ea-93ca-84868e146d0d.png">

Lens overview didn't work after configure.

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/23701239/79410989-55f2ef00-7fd4-11ea-8ee4-c8eccb0d13ac.png">
**Environment (please complete the following information):**
- Lens Version: Version: 3.2.0
- OS: OSX 10.14.6
- Installation method: Download .dmg file from release at <https://github.com/lensapp/lens/releases>
 
**Logs:**
No log file.

**Kubeconfig:**
kubeconfig didn't have problem since I can see all the function besides metrics of customer prometheus.

**Additional context**
NO.

**Comment by webmutation** [comment]
Similar problem... 
monitoring/prometheus-kube-prometheus-prometheus:9090

on Lens 5.1.3 cant find the metrics

**Comment by jun0tpyrc** [comment]
same,`--web.route-prefix="/"` won't work for the state-metrics too
