### ISSUE TITLE
Closing Settings takes more than 20s

### ISSUE THREAD

**Issue by aleksfront** [lensapp/lens#2603]
When page is reloaded inside some of the settings pages (Extensions, Preferences, Cluster Settings etc) user need to wait more than 20s (> 30s in dev build) after hitting ESC key without any meaningful "loading..." messages.

We should speed up this process or at least provide some visible "Loading" component.

Dev build

https://user-images.githubusercontent.com/9607060/115831576-72610d00-a41a-11eb-97d3-8bbff339e73e.mov

Production build

https://user-images.githubusercontent.com/9607060/115832087-1f3b8a00-a41b-11eb-897d-373e2b072bae.mp4

**Comment by Nokel81** [comment]
Maybe fixed by #2591, would you mind checking again @aleksfront ?

**Comment by Nokel81** [comment]
I have checked and it now takes about 4s on a dev build. So I think that the above helped a lot

**Comment by aleksfront** [comment]
Fixed in #2591
