### ISSUE TITLE
Crash on application close

### ISSUE THREAD

**Issue by v1vendi** [lensapp/lens#262]
**Describe the bug**
Client crashes with a Javascript error window (screenshot provided)
![lens-crash](https://user-images.githubusercontent.com/643289/79450867-408abe80-7fee-11ea-8332-8a2dc613daa2.png)
I have multiple k8s clusters configured. If I close the app just after I open it (without selecting cluster) - it closes correctly. If I connect to som clusters, app closes correctly. For other clusters for some reason I get an error

**Expected behavior**
Client closes without error

**Environment (please complete the following information):**
- Lens Version: 3.2.0
- OS: Windows 10 x64
- Installation method: installer
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
C:\Users\i_komsa\AppData\Local\Programs\kontena-lens>
 info: Checking for update
info: Update for version 3.2.0 is not available (latest version: 3.2.0, downgrade is disallowed).
error: proxy eu-central-1.*domain*.com exited with code null
```

**Comment by jtackaberry** [comment]
I also get this even without closing.  It's often (though not reliably) triggerable by changing cluster settings, such as Prometheus service address.

Lens 3.5.0 on Windows 10 x64 1909 Build 18363.900

**Comment by lehno** [comment]
I get this error every time I go to cluster settings

**Comment by Nokel81** [comment]
Is this still happening in 5.4.6?
