### ISSUE TITLE
Provide informations about certificates in secrets

### ISSUE THREAD

**Issue by jkroepke** [lensapp/lens#2632]
**What would you like to be added**:
If there is a certificate inside a secret or config map. show additional values like SAN attributes or expired/notBefore dates.

**Why is this needed**:
Quickly detect if a certificates is expired.

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]: Any, GKE in this case
- Desktop OS: MacOS

Current workaround:

Copy certificate in a file and run `openssl x509 -in tls.crt -text -noout`.

**Comment by jim-docker** [comment]
We feel this is beyond the scope of what Lens should provide, may be good implemented via an extension

**Comment by jkroepke** [comment]
@jim-docker It‘s possible to add a new label like „implement-as-extension“?

Motivated Extension developers could use this to get a list about enhancment like that.

**Comment by jkroepke** [comment]
I figured out, extensions for lens are quite simple.

If any one is interrested into this feature, take a look here https://github.com/jkroepke/lens-extension-certificate-info
