### ISSUE TITLE
helm does not take into the repository from which the chart is installed

### ISSUE THREAD

**Issue by ghost** [lensapp/lens#264]
**Describe the bug**
The 'Releases' page displays a list of installed helm charts, and for each of them a version number is checked. If a newer version is found, an upgrade is offered. The error is that when comparing versions it does not take into account that the chart can be set not from a stable helm repository, but from a third-party one. The best example is cert-manager: the version in stable repo is larger than version in a jetstack's repo but unsupported and abandoned. As a result, Lens offers an upgrade for the cert-manager, while this is not required at all.

**To Reproduce**
1. Have a jetstack/cert-manager installed in your cluster, the latest version is 0.14.2
2. Click on 'Apps/Releases' in the main menu
3. See the cyan bulb with a proposition to upgrade to version v0.6.7
4. That's it

**Expected behavior**
Check the version of the helm chart in the native repo, not only a stable.

**Screenshots**
![image](https://user-images.githubusercontent.com/2364144/79479308-3e882600-8015-11ea-848b-a874a069e1d2.png)

**Environment (please complete the following information):**
- Lens Version: 3.3.0-rc.1
- OS: OSX 10.15.4 (19E287)
- Installation method: from .dmg

**Comment by nevalla** [comment]
I thought we already fixed the chart version comparison in 3.2.0. I tried to reproduce this, but `0.15-alpha` is suggested correctly. After upgrading to `0.15-alpha.0` no upgrades are visible anymore.

Other issue is that helm it self does not store any information of repository and chart from where the release is installed. So it's impossible to know it afterwards.

**Comment by nox-404** [comment]
Tested with 3.5.0, it doesn't show update icon when using jetstack version and trying to upgrade gives a forever pending upgrade tab as shown here

![image](https://user-images.githubusercontent.com/5402193/86341554-bf3ee180-bc56-11ea-86e5-a799586810fa.png)

That leaves no other choices than using the helm cli

(could be great to be able to select the repo upon clicking on the release when multiple are available for it

**Comment by augcampos** [comment]
I try in 4.0.1 and also occur.

**Comment by Nokel81** [comment]
Closing as we have removed the update hover
