### ISSUE TITLE
Dialog about invalid kubeconfig

### ISSUE THREAD

**Issue by unexist** [lensapp/lens#2641]
**What would you like to be added**:

Lens keeps on warning me, that my kubeconfig is invalid, when a local cluster e.g. via minikube is not running. This dialog pops up quite frequently on multiple actions, so the only relief is to remove the cluster config and re-add it once minikube is back running. For some working environments I need a VPN connection, which basically leads to the same problems when I am not connected.

I see the difficulty here to distinguish between this case and real non-working configs, but can this dialog get something like a "Don't remind me again for this cluster" checkbox or is an option feasible to disable this check all-together? 

**Environment you are Lens application on:**

- Kubernetes distribution: Rancher, Minikube, ..
- Desktop OS: macOS 11.2.3 (20D91)

![Screenshot 2021-04-27 at 11 40 21](https://user-images.githubusercontent.com/7075/116223466-d56ede80-a74f-11eb-92bc-a48482b39730.png)

**Comment by Nokel81** [comment]
This will be fixed in 5.0.0

**Comment by Nokel81** [comment]
This was fixed.
