### ISSUE TITLE
Adding a cluster to the hotbar should override "empty" entries

### ISSUE THREAD

**Issue by Nokel81** [lensapp/lens#2650]
**Describe the bug**
Now that the hotbar has "empty" entries by default (see #2638) (though I don't know why they actually exist instead of just being placeholders). If you add a cluster they should override them.

This is what happens if you add a cluster currently:
![Screen Shot 2021-04-27 at 3 52 43 PM](https://user-images.githubusercontent.com/8225332/116304475-9bfa9b00-a770-11eb-973f-1ad2d4f7e795.png)

@aleksfront ?

**Comment by jim-docker** [comment]
fixed by #2691
