### ISSUE TITLE
Unexpectedly breaks out of default namespace since 3.2.0.

### ISSUE THREAD

**Issue by webbertakken** [lensapp/lens#267]
**Describe the bug**
Since version 3.2.0, it looks like Lens is trying to access all namespaces. If you don't have detailed access to resources in other namespaces, you will get non stop scrolling errors saying something like:

persistentvolumeclaims is forbidden: User "arn:aws:iam::########:role/############" cannot list resource "persistentvolumeclaims" in API group "" in the namespace "######-#####"

**To Reproduce**
Steps to reproduce the behaviour:
1. Update to 3.2.0
2. Click on an environment where you have list access but not detailed access to any amount of objects in other namespaces
3. Find that you get an error message for every single object you don't have access to (scrolling through your screen for quite a while).

**Expected behaviour**
- Loads only the objects of the selected namespace.
- Something in the change logs that hints towards - or is related to - this behaviour suddenly being changed.

**Environment (please complete the following information):**
- Lens Version: 2.3.0
- OS: Windows 10

**Kubeconfig:**
Kubeconfig worked perfectly in the last version

**Additional context**
The described behaviour worked perfectly in v3.1.0

**Comment by jakolehm** [comment]
@webbertakken does this happen with v3.3.0?

**Comment by webbertakken** [comment]
Yes. I observe exactly the same behaviour in v3.3.0. Same steps to reproduce.

**Comment by ddvogt** [comment]
The same goes for v3.3.1

**Comment by Nokel81** [comment]
This has been fixed in at least 4.1. We now only list the default namespace (or the first of accessible Namespaces).
