### ISSUE TITLE
Preserve search result when switching tabs 

### ISSUE THREAD

**Issue by goldlil** [lensapp/lens#2674]
**What would you like to be added**:
When switching tabs in lens, eg from deployment to pods I think it would be nice to preserve search entry from previous tab when we returns to it.

**Why is this needed**:
This would make whole experience better and when switching tabs we would not need to reenter last search again.

**Environment you are Lens application on:**
MacOS Catalina, EKS

**Comment by Nokel81** [comment]
Duplicate of https://github.com/lensapp/lens/issues/3510
