### ISSUE TITLE
Download/copy pod logs

### ISSUE THREAD

**Issue by kokizzu** [lensapp/lens#2677]
**What would you like to be added**:
download/copy logs

**Why is this needed**:
highlight specific logs always refreshed after few seconds scrolling, so it's better to have option to download whole pod logs, or at least make the select logs less buggy

**Environment you are Lens application on:**
Linux

- Kubernetes distribution: not sure, it was exists way before i joined the company
- Desktop OS: Ubuntu 20.04 64-bit

btw awesome job making this `kontenta-lens`, i think this the best GUI for kubernetes [i've ever tried](http://kokizzu.blogspot.com/2021/03/kubernetes-gui.html).

**Comment by jakolehm** [comment]
@kokizzu you can already download pod logs, see bottom-right corner of logs "window".

**Comment by jim-docker** [comment]
We'll keep this open to consider a "copy log" functionality

**Comment by jrhizor** [comment]
+1 for copy.

The most intuitive approach to allow copying logs (at least to me) would be to allow clicking in the logs section and then CMD+A / CMD+C to select all and copy. Right now it selects all the text on the screen.

**Comment by Nokel81** [comment]
Fixed by #5970
