### ISSUE TITLE
Empty "reserved" seats in hotbar

### ISSUE THREAD

**Issue by chenhunghan** [lensapp/lens#2685]
**Describe the bug**

Add and remove items back and forth will create "empty seats" in hot bar

**To Reproduce**
1. Add a cluster to hotbar
2. Add a second cluster to hotbar
3. Remove the fist cluster from hotbar
4. Try to add the fist cluster to hotbar again

**Expected behavior**

No empty reserved seats

**Screenshots**

<img width="317" alt="Screen Shot 2021-04-30 at 11 41 36 AM" src="https://user-images.githubusercontent.com/1474479/116700775-d44be480-a9cf-11eb-99b0-c26e2d371e5c.png">

<img width="140" alt="Screen Shot 2021-04-30 at 4 06 11 PM" src="https://user-images.githubusercontent.com/1474479/116700814-dca41f80-a9cf-11eb-943f-3f8b2e5115c4.png">

**Comment by jim-docker** [comment]
Looks like it's fixed or can be worked around on master with drag and drop
