### ISSUE TITLE
All 3 new methods of installing extensions appear broken in 4.2.3

### ISSUE THREAD

**Issue by stefcameron** [lensapp/lens#2688]
https://github.com/lensapp/lens/pull/2435 should have enabled installing extensions in 3 ways:

- `lens://app/extensions/install/@mirantis/lens-extension-cc` from a browser (this was https://github.com/lensapp/lens/issues/2422)

This fails:
![image1](https://user-images.githubusercontent.com/2855350/116764177-e042a100-a9e5-11eb-8b44-87acdec9e8ac.png)

- Paste `https://www.npmjs.com/package/@mirantis/lens-extension-cc` in the "Install extension" box in Lens (this was  https://github.com/lensapp/lens/issues/1708)

This fails:
![image2](https://user-images.githubusercontent.com/2855350/116764183-e8024580-a9e5-11eb-890b-b13b39d7eecb.png)

- Paste `http://registry.npmjs.com/@mirantis/lens-extension-cc` in the "Install extension" box in Lens (this was https://github.com/lensapp/lens/issues/1707)

This fails:
![image3](https://user-images.githubusercontent.com/2855350/116764192-ef295380-a9e5-11eb-91f6-4a225bf7df34.png)

All 3 methods should work now, as of Lens 4.2.2, based on the PR and milestone.

**Comment by Nokel81** [comment]
So the second and third forms were decided against and instead just the `@mirantis/lens-extension-cc` as the required input.

**Comment by stefcameron** [comment]
> So the second and third forms were decided against and instead just the `@mirantis/lens-extension-cc` as the required input.

OK, I wasn't aware. Might want to update #1707 and #1708 then, because they're just marked as "fixed" without explanation.

**Comment by stefcameron** [comment]
I verified this is fixed with today's Lens 4.2.4 release. Thank you!
