### ISSUE TITLE
Blank line in workspace list where current workspace name should be

### ISSUE THREAD

**Issue by Nuru** [lensapp/lens#2690]
**Describe the bug**

My list of workspaces includes a blank line which is not selectable in the middle of the list.

**To Reproduce**

1. Create a few workspaces
2. Select one
3. Click on the workspace name in the lower left of the window, to bring up the "Select workspace" window/overlay/modal
4. Note a blank line in the list and the current workspace missing from the list

**Expected behavior**

List of workspaces should either include the current workspace or not leave room for it. 

**Screenshots**

![image](https://user-images.githubusercontent.com/2793313/116797977-17758880-aaa0-11eb-96d8-d48fab530ea9.png)

**Environment (please complete the following information):**
- Lens Version: 4.2.3
- OS: OS X 10.15.7
- Installation method (e.g. snap or AppImage in Linux): `dmg`

**Comment by jim-docker** [comment]
fixed by #2697
