### ISSUE TITLE
Service's metrics were missing in the nodes from v4.2.3

### ISSUE THREAD

**Issue by eugenesotnikov** [lensapp/lens#2705]
**Describe the bug**
Service's metric were missing in the nodes

**To Reproduce**
1. Go to Nodes
2. Click on any nodes
3. Scroll down to Pods
4. See that pods didn't have metrics

Metrics worked in v4.2.2

**Screenshots**
![image](https://user-images.githubusercontent.com/60689184/117122113-30cb4d00-ad9e-11eb-8db9-9dbfce070162.png)

**Environment (please complete the following information):**
- Lens Version: 4.2.3 4.2.4
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux):

**Additional context**

**Comment by jim-docker** [comment]
duplicate of #2664
