### ISSUE TITLE
Cannot remove local clusters

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#2709]
#2567 did not implement local cluster remove. We should implement context removal from files which should also remove item from catalog (after sync notices it).

**Comment by jim-docker** [comment]
cluster remove is covered in #2663, though the plan seems to be to not allow removal (user would be responsible for removing it from the config manually or through kubectl)? @Nokel81 

Up to now Lens hasn't been modifying a user's files. If we add this we should warn that Lens is about to modify their config file. There may still be issues with this though, e.g. if a config file is automatically generated then clusters may just get added back to the catalog via the sync.

**Comment by Nokel81** [comment]
Yes if we modify user files we **must** warn the user.

I think this is most a way for users to visually cleanup their files.

**Comment by Nokel81** [comment]
fixed by #2923
