### ISSUE TITLE
keep filter when changing view

### ISSUE THREAD

**Issue by matti** [lensapp/lens#271]
- filter pods with "myservice"
- change to "HPA" --> filter is gone

suggestion: keep filter "myservice" when the view is changed

**Comment by moonheart** [comment]
Yes, it's annoying when I troubleshooting something, switching between Deployment/Pods/Service/Ingress and found myself having to type same words over and over again.
I think we can keep filter string for different views separately.

**Comment by jakolehm** [comment]
Now that Lens has tabbed interface this should be possible (tabs keep their state).
