### ISSUE TITLE
Use OpenLens logo for welcome screen

### ISSUE THREAD

**Issue by leenamba** [lensapp/lens#2723]
**Describe the bug**
Should use OpenLens logo for welcome screen

**Environment (please complete the following information):**
- Lens Version: OpenLens: 5.0.0-beta.3.2
- OS: OSX

**Comment by jim-docker** [comment]
Also tray icon

**Comment by msa0311** [comment]
I think this is already implemented.
 //cc please confirm 
@leenamba 

![Bildschirmfoto 2021-05-20 um 08 38 31](https://user-images.githubusercontent.com/26629812/118931072-d3f79700-b946-11eb-91c6-4dbefbc00eb4.png)
