### ISSUE TITLE
no pod info under node 

### ISSUE THREAD

**Issue by linehrr** [lensapp/lens#2729]
**Describe the bug**
After upgrading Lens version, we can no longer see the pods under the node info page. 

**To Reproduce**
go to nodes, and click on a node, in the info page, there is no longer pods info. 

**Expected behavior**
previous version will have pods info under node page. 
![image](https://user-images.githubusercontent.com/1124115/117471479-e4ab1480-af25-11eb-8a0a-94d4658de1e4.png)

**Environment (please complete the following information):**
- Lens Version: 4.2.4
- OS: MacOS
- Installation method: dmg

4.1.x versions are all ok, we noticed that since 4.2.x pods info is removed.

**Comment by jim-docker** [comment]
Do you mean the CPU and Memory info is missing?

**Comment by linehrr** [comment]
@jim no. The list of pods is missing. There used to be a list of pods that are running on that host. You can see the screenshot I posted.  That was the older version. The newer version the whole list of pods is missing.

**Comment by jakolehm** [comment]
@linehrr do you see a list of pods if you first go to Workloads and select "All namespaces" and then go back to node details?

**Comment by linehrr** [comment]
@jakolehm I see, so there is a behaviour change. in the past version, pods are all shown under node list, no matter what namespace is chosen. I think this new behaviour will confuse some people, like me for example. since the namespace selector is under workload, and nodes is on the same level of workload, therefore they should not affect each other.

**Comment by mjseid** [comment]
I agree this was very confusing to me until I read this issue.

Can we get a namespace selector box on the Nodes section like there is in the Workloads section so that it is clear things are being namespaced at this level.  It doesn't make sense to have to switch back to a different section to change this setting.

**Comment by jim-docker** [comment]
I'm pushing for the namespace selector to be globally available on the cluster dashboard. Like `--namespace` is a "global" option for kubectl (even though not everything is namespace-scoped).

**Comment by jakolehm** [comment]
> @jakolehm I see, so there is a behaviour change. in the past version, pods are all shown under node list, no matter what namespace is chosen. I think this new behaviour will confuse some people, like me for example. since the namespace selector is under workload, and nodes is on the same level of workload, therefore they should not affect each other.

It's a bug.
