### ISSUE TITLE
Sorting of Warnings by age not working correctly

### ISSUE THREAD

**Issue by jdato** [lensapp/lens#2741]
**Describe the bug**
Go to warnings in cluster tab and try sorting by age. Sorting apprears to be by String so 80m is "greater than" 100m which is technically wrong.

**To Reproduce**
1. Go to warnings in cluster tab
2. Click on 'Age' to try sorting by age
4. See that results are not sorted correctly

**Expected behavior**
Sorting by age such as:
10m
80m
100m
120m
140m

**Screenshots**
![image](https://user-images.githubusercontent.com/22294144/117659492-4c6a9500-b19c-11eb-8142-27cd5f57449d.png)

**Environment (please complete the following information):**
  Lens: 4.1.4
  Electron: 9.4.0
  Chrome: 83.0.4103.122
  Node: 12.14.1
- OS: Mac OS
- Installation method homebrew

**Comment by jim-docker** [comment]
This has been fixed in Lens 4.2
