### ISSUE TITLE
Protocol handler not working when lens is in "standby"

### ISSUE THREAD

**Issue by msa0311** [lensapp/lens#2746]
**Describe the bug**
Protocol Handler links are not opening lens if the user closed it to "standby". "standby" describes the state when lens was closed but the tray-icon is still displayed.

**To Reproduce**
1. Close Lens so that only tray icon is visible
2. Click on lens://asfdsaf
4. See that lens does not open

**Expected behavior**
Lens opens 

**Environment (please complete the following information):**
- Lens Version: 4.2.x
- OS: Mac OS (maybe further)

**Comment by Nokel81** [comment]
Note: `lens://asfdsaf` or such like are not supposed to work. There still is a bug, because `lens://app` should open the catalog though.

**Comment by msa0311** [comment]
Please change it to always open lens no matter of the url behind lens://
