### ISSUE TITLE
Stuck in Syncing shell environment

### ISSUE THREAD

**Issue by jsecchiero** [lensapp/lens#2764]
**Describe the bug**
No window appears

**To Reproduce**
for view where the app stuck i have used the following command `gnome-terminal -- /bin/bash -c '/snap/bin/kontena-lens'`

**Screenshots**
```
info: 📟 Setting Lens as protocol client for lens://
info: 📟 failed ❗
info: 🚀 Starting Lens from "/home/lop/snap/kontena-lens/179/.config/Lens"
info: 🐚 Syncing shell environment
```

**Environment (please complete the following information):**
- Lens Version: 4.2.2
- OS: Ubuntu 20.04
- Installation method: snap

**Additional context**
if you run CTRL+c the following error appears:
```
^Cerror: shellEnv: TypeError: Cannot read property 'split' of undefined
```
the application proceed and the window appears

**Comment by jim-docker** [comment]
Is there something in your shell startup script(s) that causes Lens to block?

**Comment by jsecchiero** [comment]
That probably is why i have this problem. Lens is the first application that i see that have this issue
