### ISSUE TITLE
collapse managedFields trash by default

### ISSUE THREAD

**Issue by matti** [lensapp/lens#2765]
![2021-05-12 at 20 23](https://user-images.githubusercontent.com/3893/118018031-f2b2c800-b35f-11eb-8d3b-8ecc114d23c1.jpg)

maybe with an option, but also as default behaviour would be okay - nobody needs to see these.

**Comment by jim-docker** [comment]
This may help us implement: https://stackoverflow.com/questions/12823456/programmatically-fold-code-in-ace-editor

**Comment by paulmiu** [comment]
Or maybe as an entry in the settings to specify which fields should be collapsed by default.

**Comment by Nokel81** [comment]
I think we will hold off on this until https://github.com/lensapp/lens/pull/2949 is merged.

**Comment by MichaelSp** [comment]
#2949 is in. This `managedFields` is really getting annoying....

**Comment by Nokel81** [comment]
Doing some preliminary investigation, the following needs to be implemented:

1. Implement a FoldingRangeProvider for the "yaml" language and register it to monaco
2. Using a yaml parsing library that outputs line information (for instance https://eemeli.org/yaml/#lexer seems really good) that is executing in a webworker to get the line numbers for `.metadata.managedFields`

While this would be great to have, I don't think we will have time to implement this for 5.3

**Comment by alan-marcinkowski** [comment]
This is extremely annoying. I'd prefer a fold or remove ... either way ... it's nothing I care to look at and it's just noise.

**Comment by alan-marcinkowski** [comment]
If kubectl client can do this, why not leverage that? Forget the fold, just make it an option to filter it ... folding seems overkill.

**Comment by CallMeLaNN** [comment]
I'm quite surprise to see this issue. Coming to Lens, there are a few differences first the metric doesn't use metric server like k8s Dashboard then the edit doesn't the same with `kubectl edit`. This is not the same DX, took sometime to figure out it is Lens issue.

At first, I thought this is something to do with k8s in general, then > v1.21 already `hide` by default. Then I thought my k8s server config and looking for if there a default to set, nope. Finally I found this issue and realize the problem is only edit on Lens.

I'm not sure how Lens edit get the yaml to be applied but I believe it must be the same with `kubectl edit`. Please decide where to go for this issue.

**Comment by alan-marcinkowski** [comment]
@CallMeLaNN  .. I'm not sure I follow your statement. I use kubectl to edit resources ... and I don't see the field mapping. I do certainly see the field mapping for managedFields when I edit a resource in Lens. Where Len's is picking that up, I assume it's direct from the call to the API server itself. As for kubectl, as of kubectl version 1.18, it actively filters it ... why can't Lens do the same? 

https://stackoverflow.com/questions/62077977/kubectl-get-o-yaml-is-it-possible-to-hide-metadata-managedfields/67056145

**Comment by CallMeLaNN** [comment]
@alan-marcinkowski Yeah, that's what I mean and the same question too. `kubectl edit` can, why not Lens.

I forgot to add about your last comment, I do agree to forget about the fold and just make the experience the same.

**Comment by PehrGit** [comment]
How does this work under the hood? Does Lens call `kubectl get deploy -o yaml`? The reason I ask is that that command has an option `--show-managed-fields` which by default is false and when passed shows exactly the bit that we're asking to hide here. So maybe a checkbox could be added to either use or not use this argument?

Edit: never mind, it looks like the "get" action is a GET http call to the API server without any filtering:
https://github.com/lensapp/lens/blob/2657df2293238f0c99946509d5339a43c2e44f34/packages/core/src/common/k8s-api/kube-api.ts#L486
which calls
https://github.com/lensapp/lens/blob/2657df2293238f0c99946509d5339a43c2e44f34/packages/core/src/common/k8s-api/kube-api.ts#L371

**Comment by zagr0** [comment]
Would be so great to be able to hide managed fields in the editor, either with UI option like checkbox or just to save the state when you already collapsed once

**Comment by nevetS** [comment]
Adding my vote that this issue gets addressed.

**Comment by jakolehm** [comment]
I think we can close this one because the latest version removes `managedFields` trash for the editor. It's not meant for humans.
