### ISSUE TITLE
Broken link in add cluster window

### ISSUE THREAD

**Issue by AugustasV** [lensapp/lens#2769]
**Describe the bug**
In add cluster main windows, where I can add select config file there is text: You can either browse it from the file system or paste it as a text from the clipboard. Read more about adding clusters here.
Link is broken

**To Reproduce**
1. Go to Add cluster section
2. Click on link here ( to read more info about adding cluster)
3. See error

**Expected behavior**
I would expect some information, not broken link. Now it redirects to https://docs.k8slens.dev/v4.2.4/latest/clusters/adding-clusters/

<img width="827" alt="image" src="https://user-images.githubusercontent.com/7377334/118177291-c9af3780-b432-11eb-9a9e-202f35b9827e.png">

**Environment (please complete the following information):**
- Lens Version: 4.2.4
- OS: [e.g. OSX] osx
- Installation method (e.g. snap or AppImage in Linux): brew

**Comment by jim-docker** [comment]
fixed by #2716

**Comment by jim-docker** [comment]
need to revert #2268, will be fixed in v4.2.5

**Comment by AugustasV** [comment]
Great!
