### ISSUE TITLE
Selecting one namespace at a time

### ISSUE THREAD

**Issue by pieterdd** [lensapp/lens#2773]
**What would you like to be added**:
This is about the namespace dropdown menu in this part of the UI:
![image](https://user-images.githubusercontent.com/1407980/118235419-04e25280-b495-11eb-9732-be184c8aa44f.png)

I want to be able to select one namespace at a time, much like you would in a standard dropdown menu. This could be implemented as Alt+Left click for example.

**Why is this needed**:
I'm usually only interested in one namespace at the same time, so I always end up toggling one namespace on and the previous namespace off. This could be more efficient and it actually makes the toggle behavior of the dropdown menu less intuitive than `kubectl`'s behavior of showing one namespace unless you explicitly ask for more.

**Environment you are Lens application on:**

- Kubernetes distribution: Amazon EKS
- Desktop OS: Ubuntu

**Comment by andrei-dascalu** [comment]
Somewhat same situation here. It would be tremendously useful to have both behaviours. I can't say I necessarily use multiple namespaces selected more or less than single namespace, but it's very helpful to have a quick way to switch to a single namespace selection without having to go around and unselect everything else.

**Comment by Nokel81** [comment]
We are thinking of picking between single namespaces as the default and then using "shift clicking" as a way to select multiple namespaces.

**Comment by pieterdd** [comment]
I support Nokel81's suggestion. This seems most in line with other UIs I've used.
