### ISSUE TITLE
Terminal: rendering tab characters as tabs

### ISSUE THREAD

**Issue by rcoup** [lensapp/lens#2798]
**What would you like to be added**:

Tab characters in terminals seem to be rendered as spaces, which shows up when copying from a console pane to the system clipboard.

```
# running this in a lens console
$ python -c 'print("this is 4 spaces:   : and this is a tab:\t:")'
this is 4 spaces:····: and this is a tab:········:

# running this via `kubectl exec` to the same pod
$ python -c 'print("this is 4 spaces:   : and this is a tab:\t:")'
this is 4 spaces:····: and this is a tab:→:
```
(I've substituted `·` & `→` for clarity)

Same thing happens when using the "Terminal" console tab, so I guess it's nothing to do with the Kubernetes interaction.

**Why is this needed**:

In my particular case, copying the TSV output of a script running on a pod into a spreadsheet app loses all the tab characters, so it isn't TSV anymore ☹️ 

**Environment you are Lens application on:**

- Kubernetes distribution: Kops
- Desktop OS: macOS 10.15

**Comment by rcoup** [comment]
Upstream issue (IIUC): https://github.com/xtermjs/xterm.js/issues/734

**Comment by Nokel81** [comment]
Closing as the upstream library issue is closed as "working as designed"
