### ISSUE TITLE
Events: Last Seen column displays First Seen value

### ISSUE THREAD

**Issue by ryantse** [lensapp/lens#2819]
**Describe the bug**
The "Last Seen" column in the Events view on Lens currently displays the first seen value.

**To Reproduce**
1. Go to 'Events'
2. Show the "Last Seen" column
3. See incorrect value in Last Seen column

**Expected behavior**
The column should be the value of Last Seen.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 4.2.4
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): Website

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
N/A
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
N/A
```

**Additional context**
N/A

**Comment by Nokel81** [comment]
Funnily enough it actually displays "age" which, I guess, is close to first seen.

**Comment by ryantse** [comment]
@Nokel81: I see that the change being made is to change the header's naming. However, would it not be more useful to sort by last seen versus age? I think from a usability standpoint, it would be better to sort by how recently the event occurred.

**Comment by Nokel81** [comment]
@ryantse what do you mean by "how recently the event occurred"? Is that not Age? Namely, the older the event, the longer ago it occurred?

**Comment by ryantse** [comment]
@Nokel81: That's necessarily true when an event has repeated. The age represents when the event was first created, but if the message repeats, controllers just increase the count and the last seen time. So, if sorting by age, then that event may be at the bottom of the list but have occurred recently.

**Comment by Nokel81** [comment]
Ah makes sense, I think both columns would be useful. So I'll change the PR
