### ISSUE TITLE
windows containers exec error (sh not found)

### ISSUE THREAD

**Issue by dzmitry-lahoda** [lensapp/lens#2823]
when I try exec into windows container it tries next and fails(there is no sh on this):
```sh
kubectl exec -i -t -n default gs-zlxrz -c gs "--" sh -c "clear; (bash || ash || sh)"
````

but next works well:
```powershell
kubectl exec -i -t -n default gs-zlxrz -c gs "--" cmd
```

not sure how to autoswitch. i see nodes has osType windows, but what if windows node can run Linux containers?

**Comment by Nokel81** [comment]
According to https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/ a windows container MUST be scheduled on a windows node.

**Comment by Nokel81** [comment]
Are you trying to open a pod shell or a node shell?

**Comment by matt-richardson** [comment]
I'm also hitting this; I'm trying to shell into a windows pod.
Looks like over [here](https://github.com/lensapp/lens/blob/e49576ee8c2b8c11182c6faf8052e734b6a3caa3/extensions/pod-menu/src/shell-menu.tsx#L58-L62), it handles the node being windows, but over [here](https://github.com/lensapp/lens/blob/8c5457cf892c7920d0c72566787cbf3db42caa42/src/main/shell-session/node-shell-session.ts#L57), it only supports *nix variants.
