### ISSUE TITLE
Prevent ability to select all texts

### ISSUE THREAD

**Issue by aleksfront** [lensapp/lens#2827]
We should go from website style to more app-like. Cursor must be set to `cursor: pointer` in most places except the details panel (drawer).

![selecting text](https://user-images.githubusercontent.com/9607060/118938906-ceef1380-b957-11eb-8ab5-33856fd3d06a.gif)

Should be like this
![not selecting text](https://user-images.githubusercontent.com/9607060/118939127-0a89dd80-b958-11eb-919c-d4f850d04708.gif)

**Comment by ixrock** [comment]
Why we should disallow users to select & copy text from app views? Isn't it downgrade of UX?

**Comment by jakolehm** [comment]
I think it would make sense to allow text selection from specific parts of the UI.

**Comment by Nokel81** [comment]
I agree that some places it would make sense to not allow text selecting, for instance the text of buttons.

**Comment by aleksfront** [comment]
App contains a lot of textual data which must have ability to be copied, so we should do otherwise issue title says: prevent to select text partially on specific areas, and not everywhere.
