### ISSUE TITLE
Icon for not connected cluster remains in hotbar 

### ISSUE THREAD

**Issue by jim-docker** [lensapp/lens#2837]
For a cluster that can't be reached, when you try to connect to it, it's icon is put in the hotbar (probably shouldn't be?) Right clicking on the icon and selecting Disconnect does not remove it from the hotbar (until you go back to the catalog).

https://user-images.githubusercontent.com/40840436/119031672-58630d80-b979-11eb-8def-47afbf2d6a98.mov

**Comment by Nokel81** [comment]
Closing as we don't auto put into the hotbar anymore
