### ISSUE TITLE
Catalog table cell tooltip

### ISSUE THREAD

**Issue by panuhorsmalahti** [lensapp/lens#2842]
**What would you like to be added**:
Display a tooltip when hovering Catalog (Browser All) table cell values.

**Why is this needed**:
If e.g. the Name is too long and the value is clipped, user can't see the full value, but tooltip could show it.

**Environment you are Lens application on:**

- Kubernetes distribution: EKS
- Desktop OS: macOS
- Lens: 5.0.0-beta.6.20210521.1
- Electron: 9.4.4
- Chrome: 83.0.4103.122
- Node: 12.14.1

**Comment by Nokel81** [comment]
Closing as the sidebar currently wraps the category names.
