### ISSUE TITLE
app crash when editing cronjob api version

### ISSUE THREAD

**Issue by matti** [lensapp/lens#2866]
![2021-05-25 at 11 31](https://user-images.githubusercontent.com/3893/119465927-d09c4b00-bd4c-11eb-93c4-207b928221e3.jpg)

**Comment by vshakirova** [comment]
Hi, @matti. Could you please provide kubernetes and Lens versions?

**Comment by Nokel81** [comment]
Closing as not reproducible in 5.2.5
