### ISSUE TITLE
Remove sidebar compact mode

### ISSUE THREAD

**Issue by aleksfront** [lensapp/lens#2873]
Cluster and Catalog sidebar always will be visible in "expanded" view.

![expanded sidebar](https://user-images.githubusercontent.com/9607060/119621241-8e3b4280-be0e-11eb-8dc8-99e850c1401a.png)
![collapsed sidebar](https://user-images.githubusercontent.com/9607060/119621247-8f6c6f80-be0e-11eb-806e-8d203c42f839.png)

Relates to #2546

**Comment by biswarup1290dass** [comment]
![iy47EPesT5](https://user-images.githubusercontent.com/6507648/119867380-78776b80-bf3b-11eb-98cd-2c001aa1a1b9.gif)

 
Just noticed this on lens IDE Version : 
![image](https://user-images.githubusercontent.com/6507648/119867285-5847ac80-bf3b-11eb-8502-58a742b831db.png)

**Comment by Nokel81** [comment]
@aleksfront Can you explain what you mean? The issue title says that you want to remove it, but the issue description implies that you want to keep it.

**Comment by Nokel81** [comment]
@biswarup1290dass Try moving your mouse, because this is currently working as designed, since if it didn't stay open the element is still considered to be "hovered over" by the browser.
