### ISSUE TITLE
Can you consider adding support for "lrzsz" in the lens

### ISSUE THREAD

**Issue by XWolcen** [lensapp/lens#2881]
Can you consider adding support for "lrzsz" in the lens, so that uploading and downloading files in the container becomes more advantageous, otherwise, it is inconvenient to switch back and forth between xshell Lens, thank you for your hard work!

**Comment by LucaDev** [comment]
Why do you need lrzsz(x/y/zmodem transfer protocol) support in Lens? If I recall correctly zmodem was outdated even before I was born.

If you need to copy files to/from your container why don't you just use kubectl cp? 

Additionally: You can use the inbuilt terminal to use all of your tools just like you would in xshell or any other terminal emulator.

**Comment by XWolcen** [comment]
get it ~ I just found out that you can use the full set of kube* commands directly in the terminal, thanks for your reply！
