### ISSUE TITLE
Infinite spinner on kube-prometheus helm release details page

### ISSUE THREAD

**Issue by jim-docker** [lensapp/lens#2922]
**To Reproduce**
- Install kube-prometheus from bitnami helm repo and go to releases/details for it.

master branch, mac

![Screen Shot 2021-05-31 at 1 15 54 PM](https://user-images.githubusercontent.com/40840436/120235579-5d9d4380-c228-11eb-83fc-2b8618a62281.png)

**Comment by LucaDev** [comment]
This is probably somehow connected to https://github.com/lensapp/lens/issues/2346

**Comment by jim-docker** [comment]
Thanks @LucaDev , I forgot that it too was specific to kube-prometheus, we are looking at it again
