### ISSUE TITLE
Line Wrapping for Logs

### ISSUE THREAD

**Issue by Taragos** [lensapp/lens#2933]
**What would you like to be added**:
The possibility to wrap the lines in the log view. (Or maybe the ability to toggle such a feature)
Lines that are wider than the current display is wide should be wrapped and displayed in the next line, so that there is no need to horizontally scroll.

**Why is this needed**:
Reading wide logs can be quite exhausting in the current view, as you have to scroll to the right, read the logs and then scroll back and try not to lose sight of your current line.

**Environment you are Lens application on:**

- Kubernetes distribution: Baremetal
- Desktop OS: Windows 10

**Comment by jim-docker** [comment]
Duplicate of #1077
