### ISSUE TITLE
View metrics without Prometheus installation

### ISSUE THREAD

**Issue by WLun001** [lensapp/lens#2942]
**What would you like to be added**:
View metrics without Prometheus installtion

**Why is this needed**:

For example, this is the cluster connected with infra.app, without Prometheus installation

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/23547929/120603573-c4b43580-c47e-11eb-9fff-78c590aa8fa7.png">

Where as Lens show blank for all metrics. As Prometheus stack is quite heavy to be installed, it would be great to view metrics without Prometheus stack installation

**Environment you are Lens application on:**

- Kubernetes distribution: GKE
- Desktop OS: MacOS 10.15.7

**Comment by Nokel81** [comment]
I am going to mark this as a duplicate https://github.com/lensapp/lens/issues/1865 since once that lands it should be pretty easy to write an extension.

I can say with a decent amount of confidence that the interface should be pretty generic and not just Prometheus like.
