### ISSUE TITLE
"Shell" command doesn't respect kubectl location

### ISSUE THREAD

**Issue by owiefawefoeiwf** [lensapp/lens#2948]
**Describe the bug**
My kubectl binary is set in preferences with the "Path to kubectl binary" setting.  However, in the Pods screen, when I click "Shell", it opens a terminal window using just `kubectl` (instead of the full path to my kubectl binary).

**To Reproduce**
1. Go to settings, set a value for "Path to kubectl binary"
2. Go to Workloads > Pods. Click the menu next to a pod and click "Shell"
3. The terminal opens with the command `exec kubectl exec ...`. (This fails because `kubectl` cannot be found)

**Expected behavior**
The terminal opens with the command `exec /my/kubectl/path exec ...`

**Environment (please complete the following information):**
- Lens Version:
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): not sure

**Additional context**
Don't fully understand the codebase, but it seems like the menu bar does not attempt to retrieve the kubectl path from the settings: https://github.com/lensapp/lens/blob/master/extensions/pod-menu/src/shell-menu.tsx#L52

**Comment by LucaDev** [comment]
My PR(https://github.com/lensapp/lens/pull/2927) is using the same call to kubectl. It should be fixed there too. I'm currently not at home. I'll have a look at it when I'm back if someone else has not already taken care of it by then.
