### ISSUE TITLE
How does lens use terminal/ssh for worker nodes?

### ISSUE THREAD

**Issue by mhobotpplnet** [lensapp/lens#295]
This is more of a question as I could not find any information on it. How does lens use terminal and ssh into a worker or master node? And how does it even gain root access considering its using just kubeconfig ?

**Comment by matti** [comment]
![magic](https://media.giphy.com/media/12NUbkX6p4xOO4/source.gif)

**Comment by matti** [comment]
spoiler: https://github.com/jpetazzo/nsenter/blob/master/README.md

**Comment by mhobotpplnet** [comment]
> spoiler: https://github.com/jpetazzo/nsenter/blob/master/README.md

Thanks..

I am looking from preventing people installing the lens because they could execute into worker nodes

**Comment by matti** [comment]
That's not the scope of lens or fault of lens - the users can do the same without lens. You need to adjust policies etc of kubernetes.
