### ISSUE TITLE
Won't able to Access Kube config file from WSL2 to my windows k8s lens

### ISSUE THREAD

**Issue by imoisharma** [lensapp/lens#2965]
**Describe the bug**
I am using Windows 10 Pro, where I am running the WSL2 with Ubuntu install. I set up the AWS CLI inside the WSL2. 
Directory location - /hom/myusername/ and my .kube directory also exists in home directory of ubuntu.

I installed the Lens in Windows, but when I am trying to connect by passing the config file or paste it as text it won't work because config exist at /home/myusername (home-directory) and from Lens, I can't above C drive.

Structure WSL follows - /home/username(Home directory for linux)
Windows - /mnt/c/USERS/homedirectory (Home directory for windows)

What should I do to connect with my EKS cluster? And, due to some of the dependencies, I can't install the AWS directly on Windows.

**Comment by nevalla** [comment]
One option is to configure kubeconfig to run aws command inside wsl, ie. `wsl aws ...`, please see more details here:
https://github.com/lensapp/lens/issues/2079#issuecomment-781468958

**Comment by imoisharma** [comment]
Hi @nevalla , I also find very simple solution, if you copy the .aws and .kube folder to the window user directory, then you can connect to your cluster. Thanks, I am happy to close the issue.
