### ISSUE TITLE
ERR_STREAM_WRITE_AFTER_END

### ISSUE THREAD

**Issue by Rushera** [lensapp/lens#2987]
**Describe the bug**
Error window randomly pops up:

ERR_STREAM_WRITE_AFTER_END

**To Reproduce**
1. Go to any page (probably)
2. Wait few minutes

**Expected behavior**
No Error

**Screenshots**

![图片](https://user-images.githubusercontent.com/9796128/121117547-e3ce1100-c84a-11eb-9ff3-dddb4cd70306.png)

**Environment (please complete the following information):**
- Lens Version: 4.2.4
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): scoop install lens

**Comment by Nokel81** [comment]
Closing as not enough information, if this happens again please reopen.
