### ISSUE TITLE
Possibility to open URLs like kube://<k8s-resource> on Lens

### ISSUE THREAD

**Issue by fhperuchi** [lensapp/lens#2999]
**What would you like to be added**:
Support to open k8s resoureces URLs on browsers directly on Lens.
Example: `kube://<HOST>/pod/default/cleanup-operator-7757b8cd5-xxxx?namespace=default`

**Why is this needed**:
To open k8s resoureces URLs on browsers directly on Lens instead of open it on [Kubernetes Dashboard](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/).

**Environment you are Lens application on:**
Intel core i7 10th generation PC with 32GB

```
Kubernetes distribution: k8s installed with kOps version 1.19.9
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Desktop OS: Ubuntu 20.04.2 LTS

**Comment by LucaDev** [comment]
Related to https://github.com/lensapp/lens/issues/2360

**Comment by fhperuchi** [comment]
Related to https://github.com/lensapp/lens/issues/1274
