### ISSUE TITLE
Duplicate 'Unpin from Hotbar' menu items

### ISSUE THREAD

**Issue by aleksfront** [lensapp/lens#3005]
![unping from hotbar](https://user-images.githubusercontent.com/9607060/121332895-f3b82480-c920-11eb-9878-ee36f783c999.png)

**Comment by aleksfront** [comment]
As noticed, same things happens in Catalog menu items.

![same menu items in catalog](https://user-images.githubusercontent.com/9607060/121355333-73052280-c938-11eb-9614-8d5be1d3471f.png)

**Comment by Nokel81** [comment]
This error is currently on master when clicking on a hotbar item.

![Screen Shot 2021-06-10 at 3 29 01 PM](https://user-images.githubusercontent.com/8225332/121585445-972c3680-ca00-11eb-88bf-dcc237071603.png)
