### ISSUE TITLE
Upgrade to a newer version of Ubuntu

### ISSUE THREAD

**Issue by Nokel81** [lensapp/lens#3025]
As per https://github.com/actions/virtual-environments/issues/3287

We should upgrade to a newer version of ubuntu.

**Comment by weyderfs** [comment]
> As per [actions/virtual-environments#3287](https://github.com/actions/virtual-environments/issues/3287)
> 
> We should upgrade to a newer version of ubuntu.

I made the upgrade here using Ubuntu 20.04.2 LTS to _latest_ Lens version on `.deb`, but was necessary to me uninstall the old version.

**Comment by Nokel81** [comment]
@weyderfs This issue is about github actions deprecating and then removing the version of ubuntu we use in CI.

**Comment by weyderfs** [comment]
> @weyderfs This issue is about github actions deprecating and then removing the version of ubuntu we use in CI.

My bad, @Nokel81, I really understood wrong 😞

**Comment by Nokel81** [comment]
fixed by #3799
