### ISSUE TITLE
[Feature Request] Cascade delete the job-pod when user delete the job from console

### ISSUE THREAD

**Issue by wenhui-prudencemed** [lensapp/lens#304]
**What would you like to be added**:
when user delete the jobs, the related pods should be deleted too

**Why is this needed**:
in most cases, user want to delete the related pods when they delete the jobs and it's also default behaivour in cloud service k8s console like AWS, Azure, etc.

**Comment by NArnott** [comment]
I for one would expect the same result as when using kubectl to delete the job, as in all related pods would be deleted.

Same for deleting CronJobs. All related jobs and pods should be deleted. At present, when you delete a CronJob from Lens, the Jobs (and their related Pods) remain indefinitely.

**Comment by Nokel81** [comment]
Fixed by #453
