### ISSUE TITLE
Snap version : does not start with display not found error 

### ISSUE THREAD

**Issue by olivierchatry** [lensapp/lens#305]
**Describe the bug**
Trying to start Snap version of lens ( still named kontena-lens)
I get this error:

(kontena-lens:360549): Gtk-WARNING **: 10:02:56.799: cannot open display: :0
And the software does not start.

**To Reproduce**
On fedora31, using wayland, install snap package, try to launch the software.
 
**Expected behavior**
Software should launch.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: Latest snap ( 3.3.1 )
- OS: Fedora 31
- Installation method (e.g. snap or AppImage in Linux): Snap in linux
 
**Logs:**
```
(kontena-lens:360549): Gtk-WARNING **: 10:02:56.799: cannot open display: :0
```

**Comment by jakolehm** [comment]
Duplicate of https://github.com/lensapp/lens/issues/196

**Comment by sjtoik** [comment]
Use X instead of Wayland.
