### ISSUE TITLE
New Catalog Category "General"

### ISSUE THREAD

**Issue by msa0311** [lensapp/lens#3052]
**What would you like to be added**:
Create a new catalog category called general with 2 entities:
- Catalog 
- Preferences

The first entity (catalog) should be by default on the index 0 of the hotbar.
Remove Catalog symbol from Status Bar.

**Notes from discussions:**
- add general section with catalog / preferences
- catalog should show the last thing you did on catalog preferrable (if not possible now, just show browse)
- catalog item is by default added to the first index
- catalog item is not on the other hotbars
- catalog item should be view-list material icon ui
- preferences should show system preferences on item click
- (category general list should only show description)

**Comment by msa0311** [comment]
Just found this screenshot with the catalog icon on hotbar on our website, I like it! wdyt @aleksfront 
https://k8slens.dev/images/lens-5-screenshot.png

**Comment by aleksfront** [comment]
Looks nice! Will implement it.
