### ISSUE TITLE
Migration of custom Cluster Icons

### ISSUE THREAD

**Issue by msa0311** [lensapp/lens#3057]
When upgrading to 5.0.0 custom cluster icons feature is gone. Right now we dont support custom cluster icons.
**Interims solution:** Display "old" icons, not allow new icons to be configured right now.

**Comment by jakolehm** [comment]
> When upgrading to 5.0.0 custom cluster icons feature is gone. Right now we dont support custom cluster icons.

#3066 added support for custom cluster icons.
