### ISSUE TITLE
Unable to filter by labels

### ISSUE THREAD

**Issue by huang-jy** [lensapp/lens#306]
**Describe the bug**
In the filter, I am unable to fillter using labels.

**To Reproduce**
1. Go to pods
2. In the search string enter a key-value pair that matches a label on one of your pods for example in my base "env-name=dev1" -- note how no results are displayed
3. In the console, use the equivalent kubectl command:

`kubect get pods -n {namespace} -l env-name=dev1`

And you get results

**Expected behavior**
To be able to search by labels, or at least make them clickable on the popup so we can click them to add them to filters easily.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 3.3
- OS: Ubuntu
- Installation method: Snap 
 
**Logs:**
Available if required

**Kubeconfig:**
Available if required

**Additional context**

**Comment by jakolehm** [comment]
@huang-jy This should work (just tested). Could you give more info about the cluster?

**Comment by huang-jy** [comment]
It's a GKE cluster

**Comment by jakolehm** [comment]
@huang-jy I tested with GKE and it works 🤔 . Can you test with the latest Lens version (v3.4.0)?

**Comment by huang-jy** [comment]
That works... sort of.

If I use the string "app=nginx-ingress" it does indeed match all the pods which have that label

However, if I use the string "app=nginx" to match pods which have that label (which are not nginx-ingress pods, but are traditional Nginx servers), it matches those, PLUS the ingress pods.

Is it possible to add two search terms? That would allow me to match two labels and work around the fuzziness.

**Comment by jakolehm** [comment]
> Is it possible to add two search terms? That would allow me to match two labels and work around the fuzziness.

I think that's not yet possible. Please open a separate issue about that.
