### ISSUE TITLE
Label Clusters from Workspaces during migration

### ISSUE THREAD

**Issue by msa0311** [lensapp/lens#3061]
When migrating the clusters from 4.x please add a label "workspace=xyz" to each of them.

- [x] make labels on overview and detail pane clickable
- [x] increase spacer between labels
- [x] highlight labels in white text color when hovering
- [x] make labels on detail pane clickable
- [x] on click add label text to search ("workspace=xyz")
- [x] clicking another label will result in clearing the search and adding the new label
- [ ] add label per workspace to migrated clusters

**Comment by Nokel81** [comment]
Closing because this is the same issue as https://github.com/lensapp/lens/issues/3195
