### ISSUE TITLE
Support Kubectl Global Config

### ISSUE THREAD

**Issue by ppshinebl** [lensapp/lens#3068]
**What would you like to be added**:
Support setting global kubectl option for a cluster.

**Why is this needed**:
I had encounter an issue that when connecting to a cluster, kubectl showed error "specifying a root certificates file with the insecure flag is not allowed" which could be solved by add "--insecure-skip-tls-verify=true" to kubectl command. Since kubectl provides a common option, it would be nice to have the feature supported by lens.

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: Windows

**Comment by Nokel81** [comment]
Can you just remove your CA and add `insecure-skip-tls-verify: true` to your kubeconfig if necessary.
