### ISSUE TITLE
Work space view disappears after deleting a work-space

### ISSUE THREAD

**Issue by Attocode1** [lensapp/lens#307]
**Describe the bug**
Cannot return to default main view workspace after deleting another workspace. Main view disappears. 

**To Reproduce**
[Create a workspace]
1. Click on icon from bottom right on blue bar. 
2. Click on 'Workspaces'
3. Click on Add Workspace
4. Fill out form and create a workspace.
5. Close workspaces to get back to main view
[Delete a workspace]
6. Click on icon from bottom right on blue bar.
7. Click on 'Workspaces'
8. From list of workspaces, delete the recently created workspace from above.
9. Close the workspaces to get back to main view.
10. See that main view is blank,  blue bar at the bottom is now gone.

**Expected behavior**
After workspace configuration is done. Take user back to default view. 

**Screenshots**
![image](https://user-images.githubusercontent.com/3877747/80129319-bab9c680-854b-11ea-8f84-275f5ddbff09.png)

**Environment (please complete the following information):**
- Lens Version: 3.3.1
- OS: Windows 10

 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
PS C:\Users\UserName\AppData\Local\Programs\kontena-lens>
 info: Checking for update
info: Update for version 3.3.1 is not available (latest version: 3.3.1, downgrade is disallowed).

**Comment by burningalchemist** [comment]
The same thing happens when renaming an existing workspace (on MacOS in my case).

**Comment by mbentley** [comment]
I see the same behavior occurring if I add or edit an existing workspace and then close out the UI in Lens 3.5.1 on MacOS Catalina 10.15.6:
![workspace](https://user-images.githubusercontent.com/414445/88682880-31251200-d0c1-11ea-9ace-ecfbf59b1afd.gif)

**Comment by Nokel81** [comment]
This is related to an unsupported version of Lens. Please open a new issue if this continues to happen with the latest (4.1.4) version.
