### ISSUE TITLE
Cannot install/toggle Lens Metrics

### ISSUE THREAD

**Issue by nevalla** [lensapp/lens#3077]
**Describe the bug**
Lens Metrics settings (Lens 5) does not detect connected cluster properly. Despite the cluster is connected, there's error message `Lens Metrics settings requires established connection to the cluster.`

**Screenshots**
![image](https://user-images.githubusercontent.com/455844/122273564-3c0baf80-ceea-11eb-8bcc-62a489292bf5.png)

**Comment by hiromis** [comment]
I am seeing the exact same issue in 5.2.5-latest.20211001.2
![Screen Shot 2021-10-05 at 3 03 25 PM](https://user-images.githubusercontent.com/5401333/136094625-1e425eef-8a72-46ab-bfe7-0a2edba69645.png)

![Screen Shot 2021-10-05 at 3 04 29 PM](https://user-images.githubusercontent.com/5401333/136094748-ff5e4acb-d6f8-4c03-940f-09e52e03f37f.png)

**Comment by fados** [comment]
The same issue happening with version: `5.3.4-latest.20220120.1`
![Screenshot 2022-02-10 at 17 13 05](https://user-images.githubusercontent.com/19396764/153460524-fef82014-780b-4d07-b231-8cf9381cf782.png)
![Screenshot 2022-02-10 at 17 13 14](https://user-images.githubusercontent.com/19396764/153460555-477456cb-f24f-4386-84fa-1ff3bbccced5.png)

**Comment by syncharny** [comment]
Confirmed here as well, the problem exists in version 5.3.4-latest.20220120.1 on ubuntu
