### ISSUE TITLE
Lens on mac os get crash error

### ISSUE THREAD

**Issue by hantmac** [lensapp/lens#309]
**Describe the bug**
![image](https://user-images.githubusercontent.com/7600925/80182385-58d78a80-8639-11ea-8c1c-4d4bd21124b6.png)

**To Reproduce**
After running long time, got the error as flows:
![image](https://user-images.githubusercontent.com/7600925/80182372-51b07c80-8639-11ea-8bc7-cb37dc8d0dcd.png)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7600925/80182395-5d9c3e80-8639-11ea-9d26-3862342fede7.png)

**Environment (please complete the following information):**
- Lens Version: 3.2.0
- OS: [e.g. OSX]  mac os 10.15.4 (19E287)
- Installation method (e.g. snap or AppImage in Linux): 
 mac os dmg file.

**Comment by Nokel81** [comment]
Is this still a problem in 4.1.4?

**Comment by hantmac** [comment]
> Is this still a problem in 4.1.4?

It's ok in 4.14.
