### ISSUE TITLE
OpenShift Route resource is not shown

### ISSUE THREAD

**Issue by raymondchen625** [lensapp/lens#310]
**Describe the bug**
When access a OpenShift 4.3 cluster, the Route resource is not found in the GUI.

**To Reproduce**
Open the Lens GUI

**Expected behavior**
OpenShift Routes should be displayed somewhere in the tree on the left.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 3.3.1
- OS: macOS Catalina

**Comment by Bonehead5338** [comment]
Maybe they are in the CRDs, as showing them in the navigation tree is an Openshift thing not a K8s thing

**Comment by raymondchen625** [comment]
> Maybe they are in the CRDs, as showing them in the navigation tree is an Openshift thing not a K8s thing

Route is not a CRD, hence it doesn't show up in 'kubectl get crd'. It's an API resource. It's not in any of the categories of Lens, such as CRD, Configuration and Network. 
It would be great to have a category for such resources if Lens doesn't want to include an OpenShift-specific object under 'Network', although it's the natural location people would look into.

**Comment by jakolehm** [comment]
Going to close this as it's a bit out of scope. This could be implemented as an extension.
