### ISSUE TITLE
Lens does not respect custom DNS resolvers on MacOS

### ISSUE THREAD

**Issue by JessedeJonge** [lensapp/lens#3101]
**Describe the bug**
On MacOS you can config domain specific dns resolving via `/etc/resolver`. When creating a file in this directory with the name `my.domain.com` and `nameserver 15.15.15.15` for example, MacOS will DNS resolve only to this specific domain via nameserver 15.15.15.15.

**Expected behavior**
I have never had an isue with GUI's or CLI's with this setup before, but Lens seems to not respect this resolving, and will try to resolve targets (kubernetes api endpoint) via a public DNS. Might be hardcoded?

**Comment by jakolehm** [comment]
DNS resolv is actually done via embedded `kubectl`.. which is a statically compiled golang binary. That's probably the reason why it does not pick host DNS config.

**Comment by JessedeJonge** [comment]
Anyway we can fix this? Maybe option to point to our local kubectl binary?

**Comment by itz-Jana** [comment]
I was just about to create an issue for this, but pointing Lens to my local kubectl fixed the issue.

For anyone also facing this issue:

1. Go to the Lens preferences
2. Go to "Kubernetes"
3. Disable "Download kubectl binaries matching the Kubernetes cluster version"
4. Input "Path to Kubectl binary" (For me on M1, installed via homebrew this is `/opt/homebrew/bin/kubectl`. If you don't know where your binary is, run `which kubectl` in a terminal)

Afterwards it started working immediately.
