### ISSUE TITLE
Cluster settings menu looks wrong

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#3103]
Header "Extensions" should be above "Lens Metrics"... now it's above everything.

![image](https://user-images.githubusercontent.com/1446224/122557058-f1527a80-d044-11eb-97f3-aef1d51ac2f2.png)

**Comment by Nokel81** [comment]
I'll take a look

**Comment by jim-docker** [comment]
duplicate of #2847 ?

**Comment by Nokel81** [comment]
yes, I'll mark my PR as fixing both.
