### ISSUE TITLE
exec -it does not work for windows pod

### ISSUE THREAD

**Issue by aaronsssya** [lensapp/lens#311]
**Describe the bug**
At version 3.1, Lens could exec PowerShell of windows pod. However, in the version 3.3.1 Lens try exec ‘shell' for windows pod. I have to ctrl + c and change command to be powershell manually.

**To Reproduce**
1. Go to windows pod
2. Click on shell button
3. See error
```text
container xxxxxxxxxxxxxxxxxxxxxxx encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified.
```

**Expected behavior**
execute powershell command

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 3.3.1
- OS: OSX
- Installation method: auto upgrade from 3.2 -> 3.3

**Comment by jakolehm** [comment]
Most likely fixed in https://github.com/lensapp/lens/pull/293

**Comment by aaronsssya** [comment]
yes. it is working in Version: 3.4.0-beta.1
