### ISSUE TITLE
Do not close the application on command + w

### ISSUE THREAD

**Issue by fsadykov** [lensapp/lens#3121]
Hello There team,

I love what you guys created Lens gives me a much clear environment to work with my Kubernetes clusters. But there is one problem that needs to be fixed. When I use `Command + W` to close the terminal its closing the lens app. I think it should close terminals and if you hold it should close the lens app. This feature will prevent closing the lens app accident 

**What would you like to be added**:  
Please do not close the Lens app if the user uses `Command + W` instead close the terminal 

**Why is this needed**: 
The lens keeps closing when you use `Command + W`

**Environment you are Lens application on:**

- Kubernetes distribution: 
GKE
- Desktop OS: 
MacOs

**Comment by ksalrin** [comment]
Hello!
The same issue comes up on my end as well.  If possible, making this improvement will help stop accidentally closing the program as a whole.  I'm also on a MacOS working with Kubernetes on GKE. 
Thank you!

**Comment by Nokel81** [comment]
This has been fixed if the terminal is currently focused.
