### ISSUE TITLE
Hot bar context menu not opening

### ISSUE THREAD

**Issue by panuhorsmalahti** [lensapp/lens#3126]
How to reproduce:
1. Pin a new icon to the hot bar (can be e.g. web link or Space)
2. Right click on the icon in the hot bar to open the context menu

What should happen:
- Context menu opens

What actually happens:
- Context menu is not opened

Refreshing with CMD+R seems to fix the context menu. The menu works fine for older icons.

**Comment by aleksfront** [comment]
Happens for now when duplicated items appeared in Hotbar.
