### ISSUE TITLE
Catalog Icons have a `:hover` rule.

### ISSUE THREAD

**Issue by Nokel81** [lensapp/lens#3133]
**Describe the bug**
Catalog icons currently have a hover rule, the same as in the hotbar. But they shouldn't.

https://user-images.githubusercontent.com/8225332/122774876-96ed3000-d277-11eb-8af1-7900676b5c72.mov

**Comment by chenhunghan** [comment]
unassigned because I had to do something else, feel free to pick it up.

**Comment by Nokel81** [comment]
I was thinking that maybe we should just leave this and have clicking on the icon do the run action. Wdyt @jakolehm ?
