### ISSUE TITLE
Alert manager is using an old version?

### ISSUE THREAD

**Issue by NadavkOptimalQ** [lensapp/lens#317]
I'm trying to implement slack and email notifications from the alert manager but it doesn't seem to accept any of the values that should be allowed in alert manager.

I edited the config through lens and called the reload endpoint for Prometheus to reload the changes

The errors i'm getting for example are:
`field slack_api_url not found in type config.plain`
`field smtp_smarthost not found in type config.plain`

Is there a way to upgrade the alert manager?
Am I doing something wrong or missing something?

**Comment by kferrone** [comment]
[Bitnami Prometheus-Operator](https://github.com/bitnami/charts/tree/master/bitnami/prometheus-operator) has the latest and greatest everything and it is very easy to install with Helm. `helm repo add bitnami https://charts.bitnami.com/bitnami ` then in charts section of Lens simply search prometheus-operator and click install.

**Comment by NadavkOptimalQ** [comment]
So the metrics option in lens should not be used? I'm confused

**Comment by kferrone** [comment]
I personally don't use Lens installed Prometheus, I'm not part of the lens team though, just a fan. The install prometheus option in Lens installs a very minimalistic version of prometheus which is out of date compared to most distributions of Prometheus. 

On the other hand, the prometheus-operator is basically the defacto standard Prometheus as of late and it works very well. 

Lens Prometheus integration just expects Prometheus to be installed and configured correctly. Then in Lens settings, simply type in the address of Prometheus so Lens knows where to look. 

here are the instructions to configure Prometheus: https://github.com/lensapp/lens/blob/master/troubleshooting/custom-prometheus.md

As long as you configured Prometheus correctly, Lens will start scraping metrics from it and light up like Christmas.

**Comment by jakolehm** [comment]
Closing this because Lens metrics does not include Alert manager. As @kferrone pointed out, you can use prometheus-operator (or any other Prometheus installation). Lens v3.4 even auto-detects these installations (if user has enough rights to list services).
