### ISSUE TITLE
Migrating workspaces to hotbars does not work

### ISSUE THREAD

**Issue by nevalla** [lensapp/lens#3177]
**Describe the bug**
When upgrading from 4.x to 5, current workspaces should be migrated to hotbars. However, it's not working properly at this moment. It looks like migration will create hot bars two times. First hotbars do not contain any clusters.

Also cluster icons are not migrated at all.

**To Reproduce**
1. Install Lens 4.x
2. Add workspaces and clusters
3. Install Lens 5 beta
4. See that workspaces are not migrated to hot bars.

**Comment by aleksfront** [comment]
I would add another feature that is still missing:
After the migration first hotbar cell must be filled with `Catalog` hotbar icon. 
![catalog icon](https://user-images.githubusercontent.com/9607060/123262220-505e3680-d500-11eb-8105-5e8992df3f28.png)
