### ISSUE TITLE
Lens cluster view is crashing with prometheus kube state metric service

### ISSUE THREAD

**Issue by rohitrav33ndran** [lensapp/lens#318]
Lens Cluster view is crashing when configured to target prometheus kube state metrics. 

1. Go to Cluster settings
2. Update the prometheus to already running prometheus kube state metrics service
3. Go back to cluster view

I expect the metric graphic to display with the information from kube state metrics

**Screenshots below**

**Environment (please complete the following information):**
- Lens Version:
- OS: Mac OS X Catalina
- Installation method : From lens site download option.
 
![Screenshot 2020-04-27 at 11 27 58 PM](https://user-images.githubusercontent.com/56229646/80404516-ebe51e80-88de-11ea-8957-74a501f5f9c5.png)

**Comment by nevalla** [comment]
I think the issue here is that when setting non-prometheus service as prometheus service address, application should handle the error properly.
