### ISSUE TITLE
Flatpak support?

### ISSUE THREAD

**Issue by kallisti5** [lensapp/lens#319]
Noticing a strong lack of Lens at Flathub.  Any chance of a Flatpak version?  

**What would you like to be added**:

Flatpak version of Lens

**Why is this needed**:

Pretty much every distribution of Linux except Ubuntu has moved to Flatpak applications. Gnome software dropped Snap support a few months ago.

Picture Lens here:

![kubernetes](https://user-images.githubusercontent.com/100110/80441234-1aa7c880-88d0-11ea-9d6a-028a8cb230c0.png)

Fedora 32 will be out in a few days.

There's a developers guide here:
https://docs.flatpak.org/en/latest/

**Comment by kallisti5** [comment]
I did a little research.. so:

electron-builder doesn't seem to support flatpak?
  * https://github.com/electron-userland/electron-builder/issues/512

While electron-forge does seem to support flatpak:
  * https://github.com/electron-userland/electron-forge

As a non-nodejs developer... that's as far as I'm digging! :-)

**Comment by starkers** [comment]
This is correct, because `electron-builder` doesn't support it (and there has been several issues opened on this topic since [over 4 years ago](https://github.com/electron-userland/electron-builder/issues?q=flatpak) ).

The reason? who knows.. there isn't an actual reason to not support it from what I can tell..

We can in fact package an AppImage's into flatpak

1. extract the AppImage eg: https://github.com/starkers/joplin-flatpak/blob/master/build.sh#L11-L13
2. drop the contents into flatpak (see above repo)

The only caveat is that sometimes we need to run it the application [without the sandbox](https://github.com/starkers/joplin-flatpak/blob/master/run.sh)

Its a little bit of a hack I suppose but it works. I will attempt to PR support for this via the `npm run` + Makefile + azure pipelines on this project as soon as I'm able :crossed_fingers:

**Comment by w0k3** [comment]
Any news about this, please?

**Comment by SISheogorath** [comment]
I just put something together tonight: https://git.shivering-isles.com/sheogorath/lens-flatpak

It's a first draft and currently starts with an error but is basically functional. ~~Next step is to submit it to Flathub~~

**Update:** *As I decided not to set up a K8s cluster today or tomorrow for daily use, I'll not maintain a flatpak for lens. However, the project is still there for anyone who wants to take over.*

**Comment by kallisti5** [comment]
:fireworks: electron-builder now natively supports flatpak...
https://github.com/electron-userland/electron-builder/issues/512

**Comment by jakolehm** [comment]
Recent electron-builder versions with flatpak support require >= node14. Which means that we need Electron 12 update first (#3572)

**Comment by Nokel81** [comment]
Update: I have gotten it to build and run, however I am still missing:

1. The application icon doesn't work
2. The tray icon doesn't work
3. verify that kube sync works as expected.

**Comment by IDerr** [comment]
Thanks @Nokel81, do you have a working build for flatpak, I'm really interested if yes :)

Thanks a lot for your work ! 
PS : Happy new year in advance !

**Comment by mbana** [comment]
> Thanks @Nokel81, do you have a working build for flatpak, I'm really interested if yes :)
> 
> Thanks a lot for your work ! PS : Happy new year in advance !

Hi, can you share the Flatpak link even if it's not fully functional.

**Comment by Nokel81** [comment]
@mbana I cannot as there is no link this was just trying to create a flatpak locally, I have not be able to work on this recently.

**Comment by mbana** [comment]
> @mbana I cannot as there is no link this was just trying to create a flatpak locally, I have not be able to work on this recently.

OK. How did you create the Flatpak locally? It would be nice if you share the set of commands you ran.

**Comment by tstoeckler** [comment]
I put together a (somewhat) working version of a Lens flatpak over here: https://github.com/lensapp/lens/pull/6957
Would appreciate any kind of feedback! :crossed_fingers:

**Comment by proletarius101** [comment]
FYI I'm also trying to submit it to flathub: https://github.com/flathub/flathub/pull/3811

**Comment by tstoeckler** [comment]
Ahh nice, I missed that :+1:
If I'm seeing that correctly, that one "re-packages" the existing snap for Lens, right? So I guess this does not really duplicate that work, as I assume a "native" build would be preferable in the end? I.e. if that gets accepted we could eventually just switch that over to this one?

**Comment by proletarius101** [comment]
@tstoeckler Yes. If possible, we need to make generated-resources.json updated everytime yarn.lock updates. Everything else is easy to implement.

**Comment by harmathy** [comment]
I also [tried to put a flatpak together](https://github.com/harmathy/openlens-flatpak) using the debian package provided by https://github.com/MuhammedKalkan/OpenLens

**Comment by tstoeckler** [comment]
I guess this can be closed now: https://flathub.org/apps/details/dev.k8slens.OpenLens

Really awesome work @proletarius101, thanks a lot!

**Comment by mbana** [comment]
> I guess this can be closed now: https://flathub.org/apps/details/dev.k8slens.OpenLens
> 
> Really awesome work @proletarius101, thanks a lot!

I second that. Awesome work!

The `README.md` just needs updating so people know a Flatpak version exists now.

**Comment by marcinjahn** [comment]
It would be awesome if lensapp would take ownership of the flathub release. Currently, https://flathub.org/apps/dev.k8slens.OpenLens screams "Unverified".

**Comment by kallisti5** [comment]
under the new closed-source model of lens, no longer have any interest in it.

**Comment by kallisti5** [comment]
also, for any lurkers, here are some awesome open source alternatives to the now-closed source lens:

[k9s](https://archlinux.org/packages/extra/x86_64/k9s/), [kdash](https://aur.archlinux.org/packages/kdash), [Headlamp](https://aur.archlinux.org/packages/headlamp-bin) or [Seabird](https://aur.archlinux.org/packages/seabird).
