### ISSUE TITLE
Lens kubectl issue

### ISSUE THREAD

**Issue by adamtheis** [lensapp/lens#3192]
~/.config/Lens/binaries/kubectl/1.21.1+k3s1/kubectl: line 1: `<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: kubernetes-release/release/v1.21.1+k3s1/bin/linux/amd64/kubectl</Details></Error>'

The binary or linker thingy is broken
.config/Lens/binaries/kubectl/1.21.1+k3s1/kubectl: XML 1.0 document, ASCII text, with no line terminators  

older versions (19) they still work..  but not my new cluster

**Comment by Nokel81** [comment]
You can configure a specific kubectl to use in your clusters settings.

**Comment by adamtheis** [comment]
Fixed!
by upgrading lens from version 3.5 to 5. 

sry version 4 I never knew you at all.

**Comment by Nokel81** [comment]
Okay wow I didn't know that you were on 3.5

**Comment by adamtheis** [comment]
or upgrade to version 5 - that fixed it.

**Comment by adamtheis** [comment]
ack, stupid phone.. just ignore that
