### ISSUE TITLE
Cluster Settings are not migrated from 4.x to 5.x

### ISSUE THREAD

**Issue by aleksfront** [lensapp/lens#3195]
It seems all Cluster Settings are not migrated from 4.x to 5.x

This is a list of settings I tested that have not been migrated:
- Cluster Icons
- Hide metrics from UI
- HTTP Proxy
- Cluster Name
- ... probably all other settings...

**Comment by msa0311** [comment]
It seems accessible namespace settings is not migrated properly as well. Maybe further settings affected.
