### ISSUE TITLE
Allow Mouse Middle click to close tabs

### ISSUE THREAD

**Issue by DanielHabenicht** [lensapp/lens#3202]
**What would you like to be added**:

Make the tabs closeable via the middle mouse button (also named wheel-click). 

![image](https://user-images.githubusercontent.com/13590797/123665493-a13f9900-d838-11eb-80a5-43dc6c759575.png)

**Why is this needed**:
It is a default behavior in most IDEs

**Environment you are Lens application on:**

Lens Version: 4.2.4
OS: Win10x64

**Comment by DanielHabenicht** [comment]
I am also happy to implement if its deemed useful enough :)

**Comment by Nokel81** [comment]
Implementation PRs are always welcome!

**Comment by DanielHabenicht** [comment]
Just updated to version 5. Seems like its already working there.
