### ISSUE TITLE
helm Issues with names and repos

### ISSUE THREAD

**Issue by kferrone** [lensapp/lens#321]
**Describe the bug**

Issue 1: When more than one Helm repo has the same chart, Lens will say the chart has an upgrade and mention to upgrade to the later version from the other repo. 

Issue 2: When a chart name has a dot in it, everything after the dot is dropped in the name. 

**To Reproduce**
Issue 1: Easy to see the issue when using the prometheus-operator chart from Bitnami
 1. install bitnami/prometheus-operator which is verison `0.15.2`
 2. Lens suggests upgrading to version `8.13.2` which is the latest prometheus-operator chart version from the stable repo. 
 3. Try upgrading, I dare you

Issue 2: The only chart I know of which has a dot in the name is the k8s service catalog
 1. add this repo: `"https://svc-catalog-charts.storage.googleapis.com"`
 2. Install the chart and view the release in the release section of lens
 3. Observe the name is `catalog-0.3.0` instead of `catalog-0.3.0.beta.2`
 4. Attempt to make a change to the values and you get an error about missing path to chart 

**Expected behavior**
Issue 1: Suggests updates to versions from the correct repo, not just the highest number from all repos.

Issue 2: Don't truncate the `.beta.2` part in the name

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 3.3.1
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): Web Download of DMG

**Comment by nevalla** [comment]
About the issue 1. It's a bummer that Helm does not store the information about the repository where the release is created from. Maybe Lens could store this somewhere and use that when checking the upgrades.

**Comment by jakolehm** [comment]
Issue 1. is something that Lens cannot really change (or fix). @kferrone could you open a separate issue about 2.?

**Comment by kferrone** [comment]
@jakolehm done and done: https://github.com/lensapp/lens/issues/363
