### ISSUE TITLE
Sentry Integration

### ISSUE THREAD

**Issue by msa0311** [lensapp/lens#3215]
Add Sentry Integration, activated by default, configureable in settings next to telemetry. (similar behaviour)

--> Change Page name: "Reporting & Surveys"

![image](https://user-images.githubusercontent.com/26629812/123922529-69e00200-d988-11eb-9a4c-2e2aba46c44c.png)

**Comment by chenhunghan** [comment]
Todo:

Capture exceptions

- [ ] Add Sentry to source code
  - [x] For renderer, uses https://github.com/getsentry/sentry-javascript/tree/master/packages/react
  - [x] For main, use https://github.com/getsentry/sentry-javascript/tree/master/packages/node
  - [x] Capture Electron native exception using https://github.com/getsentry/sentry-electron
  - [ ] *(Optional)* Enable Profiler https://docs.sentry.io/platforms/javascript/guides/react/components/profiler/

Add context to exceptions
 
- [ ] Add typescript source map support https://docs.sentry.io/platforms/node/typescript/ to tsconfig
- [ ] CI Sentry Integrations
  - [ ] Create Sentry releases in CI by git hash on master, and upload sourcemap
  - [ ] Create Sentry releases in CI by version number in azure pipeline and upload sourcemap

Other
- [x] Set enable Sentry flag in Preferences `Reporting & Surveys` tab
- [ ] Move Sentry error tracking into extension

**Comment by Nokel81** [comment]
@chenhunghan I am going to close this issue as we have the beginnings of integration already in 5.1.0. All subsequent items should be made into bugs for 5.1.1 or enhancements for 5.2.0
