### ISSUE TITLE
Predictable Release binaries/packages

### ISSUE THREAD

**Issue by batistein** [lensapp/lens#3217]
Currently no binaries or packages are attached to a release on github. Downloading Lens is only possible via the website. Unfortunately, the timestamp is included in the name of each package, so it is currently not possible to automate the download via a script to always have the latest version.

**Comment by nevalla** [comment]
You can use our binaries API for this:

```
https://api.k8slens.dev/binaries/latest.dmg // Mac OS
https://api.k8slens.dev/binaries/latest.exe // Windows
https://api.k8slens.dev/binaries/latest.x86_64.AppImage // Linux
```

**Comment by batistein** [comment]
@nevalla thank you. And how can i specify a specific version? I tried to replace latest with v5.0.0 for example but had no luck.
