### ISSUE TITLE
something went wrong with the icons

### ISSUE THREAD

**Issue by OSRebooting** [lensapp/lens#322]
What happened to my Lens, something went wrong with the icons
![image](https://user-images.githubusercontent.com/37145561/80557331-20ed9000-8a09-11ea-8adf-d8de4fca599f.png)
Environment (please complete the following information):

Lens Version: 3.3.1
OS: ubuntu 18.04
Installation method (e.g. snap or AppImage in Linux): Web Download AppImage

**Comment by jakolehm** [comment]
Does this still happen with 3.4.0?

**Comment by nevalla** [comment]
If this is still the issue, please re-open
