### ISSUE TITLE
Unable to connect to any cluster

### ISSUE THREAD

**Issue by Josh-HouseME** [lensapp/lens#323]
After opening Lens I attempt to connect to a cluster and am met with an error
![image](https://user-images.githubusercontent.com/62244491/80573706-c18b8200-8a00-11ea-95aa-6b55a35becee.png)

I was able to connect without issue until recently (24 April)

**Environment (please complete the following information):**
- Lens Version: 3.3.1
- OS: Windows 10 Pro 64 bit
- Installation method (e.g. snap or AppImage in Linux): .exe
 
**Logs:**
``` info: Checking for update
info: Update for version 3.3.1 is not available (latest version: 3.3.1, downgrade is disallowed).
error: proxy aws exited with code 3221225477
error: Failed to connect to cluster aws: {"name":"RequestError","message":"Error: ESOCKETTIMEDOUT","cause":{"code":"ESOCKETTIMEDOUT","connect":false},"error":{"code":"ESOCKETTIMEDOUT","connect":false},"options":{"json":true,"timeout":10000,"headers":{"host":"48f07770-379c-4ee7-a8e2-81cc7e81ea29.localhost:49152"},"uri":"http://127.0.0.1:49152/api-kube/version","simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}
(node:20992) UnhandledPromiseRejectionWarning: Error: timeout
    at Timeout.timeoutFunc (C:\Users\Work\AppData\Local\Programs\kontena-lens\resources\app.asar\node_modules\tcp-port-used\index.js:204:25)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:20992) UnhandledPromiseRejectionWarning: Error: timeout
    at Timeout.timeoutFunc (C:\Users\Work\AppData\Local\Programs\kontena-lens\resources\app.asar\node_modules\tcp-port-used\index.js:204:25)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:20992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:20992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Kubeconfig:**
My colleagues are not experiencing the same issue and they have the same config.

**Additional context**
I am able to delete pods and the like via command prompt

**Comment by jakolehm** [comment]
@Josh-HouseME is it possible that windows firewall (or similar) blocks the connection?

**Comment by Josh-HouseME** [comment]
@jakolehm I have now attempted again with windows virus and threat protection disabled as well as firewall disabled (and no other antiviruses or the like active)
Still experiencing the same issue

**Comment by jakolehm** [comment]
@Josh-HouseME does this still happen?

**Comment by Josh-HouseME** [comment]
Hi

This does still happen
[cid:bc511fb1-0f2e-4665-831f-808a36f57ac8]

I have been using command line.


Kind Regards,

Josh

[https://support.house.me/support/ImageDisplay?downloadType=uploadedFile&fileName=1540895644403.png&blockId=bc235480bcc800373244af58d0b4d2461faa1b8030da4e5c&zgId=c1e0b4525abb81150b498ee34174141d&mode=view]

HouseME Rentals

W:   www.Hou​se.ME<http://www.house.me/>

E:    ask@​house.me<mailto:ask@house.me>

Check out our most recent feature on Enterprise Africa<https://enterprise-africa.net/houseme-the-new-way-to-rent-lease-in-sa/>


________________________________

**Comment by simake2017** [comment]
I M1 have the same problem

**Comment by simake2017** [comment]
![image](https://user-images.githubusercontent.com/31234273/146766703-a3fdb1c7-b7ad-455b-8c97-de49b8d94b31.png)

I use the  latest version

**Comment by simake2017** [comment]
![image](https://user-images.githubusercontent.com/31234273/146768841-252f3600-ba1f-46aa-9c83-b1287c8f29a5.png)

**Comment by simake2017** [comment]
![image](https://user-images.githubusercontent.com/31234273/146771073-ca179267-a64d-4999-830f-a576f1f675a9.png)
