### ISSUE TITLE
Logs appear to overlap in Lens5 with git clone/fetch

### ISSUE THREAD

**Issue by seanhamlin** [lensapp/lens#3233]
**Describe the bug**

We viewing the pod logs, when that log contains a git clone, or fetch. I suspect there are some special characters in the log output. Lens is not doing a good job as displaying the log

![image](https://user-images.githubusercontent.com/10605846/124032531-c9074a80-da4c-11eb-8582-9329d0b7a1ae.png)

This causes the rest of the log to be unreadable as well (the scrollbar really freaks out).

The plain text of the log is quite standard:

```
+ git fetch --tags --progress git@github.com:redacted/redacted.git '+refs/heads/*:refs/remotes/origin/*'
Warning: Permanently added 'github.com,52.64.108.95' (RSA) to the list of known hosts.

remote: Enumerating objects: 4080, done.        
remote: Counting objects:   0% (1/2315)        
remote: Counting objects:   1% (24/2315)        
remote: Counting objects:   2% (47/2315)        
remote: Counting objects:   3% (70/2315)        
remote: Counting objects:   4% (93/2315)        
remote: Counting objects:   5% (116/2315)        
remote: Counting objects:   6% (139/2315)        
remote: Counting objects:   7% (163/2315)        
remote: Counting objects:   8% (186/2315)        
remote: Counting objects:   9% (209/2315)        
remote: Counting objects:  10% (232/2315)        
remote: Counting objects:  11% (255/2315)        
remote: Counting objects:  12% (278/2315)        
remote: Counting objects:  13% (301/2315)        
remote: Counting objects:  14% (325/2315)        
remote: Counting objects:  15% (348/2315)        
remote: Counting objects:  16% (371/2315)        
remote: Counting objects:  17% (394/2315)        
remote: Counting objects:  18% (417/2315)        
remote: Counting objects:  19% (440/2315)        
remote: Counting objects:  20% (463/2315)        
remote: Counting objects:  21% (487/2315)        
remote: Counting objects:  22% (510/2315)        
remote: Counting objects:  23% (533/2315)        
remote: Counting objects:  24% (556/2315)        
remote: Counting objects:  25% (579/2315)        
remote: Counting objects:  26% (602/2315)        
remote: Counting objects:  27% (626/2315)        
remote: Counting objects:  28% (649/2315)        
remote: Counting objects:  29% (672/2315)        
...
```

**To Reproduce**
1. Inside a pod, execute a git clone, or git fetch
2. Watch the pod logs in Lens 5
3. Notice how the logs are messed up

**Expected behavior**
Logs can be scrolled through, like in Lens4

**Screenshots**
See above

**Environment (please complete the following information):**
- Lens Version: 5
- OS: OSX
- Installation method: dmg

**Comment by Nokel81** [comment]
This looks like we are not emulating terminal cursor repositioning control characters correctly.

**Comment by Nokel81** [comment]
So this is probably a bug with xterm.js

**Comment by Nokel81** [comment]
@seanhamlin I cannot seem to reproduce this on lens 5.2

**Comment by jim-docker** [comment]
I can reproduce on v5.4.0-beta.3

https://user-images.githubusercontent.com/40840436/155214935-cb5e1679-9bb7-46e7-8bc6-2226b9842735.mov
