### ISSUE TITLE
Kubeconfig env variable is wrong (Lens 5)

### ISSUE THREAD

**Issue by gudleik** [lensapp/lens#3246]
**Describe the bug**

The KUBECONFIG env variable in Lens is wrong, causing neither kubectl or attaching to pods work.

Output from terminal in Lens:

```bash
# echo $KUBECONFIG 
[object Promise]
```

Launching pods or using kubectl via the terminal in Lens now fails with errors like

```bash
# kubectl version
W0701 14:01:17.545882    7103 loader.go:223] Config not found: [object Promise]
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**To Reproduce**

1. Installed Lens 5 and added 3 clusters
2. Open terminal in Lens and run `kubectl version` or try attaching to a running pod

**Expected behavior**

KUBECONFIG env variable should be set correctly and kubectl should not return error

**Environment:**
- Lens Version: 5
- OS: OSX
- Installation method: Downloaded from https://k8slens.dev/ and replaced existing version (4)

**Comment by tugtugtug** [comment]
Have the same issue on Linux as well.
```
~> env | grep KUBECONFIG
KUBECONFIG=[object Promise]
```

**Comment by Nokel81** [comment]
I believe I have found the issue. This seems to be only happening when a user is using `fish`.

**Comment by thhermansen** [comment]
Thank you, @Nokel81 :)
