### ISSUE TITLE
Apps/Charts endless loading

### ISSUE THREAD

**Issue by Moskovych** [lensapp/lens#3250]
**Describe the bug**
After few latest updates (including version 5) of Lens - Apps/Charts are in endless loading.
Where the Apps/Releases works fine.

**To Reproduce**
1. Go to 'Apps/Charts'

**Expected behavior**
Full list of Helm charts (based on installed repositories) in the UI

**Screenshots**
![Screenshot 2021-07-02 at 11 52 20 AM](https://user-images.githubusercontent.com/10400095/124249591-b2d0bb80-db2c-11eb-91a7-ce5f2e104496.png)

**Environment (please complete the following information):**
- Lens Version: 5.0.0-latest.20210629.3
- OS: macOS Big Sur 11.4
- Installation method (e.g. snap or AppImage in Linux): brew

**Logs:**
Nothing interesting, except 
```
[CLUSTER]: refresh {"id":"*","name":"dev","ready":true,"online":true,"accessible":true,"disconnected":false}
```

**Kubeconfig:**
N/A

**Additional context**
Is there any option to enable debug mode, see more precise logs?

**Comment by jim-docker** [comment]
Hi, try this: https://docs.k8slens.dev/main/faq/#how-can-i-see-more-verbose-logs. You'll see logs for Lens's main process in the terminal. To see logs from Lens's renderer process select View -> Toggle Developer Tools from the Lens app menu, then select the Console tab.

**Comment by Moskovych** [comment]
@jim-docker , thanks....
So, enabled debug. When click to Apps/Releases I see `GET /api/v2/releases`,
when Apps/Charts - silent....no requests, no errors.

Only one thing in the log:

```
(node:38341) UnhandledPromiseRejectionWarning: TypeError: Invalid Version: null
    at new SemVer (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/semver/classes/semver.js:19:13)
    at Object.compare (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/semver/functions/compare.js:3:3)
    at /Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:90679
    at Array.sort (<anonymous>)
    at Object.sortChartsByVersion (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:90595)
    at Object.listCharts (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:87796)
    at async Object.listCharts [as route] (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:90766)
    at async ls.route (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:95179)
(node:38341) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```
Is that might be an issue?
I suspect it might be cause by some charts in repositories, which I have, and there is no check on `null` value?

**Comment by jim-docker** [comment]
That's probably it, thanks for the logs!

**Comment by Nokel81** [comment]
@Moskovych What repos have you added to your local helm instance?

**Comment by Moskovych** [comment]
@Nokel81 , here is the list:
```
jetstack            	https://charts.jetstack.io
eks                 	https://aws.github.io/eks-charts
nginx-stable        	https://helm.nginx.com/stable
ingress-nginx       	https://kubernetes.github.io/ingress-nginx
kube-state-metrics  	https://kubernetes.github.io/kube-state-metrics
prometheus-community	https://prometheus-community.github.io/helm-charts
appscode            	https://charts.appscode.com/stable/
apache-solr         	https://solr.apache.org/charts
bitnami             	https://charts.bitnami.com/bitnami
pravega             	https://charts.pravega.io
grafana             	https://grafana.github.io/helm-charts
```
There was also `stable` one, which is deprecated, but removing it didn't help.

**Comment by Nokel81** [comment]
Thanks I only have bitnami so having more will help with testing

**Comment by Nokel81** [comment]
I have narrowed the unexpected output to `appscode https://charts.appscode.com/stable/` and will push a fix PR shortly.

**Comment by Nokel81** [comment]
The problem is that `appscode` seems to be outputting very non-compliant semver versions and we were being a bit too strict in the parsing of them.

**Comment by Nokel81** [comment]
@Moskovych the versions it was outputting are of the form `v2021.04.12`. Even ignoring the `v` this is not strictly semver because of the leading `0` in the minor version. The PR turns on loose parsing which fixes the issue.

**Comment by Moskovych** [comment]
Hey @Nokel81 , thanks for the update.
Anyway, nobody can't guarantee that other charts following semver.
I think if the parsing is failing for some reason need to show it as raw or at least part of charts without failed with appropriate message somewhere (not in debug).

**Comment by Nokel81** [comment]
My choice in #3308 was to sort treating the string as a blackbox (so just alphanumeric sorting) if we cannot loosely coerce. That will remove these errors and still show the charts.
