### ISSUE TITLE
lens parses ALL configs in ~/kube/config*

### ISSUE THREAD

**Issue by marafa-sugarcrm** [lensapp/lens#3254]
**Describe the bug**
every so often i backup my kube config to ~/.kube/config_<some date> 
lens 5.0 parses them all not just the ~/kube/config file . this means that i have duplicate clusters in my catalog

**To Reproduce**

**Expected behavior**
lens will only look at ~/.kube/config file

**Screenshots**
![Screen Shot 2021-07-02 at 12 31 36 PM](https://user-images.githubusercontent.com/69474017/124304267-73f13480-db31-11eb-86ef-77eb992ee1ca.png)

**Environment (please complete the following information):**
- Lens Version:  5.0
- OS: [e.g. OSX] OSX 10.15.7
- Installation method (e.g. snap or AppImage in Linux): brew

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by marafa-sugarcrm** [comment]
i see this is a setting that is "on" by default. maybe it should be "off" and so it doesnt catch users unawares?

**Comment by jim-docker** [comment]
Hi, not sure if that is a common use case for the `.kube` folder, but we should consider that you can disable this (and only sync `.kube/config` file). We feel that syncing all config files in the `.kube` folder is a good user experience, especially for new users.

**Comment by Nokel81** [comment]
This is how we envisioned it would work, so that any other kubeconfig files within `.kube/` would also be picked up as it is the canonical location for those files.

**Comment by Nokel81** [comment]
Thanks for the report.
