### ISSUE TITLE
Add custom resources (CRDs) to command palette

### ISSUE THREAD

**Issue by paulmiu** [lensapp/lens#3258]
Please add custom resources (CRDs) to the command palette.

As you can see in the following screenshot **Ingresses** can be accessed from the command palette but **IngressRoutes** not.

<img width="992" alt="Screen Shot 2021-07-03 at 16 29 16" src="https://user-images.githubusercontent.com/3653465/124345566-fe629280-dc1c-11eb-9475-b5deaf1aed0f.png">

**What would you like to be added**:

If you have a lot of custom resources it might take a while to find the correct one. It would be much easier to access them from the command palette.

**Environment you are Lens application on:**

- Kubernetes distribution: k3s
- Desktop OS: macOS

**Comment by jim-docker** [comment]
Thanks for the suggestion!

**Comment by paulmiu** [comment]
I just realized that many more resources are not available in the command palette.

E.g.

* All resources under **Storage**
* **Namespaces**
* **Events**
* All resources under **Access Control**
* All resources under **Custom Resources**
* ...and maybe even more

<img width="324" alt="Screen Shot 2021-07-09 at 14 05 17" src="https://user-images.githubusercontent.com/3653465/125022060-35bebc80-e0bf-11eb-8da1-53b7843c8874.png">
