### ISSUE TITLE
Autoupdate to 5.0.0 failed

### ISSUE THREAD

**Issue by DmytroDrachov** [lensapp/lens#3259]
**Describe the bug**
Can not autoupdate from Lens 4.2.5 to 5.0.0

**To Reproduce**
1. brew install --cask lens
2. /Applications/Lens.app/Contents/MacOS/Lens
3. Await app loaded
4. Click yes when autoupdate appear
5. Nothing happened

**Expected behavior**
Should be updated

**Environment (please complete the following information):**
- Lens Version: 4.2.5
- OS: Mac OS BigSur 11.4 (20F71) (MacBook Pro 2019)
- Installation method (e.g. snap or AppImage in Linux): brew

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info: [UPDATE-CHECKER]: broadcasting update available {"backchannel":"auto-update:5.0.0-latest.20210629.3","version":"5.0.0-latest.20210629.3"}
info: [WINDOW-MANAGER]: Main window loaded
info: [UPDATE-CHECKER]: User chose to update now
info: / requested
info: /1625356466222-6420.zip requested
info: /1625356466222-6420.zip requested by Squirrel.Mac, pipe /Users/ddrachov/Library/Application Support/Caches/kontena-lens-updater/pending/Lens-5.0.0-latest.20210629.3-mac.zip
2021-07-04 02:54:29.790 Lens[73169:18185334] Download completed to: file:///Users/ddrachov/Library/Caches/com.electron.kontena-lens.ShipIt/update.5aSDJ4y/1625356466222-6420.zip
warn: Could not locate update bundle for com.electron.kontena-lens within file:///Users/ddrachov/Library/Caches/com.electron.kontena-lens.ShipIt/update.5aSDJ4y/ {"code":2,"domain":"SQRLUpdaterErrorDomain"}
error: Error: Error: Could not locate update bundle for com.electron.kontena-lens within file:///Users/ddrachov/Library/Caches/com.electron.kontena-lens.ShipIt/update.5aSDJ4y/
```

**Comment by jim-docker** [comment]
should be fixed by #3264 . Please reopen if still a problem.
