### ISSUE TITLE
ClusterStore deprecated and no way to get active cluster from Extension

### ISSUE THREAD

**Issue by besharper** [lensapp/lens#3265]
**Describe the bug**
Since `5.0.0` we are unable to get the active cluster from Extensions. Is there an alternative to getting the active cluster?

**To Reproduce**
1. Use `4.1.3` of `k8slens/extensions` in your extension
2. Implement code using `clusterStore`
3. Upgrade Lens to `5.0.0`
4. Custom extension no longer works

**Expected behavior**
After the upgrade to `5.0.0`, users must still be able to retrieve clusters from some kind of store.

**Environment (please complete the following information):**
- Lens Version: 5.0.0
- OSX

**Additional context**
Is there an alternative way of getting the active cluster, i.e. from the `CatalogEntity` registry, or is getting the active cluster no longer supported?

The Documentation of `Catalogs` are `WIP` and none of the Catalog members that are useful are being exported.
The Documentation for `ClusterStore.getInstance()` is also missing, and only `ExtensionStore` is documented.

**Comment by jim-docker** [comment]
Hi, we are in the process of updating our docs regarding the catalog. This question was answered on our community slack: https://k8slens.slack.com/archives/C01DXFK6SQ3/p1625126953079700?thread_ts=1625125204.079600&cid=C01DXFK6SQ3

```
import { Common, Renderer } from "@k8slens/extensions";
const activeEntity = Renderer.Catalog.catalogEntities.activeEntity;
if (activeEntity && activeEntity instanceof Common.Catalog.KubernetesCluster)
```
