### ISSUE TITLE
Lens 5 not available on SnapCraft

### ISSUE THREAD

**Issue by braunsonm** [lensapp/lens#3273]
**Describe the bug**
The website lists Snap as an option to install lens however it is not updated to 5.0 yet.

**Comment by jim-docker** [comment]
Hi, we will be offering the snap package through our site (https://github.com/lensapp/lensapp.github.io/issues/18), but we have currently stopped pushing it to SnapCraft. We have some technical issues in moving forward with SnapCraft but we may reopen this issue soon.

**Comment by Wouter0100** [comment]
Is there any idea when this would be possible? I just got a message from Lens that V5 is available, and would love to get it through SnapCraft.

**Comment by devopsmash** [comment]
It will be awesome to have the latest Lens releases on the snapcraft store

meanwhile this is the workaround that I have found:
1. download the latest .snap file from: https://k8slens.dev/
2. run the following snap command in order to install the .snap file
```
sudo snap install --dangerous --classic  <Lens snap file name>.snap
```
