### ISSUE TITLE
More detailed error message

### ISSUE THREAD

**Issue by matkosoric** [lensapp/lens#3284]
It would be nice to get slightly more detailed message than "Oops, something went wrong."

![image](https://user-images.githubusercontent.com/24875759/124605474-3875a380-de6c-11eb-8e11-84b871a987b6.png)

Environment is Lens 5, and Kubernetes distribution is EKS, accessed from Windows 10.

**Comment by taspeotis** [comment]
Yes the error message is unhelpful especially considering how Lens 5 does not work [without being Administrator](https://github.com/lensapp/lens/issues/3244).

![image](https://user-images.githubusercontent.com/1189399/124690321-57803e00-df1d-11eb-96d9-ac8cae382fd1.png)

![image](https://user-images.githubusercontent.com/1189399/124690309-53ecb700-df1d-11eb-98fd-5289e34f4561.png)
