### ISSUE TITLE
Can't load extensions

### ISSUE THREAD

**Issue by vamsikrishna7667** [lensapp/lens#3287]
I'm using the lens in an air gap environment. Extensions are kept on loading and can't upload a TGZ file.
<img width="632" alt="lens" src="https://user-images.githubusercontent.com/30297494/124620757-b70c1a00-de47-11eb-8e2c-d4bf9972cb10.PNG">

**Comment by Nokel81** [comment]
Any logs?

**Comment by vamsikrishna7667** [comment]
I found this in npm-cache folder.

43 silly fetchPackageMetaData error for react-open-doodles@^1.0.5 request to https://registry.npmjs.org/react-open-doodles failed, reason: self signed certificate in certificate chain
44 timing stage:rollbackFailedOptional Completed in 2ms

**Comment by Nokel81** [comment]
No I meant https://docs.k8slens.dev/main/faq/?h=logs#where-can-i-find-application-logs

**Comment by vamsikrishna7667** [comment]
�[32minfo�[39m: [PROTOCOL ROUTER]: internal registering /cluster/:clusterId
�[32minfo�[39m: [PROTOCOL ROUTER]: internal registering /cluster/:clusterId/settings
�[32minfo�[39m: [PROTOCOL ROUTER]: internal registering /extensions
�[32minfo�[39m: [PROTOCOL ROUTER]: internal registering /extensions/install/:LENS_INTERNAL_EXTENSION_PUBLISHER_MATCH(@[A-Za-z0-9_]+)?/:LENS_INTERNAL_EXTENSION_NAME_MATCH
�[31merror�[39m: Can't find working API for the Kubernetes resource ingresses
�[32minfo�[39m: [StorageHelper]: loading finished for C:\Users\user\AppData\Roaming\Lens\lens-local-storage\app.json

**Comment by Nokel81** [comment]
We need more logs, can you run in debug mode and post the whole log file?

**Comment by vamsikrishna7667** [comment]
This is resolved. I removed .k8slens folder in the home directory and reinstalled the lens. It's working now.
