### ISSUE TITLE
[Feature Request] LimitRanges and Describe Limits

### ISSUE THREAD

**Issue by kferrone** [lensapp/lens#329]
**What would you like to be added**:
I would like a section for the `LimitRange` kind. [View the docs here.](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/) As these are namespaced and all of the limits together apply to the namespace, it would be very nice to see the output of `kubectl describe limits -n default` on the namespace view. I imagine the best place for `LimitRange` kind would be directly below the `ResourceQuota` kind in the dashboard. 

**Why is this needed**:
No way to see the `LimitRange` kind or any of the information about them. 

**Environment you're Lens application is on:** 3.3.1

- Kubernetes distribution: EKS
- Desktop OS: MacOSX

**Comment by vshakirova** [comment]
hey guys :) I'd like to implement it if you don't mind

**Comment by nevalla** [comment]
> hey guys :) I'd like to implement it if you don't mind

Go for it!
