### ISSUE TITLE
Option to add custom templates or edit default templates

### ISSUE THREAD

**Issue by paulmiu** [lensapp/lens#3319]
**What would you like to be added**:

Option to add custom templates or edit default templates.

**Why is this needed**:

Templates are a super useful feature, but currently users are limited to the default templates in Lens which unfortunately limits that feature a lot.

**Environment you are Lens application on:**

- Kubernetes distribution: k3s
- Desktop OS: macOS

**Comment by jim-docker** [comment]
Hi, I believe this has been addressed here: https://github.com/lensapp/lens/pull/2327

**Comment by paulmiu** [comment]
@jim-docker You're right. At least that's what it looks like from the GIF in the pull request you've mentioned.

But according to the PR this feature should already be available in Lens 5... which it isn't (or maybe I'm blindfolded because I can't find any option to create custom templates in Lens 5 😀).

**Comment by aleksfront** [comment]
@mamiu All you need to do is create new folder inside `/.k8slens/templates` and add some `*.yaml` files in there. Right after you will see your new templates grouped by the name of the directory.

![custom templates](https://user-images.githubusercontent.com/9607060/125613746-40901634-361a-4377-8ef8-62d0e3fe64cc.png)

We're working on improving documentation to cover this feature. Sorry for the confusion.

**Comment by paulmiu** [comment]
@aleksfront That's amazing! Thanks a lot!
