### ISSUE TITLE
Lens cannot detect my kube-state-metrics installed in a non-default namespace

### ISSUE THREAD

**Issue by douglascamata** [lensapp/lens#3329]
**Describe the bug**
Lens is not able to detect a kube-sate-metrics instance that I have running outside of the default namespace.

**To Reproduce**
1. Install kube-state-metrics in a cluster outside of the default namespace
2. Click on the "Cluster" item on the left bar
3. See no metrics

**Expected behavior**
Lens should be able to discover my KSM instance, no matter in which namespace it is, and use it to provide me cluster wide metrics.

**Screenshots**

Not really needed.

**Environment (please complete the following information):**
- Lens Version: 5.0.2-latest.20210705.2
- OS: [e.g. OSX] MacOS
- Installation method (e.g. snap or AppImage in Linux): DMG file

**Comment by Nokel81** [comment]
We only use `kube-state-metrics` for the pod-metrics in the node details panel. The rest of the metrics views are powered by prometheus.

I have installed kube-state-metrics within the `kube-system` namespace and they are picked up in that space. So this is working as intended.
