### ISSUE TITLE
Lens 5.0.2 never starts (mac)

### ISSUE THREAD

**Issue by Valkyrie00** [lensapp/lens#3346]
**Describe the bug**
Hi there, my problem is very similar of this issue:  #3239 . I see that there are some works for fix this problem already released, but they didn't work in my case.
I tried to find in my zsh env/config if i have some plugin that can cause this problem like this issue: #3294 , but i not found nothing of relevant, and i never touch my configuration in last month.

There are one difference respect of the linked issues. In my case if i run lens directly in shell with this command:
`/Applications/Lens.app/Contents/MacOS/Lens`, the application start as usual.

**To Reproduce**
In first attempt, i have downloaded the new version with the information tooltip in lens app.

I tried to fix my problem like this BUT NOT WORK :( :
1. Deleted Lens app in application directory
2. Deleted All content of Library/Application Support/Lens
1. Install latest Lens version 5.0.2-latest.20210705.2. downloaded from the website
2. Start Lens with spotlight or double click in application folder

**Expected behavior**
Start lens as usual.

**Screenshots**
![Screenshot 2021-07-10 at 14 20 17](https://user-images.githubusercontent.com/4854263/125162806-2ce6ed00-e18a-11eb-8e62-4bc0290d0141.png)

**Environment (please complete the following information):**
- Lens Version: 5.0.2-latest.20210705.2
- OS: MacOs Big Sur 11.4
- Installation method (e.g. snap or AppImage in Linux): DMG

**Logs:**
This is the logs when i lunch lens directly from shell: ( and this is work 🤯 )
```
 MYYUSER@VItos-MacBook-Pro-2  ~  /Applications/Lens.app/Contents/MacOS/Lens
info: 📟 Setting Lens as protocol client for lens://
info: 📟 Protocol client register succeeded ✅
info: 🚀 Starting Lens from "/Users/MYYUSER/Library/Application Support/Lens"
info: 🐚 Syncing shell environment
info: 💾 Loading stores
info: [STORE]: LOADED from /Users/MYYUSER/Library/Application Support/Lens/lens-user-store.json
info: [STORE]: LOADED from /Users/MYYUSER/Library/Application Support/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /Users/MYYUSER/Library/Application Support/Lens/lens-hotbar-store.json
info: [STORE]: LOADED from /Users/MYYUSER/Library/Application Support/Lens/lens-extensions.json
info: [STORE]: LOADED from /Users/MYYUSER/Library/Application Support/Lens/lens-filesystem-provisioner-store.json
info: [STORE]: LOADED from /Users/MYYUSER/Library/Application Support/Lens/lens-weblink-store.json
info: 🔌 Starting LensProxy
info: [LENS-PROXY]: Proxy server has started at 127.0.0.1:63021
info: 🔎 Testing LensProxy connection ...
info: ⚡ LensProxy connection OK
info: 🖥️  Starting WindowManager
info: 🧩 Initializing extensions
info: [EXTENSION-DISCOVERY] loading extensions from /Users/MYYUSER/Library/Application Support/Lens
info: [EXTENSION-INSTALLER] installing dependencies at /Users/MYYUSER/Library/Application Support/Lens
info: [WINDOW-MANAGER]: Loading Main window from url: http://localhost:63021 ...
info: [EXTENSION-INSTALLER] dependencies installed at /Users/MYYUSER/Library/Application Support/Lens
info: [EXTENSION-DISCOVERY] watching extension add/remove in /Users/MYYUSER/.k8slens/extensions
Native extraction module not loaded, msgpackr will still run, but with decreased performance. Cannot find module 'msgpackr-extract'
Lens Cloud Extension activated
info: [STORE]: LOADED from /Users/MYYUSER/Library/Application Support/Lens/extension-store/lenscloud-lens-extension/auth-token-store.json
error: [EXTENSIONS-LOADER]: can't load main for "lens-telemetry": TypeError: Cannot create a second singleton while creating a first {"extension":{"id":"/Users/MYYUSER/Library/Application Support/Lens/node_modules/lens-telemetry/package.json","absolutePath":"/Applications/Lens.app/Contents/Resources/extensions/telemetry/lens-telemetry-5.0.2-latest.20210705.2.tgz","manifestPath":"/Users/MYYUSER/Library/Application Support/Lens/node_modules/lens-telemetry/package.json","manifest":{"name":"lens-telemetry","version":"5.0.2-latest.20210705.2","description":"Lens IDE telemetry","main":"dist/main.js","renderer":"dist/renderer.js","lens":{"metadata":{},"styles":[]},"scripts":{"build":"webpack -p && npm pack","dev":"webpack --watch","test":"jest --passWithNoTests --env=jsdom src $@"},"files":["dist/**/*"],"devDependencies":{"@k8slens/extensions":"file:../../src/extensions/npm/extensions","@types/analytics-node":"^3.1.3","@types/node":"^14.14.14","@types/react":"^17.0.0","@types/universal-analytics":"^0.4.4","analytics-node":"^3.4.0-beta.3","conf":"^7.1.2","jest":"^26.6.3","mobx":"^6.3.2","mobx-react":"^7.1.0","node-machine-id":"^1.1.12","react":"^16.13.1","ts-loader":"^8.0.4","typescript":"^4.0.3","universal-analytics":"^0.4.23","webpack":"^4.44.2","webpack-cli":"^3.3.11"}},"isBundled":true,"isEnabled":true,"isCompatible":true}}
error: [EXTENSION]: failed to activate lens-survey@5.0.2-latest.20210705.2: Error: [MobX] No annotations were passed to makeObservable, but no decorated members have been found either
info: [EXTENSION]: enabled lens-license@5.0.2-latest.20210705.2
[CLUSTER-CONNECT] cluster proxy started on port 63034
[CLUSTER-CONNECT] cluster proxy is using aes-256-gcm for end-to-end encryption
info: [EXTENSION]: enabled lenscloud-lens-extension@5.0.2-latest.20210705.2
info: [KUBECONFIG-SYNC]: starting requested syncs
info: 📡 Checking for app updates
info: Checking for update
info: [KUBECONFIG-SYNC]: starting sync of file/folder {"filePath":"/Users/MYYUSER/.kube"}
info: [KUBECONFIG-SYNC]: starting sync of file/folder {"filePath":"/Users/MYYUSER/Library/Application Support/Lens/kubeconfigs"}
info: Update for version 5.0.2-latest.20210705.2 is not available (latest version: 5.0.2-latest.20210705.2, downgrade is disallowed).
info: [WINDOW-MANAGER]: Main window loaded
info: [WINDOW-MANAGER]: Main window has reported that it has loade
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by jim-docker** [comment]
Is the Lens tray icon present?" If so, can you open it and click "Open Lens"? Does it load then?

**Comment by Valkyrie00** [comment]
Thanks @jim-docker for your support.
Yess i confirm. When i lunch Lens from spotlight or double click in application folder, Lens icon appears in tray, but when i click on **open lens** label, appears an empty application windows. Here some screenshot.

![Screenshot 2021-07-12 at 16 27 37](https://user-images.githubusercontent.com/4854263/125304683-137ea600-e32e-11eb-8a54-daecc4cadcbd.png)
![Screenshot 2021-07-12 at 16 28 52](https://user-images.githubusercontent.com/4854263/125304900-3f9a2700-e32e-11eb-9961-2230018859f8.png)

Works only about lens
![Screenshot 2021-07-12 at 16 31 07](https://user-images.githubusercontent.com/4854263/125305335-90aa1b00-e32e-11eb-82ff-e8f91124130d.png)

Here you can found the console log reported in **view**->**toggle developer tools**
![Screenshot 2021-07-12 at 16 32 23](https://user-images.githubusercontent.com/4854263/125306649-ab30c400-e32f-11eb-9db4-31eb1180e9a8.png)

**Comment by jim-docker** [comment]
Thanks, this helps. 
If you go to View -> Reload in the Lens menu, does the proper UI finally appear? A workaround, at least, until we fix the issue

**Comment by Valkyrie00** [comment]
@jim-docker Ok, i tried and nope :( , UI not appear. The logs is very similar with the previous, but not the same, for example when application try to create a second singleton say that the responsable is **singleton.ts**, idk if can help.
![Screenshot 2021-07-12 at 19 33 28](https://user-images.githubusercontent.com/4854263/125332977-f8219400-e349-11eb-919f-444ba92fd4ec.png)


A curious thing, if i click for 3 consecutive times **Reload** application crashed and mac problem reports appears:
![Screenshot 2021-07-12 at 19 41 32](https://user-images.githubusercontent.com/4854263/125332208-2a7ec180-e349-11eb-8fe7-563f93dbd128.png)
.

**Comment by Nokel81** [comment]
I believe your issue will be fixed in 5.1.0 because of #3225

**Comment by Valkyrie00** [comment]
@Nokel81 oh perfect thanks, I hope this minor arrives as soon as possible. it's really blocking as a problem.

**Comment by Nokel81** [comment]
Should be out tomorrow, we released the beta for it today. You can get it from https://api.k8slens.dev/binaries/Lens-5.1.0-beta.1.20210712.1.dmg

Would you mind checking if it resolves your issue?

**Comment by Valkyrie00** [comment]
@Nokel81 Confirmed! Work perfectly! 🎉 
![Screenshot 2021-07-12 at 23 03 42](https://user-images.githubusercontent.com/4854263/125355492-6889de80-e365-11eb-8eb6-fe7a8235e19a.png)
![Screenshot 2021-07-12 at 23 07 53](https://user-images.githubusercontent.com/4854263/125356030-fd8cd780-e365-11eb-89a6-51230abeb9df.png)


QA for this ticket PASS 😁
Thanks for support 👍
