### ISSUE TITLE
UI does not show when run through ssh ForwardX11

### ISSUE THREAD

**Issue by mehturt** [lensapp/lens#3356]
**Describe the bug**
Lens UI does not start up when run through ssh session with ForwardX11 enabled.  Only an empty window is displayed.

**To Reproduce**
1. Open terminal
2. Ssh to localhost with X forwarding, e.g. "ssh -X localhost"
3. Start Lens

**Expected behavior**
Lens UI displayed

**Screenshots**
![lens](https://user-images.githubusercontent.com/195313/125294884-f5f90e80-e324-11eb-9b9f-aac26a5efc4f.png)

**Environment (please complete the following information):**
- Lens Version: 5.0.2-latest.20210705.2-20210705.2
- OS: Debian GNU/Linux 10.10
- Installation method (e.g. snap or AppImage in Linux): deb file

**Logs:**
n/a

**Kubeconfig:**
n/a

**Additional context**
n/a

**Comment by jim-docker** [comment]
Hi, I had a similar problem when running Lens remotely, via ssh. I believe there is some shared memory issue involving electron/chromium that causes this. I fixed it by adding on the remote system:
```
export QT_X11_NO_MITSHM=1
```

**Comment by mehturt** [comment]
Thank you @jim-docker  that fixes (works around) the problem for me as well.

**Comment by jim-docker** [comment]
That's good. I think it is the best we can do for now since the issue is outside of the Lens codebase.

**Comment by mehturt** [comment]
It would be nice to document this workaround.
