### ISSUE TITLE
Lens does not show Workloads even after full uninstall

### ISSUE THREAD

**Issue by ilelouis** [lensapp/lens#3363]
**Describe the bug**
After installing Lens, the workspace does not show anything.  Any attempts to expand Workloads, Overview, Apps, etc do not show expected items.

I have attempted to uninstall Lens, remove the Lens directory and cache as well as completely remove the kubeconfig file but the issue persists.  I installed from k8lens.dev and using `brew`, but the problem persisted.  Several other users do not have this issue. 

I am able to perform all actions via `kubectl` so I do not think this is a permissions issue within the cluster.

**To Reproduce**
1. Install Lens
2. use `gcloud` to populate the kubeconfig to connect to GKE cluster
3. Open Lens
4. Notice that nothing shows on Lens

**Expected behavior**
Expected behavior is to open Lens and be able to see all workloads, nodes and other objects. 

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.0.2
- OS: Mac Catalina 10/15/7
- Installation method (e.g. snap or AppImage in Linux): Website or `brew`

**Logs:**
Only error in logs i see is:
```
error: Can't find working API for the Kubernetes resource ingresses
```

**Additional context**
I have tried multiple versions 4.x and 5.x without success.

**Comment by Nokel81** [comment]
Can you post a video of what you are seeing when you start lens?

**Comment by Nokel81** [comment]
Also I don't think "Workspace" is a kube object type.

**Comment by ilelouis** [comment]
I apologize for the delay here.  

When i say "workspace" i really just mean the app UI. In the screenshot below, the user has logged into the GKE cluster and connected to it in Lens but cannot see any objects, nothing displays.  The user is able to run `kubectl` commands to get pods, ingress, etc, but nothing shows in Lens

![Lens-ClusterA-Issue](https://user-images.githubusercontent.com/87339811/125955812-f0573db2-a35f-4d30-b578-1e8f3c9c10d6.png)

**Comment by Nokel81** [comment]
Sounds like the cluster that is being used in lens has a different user account. One that has some restrictive RBAC rules. Are there several clusters in the catalog?

**Comment by ilelouis** [comment]
We control access via Active Directory groups. The user in question is in the same group with the same RBAC assigned via Role as a dozen other users. I temporarily gave the user cluster-admin permissions thinking maybe there was something wrong, but issue persisted.

The user has added a second cluster to the catalog ad confirmed that they have the same issue in the second cluster.

Could there be some other location where Lens stores configuration files or objects that might need to be manually removed in order to attempt a full uninstall / re-install?

**Comment by Nokel81** [comment]
Yes that would be `/Users/<user>/Library/Application Support/Lens`

**Comment by ilelouis** [comment]
OK thanks. so we did have the user remove that folder many times while we tried to troubleshoot this issue.  After every uninstall, we would remove that folder.

**Comment by Nokel81** [comment]
Do you see anything more with `DEBUG=true` running from the command line? Does the user have any local firewalls?

**Comment by ilelouis** [comment]
The only error at the time was `error: Can't find working API for the Kubernetes resource ingresses` as noted in the problem description. But i can have the user launch it again and send me the full log output and then scrub it, I will post that shortly

It is possible that one of the security tools installed on our laptops are blocking the connectivity and I have opened up a ticket internally to check on that.

**Comment by Nokel81** [comment]
That error occurs if all of the kube APIs URLs for the `ingresses` resource is rejected. A full log would be very helpful, thank you.

**Comment by yogageek** [comment]
> able to run kubectl commands to get pods, ingress, etc, but nothing shows in Lens (workloads, overview are empty)
i totally have the same issue. 
> Yes that would be `/Users/<user>/Library/Application Support/Lens`
But I could not find this folder on my windows.

**Comment by yogageek** [comment]
able to run kubectl commands to get pods, ingress, etc, but nothing shows in Lens (workloads, overview are empty)

i totally have the same issue.

Yes that would be /Users/<user>/Library/Application Support/Lens

But I could not find this folder on my windows.

**Comment by yogageek** [comment]
>able to run kubectl commands to get pods, ingress, etc, but nothing shows in Lens (workloads, overview are empty)

i totally have the same issue.

>Yes that would be /Users/<user>/Library/Application Support/Lens

But I could not find this folder on my windows.

**Comment by yogageek** [comment]
>able to run kubectl commands to get pods, ingress, etc, but nothing shows in Lens

I totally have the same issue.  Workloads only show Overview, but inside are empty

>Yes that would be /Users/<user>/Library/Application Support/Lens

Where can I find this folder on my windows?

**Comment by Nokel81** [comment]
> >able to run kubectl commands to get pods, ingress, etc, but nothing shows in Lens
> 
> I totally have the same issue.  Workloads only show Overview, but inside are empty
> 
> >Yes that would be /Users/<user>/Library/Application Support/Lens
> 
> Where can I find this folder on my windows?

Do you have RBAC? On windows that would be `%AppData%\Lens`

**Comment by yogageek** [comment]
I'm not sure what's mean by RBAC here. As I know I share one kubenetes with other developers, and my account role is ClusterOwner.

**Comment by Nokel81** [comment]
If you run the lens executable with the environment variable `LOG_LEVEL` set to `silly`. Do you see any log lines of the form `[CLUSTER]: push-state { ... }` and if so, what is in that logged object?

**Comment by mcm-ham** [comment]
I'm experiencing this bug too. In the logs I see this error:

```
info: Downloading kubectl 1.20.8 from https://storage.googleapis.com/kubernetes-release/release/v1.20.8/bin/darwin/arm64/kubectl to /Users/michael/Library/Application Support/Lens/binaries/kubectl/1.20.8/kubectl
error: Local kubectl failed to run properly (Command failed: "/Users/michael/Library/Application Support/Lens/binaries/kubectl/1.20.8/kubectl" version --client=true -o json
/Users/michael/Library/Application Support/Lens/binaries/kubectl/1.20.8/kubectl: line 1: syntax error near unexpected token `<'
/Users/michael/Library/Application Support/Lens/binaries/kubectl/1.20.8/kubectl: line 1: `<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: kubernetes-release/release/v1.20.8/bin/darwin/arm64/kubectl</Details></Error>'
), unlinking
```

Seems it's trying to download kubectl from this URL which doesn't work https://storage.googleapis.com/kubernetes-release/release/v1.20.8/bin/darwin/arm64/kubectl if I try to download from this URL https://dl.k8s.io/release/v1.20.8/bin/darwin/amd64/kubectl and place in folder, it simply gets deleted the next time I try to run the app.

**Comment by Nokel81** [comment]
@mcm-ham You should be able to just download the version that you want to use and stick it somewhere else and then point Lens at it.

FYI your second URL is for an `amd64` binary not a `arm64` binary.
