### ISSUE TITLE
Prometheus endpoint as url

### ISSUE THREAD

**Issue by korjavin** [lensapp/lens#337]
I use VictoriaMetrics as drop-in replacement for prometheus.
But it has url with some path in it.

So, it's not enough for me just host:port  in the settings.

**Comment by korjavin** [comment]
doesn't work for me (in 3.4.0-rc.1)

I can't set 
`namespace/vm-victoria-metrics-cluster-vmselect:8481/select/0/prometheus`
in settings
it loses path part

**Comment by jakolehm** [comment]
@korjavin #341 didn't make into 3.4.0-rc.1 .. it will be in next rc/final.

**Comment by korjavin** [comment]
Sorry, it still doesn't work

![image](https://user-images.githubusercontent.com/148765/82597440-a3edaa80-9bb1-11ea-989d-bca6861d118a.png)

**Comment by sergeyshaykhullin** [comment]
@jakolehm I am still getting this error with VM setup + Lens 5.6.0-alpha.5. Path is omitted 

![image](https://user-images.githubusercontent.com/46970457/177053565-f06fe0f6-c049-43a9-b7a4-911b32da2099.png)

![image](https://user-images.githubusercontent.com/46970457/177053617-65f8ca4c-8c0b-4fb2-8e0d-51d8a8cade7e.png)

It has to be `/select/0/prometheus/api/v1/query_range?...` to work with Victoria Metrics
