### ISSUE TITLE
Unable to switch on metrics in connected cluster

### ISSUE THREAD

**Issue by aleksfront** [lensapp/lens#3370]
Settings page can't properly fetch cluster status. This caused inability to enable metrics. All switchers inside the connected cluster are disabled.

<img width="997" alt="disabled metrics" src="https://user-images.githubusercontent.com/9607060/125448264-d3b2cdbf-da81-496e-88c7-368af3da29e3.png">

To reproduce:
1. Open cluster dashboard.
2. Go to cluster settings.
3. Go to Lens Metrics page under Extensions title.

**Comment by Nokel81** [comment]
I cannot reproduce this on master.

**Comment by jim-docker** [comment]
me neither

**Comment by aleksfront** [comment]
Recompiling bundled extensions did the trick. Just needed to make fresh `make dev`.
