### ISSUE TITLE
lens/extensions 5+ doesn't provide access to k8s cluster version

### ISSUE THREAD

**Issue by pashevskii** [lensapp/lens#3375]
Hi lens team, 
My [extension](https://github.com/pashevskii/debug-pods-lens-extension) used clusterStore to get k8s version. It allowed building kubectl command considering a specific version of k8s instance (or block the ability to use some features if k8s doesn't support these ones). 
But, after extensions 5+ release, access to clusterStore was suppressed, moreover, the package doesn't provide alternative ways to get information about clusters. That fully blocks implementing lens5 compatible version of the extension

**Comment by Nokel81** [comment]
Fixed by #3335
