### ISSUE TITLE
Lens spawns kubectl exec incorrectly on Windows

### ISSUE THREAD

**Issue by jtackaberry** [lensapp/lens#338]
When opening a shell on a container, Lens opens a Powershell terminal, and calls `exec kubectl exec [...]` which fails as below:

![image](https://user-images.githubusercontent.com/1280551/80927921-03a12480-8d6f-11ea-9368-76c9c778ef75.png)

Invoking the command without the prepended `exec` works fine.

Lens 3.4.0-beta2, Windows 10 1909 (build 18363.778).

**Comment by jakolehm** [comment]
Does this still happen? Lens should only prepend `exec` if `process.platform !== "win32"`.

**Comment by RiFi2k** [comment]
@jakolehm I was writing some windows docs for clients on the newest lens version and this happens in powershell for sure, which is what he is showing above. So most likely regular command prompt is good but if you have PS as default terminal then this will happen.

**Comment by pappnase99** [comment]
Still happening in 3.4.0 release version.

**Comment by servo1x** [comment]
@RiFi2k is there a way to make command prompt as the default from powershell? It's really confusing for some of our windows developers.

**Comment by jakolehm** [comment]
@nevalla Dashboard is executed within webview sandbox and it does not have access to `process.platform`. Maybe we can use `window.navigator.platform` here.

**Comment by avg07** [comment]
Works in 3.5.0-beta.1
