### ISSUE TITLE
Catalog list poor performance

### ISSUE THREAD

**Issue by aleksfront** [lensapp/lens#3389]
Switching between catalog categories goes with visible delay, causing poor UX. Rendering process here should be optimised.

https://user-images.githubusercontent.com/9607060/125783224-755c2fdb-8ed4-47bf-9611-ab9134f58ebe.mov

**Comment by Nokel81** [comment]
I think we should work by bypassing ItemListLayout and use table itself.

**Comment by aleksfront** [comment]
> I think we should work by bypassing ItemListLayout and use table itself.

Good point. I will check this also.

**Comment by Nokel81** [comment]
Because ItemListLayout requires a new store to be initialized.
