### ISSUE TITLE
issue with using Kontena Lens with AKS cluster

### ISSUE THREAD

**Issue by Harishkrishna17** [lensapp/lens#34]
Hi Team, 

We are facing issue with connecting kotena with aks cluster ,

Steps to reproduce :

1. Start a aks cluster and install kotena locally , and connect to it and enable metrics
2. Once metrics is enabled, all the required resources are created in lens-metrics namespaces without any errors 
3. Node level metrics are scraped correctly , When we are trying to get pod level metrics it fails , Saying metrics not available yet 
4. On seeing the kotena logs , This seem to be a bug 

```
error: server https://aks:443 stderr: [ERROR] -> [KUBE-REQUEST]: Request failed with status code 404 {
 "method": "get",
 "url": "https://aks:443/api/v1/namespaces/lens-metrics/services/prometheus:80/proxy/api/v1/query_range",
 "headers": {
   "Accept": "application/json, text/plain, /",
   "Content-Type": "application/json",
   "User-Agent": "axios/0.19.0"
 },
 "params": {
   "query": "sum(node_filesystem_size_bytes{mountpoint=\"/\"}) by (kubernetes_node)",
   "start": "1569985980",
   "end": "1569989580",
   "step": "60",
   "kubernetes_namespace": "kontena-stats"
 }
}
```

We faced the same issue when installing prometheus operator on the cluster , Work around for this is to change https to htp 
On executing the below command on prometheus operator , Everything works fine 
```
kubectl -n monitoring get servicemonitor prometheus-prometheus-oper-kubelet -o yaml | sed 's/https/http/' | kubectl replace -f - 
```

This may be an hint for the issue

**Comment by jnummelin** [comment]
> On executing the below command on prometheus operator , Everything works fine
> `kubectl -n monitoring get servicemonitor prometheus-prometheus-oper-kubelet -o yaml | sed 's/https/http/' | kubectl replace -f - `
> This may be an hint for the issue 

Would you be able to produce a "diff" what that sed command actually changes?

**Comment by jnummelin** [comment]
closing due inactivity, re-open if needed
