### ISSUE TITLE
Setting lens engine to ^5.1.0 in package.json for Lens 5.1.0 does not work

### ISSUE THREAD

**Issue by stefcameron** [lensapp/lens#3404]
In relation to https://github.com/lensapp/lens/issues/3212, which was mostly fixed, I can set my `lens` engine, in package.json, to `^5.0.0` and Lens 5.1.0 will deem it compatible.

But if I set the engine to `^5.1.0` in Lens 5.1.0, then Lens deems it _incompatible_.

Doesn't seem right. And in the case of the https://github.com/Mirantis/lens-extension-cc extension, it was DOA in Lens until 5.1.0, so technically, I should be setting the engine to `^5.1.0` so that someone installing it in <5.1.0 isn't able to use it...

Lens version: `5.1.0-latest.20210715.1` on macOS 11.4

**Comment by jim-docker** [comment]
Thanks Stefan, that's odd.

With respect to compatibility I think `^5.0.0` is the right spec for your extension, though setting it as `^5.1.0` is a convenient way to indicate the minimum version needed such that it is successfully loaded.

**Comment by stefcameron** [comment]
> With respect to compatibility I think `^5.0.0` is the right spec for your extension, though setting it as `^5.1.0` is a convenient way to indicate the minimum version needed such that it is successfully loaded.

I would argue that it's not compatible back to 5.0.0, which `^5.0.0` allows, because 5.0.0, 5.0.1, 5.0.2, and 5.0.3 all fail to load the extension properly.

But I suppose you could look at this and say the extension still supports Lens 5.0.0 and the fact it doesn't load is because of Lens issues, not the extension's.
