### ISSUE TITLE
Issues trying to add clusters to Lens

### ISSUE THREAD

**Issue by vjcubas** [lensapp/lens#3407]
**Describe the bug**
Cannot add  clusters that are not in ~/.kube/config file. Regardless of what I paste in the input filed, the only cluster that appears in the cluster list is the one in ~/.kube/config file. If the ~/.kube/config file does not exist, no cluster is added.

**To Reproduce**
1. Go to 'clusters'
2. Click on '+'
3. Paste Kubeconfig contents into input field

**Expected behavior**
A new cluster should appear on the cluster list

**Screenshots**
The only cluster that appears is the one on ~/.kbue/config

<img width="1614" alt="image" src="https://user-images.githubusercontent.com/7746604/125949562-2f199252-6a39-4e10-b278-d21f011c8a77.png">

**Environment**
OS: OSX
Lens: 5.0.2-latest.20210705.2
Electron: 9.4.4
Chrome: 83.0.4103.122
Node: 12.14.1

**Comment by Nokel81** [comment]
Please restart lens (including the tray icon) your clusters will appear. 

I will leave this issue open as there is a bug here.
