### ISSUE TITLE
Cannot add ClusterRoleBinding with user/group target

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#3451]
Create button is only enabled if I select ServiceAccount.

![image](https://user-images.githubusercontent.com/1446224/126309182-6acc62aa-7cfc-40a5-adbc-d60566da9f74.png)

**Comment by jakolehm** [comment]
Same applies to RoleBinding UI.

**Comment by Nokel81** [comment]
You need to press enter to add the name of the user to the list of users. This is working as intended but maybe should have some better affordance
