### ISSUE TITLE
List of clusters not updated after adding a kubeconfig configuration to Lens

### ISSUE THREAD

**Issue by jicowan** [lensapp/lens#3471]
**Describe the bug**
I clicked the "+" sign to add a new cluster and pasted in the cluster's kubeconfig. The cluster did not appear in the list until I restarted Lens. Before restarting, I also tried "reload", but that didn't work. 

**To Reproduce**
1. Go to clusters
2. Click on + or add a cluster
3. Paste in your kubeconfig and click add cluster
4. Observe cluster list

**Expected behavior**
I expected the new cluster to appear in the list of available clusters.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: Lens: 5.1.2-latest.20210719.1
- OS: OSX

**Comment by Nokel81** [comment]
Duplicate of https://github.com/lensapp/lens/issues/3407
