### ISSUE TITLE
Metrics Not Available in 5.1.2 - RBAC

### ISSUE THREAD

**Issue by MisterBlueBear** [lensapp/lens#3476]
**Describe the bug**
Under Lens 4.2.5, a user is able to view Pod metrics (cpu, memory, etc) without any issues in their namespaces, but after upgrading to 5.1.2, the metrics are not available. Lens logs mention "is forbidden: User \"xxxxxx@xxxxxx\" cannot create resource \"services/proxy\" in API group \"\" in the namespace \"monitoring\"""

Why is Lens 5.x trying to create the Service if it already exists and is accessible by the user ?
Shouldn't "get", "list", "watch" on resources "services"and "services/proxy" be enough for RBAC ?

**To Reproduce**
1. Upgrade Lens 4.2.5 to 5.1.2

**Expected behavior**
Pod metrics would be visible.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.1.2
- OS: Ubuntu
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
      "error":{
         "kind":"Status",
         "apiVersion":"v1",
         "metadata":{
            
         },
         "status":"Failure",
         "message":"services \"prometheus:9090\" is forbidden: User \"xxxxxx@xxxxxx\" cannot create resource \"services/proxy\" in API group \"\" in the namespace \"monitoring\"",
         "reason":"Forbidden",
         "details":{
            "name":"prometheus:9090",
            "kind":"services"
         },
         "code":403
      },

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
```

**Additional context**

**Comment by Nokel81** [comment]
@jakolehm I cannot find any changes related to the files we apply for setting up Lens metrics. Do you have an idea as to why this might now be required?

**Comment by MisterBlueBear** [comment]
This issue is still present in 5.2.0-latest.20210908

error: [Metrics]: metrics not available {"error":{"name":"StatusCodeError","statusCode":403,"message":"403 - {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"services \\\"prometheus:9090\\\" is forbidden: User \\\"XXX-User-XXX\\\" cannot create resource \\\"services/proxy\\\" in API group \\\"\\\" in the namespace \\\"monitoring\\\"\",\"reason\":\"Forbidden\",

**Comment by cpum** [comment]
Can confirm this issue is still present in 5.2.0-latest.20210908.1

**Comment by Nokel81** [comment]
Are you using the lens prometheus stack or your own?

**Comment by cpum** [comment]
We are using a conventional Prometheus stack, it wasn't set up/configured via Lens.

I'm currently on Lens 5.2.5, where I'm still seeing the issue. Couple of co-workers are still running Lens 4.x, where metrics are displayed properly. Other than the Lens version the setup is identical to mine (using EKS, same cluster, RBAC, same level of authorization, etc.)

**Comment by Nokel81** [comment]
Ah I see, your error is caused by https://github.com/lensapp/lens/pull/2401 which is why we require "create" permissions (I think).

**Comment by MisterBlueBear** [comment]
Relates to #3917
