### ISSUE TITLE
Remove legacy plus sign (+) from component directories

### ISSUE THREAD

**Issue by aleksfront** [lensapp/lens#3481]
For legacy purposes some of the directories inside `/components` are named with `+`. The meaning was originally to indicate components which get opened by `Routes`.

However, this decision creates problems to testing. Jest matcher doesn't understand plus sing in folder names and unable to find any tests there.

```
In /Users/alexfront/Projects/lens
  900 files checked.
  testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x) - 60 matches
  testPathIgnorePatterns: /node_modules/ - 900 matches
  testRegex:  - 0 matches
Pattern: src/renderer/components/+workloads-deployments/deployment-scale-dialog.test.tsx - 0 matches
```

![legacy folders](https://user-images.githubusercontent.com/9607060/126615099-980f0ea0-8c91-47d5-8eb8-baeef2931165.png)

We need to rename all folders to be without `+`.

**Comment by jakolehm** [comment]
@aleksfront does it work if you escape `+` in a pattern match (`\+`).

**Comment by aleksfront** [comment]
Thanks for the solution!

It works if 
1. Test address gets wrapped with quotes.
2. Plus sign gets escaped.

So this command will work:
```
yarn jest "src/renderer/components/\+welcome/__test__/welcome.test.tsx"
```
