### ISSUE TITLE
Unable to select multiple namespaces in latest release.

### ISSUE THREAD

**Issue by matglas** [lensapp/lens#3484]
**Describe the bug**
Working with the latest release (5.1.2-latest.20210719.1) it is not possible anymore to select multiple namespaces in the dropdown.

**To Reproduce**
1. Go to 'Pods'
2. Click on Namespaces dropdown
3. Click a namespace. (dropdown collapses)
4. Click on Namespaces dropdown again.
5. Click another namespace.
6. Result: The previous namespace is removed.

**Expected behavior**
I expect the when I click in step 5 that a second namespace is selected.

**Environment (please complete the following information):**
- Lens Version: 5.1.2-latest.20210719.1
- OS: MacOs
- Installation method: Downloaded through site.

**Comment by vshakirova** [comment]
Hi @matglas . We've changed the select behavior, now please press MetaKey (for mac) for selecting multiple namespaces. It selects only one by default. Let me know if smth wrong.

**Comment by matglas** [comment]
I see. I will check if it works.

**Comment by Nokel81** [comment]
Closing as working as intended.
