### ISSUE TITLE
bug on deleting a cluster

### ISSUE THREAD

**Issue by ngtuna** [lensapp/lens#3500]
**Describe the bug**
Can not remove cluster from lens on macos.

**To Reproduce**
1. Right click in cluster in the left panel.
2. Click on 'Delete'
3. It says `Deleting` forever. Cluster never gone. If I add the cluster again, it will keep disconnected whenever I switch to another cluster.

**Expected behavior**
Cluster is deleted.

**Screenshots**
![Screen Shot 2021-07-23 at 19 26 18](https://user-images.githubusercontent.com/1963463/126781562-a1951ec5-4407-4428-88ab-020b42111281.png)

**Environment (please complete the following information):**
- Lens Version:  5.1.1-latest.20210716.1
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux):

**Comment by Nokel81** [comment]
Thanks for the report, this will be fixed by #3473

**Comment by ngtuna** [comment]
Cool thanks @Nokel81
