### ISSUE TITLE
Terminal does not like Unicode strings with kube_ps1

### ISSUE THREAD

**Issue by dan-slinky-ckpd** [lensapp/lens#351]
**Describe the bug**
I use kube_ps1 with zsh. By default it adds the Helm symbol to the prompt.

```
KUBE_PS1_SYMBOL_DEFAULT=${KUBE_PS1_SYMBOL_DEFAULT:-$'\u2388 '}
```

Lens terminal doesn't like this.

<img width="559" alt="Screenshot 2020-05-07 at 19 00 01" src="https://user-images.githubusercontent.com/62966219/81328531-ffd61080-9094-11ea-8ab5-fa874ada8884.png">

I can fix this by overriding the symbol:

```
KUBE_PS1_SYMBOL_DEFAULT="k"
```

Interestingly I can use the character successfully:

```
KUBE_PS1_SYMBOL_DEFAULT="⎈"
```

<img width="290" alt="Screenshot 2020-05-07 at 19 14 53" src="https://user-images.githubusercontent.com/62966219/81329860-10878600-9097-11ea-9c4d-994dbb35200d.png">

Even more interestingly, I cannot replicate the issue if I run Lens app from the command line, the Terminal does not throw an error and shows the symbol as expected.

```
$ /Applications/Lens.app/Contents/MacOS/Lens
```

**To Reproduce**

Use zsh with kube_ps1

**Expected behavior**
When launching the Lens app from Applications, when using zsh + kube_ps1, it should not throw an error.

- Lens Version: 3.4.0-rc.1
- OSX

**Comment by Nokel81** [comment]
I have also noted that when running the app (not from the command line) pasting in `KUBE_PS1_SYMBOL_DEFAULT="⎈"` to the terminal results in `KUBE_PS1_SYMBOL_DEFAULT="�<008e><0088>"` being displayed. 

So this is definitely not a problem related to `kube_ps1` and everything to do with unicode handling when not running in the terminal. More investigation is required, which I will do.

**Comment by Nokel81** [comment]
Found the problem, the terminal emulator requires the `LANG` environment variable to be set, and probably always including `UTF-8`. To verify this run `export LANG=en_ca.UTF-8` before re-source your zshrc file. I will go about trying to make sure that this gets set if not in a PR.
