### ISSUE TITLE
Some of cluster's icons on the hotbar look like disabled

### ISSUE THREAD

**Issue by devkoriel** [lensapp/lens#3513]
**Describe the bug**
Some of cluster's icons on the hotbar look like disabled.

**To Reproduce**
1. Open the Lens.
2. Add some clusters.
3. Check the hotbar leftside.

**Expected behavior**
All hotbar icons seem right.

**Screenshots**
<img width="123" alt="Screen Shot 2021-07-25 at 6 54 37 PM" src="https://user-images.githubusercontent.com/11952424/126895102-e96ea2ae-af0b-43df-b707-0a7ce2f31f03.png">

**Environment (please complete the following information):**
- Lens Version: 5.1.3-latest.20210722.1
- OS: macOS
- Installation method (e.g. snap or AppImage in Linux): dmg image.

**Logs:**
No logs.

**Additional context**
When I was using Lens version 4.x, there was no problem of showing hotbar icons. However, after upgrading to Lens 5.x, some of them disappeared.

**Comment by Nokel81** [comment]
I don't see any that look disabled, can you elaborate?

**Comment by Nokel81** [comment]
FYI there is a max number of 12 entries per hotbar (you can create more). I believe that this bug has been resolved as https://github.com/lensapp/lens/pull/3379 has now been merged and released as part of 5.2.0
