### ISSUE TITLE
Highlighting text selections in the "Add Cluster from Kubeconfig" view does not show highlighted selection

### ISSUE THREAD

**Issue by trevorlyman** [lensapp/lens#3516]
When adding a new cluster using the "Add Clusters from Kubeconfig", there is an issue with showing highlighted text. Moving the cursor to a line will highlight the entire line with grey. If you then try to highlight a single word on the line the highlight is not visible. The text will still be selected and operations such as deleting the selected text still work as expected.

In this image the IP address should show as highlighted, but it does not.
![image](https://user-images.githubusercontent.com/15242660/127031541-e6bb8ec5-ff52-4319-a268-aaa1bf36d41c.png)

This behavior was observed using version:
Lens: 5.1.3-latest.20210722.1
Electrion: 9.4.4
Chrome: 83.0.4103.122
Node: 12.14.1

**Comment by Nokel81** [comment]
Fixed in 5.2.0 by #2949
