### ISSUE TITLE
Have executables run from the "Directory for binaries" setting

### ISSUE THREAD

**Issue by carlreid** [lensapp/lens#3518]
I'm unsure if this is a bug or enhancement. It's the same as issue #679, with fix #800.

Our corporate policy blocks running unapproved executable. However, as developers, we can install and run applications in a specific folder.

It seems the latest version of Lens still downloads kubectl into a custom folder (but not helm?) then tries to execute binaries from `%OSDRIVE%\USERS\BOB\APPDATA\LOCAL\PROGRAMS\LENS\RESOURCES` and doesn't make use of the `DIRECTORY FOR BINARIES` field. I'd expect that the directory for binaries would be the place they'd execute from too?

So current issue:
- kubectl exe(s) downloaded into `DIRECTORY FOR BINARIES` but are not ran from there.
- Helm exe doesn't use `DIRECTORY FOR BINARIES` when downloading (and is also not then ran from there)

I can work around the kubectl not running problem by the `PATH TO KUBECTL BINARY` but then I lose the flexibility of having the kubectl binary matching the cluster version. I am however, unable to do the same for running the helm executable.

**Comment by Nokel81** [comment]
If you quit and restart lens after setting that setting does the problem persist? (By quitting I mean including the tray icon).

**Comment by Nokel81** [comment]
Note we do not download helm, it comes bundled with it. This would also cause an issue with the fact that we have a custom binary for proxying the kube API.
