### ISSUE TITLE
Cannot delete kubeconfigs and add them again

### ISSUE THREAD

**Issue by msa0311** [lensapp/lens#3523]
This twitter user has issues with deleting and adding clusters again with Lens 5:

https://twitter.com/tomharrisonjr/status/1419868232983400450

**Comment by msa0311** [comment]
We are just removing the "context" from kubeconfig when cluster is deleted through Lens Catalog. We implement it that way to ensure that the content is not entirely lost.

That said it currently works as intended, nevertheless we could reconsider other options.

**Comment by Nokel81** [comment]
I think that this will be resolved by #3473
