### ISSUE TITLE
cronjob trigger 

### ISSUE THREAD

**Issue by aaronsssya** [lensapp/lens#353]
**What would you like to be added**:
Is it possible to manual trigger job in cronjob view. Normally, I have to open a terminal to execute kubectl create job. 

**Why is this needed**:
If we can trigger job more easy. I think that is good for testing.

**Environment you are Lens application on:**
Dev, QA, beta, Stage, Production
- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
K8S, EKS
- Desktop OS: <the OS Lens app runs on in your case>
Mac Catalina

**Comment by JavierHernandezMontes** [comment]
Every Kubernetes manangment tool as Dashboard, Octant, K9s have a trigger button to trigger a cronjob. This feature I think we will be interesting

**Comment by nox-404** [comment]
That would be incredibly useful !

**Comment by trntv** [comment]
missing this feature a lot :-(

**Comment by nox-404** [comment]
Just did a PR for this

You can check it out (w/ Pictures), give me some feedback on that !
