### ISSUE TITLE
Continiously Crashing - undefined kind

### ISSUE THREAD

**Issue by darkn3rd** [lensapp/lens#3549]
**Describe the bug**
I tried to remove selection to a non-existent namespace, and now Lens is completely non-function, continuously crashes.  I deleted the connection and recreated it and it still crashes.

**To Reproduce**
1. provision k8s
2. connect to `~/.kube/test.yaml` w/ Lens
3. deploy apps, such as client namespace, e.g. `pydgraph-client`
4. view pods with client namespace, e.g. `pydgraph-client`, checked
5. delete k8s cluster, quit Lens
6. delete `~/.kube/test.yaml`
6. provision k8s using same `~/.kube/test.yaml` path
7. launch Lens, reconnect
8. Try to view pods, setting is locked to non-existent namespace, e.g. `pydgraph-client`
9. try to select other namespaces (not easy to deselect non-existent namespace)

**Expected behavior**

I expected Lens not to crash with a stack trace and I expected Lens to not get into a non-functional state of continuously crashing.

The Actual Behavior is:

```
TypeError: Cannot read property 'kind' of undefined
    at r.value (http://45c837c4-f8fd-422b-96cb-5ac2d13d547c.localhost:56361/build/Lens.js:2:3775674)
    at http://45c837c4-f8fd-422b-96cb-5ac2d13d547c.localhost:56361/build/Lens.js:2:8681971
    at Array.map (<anonymous>)
    at http://45c837c4-f8fd-422b-96cb-5ac2d13d547c.localhost:56361/build/Lens.js:2:8681939
    at Array.map (<anonymous>)
    at r.value (http://45c837c4-f8fd-422b-96cb-5ac2d13d547c.localhost:56361/build/Lens.js:2:8681883)
    at r.value (http://45c837c4-f8fd-422b-96cb-5ac2d13d547c.localhost:56361/build/Lens.js:2:8687231)
    at ve (http://45c837c4-f8fd-422b-96cb-5ac2d13d547c.localhost:56361/build/Lens.js:2:18448)
    at http://45c837c4-f8fd-422b-96cb-5ac2d13d547c.localhost:56361/build/Lens.js:2:70625
    at ce (http://45c837c4-f8fd-422b-96cb-5ac2d13d547c.localhost:56361/build/Lens.js:2:16554)
```

**Environment (please complete the following information):**
- Lens Version: 4.0.3
- OS: macOS 10.15.2 (19C57)
- Installation method: brew

**Logs:**

* https://gist.github.com/darkn3rd/5c4bd26da36fa37eb35d6582857f96e9

**Kubeconfig:**
KUBECONFIG is autogenerated by Azure CLI.

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://net-test-blog-test-dda134-1b9f9609.hcp.westus2.azmk8s.io:443
  name: net-test
contexts:
- context:
    cluster: net-test
    user: clusterUser_blog-test_net-test
  name: net-test
current-context: net-test
kind: Config
preferences: {}
users:
- name: clusterUser_blog-test_net-test
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
    token: REDACTED```

**Additional context**

Lens is in an unusable state and is no longer functional.

**Comment by Nokel81** [comment]
Does this happen when using 5.1.3?
