### ISSUE TITLE
Question: is there a helm release for the metrics that can be installed via the lens IDE

### ISSUE THREAD

**Issue by mattduguid** [lensapp/lens#3550]
in the lens IDE under cluster settings is an option to manually install "Metrics Stack" and we are keen to automate this using terraform and the "helm_release" resource but cannot locate a helm release for this? there is also a link to the YAML manifests here https://github.com/lensapp/lens/tree/master/extensions/metrics-cluster-feature/resources is it just a case of automating those to meet the same configuration?

**Comment by dominch** [comment]
This is bit misleading, for metrics You need prometheus operator (not metrics-server), just install kube-prometheus-stack 
```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm upgrade
kubectl create ns prometheus
helm install prometheus prometheus-community/kube-prometheus-stack --namespace prometheus
```
that fixed problem for me

**Comment by mattduguid** [comment]
Thanks @dominch that helped push us in right direction 👍

To get this working via terraform for our AKS clusters we were successful using 2 steps,

**step 1 - terraform**

resource "helm_release" "monitoring" {
   atomic = true
   chart = "kube-prometheus-stack"
   name = "kube-prometheus-stack"
   create_namespace = true
   namespace = "lens-metrics"
   repository = "https://prometheus-community.github.io/helm-charts/"
   timeout = 180 
   wait = true 
   set {
     name  = "rbacEnable"
     value = "false"
   }
   depends_on = [
     azurerm_kubernetes_cluster.azure,
   ]
}

**step 2 - change cluster setting in lens IDE**

In the lens IDE we also needed an extra bit provided by @Supesharisuto which was,

_To get metrics to show up in Lens: go to cluster -> settings Under Prometheus drop down choose " Prometheus Operator" NOT "Auto detect"_

![image](https://user-images.githubusercontent.com/7642305/128400845-1c5c4330-b85a-4547-bb3a-627a3056c83e.png)

After that metrics started showing
