### ISSUE TITLE
资源优先级问题

### ISSUE THREAD

**Issue by zhaobei** [lensapp/lens#3551]
使用config 同时绑定了role 和 clusterrole，最终在 lens里显示的是 clusterrole级别的资源而不显示 role级别的资源
![image](https://user-images.githubusercontent.com/55879962/127841532-0dc648b0-f9f3-4dca-bc07-0fdd04f49194.png)

**Comment by zhaobei** [comment]
此处应该对其权限进行取交集并进行展示，并且对集群内的其他helm chart 资源没有赋予其权限则不应该展示。
![image](https://user-images.githubusercontent.com/55879962/127842171-ad1dbb38-dcf9-4357-b311-beb4553be685.png)

**Comment by msa0311** [comment]
Hi @zhaobei thanks for reporting this, is it possible for you to translate your request to english? We tried to figure out what its about but were not able to understand.

**Comment by Nokel81** [comment]
Closing as unanswerable
