### ISSUE TITLE
why could not edit the binary directory path

### ISSUE THREAD

**Issue by jiangxiaoqiang** [lensapp/lens#3568]
**Describe the bug**

I want to edit the kubectl binary path in macOS Big Sur, bit it not editable.

**To Reproduce**

1 open lens in macOS big sur
2 go to preference and kubernetes
3 the directories for binaries could not edit

**Expected behavior**

I could edit the path

**Screenshots**

![image](https://user-images.githubusercontent.com/4521375/128132962-9a881e97-1bbb-4772-800d-fcbcc3c75cad.png)

**Environment (please complete the following information):**
- Lens Version: 5.1.3
- OS: macOS big sur
- Installation method (e.g. snap or AppImage in Linux):

**Comment by nevalla** [comment]
~~So you are not able to type anything into that field?~~ Okay got this reproduced, something is off there.

Seeing this on dev console:
![image](https://user-images.githubusercontent.com/455844/128136549-0ece7579-09cd-4cf0-b48f-a804c4055822.png)

**Comment by Nokel81** [comment]
I believe that warning was fixed by #3497
