### ISSUE TITLE
CRD namespaces cut-off long lists when expanded

### ISSUE THREAD

**Issue by Bonehead5338** [lensapp/lens#358]
**Describe the bug**
If a CRD Group has a lot of CRDs under it, expanding the 'folder' will not show entire list

Able to access the instances via definitions section though

**To Reproduce**
1. Go to Custom Resources
2. Expand a Group with a long list
3. Unable to view items past a certain point

**Expected behavior**
Either entire list in view, or a windowed scrollable section i.e. some method to access all items

**Screenshots**
See attached

**Environment (please complete the following information):**
- Lens Version: 3.4.0
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): Install and upgrades
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
N/A
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
N/A
```

**Additional context**
![2020-05-09 10_15_30-Lens](https://user-images.githubusercontent.com/11580510/81477694-9c57fa00-91de-11ea-8dbc-ef1dc71ad0ec.png)

**Comment by jakolehm** [comment]
@aleksfront @ixrock any ideas how to fix?

**Comment by ixrock** [comment]
Width of the sidebar currently seems to be fixed in CSS. We could extend it by content size probably?
**UPD:** or I actually didn't  get the issue, what does the red arrow on screenshot? This area in sidebar should be scrollable to whole block's height afaik.

**Comment by Bonehead5338** [comment]
> 
> 
> Width of the sidebar currently seems to be fixed in CSS. We could extend it by content size probably?
> **UPD:** or I actually didn't get the issue, what does the red arrow on screenshot? This area in sidebar should be scrollable to whole block's height afaik.

scrolling in that pic would scroll the monitoring line up, and the cutoff with it

**Comment by mverleun** [comment]
Using Lens 4.0.5 I still experience this issue as well. We're using Rancher on our clusters and Rancher creates a lot of CRD's.

When navigating through the CRD's a long list of items is limited in length. In the above shown image the arrow points at a location where only the top half of an entry is displayed which is the 35th entry.

My screen shows the same. The 35th item is shown partially and the other items in the same 'group' are not shown. In total there are 62 items in my list of CRD with names ending in management.cattle.io. This picture tries to illustratie that the group management.cattle.io is shown completely when selecting 'Definitions'.

In the sidebar on the left only the green portion is show with a cut-off point between Nodedrivers and Nodepools. Nodepools is the 35th item in the list. Everything in red is not accessible via the sidebar,
![Lens_-_The_Kubernetes_IDE](https://user-images.githubusercontent.com/11242627/103268769-660cfc00-49b4-11eb-935d-9e890c53382a.png)
