### ISSUE TITLE
No Workloads loaded

### ISSUE THREAD

**Issue by xdeveloper** [lensapp/lens#3586]
Hi!

No Workloads section loaded: 
One of the requests is running too long:
I think that's the root of the problem. 

1. I'm behind the proxy
2. Lens version - latest 5.x
3. OS - Windows 10
4. Only Lens-Setup-4.0.0-rc.2.exe works on my PC

![image](https://user-images.githubusercontent.com/988712/128878281-44d86567-89a2-4a68-b224-8e0f7a06381f.png)

**Comment by xdeveloper** [comment]
![image](https://user-images.githubusercontent.com/988712/128880644-c5ab07a5-b4a0-4c2b-a42f-ab3989d15d15.png)

**Comment by Nokel81** [comment]
That long request is by design, we are watching for changes.

It seems that you have some RBAC rules in place for that cluster, do you have `watch` permissions for any of: pods, deployments, daemonsets, statefulsets, replicasets, jobs, or cronjobs?

**Comment by LeeKevin** [comment]
I'm seeing the same issue

**Comment by Nokel81** [comment]
@LeeKevin can you give an answer for you case to my post above?

**Comment by LeeKevin** [comment]
@Nokel81 I get the following when I run `kubectl get pods -A -n <namespace>`:

```
Error from server (Forbidden): pods is forbidden: User "<email>" cannot list resource "pods" in API group "" at the cluster scope
```

**Comment by LeeKevin** [comment]
Otherwise:

```
 kubectl auth can-i watch pods -n <namespace>
yes
```

**Comment by LeeKevin** [comment]
In my case, the workaround was to manually add my namespace to the cluster settings in Lens.

My organization restricted access for all namespaces--I only have access to one namespace.

thanks @Nokel81 !

**Comment by xdeveloper** [comment]
![image](https://user-images.githubusercontent.com/988712/130463318-8adef573-6093-4add-858e-0107debdfb18.png)
It works! 

Yes. Must set your namespaces directly
