### ISSUE TITLE
Add progress information for update installation as well as update item into the dropdown menu

### ISSUE THREAD

**Issue by europ** [lensapp/lens#3590]
**What would you like to be added**:
1. A new item "Update" into "Help" dropdown menu, where the user can start initialize the update manually if the user has cancelled the on-startup of LENS pop-up option for update.
1. A new view about the update installation progress (e.g. progress bar) as well as a notification view (e.g. pop-up) about the update installation result (e.g. <version> has been successfully installed).

**Why is this needed**:
1. The user must force the start of LENS application if he wants to update, there is no option to do it later while using the application itself.
1. The user is not aware of the update installation progress / result.

**Comment by Nokel81** [comment]
FYI you should be asked the next day if you want to upgrade again. Is that not working for you?

**Comment by europ** [comment]
@Nokel81 it works.

**Comment by Nokel81** [comment]
Also you can use the tray icon to recheck if there is an update. Though I will leave this issue open as I agree some sort of progress bar would be good.

**Comment by europ** [comment]
I think that you should consider adding an "Update" item (button) into this dropdown menu (see image), which would trigger the update process as it is usually done in almost every other application (the user has the ability to start the update process instead of waiting for the update prompt on next day).

![image](https://user-images.githubusercontent.com/22373707/129794478-9232c76b-c673-4ce6-980b-06213501ac0c.png)

Yes, it would be great to have a progress bar.

**Comment by Nokel81** [comment]
I see that it is somewhat common on windows for that to be the case and macOS seems to do it under the "$ApplicationName" menu. In either case the tray icon menu works today.

**Comment by europ** [comment]
Yes, the tray icon menu does have the "update" button.
![image](https://user-images.githubusercontent.com/22373707/129798241-5661797e-64c5-44b0-a12a-9f75248e34d8.png)

**Comment by Nokel81** [comment]
Closing this in favour of https://github.com/lensapp/lens/issues/5059 and #4948
