### ISSUE TITLE
Unable to modify manifests

### ISSUE THREAD

**Issue by jvandervelden** [lensapp/lens#36]
I am trying to update manifests within my cluster but I am getting the following error:

"TypeError: e.map is not a function"

Steps to reproduce:

1 - Open a resource within a cluster
2 - Click the edit icon to bring up the manifest editor
3 - Edit the manifest (Optional also fails when un-altered)
4 - Click save or save & close

Environment:

Cluster Type: Azure Kubernetes System (AKS)
Nodes: Linux aks-agentpool-XXXX 4.15.0-1060-azure #65-Ubuntu SMP Wed Sep 18 08:55:51 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Client OS: Windows 10
Manifest example:

apiVersion: v1
kind: Pod
metadata:
  name: kube-state-metrics-54558ff88b-rfv2z
  generateName: kube-state-metrics-54558ff88b-
  namespace: lens-metrics
  selfLink: /api/v1/namespaces/lens-metrics/pods/kube-state-metrics-54558ff88b-rfv2z
  uid: 9ce60a05-e5dc-11e9-bb7d-2e2df2e8421e
  resourceVersion: '49804274'
  creationTimestamp: '2019-10-03T12:52:09Z'
  labels:
    name: kube-state-metrics
    pod-template-hash: '1011499446'
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: kube-state-metrics-54558ff88b
      uid: 9ce28372-e5dc-11e9-bb7d-2e2df2e8421e
      controller: true
      blockOwnerDeletion: true
spec:
  volumes:
    - name: kube-state-metrics-token-4r7z5
      secret:
        secretName: kube-state-metrics-token-4r7z5
        defaultMode: 420
  containers:
    - name: kube-state-metrics
      image: 'registry.pharos.sh/kontenapharos/prometheus-kube-state-metrics:v1.6.0'
      ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
      env:
        - name: KUBERNETES_PORT_443_TCP_ADDR
          value: aks-caf-7af47eaf.hcp.eastus2.azmk8s.io
        - name: KUBERNETES_PORT
          value: 'tcp://aks-caf-7af47eaf.hcp.eastus2.azmk8s.io:443'
        - name: KUBERNETES_PORT_443_TCP
          value: 'tcp://aks-caf-7af47eaf.hcp.eastus2.azmk8s.io:443'
        - name: KUBERNETES_SERVICE_HOST
          value: aks-caf-7af47eaf.hcp.eastus2.azmk8s.io
      resources:
        limits:
          cpu: 200m
          memory: 150Mi
        requests:
          cpu: 10m
          memory: 150Mi
      volumeMounts:
        - name: kube-state-metrics-token-4r7z5
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 5
        timeoutSeconds: 5
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/os: linux
  serviceAccountName: kube-state-metrics
  serviceAccount: kube-state-metrics
  securityContext: {}
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
status:
  phase: Pending
  conditions:
    - type: PodScheduled
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2019-10-03T12:52:09Z'
      reason: Unschedulable
      message: '0/8 nodes are available: 8 node(s) didn''t match node selector.'
  qosClass: Burstable

But all attempts give the same error.

**Comment by nevalla** [comment]
Just a side note that you shouldn't be able to edit pod if it's created by deployment, but still you should see different error message.

The editor is using similar mechanism that is used in embedded terminal under the hood. Are you able to execute `kubectl` commands in embedded terminal?

**Comment by jvandervelden** [comment]
Yes I can do kubectl commands in the terminal. 

I tried editing the deployment of the pod I was editing with the same result.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: lens-metrics
  selfLink: /apis/apps/v1/namespaces/lens-metrics/deployments/kube-state-metrics
  uid: 9ce1283b-e5dc-11e9-bb7d-2e2df2e8421e
  resourceVersion: '49805678'
  generation: 1
  creationTimestamp: '2019-10-03T12:52:09Z'
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"kube-state-metrics","namespace":"lens-metrics"},"spec":{"replicas":1,"selector":{"matchLabels":{"name":"kube-state-metrics"}},"template":{"metadata":{"labels":{"name":"kube-state-metrics"}},"spec":{"containers":[{"image":"registry.pharos.sh/kontenapharos/prometheus-kube-state-metrics:v1.6.0","name":"kube-state-metrics","ports":[{"containerPort":8080,"name":"metrics"}],"readinessProbe":{"httpGet":{"path":"/healthz","port":8080},"initialDelaySeconds":5,"timeoutSeconds":5},"resources":{"limits":{"cpu":"200m","memory":"150Mi"},"requests":{"cpu":"10m","memory":"150Mi"}}}],"nodeSelector":{"kubernetes.io/os":"linux"},"serviceAccountName":"kube-state-metrics"}}}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kube-state-metrics
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-state-metrics
    spec:
      containers:
        - name: kube-state-metrics
          image: >-
            registry.pharos.sh/kontenapharos/prometheus-kube-state-metrics:v1.6.0
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 150Mi
            requests:
              cpu: 10m
              memory: 150Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: kube-state-metrics
      serviceAccount: kube-state-metrics
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  unavailableReplicas: 1
  conditions:
    - type: Available
      status: 'False'
      lastUpdateTime: '2019-10-03T12:52:09Z'
      lastTransitionTime: '2019-10-03T12:52:09Z'
      reason: MinimumReplicasUnavailable
      message: Deployment does not have minimum availability.
    - type: Progressing
      status: 'False'
      lastUpdateTime: '2019-10-03T13:02:10Z'
      lastTransitionTime: '2019-10-03T13:02:10Z'
      reason: ProgressDeadlineExceeded
      message: ReplicaSet "kube-state-metrics-54558ff88b" has timed out progressing.

```

**Comment by mrfelek** [comment]
Same here.
I clicked Create resource and paste

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs10
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nas.home.lan
    path: "/mnt/GitLab"
```

And I get TypeError: e.map is not a function
Same config works via kubectl apply -f pv.yaml

**Comment by nevalla** [comment]
Trying to re-produce this. Please could you tell also Kubernetes version.

**Comment by jvandervelden** [comment]
It was happening in the 2 clusters I tried; 1.13.10 and 1.11.3

**Comment by nevalla** [comment]
I was able to re-produce this on Windows. Fix will be included in the next patch release.

**Comment by jvandervelden** [comment]
Thanks, installed 2.0.9 this morning and it's working now 👍

**Comment by mrfelek** [comment]
Works like a charm.
Thank you!
