### ISSUE TITLE
container cpu/memory Requests/limits missing

### ISSUE THREAD

**Issue by schmurfy** [lensapp/lens#3611]
**Describe the bug**
Only Usage is shown.

**To Reproduce**
install prometheus + kube-metrics, open lens

**Expected behavior**
Requests/limits to be shown

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.1.3
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): dmg

**Additional context**
When exploring the metrics produced for `kube-state-metrics` I see a label `exported_pod` which contains the name of the pod for which the requests/limits are reported but when looking at the queries built by lens I see:

```go
case "cpuRequests":
            return `sum(kube_pod_container_resource_requests{pod=~"${opts.pods}",resource="cpu",namespace="${opts.namespace}"}) by (${opts.selector})`;
```

I tried to change the code to:
```go
case "cpuRequests":
            return `sum(kube_pod_container_resource_requests{exported_pod=~"${opts.pods}",resource="cpu",namespace="${opts.namespace}"}) by (${opts.selector})`;
```

and the graph are now shown but I don't get how the original can even work since `pod` is the name of the pod which emitted the metrics, in the case of `kube-metrics` it will never be the one you want unless you are looking at its own pod which indeed had the `requests` / `limits` graph showing even without the change.

I can open a pull-request for it if that's the right move.

**Comment by Nokel81** [comment]
From what source did you install prometheus? We do not see the `exported_pod` field when using our own metrics stack.

**Comment by schmurfy** [comment]
We install our own stack a bit like what lens do, after a bit more digging I found the culprit: `honorLabels`, it was'nt set when reading metrics from `kube-state-metrics`
