### ISSUE TITLE
Add support for RuntimeClass

### ISSUE THREAD

**Issue by matlegit** [lensapp/lens#3614]
**What would you like to be added**:
Hi there, I'm a big fan of Lens!

I couldn't seem to find a way in Lens to view my `RuntimeClass`es
https://kubernetes.io/blog/2020/12/08/kubernetes-1-20-release-announcement/

The proposed enhancement would be to add support for `RuntimeClass`, thanks!

**Why is this needed**:
Kubernetes `RuntimeClass` is now stable as of 1.20
https://kubernetes.io/docs/concepts/containers/runtime-class/

**Environment your Lens application is on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
  - AWS EKS
- Desktop OS: <the OS Lens app runs on in your case>
  - Mac OS
  
```
Lens: 5.1.3-latest.20210722.1
Electron: 9.4.4
Chrome: 83.0.4103.122
Node: 12.14.1
© 2021 Mirantis, Inc.
```

**Comment by Nokel81** [comment]
This was fixed by #6294
