### ISSUE TITLE
Provide access to Lens' logs

### ISSUE THREAD

**Issue by Nuru** [lensapp/lens#362]
**What would you like to be added**:
Easy access to Lens' logs, including the ability to adjust verbosity.

**Why is this needed**:
Lots of issues come up where looking at the logs would presumably help diagnose and fix the problem, but there is no easy way to look at the logs from within Lens, or to find the log file (if there even is one).

**Environment you are using Lens application on:**

- Desktop OS: macOS Catalina

**Comment by nevalla** [comment]
Lens will output logs under `~/Library/logs/Lens` directory now.
