### ISSUE TITLE
Convert unix time stamp to human readable format 

### ISSUE THREAD

**Issue by vivanov83** [lensapp/lens#3633]
**What would you like to be added**:
Convert unix time stamp to human-readable format when node has some taints (in this case, PreferNoSchedule)

**Why is this needed**:
Humans are not so good in calculation of timestamps

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS]
- Desktop OS: MacOS 11.5.1
<img width="680" alt="image" src="https://user-images.githubusercontent.com/62815076/129889290-fc8fa678-d20f-444a-a410-cc7b835a092b.png">

**Comment by Nokel81** [comment]
The value of taints are blackbox strings so this is not possible in general, I tried to do some searching but couldn't find anything super definite about the key of `DeletionCandidateOfClusterAutoscaler` always has a string value that represents a unix timestamp

**Comment by Nokel81** [comment]
We have changed the format of the taints display (in https://github.com/lensapp/lens/pull/3646) to be `key=value:effect` (which more closely matches `kubectl`). This cannot be done in the general case as all integers are unix timestamps but not all are supposed to be. Hopefully now that the value is more easily copyable doing the conversion yourself where necessarily will be easier.
