### ISSUE TITLE
Allow extensions to create new preferences Tabs

### ISSUE THREAD

**Issue by Nokel81** [lensapp/lens#3644]
**What would you like to be added**:
The ability for extensions to add settings to any preferences tab and for extensions to register new preferences tabs

**Why is this needed**:
Currently extensions can only add items into the "Telemetry" (opt in) and the "Extensions" (default) tabs. This is unnecessarily limiting and bad UX, especially if there are lots of extensions.

Furthermore, it might be a good idea to have the order of those tabs be static (maybe sorted alphabetically).

**Comment by Nokel81** [comment]
@jakolehm @aleksfront Thoughts?

**Comment by DmitriyNoa** [comment]
@Nokel81 Is this still relevant? I see it's pretty old.
If yes - can someone please provide more details on this? I would like to take it.

**Comment by Nokel81** [comment]
Yes I think is is relevant. However, it is blocked on https://github.com/lensapp/lens/pull/4651 first

**Comment by Nokel81** [comment]
This was completed by #5284
