### ISSUE TITLE
Use specific namespace

### ISSUE THREAD

**Issue by 4got10dev** [lensapp/lens#365]
Hello,

I faced next problem: I work with multiple EKS clusters with login managed by Okta. For some of clusters we have specific role which have access only to **default** namespace and **lens** shows: 
> events is forbidden: User "dev" cannot list resource "events" in API group "" at the cluster scope

Is it possible to configure **lens** to use specific namespace instead of _All namespaces_?

Thanks in advance

**Comment by 4got10dev** [comment]
![image](https://user-images.githubusercontent.com/22197145/81716806-1b1c9380-947a-11ea-9fa1-5ade73ce1427.png)

**Comment by shinebayar-g** [comment]
See: https://github.com/lensapp/lens/issues/107

**Comment by jakolehm** [comment]
#366 will probably solve this.

**Comment by Nokel81** [comment]
Fixed by in 4.1
