### ISSUE TITLE
Using Metrics in Lens without Prometheus Operator

### ISSUE THREAD

**Issue by mstoetzer** [lensapp/lens#3654]
https://github.com/lensapp/lens/blob/33c405bdcf86ff755069ce50a21efbf10985810e/troubleshooting/custom-prometheus.md describes the scrape configuration for Prometheus Operator in conjunction with ServiceMonitors.

Could we extend the docs with the scrape configuration when using a plain Prometheus installation?

Has anybody got the scrape configuration right?

**Comment by Nokel81** [comment]
These are a sample of the queries that we use (https://github.com/lensapp/lens/blob/master/src/main/prometheus/lens.ts) are you able to align your prometheus with them?

**Comment by mstoetzer** [comment]
Hi Nokel81, thanks for the hint! I have not been successful so far. I tried all the queries from lens.ts file and all returned valid results in the Prometheus GUI. But Lens is somehow not able to query them.

**Comment by mstoetzer** [comment]
I'm using metrics-server instead of prometheus-adapter, could this be the cause?

see #1865

**Comment by Nokel81** [comment]
Yes that would be it then. I assume that metrics server doesn't have the same API as Prometheus so unless there is some form of an adapter that consumes metrics-server and hosts a prometheus API then I don't think it is possible yet.
