### ISSUE TITLE
AWS Command not found

### ISSUE THREAD

**Issue by Vanheelsing** [lensapp/lens#3683]
I have aws cli on my env path of windows and under CMD i can do aws no problem, but lens (on latest version) fails to add cluster:
ExecValidationNotFoundError: User Exec command "aws" not found on host. Please ensure binary is found in PATH or use absolute path to binary in Kubeconfig

i have tried given the full path on command argument and still nothing:
ExecValidationNotFoundError: User Exec command "C:\Program Files\Amazon\AWSCLIV2\aws.exe" not found on host.

i have tested with beta vrsion of lens and i still can't get it to find aws

**Comment by Nokel81** [comment]
Duplicate of #2079
