### ISSUE TITLE
Lens uses wrong verb (update instead of patch) to scale deployments

### ISSUE THREAD

**Issue by alert101-gof** [lensapp/lens#3721]
**Describe the bug**
Lens uses wrong verb (update) to scale deployments, according to spec the verb used should be 'patch'.

**To Reproduce**
Create a user with the following permissions
```
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["patch"]
```
Try scaling a deployment with Lens and it fails with the following error:
```
Lens: deployments.apps "myDeployment" is forbidden: User "myUser" cannot update resource "deployments/scale" in API group "apps" in the namespace "myNamespace"
```

**Expected behavior**
Lens should be able to scale the deployment. According to the documentation scaling should use the patch verb while Lens seems to use update.

**Environment (please complete the following information):**
- Lens Version: v5.1.3-latest.20210722.1
- OS: Windows 10 (19043.1165)
- Installation method (e.g. snap or AppImage in Linux): .EXE

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**
Related issue: https://github.com/lensapp/lens/issues/2553

**Comment by nevalla** [comment]
Kubernetes API allows to use both verbs, but since `kubectl` uses patch and people are used to create rbac rules based on that, probably we should switch to use `patch` too.
