### ISSUE TITLE
Full support for ReplicaSets

### ISSUE THREAD

**Issue by Nuru** [lensapp/lens#373]
**What would you like to be added**:

List ReplicaSets under Workloads, generally provide all the features for ReplicaSets you do for StatefulSets

**Why is this needed**:

ReplicaSets are common intermediaries between Deployments and Pods.

**Environment you are Lens application on:**

3.4.0

- Kubernetes distribution: 1.15.11
- Desktop OS: macOS Catalina

**Comment by jakolehm** [comment]
@Nuru ReplicaSets are visible under Deployment details (as Deploy Revisions).

**Comment by Nuru** [comment]
In the Side Bar, under Workloads, there are (among other things)
- Deployments
- DaemonSets
- StatefulSets

What is the rationale for not including ReplicaSets in that list?

**Comment by ChillarAnand** [comment]
@jakolehm It is un-intuitive & hard to find `rs`. Won't it be better to add it under workloads?

**Comment by brechtvhb** [comment]
It would also be nice to see the aggregated logs of all pods in a replica set, as you can do in kubernetes dashboard.

**Comment by iamandymcinnes** [comment]
Where are replicasets hiding? I can see them on the demos but not when I look against my clusters workloads in lens?

**Comment by andrein** [comment]
> @Nuru ReplicaSets are visible under Deployment details (as Deploy Revisions).

Hi @jakolehm, we're deploying our applications as ReplicaSets through Spinnaker, and this workaround doesn't work for us, since we don't have any Deployments associated with them. A separate tab for ReplicaSets (similar to the one for deployments) would make our lives a lot easier.

**Comment by bttger** [comment]
I would also prefer to see the ReplicaSets directly under Workloads. This would be consistent with the K8s documentation and the K8s dashboard. I didn't even know until now that you can also display the ReplicaSets via _Deploy Revisions_ and think this is unintuitive since the ReplicaSet is a standalone resource, not necessarily connected with a Deployment.

**Comment by vshakirova** [comment]
Hi, lens team. I also want this enhancement and I'd like to try to implement it if you don't have objections 🙂
