### ISSUE TITLE
jobs.batch is forbidden, cannot list resource "jobs"

### ISSUE THREAD

**Issue by aaronsssya** [lensapp/lens#374]
**Describe the bug**
jobs.batch is forbidden, cannot list resource "jobs".
We delegate K8S namespace permission to users. In 3.3.1 or earlier version, it is working good. However, when user upgrade the 3.4.0. They are encountering jobs.batch is forbidden, cannot list resource "jobs".

**To Reproduce**
1. Go to 'Workloads'
2. Click on 'jobs' or 'cronjobs'
3. See error

**Expected behavior**
same as 3.3.1

**Screenshots**
<img width="1201" alt="Screen Shot 2020-05-14 at 10 19 17 AM" src="https://user-images.githubusercontent.com/30425926/81885217-73fc4100-95cc-11ea-889b-635f4097c8d4.png">

**Environment (please complete the following information):**
- Lens Version: 3.4.0
- OS: OSX, Windows 10

**Comment by jakolehm** [comment]
That error comes directly from Kubernetes API. Did you verify that it's still working on Lens 3.3.1?

**Comment by aaronsssya** [comment]
in 3.3.1, it is working.

**Comment by aaronsssya** [comment]
fixed. Thanks
