### ISSUE TITLE
Avoid spurious error messages when events are not available

### ISSUE THREAD

**Issue by jflamy** [lensapp/lens#375]
**What would you like to be added**:
A way to disable metrics/events when unavailable, to avoid spurious error messages

**Why is this needed**:
Spurious messages on some shared clusters where it is not possible to get events
For example, on kubesail.com
![image](https://user-images.githubusercontent.com/678663/81964660-e416c100-95e4-11ea-92a0-c634af89ab29.png)

**Environment you are Lens application on:**

- Kubernetes distribution: Kubesail
- Desktop OS: Docker Desktop with WSL2 Backend

**Comment by jakolehm** [comment]
Fixed in #366
