### ISSUE TITLE
Hot Bar Pin Item next to Cluster Name in catalog view

### ISSUE THREAD

**Issue by msa0311** [lensapp/lens#3754]
Show the Pin icon next to the cluster name (and catalog) to allow users to pin it to the hotbar easily!

**Comment by msa0311** [comment]
@aleksfront sorry, I guess the description was not very clear... my fault! I thought this to be added next to name / icon on left hand side menu. 

next to minikube:
![image](https://user-images.githubusercontent.com/26629812/133432415-f9a19739-3c5e-40b7-93d8-c4de09786d41.png)

wdyt?

**Comment by msa0311** [comment]
But I think we can keep it on the list as well! That was anyway already discussed with Miska afair...

**Comment by aleksfront** [comment]
Yes, it can be pulled as separated features.

**Comment by msa0311** [comment]
created new issue for this:https://github.com/lensapp/lens/issues/3811
