### ISSUE TITLE
Terminal shell is taking a long time to complete startup

### ISSUE THREAD

**Issue by systemmonkey42** [lensapp/lens#3757]
**Describe the bug**
I regularly see the message `Terminal shell is taking a long time to complete startup` followed by a suggestion to check my .rc. file.

How do I diagnose what is causing the slow startup?

Thanks.

**To Reproduce**
1. Go to 'nodes' view
2. Click on a node and select an action (drain or cordon).
3. Dismiss 'are you sure' prompt
4. Terminal appears sitting on the 'PS C:\Users\[username]' prompt.
5. Wait 5 seconds
6. Blue popup containing the above message appears
7. Requested command executes in the terminal window.

**Expected behavior**

Skip step 5. 

Note that on other screens (like connecting to a POD shell) there is no wait.

**Screenshots**
![3](https://user-images.githubusercontent.com/2985620/132604917-ac772f01-9401-4e58-a2f1-145e877325b2.png)

**Environment (please complete the following information):**
- Lens Version: 5.2.0
- OS: Windows 10 x64
- Installation method: Lens Setup 5.2.0-latest.20210908.1.exe

Note, 5.1.5 has the same issue.  4.x never had this issue.  Unfortunately I had no reason to try any 5.x betas

**Comment by Nokel81** [comment]
How are you starting Lens? Are you running it from WSL?

**Comment by systemmonkey42** [comment]
I don't have WSL or Windows Terminal installed.  I'm just using the Windows x64 build.

**Comment by Nokel81** [comment]
Ah now I see your problem more clearly. PR to fix this should be up shortly
