### ISSUE TITLE
Specify Port Forwarding's Port

### ISSUE THREAD

**Issue by sherifabdlnaby** [lensapp/lens#3768]
**What would you like to be added**:

When port forwarding to a container, I want to specify the client local port.

**Why is this needed**:

Used for debugging and connecting to Databases, and any TCP services, it is inconvinent having to configure my tool to whatever the random port Lens chooses **every time**.

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...] EKS ( but this is applicable to any )
- Desktop OS: ( Mac, & Linux )

**Comment by Nokel81** [comment]
Thanks for reporting this, however, we already have a request for this. https://github.com/lensapp/lens/issues/2340
