### ISSUE TITLE
Js error on every close 

### ISSUE THREAD

**Issue by mehmetcakmaz** [lensapp/lens#377]
**Describe the bug**
I got a js error. Every close on app

**To Reproduce**
1. Open Lens
2. Use it for a while
3. Close to app

**Screenshots**
![error](https://user-images.githubusercontent.com/10825597/82037095-5d2c1c00-96aa-11ea-9358-a208a333ccf3.png)

**Environment (please complete the following information):**
- Lens Version: 3.3.1
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux): exe

**Comment by Nuru** [comment]
Seems like a duplicate of #262 and #376 but why seeming to show up more frequently now? 

In any case, upgrade to 3.4.0 might help.

**Comment by mehmetcakmaz** [comment]
Every close, actually.

I updated now. Let me check few times

**Comment by mehmetcakmaz** [comment]
Hi again,
Unfortunately nothing changed. I faced the error for first use in version 3.4.0

**Comment by andyliddle** [comment]
We are also seeing this on every version for a while.  it happens every time the application is closed.

**Comment by mehmetcakmaz** [comment]
Unfortunately. I use the application less, because of this error.

**Comment by alex-hempel** [comment]
I have the same issue with 3.4.0 on Windows. Saw it with previous versions as well.
