### ISSUE TITLE
Super Slow UI on 5.2.*

### ISSUE THREAD

**Issue by maxUo** [lensapp/lens#3773]
**Describe the bug**
After auto-updating to 5.2, my Lens installation became laggy and almost impossible to use, opening absolutely any tab leads to 10-20 second lags and brakes on the UI. I even reinstalled lens.dmg for intel from the official website.

**To Reproduce**
1. Click on pods (5k+)
2. Click on deployments (8k+)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/20925019/132883629-15284286-0dd3-4838-a24d-cf767a68d152.png)

**Environment (please complete the following information):**
- Lens Version: 5.2
- OS: OSX 
- Installation method: .dmg from official site

**Comment by jim-docker** [comment]
Can you provide logs from when it is laggy? From the Lens main menu: **View** -> **Toggle Developer Tools**, and open the Console tab.

Presumably this only happens for a cluster with a large number of pods or other resources?

**Comment by Delorien84** [comment]
Hello, I have also notice slow down of UI, sometimes it even freeze. Lens consume a lot of CPU when switching between Pods / Deployments view. I have two cluster one with 15 nodes and cca 400 pods, seconds with 15 nodes and cca 900 pods.

**Comment by darrenfurr** [comment]
I am seeing the same issue. macOS Big Sur 11.5.2, Lens 5.2-latest.20210908.1...
![Screen Shot 2021-09-15 at 8 46 38 AM](https://user-images.githubusercontent.com/133894/133445216-bfbac986-07ed-49b1-a9c3-082d04bee44b.png)

**Comment by andyast** [comment]
I have seen this behavior as well.  It will just plan hang.  Depending on load we are talking 19 Nodes and around 350 Pods.  The issue seems most pronounced when searching/filtering.

![image](https://user-images.githubusercontent.com/527465/133445890-51b87f74-77e4-4409-8f7e-0db6ac07b2a8.png)

It started happening with the latest update.
![image](https://user-images.githubusercontent.com/527465/133446528-8a90a10f-bb7c-48ae-8739-e7a87835289c.png)


<img width="1159" alt="image" src="https://user-images.githubusercontent.com/527465/133447649-6319ebf6-6550-4de3-86ec-5d9159325983.png">

**Comment by jim-docker** [comment]
Are these local clusters (i.e. clusters that lens discovers by sync'ing your local kubeconfig), or clusters reached through Lens Spaces?

**Comment by andyast** [comment]
Local.  The cluster is AWS EKS.  Other teammates (in other locations) have the same issue so we have eliminated a internet connectivity issue.

**Comment by DanTulovsky** [comment]
Local as well, but mine are in GCP.  Definitely started with the latest upgrade.

**Comment by dobl1** [comment]
Hello, On W10 I have like crazy RAM usage (not even connected to a cluster)
![image](https://user-images.githubusercontent.com/9740002/133744445-66d9082f-0ea9-4799-9726-fe102cafe043.png)

Is it possible to have a download link for previous version (5.1.3 for example) ?

**Comment by darrenfurr** [comment]
Same issue in 5.2.2...
![Screen Shot 2021-09-17 at 6 54 51 AM](https://user-images.githubusercontent.com/133894/133778609-e0886162-27e4-4d67-994e-4270376e11eb.png)

This is while searching for a deployment...
![Screen Shot 2021-09-17 at 6 53 27 AM](https://user-images.githubusercontent.com/133894/133778646-e603e980-97ab-4424-9ffa-922804313f6c.png)

**Comment by Delorien84** [comment]
When I compile Lens by my own (running `make dev`), it works like charm, without any freeze or CPU spike.

**Comment by jim-docker** [comment]
Is anyone experiencing this on macOS Catalina?

**Comment by maxUo** [comment]
> Can you provide logs from when it is laggy? From the Lens main menu: **View** -> **Toggle Developer Tools**, and open the Console tab.
> 
> Presumably this only happens for a cluster with a large number of pods or other resources?

1) I'm sorry, but I can't provide the logs in their pure form.
2) In my clusters, there are from 5000 to 18000+ pods and 100+ nodes in each. But the most interesting thing is that in version 4.* everything worked perfectly.

**Comment by alekc** [comment]
For anyone looking for old binaries (at least for mac), see this historical https://github.com/Homebrew/homebrew-cask/commits/0ab6f251d96b12c40b281f69f4deb02e728977e0/Casks/lens.rb 

I am affected as well on Big Sur, generally speaking app seems to be very sluggish and not registering clicks 
I have rolled back for now to 5.1.3, hopefully it will solve it for now. 

p.s. in my case we are talking about small cluster, 4 nodes 93 pods

**Comment by ahousseini** [comment]
I had the same issue and it turned out my Pi-hole was blocking a lot. After disabling all Telemetry settings the speed is like before.

Hope this helps someone.

**Comment by alekc** [comment]
@ahousseini Thx, disabling telemetry did speed up ui by a lot (at least on 5.0.0)

**Comment by jim-docker** [comment]
@maxUo Can you try Lens 5.2.4? We fixed an issue which impacted performance noticed on windows. The problem we fixed could have impacted macOS users too, though I was not able to reproduce your issue to confirm.

**Comment by benblack86** [comment]
Just upgraded to 5.2.4 from 4 and ran into this issue.

**Comment by maxUo** [comment]
> @maxUo Can you try Lens 5.2.4? We fixed an issue which impacted performance noticed on windows. The problem we fixed could have impacted macOS users too, though I was not able to reproduce your issue to confirm.

After the upgrade to this version (5.2.4), it got a little better, but there are still strong drawdowns compared to the last 4.x major version.

**Comment by maxUo** [comment]
https://github.com/lensapp/lens/releases/tag/v4.2.0 It's the only thing that works for me.

**Comment by alekc** [comment]
Upgraded back to the 5.2.4

Slowness (and I mean for example the lack of highlighting on mouseover) by disabling completely all telemetry in settings. 

I am behind the pihole as well so that might be influencing the issue (by blocking telemetry dns), so potentially that would be one direction to investigate (in case there is an issue in solving dns just disable it?)

**Comment by Nokel81** [comment]
@maxUo what do you mean by drawdowns? Do you mean drawbacks? Are they performance related or do you not like some of the other changes that have been made?

**Comment by Nokel81** [comment]
@alekc I am confused with your comment, are you saying that even on 5.2.4 you are experiencing UI slowness unless you turn off telemetry? And by the second comment, should I take you to mean that you are behind a proxy?

**Comment by andyast** [comment]
I can also confirm that on a Mac 5.2.4 is not better than previous versions.

**Comment by alekc** [comment]
@Nokel81 yes, exactly that. 

With 5.2.4, telemetry on, I've been experiencing the slowness on UI (note, not the slowness on getting the data, but generally registering clicks, mouse movements, etc).  

With telemetry off, ui was snappy and working fine (maybe some slowness in getting the actual data, but nothing major).  Pretty much the same as reported by @ahousseini 

Just for the sake of test: I've now reenabled the telemetry, and I am getting the slow UI again. 

I am behind pihole dns server as well, and as consequence, some dns records are blocked from resolving (probably it might be a scenario in some corporate environments as well if they are behind some proxy). 

Once I've disabled pihole, it looks like it's working even with telemetry on (at least for the past 5 min), so it suggests that it might be the case of telemetry trying to perform some actions and blocking the main ui thread. 

@andyast could you try to disable telemetry as well (Catalog->preferences->telemetry) and see if that fix the issue (after the app restart)?

**Comment by DanTulovsky** [comment]
fwiw, I have telemetry disabled, but it's still slow.

**Comment by andyast** [comment]
Tried disabling telemetry and it seemed to help.... some.  Still not a quick as the last 4.X version.

**Comment by darrenfurr** [comment]
After this latest release being completely unusable. I downgraded to 4.2.0 thanks to this comment:
https://github.com/lensapp/lens/issues/3773#issuecomment-929701908

Performance is back to where I expect it...UI is responsive, doesn't lag at all

**Comment by smartpierre** [comment]
My Setup:
MacOS Big Sur on 2021 MacBookPro
Lens IDE 5.25

Clusters: 
mix of EKS and non-EKS, up to 50 nodes/2k pods

Experienced a very slow Lens for the past weeks, **I just disabled telemetry in my Preferences and this is MUCH better.** 

However, it feels a bit slower than 6 months ago when I started to use Lens (our clusters are the same though).

**Comment by rlex** [comment]
Same issues. Thought my cluster was slow, but checked with k9s and everything was super fast. Downloaded 4.2.0 and it works fast too. 5.2.x, on the other side, often fails to render logs, or monitoring data, or anything, requiring CMR-R to reload interface or sometimes even process restart.

**Comment by jakolehm** [comment]
This might be caused by Sentry integration. I also see laggy UI on official Lens IDE builds but not when I do a development build.

**Comment by jim-docker** [comment]
@maxUo can you try Lens v5.2.6? It has some performance fixes.
