### ISSUE TITLE
High CPU usage on 5.2 

### ISSUE THREAD

**Issue by dominch** [lensapp/lens#3777]
**Describe the bug**
After upgrade to recent version lens started to use cpu very intense. It takes about one full core and quickly makes fan loud. I can't see that cpu usage is even higher when I'm connected to some cluster and running some consoles there. It's about 40% of cpu. When it's completely idle (disconnected from everything on welcome screen) it's about 20%.

**To Reproduce**
Nothing special - just running lens on windows 10. 

**Expected behavior**
It should not eat so much CPU for sure. 

**Screenshots**
This is when it's completely idle on start screen: 
![image](https://user-images.githubusercontent.com/10815109/132912003-28559616-bdb9-4640-aaea-13265186b832.png)

When it's connected and used normally it's much worse: 
![image](https://user-images.githubusercontent.com/10815109/132912174-0ea5c968-3456-4c0b-bd99-e9c3dea1ab18.png)

**Environment (please complete the following information):**
- Lens Version: latest - 5.2 
- Windows 10 
- Installed via installer from homepage

**Additional context**
This happened soon after update, I see it's using GPU but same thing happens in chrome where hardware accelleration is disabled. I don't know how to open "chrome://gpu" panel information, but this may be good point to start. 

Please take a look at performane console with lens running and closed (last few seconds) 
![image](https://user-images.githubusercontent.com/10815109/132912668-2be377d1-b79a-4356-9da7-3a26298d6d4c.png)

**Comment by jmcarranza** [comment]
Hi, i had the same problem and succeeded in reducing the high CPU consumption by disabling these options.
![image](https://user-images.githubusercontent.com/9244484/133268911-0bdea3a7-264a-4c1a-9981-b59fc0784c6c.png)

**Comment by dominch** [comment]
@jmcarranza I already disabled first two options, but this is not that
issue. After lens restart I see that it's working ok without high cpu
usage. Later it eat more and more CPU resulting in something like in
screens. It may be somehow related with computer sleep mode (I'm using that
frequently).

**Comment by matthiasbaldi** [comment]
Same here @dominch but I only have between 2-8 processes.
But high CPU usage starts immediately after starting Lens and doing nothing. Just watching the pod list with three items.
And it does not matter if the UI is in the background or active usage.

**Comment by degeens** [comment]
I'm also on version 5.2 and have the same issue.

**Comment by j-rewerts** [comment]
To be honest, I've noticed this with several versions of Lens going back to 4.x. Is this to be expected? It'd be nice to get an official response on if this. Not sure if it matters, but I have ~10 clusters added.

**Comment by matthiasbaldi** [comment]
> To be honest, I've noticed this with several versions of Lens going back to 4.x. Is this to be expected? It'd be nice to get an official response on if this. Not sure if it matters, but I have ~10 clusters added.

I don't think that this is a problem if the number of clusters. I have added between one and two clusters and use sometimes both in parallel.
But the problem happens even if I only use one.

**Comment by jakolehm** [comment]
I can reproduce this on Windows 10 and it's most likely something to do with new `node-fetch` based api communication backend.

**Comment by rendasaev** [comment]
Good day!
I have the same problem on Windows 10.
![image](https://user-images.githubusercontent.com/67231406/134118795-5042b450-d41f-4ce9-b4a7-f85a7a1b3836.png)
![image](https://user-images.githubusercontent.com/67231406/134118820-e17ac177-da18-493c-8f1e-716c64d4f423.png)

Version: 
![image](https://user-images.githubusercontent.com/67231406/134118852-bd8c1551-e6ce-4309-a1bd-7f203cc9af31.png)

**Comment by dominch** [comment]
It seems that latest update fixes issue: 
![image](https://user-images.githubusercontent.com/10815109/134137618-d48ed02d-02f6-4161-aa2d-3f5ad0d5aac8.png)

It came today and clearly it don't drain CPU anymore. I'll play more with that version and report if anything is wrong, but as far as I can see after few minutes problem is probably fixed. 

Go ahead and grab newest version, I'll close issue at the end of day.

**Comment by rendasaev** [comment]
I agree with @dominch. Looks like the last update 
![image](https://user-images.githubusercontent.com/67231406/134156404-b1d5956d-916d-4efd-877d-0dd046a2687d.png)
fix issue with CPU's perfomance.
![image](https://user-images.githubusercontent.com/67231406/134156511-5d26306b-b752-4533-8a39-4e3585e97420.png)

**Comment by matthiasbaldi** [comment]
Yes, I can also confirm that the latest release is much better.
But when I open a terminal or the logs overview my CPU is used around 10-20%.
Maybe that is normal but the CPU cooler is pretty busy 😅😏.

**Comment by jmcarranza** [comment]
hi, i update to the same verison and the problem persists 
![image](https://user-images.githubusercontent.com/9244484/134205979-16447e1b-5373-4be1-9893-0a5b8ddcc9a6.png)
![image](https://user-images.githubusercontent.com/9244484/134206120-cfe8ae9f-be63-42ba-8221-068c272b8e47.png)

**Comment by georok** [comment]
Confirmed. 5.2.3 does not resolve the issue.
5.1.3 is the last one that works properly.

![Lens](https://user-images.githubusercontent.com/82239117/134238280-74ac419a-0f01-4545-8fde-6413e93e9859.jpg)

**Comment by dominch** [comment]
Today I was able to reproduce issue with current version, 
![image](https://user-images.githubusercontent.com/10815109/134301211-b8fdf834-341f-4d9b-a172-62138c802dc8.png)

Interestingly - here it's graph with cpu usage and lens restarting and yet again don't drain cpu: 
![image](https://user-images.githubusercontent.com/10815109/134301567-c7c73cf3-f532-40a7-b973-e897102c8bae.png)
(one peak is lens starting, next one is connecting to cluster) 

On older version there was always about 20-30% of cpu, now soon after restart it's ok - less than 4% on idle (one cluster connected). As you can see sometimes things goes wrong and yet again cpu usage is higher, I had today constant 15-20% and soon later 40%. For now I need to restart lens when this happens. 

For now let's reopen issue and try to find cause. It does not happen always but sure there is something more about cpu usage.

**Comment by dominch** [comment]
Yesterday I had no problem with high cpu usage, today after few restarts I noticed that it starts with good cpu consuption <3%, after one cluster is connected and listing few pages (just clicking on menu positions) it starts to use 15-20% of cpu. Turning on debug console doubles cpu usage to 35-45%, everything on idle. 
![image](https://user-images.githubusercontent.com/10815109/134304128-a5f3587f-9308-45f4-bf26-a1b38f4c6106.png)

When problem is visible restarting lens helps, any reload has no effect I need to shut down it, wait about 10s and start it again.

**Comment by dominch** [comment]
After tonight upgrade Yet again seems to be ok. 
![image](https://user-images.githubusercontent.com/10815109/134633167-e7e0c1fc-0461-4c50-be75-65f2abc05c56.png)

I've been using it for about 2-3 hours and it did not reached more than 1% of CPU now. 
![image](https://user-images.githubusercontent.com/10815109/134633265-ea6ed6b7-b7b8-4fbf-b47b-8b8f9f664042.png)

Let's hope that issue is solved :) I will test it today and report back at the end of day.

**Comment by systemmonkey42** [comment]
I've been trying to isolate the cause for this issue.  It happened today after I restarted kubelet on the control plane.

It appears if there is a connectivity issue with the cluster, even a transient one, cpu suddently spikes.   The connection does get restored, but Lens had to be restarted to get CPU usage back to normal.  (Closing the GUI was not enough.  Killing was task manager was required in one instance when I could not interact with the system tray icon.)

Edit:  It happened to with 5.2.4-latest release.

**Comment by j-rewerts** [comment]
It looks like this fixed it for me. Thanks for the quick turnaround!

**Comment by georok** [comment]
Indeed, it looks like it is resolved. I have been running it the whole day connected to four GKE clusters simultaneously. Lens stays below 1% utilization, briefly jumping to 3-4% from time to time. Thank you

**Comment by dominch** [comment]
Yes, yet again it's ok :) After four days it stay <%1 almost all the time 
I'm marking it as resolved again
