### ISSUE TITLE
The latest version(v5.2.0-latest.20210908.1) of lens work not correctly

### ISSUE THREAD

**Issue by 510mt** [lensapp/lens#3779]
**Describe the bug**
Connected to the default cluster ,but it just show the full empty and grey screen.
By the way, it make my laptop cpu go height , and my laptop's fan is working abnormally

**To Reproduce**
1. Connect to the default cluster ,but it just show the full empty and grey screen

**Expected behavior**
Before the version v5.2.0-latest.20210908.1 , everything works well 

**Screenshots**
![issue](https://user-images.githubusercontent.com/25953268/132943680-5b5dafb9-4a1a-4818-9416-bef0328a0788.png)

**Environment (please complete the following information):**
- Lens Version: v5.2.0-latest.20210908.1
- OS: Ubuntu
- Installation method (e.g. snap or AppImage in Linux):
both AppImage and Deg

**Additional context**

**Comment by sefi-litmanovich-deel** [comment]
Having the same issue on the same version.
OS: macOs Catalina 10.15.7
Processor: Intel
Tried to install with brew and then also with dmg from the website.

**Comment by tonihoang** [comment]
same problem on macOS BigSur 11.5.2, but somehow only with the one cluster I have not connected to before the latest update.

**Comment by tonihoang** [comment]
What worked for me was to remove /Users/*****/Library/Application Support/Lens and restart Lens

**Comment by systemmonkey42** [comment]
```
/Users/*****/Library/Application Support/Lens
```
I'm not familiar with OSX, but this is likely where Lens Extensions were installed.  Did you have any extensions?
They may have needed upgrading to work with the newest version.
Removing the folder effectively uninstalled the extensions.

Lens may need a way to open in _safe_ mode, where extensions are ignored.

**Comment by tonihoang** [comment]
> ```
> /Users/*****/Library/Application Support/Lens
> ```
> 
> I'm not familiar with OSX, but this is likely where Lens Extensions were installed. Did you have any extensions? They may have needed upgrading to work with the newest version. Removing the folder effectively uninstalled the extensions.
> 
> Lens may need a way to open in _safe_ mode, where extensions are ignored.

no, just lens, nothing else

**Comment by tonihoang** [comment]
it seems to mostly happen, when I have 2 connections and the second one is opened, after a sleep session of the machine.

Only help for me so far: Force Quit Lens + Remove the mentioned folders.

**Comment by Nokel81** [comment]
Duplicate of #4018 (I know that this is older but that issue has more responses)
