### ISSUE TITLE
App crash at /namespaces

### ISSUE THREAD

**Issue by hansiemithun** [lensapp/lens#3782]
**To Reproduce**
1. Go to 'Namespaces'
2. Click on 'namespace'
3. App crashes. See error below:

instrument.js:109 TypeError: namespace.getStatus is not a function

**Expected behavior**
Should show the details of the namspace without any error.

**Screenshots**
[Namespace-Crash-Error-Image-Reference](https://i.imgur.com/tUVoIci.png)

**Environment (please complete the following information):**
- Lens Version: 5.x
- OS: [e.g. OSX]: Mac OS, Catalina and Sur
- Installation method (e.g. snap or AppImage in Linux): Updated Version

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
instrument.js:109 TypeError: namespace.getStatus is not a function
    at NamespaceDetails.render (namespace-details.tsx:85)
    at allowStateChanges (mobx.esm.js:1204)
    at mobxreact.esm.js:300
    at trackDerivedFunction (mobx.esm.js:1785)
    at Reaction.track (mobx.esm.js:2329)
    at NamespaceDetails.reactiveRender [as render] (mobxreact.esm.js:298)
    at NamespaceDetails.makeComponentReactive (mobxreact.esm.js:313)
    at NamespaceDetails.target.render (mobxreact.esm.js:226)
    at qi (react-dom.production.min.js:187)
    at pi (react-dom.production.min.js:186)
    at ck (react-dom.production.min.js:269)
    at bk (react-dom.production.min.js:250)
    at ak (react-dom.production.min.js:250)
    at Tj (react-dom.production.min.js:250)
    at Lj (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at exports.unstable_runWithPriority (scheduler.production.min.js:18)
    at gg (react-dom.production.min.js:122)
    at jg (react-dom.production.min.js:123)
    at ig (react-dom.production.min.js:122)
    at Hb (react-dom.production.min.js:292)
    at gd (react-dom.production.min.js:73)
    at HTMLDivElement.sentryWrapped (helpers.js:72)

```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
By version 5.X do you mean that it consistently fails with 5.0, 5.1, and 5.2?

If you clean out your `~/Library/Application Support/Lens` folder (and save it somewhere) does this still happen?

**Comment by hansiemithun** [comment]
@Nokel81 - Did not find Lens folder inside Application Support

**Comment by hansiemithun** [comment]
Any update on this, the latest Lens release also have no fix on this.

This is noticed in `MacOS Big Sur - 11.6`

Lens version: 5.2x

**Comment by Nokel81** [comment]
If you go to a terminal and type the following commands can you post a screenshot of the result?

```
cd ~/Library
ls
```

**Comment by Nokel81** [comment]
Or even better, can you open your devtools, trigger this error, then set a breakpoint at that line, then go back in history using the main menu `View > Go Back` and then navigate back to view namespaces.

Finally, go back to your devtools and look at the value of `namespace` and post a screenshot here.

Thanks

**Comment by hansiemithun** [comment]
## Library contents

![Library](https://i.imgur.com/wxZvJwE.png)

**Comment by hansiemithun** [comment]
If you clean out your ~/Library/Application Support/Lens folder (and save it somewhere) does this still happen?

- Yes its happening.

I am seeing this in latest 5.2.4 version also

**Comment by hansiemithun** [comment]
this is the namespace for your information:

```
{
  "apiVersion": "v1",
  "kind": "Namespace",
  "metadata": {
    "name": "default",
    "uid": "bbc8790c-e52f-4801-9f57-a43507f1ec09",
    "resourceVersion": "207",
    "creationTimestamp": "2021-08-27T01:26:32Z",
    "managedFields": [
      {
        "manager": "kube-apiserver",
        "operation": "Update",
        "apiVersion": "v1",
        "time": "2021-08-27T01:26:32Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:status": {
            "f:phase": {}
          }
        }
      }
    ],
    "selfLink": "/api/v1/namespaces/default"
  },
  "status": {
    "phase": "Active"
  },
  "spec": {
    "finalizers": [
      "kubernetes"
    ]
  }
}
```

**Comment by hansiemithun** [comment]
Error Image:

![Error](https://i.imgur.com/A7x3DNa.png)

**Comment by Nokel81** [comment]
> this is the namespace for your information: 

can you provide the prototype hierarchy of that value?

**Comment by hansiemithun** [comment]
This is the YAML prototype what we have:

```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    core.juniper.net/clusterName: contrail-k8s-kubemanager-mk
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"contrail"}}
  creationTimestamp: "2021-08-27T01:26:34Z"
  labels:
    core.juniper.net/clustername: contrail-k8s-kubemanager-mk
    core.juniper.net/namespace: contrail
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:status:
        f:phase: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-08-27T01:26:34Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:core.juniper.net/namespace: {}
    manager: manager
    operation: Update
    time: "2021-08-27T01:28:52Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:core.juniper.net/clusterName: {}
        f:labels:
          f:core.juniper.net/clustername: {}
    manager: kubemanager
    operation: Update
    time: "2021-10-28T14:31:52Z"
  name: contrail
  resourceVersion: "1943731"
  uid: 9e0c687f-922e-41ce-8e76-4ebc15d7b74f
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

Please verify this, thanks in advance

**Comment by Nokel81** [comment]
I meant the JS object prototype. But thanks anyway

**Comment by hansiemithun** [comment]
Any update on this? Can this be re-opened?

**Comment by Nokel81** [comment]
No release has been made with the resolving PR. It will definitely be out as part of 5.3.0 (currently on alpha.8) but it might be out as part of 5.2.6 if the PR can be applied cleanly.

**Comment by hansiemithun** [comment]
5.2.6 is released, no crash happening. But no data also displayed 😞 
![Screenshot 2021-11-08 at 6 21 19 PM](https://user-images.githubusercontent.com/3661669/140745118-6ea162dd-51cc-41d6-9321-e32f0e778998.png)

**Comment by Nokel81** [comment]
If you open up devtools you should see an error that starts with `[NamespaceDetails]: passed object that is not an instanceof Namespace` can you post a screenshot of that?

**Comment by hansiemithun** [comment]
![Screenshot 2021-11-09 at 5 57 40 PM](https://user-images.githubusercontent.com/3661669/140924263-47191fba-2486-4b1e-a800-876d96b905ea.png)

**Comment by Nokel81** [comment]
So it seems that for the details panel you are getting something that is only a `KubeObject` and not a `Namespace extends KubeObject` which is very strange because given that the namespaces list is rendering I have to take it that the store does indeed have a `Namespace extends KubeObject` for that value. So I wonder why the details panel isn't getting that one ... will have to investigate.

**Comment by Nokel81** [comment]
Would you mind sharing what the `selfLink` getter returns?

**Comment by Nokel81** [comment]
Do you have any extensions installed?

**Comment by hansiemithun** [comment]
No more extensions apart from the one which we build

**Comment by hansiemithun** [comment]
this is the selfLink details: /api/v1/namespaces/default? How do we get the return details?

**Comment by Nokel81** [comment]
if you start lens from the command line with `DEBUG=true` as a prefix you should be able to see the requests

**Comment by DanishKhakwani** [comment]
Similar issue for different KubeObject
![image](https://user-images.githubusercontent.com/4856506/142083669-abe717fd-8b3d-4385-a57e-1e20c3063ac6.png)

How do I clear the cache? Connecting again to that cluster brings back to the error. Cannot go back. I will have to reinstall Lens I guess if I can't clear the cache.

Clearing up `~/Library/Application\ Support/Lens/Cache/` didn't work.

Cleaning up bunch of other Cache and storage directories worked. This was the last one I cleaned up `~/Library/Application\ Support/Lens/lens-local-storage/*`.

**Comment by Nokel81** [comment]
Cleaning up `~/Library/Application\ Support/Lens/lens-local-storage/e8d1...4fc1.json` will fix that issue in the future.

@DanishKhakwani Thanks for the report but that is a slightly different bug, that has to do with something surrounding the logs saving bad data and we are not handling it very well.

Thanks for the report though.

**Comment by Nokel81** [comment]
> No more extensions apart from the one which we build

Do you create any `KubeApi`s?

**Comment by hansiemithun** [comment]
@Nokel81 - yes we do have our own KubeApis

**Comment by Nokel81** [comment]
Do you mind sharing what your KubeApis are? Do you automatically add items to other stores from within your extension?

**Comment by hansiemithun** [comment]
Weird observation is the same namespaces that we have works without extension enabled. Once extension is enabled, the app crashes by throwing errors as: 

```
instrument.js:109 TypeError: namespace.getStatus is not a function
    at NamespaceDetails.render (namespace-details.tsx:85)
```

**Comment by hansiemithun** [comment]
> Weird observation is the same namespaces that we have works without extension enabled. Once extension is enabled, the app crashes by throwing errors as:
> 
> ```
> instrument.js:109 TypeError: namespace.getStatus is not a function
>     at NamespaceDetails.render (namespace-details.tsx:85)
> ```

Any update on this?

**Comment by Nokel81** [comment]
So it sounds like a bug in your extension, are you registering `KubeApis`?

**Comment by hansiemithun** [comment]
Can you brief me a little on API registering? We have done that for custom resources extension development. This namespace we have not done anywhere in our code. Where do we need to do it if suppose we have missed it?

**Comment by Nokel81** [comment]
> This namespace we have not done anywhere in our code.

Does it crash for only one namespace or for all of them?

---

Sure, I can brief you on it.

So the only way for you to do this is if you either call `Renderer.k8sApi.apiManager.registerApi` or `Renderer.k8sApi.forCluster` or `Renderer.k8sApi.forRemoteCluster`.

Though now looking at the offending code, it seems that if your extension was to call `Renderer.k8sApi.apiManager.registerStore` with a `class T extends KubeObjectStore` which has a field `api` whose `apiBase` is `"/api/v1/namespaces"` then this problem would occur. And I think we probably should guard against that.

**Comment by hansiemithun** [comment]
This issue was we have registered namespacestore once again from our codebase. After fetching this directly from lens k8sapi store, it seems to work absolutely fine. Thank you for your patience and sorry for the big chain of comments here.
