### ISSUE TITLE
Unable to add helm repos (from pre-populated list or manual)

### ISSUE THREAD

**Issue by npasken** [lensapp/lens#3787]
**Describe the bug**
Errors encountered when trying to add helm repos. Seems there's communication issue somewhere.
* I am on a corporate network using proxy for non-cluster communication.
* Proxy settings are validated and allow list of repositories to load. 
* Error is after selecting any repo.

**To Reproduce**
1. Go to File > Preferences
2. Click on Kubernetes
3. Select 'prometheus-community' from list of Repositories under Helm Charts

**Expected behavior**
Add helm repos without any communication issues.
Install and manage helm charts without any issues.
I would expect the behavior to be very similar to how I am able to install lens-metrics on cluster using Lens app. Point and click and it just works!

**Screenshots**
![2021-09-13 09 43 56](https://user-images.githubusercontent.com/34988938/133098604-30b7c00c-78b0-4d3f-ab25-57e29e2f0077.png)

**Environment (please complete the following information):**
- Lens Version: 5.2.0-latest.20210908.1
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): Windows installer (auto-update from prior version)

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Adding helm branch prometheus-community has failed: Error: looks like "https://prometheus-community.github.io/helm-charts" is not a valid chart repository or cannot be reached: Get "https://prometheus-community.github.io/helm-charts/index.yaml": read tcp 135.70.245.39:50417->185.199.109.153:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
Not applicable - cluster communication works fine
```

**Additional context**
Also tried to manually add repos after installing helm CLI on my local machine.
* That at least adds the repo locally
* Still unable to perform any action on charts from Apps section in cluster
* Can select available charts after manually adding repo, but the detail screen that pops in from right just shows loading and never does anything else.

**Comment by pwurbs** [comment]
I can confirm this bug. To be honest I am astonished that this issue is only classified as p2.
I assume that most of the users sit behind a company proxy and can't use Lens at all to manage Helm charts.
So, one of the relevant good added value of this tool can't be used.
Maybe it's a bug which can be fixed easily and quickly.

**Comment by npasken** [comment]
Is there somewhere I can get an understanding of how bugs are addressed and worked? Curious if there's any indication when this issue might be picked up and resolved.

**Comment by npasken** [comment]
Is there any workaround that can be suggested? I think I would like to use this feature.
