### ISSUE TITLE
User Preferences view doesn't have bottom padding

### ISSUE THREAD

**Issue by Nokel81** [lensapp/lens#3789]
![Screen Shot 2021-09-13 at 4 31 07 PM](https://user-images.githubusercontent.com/8225332/133152144-5bc5006e-9e63-4c80-98a1-94c7edfe6039.png)

This is a bug for all components that use the `SettingsPage` component.

**Comment by aleksfront** [comment]
No longer relevant in latest version of Lens (6.2.4)
