### ISSUE TITLE
seeing jobs in pods section

### ISSUE THREAD

**Issue by nitishvu** [lensapp/lens#379]
**Describe the bug**

I am seeing jobs in pods section is this expected. correct me if I am wrong
please find the screenshot

![lens_jobs_in_pods](https://user-images.githubusercontent.com/24861433/82111530-9c6a7380-9763-11ea-91f6-24ba6327638d.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:3.4.0
- OS:ubuntu 20.04
- Installation method (e.g. snap or AppImage in Linux): 
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by nitishvu** [comment]
May be this is the reason.

<pre>$ kubectl get pods -n istio-system
NAME                                      READY   STATUS      RESTARTS   AGE
grafana-6bb6bcf99f-4hjkc                  1/1     Running     0          52m
istio-citadel-688696f77f-fj628            1/1     Running     0          52m
istio-egressgateway-747bd76fdf-rt64b      1/1     Running     0          52m
istio-galley-78d7c776f6-nb2c8             1/1     Running     0          52m
istio-grafana-post-install-1.5.1-k8jfx    0/1     Completed   0          52m
istio-ingressgateway-76b4c5c8cd-lc8tw     1/1     Running     0          52m
istio-pilot-57b569c8fd-sq86x              2/2     Running     3          52m
istio-policy-67597856b-rm2fs              2/2     Running     4          52m
istio-security-post-install-1.5.1-tkpzc   0/1     Completed   0          52m
istio-sidecar-injector-7c84db86f4-87hfz   1/1     Running     0          52m
istio-telemetry-6c8c5b7fbc-rx7k6          2/2     Running     4          52m
istio-tracing-7bdc6f8867-hbbcs            1/1     Running     0          52m
kiali-7b5c8f79d8-q7ltv                    1/1     Running     0          52m
prometheus-74d8b55f54-t6x5m               1/1     Running     0          52m
</pre>

**Comment by nevalla** [comment]
Don't see the actual issue here. Based on screenshot and kubectl output everything seem to be correct. Those pods are created by Job and should be visible on pods list. Please reopen and elaborate if there's a real issue.
