### ISSUE TITLE
Getting entity from cluster is unreliable in ExtensionRenderer.isEnabledForCluster()

### ISSUE THREAD

**Issue by stefcameron** [lensapp/lens#3790]
**Describe the bug**

The following code, which makes a custom cluster page either visible or not given the active cluster, is unreliable:

```javascript
  public async isEnabledForCluster(cluster): Promise<boolean> {
    const entity = Renderer.Catalog.catalogEntities.getById(cluster.id);
    return entity?.metadata.source === "my-source";
  }
```

As I understand it, when this method is called, there should never be a case where `getById(id)` returns `undefined` because the associated entity isn't found in the Catalog.

The result is my custom page shows-up on one of the clusters added by my extension, while it doesn't on another one. It should show-up on both.

**To Reproduce**
1. Install https://github.com/Mirantis/lens-extension-cc from the `cluster-page` branch (if still available, or from `master` if not, since that would mean it was merged).
2. Add 2 clusters via the extension.
3. Open one cluster, the "Container Cloud" page might be there. Open another cluster, it might not be there.

**Expected behavior**
This test should never fail to find the associated Catalog entity.

**Screenshots**

Not there:
![image](https://user-images.githubusercontent.com/2855350/133158548-a6ea6cf0-5027-41b3-8739-7d46937e3ae6.png)

There:
![image](https://user-images.githubusercontent.com/2855350/133158594-905a4d03-13ce-4dc3-b814-e32be62b2c75.png)

**Environment (please complete the following information):**
- Lens Version: 5.2 (official)
- OS: macOS 11.5.2
- Installation method: .dmg

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
There's too much sensitive stuff like usernames, emails, etc., in here to post these logs into a public repo.
```

**Comment by jakolehm** [comment]
IMHO this method currently passes wrong (legacy) object. It should actually give `KubernetesCluster`, not `Cluster` (which is "private" api).

**Comment by stefcameron** [comment]
@jakolehm 
> IMHO this method currently passes wrong (legacy) object. It should actually give `KubernetesCluster`, not `Cluster` (which is "private" api).

There are actually 2 problems with this old API:
1. The one you mention.
2. The fact that it's not possible for an extension to have multiple cluster pages, and decide which one is visible and which one isn't -- it's "all or nothing". This is because Lens' visibility check is tied to the cluster, not the cluster page menu item.

So this is a good opportunity to fix this API:
1. Deprecate this API entirely. Using `public async isEnabledForCluster(cluster)` should result in a console warning, if possible. Might not be since people are encouraged to override it and not call its super impl. At least mark it deprecated in the docs.
2. Add a new option to check this in the cluster page menu item itself, so that the check is per menu item, given the activated cluster:

    ```javascript
    this.clusterPageMenus = [
      {
        target: { pageId: "page-id" },
        title: "My cluster page",
        isEnabled(entity) {
          return entity.metadata.source === "my-source";
        },
        components: {
          Icon: () => <MyIcon />,
        },
      },
    ];
    ```

    `isEnabled` should obviously default to `true` when not specified, and it's given the newly-activated entity instead of that old cluster object thing.
