### ISSUE TITLE
Issues loading Lens on Windows 7

### ISSUE THREAD

**Issue by praveenchs** [lensapp/lens#38]
Hello All,

Got the following error , while running Lens 2.0.8 on Windows 7 - 64 bit . Never get the loading screen :

C:\Users\abcd\Downloads>"Lens Setup 2.0.8.exe"

C:\Users\abcd\Downloads>**C:\Users\abcd\AppData\Local\Programs\kontena
-lens\Lens.exe**

C:\Users\abcd\Downloads>
 ←[32minfo←[39m: Checking for update
(node:7784) UnhandledPromiseRejectionWarning: Error: listen EACCES: permission d
enied 127.0.0.1:9000
    at Server.setupListenHandle [as _listen2] (net.js:1209:19)
    at listenInCluster (net.js:1274:12)
    at doListen (net.js:1413:7)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
(node:7784) UnhandledPromiseRejectionWarning: Error: listen EACCES: permission d
enied 127.0.0.1:9000
    at Server.setupListenHandle [as _listen2] (net.js:1209:19)
    at listenInCluster (net.js:1274:12)
    at doListen (net.js:1413:7)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
(node:7784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:7784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:7784) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
(node:7784) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
←[32minfo←[39m: Update for version 2.0.8 is not available (latest version: 2.0.8
, downgrade is disallowed).

=====

My Machine configuration :: 
OS Name	Microsoft Windows 7 Professional
Version	6.1.7601 Service Pack 1 Build 7601
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	C3LAP060
System Manufacturer	Hewlett-Packard
System Model	HP ProBook 440 G2
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz, 2401 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	Hewlett-Packard M73 Ver. 01.44, 13-07-2017
SMBIOS Version	2.7

**Comment by jakolehm** [comment]
Possible that firewall (or similar) is blocking port 9000 from open?

**Comment by praveenchs** [comment]
It is listening on port 9000 :

netstat -na

Active Connections

  Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING
  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING
  TCP    0.0.0.0:3389           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:5000           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:5001           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:5002           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:5357           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:6000           0.0.0.0:0              LISTENING
  **TCP    0.0.0.0:9000           0.0.0.0:0              LISTENING**
  TCP    0.0.0.0:49191          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49192          0.0.0.0:0              LISTENING
  TCP    10.10.10.226:139       0.0.0.0:0              LISTENING

**Comment by jakolehm** [comment]
Can you double check (using `netstat -a -b`) that it's actually Lens using port 9000?

**Comment by praveenchs** [comment]
Dont know how , but the issues is now resolved . Getting the dashboard . 
Tried from shell as well as clicking the icon . Both works ...
Will check if it works after a reboot .
