### ISSUE TITLE
prometheus operator is not work with matric of node

### ISSUE THREAD

**Issue by superbeer** [lensapp/lens#382]
prometheus operator is not work with matric of node but is work with pod
mac
lens versions 3.4.0

i'm follow setup 
https://github.com/lensapp/lens/issues/289

![image](https://user-images.githubusercontent.com/20677737/82361241-c6a68480-9a34-11ea-88da-011f890dd348.png)

**Comment by Nokel81** [comment]
Is this still a problem in 4.1.4?

**Comment by superbeer** [comment]
it is work
