### ISSUE TITLE
Lens got stuck in windows version for terminal use.

### ISSUE THREAD

**Issue by samirpatry** [lensapp/lens#383]
**Describe the bug**
Lens got stuck in windows version for pod-shell/terminal use. We need to kill/re-open to make it work again.

**To Reproduce**
goto workload-->pods-->select one pod---> select pod shell--> close the terminal.
it will hang.
**Expected behavior**
Able to close the terminal window.

**Screenshots**
![image](https://user-images.githubusercontent.com/46788546/82437760-94893700-9ab5-11ea-86ed-944fd51175ce.png)

![image](https://user-images.githubusercontent.com/46788546/82437790-a36fe980-9ab5-11ea-9626-afdfe179b7e7.png)

![image](https://user-images.githubusercontent.com/46788546/82437810-acf95180-9ab5-11ea-8c0e-38bdbdde7b20.png)

**Environment (please complete the following information):**
- Lens Version: 3.4.0
- OS: Windows-10
- Installation method (e.g. snap or AppImage in Linux):  exe file

**Comment by msaum** [comment]
I'm seeing the same issue.  I don't see a configuration option to either use `kubectl.exe` directly without the `exec` or to use a WSL/WSL2 shell.

**Comment by servo1x** [comment]
Related: #338

**Comment by nevalla** [comment]
Fixed in #402
