### ISSUE TITLE
JS error - occasionly pops up

### ISSUE THREAD

**Issue by Yuvky** [lensapp/lens#384]
Describe the bug
Lens got stuck and throws a JS error

To Reproduce
While closing the app (sometimes) and during different screens in the UI

Screenshots
![image](https://user-images.githubusercontent.com/23193738/82554873-62d4a680-9b6f-11ea-8761-2e11fa2f5e55.png)

Environment (please complete the following information):

Lens Version: 3.4.0
OS: Windows-10
Installation method (e.g. snap or AppImage in Linux): exe file

**Comment by sandermvanvliet** [comment]
Was about to create an issue when I saw it was already reported. 
Can confirm here, same version and running on Win10

**Comment by nevalla** [comment]
Closing in favor of #377
