### ISSUE TITLE
statefulset scale slider

### ISSUE THREAD

**Issue by matti** [lensapp/lens#389]
Deployment has this fancy scale slider, but StatefulSet doesn't have it.

**Comment by dacahill7** [comment]
I think I will try this out after I do #834, so the stateful set also gets the buttons to increase or decrease.

**Comment by vshakirova** [comment]
Hi guys, I'm a newcomer, if you don't mind I'd like to try to implement this feature

**Comment by aleksfront** [comment]
@vshakirova Feel free to implement this!
