### ISSUE TITLE
Cannot open shell in pod outside of current context

### ISSUE THREAD

**Issue by dddicillo** [lensapp/lens#39]
When attempting to open a shell session within a pod from the Lens UI, a `--context` argument is not passed. Therefore, an error indicating that the pod was not found is issued unless the pod in question exists in the `current-context` defined in the active kubeconfig.

**Comment by nevalla** [comment]
So this issue occurs when you open pod shell from pod details? For terminal sessions lens app will use temporary kubeconfig generated for the active cluster, so there should be only one context to use.

What is the exact error message that you will see? Also, please could you specify your OS (MacOS, Linux, Window) and Kubernetes version.

**Comment by dddicillo** [comment]
I see. The temporary kubeconfig doesn't seem to be loaded properly in my case. I use a prompt that displays the active context and namespace, and I can still see that my terminal session is targeting a different context than what I attempt to connect to via Lens. I've actually determined that the issue is resolved by removing my KUBECONFIG export from `~/.zshenv`. That said, here is my information regarding the issue:

Here is the shell output (names altered). As you can see, my shell prompt displays the active context and namespace above command output. The pod I am trying to is running on a separate context. As mentioned above, unsetting my KUBECONFIG variable resolves the issue
```
kubectl exec -i -t -n mynamespace mypod-78c5b4fd9-zbkhj -c mycontainer -- sh -c "((clear && bash) || (clear && ash) || (clear && sh))"

~ (active-context/active-namespace)
❯ kubectl exec -i -t -n mynamespace mypod-78c5b4fd9-zbkhj -c mycontainer -- sh -c "((clear && bash) || (clear && ash) || (clear && sh))"
Error from server (NotFound): pods "mypod-78c5b4fd9-zbkhj" not found
```
```
System Version: macOS 10.14.3 (18D109)
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: varies by context
```
