### ISSUE TITLE
Refresh kubeconfig for cluster

### ISSUE THREAD

**Issue by dev-w0olf** [lensapp/lens#390]
**What would you like to be added**:
A possibility to reload kubeconfig, if file is already chosen via dropdown.

**Why is this needed**:
Kubeconfig is changing on daily basis (because of kyma kubeconfig generator), path stays the same - atm I have to delete cluster and reconnect to get updated kubeconfig - would be nice to have something like a "refresh config" button.

**Environment you are Lens application on:**

- Desktop OS: linux

**Comment by p4p4** [comment]
maybe also reload the kubeconfig on lens startup (not only adding a "refresh config" button)

**Comment by p4p4** [comment]
ticket also relates to https://github.com/lensapp/lens/issues/387

**Comment by nevalla** [comment]
3.6.0 won't store kubeconfigs as embedded in lens store and kubeconfig files are editable from outside too. Used kubeconfig is visible in cluster settings.
