### ISSUE TITLE
Custom Resources List is Never Loading if version does not match regex "v.*?"

### ISSUE THREAD

**Issue by auzhva** [lensapp/lens#394]
**To Reproduce**
1. Go to 'Custom Resources → Group → Your CRD'
2. Click on selected CRD
3. Wait until list of CRs will load
4. It will never load

**Expected behavior**
Expected to see list of CRs for CRD

**Screenshots**
<img width="985" alt="Lens 2020-05-29 19-45-06" src="https://user-images.githubusercontent.com/1519328/83284155-ff88eb00-a1e4-11ea-8c8c-7f0a41589c42.png">

**Environment (please complete the following information):**
- Lens Version: 3.4.0
- OS: OSX
- Installation method: OSX Official Image
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
/Applications/Lens.app/Contents/MacOS/Lens
info: Checking for update
info: Update for version 3.4.0 is not available (latest version: 3.4.0, downgrade is disallowed).
warn: PrometheusLens: failed to list services: [object Object]
warn: PrometheusLens: failed to list services: [object Object]
info: using operator as prometheus provider
info: using operator as prometheus provider
```

Thank you,

**Comment by auzhva** [comment]
Looks like issue is caused by an assumption that version name matches pattern "v.*" at [kube-api.ts#L36](https://github.com/lensapp/lens/blob/master/dashboard/client/api/kube-api.ts#L36) 

In this particular CRD version is named as `hub` which causes regex to fail.

Changing regex to below fixes the problem:
```
static matcher = /(\/apis?.*?)\/(?:(.*?)\/)?(.*?)(?:\/namespaces\/(.+?))?\/([^\/]+)(?:\/([^\/?]+))?.*$/
```

Can it be accepted as a solution, or are any other side effects foreseen? Locally do not see any problems with adjusted regexp

**Comment by Nokel81** [comment]
I am trying to reproduce this issue. Would you be able to provide the crd that you are using and seeing this behaviour with. Thanks.

**Comment by auzhva** [comment]
@Nokel81 thank you a lot!

**Comment by Nokel81** [comment]
You are most welcome.
