### ISSUE TITLE
Refactor Vue parts to React

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#396]
We should unify used frontend technologies. Most logical thing to do is refactor Electron renderer (Vue) parts to React. Once that's done we can move whole dashboard React app under renderer. This way we can have unified UI and developer experience and better foundation for extensible architecture.

- [x] Vuex -> Mobx + initial migration flow
- [x] Landing page
- [x] Whats new
- [x] Add Cluster
- [x] Workspaces
- [x] Preferences
- [x] Cluster Settings

**Comment by ixrock** [comment]
Maybe we should first off move dashboard (react parts) to renderer process + merge both `package.json` and after that convert all Vue parts with React step by step?

**Comment by jakolehm** [comment]
> Maybe we should first off move dashboard (react parts) to renderer process + merge both `package.json` and after that convert all Vue parts with React step by step?

If moving dashboard first makes more sense then let's do it.

**Comment by Nokel81** [comment]
I plan on taking "Cluster Settings"

**Comment by win5do** [comment]
Very curious why migrate from Vue to React ？

**Comment by ixrock** [comment]
@win5do most of Lens code (UI) where written with React, so it will make the app/ecosystem more sustainable and extensible. 
P.S vue was used only in limited amount of app views for the cluster-management.
