### ISSUE TITLE
Extension API

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#397]
Similar to what VS Code provides (see https://code.visualstudio.com/api). 

TODO:

- [x] auto-generate type declarations from `extension-api.ts` and push to public `@types/lens-extensions` or similar (current workaround manual exports in `extension-api.mock.d.ts`)
- [ ] figure out how to use extension's external npm modules, styles, assets, etc. from extension package (introduce `lens-package-manager.ts`)?

Needs #396

**Comment by ixrock** [comment]
Closing for now in favour #839
