### ISSUE TITLE
Terminal funkiness

### ISSUE THREAD

**Issue by chrisjohnson** [lensapp/lens#40]
When I open a terminal, it doesn't seem like it's sourcing my .zshrc despite the fact that it does load zsh. One of my completion files throws an error `compdef not defined` which indicates it didn't source the `compinit` line that would have loaded it. Furthermore, there is something not properly coupled, because the namespace in the launched terminal is `default` even if my current namespace is something else. I can even go into a normal iTerm window and issue kubectl commands to confirm I'm in namespace `cjohnson` and then go back to the Lens terminal and the namespace is `default`

**Comment by chrisjohnson** [comment]
It seems that Lens is setting ZDOTDIR (or, possibly, HOME) to `/Users/cjohnson/Library/Application Support/Lens/binaries/kubectl/1.15.3`, which is what's throwing it off. If I can figure out how it's doing that and make it stop doing that, that seems to be the solution to the compdef error. I can forcibly override it by mutating my ~/.zshenv and `export ZDOTDIR=$HOME` but this is obviously not a permanent solution. And the namespace issue still happens either way

**Comment by kke** [comment]
It's done like that, because I couldn't find another way to set the PATH for a login shell to enable the smart kubectl switching.

Starting a regular shell in OSX does not have the stuff you have defined in your login shell init files, because the host OS process has not read them. 

This is what the replacement `.zlogin` in the lens directory looks like:

```bash
test -f "$OLD_ZDOTDIR/.zshenv" && . "$OLD_ZDOTDIR/.zshenv"
test -f "$OLD_ZDOTDIR/.zprofile" && . "$OLD_ZDOTDIR/.zprofile"
test -f "$OLD_ZDOTDIR/.zlogin" && . "$OLD_ZDOTDIR/.zlogin"
test -f "$OLD_ZDOTDIR/.zshrc" && . "$OLD_ZDOTDIR/.zshrc"
kubectlpath="/Users/kimmo/Library/Application Support/Lens/binaries/kubectl/1.15.3"
p=":$kubectlpath:"
d=":$PATH:"
d=${d//$p/:}
d=${d/#:/}
export PATH="$kubectlpath:${d/%:/}"
export ZDOTDIR="$OLD_ZDOTDIR"
unset OLD_ZDOTDIR
```

Threre's no way to turn this behavior off currently.

Could it be that some of the stuff you're loading in those scripts uses ZDOTDIR for something, maybe ZDOTDIR needs to be restored before sourcing any of the init files?

**Comment by kke** [comment]
@chrisjohnson this can be reopened if the latest version (which should arrive via auto-update soon) does not fix it for you.

**Comment by chrisjohnson** [comment]
The issue of compdef being undefined (because ZDOTDIR is being overwritten to `/Users/cjohnson/Library/Application Support/Lens/binaries/kubectl/1.15.3`) is still present in 2.0.9

I'll open a separate issue to capture the namespace UX issue and how I think it might easily be resolved.

**Comment by nevalla** [comment]
Unfortunately the fix did not make into `2.0.9`, but it will be included in next release.

**Comment by chrisjohnson** [comment]
Just let me know when it releases and I'll test it out :)

**Comment by chrisjohnson** [comment]
Can this be re-opened since it hasn't been solved yet?

**Comment by miskun** [comment]
This issue should have been fixed by now. If for some weird reason this issue is still around, I'd suggest installing a fresh new version of Lens.
