### ISSUE TITLE
Create Resource does not have a pod template

### ISSUE THREAD

**Issue by RaananHadar** [lensapp/lens#4004]
**Describe the bug**
When clicking on the "Create resource" the "Select Template..." pull down menu does not have a template for a Pod as an option. 

**To Reproduce**
1. Select a cluster.
2. Click "Create resource"
3. Click "Select Template..."
4. Scroll down the list, it's not there.

**Expected behavior**
Pod should be on of the options in the pull-down menu. Clicking it should show a pod template in k8s.

**Environment (please complete the following information):**
- Lens Version:
- OS: Ubuntu 20.04
- Installation method (e.g. snap or AppImage in Linux): Lens 5.2.0 via latest deb package.

**Comment by Nokel81** [comment]
FYI you can create your own templates under `/.k8slens/templates` (see https://github.com/lensapp/lens/pull/2327)
