### ISSUE TITLE
Issue for accesing cluser iframe (as it is hidden) for integration tests in Ubuntu

### ISSUE THREAD

**Issue by gautam7730** [lensapp/lens#4026]
**Describe the bug**
When I run the integration tests for my extension in Ubuntu , the cluster iframe remain in hidden state which is causing issue for the tests to execute. 

On the Mac the iframe remain visible and tests pass. we need to run the integration tests in our pipelin using Ubuntu (details of this environment i have updated as part of : https://github.com/lensapp/lens/issues/4025).

Please suggest how to handle this ?

integration tests error message:

> waiting for selector "[id^='cluster-frame-']" to be visible
>       selector resolved to hidden <iframe id="cluster-frame-336b7ec4a4a1b463cae3d721c883a9…></iframe>

if i use ` { state: "hidden" }` , it gives error that contentFrame() can not be invoked on null.  

> const minikubeFrame = await window.waitForSelector(`[id^='cluster-frame-']`, { state: "hidden" });
>   const frame = await minikubeFrame.contentFrame();

**To Reproduce**
1. runt the Playwright integration test in Ubuntu
2. try accessing your extension selectors in the ubuntu environment using Playwright test cases.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.2.5
- OS: Ubuntu:20
- Installation method (e.g. snap or AppImage in Linux): AppImage

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
TimeoutError: page.waitForSelector: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector "[id^='cluster-frame-']" to be visible
      selector resolved to hidden <iframe id="cluster-frame-336b7ec4a4a1b463cae3d721c883a9…></iframe>
    ============================================================page.waitForSelector: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector "[id^='cluster-frame-']" to be visible
      selector resolved to hidden <iframe id="cluster-frame-336b7ec4a4a1b463cae3d721c883a9…></iframe>
    ============================================================

      71 |
      72 | export async function getClusterFrame(window: Page): Promise<Frame> {
    > 73 |   const minikubeFrame = await window.waitForSelector(`[id^='cluster-frame-']`);
         |                                      ^
      74 |   const frame = await minikubeFrame.contentFrame();
      75 |   return frame;
      76 | }

```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
Are you running on an ubuntu machine or within an ubuntu docker container?

**Comment by gautam7730** [comment]
running in ubuntu docker container.

**Comment by Nokel81** [comment]
Okay so we don't support running Lens within a docker container. At least not in headless mode. A full VM should be fine to run your tests in. See the comment in https://github.com/lensapp/lens/issues/4025.
