### ISSUE TITLE
Support the Application CRD please! Its a really useful metadata object maintained mostly by Google

### ISSUE THREAD

**Issue by red8888** [lensapp/lens#4032]
**What would you like to be added**:
Support reading "Application" resources in the "Applications" tab alongside the helm stuff.

**Why is this needed**:
This CRD is a metadata object you can attach resources to. It's designed to be read by tooling like lens for easily grouping all components of an application deployed with k8s. Currently it seems only the GKE UI supports it, but its obviously open source and any UI could support it: https://cloud.google.com/solutions/using-gke-applications-page-cloud-console#objectives

This is what it looks like, you can click on an "application" and see all its k8s resources:
![image](https://user-images.githubusercontent.com/6265399/137187407-dd1255d9-79a1-4f5d-b03d-2b9a6efff6ae.png)
![image](https://user-images.githubusercontent.com/6265399/137187805-62851f1f-9745-4483-9dc0-f3349e76059b.png)

While I get some of this with lens already because I deploy my apps with helm and lens reads helm releases, the Application CRD is more flexible and allows users to easily add arbitrary metadata.

**Comment by Nokel81** [comment]
Duplicate of https://github.com/lensapp/lens/issues/3801
