### ISSUE TITLE
Cluster status does not update properly in Catalog

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#4063]
**Describe the bug**

Cluster status does not always update in catalog.

**To Reproduce**
1. Connect to a cluster
2. Go back to catalog
3. Disconnect cluster
4. Status stays "connected" forever

**Environment (please complete the following information):**
- Lens Version: 5.3.0-alpha.2

**Comment by Nokel81** [comment]
Duplicate of https://github.com/lensapp/lens/issues/4035
