### ISSUE TITLE
edit a file on the pod volume

### ISSUE THREAD

**Issue by mkshal** [lensapp/lens#4069]
**What would you like to be added**:
-a file explorer that uses kubectl in the background. but to the user seem like he is editing files. 
-allow downloading a file or folder (kubtctl cp in the background doing the job for example)

**Why is this needed**:
-to save time updating config files or params
-to make it easier to edit config files or params

**Environment you are Lens application on:**
K8s

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Azure
- Desktop OS: <the OS Lens app runs on in your case>
- ubuntu

**Comment by Nokel81** [comment]
Thank you for the request. At this time we do not plan on implementing this as it seems to be an anti-pattern. You should be able to just `kubectl exec` into the pod and then use `vim` or something similar anyway. Configs should be editable through the kube API instead, generally.

**Comment by mkshal** [comment]
Hi,

What I suggested was for convenience of clicks and NOT having to use kubectl commands on the users’ part, which is why most people use lens (saves the time having to look at the kubectl cheatsheets). It would be very nice if the following were possible:

When you see a pod like below, if the volume mounts were shown as links(highlighted), then I would click on it, and it would open an explorer like window that I could traverse through, modify files and download to my pc (or upload onto the volume) without having to run a single kubectl command.

***@***.***
.
Hopefully, this explanation helps you understanding my feature request somewhat better.

Rgds,
Shariful//

**Comment by Venryx** [comment]
In my case, the problem with trying to `kubectl exec` into the pod is that the pod kept crashing, leaving me unable to make changes to the persistent-volume-claim contents that would get the pod to _stop_ crashing.

To fix it, I ended up deploying a mini "shell pod" that just has some basic utils I can use for exploring and modifying the file-system.

Specifically, I created a variant of the following yaml config, and deployed it to my cluster: https://github.com/imesh/kubernetes-tutorials/blob/master/create-persistent-volume/busybox-pod.yaml

Just make sure to:
1) Modify the `spec.volumes[0].persistentVolumeClaim.claimName` to match the name of the PVC you want to view/modify.
2) Once you open a shell in that mini pod, remember that the data you want is under the `/mnt/volume1` path.

As for how to open a shell into that pod, you can just use Lens to explore to the list of pods, click the "busybox" one, and press "Pod Shell" in the toolbar.

(Note that while the above does work, I do also think having a built-into-Lens way to do this sort of PVC exploration would be super cool! I understand it probably would be a lot of work to implement in a generic way, though.)
