### ISSUE TITLE
AppCrash

### ISSUE THREAD

**Issue by alekc** [lensapp/lens#407]
**Describe the bug**
Clicking on a view secret (from pod details ui) brought me to the app crashed page

```
Error stack:

 
TypeError: Cannot read property 'length' of undefined
    at Object.parse (webpack-internal:///307:82:46)
    at Object.decode (webpack-internal:///2:308:31)
    at SecretKey (webpack-internal:///990:18326:96)
    at Ih (webpack-internal:///607:154:98)
    at si (webpack-internal:///607:174:273)
    at gk (webpack-internal:///607:261:312)
    at fk (webpack-internal:///607:230:22)
    at Zj (webpack-internal:///607:229:362)
    at Lj (webpack-internal:///607:223:216)
    at eval (webpack-internal:///607:121:115)
```

```
Component stack:


    in SecretKey
    in div
    in span
    in div
    in DrawerItem
    in wrappedComponent
    in div
    in PodDetailsContainer
    in div
    in PodDetails
    in div
    in div
    in div
    in Animate
    in Drawer
    in KubeObjectDetails
    in ErrorBoundary
    in Router
    in Unknown
    in App
```

**To Reproduce**
one time error

**Environment (please complete the following information):**
- Lens Version: 3.4.0
- OS: Ubuntu
- Installation method  snap

**Comment by Nokel81** [comment]
I am having trouble trying to replicate this problem. I when to the `Workloads > Pods` view, clicked on a pod, then in the sidebar clicked on the linked `secret` but did not get an error or a crash. 

So either this issue has already been fixed transitively or this is not where you observed the error.

**Comment by nevalla** [comment]
It's coming from this line: https://github.com/lensapp/lens/blob/master/dashboard/client/components/%2Bworkloads-pods/pod-container-env.tsx#L136. Since this was one time error, maybe there was something off with the secret data. Perhaps we should check that `secret.data[key]` is not undefined or null?

**Comment by Nokel81** [comment]
makes sense, how about the above check is `if (!secret?.data || !secret.data[key])`

**Comment by Nokel81** [comment]
Or inverted, will make a PR
