### ISSUE TITLE
Inconsistent casing of CRDs

### ISSUE THREAD

**Issue by rittneje** [lensapp/lens#4081]
In #3257 the casing of CRDs in the sidebar was fixed to match kubectl. However, the title bar was missed. The search bar text should also be fixed.

![image](https://user-images.githubusercontent.com/28784688/138009789-2734abf6-05ec-493b-ad29-168f6324c9c6.png)

**Comment by Nokel81** [comment]
I don't think that the search bar should be `.spec.names.kind` as it should still be the plural form. So I will change it to be just `.spec.names.plural`. I might be cool to use some form of auto-pluralization but I am hesitant on doing so because it probably won't be perfect.
