### ISSUE TITLE
Socks proxy support

### ISSUE THREAD

**Issue by xaocon** [lensapp/lens#412]
**What would you like to be added**:
SOCKS proxy support

**Why is this needed**:
Easier setup for users that need to talk to K8s through a proxy server. It would be nice to be able to `ssh -D <PORT> <SERVER>` and use that for several clusters. HTTP proxy support is already included.

**Environment you are Lens application on:**
- Kubernetes distribution: GKE, Rancher, minikube
- Desktop OS: OSX 3.4.0

**Comment by jakolehm** [comment]
This might be hard to pull of because `kubectl` does not currently support SOCKS: https://github.com/kubernetes/kubernetes/issues/58065

**Comment by xaocon** [comment]
I don't write much TS but I may try to make a PR for this. Before I dig in, could you give me some sense for how kubectl is called vs direct usage of the API?

**Comment by mphcomputing** [comment]
I dont think that it would be too hard, if you allow the http proxy field to allow socks5 format, e.g. socks5://localhost:12345, this should work, assuming that you have all other connectivity in place.

**Comment by mister2d** [comment]
> I don't write much TS but I may try to make a PR for this. Before I dig in, could you give me some sense for how kubectl is called vs direct usage of the API?

`kubectl` wouldn't be used at all for this method.

Essentially if you're a *nix user one would simply invoke `ssh -D <PORT> <SERVER>`, then simply set your application's [Lens] proxy address to `localhost:<PORT>`. You can then use an unaltered kubecfg file since DNS would be used through this SOCKS5 proxy.

If you're a Windows user with PuTTY then it's the same flow except it's called Dynamic forwarding.

`kubectl` never comes into play.

**Comment by vivanov83** [comment]
Hm, strange I tried, but I'm facing this error 

> E1018 11:41:44.813057 11499 proxy_server.go:147] Error while proxying request: context canceled

**Comment by girorme** [comment]
Hi! Any new updated method to connect lens through socks?

_Maybe: socks -> create a http proxy from socks -> set in lens._

**Comment by xaocon** [comment]
I'm not a dev here but support has landed upstream in 1.24 which has alpha
releases out already. I suspect they'll just wait for it to go GA and add a
quick option for it. Perhaps this issue should be closed in favor of an
issue for tracking whatever specifically is planned. I'll leave it to
maintainers to say though.

**Comment by ydelattre** [comment]
Hello !
Any news about this ?
I set `proxy-url` with a proxy socks in my kubeconfig and globally Lens works
But Forward or Pod Shell are not working....
Last version of kubectl fully support proxy-socks (even for kubectl exec).
Thanks !

**Comment by babs** [comment]
My findings: pod shell rely on kubectl spawn with a custom KUBECONFIG that point to local lens proxy.
At this point I drilled down to https://github.com/lensapp/lens/blob/07a775c32d3290babcd1ed242ded50ddc0b30b95/src/main/lens-proxy/lens-proxy.ts#L222 ,  https://github.com/lensapp/lens/blob/07a775c32d3290babcd1ed242ded50ddc0b30b95/src/main/context-handler/context-handler.ts#L146 and  https://github.com/lensapp/lens/blob/07a775c32d3290babcd1ed242ded50ddc0b30b95/src/main/context-handler/context-handler.ts#L152
But I might have missed something, got lost somewhere and follow the wrong path....
Would it be an issue when the connection upgrade to SPDY ?
Wouldn't it be a solution to set in the temporary KUBECONFIG as the original one, used by lens to access the cluster in the first place (namespace porperly set).
I might be missing something but what is the goal of going through the lens-proxy for that ?

**Comment by rmeleromira** [comment]
+1 on this. Pretty sure this isn't a feature request at this point, and more of a bug fix now. I'm able to set "proxy-url" in my kubeconfigs and it connects, and most features work, but pod shells do not. kubectl exec just hangs

**Comment by jakolehm** [comment]
> I might be missing something but what is the goal of going through the lens-proxy for that ?

At least in the past lens-proxy was required for all requests because it had workarounds for Rancher etc clusters (which kubectl did not handle properly). We might want to revisit this because kubectl has improved also in this regard. Anyway I think https://github.com/lensapp/lens-k8s-proxy/pull/13 will fix the remaining issues with SOCKS.

**Comment by babs** [comment]
Looking forward to it! If you need some test on this, let me know, I've several use cases, I'm on slack if needed :)
Side note: kubectl seems to have a better handling thought Rancher now (use-case also available).

**Comment by babs** [comment]
I've tested with 6.1.13, still a no route to host to the master with the following message while trying to open a shell to a pod:
`error: unable to upgrade connection: error dialing backend: dial tcp MASTERIP:6443: connect: no route to host`

**Comment by cirilloblu** [comment]
Is like the shell context lost the _cluster.proxy-url_ config inside kubeconfig. Maybe need to be mapped or something like this?

**Comment by babs** [comment]
It's a little more complex than that, as far as I understand, kubectl is loaded with a custom KUBECONFIG that point to lens-k8s-proxy binded locally with a suffix on the URL to achieve routing to the correct target cluster.

**Comment by whitingj** [comment]
I'm having the same issue. kubectl works great with `proxy-url` but that doesn't seem to carry over to the custom KUBECONFIG that lens produces. Most everything seems to work except shell. I would love a fix.

**Comment by girorme** [comment]
@whitingj to solve the issue for now, i'm using any tool to convert socks to http proxy and it works well
