### ISSUE TITLE
Unable to add Cluster

### ISSUE THREAD

**Issue by yogmangela** [lensapp/lens#4127]
@ mario sarcher

I am unable to add a cluster to the Hotbar, I can syn a cluster. but once synced it's not appearing on the left pane. 

please see the video attached should explain the bug.

I am using MacBook. See the slack channel for the video too

https://user-images.githubusercontent.com/6623718/138685460-44ae06f7-dbd4-4f60-ab57-bacd6abe2ab0.mov

 video here.

Thanks
Yogs

**Comment by Nokel81** [comment]
Duplicate of https://github.com/lensapp/lens/issues/3436
