### ISSUE TITLE
Lens showing blank screen in mac os M1 chip 2020

### ISSUE THREAD

**Issue by the-light-yagami** [lensapp/lens#4153]
**Describe the bug**
When I open Lens, I got stuck like below screenshot.

**Screenshots**
<img width="1679" alt="Screenshot 2021-10-27 at 7 54 58 PM" src="https://user-images.githubusercontent.com/12210908/139080547-e1adf48b-f7e6-4ebf-b5a6-19b4743c6afa.png">

**Environment (please complete the following information):**
- Lens Version:
`Lens: 5.2.5-latest.20211001.2
Electron: 12.2.1
Chrome: 89.0.4389.128
Node: 14.16.0`
- OS: `MacBook Air (M1, 2020) Version Big Sur 11.6`
- Installation method (e.g. snap or AppImage in Linux): `brew and also with dmg`

**Logs:**
Some fishy log.
```
<--- Last few GCs --->

[4582:0x7900000000]   133942 ms: Mark-sweep 1948.7 (2065.2) -> 1941.9 (2067.0) MB, 2955.9 / 2.1 ms  (average mu = 0.113, current mu = 0.037) allocation failure scavenge might not succeed
[4582:0x7900000000]   137624 ms: Mark-sweep 1950.1 (2067.0) -> 1943.4 (2069.0) MB, 3568.9 / 2.1 ms  (average mu = 0.073, current mu = 0.031) allocation failure scavenge might not succeed


<--- JS stacktrace --->
```

**Comment by Nokel81** [comment]
Do you have more logs? Is this a duplicate of #4018 ?

**Comment by the-light-yagami** [comment]
> Do you have more logs? Is this a duplicate of #4018 ?

Yes. It was same issue. Solved by following [this](https://github.com/lensapp/lens/issues/4018#issuecomment-942885854)

**Comment by Nokel81** [comment]
Okay I am going to close this then as duplicate of #4018 so we can track it all in one place. It should be better in 5.3.0
