### ISSUE TITLE
Add "help" texts for config sections on Preferences page

### ISSUE THREAD

**Issue by nevalla** [lensapp/lens#416]
For example, on Helm charts would be nice to display how to add private repos etc.

**Comment by Nokel81** [comment]
More information would be appreciated. Looking at the preference's page and I don't even see were a "private repo" could be added.

**Comment by Nokel81** [comment]
@nevalla Some more information on this would be nice, thanks.

**Comment by nevalla** [comment]
Right, I will provide additional information.

**Comment by Nokel81** [comment]
Closing as some of the preference fields do have "hints" or "help texts".
