### ISSUE TITLE
win 10 install stuck

### ISSUE THREAD

**Issue by NA3** [lensapp/lens#421]
![Capture](https://user-images.githubusercontent.com/3059879/84147040-045b6380-aa5d-11ea-93f0-e9b5bbe09b21.PNG)

install stuck on a fresh windows 10 20h1 install 
with roaming profile from win server with active directory

maybe some files are blocking on roaming but i can't find them

**Comment by mrbennett** [comment]
I am having this same issue after trying to update to a beta version.

Now the installer of any version gets stuck at the same progress as the screenshot above

**Comment by nevalla** [comment]
Fixed in #893
