### ISSUE TITLE
Metrics history beyond 1h

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#428]

**Comment by cosmonova** [comment]
Could be configured under Cluster Settings.

**Comment by janerikmai** [comment]
I suggest providing zoomable graphs f.ex. to see long term container memory consumption (leaks) like in a grafana dashboard.

**Comment by bertrandp** [comment]
Really need this feature

**Comment by darkfessing** [comment]
+ very need

**Comment by jakolehm** [comment]
This is already implemented.
