### ISSUE TITLE
Improved logs UI

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#430]
**What would you like to be added**:

- Get rid of modal -> logs would be visible as tabs in the dock.
- Selectable time-window
- Search logs

**Comment by donbeave** [comment]
It will be nice to add ability to enable/disable timestamp in the logs line. For example, the default behavior for Java apps (especially Spring Boot) is print logs with date-time, in this case, Lens will have almost duplicated information (for each line):

<img width="1765" alt="image" src="https://user-images.githubusercontent.com/139017/85364878-b6635700-b556-11ea-84a1-ec6fa668712e.png">

Maybe it's better to switch off timing by default and enable it when users want it for particular deploys?

**Comment by donbeave** [comment]
It will be nice to make logs as a separate window and also bigger with the ability to view logs for different pods in the same time. I mean multiple opened windows.

**Comment by ppalucha** [comment]
Search would be nice...

**Comment by devth** [comment]
Also: tail the logs for an entire namespace instead of only individual pods.

**Comment by mih-kopylov** [comment]
@devth or for a deployment / service (when there's a bunch of pods inside)

**Comment by Nuru** [comment]
@donbeave wrote:
> It will be nice to add ability to enable/disable timestamp in the logs line. 

That feature already exists. Click the clock icon ![Clock Icon](https://user-images.githubusercontent.com/2793313/93032810-5a095400-f5e8-11ea-93d6-cf24284bb26b.png) in the upper right of of the dialog to toggle the timestamps.

**Comment by Nuru** [comment]
I suggest looking at [stern](https://github.com/wercker/stern) as a source of suggested features for combining logs, particularly combining all logs for a DaemonSet or ReplicaSet into one stream.

I also would very much appreciate the ability to search and filter the logs, similar to what is available with  `less` and `grep`. 

It would also be helpful to be able to open the logs in a separate window, so I can view the logs as I work on other resources.

**Comment by aleksfront** [comment]
Closed in https://github.com/lensapp/lens/pull/1114
Selectable time-window, workload logs and other improvements are listed in their own issues.

**Comment by kilpatty** [comment]
Not sure if I'm missing this, but is there a link to the time-window PR @aleksfront?

**Comment by aleksfront** [comment]
@kilpatty There wasn't any. Now it's created https://github.com/lensapp/lens/issues/1729. All logs-related issues could be found by settings `area/logs` label https://github.com/lensapp/lens/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Flogs

**Comment by kilpatty** [comment]
@aleksfront thanks! :) Sorry don't mean to be a bother, please let me know if I can help in any way
