### ISSUE TITLE
HTTP API Proxy Bug?

### ISSUE THREAD

**Issue by joshuaquek** [lensapp/lens#455]
**Describe the bug**
I am able to curl the http proxy api, but Lens cannot connect.

**To Reproduce**
1. Start the proxy api in http://localhost:8080
2. try to curl it, and it responds with a JSON payload
3. try connecting to it with Lens and set the Proxy API field to http://localhost:8080
4. It errors out with `Connecting ... 2020/06/13 22:04:35 http: proxy error: Not Found`

**Expected behavior**
I expected it to connect

**Environment (please complete the following information):**
- Lens Version: 3.4.0
- OS: MacOS OSX Catalina
- Installation method (e.g. snap or AppImage in Linux): Releases section in Github
 
**Logs:**
When I `curl localhost:8080` I get the following:

![image](https://user-images.githubusercontent.com/5335756/84571030-6e5c6b80-adc3-11ea-8661-f23e46cfc13a.png)

I then set the HTTP Proxy here:

![image](https://user-images.githubusercontent.com/5335756/84571057-96e46580-adc3-11ea-9b51-f20321a4aa63.png)

But when I try to connect with I get the following:

![image](https://user-images.githubusercontent.com/5335756/84571048-859b5900-adc3-11ea-8618-4d87e1d87c1d.png)

**Comment by jakolehm** [comment]
HTTP proxy feature expects a real proxy server. You could try following (without setting HTTP Proxy on cluster settings): 

1. run `kubectl proxy` manually
2. create handcrafted kubeconfig that points to `kubectl proxy` address
3. add that handcrafted kubeconfig to Lens
