### ISSUE TITLE
Delete cluster from right click

### ISSUE THREAD

**Issue by hadim** [lensapp/lens#456]
I often need to create/delete clusters for dev purposes. ATM I need to scroll down at the bottom of the settings page. Could you add a delete button when right-clicking on a cluster icon?

**Comment by sdil** [comment]
@jakolehm can I try to work on this issue?

**Comment by jakolehm** [comment]
@sdil go ahead 👍

**Comment by sdil** [comment]
@jakolehm thanks. I'll work on this on my weekend

**Comment by nevalla** [comment]
Fixed in #396
