### ISSUE TITLE
Switch to use Monaco editor

### ISSUE THREAD

**Issue by nevalla** [lensapp/lens#458]
https://microsoft.github.io/monaco-editor/

Monaco editor provides better capabilities to enable k8s resource auto-completion and validation.

**Comment by aleksfront** [comment]
We should use some plugin for supporting YAML format. https://www.npmjs.com/package/monaco-yaml can be a good candidate.

**Comment by LucaDev** [comment]
Additionally I'd love to see the editor in more places, like for editing configmaps.

**Comment by aleksfront** [comment]
Closed in #2949
