### ISSUE TITLE
Option to disable GPU acceleration

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#462]
**What would you like to be added**:

Option to disable GPU acceleration.

**Why is this needed**:

MacOS seems to have issues with chrome/chromium: https://www.forbes.com/sites/gordonkelly/2020/06/11/apple-macos-macbook-pro-google-chrome-display-problem/amp/

**Comment by jakolehm** [comment]
Related issue: #222

**Comment by Nuru** [comment]
See also https://bugs.chromium.org/p/chromium/issues/detail?id=1068170#c82 Where Google team says Apple has reproduced and acknowledged the bug. Also in the thread:

[comment 100](https://bugs.chromium.org/p/chromium/issues/detail?id=1068170#c100)
>(To be clear, the core issue is that OpenGL is broken on these machines -- disabling GPU rasterization makes use use OpenGL less often, but we still use it. Switching to Metal is blocked on shader compiler hangs in issue 974219).

[comment 129](https://bugs.chromium.org/p/chromium/issues/detail?id=1068170#c129) Thu, Jul 23, 2020
> Apple indicates that the fix which they thought would fix this [in Seed 2 of 10.15.6 beta] didn't, and they're digging in further. At this point further reports of the problem on 10.15.6 aren't needed; thanks everyone. Will provide more information as we learn it.

comment 131
>It can happen any time the discrete GPU in the machine is activated, which is reliably triggered by using an external display, but can also be triggered by graphics-intensive applications and websites such as Photoshop or Google Earth.

**Comment by aleksfront** [comment]
Related issue https://github.com/lensapp/lens/issues/562
