### ISSUE TITLE
Revealing pod secret closes panel

### ISSUE THREAD

**Issue by servo1x** [lensapp/lens#473]
**Describe the bug**

When clicking on a pod, after the panel appears, when clicking on the eye icon to reveal an environment secret - instead of showing the value the pod panel is closed instead.

**To Reproduce**
1. Click workloads
2. Click pods
3. Click a pod with a environment secret
4. Click the eye icon
5. Pod panel closes instead

**Expected behavior**
Secret should be revealed with the panel not closed.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 3.5.0
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): Binary

**Comment by nevalla** [comment]
I was not able to reproduce this. Does this happen on all secrets?

**Comment by servo1x** [comment]
It seems to be working now, maybe I was having a connection issue. Thanks!
