### ISSUE TITLE
Support for alternative terminal shells

### ISSUE THREAD

**Issue by stevenfollis** [lensapp/lens#482]
**What would you like to be added**:

Can we please add a user preference/setting for a specific terminal so that when "New Terminal Session" is initiated, Lens launches and preloads my kubecontext into my terminal of choice, rather than only the singular preset? Similar to VSCode, an Electron app that does this quite well at providing added flexibility.

**Why is this needed**:

Currently when I open a New Terminal Session window in Lens while on my Windows 10 machine, I am greeted with a PowerShell prompt that has already wired up my `kubectl` integration - very slick. 

![image](https://user-images.githubusercontent.com/5393923/84815440-0c794d00-afe1-11ea-8f4b-3d8b33d6af39.png)

However, I prefer to interact with `kubectl` from a *nix-style terminal so that I can use goodies like `jq`, piping, et. al. I have WSL2 installed on my machine, but when I launch the bash prompt, I lose my kubecontext that lens had preset for me. 

![image](https://user-images.githubusercontent.com/5393923/84815536-2c107580-afe1-11ea-8d67-9c84650ad686.png)

I suspect I would also hit this issue if I:

* Was using Windows 10 and wanted to use `cmd` rather than `PowerShell` 
* Was using bash but wanted to switch to zsh, etc.

**Environment you are Lens application on:**

- Kubernetes distribution: Docker Enterprise 3.0
- Desktop OS: Windows 10 (Version 10.0.19041.264)

Thanks!

**Comment by littleccguy** [comment]
It's too bad this has not moved forward.  I would rather use Git Bash for terminal.

**Comment by sharkzeeh** [comment]
Is there any update on that?

**Comment by IstvanCsVarga** [comment]
Any news?

**Comment by Nokel81** [comment]
Did specifying the path the new shell not work?

**Comment by faisal6621** [comment]
> Did specifying the path the new shell not work?

@Nokel81 No. If I put the path to `git-bash.exe` then it launches the **git-bash** as a new process and not able to use directly within Terminal window in Lens.

**Comment by Nokel81** [comment]
@faisal6621 Can you open a new bug report please

**Comment by sardar27** [comment]
How to connect terminal in desktop

**Comment by joshsten** [comment]
> > Did specifying the path the new shell not work?
> 
> @Nokel81 No. If I put the path to `git-bash.exe` then it launches the **git-bash** as a new process and not able to use directly within Terminal window in Lens.

I think git-bash is the shell wrapper. We want the shell directly:

C:\Program Files\Git\bin\bash.exe

This worked for me. I did have to restart lens to get it to take.
