### ISSUE TITLE
New to Lens: how to connect to Linux by Terminal ?

### ISSUE THREAD

**Issue by leiw324** [lensapp/lens#485]
Hello,

k8s: 1.18.3
Windows 10 client

When I click Terminal will connect to my Windows, but how to connect to Linux ?

![image](https://user-images.githubusercontent.com/33790160/84858192-460f8e00-b09d-11ea-8c61-c10d80545406.png)

Thanks

**Comment by nevalla** [comment]
Hi @leiw324. Please could you elaborate what do you mean by connecting to Linux? Do you mean this https://github.com/lensapp/lens/issues/482?

**Comment by leiw324** [comment]
Hello nevalla,

Yes, because I don't know Windows 10 PowerShell type k8s command.

Thanks
