### ISSUE TITLE
Logs display exhibits jump and flash as logs are refreshed

### ISSUE THREAD

**Issue by danielbprice** [lensapp/lens#4855]
**Describe the bug**

I spend a lot of time looking at pod logs, but lens is slowly driving me to distraction.  The logs output exhibits period flash / scroll / repaint noise as the logs are refreshed (I think).  I

**To Reproduce**
1. Go to a pod which is logging a fair amount.  Open the logs and watch for flashes of content.    This is one issue.
2. Let the logs exceed the size of your window
3. Scroll to the top of the logs
4. Sometimes on refresh, the scroll position will change.  This is a second issue.

**Expected behavior**

Smooth behavior with no flashing and especially no jumping around.

**Screenshots**

In the screen recording below I have not pressed any keys or moved my mouse after the initial scroll, yet the display jumps around (sorry, there is a couple of seconds of nothing happening in the middle).

**Environment (please complete the following information):**

Lens: 5.3.4-latest.20220120.1
Electron: 13.6.1
Chrome: 91.0.4472.164
Node: 14.16.0

**Comment by danielbprice** [comment]
https://user-images.githubusercontent.com/2693615/153653932-4964df77-ffd8-44cb-b4a4-76d7ce146a78.mov

**Comment by Nokel81** [comment]
I believe that this has been fixed already in the 5.4 betas, would you be able to try that out? You can enable beta versions of lens within your settings page.

**Comment by danielbprice** [comment]
@Nokel81 thank you, it is definitely much improved in the beta; however I did notice some times when clicking on a pod's logs that the "spinner" would just spin forever.  Reselecting container using the new "Pod" menu seemed to solve the problem.

**Comment by Nokel81** [comment]
Okay thanks for that second bug report, we will look into it.

**Comment by danielbprice** [comment]
@Nokel81 Thank so much.  Let me know if you need a video of it.

**Comment by aleksfront** [comment]
Not reproducible in 5.4.2. @danielbprice Opened another issue about second bug, can you please share an error video there (with opened DevTools console)? https://github.com/lensapp/lens/issues/5020
