### ISSUE TITLE
Possibility to define available namespaces

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#486]
**What would you like to be added**:

Possibility to define list of user accessible namespaces (maybe somewhere in cluster settings).

**Why is this needed**:

User might not have rights to list namespaces. It would be handy to tell Lens which namespaces are allowed to access (user usually knows this).

**Comment by juv** [comment]
In Openshift clusters, the user is typically restricted to a list of namespaces (called "projects" in Openshift).
This feature enables the user to list his available namespaces in the Lens cluster settings. 
Currently, Lens is not able to list the available namespaces in Openshift clusters and the user needs to add one Lens cluster connection for each namespace/"project" he wants to connect to. The user is currently not able to switch between namespaces in an Openshift cluster without switching to another Lens cluster connection (for that specific namespace he wants to connect to).
