### ISSUE TITLE
Error reporting MAC connection to Docker-Desktop

### ISSUE THREAD

**Issue by pptfz** [lensapp/lens#493]
I made the following mistake when I used Lens to connect to the Docker-Desktop Times on the MAC
Both Docker and Kubernetes are running
```
2020/06/18 08:42:17 http: proxy error: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
```

macos10.14
docker-desktop version 2.3.1.0
docker version 19.03.8
kubernetes version 1.16.5

**Comment by sunnoy** [comment]
how to enable debug mode

**Comment by nilayparikh** [comment]
Hello, facing same issue with windows docker desktop, if anyone has a working solution? Thanks in advance.
