### ISSUE TITLE
Can't upload cluster icons with special characters in filename

### ISSUE THREAD

**Issue by nevalla** [lensapp/lens#494]
**Describe the bug**
When trying to upload cluster icon containing for example japanese letters, the icon file is not generated correctly and user see corrupted image as cluster icon.

**Expected behavior**
Cluster icon should be uploaded correctly and user can see it properly.

**Comment by nevalla** [comment]
Maybe we should rename images on upload to use Lens generated filenames.

**Comment by Nokel81** [comment]
This has been fixed in the conversion of cluster settings to react

**Comment by nevalla** [comment]
Fixed in #613
