### ISSUE TITLE
support for keyboard zoom +/-

### ISSUE THREAD

**Issue by philipgeraldtaylor** [lensapp/lens#495]
**What would you like to be added**:

**Why is this needed**:

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: <the OS Lens app runs on in your case>

**Comment by philipgeraldtaylor** [comment]
Awesome product - has enhanced our workflow - really need this feature to compete with VSCode et al

**Comment by jakolehm** [comment]
Lens already has zoom but the implementation is a bit buggy.

**Comment by philipgeraldtaylor** [comment]
Sure is - I see it in the View menu but can't get it to fire either from mouse or hotkey.

Hopefully it gets fixed, would be really useful.
