### ISSUE TITLE
Lens UI does not function after cluster upgrade until you sign out / sign back in 

### ISSUE THREAD

**Issue by pre** [lensapp/lens#5]
If your browser is logged in to Lens and the cluster is upgraded, all you get is 50% working Lens with weird error messages.

Expected: Lens should force re-authentication instead of allowing clicking around with a broken experience.

**Comment by jakolehm** [comment]
Most likely upgrade has (accidentally?) removed user role bindings. It makes no difference to logout/login because it would end up in similar errors.. is this the case?

**Comment by aleksfront** [comment]
Closed due to lack of response.
