### ISSUE TITLE
The k8slens twitter account has been suspended

### ISSUE THREAD

**Issue by NeckBeardPrince** [lensapp/lens#508]
https://twitter.com/k8slens

![image](https://user-images.githubusercontent.com/6558867/85314278-e17a7780-b47e-11ea-9930-a8fb39a97e72.png)

**Comment by miskun** [comment]
Yes, we know. Twitter has suspended the account for absolutely no reason. We have been trying to contact Twitter to activate the account but so far no response. Would be great to have this account available to share news about Lens development and for community engagement.

**Comment by nevalla** [comment]
Fixed by Twitter
