### ISSUE TITLE
exec: exec: "doctl": executable file not found in $PATH

### ISSUE THREAD

**Issue by nhalstead** [lensapp/lens#512]
**Describe the bug**
My Cluster runs on Digital Ocean so as if you were using EKS you need the client to access the cluster. In my case on Digital Ocean, I am using `doctl` installed via homebrew, for some reason when running it from the app menu it does not detect `doctl` but it works from cli.

**To Reproduce**
Select a kube config that uses the `doctl` exec step.

**Expected behavior**
Use the `doctl` cli connection 

**Screenshots**

![Screenshot from 2020-06-23 10-23-29](https://user-images.githubusercontent.com/5577816/85415713-a7bb7680-b53b-11ea-903b-cbe2ec3b0862.png)

**Environment:**
- Lens Version: 3.5.0.20200615.15
- OS: PopOS
- Installation method: AppImage
 
**Logs:**
Works when I run from the CLI but not from the app list calling it to run.
```
tk-Message: 10:26:09.003: Failed to load module "appmenu-gtk-module"
info: Checking for update
info: Update for version 3.5.0 is not available (latest version: 3.5.0, downgrade is disallowed).
info: Downloading kubectl 1.16.8 from https://storage.googleapis.com/kubernetes-release/release/v1.16.8/bin/linux/amd64/kubectl to /home/nhalstead/.config/Lens/binaries/kubectl/1.16.8/kubectl
warn: PrometheusLens: failed to list services: [object Object]
warn: PrometheusLens: failed to list services: [object Object]
warn: PrometheusLens: failed to list services: [object Object]
warn: PrometheusLens: failed to list services: [object Object]
info: using lens as prometheus provider
info: using lens as prometheus provider

```

**Kubeconfig:**

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XYZXYZXYZXYZXYZXYZXYZXYZXYZ
    server: https://XYZXYZXYZXYZXYZXYZXYZXYZXYZ.k8s.ondigitalocean.com
  name: do-nyc3-do-nyc-kubtest
contexts:
- context:
    cluster: do-kubtest
    user: do-kubtest-admin
  name: do-kubtest
current-context: do-kubtest
kind: Config
preferences: {}
users:
- name: do-kubtest-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kubernetes
      - cluster
      - kubeconfig
      - exec-credential
      - --version=v1beta1
      - --context=default
      - XYZXYZXYZ
      command: doctl
      env: null
```

**Additional context**
When I run `where doctl` it is in the path since I do get a returned value.
I use `zsh` as my shell but the config to include the homebrew is in a common config that applies to `zsh` and `bash`.
In addition, I've checked the `.profile` file and updated that to include the paths for brew and the same result after making the change and logging out and back in.

```bash
> where doctl
/home/linuxbrew/.linuxbrew/bin/doctl
```

**Comment by jnummelin** [comment]
Have you tried by adding the full path of doctl into the Kube config when importing into Lens? The issue AFAIK is that when running Lens from app menu, it does not really run all the .profile etc stuff

**Comment by nhalstead** [comment]
Thank you @jnummelin for the thought, with Lens being launched from the app menu not loading `$PATH` from the dotfiles I did a bit of googling and found a few articles of getting this to work for other applications and this is what worked for me.

This will create the link between the brew installed file to the global bin that is accessible by Lens' Path. This also allows for `doctl` to be updated by brew this will continue to be up-to-date.
```sh
sudo ln -s /home/linuxbrew/.linuxbrew/bin/doctl /usr/bin/doctl
```
