### ISSUE TITLE
Typo on pre-installed Prometheus url in settings

### ISSUE THREAD

**Issue by lehno** [lensapp/lens#518]
When using Helm as pre-installed Prometheus, there's a typo on the URL.
```http/:/```

OS: Windows 10
Lens version: 3.5.0

![image](https://user-images.githubusercontent.com/5764569/85589608-9a85b100-b63b-11ea-9b49-eb3099a54566.png)

I'm unable to update the field. It throws a nodejs error saying Headers cant be set after they are sent.

**Comment by sdil** [comment]
@jakolehm can I work on this?

**Comment by jakolehm** [comment]
@sdil go ahead 👍

**Comment by sdil** [comment]
Thanks @jakolehm

**Comment by lehno** [comment]
Any workaround until a fix?

**Comment by Nokel81** [comment]
Is this still a problem, I cannot seem to reproduce this.
