### ISSUE TITLE
Connection problem to self-signed tls certificates

### ISSUE THREAD

**Issue by bbkgh** [lensapp/lens#52]
I have problem with connecting to clusters that have self-signed certificates.
I can connect to them with my kubectl and i've put 
insecure-skip-tls-verify: true
in it's kubeconfig but seems that Lens doesn't consider that.
it tells:
Unable to connect to the server: x509: certificate is valid for INTERNALIP not PUBLICIP
How can i fix this?
Thanks

**Comment by jnummelin** [comment]
Usually all kube certs are "self-signed", so there's a cluster-wide CA cert on the master(s) which is used to sign the other certs including the API serving certificate.

It is true that currently (2.2.0 version) Lens does not fully respect the `insecure-skip-tls-verify: true` flag on kubeconfig. We have already fix cooking for that but unfortunately did not make it into 2.2.0 release.

One way to overcome this could be to inject the CA details into the config, so something like:
```
- cluster:
    certificate-authority: /Users/jussi/.minikube/ca.crt
    server: https://10.211.55.3:8443
  name: minikube
```

That way the client used to connect to the cluster validates the API cert against the provided CA cert. This is actually how most clusters are configured, either pointing `certificate-authority` to a file or embedding the base64 encoded PEM cert into `certificate-authority-data` attribute.

**Comment by nevalla** [comment]
Lens app respects now `insecure-skip-tls-verify: true` option. Please re-open if the problem is still relevant.
