### ISSUE TITLE
Multi-tab navigation

### ISSUE THREAD

**Issue by amuraru** [lensapp/lens#521]
**What would you like to be added**:
Multi-tab navigation support.

**Why is this needed**:
It would be super useful to have the ability to open multiple tabs in Lens so user can navigate through various resournces and move faster between tabs.

**Environment you are Lens application on:**
ALL

**Comment by jakolehm** [comment]
Tabbed interface is now available, see https://k8slens.dev/blog/lens-just-got-better-october-2024 .
