### ISSUE TITLE
Terminal broken when using the Snap version

### ISSUE THREAD

**Issue by HristoA** [lensapp/lens#53]
**Describe the bug**
Terminal not working and after few click on refresh button get error 

**To Reproduce**
1. Go to your Lens app
2. Click on Terminal button in bottom

**Expected behavior**
Terminal to open as Web version of Lens

**Screenshots**
![image](https://user-images.githubusercontent.com/20325836/67492095-96555e00-f67e-11e9-9a73-518298d6b015.png)

**Environment (please complete the following information):**
- Lens Version: 2.2.0
- OS: [e.g. OSX] Ubuntu 18.10
- Installation method (e.g. snap or AppImage in Linux): snap
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by kke** [comment]
What does `echo $SHELL` say in a regular terminal?

**Comment by HristoA** [comment]
```
xxx@worker2:~# echo $SHELL
/bin/bash
```

**Comment by HristoA** [comment]
On my personal PC is `/bin/zsh` On server is `/bin/bash`

**Comment by jakolehm** [comment]
@HristoA could you test AppImage version (instead of snap)? There are still permission issues with snap installation which are out of our hands (we are waiting for classic confinement approval).

**Comment by HristoA** [comment]
Terminal work on AppImage version. My bad that i miss to test it on AppImage version also.

**Comment by kke** [comment]
Still a bug for the snap so let's keep open.

**Comment by jakolehm** [comment]
Snap has classic confinement so this should be fixed.
