### ISSUE TITLE
Wrong created time

### ISSUE THREAD

**Issue by dostalradim** [lensapp/lens#530]
![Snímek obrazovky 2020-06-26 v 8 19 41](https://user-images.githubusercontent.com/9046924/85827161-fbb99b80-b785-11ea-930a-6cdf0a784b0d.png)

Some bug is probably in created time. Look at this image there should be something like 19h ago but there is 1 day and 19 hours. Is it bug or could it be some my local issue? I have 3.5.0 version and 1.16 k8s cluster version.

Thank you!

**Comment by nevalla** [comment]
Sounds like a bug. Please can you confirm that `kubectl` output shows `19h` ago?

**Comment by dostalradim** [comment]
Off course. 
```
$ kubectl get pod  jh-camunda-7fdfdd9bcf-fpvcv -o yaml | grep creation
  creationTimestamp: "2020-06-25T10:19:51Z"

$ kubectl get pod  jh-camunda-7fdfdd9bcf-fpvcv 
NAME                          READY   STATUS    RESTARTS   AGE
jh-camunda-7fdfdd9bcf-fpvcv   1/1     Running   0          20h
```

Is it enough? Thank you!

**Comment by nevalla** [comment]
Yes, thanks. Bug confirmed.

**Comment by Nokel81** [comment]
I cannot seem to reproduce this on my end. Even adding a recently created kube cluster displays correctly. May I ask for some version information?

**Comment by dostalradim** [comment]
Thank you for your time.
I have three nodes on **`Linux k8s-master1 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1+deb9u1 (2020-06-07) x86_64 GNU/Linux`** with installed kubelet and kubeadm packages in version **1.16.10-00** and using Lens in version **3.5.0** on **macOS Catalina 10.15.5**.
