### ISSUE TITLE
Add to homebrew install for macOS

### ISSUE THREAD

**Issue by carlowahlstedt** [lensapp/lens#533]
**What would you like to be added**:
The ability to install lens using homebrew on macOS

**Why is this needed**:
It makes the install process easier, more accessible for people, and an easier tool manage in general for macOS

**Environment you are Lens application on:**
None yet, just trying to install it...

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: macOS

**Comment by nevalla** [comment]
Fixed via #511

**Comment by carlowahlstedt** [comment]
😲
