### ISSUE TITLE
assign spesific port lensapp/lens

### ISSUE THREAD

**Issue by zainal-abidin-assegaf** [lensapp/lens#535]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 
**Logs:**

**Kubeconfig:**

**Additional context**
We want to install lensapp/lens in flatcar linux kuberbetes cluster server,

We see lens similar to vmware octant, for octant we used spesific port 8900 to access octant gui, so it's ip:8900 from the browser,

How to access lens ui, if we install lens in flatcar linux server and what if we want to access lens ui from specific port not from port 80/8080 ??

Than you

**Comment by Nokel81** [comment]
I don't this is is possible because the Lens UI relies on some specific electron APIs that are not available in a normal browser.
