### ISSUE TITLE
terminal font is invisibility on light mode

### ISSUE THREAD

**Issue by J0DKqH** [lensapp/lens#538]
![image](https://user-images.githubusercontent.com/23110635/85972962-f6698480-ba03-11ea-8623-339aef96efb7.png)

**Comment by J0DKqH** [comment]
![image](https://user-images.githubusercontent.com/23110635/85972997-0f723580-ba04-11ea-84b5-7397019ce5dd.png)

**Comment by J0DKqH** [comment]
my opearating system 
![image](https://user-images.githubusercontent.com/23110635/85973043-36306c00-ba04-11ea-84eb-aabb3663b43d.png)

**Comment by pashevskii** [comment]
@nevalla @jakolehm Is it relevant?  
There is [a commit](https://github.com/lensapp/lens/pull/1873) reverting white theme for tabs.
![image](https://user-images.githubusercontent.com/53330707/109141617-5c670100-7777-11eb-98b0-f3ba65bf8c97.png)

**Comment by Nokel81** [comment]
Closing in favour of to #1166
