### ISSUE TITLE
Allow global opt-out from advertising notifications

### ISSUE THREAD

**Issue by jcogilvie** [lensapp/lens#5387]
**What would you like to be added**:
I would like to select "never ask me again" for any kind of in-app notification re: kubecon or anything else.  (Note:  this is explicitly not related to in-app notifications about problems, etc.)

**Why is this needed**:
I will never be interested in one of these notifications.

**Environment you are Lens application on:**

- Kubernetes distribution: EKS
- Desktop OS: OSX

**Comment by Nokel81** [comment]
Such an option already exists under "User Preferences > Telemetry > Allow In-App Surveys".
