### ISSUE TITLE
ConfigMap value not showing properly on Lens UI

### ISSUE THREAD

**Issue by nevishs** [lensapp/lens#539]
I applied a configMap.yaml on k8s and the value is "something?somethingelse".

When checking via cmd on my terminal I see the full value 
but when I check it on the Lens interface, I see just "something" (not the full value) so everything after char "?" is not shown ...

**Comment by Nokel81** [comment]
Can you share a screenshot or two, I cannot reproduce this.

**Comment by nevishs** [comment]
Seems to be fixed now ....
