### ISSUE TITLE
Terminal broken when using fish shell

### ISSUE THREAD

**Issue by rocketraman** [lensapp/lens#54]
**Describe the bug**
My shell is set to `fish` by default. When opening the terminal, every command produces the following error output:

```
/bin/sh: ml: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `ml'
/bin/sh: module: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `module'
```

Since this seems like a prompt error, note I also use powerline-go for my prompt, my `fish_prompt` function is set as follows:

```
function fish_prompt
    #echo "$COLUMNS > "
    #set -gx COLUMNS $COLUMNS
    /usr/bin/powerline-go -error $status -colorize-hostname -shell bare -max-width 0 -modules nix-shell,user,host,ssh,cwd,perms,git,hg,jobs,exit,root,vgo
end
```

Some generic info about prompts in fish: https://fishshell.com/docs/current/tutorial.html#tut_prompt

**Comment by jakolehm** [comment]
@kke PTAL

**Comment by kke** [comment]
I've been using fish lately with the Agnoster theme without problems. 

@rocketraman which OS? Are you using the snap or appimage based lens?

Is the shell in terminal actually fish?

**Comment by rocketraman** [comment]
OS is Linux (Fedora 29). I'm using AppImage. The shell in the terminal is actually fish. Something is running at each prompt, but its not caused by `fish_prompt`:

I set the prompt temporarily like this:

```
function fish_prompt
  echo "> "
end
```

and now I get the output:

```
> 
/bin/sh: ml: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `ml'
/bin/sh: module: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `module'
```

so the `/bin/sh` output is still somehow occurring at each prompt, but its not coming from the `fish_prompt` function. I don't know what is executing at each prompt.

**Comment by rocketraman** [comment]
BTW, this is still an issue with 2.4.0.

**Comment by jakolehm** [comment]
@rocketraman does this still happen?

**Comment by rocketraman** [comment]
Nope, its fine now!
