### ISSUE TITLE
Port-Forwarding does not keep connection alive

### ISSUE THREAD

**Issue by spyro2000** [lensapp/lens#541]
**Describe the bug**
Port-Forwardings get broken after a few minutes if there is no traffic.

**To Reproduce**
1. Start port-forwarding of HTTP service
2. Open browser and ensure it's working
3. Relead browser tab after 5 minutes or so

**Expected behavior**
Port-Forward is kept alive or is automatically recreated

**Environment (please complete the following information):**
- Lens Version: 3.5.0
- OS: Win 10 x64 Prof 1819

**Comment by spyro2000** [comment]
(respectful ping)

**Comment by astanciu** [comment]
Running into this as well, also not clear how to recover from this beyond restarting Lens. Clicking the service links tries to reuse the broken ports. Would be nice if the UI showed an icon next to the port links indicating an active port-forward is in place. Maybe another icon that can be clicked to manually kill the connection too
