### ISSUE TITLE
Custom ports for port-forwarding

### ISSUE THREAD

**Issue by spyro2000** [lensapp/lens#542]
**What would you like to be added**:
When creating a port-forwarding it should be possible to set a custom port instead of having to use a random one

**Why is this needed**:
Postman / Browser Bookmarks should still work when recreating the port-forwarding.

**Environment you are Lens application on:**
- Desktop OS: Win 10x 64

**Comment by hazemarian** [comment]
also it will be so good to add option to close the process

**Comment by MichaelLebrand** [comment]
I rather like the way VS code's k8s plugin implements this, you can just right click a pod and select port-forward which brings up:
![Screenshot 2020-09-15 at 14 51 25](https://user-images.githubusercontent.com/33238287/93302943-03279880-f7fb-11ea-8590-6dbb5b1946f3.png)

**Comment by jim-docker** [comment]
fixed by #3922
