### ISSUE TITLE
(Windows 10) Add ability to point a config directory.

### ISSUE THREAD

**Issue by damntourists** [lensapp/lens#549]
**What would you like to be added**:
In windows 10, it's not immediately obvious where I need to store the `config` file in order for Lens to auto-detect it when adding a new cluster. It would be cool if I had an option to point to another folder that contains the config.

**Why is this needed**:
DigitalOcean configs expire after 7 days, so I have a weekly cron that runs on a machine on my home network which is responsible for refreshing it with their `doctl` utility. Unfortunately  I can't point Lens to the path where this config gets generated on my network and I can't create a shortcut to it either. Not only that, I'm not sure where this file would live on Windows for Lens to automatically detect it. I find it a bit inconvenient that I have to remove/add my cluster weekly.

**Environment you are Lens application on:**
Not sure I understand this question 

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...] Whatever DigitalOcean provides. I'm unsure.
- Desktop OS: <the OS Lens app runs on in your case>Windows 10. I don't have this issue under Linux.

**Comment by ppalucha** [comment]
Or just add option general option to point to any existing config file. For example, eks has option to generate kubeconfig as .kube/eksctl/clusters/<cluster name>, currently you need to copy-paste content of this file to connect to cluster.

**Comment by Nokel81** [comment]
Lens currently saves the file location that you pass it if you add the cluster by "file-picking" the config file.

Would you be able to clarify what you mean by "for Lens to auto-detect it". As long as your cron job recreates the same file name then Lens will just continue to work.

**Comment by Nokel81** [comment]
Lens now uses sync by default so you can point lens at that folder and everything should work.
