### ISSUE TITLE
Add value diff between helm release versions and with defaults

### ISSUE THREAD

**Issue by nox-404** [lensapp/lens#553]
**What would you like to be added**:
* [ ] A diff between default values and user values
* [ ] A diff between old and new values between releases

**Why is this needed**:
That would provide easier insight as to what the user changed from the default
and what has changed between versions of the charts

**Environment you are Lens application on:**

- Kubernetes distribution: vanilla v1.18.3 "on-premise"
- Desktop OS: windows & archlinux

**Comment by nox-404** [comment]
Also using lens to update sets all values, which is hard to read most of the time.
Using and only setting the diff with defaults will reduce the size of those supplied values, making it easier

**Comment by osddeitf** [comment]
+1 for this.

I've recently have an issue with `ingress-nginx`. At previous release I use just a minimal override values, but the newer version have very much changes such that my **merged values with the default values** not work anymore.

I was giving another hours to debug, diff and fix but still not work, and my cluster not tolerant long downtime, so I gave in and reinstall it.

Definitely by separating default with **USER-SUPPLIED VALUES** are important for making upgrade, edit, patch easier. Just so you know, `helm repo update` command upgrade all the charts to newest version, user may oblivious to changes, and this may cause things break.

**Comment by osddeitf** [comment]
I suggest that there is a checkbox switching back and forth from "show user-supplied values only" or merged values.

**Comment by osddeitf** [comment]
I found the culprit line: https://github.com/lensapp/lens/blob/eb5a775a2d884ea27e2398f186034d39064a49c3/src/main/helm/helm-release-manager.ts#L93
If I have time, I'll dig into it and may open a new PR.
