### ISSUE TITLE
Revealing a secret closes the pod details page

### ISSUE THREAD

**Issue by McGregsen** [lensapp/lens#560]
**Describe the bug**
Clicking on the reveal secret icon in the pod detail page immediately closes the details page.

**To Reproduce**
1. Go to workloads
2. Click on pods
3. Select a pod that has a secret mounted as an environment variable
4. Click the eye icon to reveal the secret
5. Details page of the pod is being closed

**Expected behavior**
The secret should be revealed instead of closing the details page.

**Environment (please complete the following information):**
- Lens Version: 3.5.1
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): Binary
 

**Additional context**
The issue occurs for multiple different clusters. Revealing the secret works when viewing it directly under configuration > secrets.
It sounds very similar to https://github.com/lensapp/lens/issues/473 which according to the reporter just magically resolved itself.

While I was writing down the issue and following the steps to reproduce it again I noticed that it works for the first secret on the detail page of a pod but as soon as I try to reveal another secret (even for the same pod) the details page will close. And after the issue has occured once it will always happen even for the secret that worked initially.

**Comment by VincentVerweij** [comment]
I have the exact same issue as mentioned here. Version is also 3.5.1 and OS is Windows 10.
When I tried to reproduce it I noticed the following: Close Lens, do the steps to reproduce as mentioned by the Author until step 3.

On the pod's details sidepane, I have for my pod in the environment variables 3 eye icons. When clicking the first 2, it remains open. But when the third one is clicked, the sidepane closes. When reopening the pod's details, a single eye icon click closes the sidepane.

This stays like this, until you restart the Lens app. Then you can reproduce my earlier mentioned steps.

**Comment by xeago** [comment]
Doesn't just occur on windows; seeing it on MacOS too, patched to date on OS and Lens (3.5.1).

**Comment by moreinhardt** [comment]
Happens on Ubuntu 20.04 with snap install (Lens 3.6.4) too. I've seen it sporadically work though. Really annoying :slightly_frowning_face:

**Comment by McGregsen** [comment]
Hello,
I can confirm that this is fixed in 3.6.5.
Thanks.

**Comment by aleksfront** [comment]
@McGregsen You're welcome!
