### ISSUE TITLE
Fuzzy display on Apple Pro Display XDR

### ISSUE THREAD

**Issue by moh-abk** [lensapp/lens#562]
**Describe the bug**
Opening the application shows a fuzzy display. When a cluster is selected, everything works as expected.

**To Reproduce**
1. Open the application

**Expected behavior**
Initial screen should show correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/7813457/86610253-fd186e80-bfa4-11ea-80a2-e37080808113.png)

**Environment (please complete the following information):**
- Lens Version: Version: 3.5.1
- OS: Catalina
- Installation method (e.g. snap or AppImage in Linux): Git release

**Comment by wlisac** [comment]
@moh-abk was there a reason this issue was closed? I'm seeing the same behavior in Lens version 3.6.7.
