### ISSUE TITLE
Login fails - SSL error on localhost

### ISSUE THREAD

**Issue by cristi-paraschiv** [lensapp/lens#5623]
**Describe the bug**
Cannot login into Lens.

**To Reproduce**
1. Open lens, it prompts me to log-in
2. Click on Login with Google
   - same thing happens for Login with GitHub       
3. I get a redirect to `https://localhost:53225/login?state=...`
4. This URL fails to load in the browser (Chrome) with error `ERR_SSL_PROTOCOL_ERROR`
   - same URL also fails to load in Firefox with error `SSL_ERROR_RX_RECORD_TOO_LONG`

**Expected behavior**
The redirect should log me in.

**Screenshots**
![image](https://user-images.githubusercontent.com/49153541/173565644-0f84742d-f396-4350-b792-18fa0b1359c0.png)

**Environment (please complete the following information):**
- Lens Version: 5.5.4.0
- OS: Windows
- Installation method: Installer

**Comment by Nokel81** [comment]
Do you have an "https everywhere" extension installed? The callback is `http://localhost` currently.

**Comment by cristi-paraschiv** [comment]
@Nokel81 no, I don't use such extension and I've disabled almost all of them to make sure.
 but I get a 307 Internal Redirect from the http endpoint to the https one. I have no clue what's triggering that, I temporarily disabled the setting in Chrome

![image](https://user-images.githubusercontent.com/49153541/173590821-dbb5c58a-01cf-4c80-adc5-fe4bbbaf896c.png)

![image](https://user-images.githubusercontent.com/49153541/173591191-34ef04ac-130b-4615-9dc4-9063d11d8b97.png)

**Comment by cristi-paraschiv** [comment]
Taking a closer look at the redirect I noticed the `Non-Authoritative-Reason : HSTS` response header; seems that Chrome's HSTS policy was the root cause.
I went to `chrome://net-internals/#hsts` and deleted the policy for localhost and the login worked. Thanks for your help.

![image](https://user-images.githubusercontent.com/49153541/173592578-f6b0ceaa-767f-44f4-85a8-074b87eac27c.png)

**Comment by chenhunghan** [comment]
@cristi-paraschiv thanks for reporting back!
