### ISSUE TITLE
Can't Select Custom Resources

### ISSUE THREAD

**Issue by kferrone** [lensapp/lens#564]
**Describe the bug**
I just updated to 3.5.1 and now nothing in the Custom Resources section is selectable. 

**To Reproduce**
1. select anything in the custom resources

**Expected behavior**
The sidebar with all the options and information will open up on the right just like everything else in lens.

**Comment by nevalla** [comment]
#658 fixes versioned CRD api and will be included in `3.6.0`. Please re-open if you still see this with `3.6.0`
