### ISSUE TITLE
Cannot show 'Last State' in Pods

### ISSUE THREAD

**Issue by chengshiwen** [lensapp/lens#568]
**What would you like to be added**:

Show 'Last State' in Pods, including Reason, Exit Code, Started and Finished Time.

**Why is this needed**:

When troubleshooting the cause of a restarting pod with lens app, I only see the current state's reason is 'CrashLoopBackOff', but I execute the command 'kubectl describe pod' and find the last state's reason is 'OOMKilled', which helps me find the problem.

**Environment you are Lens application on:**

- Kubernetes distribution: K8s 1.17.5 with kubespray
- Desktop OS: macOS Mojave 10.14.6
- Lens Version: 3.5.1

**Comment by jakolehm** [comment]
I think we already have this in Pod details.
