### ISSUE TITLE
Wrong chart version in release view when chart name contains numbers

### ISSUE THREAD

**Issue by vanto** [lensapp/lens#571]
The regex in [getVersion()](https://github.com/lensapp/lens/blob/55687b7d35496626e0da565a8b58a4546222b01f/src/renderer/api/endpoints/helm-releases.api.ts#L176) is not robust when chart names contain numbers.

**Example**

Chart name | Version | Expected
-------------|----------|-------------
foo42-chart-1.0.1 | 42-chart-1.0.1 | 1.0.1
foo-chart-1.0.1 |1.0.1 | 1.0.1

**Comment by vanto** [comment]
My (untested) suggestion would be a [positive lookbehind for a dash](https://regex101.com/r/Bo7eFL/1).



```diff
  getVersion() {
-    const versions = this.chart.match(/(v?\d+)[^-].*$/)
+    const versions = this.chart.match(/(?<=-)(v?\d+)[^-].*$/)
    if (versions) {
      return versions[0]
    }
    else {
      return ""
    }
  }
```

**Comment by pashevskii** [comment]
@vanto Fixed, thank you for finding the issue!
