### ISSUE TITLE
Feature to hide elements the user doesn't have permission to can't be reset

### ISSUE THREAD

**Issue by erick-thompson** [lensapp/lens#572]
The latest version introduced the feature that hides parts of the UI based on if the user has permissions to the backing object. So, for example, if the user doesn't have the permission to view Secrets, then the Secret part of the UI (both in Configuration -> Secrets and the Secrets within a pod). The bug is that this can't be reset. 

I appreciate that this feature prevents spurious errors from showing up all the time, but by removing the parts from the UI, it has caused considerable confusion for my users. For example, one user was not in a correct group, so they weren't able to view secrets. When they launched Lens, the Secrets section gone. I added them to the correct group so that they had access to Secrets again, but Lens continued to keep the Secrets UI hidden. In the end they had full permission to secrets verified via kubectl. 

I couldn't find a way to clear the existing values of isAllowed. The user eventually uninstalled and manually cleaned up all traces of Lens, then reinstalled it and it worked again. 

I think there should be either a way to reset the permissions (forcing them to be rechecked), or the permissions should be checked at startup. I think the second option is better, but both have their place. 

In general, hiding elements of the UI doesn't seem like a good idea. Can we disable them instead? Casual users won't notice the missing UI element, and so will not understand why they can't see secrets, or why their Lens instance looks different than someone else.

**Comment by Nokel81** [comment]
Currently, quitting and restarting lens (including the tray icon) should have fixed this once `list secrets` permissions are granted.

However, closing this in favour of #619
