### ISSUE TITLE
Merge titlebar and menubar on Linux

### ISSUE THREAD

**Issue by ghost** [lensapp/lens#575]
**What would you like to be added**:
Visual Studio Code on Linux allows us to merge the titlebar and menubar (so called `custom` title bar style).

**Why is this needed**:
This allows us to increase number of pixels for the content that matters in the app. It also improves the visuals of the application.

**Environment you are Lens application on:**

- Kubernetes distribution: AKS, RKE, K3s
- Desktop OS: GNU/Linux Fedora 32 (Gnome 3.36.3, Xorg)

![Screenshot from 2020-07-10 10-37-10](https://user-images.githubusercontent.com/59017104/87134716-592b0d80-c299-11ea-8c91-750546d5968c.png)

**Comment by Nokel81** [comment]
This has been done in https://github.com/lensapp/lens/pull/4528
