### ISSUE TITLE
Lens app stuck on loading page & also showing old data not current status

### ISSUE THREAD

**Issue by shawel** [lensapp/lens#577]
I see loading screen very frequently the last few releases for pods, services, node etc. I have to close and open lens. Also a bug is new data like pod creating, terminating seems to lag. i terminated a pod uing kubectl and len does not update unless restart sometimes. 
<img width="1368" alt="Screen Shot 2020-07-10 at 10 14 40 AM" src="https://user-images.githubusercontent.com/625370/87164138-6266ab00-c296-11ea-8ef3-dc085edd4a65.png">

Great work!!

**Comment by Nokel81** [comment]
Would you be able to provide more information? Such as logs, rbac restrictions, os, version.

**Comment by shawel** [comment]
this was in an old version of lens at the time i opened it. I did not encounter it for sometime now.
