### ISSUE TITLE
Way to return view to "all namespaces"

### ISSUE THREAD

**Issue by jonathanlang** [lensapp/lens#578]
**What would you like to be added**:
By default, I have all namespaces displayed in Lens. When I select one of the namespaces from the dropdown, I have not found a way to return to the "all namespaces" view without restarting Lens. 

**Why is this needed**:
Having a way to look at all namespaces is very convenient, so it should be possible to single out a namespace and then return to the overview of all ns. 

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...] Kubespray, k8s v.1.15
- Desktop OS: Windows 10 1909

**Comment by dan-slinky-ckpd** [comment]
You just unselect the namespace by clicking on it again, so it removes the tick next to the namespace..

**Comment by UnleashSpirit** [comment]
Yes but if you have lots of namespaces selected this is not easy.
However if you go to "Overwiew", under "Workloads", there is "CURRENTLY APPLIED FILTERS" above circle graph with a reset button which, I think, does what you want.

**Comment by jonathanlang** [comment]
Thanks, this helps a lot!
