### ISSUE TITLE
Proxy requests to cluster

### ISSUE THREAD

**Issue by hadim** [lensapp/lens#579]
Would be nice to have a feature equivalent to `kubectl proxy`. For example, in Lens in the Services list we could have a proxy button similar to the ones to access log and ssh. Upon clicking on it, ` kubectl proxy` feature would started, then Lens could open a new page directing to the service. Similar to `http://localhost:8001/api/v1/namespaces/argo/services/http:argo-server:2746/proxy/workflows`

Not sure whether it is technically possible. Let me know your thoughts.

**Comment by hadim** [comment]
Looks related to https://github.com/lensapp/lens/pull/528

**Comment by Nokel81** [comment]
Is this still desired? I am slightly confused as to what you are asking for. Lens uses a proxy itself but I think you are asking about something else.

**Comment by Nokel81** [comment]
Is this still desired? I am slightly confused as to what you are asking for. Lens uses a proxy itself but I think you are asking about something else.

**Comment by hadim** [comment]
Already available from #528. Closing.
