### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by darkforest42** [lensapp/lens#58]
![截屏2019-10-31上午10 12 16](https://user-images.githubusercontent.com/7768408/67913350-b8436900-fbc7-11e9-82e9-15a7c64d6af0.png)
![截屏2019-10-31上午10 12 24](https://user-images.githubusercontent.com/7768408/67913356-bda0b380-fbc7-11e9-9c0e-8ad258e32898.png)
![截屏2019-10-31上午10 12 56](https://user-images.githubusercontent.com/7768408/67913360-c1343a80-fbc7-11e9-963a-3a5885649ff7.png)

**Comment by aleksfront** [comment]
This is a known issue which already has been fixed and will be available in the upcoming release. Thanks!
