### ISSUE TITLE
A different way to display clusters on the side pane - have lots of clusters I manage

### ISSUE THREAD

**Issue by paulchoi-nuro** [lensapp/lens#586]
**What would you like to be added**:
Lens represents each cluster in a colorful, randomly-generated icon. I have 20+ clusters I manage and I'd prefer to have a list view (or some other clever way)

**Why is this needed**:
I have 20+ clusters I manage. It's annoying to have to mouse-over each icon to figure out which cluster I want to select.

**Environment you are Lens application on:**
MacOS Catalina 10.15.5

- Kubernetes distribution: GKE, Ubuntu bare-metal
- Desktop OS: MacOS Catalina 10.15.5

**Comment by nevalla** [comment]
You can create multiple workspaces and that way group your clusters in separate logical groups. Does this bring any help to your problem?

**Comment by paulchoi-nuro** [comment]
Yes, that would be very helpful. Likely, I can have a workspace per project in GCP.
I do not see a way to create workspaces... is there a specific version I need to get, or take some action?

**Comment by paulchoi-nuro** [comment]
Ok, so I found the workspace button at the very bottom right. It was so small that I never noticed.
(Actually with Lens 3.6, the workspace button is at the bottom left corner)

I'll give that a shot. I think workspaces would help a lot. Thank you.
