### ISSUE TITLE
Improve NetworkPolicy Side Panel View 

### ISSUE THREAD

**Issue by andyliddle** [lensapp/lens#587]
**What would you like to be added**:

Change the display of the Ingress / Egress Rules to be clearer which ports relate to each rule

**Why is this needed**:

It's a bit confusing as the spec says to specify From/To before the port,  but the other way round is also allowed.  

**Environment you are Lens application on:**

- Kubernetes distribution: AKS, [Bare-Metal]
- Desktop OS:  Windows 10

**Comment by Nokel81** [comment]
![Screen Shot 2021-03-24 at 12 46 36 PM](https://user-images.githubusercontent.com/8225332/112349283-f9e22180-8c9e-11eb-912d-514f0a3e9f4e.png)

I think that the above is pretty clear. There is a header for `Egress` and a header for `Ingress`.
