### ISSUE TITLE
Problem in release version column with number in the middle of app name

### ISSUE THREAD

**Issue by dostalradim** [lensapp/lens#588]
Hi, it looks like some small bug. Lens version is 3.5.1

![Snímek obrazovky 2020-07-16 v 13 58 52](https://user-images.githubusercontent.com/9046924/87668910-5171da00-c76d-11ea-9557-c4c3f332cb6b.png)

**Comment by vshakirova** [comment]
Hi guys, I'd like to fix this bug and I've spent some time and found how we can fix it. Chart's versions are expected to follow Semantic Versioning.
There is a regular expression `(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$` from `https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string` and we can use it in code. 
Also, I took a look at `semver` package, it has `coerce()` func, but it cuts the original version and leaves only X.Y.Z fields. Could you tell me please, what do you think about it?

**Comment by pashevskii** [comment]
It should be fixed by the commit https://github.com/lensapp/lens/pull/2226, @aleksfront could you please to close the issue?
@vshakirova , I'm not sure that we should use so strict expression for extracting version

**Comment by Nokel81** [comment]
fixed by #2226
