### ISSUE TITLE
sensible unit for graphs

### ISSUE THREAD

**Issue by matti** [lensapp/lens#589]
23.703mi vs 2500000000000000000 makes no sense:

![image](https://user-images.githubusercontent.com/3893/87673415-2db69000-c77d-11ea-83f9-d7ed93369760.png)

**Comment by matti** [comment]
![image](https://user-images.githubusercontent.com/3893/87765475-8723cb00-c820-11ea-8679-65cbbb0c1aa3.png)

**Comment by Nokel81** [comment]
Fixed by #450.

![Screen Shot 2021-03-24 at 12 52 15 PM](https://user-images.githubusercontent.com/8225332/112350678-c3f16d00-8c9f-11eb-9ef0-e8c477840baf.png)
