### ISSUE TITLE
Customize / Disable node-shell

### ISSUE THREAD

**Issue by kgelinas** [lensapp/lens#590]
Provide a way to customize the pods to do node Shell.
Because corporate environment does not always permit access to docker.io

- Kubernetes distribution: AKS
- Desktop OS: Windows

**Comment by gorkemozlu** [comment]
any idea when this enhancement fulfills ?

**Comment by john-adkins** [comment]
I would like to disable the node-shell pod from being deployed too. Our AKS cluster has some Windows nodes and this causes node-shell to repeatedly fail because it cannot run on a Windows host.

**Comment by devopsmariocom** [comment]
Same here corporate airgapped environment desn't allow this.

All it needs is add setting option for node-shell image here https://github.com/lensapp/lens/blob/a03da3c5720bd392910c3e816c0b76aa38654a1f/src/renderer/components/%2Bpreferences/preferences.tsx and use it here https://github.com/lensapp/lens/blob/master/src/main/node-shell-session.ts#L78.  

WDYT @jakolehm @nevalla? If you agree I can give it a try and implement it.

**Comment by nevalla** [comment]
> WDYT @jakolehm @nevalla? If you agree I can give it a try and implement it.

Sounds good!

**Comment by awilkins-frel** [comment]
I have also hit this issue due to docker.io bringing in limits on anonymous pulls

**Comment by Nokel81** [comment]
This has been fixed by #3249

**Comment by meganeinu7** [comment]
@Nokel81 I am wondering how I can access this feature. I downloaded the latest version - Lens: 5.4.5-latest.20220405.1
, but I can't find the UI that I see in the fix (https://github.com/lensapp/lens/pull/3249)
Thanks!
