### ISSUE TITLE
Suspended CronJobs show up as 'Failed' in Overview Tab

### ISSUE THREAD

**Issue by tejas0908** [lensapp/lens#592]
Suspended CronJobs show up as 'Failed' in Overview Tab

<img width="210" alt="Screenshot 2020-07-17 at 6 21 16 PM" src="https://user-images.githubusercontent.com/1906831/87788233-a0e20400-c85a-11ea-8ce1-ce0772efb662.png">

**Comment by nox-404** [comment]
I did a PR fixing this, it will look like this if merged

![image](https://user-images.githubusercontent.com/5402193/90340233-fc88e400-dff6-11ea-9ba3-3841078741ab.png)

**Comment by nevalla** [comment]
Fixed in #694
