### ISSUE TITLE
Master donut graph for memory usage only appears to show one master

### ISSUE THREAD

**Issue by TJM** [lensapp/lens#594]
**Describe the bug**
While looking at our K8s cluster, it looked like we had very little memory utilization on the masters from the Cluster (overview?) screen. It only shows "24G" of memory usage, however when I switch to the nodes screen, *each* master is showing ~24G of usage (5 masters). The capacity has the entire total (~156GB), but the usage is only one node. NOTE: each master node is 8cpu/32GB ram.

**To Reproduce**
1. Connect to multi-master K8s cluster
2. Click on 'Cluster' - Look at memory stats
3. Click on 'Nodes' - Look at memory usage
4. See discrepancy

**Expected behavior**
The usage should be totaled up across all masters

**Screenshots**

* Cluster:
<img width="1182" alt="Screen Shot 2020-07-18 at 2 08 29 PM" src="https://user-images.githubusercontent.com/1641316/87861149-b4e04100-c900-11ea-8f5e-780361f96d38.png">

* Nodes:
<img width="1126" alt="Screen Shot 2020-07-18 at 2 08 48 PM" src="https://user-images.githubusercontent.com/1641316/87861154-be69a900-c900-11ea-8b3b-9d484f325d4b.png">

* top
```
top - 13:24:20 up 154 days, 22:07,  1 user,  load average: 0.40, 0.35, 0.39
Tasks: 254 total,   1 running, 253 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.4 us,  2.0 sy,  0.0 ni, 94.9 id,  0.5 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem : 32780228 total,   393364 free,  6213320 used, 26173544 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 24400856 avail Mem
```

* relevant sections of `kubectl desctribe node den3l1kubem01`
```
Allocatable:
  cpu:                8
  ephemeral-storage:  48291017853
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             32677828Ki
  pods:               110
System Info:
  Machine ID:                 c9850ddeedec4f3fbf42ed4adf76c9b3
  System UUID:                4239F086-537D-1AEB-2E1B-1F50B8E229C2
  Boot ID:                    6704c087-7a7a-4b6e-a691-9fcbc123eae8
  Kernel Version:             3.10.0-957.21.3.el7.x86_64
  OS Image:                   CentOS Linux 7 (Core)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  docker://18.6.3
  Kubelet Version:            v1.15.2
  Kube-Proxy Version:         v1.15.2
```

```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                1 (12%)     1 (12%)
  memory             170Mi (0%)  370Mi (1%)
  ephemeral-storage  0 (0%)      0 (0%)
  hugepages-1Gi      0 (0%)      0 (0%)
  hugepages-2Mi      0 (0%)      0 (0%)
```

**Environment (please complete the following information):**
- Lens Version: 3.5.1
- OS: OSX 10.14.6
- Installation method (e.g. snap or AppImage in Linux): image
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
# Setup Certificate and context if you haven't already
echo "-----BEGIN CERTIFICATE-----
#####(contents of CA stripped)
-----END CERTIFICATE-----
" \ > ca-den3ss.pem
kubectl config set-cluster den3ss --server=https://kubernetes-den3ss-api.company.com/ --certificate-authority=ca-den3ss.pem --embed-certs
rm ca-den3ss.pem
 
# Setup credentials
kubectl config set-credentials oidc-login@den3ss \
    --exec-command=kubectl --exec-arg oidc-login --exec-arg get-token  \
    --exec-api-version 'client.authentication.k8s.io/v1beta1' \
    --exec-arg '--oidc-issuer-url=https://dex-den3ss.company.com/'  \
    --exec-arg '--oidc-client-id=oidc-kubernetes-den3ss'  \
    --exec-arg '--oidc-client-secret=SUPERSECRETDONTLOOK' \
    --exec-arg '--oidc-extra-scope=groups' --exec-arg '--oidc-extra-scope=email'
kubectl config set-context den3ss --cluster=den3ss --user=oidc-login@den3ss
 
# Use Context
kubectl config use-context den3ss

```

**Additional context**

From what I can tell, the "node" statistics must be coming from node exporter (prometheus-operator). They must be reporting usage including buffer/cache... Something is inconsistent, not sure which is right, if either :)

**Comment by Nokel81** [comment]
This seems to be fixed by the react conversion. 

fixed by #585
