### ISSUE TITLE
Crash when trying to connect to cluster

### ISSUE THREAD

**Issue by aodpi** [lensapp/lens#597]
**Describe the bug**
When i'm trying to add a cluster and connect to it, the app just crashes. Previously this worked perfectly. I noticed that once I have tried to execute a shell into a pod, the app crashed and after I tried to launch it again, this problem appeared. Judging from the error message, it seems that the kubectl executable disappeared. 

**To Reproduce**
1. Click on `Add Cluster`
2. Provide your kube config file
3. Click on add cluster on the bottom.
4. Try to execute a shell into a pod of your choice
5. The app crashes.
6. Try to open the app again and connection to the cluster.

**Expected behavior**
The cluster should be added and the connection to it should begin.
**Screenshots**
![image](https://user-images.githubusercontent.com/6562956/87942926-fc540200-caa5-11ea-9c60-9a794d11ba93.png)

**Environment (please complete the following information):**
- Lens Version: 3.5.1
- OS: Windows 10 Version 2004 (Build 19041.388)
- Installation method: Windows Installer
 
**Logs:**
no logs..

**Kubeconfig:**
I'd rather not share kube config here. I used the same config previously and it worked fine. 

**Additional context**

**Comment by aodpi** [comment]
I've noticed that the kubectl is downloaded, created maybe when I try to add a cluster. But this time, when I'm trying to add, the binary is not created, for version 1.17.4

**Comment by aodpi** [comment]
On another machine the behavior is different. When trying to execute shell into a pod gives this error:

``` kubectl exec -i -t -n lens-metrics kube-state-metrics-6ff8665f98-zlfnj -c kube-state-metrics "--" sh -c "clear; (bash || ash || sh)"
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown
command terminated with exit code 126```

**Comment by nevalla** [comment]
> On another machine the behavior is different. When trying to execute shell into a pod gives this error:
> 
> ```
> OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown
> command terminated with exit code 126```
> ```

The error indicates that container does not include any shell binary. Are you able to execute shell with `kubectl exec`?

**Comment by aodpi** [comment]
> > On another machine the behavior is different. When trying to execute shell into a pod gives this error:
> > ```
> > OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown
> > command terminated with exit code 126```
> > ```
> 
> The error indicates that container does not include any shell binary. Are you able to execute shell with `kubectl exec`?

Yes, I was using kubernetes dashboard for that, I could execute the shell without any problems.

Update: You are right, that pod didn't include any shell binary. I've tried another pod and it executed successfully with no crash. Then the problem seems to be with that other machine.

**Comment by aodpi** [comment]
One more thing to notice is that after that crash lens becomes completely unusable, unless restarting the machine. Sign out will not help, a complete reboot will.

**Comment by Nokel81** [comment]
Is this still a problem now that you can point lens to your own version of `kubectl`?

**Comment by aodpi** [comment]
> Is this still a problem now that you can point lens to your own version of `kubectl`?

The problem has disappeared. That is because I reset my windows PC. Now everything works fine. Didn't encounter this issue since then.

**Comment by Nokel81** [comment]
Cool thanks. Please open a new issue if this appears again.
