### ISSUE TITLE
Kube config is not found on Windows

### ISSUE THREAD

**Issue by pawelpabich** [lensapp/lens#599]
**Describe the bug**

When I try to add a new cluster to Lens I don't see any of the clusters defined in my kube config. 
My kube config is in the default location.

![image](https://user-images.githubusercontent.com/347637/88015937-b8c0cd00-cb65-11ea-99f1-9c5abb425397.png)

**To Reproduce**
1. Go to 'File'
2. Click on 'Add Cluster'
3. Select to 'Select kubeconfig'
4. No existing clusters are shown

**Expected behavior**

Existing clusters are shown

**Screenshots**

![image](https://user-images.githubusercontent.com/347637/88015937-b8c0cd00-cb65-11ea-99f1-9c5abb425397.png)

**Environment (please complete the following information):**
- Lens Version: 3.5.1
- OS: Win 10 2004
- Installation method (e.g. snap or AppImage in Linux):  Exe
- Kubectl 1.14.2
 
Can I manually point Lens at my kube config?

**Comment by cslovell** [comment]
Similar issue - when I open lens, there are no clusters listed, even though there are several in my kubeconfig file. 

Lens Version 3.5.1
OS: Win 10 2004
Installation method: exe
kubectl v1.16.6-beta.0

**Comment by nevalla** [comment]
https://github.com/lensapp/lens/pull/740 allows users to select kubeconfig from filesystem. I still leave this open since app should find the default kubeconfig automatically.

**Comment by pawelpabich** [comment]
When I upgraded to beta2 I got this error

![image](https://user-images.githubusercontent.com/347637/92339000-341b1580-f0f7-11ea-8297-ea7784851020.png)

Maybe this is why the contexts were not listed.

`kubectl` seems to work fine.

![image](https://user-images.githubusercontent.com/347637/92339058-7c3a3800-f0f7-11ea-87cd-6ed456f1978b.png)

This is context  number 3

![image](https://user-images.githubusercontent.com/347637/92339103-bc011f80-f0f7-11ea-851d-ba4fe910a253.png)

**Comment by Nokel81** [comment]
Fixed by #1078 and related to #2343
