### ISSUE TITLE
UI Icons need to download for every cluster and unusable UI

### ISSUE THREAD

**Issue by andrejonathan** [lensapp/lens#60]
**Describe the bug**
When we are using Lens on a VPN and you add new cluster the UI icons dont download, resulting in an almost unusable UI.

**To Reproduce**
1. Be on a corporate VPN where Lens image urls cannot be be whitelisted
2. Click on add new cluster
3. Add kubectl contents
4. See  partially readable UI with no icons

**Expected behavior**
Download icons once or include them in package and reuse them across all cluster screens

**Screenshots**
<img width="321" alt="image" src="https://user-images.githubusercontent.com/36840575/67952641-459db200-fbf6-11e9-9daf-ebb887437bb9.png">

**Environment (please complete the following information):**
- Lens Version: Version: 2.3.2
- OS: MacOs Mojave
- Installation method : dmg

**Comment by ixrock** [comment]
It's fixed already. All required fonts (including icons) will be bundled with lens-app in next release.
related #58
