### ISSUE TITLE
Allow to expand/resize column headers

### ISSUE THREAD

**Issue by spyro2000** [lensapp/lens#601]
**What would you like to be added**:

Would love to expand individual columns to see the full pod/service names

**Why is this needed**:

Currently it's not possiblel to expand the column to see the full name of services/pods...

![image](https://user-images.githubusercontent.com/8479925/88028791-67024d80-cb39-11ea-8286-3d559b43ce73.png)

**Environment you are Lens application on:**

- Kubernetes distribution: (shouldn't matter)
- Desktop OS: Win10x64Prof

Thank you!

**Comment by nevalla** [comment]
Also reported in #350

**Comment by paul-theorem** [comment]
I'd like to see this as well. The relevant bits of my pods in argo jobs are cut off - can't see which pod is which.

**Comment by dsgreene713** [comment]
any updates on when this feature might be available?

**Comment by greedybro** [comment]
I'd like to see this implemented as well, since some columns are more relevant than others. Plus it would be amazing for readability on any size of screen.

**Comment by jamiejackson** [comment]
This is the most-requested Lens feature, by a fair margin. https://github.com/lensapp/lens/issues?q=is%3Aissue+is%3Aopen+org%3Agithub+sort%3Areactions-%2B1

**Comment by gilbrown123** [comment]
I would love to have it as well .

**Comment by RSLukin** [comment]
same here, please add this

**Comment by JackSinclairT** [comment]
Please please please please add this. The names of our nodes are quite big so being able to make 1 specific column bigger would help so much!!

**Comment by johnfoxcloudreach** [comment]
yes, please

Be very much appreciated

**Comment by Punkoivan** [comment]
2 years here, moving to atlassian-style issues, if you know what I mean...
I understand that this is open-source project, but as I can see it's already been 2 related PR (declined)
Along with https://github.com/lensapp/lens/issues/5444 I would say open source Lens is dead.

**Comment by laurensramandt** [comment]
It's useless to put in any effort into ANY issue as long as #5444 isn't fixed.

**Comment by twoTimesAgnew** [comment]
Would love to see this feature added! 
Currently, I need to hover over a pod name to see the important bit, the hash at the end.

**Comment by zerog2k** [comment]
This is also an issue when trying to connect to eks clusters, as the default kubecontext naming for them is quite long (arns like `arn:aws:eks:us-west-2:ACCOUNTID:cluster/eks-cluster-foo-bar-1`, and they truncate the names, and do not have any hover tool tip.

**Comment by darrenfurr** [comment]
I'm just one more person who would like to see column widths be adjustable.

**Comment by giuliocalzo** [comment]
yes, please

Be very much appreciated

**Comment by giuliocalzo** [comment]
yes, please

Be very much appreciated

**Comment by DevFontes** [comment]
Please, be very much appreciated!

**Comment by rust0258** [comment]
any updates on this requested feature, horizontal scrolling, column resizing, column filter, and column sorting, would make UX  much better

**Comment by waldner** [comment]
+1

**Comment by theblinkingusb** [comment]
Updated to v2023.8.291046-latest today and resizing working great for me! Thanks Lens team!

**Comment by bennesp** [comment]
This feature was implemented in Lens Desktop by Mirantis but not in this repository (which only contains OpenLens code). Can we have this feature ported in this repository ?

**Comment by takashoty** [comment]
Yes, please! Wanna see it in the future release or as a Extension. Thank you!

**Comment by erick-waterworth** [comment]
Yes PLEASE!!!

**Comment by asos-rickbruins** [comment]
I need this feature!

**Comment by jakolehm** [comment]
This is already implemented in Lens Desktop.
