### ISSUE TITLE
Restart deployment

### ISSUE THREAD

**Issue by SeriousM** [lensapp/lens#603]
**What would you like to be added**:
A way to restart all pods of a deployment.
This can be done by add/replace an annotation lensapp.kubernetes.io/restartedAt to spec.template.metadata.annotations like kubectl rollout restart. It can be used to restart the rollout of a Deployment, StatefulSet or DaemonSet.

Idea from here: https://github.com/kubenav/kubenav/issues/80

**Why is this needed**:
To restart all pods of a deployment

**Environment you are Lens application on:**

- Kubernetes distribution: [AKS]
- Desktop OS: Win10

**Comment by jdomag** [comment]
+1

**Comment by nevalla** [comment]
Thanks for the idea! Definitely something that can be added.

**Comment by adleong** [comment]
:+1:

**Comment by creativefctr** [comment]
This one can be really handy!

**Comment by teliaz** [comment]
+1

**Comment by mabdelfattah** [comment]
I think it should be an easy pull request to exec `kubectl rollout restart deployment {{deployment-name}}`

**Comment by pashevskii** [comment]
https://github.com/lensapp/lens/pull/1175 It seems it works
