### ISSUE TITLE
Closing Lens does not close the application

### ISSUE THREAD

**Issue by andrejonathan** [lensapp/lens#61]
**Describe the bug**
Clicking the red x to close Lens does not actually close the application but leaves it running and can be viewed in Activity Monitor

**To Reproduce**
1. Open Lens
2. Click red x to close Lens
3. Check Activity Monitor
4. See Lens not closed/exited

**Expected behavior**
When the red x is clicked the application should exit fully.

**Screenshots**
<img width="935" alt="image" src="https://user-images.githubusercontent.com/36840575/67953068-15a2de80-fbf7-11e9-9605-ef95ee933415.png">

**Environment (please complete the following information):**
- Lens Version: 2.3.2
- OS: [OSX Mojave
- Installation method DMG

**Comment by andrejonathan** [comment]
Ha I think this is a standard Mac thing :|

**Comment by miskun** [comment]
@andrejonathan Indeed, it's mac thing. Like you, I don't understand _why_ people like it like this, but it is the "standard" way :)
