### ISSUE TITLE
Diagram screen for ingress to pod

### ISSUE THREAD

**Issue by kallisti5** [lensapp/lens#62]
This is 100% a enhancement request.

The Kontena Lens tool is *AWESOME*. One thing that would make it even better is a "map" mode which shows the Ingress -> Service -> Deployment -> Pod configuration graphically per namespace. This would be a huge step forward in visualizing kubernetes deployments and rapidly finding relevant pods,services,etc.

**Comment by jnummelin** [comment]
Yes, this is definitely something we'll be working on. There's been some very early prototypes on this already... :)

**Comment by Nokel81** [comment]
Does https://github.com/nevalla/lens-resource-map-extension resolve this?

**Comment by Nokel81** [comment]
Closing as there is an extension that does this.
