### ISSUE TITLE
Failed to open port-forward

### ISSUE THREAD

**Issue by janavenkat** [lensapp/lens#634]
**Describe the bug**
Am trying to use the port-forwarding feature but it failed

**To Reproduce**
1. Go to services
2. Click on the service on the available service 
3. In Ports, section click the available link

**Expected behavior**
We should able to access the service locally using port-forward

**Screenshots**
![image](https://user-images.githubusercontent.com/28565699/89151038-4a660c80-d560-11ea-90a4-ced57e3eb581.png)

**Environment (please complete the following information):**
- Lens Version: 3.5.1
- OS: OSX

**Comment by Lp-Francois** [comment]
Same issue here


```
    Lens Version: 3.5.1
    OS: OSX
```

**Comment by gabrielbcn** [comment]
Same issue here. It fails randomly. Tends to work the second time. It looks like a timeout before it can complete the action.

**Comment by timurista** [comment]
A simple bump on the timeout fixed it for me. Opened a PR: https://github.com/lensapp/lens/pull/732

**Comment by nevalla** [comment]
Probably fixed by #732 and will be included in `3.6.0`. Please re-open if you still see this

**Comment by gimlichael** [comment]
I still encounter this .. Windows 10 Enterprise. Have to click multiple times. Is it possible to try to increase the timeout by myself? I could not find it under preferences.

And the behavior is not consistent. Sometimes it works a second times - other times not.
Sometimes it work restarting Lens .. other times not.

The common denominator for now is, that it seems to be related to local development; eg. services deployed to Docker Desktop. Lens is latest version.
