### ISSUE TITLE
Trying to access a gcloud cluster

### ISSUE THREAD

**Issue by olivierchatry** [lensapp/lens#64]
**Describe the bug**
Using lens to browse a gcloud cluster : 
```
Failed to refresh token: Command failed: "/usr/lib64/google-cloud-sdk/bin/gcloud" config config-helper --format=json /bin/sh: 1: /usr/lib64/google-cloud-sdk/bin/gcloud: not found
```
Gcloud is installed. I think the sandboxing of the application (AppImage) might be the cause.

**Comment by jnummelin** [comment]
AFAIK AppImage does not do much sandboxing that would prevent the app form calling other binaries. I assume you can call that `/usr/lib64/google-cloud-sdk/bin/gcloud` on normal shell without needing for sudo or such?

**Comment by olivierchatry** [comment]
Yeah, seems it is working on latest now. Not sure why. Closing.
