### ISSUE TITLE
Can not update K8s endpoint through Lens

### ISSUE THREAD

**Issue by Snaacker** [lensapp/lens#646]
**Describe the bug**
Can not update K8S endpoint through Lens.

**To Reproduce**
1. Go to 'Network/Endpoints'
2. Select any Endpoint on the list
3. Click Edit icon to edit Endpoint value
4. Click 'Save' or 'Save and Close'
5. Error popup is shown with content: `error: unable to recognize "/tmp/5d8b45e5c8e7536204e8ac24aa8b1ca6/resource.yaml": no matches for kind "Endpoint" in version "v1"`

**Expected behavior**
Endpoint should be updated successfully

**Environment (please complete the following information):**
- Lens Version: 3.5.1
- OS: Ubuntu 18.04.4
- Installation method (e.g. snap or AppImage in Linux): snap

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    server: https://xxx.yyy
  name: xxxx
contexts:
- context:
    cluster: xxxx
    user: xxxx
  name: xxxx
current-context: ""
kind: Config
preferences: {}
users:
- name: xxxx
  user:
    token: kubeconfig-u-xxxx
```

**Additional context**
This seem to be typo issue, the content of .yaml file are something like
```
kind: Endpoint
apiVersion: v1
metadata:
  name: mysql
  namespace: db
  selfLink: /api/v1/namespaces/db/endpoints/mysql
  uid: 72ee7fbc-8185-4ff0-9c84-75ab9da3bd9c
  resourceVersion: '123445327'
  creationTimestamp: '2020-05-20T13:05:35Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Endpoints","metadata":{"annotations":{},"creationTimestamp":"2020-05-20T13:05:35Z","name":"mysql","namespace":"db","selfLink":"/api/v1/namespaces/db/endpoints/mysql","uid":"72ee7fbc-8185-4ff0-9c84-75ab9da3bd9c"},"subsets":[{"addresses":[{"ip":"x.x.x.x"}],"ports":[{"name":"mysql-service-port","port":3306,"protocol":"TCP"}]}]}
subsets:
  - addresses:
      - ip: x.x.x.x
    ports:
      - name: mysql-service-port
        port: 3306
        protocol: TCP
```
kind should be `Endpoints` instead of `Endpoint`.
When I add missing `s` character in kind value, then I can update the endpoint successfully

**Comment by nevalla** [comment]
Thanks for reporting this. Got this re-produced and the fix should be trivial.
