### ISSUE TITLE
What are the requirements to make my prometheus deployment compatible with Lens?

### ISSUE THREAD

**Issue by marcofranssen** [lensapp/lens#656]
I want to deploy a prometheus deployment on my cluster using Helm.

Are there any specific requirements to make the metrics show up in Lens?

**Comment by Stono** [comment]
^^ +1 to this, i'm trying out lens too but have quite a bespoke prometheus setup so i'd need to know exactly what was required.

currently we don't see anything in terms of graphs, but it does seem to be pulling cpu and ram data in the pod list table from somewhere, i presume cadvisor?

**Comment by mboutet** [comment]
I managed to make it work with prometheus-operator (the bitnami prometheus-operator helm chart to be more precise). Check out the comments on this issue: https://github.com/lensapp/lens/issues/180. In the end, the key was to set `kube-state-metrics.serviceMonitor.honorLabels` to `true` (see https://github.com/lensapp/lens/issues/180#issuecomment-650432515) on top of the other instructions from the other comments.

**Comment by marcofranssen** [comment]
@mboutet It would be great if you or anyone with experience on this could add a PR which adds this to the documentation with clear steps to explain the exact requirements.

**Comment by Nokel81** [comment]
Closing in favour of #180.

I agree that a PR for a documentation change to help with getting metrics up an running would be much appreciated.
