### ISSUE TITLE
Add Cluster missing for 'custom' option on Windows version 3.5.2

### ISSUE THREAD

**Issue by cnukwas** [lensapp/lens#660]
**Describe the bug**
Installed latest lens version(3.5.2) for Windows from Github and selected 'custom' option. I see large textbox to enter data and I no longer see 'Add Cluster' button on the screen even after closing/opening the tool multiple times.

**To Reproduce**
1. Click + sign
2. Change 'Choose config' options to custom
3. Notice that Add cluster button is not on the screen anymore.

**Expected behavior**
See largex text box followed by Add cluster button under that.

**Screenshots**
![image](https://user-images.githubusercontent.com/63475948/89680301-b0d08f00-d8c0-11ea-94c0-ee7655e58f83.png)

**Environment (please complete the following information):**
- Lens Version: 3.5.2
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): .exe

**Comment by nevalla** [comment]
Should be fixed in `3.6.0`. Please re-open if you still experience this with 3.6.0.
