### ISSUE TITLE
Can`t edit ConfigMaps 

### ISSUE THREAD

**Issue by HristoA** [lensapp/lens#68]
**Describe the bug**
Editing the `ConfigMap` is not working. When i try to edit it and pres `Save` button nothing happen. On reload i see removed line to be there

**To Reproduce**
1. Go to `ConfigMaps` and edit some item
2. Click on `Save`

**Expected behavior**
ConfigMap element to be update/edited and right edit box to b hiden 

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 2.4.0
- OS: [e.g. OSX] Ubuntu 18.10
- Installation method (e.g. snap or AppImage in Linux):  AppImage
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by HristoA** [comment]
Hi @ixrock . What is case with this issue? :)

**Comment by nevalla** [comment]
Version 2.6.0 will have the fix in.

**Comment by HristoA** [comment]
I test it on RC version and can confirm that bug not exist! Thanks, great work
