### ISSUE TITLE
Updated helm charts don't appear in list without app recycle

### ISSUE THREAD

**Issue by justinrush** [lensapp/lens#691]
**Describe the bug**
When new versions of a chart are available (and I've done a helm repo update to validate), the new chart versions do not show up in the list. Same is true of new charts in general. If I close and re-open the app, the new charts / versions show up.

**To Reproduce**
1. Open Lens and load the Charts tab
2. Push a new chart or version to a repo
3. click around a bit in lens and notice that the new chart or version isn't there
4. close lens and reopen it and notice it is there

**Expected behavior**
I expect the new chart or version to show up when I do a helm repo update, or for there to be some button inside the Lens GUI to flush cache / refresh list, etc.

**Environment (please complete the following information):**
- Lens Version: 3.5.3
- OS: Windows 10 v2004
- Installation method (e.g. snap or AppImage in Linux): exe download/install

**Comment by dromaniuk** [comment]
I got the same trouble.

**Environment (please complete the following information):**

- Lens Version: 4.0.5
- OS: Ubuntu 20.04.1
- Installation method (e.g. snap or AppImage in Linux): AppImage

**Comment by aloker** [comment]
I actually can't make Lens update the versions **at all**, ie. even a restart of the application does not help.

- Lens version: 4.1.2
- OS: Windows 10 20H2
- Installation method (e.g. snap or AppImage in Linux): exe download/install

**Comment by timsamart** [comment]
I have the same problem. 

It seems they are cached somewhere and not reloaded. It would be great if we could reload them somehow. One possibility would be a refresh button on the right side of the search-bar or a right click option menu inside the chart-list. 

This is especially useful if you deploy your own charts and want to test them.

**Comment by Nokel81** [comment]
Related line is https://github.com/lensapp/lens/tree/67898152171cd8a9f6f927f12c47aa306105158c/src/main/helm/helm-chart-manager/ts#L70

**Comment by timsamart** [comment]
Hey @Nokel81 funny I just checked out the repo to search for the line myself and then you posted it 2 min. later 😄 

The line you found references a cacheFile. I could not find it saved in the lens folder %appdata%. Is it managed through a worker somewhere?

I got this path from ```helm-repo-manager.ts``` line 100: 

```javascript
cacheFilePath: `${this.helmEnv.HELM_REPOSITORY_CACHE}/${repo.name}-index.yaml`
```

**Comment by Nokel81** [comment]
Is it not saved within Lens but by helm itself, Lens merely reads it once per repo name.

**Comment by timsamart** [comment]
Oh okay so when I update my helm repo it should update too?

**Comment by timsamart** [comment]
I correct myself i did ```helm repo update``` and I can see my updated charts from my private registry. I restarted Lens and it still does not show the updated charts. Maybe I am missing something

**Comment by Nokel81** [comment]
That should have worked. Did you quit the tray icon too?

**Comment by timsamart** [comment]
Nice Awesome!!! That helped for now! Thank you so much!

**Comment by Nokel81** [comment]
You are welcome, I am going to leave this open since we should periodically reload that file.

**Comment by phpwutz** [comment]
I have the same issue here.
Using microk8s, helm3. Closing the Tray Icon does not refresh the list of helm charts. 
Only removing the cluster and re-adding seems to help right now

**Comment by quantumsheep** [comment]
Same issue, I did a `helm repo update` locally and on the server, my new Helm Chart's version doesn't appear :(

Quitting Lens and killing `Lens` and `Lens Helper` background processes (on macOS) then restarting Lens works but it's not very intuitive.

**Comment by Nokel81** [comment]
>  Closing the Tray Icon does not refresh the list of helm charts.

Do you mean picking "Quit Lens"?

**Comment by SSmale** [comment]
I am having this issue now, if I add a new repo it will only show up after reconnection to the cluster
