### ISSUE TITLE
Sorting and namespace selections should persist

### ISSUE THREAD

**Issue by msorens** [lensapp/lens#696]
**Describe the bug**

(Was debating whether to call this a bug or a feature request--I will let you decide, but I lean slightly towards "bug". 😁 )

On sorting:
Once I select a column to sort on and a sort direction in any given view, that should persist the next time I return to that view. And this should be true even if exiting Lens and restarting it. Currently, when I switch to any view, the first thing I have to do every single time is sort by Namespace so my services/pods/deployments of interest are all grouped together.

On filtering-by-namespace:
This is better than sorting--filtering does persist when switching between views. However, it does not persist when I close then re-open Lens.

**To Reproduce**
Explained above.

**Expected behavior**
Sorting selection should persist per view, and across invocations.
Namespace filtering should persist across invocations.

**Screenshots**
NA

**Environment (please complete the following information):**
- Lens Version:3.5.3
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): brew
 
**Logs:**
NA

**Kubeconfig:**
NA

**Additional context**
NA

**Comment by Nokel81** [comment]
Resolved by #2166 and #2279
