### ISSUE TITLE
airgapped k8s - changing private image registry

### ISSUE THREAD

**Issue by gorkemozlu** [lensapp/lens#697]
issue description: 

i'm using a airgapped k8s environment, when i want to start a shell to one of the worker node with lens, it deploys a pod, but since i'm on airgapped env., it's not possible to pull the image from gcr.io, 
**What would you like to be added**:
is it possible to change the image registry settings to private registry in the settings page ?

**Why is this needed**:
if we have ability to change the image registry value on settings, that would make sense on airgapped env.s

**Environment you are Lens application on:**

- Kubernetes distribution: pivotal pks
- Desktop OS: linux

**Comment by kgelinas** [comment]
dupe?
https://github.com/lensapp/lens/issues/590

**Comment by nevalla** [comment]
> dupe?
> #590

Yes. Closing this in favor of #590. Let's track the progress there.
