### ISSUE TITLE
Integration with prometheus instance configured to use a basepath

### ISSUE THREAD

**Issue by kbirger** [lensapp/lens#70]
**Describe the bug**
I configure my custom prometheus path as described in Settings. I have verified this path, and have performed manual GET calls (using curl) on it. All good.

I still see "metrics are not available due to missing or invalid Prometheus configuration".

I suspect the following is the cause:

My cluster has been provisioned with an instance of prometheus whose basepath is /prometheus. As such, GET prometheus:9090 responds with a 302 to location "/prometheus"

**To Reproduce**
1. Configure prometheus with a basepath of /prometheus
2. Configure your cluster's custom prometheus path 
3. See error

**Expected behavior**
Lens should honor 302 response location headers? 

Should show me metrics

I'm not sure if Lens provides error logs anywhere. If someone can clarify this for me I can add some logs from the app

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux): 
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by nevalla** [comment]
Prometheus service address should handle base path now.
