### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by DanTulovsky** [lensapp/lens#703]
**Describe the bug**

Workflows tab shows crash:

Error stack:

 
TypeError: Cannot read property 'toLowerCase' of undefined
    at lookupApiLink (webpack-internal:///994:2538:23)
    at renderTableContents (webpack-internal:///994:19244:42)
    at ItemListLayout.getRow (webpack-internal:///994:18545:11)
    at eval (webpack-internal:///994:18793:23)
    at Array.map (<anonymous>)
    at ItemListLayout.renderList (webpack-internal:///994:18792:30)
    at ItemListLayout.render (webpack-internal:///994:18817:58)
    at allowStateChanges (webpack-internal:///9:1008:15)
    at eval (webpack-internal:///11:345:4642)
    at trackDerivedFunction (webpack-internal:///9:802:24)

Component stack:

    in ItemListLayout
    in KubeObjectListLayout
    in Events
    in div
    in WorkloadsOverview
    in Route
    in Switch
    in ErrorBoundary
    in main
    in div
    in MainLayout
    in Workloads
    in Route
    in Switch
    in Switch
    in ErrorBoundary
    in Router
    in Unknown
    in App

**To Reproduce**
Not sure how to reproduce.

**Environment (please complete the following information):**
- Lens Version: 3.5.3
- OS: OSX 10.15.6
- Installation method (e.g. snap or AppImage in Linux): 
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Abhinand-Gokul** [comment]
I just encountered a similar problem as well.

Error stack:

 
TypeError: Cannot read property 'toLowerCase' of undefined
    at lookupApiLink (webpack-internal:///994:2538:23)
    at eval (webpack-internal:///994:47827:21)
    at Array.forEach (<anonymous>)
    at ClusterIssues.get (webpack-internal:///994:47812:14)
    at trackDerivedFunction (webpack-internal:///9:802:24)
    at ComputedValue.computeValue (webpack-internal:///9:1289:19)
    at ComputedValue.trackAndCompute (webpack-internal:///9:1274:29)
    at ComputedValue.get (webpack-internal:///9:1234:26)
    at ObservableObjectAdministration.read (webpack-internal:///9:3976:37)
    at ClusterIssues.get (webpack-internal:///9:4240:68)


Component stack:


    in ClusterIssues
    in div
    in ErrorBoundary
    in main
    in div
    in MainLayout
    in Cluster
    in Route
    in Switch
    in Switch
    in ErrorBoundary
    in Router
    in Unknown
    in App

I am able to use kubeconfig using a kubectl or k9s.

**Comment by aleksfront** [comment]
Can you please provide your `EventsList`? Share the output of this command `kubectl get events -o=json`. If you were using any namespace but `default`, add `-n` selector, for example `kubectl get events -o=json -n=kube-system`.

**Comment by Abhinand-Gokul** [comment]
This happens when I am on the Cluster overview. All other views like Nodes, Workloads, Configuration...etc work fine. I have about 30+ namespaces in this cluster, not sure events would help?

**Comment by aleksfront** [comment]
Yes, it will help, because the error appeared into Event list actually. In Cluster Overview it's located at the bottom. It seems like some of the events missed required `involvedObject` part.

**Comment by aleksfront** [comment]
@Abhinand-Gokul Can you check please command `kubectl descrive event` and see what `API Version` your events using?

**Comment by Abhinand-Gokul** [comment]
Provisioning and OOM is from one of our application pods.


kubectl get events -o json

{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "v1",
            "count": 2,
            "eventTime": null,
            "firstTimestamp": "2020-08-25T09:14:22Z",
            "involvedObject": {
                "apiVersion": "v1",
                "kind": "Endpoints",
                "name": "XXXXX"
            },
            "kind": "Event",
            "lastTimestamp": "2020-08-25T09:14:22Z",
            "message": "Failed to create endpoint for service XXXXX/service: endpoints \"XXXXX\" already exists
",
            "metadata": {
                "creationTimestamp": "2020-08-25T09:14:22Z",
                "managedFields": [
                    {
                        "apiVersion": "v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:count": {},
                            "f:firstTimestamp": {},
                            "f:involvedObject": {
                                "f:apiVersion": {},
                                "f:kind": {},
                                "f:name": {}
                            },
                            "f:lastTimestamp": {},
                            "f:message": {},
                            "f:reason": {},
                            "f:source": {
                                "f:component": {}
                            },
                            "f:type": {}
                        },
                        "manager": "kube-controller-manager",
                        "operation": "Update",
                        "time": "2020-08-25T09:14:22Z"
                    }
                ],
                "name": "XXXXX",
                "namespace": "default",
                "resourceVersion": "9473736",
                "selfLink": "/api/v1/namespaces/default/events/XXXXX.162e7800b1c20dff",
                "uid": "58c12c8d-995c-4e67-bb4f-8dc33756d0da"
            },
            "reason": "FailedToCreateEndpoint",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "endpoint-controller"
            },
            "type": "Warning"
        },
        {
            "apiVersion": "v1",
            "count": 14797,
            "eventTime": null,
            "firstTimestamp": "2020-08-14T13:45:15Z",
            "involvedObject": {
                "name": "pvc-69b14921-01cb-4785-88ad-0c8e77322a61",
                "resourceVersion": "157287104",
                "uid": "2f4bcbf3-b328-4c55-a8cf-a6f29dc34860"
            },
            "kind": "Event",
            "lastTimestamp": "2020-08-25T09:19:26Z",
            "message": "Fatal: underlying volume of persistent volume pvc-69b14921-01cb-4785-88ad-0c8e77322a61 is gone",
            "metadata": {
                "creationTimestamp": "2020-08-14T13:45:15Z",
                "managedFields": [
                    {
                        "apiVersion": "v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:count": {},
                            "f:firstTimestamp": {},
                            "f:involvedObject": {
                                "f:name": {},
                                "f:resourceVersion": {},
                                "f:uid": {}
                            },
                            "f:lastTimestamp": {},
                            "f:message": {},
                            "f:reason": {},
                            "f:source": {
                                "f:component": {}
                            },
                            "f:type": {}
                        },
                        "manager": "rest-client",
                        "operation": "Update",
                        "time": "2020-08-25T09:19:26Z"
                    }
                ],
                "name": "pvc-69b14921-01cb-4785-88ad-0c8e77322a61.162b2666c940e176",
                "namespace": "default",
                "resourceVersion": "9473897",
                "selfLink": "/api/v1/namespaces/default/events/pvc-69b14921-01cb-4785-88ad-0c8e77322a61.162b2666c940e176",
                "uid": "20f1476d-1844-4002-b6cd-6070c3490221"
            },
            "reason": "ProvisioningFailed",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "storage-controller: manila"
            },
            "type": "Warning"
        },
        {
            "apiVersion": "v1",
            "count": 14793,
            "eventTime": null,
            "firstTimestamp": "2020-08-14T13:45:15Z",
            "involvedObject": {
                "name": "pvc-7279c1a4-d41e-4d19-9a20-da6c37606aae",
                "resourceVersion": "157287111",
                "uid": "7254aa27-28c7-404a-9404-78571b079799"
            },
            "kind": "Event",
            "lastTimestamp": "2020-08-25T09:19:26Z",
            "message": "Fatal: underlying volume of persistent volume pvc-7279c1a4-d41e-4d19-9a20-da6c37606aae is gone",
            "metadata": {
                "creationTimestamp": "2020-08-14T13:45:15Z",
                "managedFields": [
                    {
                        "apiVersion": "v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:count": {},
                            "f:firstTimestamp": {},
                            "f:involvedObject": {
                                "f:name": {},
                                "f:resourceVersion": {},
                                "f:uid": {}
                            },
                            "f:lastTimestamp": {},
                            "f:message": {},
                            "f:reason": {},
                            "f:source": {
                                "f:component": {}
                            },
                            "f:type": {}
                        },
                        "manager": "rest-client",
                        "operation": "Update",
                        "time": "2020-08-25T09:19:26Z"
                    }
                ],
                "name": "pvc-7279c1a4-d41e-4d19-9a20-da6c37606aae.162b2666ce9a1ce9",
                "namespace": "default",
                "resourceVersion": "9473898",
                "selfLink": "/api/v1/namespaces/default/events/pvc-7279c1a4-d41e-4d19-9a20-da6c37606aae.162b2666ce9a1ce9",
                "uid": "215a37c4-e3b3-4dc5-bc33-df02d6090643"
            },
            "reason": "ProvisioningFailed",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "storage-controller: manila"
            },
            "type": "Warning"
        },
        {
            "apiVersion": "v1",
            "count": 14790,
            "eventTime": null,
            "firstTimestamp": "2020-08-14T13:45:15Z",
            "involvedObject": {
                "name": "pvc-8c6b02b9-15e2-4452-9929-756495b881b6",
                "resourceVersion": "157287149",
                "uid": "3ca78816-30e4-4187-b117-84ab46bfb81e"
            },
            "kind": "Event",
            "lastTimestamp": "2020-08-25T09:19:26Z",
            "message": "Fatal: underlying volume of persistent volume pvc-8c6b02b9-15e2-4452-9929-756495b881b6 is gone",
            "metadata": {
                "creationTimestamp": "2020-08-14T13:45:16Z",
                "managedFields": [
                    {
                        "apiVersion": "v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:count": {},
                            "f:firstTimestamp": {},
                            "f:involvedObject": {
                                "f:name": {},
                                "f:resourceVersion": {},
                                "f:uid": {}
                            },
                            "f:lastTimestamp": {},
                            "f:message": {},
                            "f:reason": {},
                            "f:source": {
                                "f:component": {}
                            },
                            "f:type": {}
                        },
                        "manager": "rest-client",
                        "operation": "Update",
                        "time": "2020-08-25T09:19:26Z"
                    }
                ],
                "name": "pvc-8c6b02b9-15e2-4452-9929-756495b881b6.162b2666d441bc10",
                "namespace": "default",
                "resourceVersion": "9473899",
                "selfLink": "/api/v1/namespaces/default/events/pvc-8c6b02b9-15e2-4452-9929-756495b881b6.162b2666d441bc10",
                "uid": "a2405c75-d500-4b8a-a573-4cf14a7e9adb"
            },
            "reason": "ProvisioningFailed",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "storage-controller: manila"
            },
            "type": "Warning"
        },
        {
            "apiVersion": "v1",
            "count": 14782,
            "eventTime": null,
            "firstTimestamp": "2020-08-14T13:45:16Z",
            "involvedObject": {
                "name": "pvc-e3bf4edf-2c79-43cf-90fc-7ef8eb26039a",
                "resourceVersion": "157287145",
                "uid": "918e4e96-13e7-4cf9-ada0-9b9f58257a95"
            },
            "kind": "Event",
            "lastTimestamp": "2020-08-25T09:19:26Z",
            "message": "Fatal: underlying volume of persistent volume pvc-e3bf4edf-2c79-43cf-90fc-7ef8eb26039a is gone",
            "metadata": {
                "creationTimestamp": "2020-08-14T13:45:16Z",
                "managedFields": [
                    {
                        "apiVersion": "v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:count": {},
                            "f:firstTimestamp": {},
                            "f:involvedObject": {
                                "f:name": {},
                                "f:resourceVersion": {},
                                "f:uid": {}
                            },
                            "f:lastTimestamp": {},
                            "f:message": {},
                            "f:reason": {},
                            "f:source": {
                                "f:component": {}
                            },
                            "f:type": {}
                        },
                        "manager": "rest-client",
                        "operation": "Update",
                        "time": "2020-08-25T09:19:26Z"
                    }
                ],
                "name": "pvc-e3bf4edf-2c79-43cf-90fc-7ef8eb26039a.162b2666d9a44579",
                "namespace": "default",
                "resourceVersion": "9473900",
                "selfLink": "/api/v1/namespaces/default/events/pvc-e3bf4edf-2c79-43cf-90fc-7ef8eb26039a.162b2666d9a44579",
                "uid": "d6bfc3d0-35ed-45f5-840c-43877938c143"
            },
            "reason": "ProvisioningFailed",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "storage-controller: manila"
            },
            "type": "Warning"
        },
        {
            "apiVersion": "v1",
            "count": 14780,
            "eventTime": null,
            "firstTimestamp": "2020-08-14T13:45:16Z",
            "involvedObject": {
                "name": "pvc-e43bd00e-7031-4fc3-8ca7-08d9229a40ad",
                "resourceVersion": "157287153",
                "uid": "349062ca-9f2e-479d-9be6-213429f4199d"
            },
            "kind": "Event",
            "lastTimestamp": "2020-08-25T09:19:26Z",
            "message": "Fatal: underlying volume of persistent volume pvc-e43bd00e-7031-4fc3-8ca7-08d9229a40ad is gone",
            "metadata": {
                "creationTimestamp": "2020-08-14T13:45:16Z",
                "managedFields": [
                    {
                        "apiVersion": "v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:count": {},
                            "f:firstTimestamp": {},
                            "f:involvedObject": {
                                "f:name": {},
                                "f:resourceVersion": {},
                                "f:uid": {}
                            },
                            "f:lastTimestamp": {},
                            "f:message": {},
                            "f:reason": {},
                            "f:source": {
                                "f:component": {}
                            },
                            "f:type": {}
                        },
                        "manager": "rest-client",
                        "operation": "Update",
                        "time": "2020-08-25T09:19:26Z"
                    }
                ],
                "name": "pvc-e43bd00e-7031-4fc3-8ca7-08d9229a40ad.162b2666def3e82d",
                "namespace": "default",
                "resourceVersion": "9473901",
                "selfLink": "/api/v1/namespaces/default/events/pvc-e43bd00e-7031-4fc3-8ca7-08d9229a40ad.162b2666def3e82d",
                "uid": "3bc18e27-44c9-4c08-b039-416c4f008647"
            },
            "reason": "ProvisioningFailed",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "storage-controller: manila"
            },
            "type": "Warning"
        },
        {
            "apiVersion": "v1",
            "count": 14777,
            "eventTime": null,
            "firstTimestamp": "2020-08-14T13:45:16Z",
            "involvedObject": {
                "name": "pvc-fa029ee7-f037-4fdd-9175-c696c1d1fe2e",
                "resourceVersion": "157287160",
                "uid": "65aa2ec3-6cec-4f41-a961-f9c80d693ed3"
            },
            "kind": "Event",
            "lastTimestamp": "2020-08-25T09:19:26Z",
            "message": "Fatal: underlying volume of persistent volume pvc-fa029ee7-f037-4fdd-9175-c696c1d1fe2e is gone",
            "metadata": {
                "creationTimestamp": "2020-08-14T13:45:16Z",
                "managedFields": [
                    {
                        "apiVersion": "v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:count": {},
                            "f:firstTimestamp": {},
                            "f:involvedObject": {
                                "f:name": {},
                                "f:resourceVersion": {},
                                "f:uid": {}
                            },
                            "f:lastTimestamp": {},
                            "f:message": {},
                            "f:reason": {},
                            "f:source": {
                                "f:component": {}
                            },
                            "f:type": {}
                        },
                        "manager": "rest-client",
                        "operation": "Update",
                        "time": "2020-08-25T09:19:27Z"
                    }
                ],
                "name": "pvc-fa029ee7-f037-4fdd-9175-c696c1d1fe2e.162b2666e3f8a09c",
                "namespace": "default",
                "resourceVersion": "9473902",
                "selfLink": "/api/v1/namespaces/default/events/pvc-fa029ee7-f037-4fdd-9175-c696c1d1fe2e.162b2666e3f8a09c",
                "uid": "42fd9a6f-c1c9-4cdd-a917-30faaa537609"
            },
            "reason": "ProvisioningFailed",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "storage-controller: manila"
            },
            "type": "Warning"
        },
        {
            "apiVersion": "v1",
            "count": 96867,
            "eventTime": null,
            "firstTimestamp": "2020-08-09T04:24:15Z",
            "involvedObject": {
                "kind": "Node",
                "name": "XXXXXworker-z1-7844994598-9s44f",
                "uid": "XXXXXworker-z1-7844994598-9s44f"
            },
            "kind": "Event",
            "lastTimestamp": "2020-08-25T09:18:17Z",
            "message": "(combined from similar events): System OOM encountered, victim process: ruby, pid: 3013199",
            "metadata": {
                "creationTimestamp": "2020-08-09T04:24:15Z",
                "managedFields": [
                    {
                        "apiVersion": "v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:count": {},
                            "f:firstTimestamp": {},
                            "f:involvedObject": {
                                "f:kind": {},
                                "f:name": {},
                                "f:uid": {}
                            },
                            "f:lastTimestamp": {},
                            "f:message": {},
                            "f:reason": {},
                            "f:source": {
                                "f:component": {},
                                "f:host": {}
                            },
                            "f:type": {}
                        },
                        "manager": "kubelet",
                        "operation": "Update",
                        "time": "2020-08-25T09:18:17Z"
                    }
                ],
                "name": "XXXXXworker-z1-7844994598-9s44f.16297ee2ecc50e8b",
                "namespace": "default",
                "resourceVersion": "9473870",
                "selfLink": "/api/v1/namespaces/default/events/XXXXXworker-z1-7844994598-9s44f.16297ee2ecc50e8b",
                "uid": "cfd8330a-8271-44a6-93d8-3a24054d4c12"
            },
            "reason": "SystemOOM",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "kubelet",
                "host": "XXXXXworker-z1-7844994598-9s44f"
            },
            "type": "Warning"
        },
        {
            "apiVersion": "v1",
            "count": 23637,
            "eventTime": null,
            "firstTimestamp": "2020-08-21T07:28:46Z",
            "involvedObject": {
                "kind": "Node",
                "name": "XXXXXworker-z1-7844994598-jf99c",
                "uid": "XXXXXworker-z1-7844994598-jf99c"
            },
            "kind": "Event",
            "lastTimestamp": "2020-08-25T09:18:48Z",
            "message": "(combined from similar events): System OOM encountered, victim process: ruby, pid: 669756",
            "metadata": {
                "creationTimestamp": "2020-08-21T07:28:46Z",
                "managedFields": [
                    {
                        "apiVersion": "v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:count": {},
                            "f:firstTimestamp": {},
                            "f:involvedObject": {
                                "f:kind": {},
                                "f:name": {},
                                "f:uid": {}
                            },
                            "f:lastTimestamp": {},
                            "f:message": {},
                            "f:reason": {},
                            "f:source": {
                                "f:component": {},
                                "f:host": {}
                            },
                            "f:type": {}
                        },
                        "manager": "kubelet",
                        "operation": "Update",
                        "time": "2020-08-25T09:18:48Z"
                    }
                ],
                "name": "XXXXXworker-z1-7844994598-jf99c.162d37eb31094252",
                "namespace": "default",
                "resourceVersion": "9473884",
                "selfLink": "/api/v1/namespaces/default/events/XXXXXworker-z1-7844994598-jf99c.162d37eb31094252",
                "uid": "62e6b882-1e08-4443-bbe9-cdb33a867583"
            },
            "reason": "SystemOOM",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "kubelet",
                "host": "XXXXXworker-z1-7844994598-jf99c"
            },
            "type": "Warning"
        },
        {
            "apiVersion": "v1",
            "count": 12233,
            "eventTime": null,
            "firstTimestamp": "2020-08-23T04:29:30Z",
            "involvedObject": {
                "kind": "Node",
                "name": "XXXXXworker-z1-7844994598-v2bbt",
                "uid": "XXXXXworker-z1-7844994598-v2bbt"
            },
            "kind": "Event",
            "lastTimestamp": "2020-08-25T09:20:09Z",
            "message": "(combined from similar events): System OOM encountered, victim process: ruby, pid: 1364824",
            "metadata": {
                "creationTimestamp": "2020-08-23T04:29:30Z",
                "managedFields": [
                    {
                        "apiVersion": "v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:count": {},
                            "f:firstTimestamp": {},
                            "f:involvedObject": {
                                "f:kind": {},
                                "f:name": {},
                                "f:uid": {}
                            },
                            "f:lastTimestamp": {},
                            "f:message": {},
                            "f:reason": {},
                            "f:source": {
                                "f:component": {},
                                "f:host": {}
                            },
                            "f:type": {}
                        },
                        "manager": "kubelet",
                        "operation": "Update",
                        "time": "2020-08-25T09:20:09Z"
                    }
                ],
                "name": "XXXXXworker-z1-7844994598-v2bbt.162dcb4c09843cfa",
                "namespace": "default",
                "resourceVersion": "9473930",
                "selfLink": "/api/v1/namespaces/default/events/XXXXXworker-z1-7844994598-v2bbt.162dcb4c09843cfa",
                "uid": "f5509e43-ce5f-42cc-b8cd-81a2331e9ded"
            },
            "reason": "SystemOOM",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "kubelet",
                "host": "XXXXXworker-z1-7844994598-v2bbt"
            },
            "type": "Warning"
        },
        {
            "apiVersion": "v1",
            "count": 1,
            "eventTime": null,
            "firstTimestamp": "2020-08-25T09:19:34Z",
            "involvedObject": {
                "kind": "Node",
                "name": "XXXXXworker-z2-6c9d6f5798-wgrb5",
                "uid": "XXXXXworker-z2-6c9d6f5798-wgrb5"
            },
            "kind": "Event",
            "lastTimestamp": "2020-08-25T09:19:34Z",
            "message": "System OOM encountered, victim process: redis-server, pid: 834489",
            "metadata": {
                "creationTimestamp": "2020-08-25T09:19:34Z",
                "managedFields": [
                    {
                        "apiVersion": "v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:count": {},
                            "f:firstTimestamp": {},
                            "f:involvedObject": {
                                "f:kind": {},
                                "f:name": {},
                                "f:uid": {}
                            },
                            "f:lastTimestamp": {},
                            "f:message": {},
                            "f:reason": {},
                            "f:source": {
                                "f:component": {},
                                "f:host": {}
                            },
                            "f:type": {}
                        },
                        "manager": "kubelet",
                        "operation": "Update",
                        "time": "2020-08-25T09:19:34Z"
                    }
                ],
                "name": "XXXXXworker-z2-6c9d6f5798-wgrb5.162e784966ca2558",
                "namespace": "default",
                "resourceVersion": "9473903",
                "selfLink": "/api/v1/namespaces/default/events/XXXXXworker-z2-6c9d6f5798-wgrb5.162e784966ca2558",
                "uid": "ccc43a80-f0c9-4866-b89e-446a23fb2f00"
            },
            "reason": "SystemOOM",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "kubelet",
                "host": "XXXXXworker-z2-6c9d6f5798-wgrb5"
            },
            "type": "Warning"
        },
        {
            "apiVersion": "v1",
            "count": 54458,
            "eventTime": null,
            "firstTimestamp": "2020-08-20T13:41:10Z",
            "involvedObject": {
                "kind": "Node",
                "name": "XXXXXworker-z2-6c9d6f5798-wkqhq",
                "uid": "XXXXXworker-z2-6c9d6f5798-wkqhq"
            },
            "kind": "Event",
            "lastTimestamp": "2020-08-25T09:19:01Z",
            "message": "(combined from similar events): System OOM encountered, victim process: ruby, pid: 486346",
            "metadata": {
                "creationTimestamp": "2020-08-20T13:41:10Z",
                "managedFields": [
                    {
                        "apiVersion": "v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:count": {},
                            "f:firstTimestamp": {},
                            "f:involvedObject": {
                                "f:kind": {},
                                "f:name": {},
                                "f:uid": {}
                            },
                            "f:lastTimestamp": {},
                            "f:message": {},
                            "f:reason": {},
                            "f:source": {
                                "f:component": {},
                                "f:host": {}
                            },
                            "f:type": {}
                        },
                        "manager": "kubelet",
                        "operation": "Update",
                        "time": "2020-08-25T09:19:01Z"
                    }
                ],
                "name": "XXXXXworker-z2-6c9d6f5798-wkqhq.162cfda92f0f66a7",
                "namespace": "default",
                "resourceVersion": "9473890",
                "selfLink": "/api/v1/namespaces/default/events/XXXXXworker-z2-6c9d6f5798-wkqhq.162cfda92f0f66a7",
                "uid": "d40cd31d-fde5-4859-ab47-7dce461f548b"
            },
            "reason": "SystemOOM",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "kubelet",
                "host": "XXXXXworker-z2-6c9d6f5798-wkqhq"
            },
            "type": "Warning"
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}
