### ISSUE TITLE
Limit on Clusters in UI

### ISSUE THREAD

**Issue by RickThiessen** [lensapp/lens#707]
**Describe the bug**
I have just downloaded and am testing the UI and fined it very easy to use and have added several of my EKS Clusters to the UI.
I currently have added 16 Clusters to the list, but the 16th I had to use the "File" menu to add as the "+" icon had moved off the screen.
There Is no Scroll bar for the Icons and the "View->Zoom" does not resize the Icons on the Left Column, So I have no way to get to the 16th icon.
We have more Clusters coming and would love to continue using the App but currently it does not support all the Clusters we have.

**Comment by nevalla** [comment]
As a workaround you can already split those clusters in different workspaces.

**Comment by ixrock** [comment]
What is the Lens version? You can actually scroll icons when they go off (even if scrollbar invisible, checked in `3.6.0-beta`)

**Comment by liam-mackie** [comment]
I experience this issue as well, and cannot scroll. I am on the latest snap version (3.5.3). It would be optimal if we could also choose between a (searchable) list and icon view in settings. When using lens with a lot of clusters, it can be hard to find the right one, even if we could scroll the list.

**Comment by RickThiessen** [comment]
> What is the Lens version? You can actually scroll icons when they go off (even if scrollbar invisible, checked in `3.6.0-beta`)

I am running on linux and Version 3.5.3.

**Comment by RickThiessen** [comment]
I have found the solution to this problem.
There is a selection element in the bottom Right corner (Workspaces).  It says "default" and that is for the default workspace.
Adding additional Workspace entries allows me to add all my clusters to different spaces.  
This also helps to organize the Clusters.
It would have been Nice to have that up in the Menu at the top, so it was more obvious but, this works.
