### ISSUE TITLE
Allow Custom Helm Repos

### ISSUE THREAD

**Issue by mudged** [lensapp/lens#708]
**What would you like to be added**:
The ability to add a custom Helm Chart Repository i.e. my companies internal private Helm Repo

**Why is this needed**:
Install Helm Charts from my companies private Helm Repository

**Environment you are Lens application on:**

- Kubernetes distribution: microk8s
- Desktop OS: Ubuntu

**Comment by jakolehm** [comment]
Duplicate of #112
