### ISSUE TITLE
Failed to start connection: Error: failed to retrieve port from stream

### ISSUE THREAD

**Issue by djarami726** [lensapp/lens#7087]
**Describe the bug**
One of my collegues is trying to setup openlens and gets the following error when connecting to the AKS cluster.
`Failed to start connection: Error: failed to retrieve port from stream`

**To Reproduce**
1. Start OpenLens
2. Click on catalog
3. See error

Kubectl works fine from the terminal against that cluster.  I'm able to do the following without a problem:
Kubectl get pods -A
Kubectl get ns -A

**Expected behavior**
The cluster should open up.  I have installed it on another machine same version and os and it works fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/107571134/216171298-2a05dddd-17c3-4faa-9624-24e421a36b8e.png)

**Environment (please complete the following information):**
- Lens Version: 6.4.0-beta.10
- OS: Windows 11
- Download exe and install

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
didn't see any logs
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by djarami726** [comment]
opened issue in wrong place

**Comment by saiaptiv** [comment]
@djarami726  I am seeing the same issue. Did you find any solution?
