### ISSUE TITLE
Logging in into Lens does not work behind a corporate firewall

### ISSUE THREAD

**Issue by roedles** [lensapp/lens#71]
**Describe the bug**
Logging in into Kontena Account does not work in Lens, because we are behind a corporate firewall (Zscaler) and Lens does not trust the Zscaler CA certificate.

**To Reproduce**
1. Logging in into Lens behind a corporate firewall

**Expected behavior**
Logging in into Lens should work behind a corporate firewall.
Make Lens (maybe as an option) use the CA certificates configured in Windows. 

**Screenshots**
![Lens-Login-Error](https://user-images.githubusercontent.com/54976754/68383364-cfe59900-0155-11ea-8f0b-3ad7d6746f60.PNG)

**Environment (please complete the following information):**
- Lens Version: 2.4.1
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux): Lens Setup 2.4.1.exe

**Comment by jakolehm** [comment]
Lens 2.5.0 should use system CA certificates on Windows (and MacOS). Could you test if it fixes your issue?

**Comment by roedles** [comment]
Thanks for the quick response. On 2.5.0 I still see the RequestError: "Error: unable to get local issuer certificate". This might be the case because, for all certificats (kontena.io, google.com or any other) the issuer of the certificat is always the ZScaler Root CA  for us.

**Comment by jakolehm** [comment]
@roedles Lens 2.6.0 most likely fixes this issue.

**Comment by dannyyy** [comment]
@jakolehm Unfortunately either not fixed for me with 2.6.0
We are also using ZScaler corporate proxy.

**Comment by roedles** [comment]
@jakolehm I have still the same error message. One possible workaround could be to add an option to enable/disable the trust of untrusted CA's.

**Comment by jakolehm** [comment]
Lens 3.x does not have login anymore.
