### ISSUE TITLE
Azure AD token not refreshing

### ISSUE THREAD

**Issue by brechtvhb** [lensapp/lens#713]
**Describe the bug**
Whenever I try to connect to our AKS cluster using AAD I see a red lock with the option to reconnect, but clicking reconnect does not help. 

**To Reproduce**
1. Use aks get credentials to store the authentication info in the kubeconfig file.
2. Add the cluster to lens en connect to it.
3. Wait 1 hour, close lens.
4. Open lens again and try to connect to the cluster.
5. Red lock appears.

PS: kubectl is working, It looks like lens is not able to refresh tokens while kubectl is able to do so.

**Expected behavior**
Refresh tokens and login to the cluster.

**Screenshots**
![image](https://user-images.githubusercontent.com/330772/90608014-4f82b700-e202-11ea-84c1-fc9ebbe6f66f.png)

**Environment (please complete the following information):**
- Lens Version: 3,5,3
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): MSI
 
**Logs:**
error: Failed to connect to cluster cluster-playground: {"name":"StatusCodeError","statusCode":401,"message":"401 - {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Unauthorized\",\"reason\":\"Unauthorized\",\"code\":401}","error":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401},"options":{"json":true,"timeout":10000,"headers":{"host":"738923f2-beb3-4847-9afd-77aa1811cae8.localhost:56963"},"uri":"http://127.0.0.1:56963/api-kube/version","simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false},"response":{"statusCode":401,"body":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401},"headers":{"cache-control":"no-cache, private","content-length":"129","content-type":"application/json","date":"Wed, 19 Aug 2020 07:52:34 GMT","connection":"close"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"127.0.0.1:56963","port":"56963","hostname":"127.0.0.1","hash":null,"search":null,"query":null,"pathname":"/api-kube/version","path":"/api-kube/version","href":"http://127.0.0.1:56963/api-kube/version"},"method":"GET","headers":{"host":"738923f2-beb3-4847-9afd-77aa1811cae8.localhost:56963","accept":"application/json"}}}}

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
- name: clusterUser_aks-playground-rg_cluster-playground
  user:
    auth-provider:
      config:
        access-token: {redacted}
        apiserver-id: {redacted}
        client-id: {redacted}
        config-mode: "1"
        environment: AzurePublicCloud
        expires-in: "3599"
        expires-on: "1597821456"
        refresh-token: {redacted}
        tenant-id: {redacted}
      name: azure

**Comment by ocdi** [comment]
I had this issue also. You need to use kubelogin which worked for me

https://github.com/Azure/kubelogin

The releases page has binaries in one zip file for all platforms.

**Comment by brechtvhb** [comment]
> I had this issue also. You need to use kubelogin which worked for me
> 
> https://github.com/Azure/kubelogin
> 
> The releases page has binaries in one zip file for all platforms.

Working now. Thanks a lot!
