### ISSUE TITLE
Only single line annotations are shown in detailed view

### ISSUE THREAD

**Issue by gabrielbcn** [lensapp/lens#719]
**Describe the bug**
When getting details about an object, for instance deployments, daemon sets or services, the detail view will display only single line annotations and will ignore those that are multiline

**To Reproduce**

In the attached window capture you can see how a service that has two annotations is shown as having only one annotation, having the multi-line annotation (kubectl.kubernetes.io/last-applied-configuration) ignored.

<img width="1552" alt="Screen Shot 2020-08-20 at 11 50 43" src="https://user-images.githubusercontent.com/45199871/90707783-ab6d3e80-e2db-11ea-8b03-b5bcaea005d1.png">

**Expected behavior**
I expect either:
* To display the full annotation in a foldable way, a multi-line annotation can take a lot of space and we don't want that
* To get an indication that the annotation is there, maybe just the name equals three dots as I can always go to edit to see it

What I find misleading is that the annotation just "disappears". That can make me miss something important.

**Screenshots**
See above in explanation

**Environment (please complete the following information):**
- Lens Version: 3.5.3
- OS: OSX
- Installation method: brew
 
**Logs:**
Not applicable

**Kubeconfig:**
Not applicable

**Additional context**
Not applicable

**Comment by ixrock** [comment]
I guess it's only `kubectl.kubernetes.io/last-applied-configuration` ignored in the output for some reason.. 
@nevalla maybe you remember why?

**Comment by gabrielbcn** [comment]
Indeed, other multi-line annotations do work... I've just checked.

**Comment by nevalla** [comment]
So, is the issue that `last-applied-configuration` is not visible in details drawer? 

> I guess it's only `kubectl.kubernetes.io/last-applied-configuration` ignored in the output for some reason..
> @nevalla maybe you remember why?

Yes, it was bloating the details drawer back then. Is that something you really want to see on details, since it's something kubectl uses internally?
