### ISSUE TITLE
brew cask install kontena-lens

### ISSUE THREAD

**Issue by kachkaev** [lensapp/lens#72]
I just discovered Kontena Lens and went to check if it had a [Homebrew Cask](https://github.com/Homebrew/homebrew-cask) distribution. Seems like this is not the case, which means that lazy macOS users like sadly have to manually download a DMG, open it, drag an icon to Applications or run some strange setup wizard.

It'd be great if you could crearte a Cask for your app. This should improve the initial customer experience and generally comply with expectations that macOS users have. Cheers 👋

**Comment by jnummelin** [comment]
I _think_ there was some early stuff being worked on. @kke do you know in which state that got into?

**Comment by kke** [comment]
You can already do `brew cask install kontena/lens/lens`

I haven't tried to create a PR to get it included in the homebrew repo.

**Comment by Addono** [comment]
I just opened a PR for 3.0.1 against the Homebrew repo, see Homebrew/homebrew-cask#79339. 

Are [these](https://github.com/Homebrew/homebrew-cask/pull/79339/files#diff-ed191c5858aa52c870d1d04c4f03550cR13-R19) directories still correct?  (I haven't used the application much, but the cache folder hasn't been created yet.)
```ruby
  uninstall delete: [
                      '~/Library/Caches/Lens',
                    ]

  zap trash: [
               '~/Library/Application Support/Lens',
             ]
```

**Comment by jakolehm** [comment]
I think `~/Library/Caches/Lens` is not needed, at least I haven't seen that folder created.

**Comment by jakolehm** [comment]
Cask PR is already merged and `brew cask install lens` seems to work. @Addono huge thanks for making this happen!

**Comment by sshishov** [comment]
Will we support new version `3.1.0` for example?

**Comment by JAG-01** [comment]
Indicating there's a "lens" Homebrew Cask in the "Installation" section of the README.md would be greatly appreciated. 😉 

Great tool!
