### ISSUE TITLE
add kubeconfig from command-line

### ISSUE THREAD

**Issue by matti** [lensapp/lens#73]
currently I need to
```
cat $KUBECONFIG | pbcopy
```

open lens, click-click, paste

would be create to automate this from the command-line

**Comment by peterloron** [comment]
That would be great. Also nice would be adding support for parsing kubeconfg files recursively in a directory tree. I have dozens arranged in folder hierarchies, one file per cluster. Being able to point Lens to the top folder and go would be sweet. Not everyone keeps all their config in ~/.kube/config

**Comment by kke** [comment]
I think in lens terminal this could be implemented easyishishly, but then you need at least one working cluster.

Or I guess the lens binary could have some command line flag, something like `cat foofoo | /Applications/Lens.app -kc`.

**Comment by Nokel81** [comment]
I don't think this is necessary anymore because we are now syncing kubeconfig files in the general case. Even allowing for the syncing of folders. (Though currently only shallowly).
