### ISSUE TITLE
disable cert validation for SAN

### ISSUE THREAD

**Issue by hezise** [lensapp/lens#735]
**What would you like to be added**:
disable validating cert against SAN

**Why is this needed**:
I'm using K8S in OS and access the cluster via external IP and when trying to access the external IP,
I'm getting an error that available IPs are the IPs defined in SAN

**Environment you are Lens application on:**
win10

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: <the OS Lens app runs on in your case>

**Comment by nevalla** [comment]
Have you tried to put `insecure-skip-tls-verify: true` option for cluster in Kubeconfig? Does that resolve the issue?

**Comment by hezise** [comment]
yes I have
this is the error I'm getting
Connecting ...
Authentication proxy started
2020/08/27 07:36:13 http: proxy error: x509: certificate is valid for 10.233.0.1, 10.0.0.15, 10.0.0.15, 10.233.0.1, 127.0.0.1, 10.0.0.15, not 10.175.89.103

when I'm accessing via browser I'm getting a warning but I am able to access it

**Comment by fluidjeel** [comment]
@hezise did you get it to work?

**Comment by hezise** [comment]
@fluidjeel I did work around
I saw in the certificate the name is was assigned and created an entry in my etc/hosts that point the name to 10.175.89.103
and I defined the name
