### ISSUE TITLE
Feature request: Filter log by regex (or simple filter)

### ISSUE THREAD

**Issue by Richard87** [lensapp/lens#737]
**What would you like to be added**:
A simple filter search in logs to search for relevant content

**Why is this needed**:
speed up troubleshooting, no need to export big logs to search in a different app

**Environment you are Lens application on:**
Lens 3.5.3 on Gnome / Fedora 32

- Kubernetes distribution: GKE / Microk8s
- Desktop OS: Fedora32 / Gnome

..

**Comment by nevalla** [comment]
Related to https://github.com/lensapp/lens/issues/430

**Comment by Nokel81** [comment]
Fixed by #1516
