### ISSUE TITLE
Conflict in permissions across namespaces

### ISSUE THREAD

**Issue by luislhl** [lensapp/lens#745]
**Describe the bug**
I have a user that has read/list permissions to secrets in a given namespace `A`, but not in another namespace `B`.
However, he has permissions to read/list many other resource types in namespace `B`, such as Deployments, Pods, etc.

In Lens, the Secrets menu is totally missing for him, even though he can read secrets in at least 1 namespace.

He is able to run a `kubectl describe secrets -n namespace` in the namespace he has permissions, confirming that this is not a matter of misconfigured permissions.

P.S.:
- This doesn't happen with Secrets only, but any resource that is allowed in one namespace but not in the other.
- He must have permissions to read/list at least some type of resource in namespace `B` for the bug to manifest.
- I tried running an old version of Lens (3.3.0), and there is a difference in behavior. The menu is not missing, but no secrets are listed, and an error pops-up: `secrets is forbidden: User "username" cannot list resource "secrets" in API group "" in the namespace "B"`. Which is also a problem, because it should list the secrets for the other namespaces he has access to.

**To Reproduce**
1. Have a user that can read/list secrets in some namespace `A`, but not in namespace `B`
2. Make sure the user can read/list at least 1 other type of resouces in both namespaces `A` and `B`.
3. Open Lens using this user credentials
4. The Secrets menu is missing

**Expected behavior**
The user should be able to see the Secrets menu, and see the secrets for the namespaces he has permissions to.

**Screenshots**
The missing Secrets menu
![Screenshot from 2020-08-25 16-43-48](https://user-images.githubusercontent.com/5041650/91220187-2d9d9e80-e6f2-11ea-8f89-d5aad1d18cef.png)

**Environment (please complete the following information):**
- Lens Version: 3.5.3
- OS: Linux, tested in both Ubuntu and Fedora
- Installation method: tested with both snap and AppImage
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
debug: Set kubectl version 1.17.4 for cluster version 1.17.4 using version map
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
info: Checking for update
debug: getFreePort() start
debug: getNextAvailablePort() start
debug: *** server listening event ***
debug: got port : 42207
debug: Creating temporary kubeconfig: /tmp/8dx2txfr10h-sgywjyga3q-kubeconfig
debug: Creating temporary kubeconfig: /tmp/6wengcknm4a-nsz7qemtie-kubeconfig
debug: Starting to load target definitions for <hidden>
debug: Creating temporary kubeconfig: /tmp/kr3r2m5qk9k-z4trsaidkoa-kubeconfig
debug: Created cluster[id: 673f94bc-abfc-4fea-b129-4c5224524964] for context <hidden>
debug: Starting to load target definitions for <hidden>
debug: Creating temporary kubeconfig: /tmp/dnn6gifyuel-seaede6vye9-kubeconfig
debug: Created cluster[id: 145dda23-2fdc-47b3-b342-d165f0b93b6b] for context <hidden>
debug: clusters after constructor:2
debug: IPC: preferencesSaved
debug: IPC: getClusters, workspace default
info: Update for version 3.5.3 is not available (latest version: 3.5.3, downgrade is disallowed).
debug: checkForUpdatesAndNotify called, downloadPromise is null
debug: IPC: getCluster
debug: Creating temporary kubeconfig: /tmp/rl4srxzd1ir-53qelmru8sx-kubeconfig
debug: Creating temporary kubeconfig: /tmp/lf2veiemnjd-fd9jabb82hn-kubeconfig
debug: getFreePort() start
debug: getNextAvailablePort() start
debug: *** server listening event ***
debug: got port : 38869
debug: Acquired a lock for 1.17.4
debug: Releasing lock for 1.17.4
debug: proxy <hidden> stdout: Authentication proxy started

debug: features for <hidden>
debug: feature metrics
debug: getting feature status...
debug: feature user-mode
debug: getting feature status...
debug: getFeatures resolving with features: {"metrics":{"currentVersion":null,"installed":false,"latestVersion":"v2.17.2-lens1","canUpgrade":false},"user-mode":{"currentVersion":null,"installed":false,"latestVersion":"v2.0.0","canUpgrade":false}}
debug: failed to request node list: 403 - {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"nodes is forbidden: User \"username\" cannot list resource \"nodes\" in API group \"\" at the cluster scope","reason":"Forbidden","details":{"kind":"nodes"},"code":403}
debug: Set kubectl version 1.16.8 for cluster version v1.16.7 using version map
debug: Acquired a lock for 1.16.8
debug: Local kubectl is version 1.16.8
debug: Releasing lock for 1.16.8```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <hidden>
    server: api-url
  name: cluster-name
contexts:
- context:
    cluster: cluster-name
    namespace: test
    user: username
  name: context-name
current-context: ""
kind: Config
preferences: {}
users:
- name: username
  user:
    client-certificate-data: <hidden>
    client-key-data: <hidden>
```

**Additional context**
Add any other context about the problem here.

**Comment by CyborgMaster** [comment]
Same problem.  I have access to view and edit secrets in only one namespace in our production cluster, but not any other namespace.  The secrets tab isn't visible at all.

**Comment by vsel** [comment]
Same problem. 
I can do 
`kubectl get secret xxx --export -o yaml` 
But I don`t see Secret in Configuration.

**Comment by jakolehm** [comment]
Partially fixed in https://github.com/lensapp/lens/pull/1830

**Comment by Nokel81** [comment]
FYI, if you add the list of namespaces that you know you have any permissions in at at under "accessible namespaces" in cluster settings. Then that will help too (only necessary if the user doesn't have `list namespaces` permissions.

**Comment by Nokel81** [comment]
@luislhl Is this still a problem with `4.1`? A complete solution for this is planned but would require using the equivalent of `kubectl auth can-i --list -n ${namespace}`.

**Comment by Nokel81** [comment]
I think that this requires a bigger fix than a patch version or even in time for `4.2`. Since it basically requires checking all namespaces (or simpler checking the namespaces that have been selected by the `NamespaceFilterSelect` (if that becomes global. 

I am going to unassign myself until we have a good design on this.

**Comment by jim-docker** [comment]
@luislhl Is this still an important issue after the merge of #1830 ?

**Comment by luislhl** [comment]
@jim-docker , it seems the issue is gone now in the latest version.

Thank you!
