### ISSUE TITLE
Add "Back" button for description sidebar

### ISSUE THREAD

**Issue by YorikSar** [lensapp/lens#759]
**What would you like to be added**:

A "back" button to traverse the history of links followed in Lens UI.

**Why is this needed**:

I found myself sometimes following links quite deep in Lens UI, for example:
* find a StatefulSet that is failing, open it
* check list of pods in the sidebar, find the problematic one, click on it
* check which node it got assigned to, click on it
* act on some info about the node (e.g. get IP address to SSH to it)

After this I want to be able to get back to the Pod or StatefulSet description, but I can't.

**Environment you are Lens application on:**

- Kubernetes distribution: Mirantis DE Container Cloud
- Desktop OS: macOS

**Comment by adanin** [comment]
That would be a great improvement!

**Comment by Nokel81** [comment]
This has been released as part of 5.2. It was added by https://github.com/lensapp/lens/pull/3719
