### ISSUE TITLE
Improved organization/support for large number of clusters

### ISSUE THREAD

**Issue by seanwcom** [lensapp/lens#76]
**What would you like to be added**: 

I'd like to see improved organization/support for large number of clusters.

**Why is this needed**: 

My team manages many Kubernetes clusters for our company; we provide a "cluster as a service" for our company in addition to managing our large shared platform. Because of this, we manage a lot of clusters. 

Adding all our clusters to Lens leads to many icons that are pretty, but don't help to identify one from another. Furthermore, there's also no way to scroll the far left list of icons if you exceed the vertical limit. The recent change to allow replacing the icon is nice, but I suspect this would be most helpful in a case where we only have a few clusters. I currently have 14 clusters added, but could still add another 8 - 10 clusters.

I'm definitely not a UI expert, but what I'm picturing is a tabbed environment. When I create a new tab, I have a dropdown to pick a cluster for that tab. This would give me tabs that I can easily switch between when I need to focus on a few clusters at a time.

**Environment you are Lens application on:**

- Kubernetes distribution:
  - All our clusters are on-prem, nothing in the cloud
  - We manage our Kubernetes clusters with Rancher
  - We also manage OpenShift clusters
- Desktop OS: MacOS & Windows

**Comment by miskun** [comment]
The current plan is following:

1) We will make it possible to group clusters together. Similar to ios/android UI, when you drag an icon over another icon, a group is created. If you want to open a cluster from a group, you'll need to open that group first, then select and icon. Cluster may be removed from a group by pulling (dragging) it out.
2) We will add workspaces/projects. This is top level switch that can be used to switch between multiple different workspaces/projects. A cluster may belong to multiple workspaces/projects. 
3) Factory default icons. To make dealing with multiple clusters more easy, we'll add collection of factory default icons for easy picking. There will be possiblity to pick color for those icons, too. This will remove need to upload your own icon for every cluster (to make them look different).
4) Alphabetically labeled default icons. The current hexagon icon is cool but not so easy to distinguish from others. We are therefore considering on replacing those hexagon icons with colorful labels with up to 3 alphabets (auto generated/manually picked) from the cluster name. E.g. "PRD", "QA", "TST"...

**Comment by seanwcom** [comment]
Workspaces sounds like a great idea for us. We separate by networks and availability (prod, pci compliant, etc). For our needs, I believe we could use a workspace per network, then grouping within that. 

Your 4th bullet above sounds perfect. Simple, colorful label, with a tag that I can put on it would help a ton. Maybe allow more characters, up to a max (like 6 or something), but have the letters scale to fit?

Thanks for the update!

**Comment by peterloron** [comment]
These changes will be very useful. I would strongly urge the addition of a no-icon "list" view of the servers.

**Comment by skoef** [comment]
I started using workspaces today and I like the concept, however, I would like to be able to choose the color of the (currently) blue bar in the bottom. For instance so I can choose green for development/testing and red for production clusters.

**Comment by jakolehm** [comment]
I think we can close this now that Lens has workspaces.
