### ISSUE TITLE
Sorting order is not preserved when changing views

### ISSUE THREAD

**Issue by juv** [lensapp/lens#763]
**What would you like to be added**:
When selecting a sorting order of a column, the sorting order is removed when switching through views.
Example:
1) Go to view "Pods", select column "Age" to sort the timestamps descending 
2) Go to view "Deployments", the sorting order is now reset for the view "Deployments"
3) Go back to view "Pods", the sorting order is now reset back to default for the view "Pods" as well

It would be preferrable to me to keep the sorting order for the column throughout the Lens session _or_ throughout all subsequent Lens sessions by making Lens save the sorting order (maybe make the latter configurable?) 

**Why is this needed**:
For every view change, the user has to reselect his preferred sorting order

**Environment you are Lens application on:**
3.6.0-beta.1

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
not relevant 

- Desktop OS: <the OS Lens app runs on in your case>
Windows 10

**Comment by techdragon** [comment]
Replicated with macOS

**Comment by adamrushuk** [comment]
This is one of those features that you _really_ take for granted in other apps. I must've done 100's of extra clicks yesterday, so looking forward to seeing this implemented 👍

**Comment by vshakirova** [comment]
Hi @juv. Will it be ok if we keep sorting order for each table only for a current session? After restarting the program, the sorting will be reset.
