### ISSUE TITLE
View reload (ctrl+r hotkey) causes entire application reload

### ISSUE THREAD

**Issue by juv** [lensapp/lens#764]
**Describe the bug**
I think https://github.com/lensapp/lens/pull/327 was broken by the recent UI switch. When I hit CTRL+R in Windows, the whole Lens window refreshes, causing a reconnect to the cluster but not a refresh of the current view and I also get switched to the "Workloads -> Overview" tab

**To Reproduce**
1. Go to Workloads -> Pods
2. Press CTRL+R to reload the current view 
3. Lens window flashes, all ui components get removed and only the background is visible, then the cluster connection will be reopened
4. Workloads -> Overview is selected

**Expected behavior**
Only the current view and its Kubernetes resources are reloaded

**Environment (please complete the following information):**
- Lens Version: 3.6.0-beta1
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): Windows Setup

**Comment by aleksfront** [comment]
Fixed in https://github.com/lensapp/lens/pull/783
