### ISSUE TITLE
Events in Cluster view is limited to 10

### ISSUE THREAD

**Issue by ryan-dyer-sp** [lensapp/lens#766]
**What would you like to be added**:
The ability to see more than 10 events in the cluster view

**Why is this needed**:
To see all the events in the last hour, not just the 10 most recent.  I know k8s events are limited to 1hr, but right now the UI appears to still only display the most recent 10 events.  We have a cluster which is apparently having some issues and we're not able to see all the events for the past hour, but the most recent 10.

**Environment you are Lens application on:**

- Kubernetes distribution: k8s 1.18 on ec2 via kops
- Desktop OS: windows

**Comment by ixrock** [comment]
If you're talking about `Workloads` -> `Overview` then this page has limited events to `10`. 
To see all last events (limited to 1000) you should go to separate `Events` page:
![image](https://user-images.githubusercontent.com/6377066/91610425-d877bc00-e981-11ea-9d0c-695b94292813.png)

**Comment by ryan-dyer-sp** [comment]
Sorry for delay.  I was actually talking about the Cluster view.  It doesnt appear to be limited to 10, but there is some limit on it.  The Events tab though it shows the information, also shows more than warnings and errors which is all that is seen on the Cluster view and there doesnt appear to be a way to filter out the informational messages from the events view.
