### ISSUE TITLE
Receive events for all clusters on app init

### ISSUE THREAD

**Issue by ixrock** [lensapp/lens#768]
Currently, when app starts, only activated clusters receive full state which includes `eventCount` which appears as badge in `ClusterIcon`.
Maybe we'd like to include `eventsCount` to initial clusters state? Most probably we need to call some extra apis in `cluster.init()`.
Also maybe some other info for all initial clusters state will be beneficial? Like, at least add `online`/`offline` state to tweak cluster-icon style in some way?

**Current behaviour:**
_1) App started, cluster-view activated, event badge is shown_
<img width="461" alt="91608709-bc265000-e97e-11ea-99e4-f9281071e00e" src="https://user-images.githubusercontent.com/6377066/91632781-d8140b00-e9eb-11ea-9c9f-79279a853841.png">

_2) Click to second cluster, second badge updated_
<img width="551" alt="91608722-c0526d80-e97e-11ea-8351-a1d362108c59" src="https://user-images.githubusercontent.com/6377066/91632784-da766500-e9eb-11ea-9ce4-330d975f0c92.png">

**Comment by Nokel81** [comment]
I don't think we want to do this since that would involved connecting to all the clusters. Though I have noticed that the active cluster doesn't always show the event count currently.

**Comment by Nokel81** [comment]
Closing as we are no longer displaying cluster events there.
