### ISSUE TITLE
Add a way to selfupdate the app

### ISSUE THREAD

**Issue by christhomas** [lensapp/lens#770]
I think it would be an excellent idea if the app would notify me there is an updated version, offer to install it. Many applications do that and I think it would allow me to keep up to date easier.

**Comment by nevalla** [comment]
The app is doing this already. There are two release channels `stable` and `beta`. If you have installed `stable` release you won't get updates for `beta` releases and vice versa.

**Comment by christhomas** [comment]
Then how do you get the stable and beta versions, since on the github releases page there is no information about this

**Comment by nevalla** [comment]
By installing pre-release you will get `beta` channel. And by installing stable release you will get `stable`.

**Comment by christhomas** [comment]
Yes, I understand this, but on the github releases page, is it there? That was what I was wondering
