### ISSUE TITLE
can't launch lens within ubuntu 18.04

### ISSUE THREAD

**Issue by tscswcn** [lensapp/lens#771]
**Describe the bug**
can't launch lens within ubuntu 18.04

**To Reproduce**
have  install 

snap list
Name          Version      Rev   Tracking       Publisher   Notes
core          16-2.45.3.1  9804  latest/stable  canonical✓  core
core18        20200724     x1    -              -           base
kontena-lens  3.5.3        x1    -              -           classic

 not see any issue, but the UI can't see 
cand  init 5 
I can see the ico in the start menu.  but when click the lens ico,  it doesn't show the UI

**Expected behavior**
 show the UI

and 

**Screenshots**
![pic](https://github.com/tscswcn/kubernetes/blob/master/len_cant_start.PNG)
**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux): 
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
I am unable to reproduce this, if this is still an issue. Please open a new issue.
