### ISSUE TITLE
Status details for Ingress

### ISSUE THREAD

**Issue by Vacant0mens** [lensapp/lens#772]
**What would you like to be added**:
`kubectl get ingress` and `kubectl describe ingress` both show an External IP (as an `Address` property), and the Edit view in Lens currently shows `status:loadBalancer` in the yaml (which includes `ingress:ip`). It'd be nice to see this in the Ingress sidebar, especially if there are any issues with the Ingress object itself. 

**Why is this needed**:
The only other way to see the external IP for the Ingress is to go to the `Edit` view or run `kubectl [get|describe] ingress`. And if there were anything wrong with the Ingress object, it would show up in the `status` property.

We can already see the status of pods and other workload objects, but it would also be nice to see the status of the Network objects.

**Environment you are Lens application on:**
- Kubernetes distribution: any
- Desktop OS: Windows 10

**Comment by stevejr** [comment]
Pull Request https://github.com/lensapp/lens/pull/1064 raised
