### ISSUE TITLE
Reduce memory usage

### ISSUE THREAD

**Issue by sunnoy** [lensapp/lens#775]
lens app  should Reduce memory usage in mac
![image](https://user-images.githubusercontent.com/19342276/91789677-b744f300-ec41-11ea-9fb1-8076fc8b7c57.png)

**Environment you are Lens application on:**
- Desktop OS: mac 2015

**Comment by Nokel81** [comment]
What version of lens are you using? How many clusters do you have connected?

I built the current version of master and these are my results.
<img width="657" alt="Screen Shot 2020-09-03 at 2 38 08 PM" src="https://user-images.githubusercontent.com/8225332/92153993-17c76200-edf3-11ea-9244-b5172a7316e7.png">

**Comment by sunnoy** [comment]
3.5.1
mycluster is 5

**Comment by Nokel81** [comment]
3.5.1 is no longer supported. If this is still an issue, please open a new issue.
