### ISSUE TITLE
AppImage : Lens is restarting by itself after being closed

### ISSUE THREAD

**Issue by olivierchatry** [lensapp/lens#79]
**Describe the bug**
Using AppImage, on Fedora 31, if I close Lens, it restart by itself.

**To Reproduce**
Launch using AppImage, close Lens, it reopen by itself. Get even worst if launched from command line, pressing `ctrl+c` spawn multiple instance, to the point of I had to hard reset my computer. 

**Expected behavior**
`ctrl+c` or quit Lens should be actually quitting Lens.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 2.5.1 ( was doing it before )
- OS: [e.g. OSX] Linux Fedora 31
- Installation method (e.g. snap or AppImage in Linux): AppImage

**Comment by jnummelin** [comment]
If you start the app from command line, do you see any errors or messages which might explain why the app restarts automatically?

**Comment by olivierchatry** [comment]
The only warnings I have is : 

`Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"`

**Comment by olivierchatry** [comment]
Tried to look at it, did not find anything special. Not sure why it is restarting, maybe a bug in electron ?

**Comment by Nokel81** [comment]
Is this still a problem?

**Comment by olivierchatry** [comment]
Not sure I'm not using Linux anymore.

**Comment by Nokel81** [comment]
okay thanks. I will close this issue as it is quite old and we have made many changes. If this happens again someone can open a new ticket.
