### ISSUE TITLE
Docker Desktop (WSL2, Ubuntu, Win10) x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error

### ISSUE THREAD

**Issue by nilayparikh** [lensapp/lens#790]
Failing to connect docker-desktop kubernetes on Windows 10 (WSL2 enabled and Ubuntu distro). 

Error "offline (x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes"))"

![image](https://user-images.githubusercontent.com/1396372/91966342-9c3db600-ed09-11ea-96e8-11555e4ee8e6.png)

Has anyone previously faced slimier issue?

**Comment by fakoua** [comment]
Similar issue here:

`offline (dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.)`

**Comment by edvald** [comment]
Getting the certificate issue on Mac, with latest Docker Desktop (3.0.4):

![image](https://user-images.githubusercontent.com/155684/104525230-fe83bd00-55ff-11eb-8be7-6e80d4ad90c9.png)

**Comment by Nokel81** [comment]
Have you tried adding `insecure-skip-tls-verify: true`?

**Comment by nilayparikh** [comment]
I can connect.
