### ISSUE TITLE
On clicking Delete icon for Namespace there should be confirmation Yes/No since it is VERY destructive

### ISSUE THREAD

**Issue by JiriZidek** [lensapp/lens#7905]
**On clicking Delete either from dot-menu or from detail by icon, LENs should display simple confirmation dialog Yes/No with clearely showing which Namespace is about to be destroyed.**:

If a user is not concentrated enough, it allows him to doble check, that he is doing what intended. It also ensures, that he mistakenly did not change his selection. Moreover the Close detail icon (cross) is just next to Delete icon (wastebin), so using when using touchpad or touchscreen can bring tears....

**Environment you are Lens application on:**
- Kubernetes distribution: various
- Desktop OS: Windows 11

![image](https://github.com/lensapp/lens/assets/8578952/4568e0b5-10c8-4a3d-8bf1-a384119f3fe7)

**Comment by fisherwei** [comment]
if ns is not empty, LENs should ask user input namespace name again

**Comment by JiriZidek** [comment]
> if ns is not empty, LENs should ask user input namespace name again

That is not the case. LENs silently kills NS event it is full of objects.

**Comment by samitiilikainen** [comment]
Thanks for reporting! This is fixed and will be released in an upcoming release.
