### ISSUE TITLE
Download links broken on website

### ISSUE THREAD

**Issue by huang-jy** [lensapp/lens#7918]
**Describe the bug**
Download links broken on website

**To Reproduce**
1. Go to https://k8slens.dev/
2. Note the text "Latest Version: vLatest (Invalid Date)"
3. Select the download type (any of them)
4. Get a 404

**Expected behavior**
Expect to be able to download

**Screenshots**
![image](https://github.com/lensapp/lens/assets/2756283/5c2ce1a6-3ed2-4fcb-bcb8-e6dc198279c3)

**Environment (please complete the following information):**
- Windows, Manjaro, Fedora
- exe, AppImage, RPM

**Logs:**
N/A

**Kubeconfig:**
N/A

**Additional context**
N/A

**Comment by griffith-h** [comment]
unfortunate too

**Comment by huang-jy** [comment]
Closing as it now appears to be fixed
