### ISSUE TITLE
After update can't select container for execute shell

### ISSUE THREAD

**Issue by alex-kovalchuk** [lensapp/lens#7935]
**Describe the bug**
After update to 2023.9.22 can't select container for execute Shell.

**To Reproduce**
1. Go to Pods
2. Open pod menu -> Shell -> container

**Expected behavior**
Opened Shell for selected container.

**Screenshots**
Select container: https://drive.google.com/file/d/1inZgSkGxSLGZ0BMAbotmTtnqzlKCPNfe/view?usp=sharing
Command in the terminal. https://drive.google.com/file/d/1H-8TyHIcmc3fMgfSsG4AaO8uoEFLzCPQ/view?usp=sharing

**Environment:**
- Lens Version: 2023.9.221258
- OS: Ventura 13.5
- Installation method: AppImage

**Comment by artemmelnik** [comment]
I have the same. Decide faster

**Comment by Nokel81** [comment]
Thanks for posting this. We will have this fixed shortly, hopefully in the next release. 

Please note though for future bug reports concerning Lens Desktop please read our FAQ on the topic:

 https://docs.k8slens.dev/faq/#q-there-is-a-lens-release-out-on-the-lens-forums-but-no-new-release-on-github-is-openlens-discontinuedabandoned
