### ISSUE TITLE
Reload does not work when in cluster settings

### ISSUE THREAD

**Issue by Nokel81** [lensapp/lens#796]
**Describe the bug**
Reloading Lens (using CMD+R or the menu option) should reload the renderer. This works great. However, when in the cluster settings view it does nothing. I know that the command shortcut is working on macos at least because the menu is flashing as expected.

**To Reproduce**
1. Right click a cluster icon and click settings
2. Try and reload the window
4. See that nothing reloads

**Expected behavior**
The window should reload in all places

**Environment (please complete the following information):**
- Lens Version: master 43f304427399bed476a596c86e838dbe6260efd9
- OS: [e.g. OSX] macos
- Installation method (e.g. snap or AppImage in Linux): git clone

**Comment by Nokel81** [comment]
@nevalla This still is an issue on `3.6.0-rc2`

**Comment by nevalla** [comment]
So this is real issue more on dev env rather than on production?

**Comment by Nokel81** [comment]
I don't understand, if I run my downloaded copy of the RC then this issue still exists (that reloads on the cluster settings page do nothing)

**Comment by nevalla** [comment]
Yeah, I get it and agree that this is still a bug. Just thinking out loud what would you expect to happen if the reload was actually working, would you see any text to change?

**Comment by Nokel81** [comment]
Well I would expect the reload to do what the reload does on every other screen (like the cluster home screen). If for some reason the UI got bugged. I think that this will be more important with the extensions going forward since they could be buggy too. (I reload VS code at least a couple times a day for instance).

**Comment by nevalla** [comment]
>  I think that this will be more important with the extensions going forward since they could be buggy too. (I reload VS code at least a couple times a day for instance).

Fair point

**Comment by aleksfront** [comment]
The main issue here that when you have active cluster opened and then go to Cluster Settings - it tries to reload opened dashboard (active cluster). Fixing behavior can be full app reload when located in `Preferences`, `Cluster Settings` and `Add Cluster` page.
