### ISSUE TITLE
Namespace selector is cluttered

### ISSUE THREAD

**Issue by centfox** [lensapp/lens#7978]
**Describe the bug**
The namespace selector becomes cluttered and unreadable when the length of namespaces are longer and wraps to next line.

**To Reproduce**
1. Go to namespace selector.
2. You can see longer namespaces are wraped to next line and overlaps with the next item.

**Expected behavior**
All the namespace should be clearly visible and readable.

**Environment (please complete the following information):**
- Lens Version: 2023.11.131420-latest
- OS: Windows 11 64 Bit
- Installation method: Installer

**Comment by saowu** [comment]
![image](https://github.com/lensapp/lens/assets/33569619/044b3e64-aca2-4ffe-9b4b-749f6a9e5021)

**Comment by jpastoor** [comment]
Hope this can get some attention. An UUID is already long enough to be wrapped:
![image](https://github.com/lensapp/lens/assets/733306/0f719ce2-01bd-47b9-9a0a-e17668ed274d)

**Comment by clrothmann** [comment]
Thank you very much for the feedback. Our team has already fixed that and it will be available in one of our upcoming releases.

**Comment by saowu** [comment]
![image](https://github.com/lensapp/lens/assets/33569619/26b7d8b7-8240-4be9-97bb-a9191fdab9ed)
![image](https://github.com/lensapp/lens/assets/33569619/89b20310-e739-408f-8874-9f91a01a73ed)
![image](https://github.com/lensapp/lens/assets/33569619/8be87044-6243-47af-8ddf-8af296ca547e)

**Comment by jakolehm** [comment]
I think this can be closed because the latest version has a fix:
<img width="723" alt="image" src="https://github.com/user-attachments/assets/6d5672d9-4dc0-45f7-a261-0128eb6a82db">
