### ISSUE TITLE
Some font icons display their name

### ISSUE THREAD

**Issue by logerror** [lensapp/lens#798]
![image](https://user-images.githubusercontent.com/13896386/92085073-de92f000-edfa-11ea-8ffc-8d6a0a658a0c.png)

**Comment by logerror** [comment]
Problems shown

**Comment by logerror** [comment]
the os is ubuntu 18

**Comment by ixrock** [comment]
@logerror what the Linux and Lens versions?

**Comment by logerror** [comment]
![image](https://user-images.githubusercontent.com/13896386/92549407-bdfbe780-f28b-11ea-829d-e06e51807e14.png)

**Comment by logerror** [comment]
Linux  5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nevalla** [comment]
One more question :) Did you install from AppImage or Snap?

**Comment by logerror** [comment]
i follow this page : https://snapcraft.io/install/kontena-lens/ubuntu

`sudo snap install kontena-lens --classic`

**Comment by Nokel81** [comment]
Is this still an issue?, have you set `LANG` to anything?

**Comment by Nokel81** [comment]
Closing because of no response and have not been able to reproduce.
