### ISSUE TITLE
CPU and memory N/A on dashboard but availaible on details

### ISSUE THREAD

**Issue by paracetamol32** [lensapp/lens#7991]
CPU and memory N/A on dashboard but availaible on the details panel for all pods, i don't know why :

![image](https://github.com/lensapp/lens/assets/14573835/4ea6360f-c8ac-4502-b82f-5ce121ef2eae)

Config:

![image](https://github.com/lensapp/lens/assets/14573835/b0292114-6dc6-4215-bf70-47a8b23b0c84)

![image](https://github.com/lensapp/lens/assets/14573835/e4bb32a8-7b88-4f30-b91d-d5dbbdd59f78)

- Lens Version:
        Lens: 2023.12.80831-latest
        Extension API: 6.22.6
        Electron: 25.8.3
        Chrome: 114.0.5735.289
        Node: 18.15.0

- OS: OSX 14.2

**Comment by jisiallen** [comment]
I have the same problem

**Comment by Aizekso** [comment]
And I have the same problem, but not on all clusters. 2 out of 5 clusters do not display metrics on dashboard. 

Lens 2023.11.131420-latest
Extension API: 6.22.6
Electron: 25.8.3
Chrome: 114.0.5735.289
Node: 18.15.0

**Comment by paracetamol32** [comment]
Hi have try to deploy PROMETHEUS Operator an remove lens Metrics, but i have same issue

**Comment by Aizekso** [comment]
Installing metrics-server solved the problem for me!
https://github.com/kubernetes-sigs/metrics-server

**Comment by paracetamol32** [comment]
Yes !!! solved the problem for me!

**Comment by agrondemiraj** [comment]
I have the same issue. Metrics server is installed and works fine when checking `kubectl top nodes` but Lens Show N/A on Pod list and pods in the Node as well.
