### ISSUE TITLE
Keep search field value when navigating between objects

### ISSUE THREAD

**Issue by AdamoT** [lensapp/lens#7997]
**What would you like to be added**:
When navigating between sections on the left side, for instance Pods, Deployments, Secrets, Network etc. - the search field should not get cleared out. That behaviour should be similar to Namespace selection next to it, which keeps the value when navigating between objects.

**Why is this needed**:
Usually objects in k8s are created using same or very similar names for individual services. For instance a deployment called `xyz`, would have associated configmap or secrets, ingresses etc. also named `xyz` and pods created from this deployment would be prefixed with `xyz` as well. 
As a Lens user, when I'm focused on configuring or debugging a single deployment, I want to navigate between different objects associated with it. Having a long list of objects in a single namespace, everytime I change from for instance Deployments to Pods to investigate logs, or to Configmap to fix values - I need to search for the `xyz` again and again. 
As a user I would save a lot of time using Lens if the search field kept its value when navigating between objects in exactly the same way the Namespace search field works currently.

- Kubernetes distribution: AKS
- Desktop OS: Windows

**Comment by Nokel81** [comment]
Thanks for the feature request, this is on our radar

**Comment by panuhorsmalahti** [comment]
Is the "Pin" feature of the search bar enough here?

**Comment by AdamoT** [comment]
I just upgraded to `2024.1.170738` from a `2023.12.x` version and now have the separate search bar!!

> Is the "Pin" feature of the search bar enough here?

Yes, it does exactly what was needed here and much more! Love it! Thank you!

**Comment by rasenfer** [comment]
I can't find the "pin search" option in 2025.02 version, how i can configure it?

**Comment by AdamoT** [comment]
I also recently updated to 2025.02 and discovered that this feature is gone. 
I was just about to rollback to previous version because of that, but then discovered that now you can open multiple tabs, one with pods, another with deployments etc. It's not entirely replacing the "pin search" functionality and I would like it back, but it's something. 
The UX for opening a new tab is also not great, because it's difficult to discover - the only way to open a new tab is by double clicking given resource type.
