### ISSUE TITLE
Extension-Loader activation extension error on startup

### ISSUE THREAD

**Issue by nopjar** [lensapp/lens#7998]
**Describe the bug**
When starting lens it does not instantly open anymore. It takes ages and some features are not available. I didn't change anything directly in lens.

**To Reproduce**
I have no idea. Issue just began to happen.

**Expected behavior**
I would except lens to not throw the error and run like before.

**Environment (please complete the following information):**
- Lens Version: v6.5.2
- OS: Manjaro Linux
- Installation method (e.g. snap or AppImage in Linux): AppImage

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
error:   ┏ [EXTENSIONS-LOADER]: activation extension error +3ms
error:   ┃ [  1] {
error:   ┃ [  2]   ext: {
error:   ┃ [  3]     absolutePath: 'irrelevant',
error:   ┃ [  4]     id: '@lensapp/oci-image-lens-extension',
error:   ┃ [  5]     isBundled: true,
error:   ┃ [  6]     isCompatible: true,
error:   ┃ [  7]     isEnabled: true,
error:   ┃ [  8]     manifest: {
error:   ┃ [  9]       name: '@lensapp/oci-image-lens-extension',
error:   ┃ [ 10]       version: '0.36.1',
error:   ┃ [ 11]       description: 'OCI image Lens extension',
error:   ┃ [ 12]       main: 'dist/main.js',
error:   ┃ [ 13]       renderer: 'dist/renderer.js',
error:   ┃ [ 14]       storeName: 'oci-image-lens-extension',
error:   ┃ [ 15]       files: [ 'bin/*', 'dist/**/*', 'resources/**/*' ],
error:   ┃ [ 16]       engines: { lens: '^6.0.0', node: '^18.0.0' },
error:   ┃ [ 17]       exports: { './package.json': './package.json', './main': './dist/main.js', './renderer': './dist/renderer.js' },
error:   ┃ [ 18]       repository: { type: 'git', url: 'git+https://github.com/lensapp/oci-image-lens-extension.git' },
error:   ┃ [ 19]       author: 'k8slens.dev',
error:   ┃ [ 20]       license: 'UNLICENSED',
error:   ┃ [ 21]       homepage: 'https://github.com/lensapp/oci-image-lens-extension#readme',
error:   ┃ [ 22]       devDependencies: {
error:   ┃ [ 23]         '@aws-sdk/client-ecr': '3.188.0',
error:   ┃ [ 24]         '@emotion/css': '11.11.2',
error:   ┃ [ 25]         '@emotion/react': '11.10.5',
error:   ┃ [ 26]         '@emotion/styled': '11.10.4',
error:   ┃ [ 27]         '@k8slens/eslint-config': 'latest',
error:   ┃ [ 28]         '@lensapp/extensions': '^6.10.22',
error:   ┃ [ 29]         '@lensapp/lens-platform-extension-sdk': '^6.1.0',
error:   ┃ [ 30]         '@lensapp/list-layout': '^1.7.0',
error:   ┃ [ 31]         '@lensapp/prettier-config': '0.3.7',
error:   ┃ [ 32]         '@lensapp/table': '^1.3.5',
error:   ┃ [ 33]         '@ogre-tools/linkable': '15.9.0',
error:   ┃ [ 34]         '@swc/cli': '0.1.59',
error:   ┃ [ 35]         '@swc/core': '1.2.168',
error:   ┃ [ 36]         '@swc/jest': '0.2.23',
error:   ┃ [ 37]         '@testing-library/dom': '8.19.1',
error:   ┃ [ 38]         '@testing-library/jest-dom': '5.16.5',
error:   ┃ [ 39]         '@testing-library/react': '12.1.5',
error:   ┃ [ 40]         '@testing-library/user-event': '14.4.3',
error:   ┃ [ 41]         '@types/jest': '27.5.2',
error:   ┃ [ 42]         '@types/lodash': '4.14.186',
error:   ┃ [ 43]         '@types/node': '16.18.14',
error:   ┃ [ 44]         '@types/papaparse': '5.3.7',
error:   ┃ [ 45]         '@types/react': '17.0.50',
error:   ┃ [ 46]         '@types/react-dom': '17.0.17',
error:   ┃ [ 47]         '@types/react-router-dom': '5.3.3',
error:   ┃ [ 48]         '@types/tar': '6.1.3',
error:   ┃ [ 49]         '@typescript-eslint/eslint-plugin': '5.46.1',
error:   ┃ [ 50]         '@typescript-eslint/parser': '5.43.0',
error:   ┃ [ 51]         conf: '7.1.2',
error:   ┃ [ 52]         'css-loader': '6.8.1',
error:   ┃ [ 53]         'date-fns': '2.29.3',
error:   ┃ [ 54]         electron: '^25.3.0',
error:   ┃ [ 55]         eslint: '8.28.0',
error:   ┃ [ 56]         'eslint-config-airbnb': '19.0.4',
error:   ┃ [ 57]         'eslint-config-prettier': '8.5.0',
error:   ┃ [ 58]         'eslint-plugin-import': '2.27.5',
error:   ┃ [ 59]         'eslint-plugin-jsx-a11y': '6.6.1',
error:   ┃ [ 60]         'eslint-plugin-no-unsanitized': '4.0.2',
error:   ┃ [ 61]         'eslint-plugin-prettier': '4.2.1',
error:   ┃ [ 62]         'eslint-plugin-react': '7.31.11',
error:   ┃ [ 63]         'eslint-plugin-react-hooks': '4.6.0',
error:   ┃ [ 64]         'eslint-plugin-security': '1.6.0',
error:   ┃ [ 65]         'eslint-plugin-unused-imports': '2.0.0',
error:   ┃ [ 66]         'eslint-plugin-xss': '0.1.12',
error:   ┃ [ 67]         got: '11.8.6',
error:   ┃ [ 68]         jest: '27.5.1',
error:   ┃ [ 69]         lodash: '4.17.21',
error:   ┃ [ 70]         'lru-cache': '7.14.1',
error:   ┃ [ 71]         mobx: '6.8.0',
error:   ┃ [ 72]         'mobx-react': '7.6.0',
error:   ┃ [ 73]         papaparse: '5.4.1',
error:   ┃ [ 74]         prettier: '2.7.1',
error:   ┃ [ 75]         react: '17.0.2',
error:   ┃ [ 76]         'react-dom': '17.0.2',
error:   ┃ [ 77]         'react-router-dom': '5.3.4',
error:   ┃ [ 78]         'run-script-os': '1.1.6',
error:   ┃ [ 79]         'sanitize-filename': '1.6.3',
error:   ┃ [ 80]         semver: '7.5.4',
error:   ┃ [ 81]         'style-loader': '3.3.3',
error:   ┃ [ 82]         'swc-loader': '0.2.3',
error:   ┃ [ 83]         tar: '6.1.13',
error:   ┃ [ 84]         tempy: '1.0.1',
error:   ┃ [ 85]         'tmp-promise': '3.0.3',
error:   ┃ [ 86]         'ts-loader': '8.4.0',
error:   ┃ [ 87]         'tsconfig-paths-webpack-plugin': '3.5.2',
error:   ┃ [ 88]         typescript: '^4.9.5',
error:   ┃ [ 89]         webpack: '5.76.0',
error:   ┃ [ 90]         'webpack-cli': '4.10.0'
error:   ┃ [ 91]       }
error:   ┃ [ 92]     },
error:   ┃ [ 93]     manifestPath: 'irrelevant'
error:   ┃ [ 94]   },
error:   ┃ [ 95]   error: Error: Error while encrypting the text provided to safeStorage.encryptString. Encryption is not available.
error:   ┃ [ 96]       at t.encryptString (/tmp/.mount_Lens-ljToQQF/resources/app.asar/node_modules/@lensapp/oci-image-lens-extension/dist/main.js:2:586046)
error:   ┃ [ 97]       at t.serializeModel (/tmp/.mount_Lens-ljToQQF/resources/app.asar/node_modules/@lensapp/oci-image-lens-extension/dist/main.js:2:591592)
error:   ┃ [ 98]       at t.load (/tmp/.mount_Lens-ljToQQF/resources/app.asar/node_modules/@lensapp/oci-image-lens-extension/dist/main.js:2:587679)
error:   ┃ [ 99]       at async ElectronSyncStore.initialize (/tmp/.mount_Lens-ljToQQF/resources/app.asar/node_modules/@lensapp/oci-image-lens-extension/dist/main.js:2:582830)
error:   ┃ [100]       at async /tmp/.mount_Lens-ljToQQF/resources/app.asar/node_modules/@lensapp/oci-image-lens-extension/dist/main.js:2:610579
error:   ┃ [101]       at async t.initializeAuthTokenStore (/tmp/.mount_Lens-ljToQQF/resources/app.asar/node_modules/@lensapp/oci-image-lens-extension/dist/main.js:2:616059)
error:   ┃ [102]       at async OciImageExtensionMain.initLicense (/tmp/.mount_Lens-ljToQQF/resources/app.asar/node_modules/@lensapp/oci-image-lens-extension/dist/main.js:2:1910171)
error:   ┃ [103]       at async OciImageExtensionMain.onActivate (/tmp/.mount_Lens-ljToQQF/resources/app.asar/node_modules/@lensapp/oci-image-lens-extension/dist/main.js:2:1908076)
error:   ┃ [104]       at async Promise.all (index 4)
error:   ┃ [105]       at async ExtensionLoader.loadExtensions (/tmp/.mount_Lens-ljToQQF/resources/app.asar/node_modules/@lensapp/core-common/dist/index.js:7264:5)
error:   ┗ [106] }
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
I am pretty sure that it is not needed. If it is, I will reach it in afterwards.
```

**Additional context**
Also tried to completely reinstall it, didn't have any effect.

**Comment by nopjar** [comment]
I have completely reinstalled the OS on my computer and the same error occurs! I think maybe one of the latest updates of electron or something broke it?

**Comment by imoisharma** [comment]
> **Describe the bug** When starting lens it does not instantly open anymore. It takes ages and some features are not available. I didn't change anything directly in lens.
> 
> **To Reproduce** I have no idea. Issue just began to happen.
> 
> **Expected behavior** I would except lens to not throw the error and run like before.
> 
> **Environment (please complete the following information):**
> 
> * Lens Version: v6.5.2
> * OS: Manjaro Linux
> * Installation method (e.g. snap or AppImage in Linux): AppImage
> 
> **Logs:** When you run the application executable from command line you will see some logging output. Please paste them here:
> 
> ```
> error:   ┏ [EXTENSIONS-LOADER]: activation extension error +3ms
> error:   ┃ [  1] {
> error:   ┃ [  2]   ext: {
> error:   ┃ [  3]     absolutePath: 'irrelevant',
> error:   ┃ [  4]     id: '@lensapp/oci-image-lens-extension',
> error:   ┃ [  5]     isBundled: true,
> error:   ┃ [  6]     isCompatible: true,
> error:   ┃ [  7]     isEnabled: true,
> error:   ┃ [  8]     manifest: {
> error:   ┃ [  9]       name: '@lensapp/oci-image-lens-extension',
> error:   ┃ [ 10]       version: '0.36.1',
> error:   ┃ [ 11]       description: 'OCI image Lens extension',
> error:   ┃ [ 12]       main: 'dist/main.js',
> error:   ┃ [ 13]       renderer: 'dist/renderer.js',
> error:   ┃ [ 14]       storeName: 'oci-image-lens-extension',
> error:   ┃ [ 15]       files: [ 'bin/*', 'dist/**/*', 'resources/**/*' ],
> error:   ┃ [ 16]       engines: { lens: '^6.0.0', node: '^18.0.0' },
> error:   ┃ [ 17]       exports: { './package.json': './package.json', './main': './dist/main.js', './renderer': './dist/renderer.js' },
> error:   ┃ [ 18]       repository: { type: 'git', url: 'git+https://github.com/lensapp/oci-image-lens-extension.git' },
> error:   ┃ [ 19]       author: 'k8slens.dev',
> error:   ┃ [ 20]       license: 'UNLICENSED',
> error:   ┃ [ 21]       homepage: 'https://github.com/lensapp/oci-image-lens-extension#readme',
> error:   ┃ [ 22]       devDependencies: {
> error:   ┃ [ 23]         '@aws-sdk/client-ecr': '3.188.0',
> error:   ┃ [ 24]         '@emotion/css': '11.11.2',
> error:   ┃ [ 25]         '@emotion/react': '11.10.5',
> error:   ┃ [ 26]         '@emotion/styled': '11.10.4',
> error:   ┃ [ 27]         '@k8slens/eslint-config': 'latest',
> error:   ┃ [ 28]         '@lensapp/extensions': '^6.10.22',
> error:   ┃ [ 29]         '@lensapp/lens-platform-extension-sdk': '^6.1.0',
> error:   ┃ [ 30]         '@lensapp/list-layout': '^1.7.0',
> error:   ┃ [ 31]         '@lensapp/prettier-config': '0.3.7',
> error:   ┃ [ 32]         '@lensapp/table': '^1.3.5',
> error:   ┃ [ 33]         '@ogre-tools/linkable': '15.9.0',
> error:   ┃ [ 34]         '@swc/cli': '0.1.59',
> error:   ┃ [ 35]         '@swc/core': '1.2.168',
> error:   ┃ [ 36]         '@swc/jest': '0.2.23',
> error:   ┃ [ 37]         '@testing-library/dom': '8.19.1',
> error:   ┃ [ 38]         '@testing-library/jest-dom': '5.16.5',
> error:   ┃ [ 39]         '@testing-library/react': '12.1.5',
> error:   ┃ [ 40]         '@testing-library/user-event': '14.4.3',
> error:   ┃ [ 41]         '@types/jest': '27.5.2',
> error:   ┃ [ 42]         '@types/lodash': '4.14.186',
> error:   ┃ [ 43]         '@types/node': '16.18.14',
> error:   ┃ [ 44]         '@types/papaparse': '5.3.7',
> error:   ┃ [ 45]         '@types/react': '17.0.50',
> error:   ┃ [ 46]         '@types/react-dom': '17.0.17',
> error:   ┃ [ 47]         '@types/react-router-dom': '5.3.3',
> error:   ┃ [ 48]         '@types/tar': '6.1.3',
> error:   ┃ [ 49]         '@typescript-eslint/eslint-plugin': '5.46.1',
> error:   ┃ [ 50]         '@typescript-eslint/parser': '5.43.0',
> error:   ┃ [ 51]         conf: '7.1.2',
> error:   ┃ [ 52]         'css-loader': '6.8.1',
> error:   ┃ [ 53]         'date-fns': '2.29.3',
> error:   ┃ [ 54]         electron: '^25.3.0',
> error:   ┃ [ 55]         eslint: '8.28.0',
> error:   ┃ [ 56]         'eslint-config-airbnb': '19.0.4',
> error:   ┃ [ 57]         'eslint-config-prettier': '8.5.0',
> error:   ┃ [ 58]         'eslint-plugin-import': '2.27.5',
> error:   ┃ [ 59]         'eslint-plugin-jsx-a11y': '6.6.1',
> error:   ┃ [ 60]         'eslint-plugin-no-unsanitized': '4.0.2',
> error:   ┃ [ 61]         'eslint-plugin-prettier': '4.2.1',
> error:   ┃ [ 62]         'eslint-plugin-react': '7.31.11',
> error:   ┃ [ 63]         'eslint-plugin-react-hooks': '4.6.0',
> error:   ┃ [ 64]         'eslint-plugin-security': '1.6.0',
> error:   ┃ [ 65]         'eslint-plugin-unused-imports': '2.0.0',
> error:   ┃ [ 66]         'eslint-plugin-xss': '0.1.12',
> error:   ┃ [ 67]         got: '11.8.6',
> error:   ┃ [ 68]         jest: '27.5.1',
> error:   ┃ [ 69]         lodash: '4.17.21',
> error:   ┃ [ 70]         'lru-cache': '7.14.1',
> error:   ┃ [ 71]         mobx: '6.8.0',
> error:   ┃ [ 72]         'mobx-react': '7.6.0',
> error:   ┃ [ 73]         papaparse: '5.4.1',
> error:   ┃ [ 74]         prettier: '2.7.1',
> error:   ┃ [ 75]         react: '17.0.2',
> error:   ┃ [ 76]         'react-dom': '17.0.2',
> error:   ┃ [ 77]         'react-router-dom': '5.3.4',
> error:   ┃ [ 78]         'run-script-os': '1.1.6',
> error:   ┃ [ 79]         'sanitize-filename': '1.6.3',
> error:   ┃ [ 80]         semver: '7.5.4',
> error:   ┃ [ 81]         'style-loader': '3.3.3',
> error:   ┃ [ 82]         'swc-loader': '0.2.3',
> error:   ┃ [ 83]         tar: '6.1.13',
> error:   ┃ [ 84]         tempy: '1.0.1',
> error:   ┃ [ 85]         'tmp-promise': '3.0.3',
> error:   ┃ [ 86]         'ts-loader': '8.4.0',
> error:   ┃ [ 87]         'tsconfig-paths-webpack-plugin': '3.5.2',
> error:   ┃ [ 88]         typescript: '^4.9.5',
> error:   ┃ [ 89]         webpack: '5.76.0',
> error:   ┃ [ 90]         'webpack-cli': '4.10.0'
> error:   ┃ [ 91]       }
> error:   ┃ [ 92]     },
> error:   ┃ [ 93]     manifestPath: 'irrelevant'
> error:   ┃ [ 94]   },
> error:   ┃ [ 95]   error: Error: Error while encrypting the text provided to safeStorage.encryptString. Encryption is not available.
> error:   ┃ [ 96]       at t.encryptString (/tmp/.mount_Lens-ljToQQF/resources/app.asar/node_modules/@lensapp/oci-image-lens-extension/dist/main.js:2:586046)
> error:   ┃ [ 97]       at t.serializeModel (/tmp/.mount_Lens-ljToQQF/resources/app.asar/node_modules/@lensapp/oci-image-lens-extension/dist/main.js:2:591592)
> error:   ┃ [ 98]       at t.load (/tmp/.mount_Lens-ljToQQF/resources/app.asar/node_modules/@lensapp/oci-image-lens-extension/dist/main.js:2:587679)
> error:   ┃ [ 99]       at async ElectronSyncStore.initialize (/tmp/.mount_Lens-ljToQQF/resources/app.asar/node_modules/@lensapp/oci-image-lens-extension/dist/main.js:2:582830)
> error:   ┃ [100]       at async /tmp/.mount_Lens-ljToQQF/resources/app.asar/node_modules/@lensapp/oci-image-lens-extension/dist/main.js:2:610579
> error:   ┃ [101]       at async t.initializeAuthTokenStore (/tmp/.mount_Lens-ljToQQF/resources/app.asar/node_modules/@lensapp/oci-image-lens-extension/dist/main.js:2:616059)
> error:   ┃ [102]       at async OciImageExtensionMain.initLicense (/tmp/.mount_Lens-ljToQQF/resources/app.asar/node_modules/@lensapp/oci-image-lens-extension/dist/main.js:2:1910171)
> error:   ┃ [103]       at async OciImageExtensionMain.onActivate (/tmp/.mount_Lens-ljToQQF/resources/app.asar/node_modules/@lensapp/oci-image-lens-extension/dist/main.js:2:1908076)
> error:   ┃ [104]       at async Promise.all (index 4)
> error:   ┃ [105]       at async ExtensionLoader.loadExtensions (/tmp/.mount_Lens-ljToQQF/resources/app.asar/node_modules/@lensapp/core-common/dist/index.js:7264:5)
> error:   ┗ [106] }
> ```
> 
> **Kubeconfig:** Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
> 
> ```
> I am pretty sure that it is not needed. If it is, I will reach it in afterwards.
> ```
> 
> **Additional context** Also tried to completely reinstall it, didn't have any effect.

There seems to be an issue with the latest patch of Lens on my MAC too. I found a workaround by downloading the older version from https://downloads.k8slens.dev/ide/Lens-2023.12.81947-latest-arm64.dmg. @nopjar

Reference: https://github.com/Homebrew/homebrew-cask/commit/580990ad3bec6e0ddc621a7b83c0f6c20c61bfb6

**Comment by nopjar** [comment]
With the newest Version `024.1.170738-latest` it worked again for me. Closing this issue.
