### ISSUE TITLE
Cannot use terminal after last update 2023.12.281947-latest

### ISSUE THREAD

**Issue by izecy** [lensapp/lens#8000]
**Describe the bug**
Cannot use terminal, stuck in Connecting ... state. Cannot execute to pod.

![image](https://github.com/lensapp/lens/assets/143979749/6ea3fb57-384c-4054-aaef-d93bbd7a0743)
![image](https://github.com/lensapp/lens/assets/143979749/6959f060-97ac-4905-b1d1-c1172b9843e1)

**To Reproduce**
1. Go to File - Preferences - Terminal
2. Default value is powershell.exe

![image](https://github.com/lensapp/lens/assets/143979749/24dd583f-78e0-4ca6-8277-97261b9fef7c)

3. Try change to full path C:\Windows\System32\WindowsPowerShell\v1.0/powershell.exe
4. Still not work

**Expected behavior**
Terminal work normally.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 2023.12.281947-latest
- OS: [e.g. OSX] Windows 10 Enterprise 22H2 19045.3803
- Installation method (e.g. snap or AppImage in Linux): Windows installer

**Comment by MatGal01** [comment]
I have the same problem.

**Comment by rauny-henrique** [comment]
I have the same problem too.

**Comment by dhorner71** [comment]
i have the same problem.

Lens Version: 2024.1.170738-latest
Chrome: 114.0.5735.289
OS: windows 10 enterprise 19044.3803

lens.log entry:
error: [SHELL-SESSION]: failed to open a local shell Failed to get directory containing kubectl: Error: Failed to symlink bundled kubectl {"stack":"Error: Failed to get directory containing kubectl: Error: Failed to symlink bundled kubectl\n    at C:\\Program Files\\Lens\\resources\\app.asar\\node_modules\\@lensapp\\core-main\\dist\\index.js:4085:15"}

based on other similar issues, i deleted everything under:
C:\Users\<uid>\AppData\Roaming\Lens\binaries\kubectl
and restarted lens.  the bundled folder did reappear but with no content.

**Comment by alexcherka** [comment]
Lens Version: 2023.12.281947-latest
Chrome: 114.0.5735.289
OS: Microsoft Windows 10 Pro 10.0.19045 Build 19045

I had the exact same issue for Windows. I was able to **resolve** by **closing** Lens application, **deleting** the C:\Users\<USER>\AppData\Roaming\Lens\binaries\kubectl folder and then relaunching Lens **as Admin**. 

Hope this helps someone else!

---
Looks like the final result of the binaries should be a folder called bundled with a app shortcut to C:\Users\<USER>\AppData\Local\Programs\Lens\resources\x64 where the kubectl exe resides

**Comment by MatGal01** [comment]
Thanks alexcherka .. working good!!

**Comment by maximveksler** [comment]
Same for me on Mac. Not good, very bad.

**Comment by msa0311** [comment]
Thanks for reporting, a fix for this will be release soon.

**Comment by msa0311** [comment]
Fixed with latest release: https://github.com/lensapp/lens/releases/tag/v2024.1.300751-latest

Please let us know if the issue persists!

**Comment by nowakmax** [comment]
Issue still persist. Lens Setup 2024.1.300751-latest version. Cant connect with pod terminal. Same error. 
![image](https://github.com/lensapp/lens/assets/99726556/23a64855-21ce-46d7-8213-26a71eb10069)
