### ISSUE TITLE
Extension won't install in OpenLens

### ISSUE THREAD

**Issue by walec51** [lensapp/lens#8002]
**Describe the bug**
Installed OpenLens from https://github.com/MuhammedKalkan/OpenLens

But it cannot install extensions

**To Reproduce**
1. Go to extensions view
2. Paste this `@alebcay/openlens-node-pod-menu`
3. Click install
4. Installs forever

**Expected behavior**
Should finish install and add features from plugin

**Screenshots**

<img width="1058" alt="image" src="https://github.com/lensapp/lens/assets/738484/08f12f2d-510d-4614-85b5-8e3f2a57f179">

**Environment (please complete the following information):**
- Lens Version: v6.5.2-366 Latest
- OS: Windows 11
- Installation method (e.g. snap or AppImage in Linux): MSI and EXE package from https://github.com/MuhammedKalkan/OpenLens/releases

**Comment by msa0311** [comment]
Thanks for reaching out. However, it appears that the issue you're experiencing is related to OpenLens, which is a separate project and not maintained by our team. Our repository is dedicated to Lens Desktop product.

For issues specific to Lens, we encourage you to check out our latest release [here](https://github.com/lensapp/lens/releases/tag/v2024.1.300751-latest). If your issue persists with the official version of Lens, please let us know, and we'll be more than happy to assist.
