### ISSUE TITLE
No color differences among pods status after upgrading to 2024.1.170738-latest.

### ISSUE THREAD

**Issue by SgtDaJim** [lensapp/lens#8004]
**Describe the bug**
No color differences among pods status after upgrading to 2024.1.170738-latest.

**To Reproduce**
Open `Pods` panel.

**Expected behavior**
Distinguish different status of pods by color. Just like last version.

<img width="131" alt="image" src="https://github.com/lensapp/lens/assets/10288044/1e706ae3-0632-45e7-8f63-df89add53b26">

**Environment (please complete the following information):**
Lens: 2024.1.170738-latest
Extension API: 6.10.30
Electron: 25.8.3
Chrome: 114.0.5735.289
Node: 18.15.0
MacOS: 14.0 (23A344)

**Comment by ImmarKarimm** [comment]
yes please, being it backkkkkk. lets hope this is not an intentional change :)

**Comment by Albert-Coding** [comment]
This!  This right here!

**Comment by msa0311** [comment]
yes, thanks for reporting! Will be fixed soon!

**Comment by msa0311** [comment]
Fixed with latest release: https://github.com/lensapp/lens/releases/tag/v2024.1.300751-latest
