### ISSUE TITLE
many function icon disappear in mac

### ISSUE THREAD

**Issue by taoyang987** [lensapp/lens#8006]
today afternoon ,i found many function icon disappear.like pods  deploy in workloads or service in network
![WX20240123-213224@2x](https://github.com/lensapp/lens/assets/872386/73c29262-d7ba-4c44-81b2-9d80c9a5df4a)
i create a new account in my macbook(intel 14.2.1),then it works fine.
i've checked the cluster works fine.
i uninstall lens with many ways including uninstall witch third software and  delete files that i found by sudo find / -name "*lens*"
it still does  not work.
i tried Lens-2024.1.170738-latest Lens-2023.12.80831-latest Lens-2023.12.281947-latest
all the version failed
Pls help .waiting for your reply

the latest openlens also does not work

here is the log
[bad2.log](https://github.com/lensapp/lens/files/14032977/bad2.log)
i guess the error log is here.but i don't understand
![WX20240124-123622@2x](https://github.com/lensapp/lens/assets/872386/72eb751b-cdc3-4a99-a512-4da93a00f062)
 this is my export log
[Uploading lens-logs-1706155263137.zip…]()

**Comment by taoyang987** [comment]
command pallete 
view XXX stills not appear

**Comment by taoyang987** [comment]
i have i lens id.but when I logged in Lens Forums,it tips:
Login Error
There is a problem with your account. Please contact the site's administrator.
so i cant' ask for help in Lens Forums

**Comment by kgallardo97** [comment]
@taoyang987 same problem

**Comment by taoyang987** [comment]
finally i solve the issue. because i use my proxy in my terminal. export https_proxy=http://10.1.7.55:7890 http_proxy=http://10.1.7.55:7890 all_proxy=socks5://10.1.7.55:7890
i cancel the proxy in termail reinstall lens ,it works fine now
