### ISSUE TITLE
Lens stops updating pod listing with real time data for all clusters except the most recently connected

### ISSUE THREAD

**Issue by carn1x** [lensapp/lens#8007]
**Describe the bug**
Pod listings and list details stop updating for a connected cluster after opening a connection to another cluster in Lens. Performing actions on the listed pods also shows no change, for example, if I Evict a pod normally it will immediately change to `Terminating` state. In a cluster which was not the most recently connected cluster, if I Evict a pod, the status continues to state `Running`. I need to reconnect to the cluster to observe the updates.

**This behaviour only started roughly within the last week or so.**

**To Reproduce**
1. Connect to a cluster
2. Connect to 2nd cluster
3. Observe that listed pods or details such as pod CPU/RAM never update when going back to the 1st connected cluster, but continue to update in the 2nd connected cluster.
4. Disconnect/reconnect to the first cluster to fix this, but observe now that the 2nd cluster is instead no longer updating.

**Expected behavior**
All pods listings should continue to update for all connected clusters, not just the most recently connected cluster.

**Environment (please complete the following information):**
- Lens Version: 2024.1.170738-latest
- OS: Ubuntu 22.04
- Installation method (e.g. snap or AppImage in Linux): AppImage

**Logs:**
In a scenario such as the following where the `staging` cluster is bugged and not updating, whilst `develop` is not bugged, both appear to be outputting similar logs as I switch between viewing each in Lens:
```
info:    ┏ [CLUSTER]: refresh +21s
info:    ┃ [1] {
info:    ┃ [2]   id: 'eb3c852577cef3c61182448eb714ccad',
info:    ┃ [3]   name: 'develop',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
info:    ┏ [CLUSTER]: refresh +9s
info:    ┃ [1] {
info:    ┃ [2]   id: 'd28a0b7e0f264652b5cb1db4e9462d5a',
info:    ┃ [3]   name: 'staging',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
info:    ┏ [CLUSTER]: refresh +21s
info:    ┃ [1] {
info:    ┃ [2]   id: 'eb3c852577cef3c61182448eb714ccad',
info:    ┃ [3]   name: 'develop',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
info:    ┏ [CLUSTER]: refresh +9s
info:    ┃ [1] {
info:    ┃ [2]   id: 'd28a0b7e0f264652b5cb1db4e9462d5a',
info:    ┃ [3]   name: 'staging',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
```

**Comment by d-afanasiev** [comment]
I have the same problem.

**Comment by msa0311** [comment]
Thanks for reporting this! We are able to reproduce and now looking into it!

**Comment by jakolehm** [comment]
A fix should be included in the upcoming release.

**Comment by msa0311** [comment]
Fixed with latest release: https://github.com/lensapp/lens/releases/tag/v2024.1.300751-latest
