### ISSUE TITLE
Get Cannot read property 'kc' of undefined when adding a vanilla kubeadm cluster config

### ISSUE THREAD

**Issue by kalbinsson** [lensapp/lens#801]
**Describe the bug**
Installed a fresh copy of Lens 3.5.3 on OSX.
Installed afresh vanilla kubernetes  1.18.1 cluster with kubeadm on google cloud
I copy the kube config file.
I can manually connect to the cluster from my OSX system with kubectl using the provided kube config.
When copy and pasting the exact same kube config into Lens 3.5.3 I get the following error message:

Cannot read property 'kc' of undefined

**Comment by nevalla** [comment]
Did you try `3.6.0` beta before installing `3.5.3`? I've seen similar error if doing so

**Comment by kalbinsson** [comment]
Oops. I actually did.

**Comment by nevalla** [comment]
Okay... 3.6.0 changed the format of cluster configuration and 3.5.x is not able to use that properly. If you want to use 3.5.3, workaround to remove `~/Library/Application Support/Lens/lens-cluster-store.json` file and restart the app and re-add the cluster.
