### ISSUE TITLE
support to setup image for node-shell container

### ISSUE THREAD

**Issue by lucming** [lensapp/lens#8010]
**What would you like to be added**:
I hopes that image of node-shell container can be setted by user

**Why is this needed**:
Unable to access the official image registry in some internal scenarios

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: <the OS Lens app runs on in your case>

**Comment by sonnyhcl** [comment]
![image](https://github.com/lensapp/lens/assets/10840522/fc4a385f-2c3a-41b1-9ef2-1cc5937de230)
It's already there
