### ISSUE TITLE
Cannot login to MacOs app

### ISSUE THREAD

**Issue by raj-saxena** [lensapp/lens#8023]
**Describe the bug**
Hi, I have an active Lens Pro subscription from my company. When I try to login with Google SSO, it continuously shows `Login Error, please try again later!` popup and keeps redirecting me between the app and the browser. 

Upon inspection in the console, I saw that there's an error `Failed to refresh token Error: Refresh token missing.`. 
<img width="1204" alt="image" src="https://github.com/lensapp/lens/assets/6253803/2edd3d4f-ad10-45c3-bfcc-b210fd3e43f1">
I have tried re-installing the app and cleaning up local storage/cookies on both app and web, but nothing helps.
How can I continue to use the app?

**To Reproduce**
1. Open app
2. Select `Already have an Lens ID` -> Click `Get Started!`
3. See error

**Expected behavior**
Should login successfully

**Environment (please complete the following information):**
- Lens Version: Lens: 2024.1.300751-latest
- OS: [e.g. OSX] MacOS M2
- Installation method (e.g. snap or AppImage in Linux): Installer from https://app.k8slens.dev/

**Additional context**
Doesn't happen for other colleagues

**Comment by panuhorsmalahti** [comment]
Can you check your Keychain Access and see if there are any expired certificates?

**Comment by raj-saxena** [comment]
All my certificates are valid till a future date

[image: image.png]
[image: image.png]
____________________________
Thanks and regards,
Raj

**Comment by panuhorsmalahti** [comment]
Hello, we've released `2024.3.61137-alpha` which is available in the Alpha update channel (which can be set in Lens -> Settings -> App -> Update Channel). Could you try if this resolves your issue?

**Comment by raj-saxena** [comment]
Hey,

The alpha build seems to be working fine and allows me to log in
successfully. What was the issue?

____________________________
Thanks and regards,
Raj

**Comment by panuhorsmalahti** [comment]
The alpha has a fix which excludes expired certificates from being injected from the system. I noticed that even on my system on Mac there was a few expired certificates (even though I didn't see them in the Keychain UI).

Thanks for testing the alpha. We will release it as the stable version soon.
