### ISSUE TITLE
Add pod limits show to lens

### ISSUE THREAD

**Issue by emoxam** [lensapp/lens#8030]
**What would you like to be added**:

Add pod limits show to lens

**Why is this needed**:

We need to use ssh to see it

**Environment you are Lens application on:**

- Kubernetes distribution: selfhosted
- Desktop OS: Windows 11

Thanks

P.S. I mean these

   Limits:
      cpu:     500m
      memory:  512Mi
    Requests:
      cpu:      100m
      memory:   128Mi

**Comment by tracetechnical** [comment]
These already show in the pod properties tab

**Comment by emoxam** [comment]
@tracetechnical Can you provide a screenshot and version of the app ?

**Comment by tracetechnical** [comment]
CPU:
![image](https://github.com/lensapp/lens/assets/22156780/785397a5-83d0-45f9-913b-f5bb1606fb55)

Memory:
![image](https://github.com/lensapp/lens/assets/22156780/7cf464ab-c5a6-41dd-851a-95a69d4d8526)

2024.1.300751-latest

**Comment by tracetechnical** [comment]
![image](https://github.com/lensapp/lens/assets/22156780/6803066c-8a42-48eb-b210-94dcf389ca8e)
Values shown in tooltip

**Comment by emoxam** [comment]
@tracetechnical I don't have any graphics..
![image](https://github.com/lensapp/lens/assets/3593601/e5763e13-95b6-4f64-a2c9-f505d1d13467)

**Comment by tracetechnical** [comment]
This looks to me like you have no data at all from the redis container

A few checks:
- Is the lens-metrics package installed and fully running?
- Are all your node exporters running
- Have you tried changing the timerange
- Has your redis pod actually got limits defined?
- Is the redis pod actually fully running and outputting logs?

If the answer to ALL of the above are yes, then your metrics are missing.

I'd try on a few other pods such as the ones in kube-system and see if this is an issue isolated to your redis pod or its namespace.

**Comment by emoxam** [comment]
@tracetechnical can't update lens to turn on bundles solutions, so i've installed kube-prometheus-stack via helm, now all works well, thank you for clarification!

**Comment by tracetechnical** [comment]
@emoxam you are most welcome, happy to help!
