### ISSUE TITLE
Lens 2024 port forwarding broken on Windows

### ISSUE THREAD

**Issue by MostefaKamalLala** [lensapp/lens#8031]
I cannot port forward after testing changing to beta channel and updating to Lens 2024. 

![image](https://github.com/lensapp/lens/assets/56651912/4ade7191-b13a-4076-aa40-a7fb5720a35a)

**Comment by Tixon123** [comment]
Hello MostefaKamalLala,

 Thank you for reporting this bug! I will let the dev team know about it!

Best Regards,
Tikhon Kudinov
Lens Support Engineer
Mirantis, Inc

**Comment by msa0311** [comment]
Thanks for reporting this, we are tracking this already on our Known Issues list here: https://forums.k8slens.dev/t/read-first-lens-2024-early-access-version-known-issues/2999
