### ISSUE TITLE
App Crash when opening details on Knative Service

### ISSUE THREAD

**Issue by wSedlacek** [lensapp/lens#8032]
**Describe the bug**
On the beta channel when opening a Knative service an app crash occurs saying `service.getClusterIps is not a function`

**To Reproduce**
Have a Knative Service CRD and click on it to try to open the details.

**Expected behavior**
The details panel would show up on the right side with details about the Service

**Screenshots**
![Screenshot 2024-03-20 at 09 40 58](https://github.com/lensapp/lens/assets/8206108/39442bb9-223d-4020-8e10-7f7fa6dee041)

**Environment (please complete the following information):**
- Lens Version: 2024.3.191601-beta
- OS: macOS 14.1.2

**Additional context**
I suspect there is some code that just looks for `kind === “Service”` when it should also be checking the `apiVersion` to make sure it is `v1`

**Comment by jweak** [comment]
Thanks for the report, you were right about the API version! This is fixed now and will be released in a future beta soon.

**Comment by wSedlacek** [comment]
Thank you very much! Loving the new update!
