### ISSUE TITLE
Text is vertical in details menu of pods, hosts and others.

### ISSUE THREAD

**Issue by iqfx** [lensapp/lens#8035]
**Describe the bug**
Text is vertical on the pod details menu, and various other context menu's. Fairly certain they have the same root cause.

**To Reproduce**
1. Go to 'Workloads'
2. Click on 'Pods'
3. Click on 'any pod'
4. See vertical text in details menu

**Expected behavior**
The text is horizontal en thus readable.

**Screenshots**
![Screenshot 2024-04-15 at 14 02 56](https://github.com/lensapp/lens/assets/39005172/933f2080-f2a1-4160-a61a-3df7a80fb3eb)

**Environment (please complete the following information):**
- Lens Version: Lens: 2024.3.271133-latest
- OS: Macos
- Installation method: directly from website.

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
N/A.
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
N/A.
```

**Additional context**
pls fix ;-;

**Comment by clrothmann** [comment]
Thank you for your feedback. This occurs when the details panel is quite narrow. We have already fixed this issue, and it will be available in one of the upcoming releases.
