### ISSUE TITLE
Run on terminal but not from the launcher

### ISSUE THREAD

**Issue by p4pupro** [lensapp/lens#8066]
**Describe the bug**
I install Lens after having aws and kubectl configured and working fine.
Open Applications and click on Lens app to open or use finder search.
Try to connect a cluster add by kubeconfig and see error.

Expected behavior
The application should work fine from the launcher but it does not

Screenshots
Opened from the launcher
![image](https://github.com/lensapp/lens/assets/12470553/1f76a935-d05c-43ec-86de-0bbb72ee0427)

Opened from terminal through /Applications/Lens.app/Contents/MacOS/Lens
![image](https://github.com/lensapp/lens/assets/12470553/e0605b1c-d849-4a92-9f17-bad7d609f6f0)

Environment (please complete the following information):

Lens Version: 2024.5.271333-latest
Extension API: 6.10.37
Electron: 27.3.11
Chrome: 118.0.5993.159
Node: 18.17.1
© 2023 Mirantis, Inc.
Chip: ARM, Macbook Pro M1 2021
OS: MacOS Sonoma 14.5 (23F79)
Installation method: .dmg
Logs:
When you run the application executable from command line you will see some logging output. Please paste them here:
Unable to parse config file: /Users/XXX/.aws/config
E0703 08:05:12.639441 842387 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable aws failed with exit code 255

Failed to get /version for clusterId=: Internal Server Error
Kubeconfig:

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    server: 
  name: 
contexts:
- context:
    cluster: 
    user: 
  name: 
current-context: 
kind: Config
preferences: {}
users:
- name: 
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - 
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: test

**Comment by Nokel81** [comment]
> I install Lens after having aws and kubectl configured and working fine.

How have you configured `aws` on your terminal? Do you use the `zsh` or `bash` or something else? Is the setup configured within a `rc` or `profile` file?

**Comment by p4pupro** [comment]
Hi @Nokel81 I am using `zsh` with  `zshrc`, but I found the problem and its was solved. 
wrong encoding in `.aws/config` file, the whitespace have no the correct encoding... 
Sorry about that I will close the issue.
Thank you for you time!
