### ISSUE TITLE
Limits and requests are not properly shown if multiple kube-state-metrics pods present in the cluster

### ISSUE THREAD

**Issue by renaudhager** [lensapp/lens#807]
**Describe the bug**
It seems that Lens does not display properly Limits and Requests configured for at least deployment.

**To Reproduce**
- Click on a deployment 
- Check the Limits and Requests display by Lens
- Take the deployment and edit it with Lens to see the actual values

**Expected behavior**
They should be the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/12563305/92265234-28e99f00-eed7-11ea-9797-8b03390b617f.png)

**Environment (please complete the following information):**
- Lens Version: 3.5.3
- OS: OSX
- Installation method: dmg

**Comment by Nokel81** [comment]
After investigation it seems like the numbers displayed seem to correspond to `"defined values" x "# of replicas"`. The value that is displayed is retrieved from kubernetes api (`/api/metrics?...`) and not from the deployment yml. @nevalla or @jakolehm any ideas? I think that both pieces of information could be useful. Should it be clearer where that information is coming from?

**Comment by renaudhager** [comment]
Thank you for looking at this.
I don't observe what you describe. For instance here it's a deployment with a replica 1. 
Here the CPU is 400m when 200m is configured in the manifest.

![image](https://user-images.githubusercontent.com/12563305/94042433-7b75f700-fdc3-11ea-9319-bc2240db19b9.png)

**Comment by aleksfront** [comment]
@renaudhager Do you have `limits` or `requests` set for any other containers? My guess is: values fetched from api accumulates metrics from all of the containers. Checked with my deployments (1 Pod and 1 Container) and displayed data is equal.

In editor you have `200m` set for CPU requests, but got `400m` (which is double number) from metrics. Please check if any other container described in yaml.

**Comment by nevalla** [comment]
Is it possible that there are multiple `kube-state-metrics` components running in the cluster?

**Comment by nevalla** [comment]
I think we should show requests and limits only if a pod has only one container, a deployment has only one pod with only one container etc. Otherwise showing limits and requests in graph does not make any sense.

**Comment by renaudhager** [comment]
Hi guys,

> @renaudhager Do you have `limits` or `requests` set for any other containers? My guess is: values fetched from api accumulates metrics from all of the containers. Checked with my deployments (1 Pod and 1 Container) and displayed data is equal.
> 
> In editor you have `200m` set for CPU requests, but got `400m` (which is double number) from metrics. Please check if any other container described in yaml.

There is no other container for this deployment.

> Is it possible that there are multiple `kube-state-metrics` components running in the cluster?

It's actually the case yes. I have one deployed as part of my EKS deployment and it looks like when I deployed prometheus using Lens it deployed another one.

![image](https://user-images.githubusercontent.com/12563305/94795197-f26b4b00-03d4-11eb-8f51-51aa311d6e70.png)

**Comment by renaudhager** [comment]
I have scaled to 0 the kube-state-metrics deployment in Lens namespace.
It seems to have fixed the issue:

![image](https://user-images.githubusercontent.com/12563305/94797107-935b0580-03d7-11eb-895b-12d78e55cf11.png)

**Comment by stevejr** [comment]
I tried recreating this issue with the latest release of Lens on my local minikube cluster and did not see the issue.

@renaudhager - could you please confirm if you still see the issue with the latest Lens release?

**Comment by renaudhager** [comment]
Hi,

Sorry for the late reply.

Yes I still have it. But this is related to the fact that I have already a kube-state-metrics deployment, so when I deploy prometheus stack from Lens, I got all k8s metrics in double. When I set 0 to the Lens kube-state-metrics deployment I don't have the issue.

My understanding is just that Prometheus scrap the metrics from deployment.

**Comment by HristoA** [comment]
Hi,
I will like to add few more related problems. On Rancher 2.5.2, Prometheus app installed via Cluster Explorer APP store (Helm chart), Linux, Snapcraft, Lens 4.0.6

**Missing:**

- [Nodes] Master nodes CPU/Memory/Disk statistics  (for worker nodes all is there)
- [Nodes] Worker CPU statistic rounding missing (show something like : 12.23445435435435346%)
- [Cluster]  In Cluster page Master/Worker buttons not work at all

Thanks

**Comment by jakolehm** [comment]
Closing because #1867 should fix the original issue.
