### ISSUE TITLE
Cluster View Documentation has Mistake

### ISSUE THREAD

**Issue by mukunku** [lensapp/lens#8091]
**Describe the bug**
The webpage: https://docs.k8slens.dev/using-lens/cluster/ has the CPU and Memory descriptions swapped:
![image](https://github.com/user-attachments/assets/371667e8-b88e-44ec-92e4-1336842adb7c)

**Comment by Tixon123** [comment]
Hello mukunku,

 Thank you for reporting!

 I will let the dev team regarding this mistake. 

Best Regards,
Tikhon Kudinov
Lens Support Engineer
Mirantis, Inc

**Comment by clrothmann** [comment]
Nice catch @mukunku!
Thanks for reporting. I have already addressed it to the appropriate team.
