### ISSUE TITLE
OpenLens 6.5.2-366: Metrics are not displayed using metrics-server

### ISSUE THREAD

**Issue by thorstenhilker** [lensapp/lens#8095]
**Describe the bug**
Metrics like cluster cpu usage, node cpu usage or pod cpu usage are not being displayed.
The message "Metrics are not available due to missing or invalid Prometheus configuration" is shown instead.

**To Reproduce**
1. Go to Cluster
2. No metrics are displayed
3. Go to Nodes
4. No metrics are displayed
5. Go to Pods
6. Click on a Pod
7. No metrics are displayed

**Expected behavior**
The metrics should be displayed for the relevant components

**Environment (please complete the following information):**
- Lens Version: OpenLens: 6.5.2-366
- OS: macOs
- Installation method (e.g. snap or AppImage in Linux): homebrew

**Kubeconfig:**
There is no Prometheus stack on the cluster running.
Instead the metrics-server is installed.

**Additional context**
On the commercial Lens Version 2024.9.300059-latest the metrics are being displayed correctly.
In the metrics settings of the node this message is being shown:
"Currently used metrics source: Kubernetes Metrics Server"
In the metrics settings of OpenLens the following message is being shown:
"What query format is used to fetch metrics from Prometheus"

Is it possible to use OpenLens with the metrics-server?

**Comment by Christiaanvdl** [comment]
Hello thank you for reaching out we have contacted our development team about your issue .

**Comment by Christiaanvdl** [comment]
Hello It is not possible no  you should use the official Lens version

**Comment by Christiaanvdl** [comment]
Please note that OpenLens is not actively supported anymore and all raised issues are generally addressed in the official Lens. The recommendation is if possible to purchase the latest available version of Lens from https://k8slens.dev/ as more likely the issue have been solved there . 

Kind regards

**Comment by joshsten** [comment]
There is a 3rd party port here: https://github.com/shilazi/openlens-lens-metrics

The are community forked versions: https://github.com/MuhammedKalkan/OpenLens
The community fork that seems to have taken off more recently is at https://github.com/freelensapp/freelens. It's got a number of community sponsors and an enthusiastic base. 

(Use/validate at own risk)
