### ISSUE TITLE
Cannot see pods, deployments, etc after installing Lens 2024.9.30059-latest on Windows

### ISSUE THREAD

**Issue by iceaxe** [lensapp/lens#8096]
**Description**
I just installed Lens v2024.9.30059-latest on Windows. I'm able to see some components in my AWS K8S clusters but not all.  I can see Nodes, Namespaces (the list only), and custom resources and 1 or 2o others, but I cannot see Pods, Secrets (other than 1 for the default namespace -- I have a couple dozen namespaces), daemon sets, deployments, etc.

I confirmed that I have kubectl installed and in my system PATH.

**Steps to Reproduce**
1. Run 'Lens Setup 2024.9.300059-latest.exe' installer
2. Install AWS client
3. Copied .aws/config and .../credentials and .kube/config from a working WSL instance to my home directory in Windows
4. Successfully logged into AWS in Windows PowerShell using 'aws sso login --profile <K8S_CLUSTER>'
5. Could browse some K8S components in Lens but get 'Item list is empty' for pods, deployments, daemon sets, etc, all of which I can see in VS Code with the K8s plugin in my WSL instance using the same AWS credentials.

**Expected behavior**
I expect to see all of the K8S components in Lens on Windows that I can see in VS Code in WSL.

**Screenshots**
![image](https://github.com/user-attachments/assets/b8beed05-e543-4644-bba7-080d777af64d)

**Environment (please complete the following information):**
- Lens Version:  2024.9.30059-latest
- OS: Windows 11
- Installation method (e.g. snap or AppImage in Linux): Windows installer, 'Lens Setup 2024.9.300059-latest.exe'

**Comment by Christiaanvdl** [comment]
Only Thank you for reaching out ! I have contacted our development team about your issue .

**Comment by panuhorsmalahti** [comment]
What namespace(s) are selected?

**Comment by iceaxe** [comment]
> What namespace(s) are selected?

That was my issue, thanks.  I had several namespaces selected in the Namespaces tab but didn't notice that they didn't translate to the Pods (and other) tabs, and that there's a Namespace dropdown in each of the other tabs as well.  I can see pods now as expected when selecting namespaces from the dropdown in that tab.
