### ISSUE TITLE
sort node info for humans

### ISSUE THREAD

**Issue by matti** [lensapp/lens#81]
currently node info is straight outta api

propsal for betterments:
<img width="910" alt="Lens" src="https://user-images.githubusercontent.com/3893/69011658-a9a1d380-0975-11ea-92db-36ad5c9ca909.png">

**Comment by matti** [comment]
loving it how an issue is just closed

**Comment by aleksfront** [comment]
Yes, this proposal issue is implemented.

**Comment by ixrock** [comment]
@aleksfront yep, probably we should _not_ put auto-closing github tags from _private_ to _public_ repos..

**Comment by aleksfront** [comment]
Agreed.
