### ISSUE TITLE
[Question] OpenLens 6.5.2-366: Deploy a Pod, Deployment, etc.

### ISSUE THREAD

**Issue by thorstenhilker** [lensapp/lens#8100]
Hi!

Short question:
Is it possible to deploy Pods, Nods, ReplicaSets, etc. from OpenLens?
With the commercial version of Lens it works.
In OpenLens the "plus-buttons" are missing.

Thanks!

**Comment by clrothmann** [comment]
Hello @thorstenhilker,

Thank you for your question!

OpenLens is no longer actively supported, and any issues or missing features are typically addressed in the official version of Lens. If possible, we recommend switching to the latest version of Lens from [https://k8slens.dev](https://k8slens.dev/), as most issues are likely to have been resolved there.

BR
