### ISSUE TITLE
Login Error, please try again later!

### ISSUE THREAD

**Issue by 1saeedsalehi** [lensapp/lens#8108]
**Describe the bug**
I'm trying to log into the freshly installed Lens Desktop. I've already logged in with Google on my default browser, but after clicking "Already have a Lens ID," it keeps opening new browser tabs for login. Even though logged in, I kept getting the error message: "Login Error, please try again later!"

**To Reproduce**
1. Install the latest version Lens: 2024.9.300059-latest
3. Click on "Already have a Lens ID" on the login screen
4. login using Google
5. Click on the confirmation button to go back to Lens Desktop
6. See error

**Expected behavior**
Login works 

**Screenshots**
<img width="1079" alt="Screenshot 2024-10-14 at 17 03 41" src="https://github.com/user-attachments/assets/319614b4-b41c-4fd2-b2e6-750f1e5855b0">

**Environment (please complete the following information):**
- Lens Version:
- OS: 14.3.1 (23D60)
- Installation method (e.g. snap or AppImage in Linux): Download from the website

**Comment by clrothmann** [comment]
Hello @1saeedsalehi and thank you very much for your report. To rule out the possibility that you tried to log in during our maintenance work, which may have caused our backends to be temporarily unavailable, could you let us know if the problem still persists? 
We look forward to your response.

**Comment by 1saeedsalehi** [comment]
thank you for your response, It's still happening,  the login page is frozen during the login, and there is no redirect happening here is a short screen recording:

https://github.com/user-attachments/assets/915dc829-7213-4642-b9dd-479055444118

**Comment by clrothmann** [comment]
This is not the best time at the moment, as we are currently performing maintenance. You can track the status here: https://status.k8slens.dev/  I kindly ask you to be patient and try again afterwards. Sorry for the inconvenience.

**Comment by pimmpo** [comment]
Hi an update on this issue? I checked k8slens statuses and it have look okay, but I have same issue. :broken_heart:

**Comment by Ahmed-Elgohary1** [comment]
I have the same problem; I haven't been able to log in for the past five hours.

**Comment by pimmpo** [comment]
@1saeedsalehi @Ahmed-Elgohary1 UPDATE: I'm logged in Lens successfully.

**Comment by 1saeedsalehi** [comment]
I still have have the problem :(

**Comment by dechegaray** [comment]
> I still have have the problem :(

By any chance are you behind a proxy/firewall with some restrictions? we have seen this error typically in users with network restrictions in their companies. Sometimes those proxies are rewriting the requests with their self-signed corporate cert, and the auth process cannot be validated. This can be checked in Lens' logs (`Help -> Export Support Logs`) and looking for errors as `[LENS-SPACES-EXTENSION]: (from:AuthHandler) 10/8/2024, 4:50:21 PM {{some error}}`. You can also try executing a curl request to our auth API to see if you can reach it.

```
// From MacOS
curl -X POST https://app.k8slens.dev/auth/realms/lensCloud/protocol/openid-connect/token -H "Content-Type: application/json" -d '{}'
// You should obtain something like
{"error":"invalid_request","error_description":"Missing form parameter: grant_type"}
```

If you cannot reach it, some whitelisting might need to be done in your company

**Comment by 1saeedsalehi** [comment]
@dechegaray thank you for your point
I got the response from connect/token endpoint `{"error":"invalid_request","error_description":"Missing form parameter: grant_type"}` so there is no need for whitelisting 

[lens-logs-1729068448759.zip](https://github.com/user-attachments/files/17392278/lens-logs-1729068448759.zip)

**Comment by dechegaray** [comment]
> @dechegaray thank you for your point I got the response from connect/token endpoint `{"error":"invalid_request","error_description":"Missing form parameter: grant_type"}` so there is no need for whitelisting
> 
> [lens-logs-1729068448759.zip](https://github.com/user-attachments/files/17392278/lens-logs-1729068448759.zip)

Based on the logs, your Lens got caught in a state in which your user session is no longer valid, and it cannot refresh the auth token because our API status endpoint keeps timing out, as if the API was down (probably it happened during our maintenance window and somehow it got cached)

Can you run the following `curl https://api.k8slens.dev/status`  from your terminal? it should return `{}`, just to verify that that address is also reachable to you?

If you can reach it indeed, I will suggest:

- Uninstalling Lens
- Deleting the folder `/Users/USERNAME/Library/Application Support/Lens/`(assuming you are on Mac)
- Reinstalling `Lens: 2024.9.300059-latest`

The cleanup of the folder might help resetting everything so older tokens/cache, etc get cleaned up and this becomes a fresh new session

**Comment by 1saeedsalehi** [comment]
Thank you for your comment, @dechegaray 
The URL `https://api.k8slens.dev/status` is reachable from my terminal.

I also uninstalled the app and removed the application support folder. 
After reinstalling the latest version` Lens-2024.9.300059-latest-arm64`,  I got the same error. Here are the logs.

[lens-logs-1729162574881.zip](https://github.com/user-attachments/files/17411116/lens-logs-1729162574881.zip)

**Comment by 1saeedsalehi** [comment]
Can anyone help me with this? I still have the problem

**Comment by clrothmann** [comment]
@panuhorsmalahti Can you please take a look! Thx

**Comment by panuhorsmalahti** [comment]
The logs have error `certificate signature failure`. Are you perhaps using some kind of enterprise software that rewrites the certificates? Lens doesn't accept the certificate so the login process doesn't work. Lens should read system certs from the OS stores but there might be some issue with that.

**Comment by 1saeedsalehi** [comment]
Yes, that was it. Thank you so much for your help in solving the problem. Now it's up and working again!

**Comment by anho85** [comment]
@1saeedsalehi what was your solution? I have the same problem but the last 2 messages in that thread does not show me how to solve it.

**Comment by 1saeedsalehi** [comment]
@anho85  I found that the security software installed on my machine was rewriting the certificates. I asked the network admin to add a rule to exclude the K8sLens certificates. Once that was in place, the OS was able to read the correct certificates, which resolved the issue for me.
