### ISSUE TITLE
No matching route for the current path. This is a bug.

### ISSUE THREAD

**Issue by pimjansen** [lensapp/lens#8115]
**Describe the bug**
When opening Lens i received this error:
```
No matching route for the current path: /extension/lensapp--lenscloud-lens-extension/welcomepage which is the welcomeUrl. This is a bug.
```

**To Reproduce**
1. Open Lens app with Ubuntu 24.04
2. See error
3. Hotbar is not available at this point and all is greyed out

**Expected behavior**
Open lens as expected

**Screenshots**
![image](https://github.com/user-attachments/assets/00fc3cff-ac05-4fe0-b352-c5c5bddc938e)

**Environment (please complete the following information):**
![image](https://github.com/user-attachments/assets/7c864b30-9b00-4da8-b004-34271e5ed36f)
Installed via Snap

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
n/a
```

**Comment by clrothmann** [comment]
Hello @pimjansen, 
Thank you for reporting this issue! It looks like your version is not the latest—please try installing a newer version. The version on the Snap Store is not up-to-date, but we are currently working on it. Here is a link to the latest beta version:
https://forums.k8slens.dev/t/early-access-for-linux-users/3241

**Comment by pimjansen** [comment]
That is weird indeed since snap reported latest.

I reinstalled the app and fully purged all Lens info and now it is back. It was also really slow before (needed minutes to start and also that is gone)
