### ISSUE TITLE
I cannot connect  to  node

### ISSUE THREAD

**Issue by mortazakiani** [lensapp/lens#8121]
**Describe the bug**
I cannot connect  to  node  even  I  put alpine  image in private  repository 

**To Reproduce**
1. Go to 'nodes'
2. Click on 'node  shell '
3. and its  remain in  connecting 

**Expected behavior**
it's should connect to  node

**Environment (please complete the following information):**
kubenetes version 1.30.3

**Logs:**
Error occurred: Pod creation timed outfailed to open a node shell: failed to create node pod

**Kubeconfig:**
 its connect  with previous version

**Comment by dechegaray** [comment]
> **Describe the bug** I cannot connect to node even I put alpine image in private repository
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'nodes'
> 2. Click on 'node  shell '
> 3. and its  remain in  connecting
> 
> **Expected behavior** it's should connect to node
> 
> **Environment (please complete the following information):** kubenetes version 1.30.3
> 
> **Logs:** Error occurred: Pod creation timed outfailed to open a node shell: failed to create node pod
> 
> **Kubeconfig:** its connect with previous version

May we know what version of Lens are you currently on?

**Comment by mortazakiani** [comment]
> > **Describe the bug** I cannot connect to node even I put alpine image in private repository
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Go to 'nodes'
> > 2. Click on 'node  shell '
> > 3. and its  remain in  connecting
> > 
> > **Expected behavior** it's should connect to node
> > **Environment (please complete the following information):** kubenetes version 1.30.3
> > **Logs:** Error occurred: Pod creation timed outfailed to open a node shell: failed to create node pod
> > **Kubeconfig:** its connect with previous version
> 
> May we know what version of Lens are you currently on?

2024.11.131815-latest

**Comment by dechegaray** [comment]
> > > **Describe the bug** I cannot connect to node even I put alpine image in private repository
> > > **To Reproduce** Steps to reproduce the behavior:
> > > 
> > > 1. Go to 'nodes'
> > > 2. Click on 'node  shell '
> > > 3. and its  remain in  connecting
> > > 
> > > **Expected behavior** it's should connect to node
> > > **Environment (please complete the following information):** kubenetes version 1.30.3
> > > **Logs:** Error occurred: Pod creation timed outfailed to open a node shell: failed to create node pod
> > > **Kubeconfig:** its connect with previous version
> > 
> > 
> > May we know what version of Lens are you currently on?
> 
> 2024.11.131815-latest

By any chance are you using Tailscale, HAProxy, or a similar service in front of your Kube API? The reason I ask is because there is a known problem were are working on related to this. Users with such configs cannot shell into nodes/pods due to an incompatibility with an internal proxy we have in Lens, so would like to narrow down if it is the same problem in your case, or something else, maybe related to your Kube version. 

If not related, could you provide some logs after reproducing the issue?

**Comment by mortazakiani** [comment]
i  can fix this  with exit  the  program  completely  and    close it  in task  manager  and re run again  
i still have this  problem  in  two  cluster  one have  haproxy  and  another one that  have no ha proxy

**Comment by dechegaray** [comment]
> i can fix this with exit the program completely and close it in task manager and re run again i still have this problem in two cluster one have haproxy and another one that have no ha proxy

For the cluster with haproxy, our engineering team is already working on it, we should have a patch for it soon. For the others, may I ask you to download kubectl v1.30 and adjust Lens to use that binary? -> https://docs.k8slens.dev/using-lens/preferences/#configure-kubectl, we had a similar case, so would like to know if that helps

**Comment by mortazakiani** [comment]
tnx
