### ISSUE TITLE
CPU RAM not showing when viewing Node

### ISSUE THREAD

**Issue by fatsolko** [lensapp/lens#8122]
**What would you like to be added**:
CPU RAM not showing when viewing node
![image](https://github.com/user-attachments/assets/102aa823-0451-4a05-9784-6c90e4399f39)

**Environment you are Lens application on:**

- Kubernetes distribution: self-hosted
- Desktop OS: Windows 11

**Comment by clrothmann** [comment]
Hello @fatsolko, thanks for reaching out to us. 
This has been already fixed in our beta version `Lens-2024.11.51849-beta` and will be also available in our upcoming stable release.
