### ISSUE TITLE
Unable open a pod's terminal in Windows 10 22H2 19045.5131

### ISSUE THREAD

**Issue by D1987** [lensapp/lens#8138]
I get the error when open pod's terminal:
`failed to open a local shell: Error launching WinPTY agent: winpty-agent CreateProcess failed: cmdline='"\\?\C:\DEV\Lens\resources\app.asar.unpacked\node_modules\node-pty\build\Release\winpty-agent.exe" \\.\pipe\winpty-control-20216-14-1db458cee8d56a5-1338f6ff54617c22c5e21e539fe23a92 0 1 80 30' err=0x4ec`
I tried off Symantec antivirus, run the Lens as admin but I get the same error.

<img width="1496" alt="lens" src="https://github.com/user-attachments/assets/54039e46-18c4-4017-b530-28aaee4ba23c">

**Comment by Christiaanvdl** [comment]
Hello, Thank you for reaching out! 
I will contact our development team regarding your issue.

**Comment by dechegaray** [comment]
By any chance did you upgrade Lens recently @D1987 ? we have seen issues with other Windows users in which some files are missing after the upgrade. The solution is to:

- Uninstall Lens
- Delete the folder `/Users/USERNAME/AppData/Roaming/Lens` or `/Users/USERNAME/AppData/Local/Lens` depending on your installation
- Install Lens fresh

**Comment by D1987** [comment]
Thanks, it works!
