### ISSUE TITLE
Middle mouse button does not close tabs anymore

### ISSUE THREAD

**Issue by morinow** [lensapp/lens#8145]
**Describe the bug**
Middle mouse button does not close tabs anymore.

**To Reproduce**
...

**Expected behavior**
Clicking the middle mouse button should close hovered tabs.

**Environment (please complete the following information):**
- Lens Version: 2024.11.261604-latest
- OS: Windows 11

**Comment by clrothmann** [comment]
Hello @morinow, 
thank you for your feedback! 
We are already aware of this issue and plan to have it fixed in one of the upcoming releases.
