### ISSUE TITLE
ingress is clipped

### ISSUE THREAD

**Issue by matti** [lensapp/lens#82]
2.6.0

<img width="1850" alt="image" src="https://user-images.githubusercontent.com/3893/69011723-42d0ea00-0976-11ea-9e3f-e1993529ffc9.png">

**Comment by jnummelin** [comment]
I was able to reproduce this by having an ingress object without any `rules`. This seems to confuse the list renderer to clip the rows.

**Comment by matti** [comment]
yep, I just had one default backend, no rules
