### ISSUE TITLE
Fails to load on MacOS Mojave

### ISSUE THREAD

**Issue by alexellis** [lensapp/lens#822]
**Describe the bug**

Fails to load on MacOS Mojave, but the README states:

> Download a pre-built package from the releases page. 

**To Reproduce**

```
wget https://github.com/lensapp/lens/releases/download/v3.6.0-rc.1/Lens-3.6.0-rc.1-mac.zip

tar -xvf Lens-3.6.0-rc.1-mac.zip

./Lens.app/Contents/MacOS/Lens
```

<img width="488" alt="Screenshot 2020-09-08 at 09 08 57 1" src="https://user-images.githubusercontent.com/6358735/92450171-00052a80-f1b3-11ea-802d-bf0ed4e79321.png">
<img width="1409" alt="Screenshot 2020-09-08 at 09 08 57" src="https://user-images.githubusercontent.com/6358735/92450180-02678480-f1b3-11ea-8339-f0452ee1e195.png">

```
uname -a
Darwin kosmos.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
```

Perhaps the README is missing some pre-reqs or steps? Or perhaps the MacOS download is invalid for Mojave?

**Comment by jakolehm** [comment]
Did you test `dmg` package?

**Comment by alexellis** [comment]
As per the issue, this is regarding the zip that you distribute in the releases page.

Are some instructions or pre-reqs missing? Have you also seen the format error we (arkade contributors) ran into when trying to make it available as a download option? #821

**Comment by jakolehm** [comment]
@alexellis yes, releases contains a zip file for MacOS but we actually only link a `dmg` package on release notes. Zip is something that is only generated for auto-updater.

**Comment by nevalla** [comment]
I'm closing this since `dmg` file is the correct file to install Lens
