### ISSUE TITLE
How Lens accessing nodes in AKS/EKS without user and SSH key under ROOT?

### ISSUE THREAD

**Issue by KIRY4** [lensapp/lens#824]
**Describe the bug**
I believe that it is a feature, not bug but how Lens accessing nodes in AKS/EKS without user and SSH key under ROOT? Is it safe? Could you please give a reference or explain how it work?

**To Reproduce**
1. Go to 'Nodes'
2. Select one Node
3. Push Node Shell
4. You on Node with root privileges...

**Comment by nevalla** [comment]
Lens will create `nsenter` pod to the selected node https://github.com/lensapp/lens/blob/5670312c474eb5b6d506a3793863707a7df76775/src/main/node-shell-session.ts#L57-L87 and exec into that container in lens terminal.

**Comment by KIRY4** [comment]
> Lens will create `nsenter` pod to the selected node
> 
> https://github.com/lensapp/lens/blob/5670312c474eb5b6d506a3793863707a7df76775/src/main/node-shell-session.ts#L57-L87
> 
> and exec into that container in lens terminal.

Thanks for quick reply! If I correctly understood here is these pods?

k get pods -n kube-system|grep node-shell                                   
node-shell-288052a5-ad4c-4e80-abaf-917b04e9eaec       0/1     Completed   0          14h
node-shell-2b5b220c-138f-4b29-bf80-44184c7d32eb       0/1     Completed   0          13h
node-shell-a5d9c48b-9f9a-4234-bbfc-561a36757b24       1/1     Running     0          115s
node-shell-ed7ac0c2-256f-4c8b-b7a7-f4801ff5bc96       0/1     Completed   0          17h

**Comment by nevalla** [comment]
Yes...they should've been cleaned up though.

**Comment by KIRY4** [comment]
> Yes...they should've been cleaned up though.

Automatically or manually? Because looks like they stay exist with Completed state...

**Comment by nevalla** [comment]
> Automatically or manually? Because looks like they stay exist with Completed state...

Automatically

https://github.com/lensapp/lens/blob/5670312c474eb5b6d506a3793863707a7df76775/src/main/node-shell-session.ts#L50-L55

**Comment by KIRY4** [comment]
Many thanks for explanation!! I have no additional questions!!
