### ISSUE TITLE
Cluster icon doesn't get migrated from 3.5 to 3.6

### ISSUE THREAD

**Issue by jim-docker** [lensapp/lens#825]
**Describe the bug**
A cluster icon that was added in the 3.5 version is not used (default icon is shown) after updating to 3.6

**Comment by jim-docker** [comment]
Also, in 3.6 the icons are kept in the cluster-store so the `icons` folder from 3.5 should probably be removed as part of the migration(?)

**Comment by nevalla** [comment]
Fixed in `master`
