### ISSUE TITLE
Dashboard doesn't refresh after changing workspace

### ISSUE THREAD

**Issue by jim-docker** [lensapp/lens#827]
**Describe the bug**
When changing from one workspace to another the dashboard is "blank" (there is no current cluster shown) 

**To Reproduce**
1. With two workspaces, click on workspace widget (bottom left) and change to the other workspace
2. Observe that the workspace is shown, with no active cluster(even if there was an active cluster when the workspace was last selected)
3. Click on a cluster icon to cause the refresh

**Expected behavior**
When toggling between workspaces the dashboard should show previous snapshot of the workspace
**Screenshots**

![wsRefresh](https://user-images.githubusercontent.com/40840436/92516203-dbc14200-f1e2-11ea-99d0-e483c9135a80.gif)

**Environment (please complete the following information):**
- Lens Version: 3.6.0-rc.1
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): dmg

**Comment by jakolehm** [comment]
I think this is "by design" (3.5 works the same way).
