### ISSUE TITLE
GKE ingress IP not visible in pane

### ISSUE THREAD

**Issue by matti** [lensapp/lens#83]
<img width="1631" alt="Lens" src="https://user-images.githubusercontent.com/3893/69011760-92171a80-0976-11ea-9203-d1c18f038bb8.png">

**Comment by matti** [comment]
if you are lucky enough it's visible in the events for a moment

<img width="933" alt="image" src="https://user-images.githubusercontent.com/3893/69012081-3f3f6200-097a-11ea-8cc6-de5570a0b153.png">

**Comment by jakolehm** [comment]
I think this is not just GKE specific bug. We are probably missing IP on every environment that is configured like GKE.
