### ISSUE TITLE
Can't setup kubeconfig as system kubeconfig has invalid config

### ISSUE THREAD

**Issue by Nokel81** [lensapp/lens#843]
**Describe the bug**
When I go to the "Add New Cluster" page I consistently get a notification saying:
<img width="523" alt="Screen Shot 2020-09-09 at 11 02 58 AM" src="https://user-images.githubusercontent.com/8225332/92616278-087d6400-f28c-11ea-8198-4ca487fc8bf3.png">

And the dropdown for adding new clusters is empty.

**To Reproduce**
1. Have the following entry in your kubeconfig under `contexts:`
```yml
- context:
    cluster: ""
    user: ""
  name: default/foo.kuberbetes.com/kubeuser
```
2. Click on the "Add Cluster" button on the left menu
3. Observe error notification

**Expected behavior**
The invalid contexts are filtered out and ignored.

**Screenshots**
See above

**Environment (please complete the following information):**
- Lens Version: 3.6.0-rc2
- OS: [e.g. OSX] macos
- Installation method (e.g. snap or AppImage in Linux): download
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
error: contexts[0].context.cluster is missing
```

**Comment by nevalla** [comment]
I agree, this is not the most ideal solution we have atm.
