### ISSUE TITLE
Make port-forwarding possible using Lens

### ISSUE THREAD

**Issue by j-ilden** [lensapp/lens#85]
---
name: Feature request
about: Make port-forwarding possible (maybe with a shortcut?)

---

**What would you like to be added**: An option that makes port forwarding possible (kubectl port-forward <service/pod/container>)
Possible flow for the behavior:
1. Navigate to your service/pod/container
2. Click on the "port-forward" Menu button' or shortcut
3. Enter source and destination port
4. Check if it is working

**Why is this needed**:
Being able to expose a port on pods, services or container for troubleshooting/testing is a lifesaver. k9s has this (go to a pod or container and pres ctrl+f and give source/dest and voila). Lens should be able to provide something like that as well. Or maybe just open it up to configure something and then close it back again. It is the way to go on most air-gapped environment.

**Environment you are Lens application on:**

- Kubernetes distribution: On-prem (AKS in the future)
- Desktop OS: Any

**Comment by shinebayar-g** [comment]
I can't find port-forward menu. Where is it? Lens v3.4.0

**Comment by danielsimpson** [comment]
Look at the screenshot and description in #231 @shinebayar-g

**Comment by spyro2000** [comment]
That only works for HTTP resources, not for remote debugging etc. Would be great if one could just specifiy the port

**Comment by hwinkel** [comment]
Yes, general portforward would be good to not just have a browser opening but expose any socket

**Comment by joergplewe** [comment]
Why is the issue closed?

**Comment by JalalSordo** [comment]
this would be a killer feature for java development as you can remote debug any app, please allow custom pod port mapping not service kind only.

**Comment by mberrezak** [comment]
We need this guys :) Please consider it, I will switch to VSCode for now...

**Comment by j-ilden** [comment]
You can do this already since 3.x. Navigate to your service endpoint. Click on the port and it will automatically start a kube-proxy instance followed by a redirect to your browser.

See https://github.com/lensapp/lens/pull/231 for more details.

**Comment by spyro2000** [comment]
It's about other ports, e.g. for debugging.
