### ISSUE TITLE
allow add cluster via selection of kubeconfig file from file-system

### ISSUE THREAD

**Issue by tony-kerz** [lensapp/lens#871]
**What would you like to be added**:

when adding cluster allow selection of kubeconfig file from file system.

**Why is this needed**:

i tend to maintain many kubeconfig files in my ~/.kube folder with different names (as opposed to default filename `config`). in this case, it would be convenient to just select one of those files vs scraping the contents and pasting into the custom text-area field.

**Environment you are Lens application on:**

- Kubernetes distribution:  any
- Desktop OS: osx

**Comment by nevalla** [comment]
Is this something else than `3.6` introduced?

**Comment by tony-kerz** [comment]
@nevalla haha, that's exactly what i was looking for, thanks!

**Comment by DanielHabenicht** [comment]
Did this get removed or hidden in v5?
