### ISSUE TITLE
Helm integration out of sync with cli

### ISSUE THREAD

**Issue by mecostav** [lensapp/lens#872]
**Describe the bug**
When you install a helm release using lens it does not show in the cli. Some of our stuff members are still using helm cli thus it would be nice to have those 2 synced

**To Reproduce**
install any helm chart using lens
run `helm ls` in the terminal and it returns nothing

**Expected behavior**
helm ls should return a list of releases

**Environment (please complete the following information):**
- Lens: 3.6.0
- OS: ubuntu 20.04 lts
- Installation method (e.g. snap or AppImage in Linux): snapd
- Helm version: 2.14.3 / 3.3.1
- tested on: minikube
- kubernetes version: 1.14.9

**Comment by nevalla** [comment]
Lens supports only Helm v3

**Comment by mecostav** [comment]
> Lens supports only Helm v3

is there any plan to support helm 2 in the future by any chance?

**Comment by mecostav** [comment]
Just tested it with Helm 3 and the issue maintains

**Comment by jakolehm** [comment]
> > Lens supports only Helm v3
> 
> is there any plan to support helm 2 in the future by any chance?

No plans, Helm 2 is going to be deprecated soon, see: https://helm.sh/blog/helm-v2-deprecation-timeline/

**Comment by Nokel81** [comment]
Closing favour of #691 since that is also a bug, and we are not planning on supporting helm2.
