### ISSUE TITLE
How do I force a version and stop automatic upgrades?

### ISSUE THREAD

**Issue by jgreat** [lensapp/lens#877]
**Describe the bug**
I'm stuck on issue #873 and would like to revert to 3.5.3 until a fix is available. Can you provide previous versions via alternate snap channel or instructions on how to keep lens from auto updating on me?

- I had lens installed as a snap package and it updated this morning. 
- There doesn't appear to be a 3.5 series snap channel, so I can't revert back :(
- So I switched to the 3.5.3 appimage, and it auto-upgraded me to 3.6.0 (╯°□°)╯︵ ┻━┻

**Environment (please complete the following information):**
- Lens Version: 3.5.3/3.6.0
- OS: Linux - Pop!_OS 20.04 LTS
- Installation method (e.g. snap or AppImage in Linux): Both

**Comment by Nokel81** [comment]
Fixed by #1941
