### ISSUE TITLE
can't open any clusters from kube config exec not found in $PATH

### ISSUE THREAD

**Issue by leepatrick-goop** [lensapp/lens#878]
**Describe the bug**
When I try to open any of the clusters from the app, it can't authenticate saying that either `aws` or `aws-iam-authenticator` is not available in $PATH. However both are in my $PATH:

```
⋊> ~ ls /usr/local/bin/ | grep aws-iam                                                                                       16:20:00
aws-iam-authenticator
⋊> ~ ls /usr/local/bin/ | grep aws                                                                                           16:20:02
aws
aws-iam-authenticator
aws-shell
aws-shell-mkindex
aws-vault
aws_completer
aws_legacy_completer
rawshark
⋊> ~ echo $PATH | grep /usr/local/bin                                                                                        16:20:04
/Users/leepatrick/.fzf/bin /usr/local/bin
⋊> ~ which aws-iam-authenticator                                                                                             16:20:24
/usr/local/bin/aws-iam-authenticator
⋊> ~ which aws                                                                                                               16:21:21
/usr/local/bin/aws
```

**Environment (please complete the following information):**
- Lens Version: 3.6.0
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): brew
 
**Logs:**

```
2020/09/14 15:52:24 http: proxy error: getting credentials: exec: exec: "aws": executable file not found in $PATH

getting credentials: exec: exec: "aws": executable file not found in $PATH
----------------------
2020/09/14 16:15:57 http: proxy error: getting credentials: exec: exec: "aws-iam-authenticator": executable file not found in $PATH

getting credentials: exec: exec: "aws-iam-authenticator": executable file not found in $PATH

```

**Comment by leepatrick-goop** [comment]
I was able to solve this by putting the full path in my kube config as the command, but I still don't understand why it couldn't find it in my $PATH.

**Comment by nevalla** [comment]
Typically this is the issue when some shell init script (`.bash_profile` etc) is modifying PATH. When Lens app is opened from launcher those scripts are not ran. Is this possible your case too?

**Comment by Nokel81** [comment]
Related to #2079

**Comment by Nokel81** [comment]
Is this still an issue?

**Comment by eduardoaw** [comment]
Scenarios for this issue on windows 10:

1 - Install Lens
![image](https://user-images.githubusercontent.com/11036786/152421929-85958e54-1062-44e0-85c9-fadc90cdc65c.png)

2 - Register a new cluster.

3 - Open cluster
3.1 The message will occur: `getting credentials: exec: exec: "aws-iam-authenticator": executable file not found in $PATH`

4 - Install and configure `aws cli`.

5 - Install `aws-iam-authenticator` and configure `PATH` in windows environment variables.
5.1 - `aws-iam-authenticator` is now accessible.

![image](https://user-images.githubusercontent.com/11036786/152422852-c8904996-123e-4a80-86ea-3e58bc6c0a8a.png)

6 - Close/Open Lens and Open cluster 
6.1 The message will occur: `getting credentials: exec: exec: "aws-iam-authenticator": executable file not found in $PATH`

7 - Reinstall Lens

It will open the cluster perfectly

**Comment by Nokel81** [comment]
@eduardoaw Opening and closing lens is not good enough. You have to actually quit lens via the tray icon

**Comment by eduardoaw** [comment]
It would be nice to have the error message bring this procedure when there is a missing program in the PATH.

**Comment by Nokel81** [comment]
Fair enough, though it is impossible to tell if the program is missing due to it not being there or because the program hasn't been restarted recently

**Comment by awoimbee** [comment]
> Typically this is the issue when some shell init script (.bash_profile etc) is modifying PATH

Lens can't find `aws` when launched through the `.desktop` file, but it can when launched through the shell:
```bash
function k8s-lens {
  nohup open-lens >/dev/null 2>&1 &
}
```
My .zshrc indeed modifies $PATH, but it doesn't touch anything related to `aws` (which can be found at `/usr/bin/aws`).
What the hell ?

**Comment by ctsstc** [comment]
Just had a similar problem arise on Mac:

> Error while proxying request: getting credentials: exec: executable aws not found

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/416814/174674681-58a89e1c-a78f-4742-bf67-405580d67fa4.png">

I thought it came up because I left my VPN on, but that was not the case.

I ended up having to run: `brew install aws-iam-authenticator`.
Then make sure that Lens was closed from the system tray and restarted it seems to have fixed the issue.

**Comment by Z4ck404** [comment]
For mac users : 
as @ctsstc said, Just make sure to force-quite lens once you do an update
`option` + `cmd` + `esc` then start Lens again

**Comment by evgeny-goldin** [comment]
I had the same issues on MacBoook Pro M1 and none of the solutions above was helpful. However, [this thread](https://bytemeta.vip/repo/lensapp/lens/issues/5676) was helpful, specifically this advice: _"Lens is not respecting any PATH settings. The full path has to be configured in the kubeconfig"_. 

Once I changed `command: aws` to `command: /opt/homebrew/bin/aws` in `~/.kube/config` it worked just fine.

**Comment by eardk** [comment]
Happening to me too. Very annoying because I have to use kubectl to update my context and *then* go update aws path. I switch between prod / dev clusters regularly and this is a chore.

**Comment by rubenpetrosyan1** [comment]
> I had the same issues on MacBoook Pro M1 and none of the solutions above was helpful. However, [this thread](https://bytemeta.vip/repo/lensapp/lens/issues/5676) was helpful, specifically this advice: _"Lens is not respecting any PATH settings. The full path has to be configured in the kubeconfig"_.
> 
> Once I changed `command: aws` to `command: /opt/homebrew/bin/aws` in `~/.kube/config` it worked just fine.

To add my two cents.
Sometimes it's worth running "which aws" to find the correct position of aws executable.
On my laptop it was located in "/usr/local/bin/aws"
