### ISSUE TITLE
theme settings should be under cluster settings

### ISSUE THREAD

**Issue by matti** [lensapp/lens#88]
theme is under: Lens -> Preferences
other stuff is under: File -> Cluster Settings

I don't understand why theme is under Lens, when it only applies to one cluster.

**Comment by kke** [comment]
It's global and applies to all clusters.

![Nov-19-2019 09-03-34](https://user-images.githubusercontent.com/224971/69124047-96911f80-0aab-11ea-9ed9-10cfe69d65bd.gif)

**Comment by matti** [comment]
hmm, not for me?

**Comment by matti** [comment]
is my lens broken

**Comment by kke** [comment]
Not sure if it works differently in the compiled binary, perhaps requiring a restart, but there is only one global setting which is saved in the global preferences store (`config.json`), not into the per cluster preferences store (`lens-cluster-store.json`).

**Comment by miskun** [comment]
Main theme light/dark is switched from maine menu > preferences. The reason for this is that we feel people who like dark or light theme - will want to use that same theme for everything. To differentiate clusters, we will be introducing theme switcher per cluster, too - but those are just different colour schemes within that theme. Please look how Slack has implemented this same behaviour. In there you'll switch dark/light setting and within that theme, you have several colour schemes available. This is coming to Lens, too. No ETA yet.

**Comment by matti** [comment]
but if you are using lens in production you really want different colors for different clusters

**Comment by jakolehm** [comment]
No plans to add this, closing.
