### ISSUE TITLE
Update Broke Taskbar Icon when Lens Not Running

### ISSUE THREAD

**Issue by NArnott** [lensapp/lens#886]
**Describe the bug**
With the latest 3.6.0 update, when I pin Lens to the windows Taskbar and close lens, the Lens icon is no longer visible. It's just the generic Icon

**To Reproduce**
1. Load Lense
2. Right click Lens in TaskBar and click "Pin to Taskbar"
3. Close Lense

**Expected behavior**
The Lens Icon is visible and clear, so I can load Lens easily

**Screenshots**
![image](https://user-images.githubusercontent.com/198647/93220129-57fade80-f729-11ea-859e-04bc19cf2b20.png)

**Environment (please complete the following information):**
- Lens Version: 3.6.0
- OS: Windows 10

**Comment by juv** [comment]
Works fine for me. Old icon got removed while installing the new version. Then I started the Lens 3.6.0 executable and readded it to the task bar.

![Taskbar](https://i.imgur.com/9J3YUWh.png)

Windows 10 version 1809, build 17763.1397

**Comment by NArnott** [comment]
wierd. I'm on a later windows version, though I'd be surprised if that was the reason:

![image](https://user-images.githubusercontent.com/198647/93222651-6991b580-f72c-11ea-956d-0af0659d97bf.png)

**Comment by juv** [comment]
After installing, I've started Lens from the app menu (pressing Windows button and typing Lens), maybe that is different from what you did?

**Comment by NArnott** [comment]
I ran it from the Desktop icon (which was displaying correctly). 

...However, looks like a handy windows reboot solved the problem, so must have just been my machine.
