### ISSUE TITLE
Lens gets stucked in changelog notes

### ISSUE THREAD

**Issue by gabrielmcf** [lensapp/lens#889]
**Describe the bug**
 After the upgrade to 3.6.0, in Ubuntu 20.04, using snap, the program start gets stucked in the changelog page. It allows you to scroll and access the upper menu, but does nothing else.

**To Reproduce**
Not sure if this is reproducible. I already had a configured cluster.

**Expected behavior**
Open lens.

**Screenshots**
![Screenshot from 2020-09-15 15-07-13](https://user-images.githubusercontent.com/156070/93247770-2dc71200-f765-11ea-96ab-26f60a16eb86.png)

**Environment (please complete the following information):**
- Lens Version: 3.6.0
- OS: Ubuntu 20.04
- Installation method (e.g. snap or AppImage in Linux): snap
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info: [IPC]: setup channel "cluster:activate"
info: [IPC]: setup channel "cluster:disconnect"
info: [IPC]: setup channel "cluster:install-feature"
info: [IPC]: setup channel "cluster:uninstall-feature"
info: [IPC]: setup channel "cluster:upgrade-feature"
info: 🚀 Starting Lens from "/home/gabriel/snap/kontena-lens/116/.config/Lens"
info: SNAP env is defined, updater is disabled
info: [STORE]: LOADED from /home/gabriel/snap/kontena-lens/116/.config/Lens/config.json
info: [STORE]: LOADED from /home/gabriel/snap/kontena-lens/116/.config/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /home/gabriel/snap/kontena-lens/116/.config/Lens/lens-workspace-store.json
info: LensProxy server has started at http://localhost:36971
```

**Comment by nevalla** [comment]
So you don't see `Ok, got it!` button?

![image](https://user-images.githubusercontent.com/455844/93328482-74c80c80-f824-11ea-894a-f60ae6d60a7f.png)

**Comment by cmur2** [comment]
I experience the problem as well and I'm also not seing the mentioned button.The window's lower border is not visible for me.

Edit: Resizing the window did not work but launching with `./Downloads/Lens-3.6.0.AppImage --no-sandbox --disable-gpu --force-device-scale-factor=1.2` worked for my specific Linux window manager setup.

**Comment by gabrielmcf** [comment]
No, I don't see the lower bar

**Comment by evelyntavares** [comment]
> No, I don't see the lower bar

Changing to full screen mode did the trick for me

**Comment by gabrielmcf** [comment]
I've opened the dev mode and typed `$(".Button.primary").click()` in the console. It worked for me.

**Comment by jim-docker** [comment]
Looks like this is an issue for small screens. Is this happening for anyone having a screen with a height greater than 768 pixels?
