### ISSUE TITLE
Logs not showing from some pods

### ISSUE THREAD

**Issue by marshmn** [lensapp/lens#898]
Trying to view logs for some of my pods shows the logs window with a message inside:

```
Failed to load logs:
Reason:  ()
```

This doesn't happen for all pods. Some of my pods show logs as expected. The pods that I've noticed this happen on so far have been NodeJS pods - I'm not sure whether that's related or not.

Logs for these pods have shown fine in the past. I did just upgrade to Lens 3.6.0 in the last 24 hours, which may or may not be related.

Viewing the logs using the included version of `kubectl` works fine.

**Comment by matti** [comment]
the log data has already been purged from the master. lens needs some log collector in the cluster.

**Comment by marshmn** [comment]
Hmmm, I'm still new to Kubernetes (and Lens) so it's possible that I'm missing some understanding here. However, a few points about the scenario:

Whilst I was unable to view logs in Lens, I could still view them via `kubectl` and via GitLab. Would they have still been visible if the log data had been purged from the master?

The logs did start working again a little later - I don't know what changed. Once they were working again they appeared to show data from back before the problem had happened.

**Comment by sixcorners** [comment]
Could this error message be made better?

**Comment by Nokel81** [comment]
We have recently done some fixes for logs, is this still an issue?

**Comment by matti** [comment]
see my previous comment above:

> the log data has already been purged from the master. lens needs some log collector in the cluster.

**Comment by Nokel81** [comment]
Is that the master of Lens?

As far as I can tell, Lens uses the same kube route that `kubectl logs` does. As I have found some pods that I cannot view logs for (in Lens) but I get the same response when I use `kubectl logs`

**Comment by marshmn** [comment]
In my case, I was able to see the logs using `kubectl` but not using Lens - which made me think that this wasn't an issue with the logs having been purged?

I only saw it happen once and I've never noticed it since (though I can't really say that I view logs from Lens often enough to really be able to say whether or not any potential issue may have been fixed or not...)

**Comment by Nokel81** [comment]
Okay thanks. We have made some improvements to logs, so I am going to mark this as resolved for the time being. If it springs up again please don't hesitate to open a new issue.
