### ISSUE TITLE
Missing Icon on Ubuntu 19.10

### ISSUE THREAD

**Issue by strigona-worksight** [lensapp/lens#90]
**Describe the bug**
The icon is either missing or fully transparent.

**To Reproduce**

**Expected behavior**
There should be an icon for Lens in the taskbar.
![Screenshot from 2019-11-19 10-57-10](https://user-images.githubusercontent.com/13368604/69176852-5b96e800-0abb-11ea-9ae9-a2600dc15bba.png)

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 2.6.1
- OS: Ubuntu 19.10
- Installation method (e.g. snap or AppImage in Linux): AppImage
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
➜  utils >  ./Lens-2.6.1.AppImage 
info: Checking for update
Loading cluster from store with key: dev
info: Update for version 2.6.1 is not available (latest version: 2.6.1, downgrade is disallowed).

```

**Kubeconfig:**
n/a

**Additional context**

**Comment by jakolehm** [comment]
Does it work if installed via snap?

**Comment by strigona-worksight** [comment]
Hi, sorry for the delay... I transitioned to working from home 2 weeks ago and didn't have my Ubuntu PC with me till now. I installed the snap and the icon is present and working.

**Comment by strigona-worksight** [comment]
Not sure if you want to close this issue. I'm going to stick with the snap from now on.
