### ISSUE TITLE
Lens on MacOS not displaying Kube Cluster content

### ISSUE THREAD

**Issue by senad-ameti-2** [lensapp/lens#904]
**Describe the bug**
Kube config seems to be loaded but into Lens but Lens does not render content. This is happening in V3.6.2

**To Reproduce**
1. Start Lend on a MAC OS
2. Load a valid KubeConfig FIle
3. No Cluster Details Rendered in the UI 
4. When I executed "kubectl get nodes" from the Lens Terminal I get expected results
5. When I open Developer Tools, I get the screenshot attached

**Expected behavior**
I expect the UI to Container Cluster information (Nodes etc)

**Screenshots**
Screen shot attached
![image](https://user-images.githubusercontent.com/69286026/93437000-d8c6ff80-f90e-11ea-8f7a-a758fe85fe8c.png)

**Environment (please complete the following information):**
- Lens Version: 3.6.2
- OS: [e.g. OSX] Catalina
- Installation method: Manual Download from Github
 
``

**Additional context**
This is not a KubeCOnfig file issue as I had a colleague of mine try it on his Mac with the same Kube config and he had no issues.

**Comment by nevalla** [comment]
If you re-open the app, is it still the same?

**Comment by senad-ameti-2** [comment]
I tried reopening and reinstalling. I also cleared the caches (the browser cache with the app and cache files on the file system itself) 

As I mentioned, if I use the terminal with the app and execute 'kubectl' commands I get expected results. It just seems that the application is not getting information from the cluster

**Comment by vandreykiv** [comment]
Same for me. Could that be fixed?

**Comment by Nokel81** [comment]
Given your screenshot it seems that there are RBAC restrictions on your cluster. Lens cannot work around those.
