### ISSUE TITLE
Infinite chart load from WSO2 repo.

### ISSUE THREAD

**Issue by marknefedov** [lensapp/lens#905]
**Describe the bug**
Infinite loading on chart open.

**To Reproduce**
1. `helm repo add wso2 https://helm.wso2.com && helm repo update`
2. Try to open is-pattern-1 in Apps/Charts menu.

**Expected behavior**
Chart information should open.

**Screenshots**
https://imgur.com/a/nPXGwT5

**Environment (please complete the following information):**
- Lens Version: 3.6.2
- OS: Fedora 32
- AppImage in Linux 

 `helm install wso2 wso2/is-pattern-1 --version 5.10.0-2` works fine.

**Comment by Nokel81** [comment]
fixed by #949
