### ISSUE TITLE
disable connect to node by ssh

### ISSUE THREAD

**Issue by BlueCompiler** [lensapp/lens#921]
1、On the version 3.5.3, lens can connect to node with command line by ssh. But from the version of 3.6.0, it always disable connect to node with command line. If you try it, you will see the problem.
2、May you will say, Hi there! You should confirm that your node server is OK? And I will say "YES", I tried with lens version 3.5.3,It is OK, and lens version from 3.6.0 is not OK.

![image](https://user-images.githubusercontent.com/59145629/93546567-a3192980-f995-11ea-9c28-f2d467688c9a.png)

**Comment by Nokel81** [comment]
Is this still a problem? Are you able to connect to nodes in a newer version of lens?
