### ISSUE TITLE
can not open with browser

### ISSUE THREAD

**Issue by BlueCompiler** [lensapp/lens#922]
1、from the version of 3.6.0, lens can not open a lens page on browser.
2、May you will see "Hi there , do you sure your browser is OK?", And I  will answer "YES", I tried with lens version 3.5.0, It must OK.
![image](https://user-images.githubusercontent.com/59145629/93547880-a5c94e00-f998-11ea-979d-12df07761b29.png)

**Comment by nevalla** [comment]
At this moment we are not planning to support opening Lens on browser.

**Comment by BlueCompiler** [comment]
OK，Now I Know. At least I confirmed that it is not a bug.
