### ISSUE TITLE
Cannot read property 'kc' of undefined(solved)

### ISSUE THREAD

**Issue by mailbyms** [lensapp/lens#923]
**Describe the bug**
Cannot read property 'kc' of undefined

Lens 3.5.1 worked fine with k8s 1.15.0，after autoupdate to 3.6.0，Lens fails to connect to any cluster
So I re-install Lens 3.5.1, then add cluster with a  config file. Error show up saying "Cannot read property 'kc' of undefined"

How to fix this?

Here is my config file of a k8s 1.15.0 master node:

`apiVersion: v1
kind: Config
preferences: {}
current-context: kubernetes-admin@kubernetes
clusters:
  - name: kubernetes
    cluster:
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EY3dPREE1TXpZeU5Wb1hEVE13TURjd05qQTVNell5TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTEIrCkhsQkFQb0t0TEw2Z09sR3h2M1hDcTgwdXhyb29uVlZjRlYzUUFnU2ZXUGp3MzF2MFV6VzlpTi9EbGNVNCtrOWoKN2s1QmZOaUNEWVBOMFhHNENWSDNYNUo1eEorb0tRb25wSVVkVVc2Y2ZmMFpoVS9RUWR6NDUwZVhUT0xLL3ZGTwpORWxQYzJBWTlLWkRPdGg5L3BrbWdKQkhMZUpoYTVLMVZhMUJkWGxSQ1hERVgzVEdpcUQvTU5tSW1KY0E0eFdBCnJKcGlnaThFYXl3R0d1VEIrY3pDcEhQa1JKeW5xczV2akJldmo3eUNvMHgrVEZLWkh5S3dNOE02NFVqOGdVam0KaWlnd0tQcVlxTE9hcFJ4NE5YeGZHSGxnSnQyRVVHQkRicHMveUtLWE9GMzhKYnMzc1NZcnJGTldIYXYrU2dpZgpNZGV0alBIUTNza0dPQTY3RFRNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHZ3JsRGEvMzlWWS9XMFlFSm4zVzQ0ekpFZDgKYVNjdHBYSXkza2J5d29yNzRJV1pZdW93bHBVaExsVDQ1cFFwU2tEQk1yTGRLdmdCNWgzaWVVVjhzcXNnZmhydQpRTHNoQnBTN0EvWVlRREtnZi9BeHpYREdJNXgrT2t4MmtIRlpodlYrNDFVWGFIeXN0QU16V2hJY3p0QXpCZHNTClFQMVppMmQzaEtBdFhIOGFvQXhXUGdWeUN5cWU1cmFhV2I3cHk0Tk9TY3BrR1VrQnZWV0NxYXpyN0R3SVdlbVAKS2E0RTJJdytuam9rdktIUU00MXBqbU00YjkyVG9aaE5UZThMUFJoVUJxQW9MZXNnbjZ3S2t6dE1JVXhJbjY2RgpNL3h1QTVjamhBSGtqQkRBbjZZdllFRTJkcmt0c0VBVEF0anZPTHdkSGlPUVNVQkEzeVd3dU95WDZsND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      server: 'https://192.168.0.39:6443'
      insecure-skip-tls-verify: false
contexts:
  - name: kubernetes-admin@kubernetes
    context:
      cluster: kubernetes
      user: kubernetes-admin
users:
  - name: kubernetes-admin
    user:
      client-certificate-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lJSDk0SnVIVlNDbHd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TURBM01EZ3dPVE0yTWpWYUZ3MHlNVEEzTURnd09UTTJNamRhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXZvd0hHeStCYWt0NVhMNXYKbk9JaFhZbnB6ZUp0dXhwVGFFWm1iaUlJUnI1cko2MkhUbkFtaUY1ZEc4eXByYjBzaTJQMGovRGc0OGpWYVB4UQpTTTRhMjEvQXA2bllBSkpIY1ZWL1ZWbXI2L2ZHdlZWYkpqMFk4SzM3MUZmU25EMng4aWJlYWxzM0ZtN2NQMXpPCnFiaWNvL0dDVjJkRWg3SDNGa3QrU0wyZEFJLzNtSWFRMnVnTldWdXAva0xTcUlvcGJaekttWGhxT0VIUXAydHMKS3JDajRxS3QrOHhubGpFQ3JkeWNKeUkxbmllR216Vkg1MWdtV1MyTHU0eU9qdFRiS2ZmRnZKdTVORW5FQjZDLwpaZjM5cmpWWkx4VnY4bWcycmo3N3c4aHBDTnl6bGJaeTNBaFRkMW1rWW8yY1lGc1RIbU4zRTdvaEp1SC80ams1ClVzRXJxUUlEQVFBQm95Y3dKVEFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBNHpQWktIOGo5S1hmU3gvSUVJR0Z2TUFCNkowclZPZFhWRQo4c041b1pGTVVZeG5DSUNZb0k1bE4vRm5mMmwzRi9sdEtxd3NhS0wxVnZaSEVNb25JeTdCSmgvRGVoTlVkQ1NECkJ3Ymx6ekt1Qy9jblZiNDBWU21iVVVUK3Fka1RHN0ZrMzlhdGdVM25nNTY1YkwvTnIyUlNpekNwbGhSalFEUjIKdzRXVUYvN1E2VGlSemZtYkpFU1lBd2FYbUN6UWNrYjAwNG4xbHFTaXZOUk14YW03OURsYXBGdzB5REhzMm15eApMaVczS1JqaFpBeGo4UFphdXkwUzJxdzFQSmlNczdCUHcrS1ZvL0Q4MlJSK3NNVHFQQ1VlNy9UbTFYVTNKVXNIClF2b2QvRVlPWnhFWlp4QVdiOTUyYjdScXFiZ3RoWTVnVWxRZHZsSWRXL21JQkJrdnpsdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      client-key-data: >-
        LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdm93SEd5K0Jha3Q1WEw1dm5PSWhYWW5wemVKdHV4cFRhRVptYmlJSVJyNXJKNjJIClRuQW1pRjVkRzh5cHJiMHNpMlAwai9EZzQ4alZhUHhRU000YTIxL0FwNm5ZQUpKSGNWVi9WVm1yNi9mR3ZWVmIKSmowWThLMzcxRmZTbkQyeDhpYmVhbHMzRm03Y1Axek9xYmljby9HQ1YyZEVoN0gzRmt0K1NMMmRBSS8zbUlhUQoydWdOV1Z1cC9rTFNxSW9wYlp6S21YaHFPRUhRcDJ0c0tyQ2o0cUt0Kzh4bmxqRUNyZHljSnlJMW5pZUdtelZICjUxZ21XUzJMdTR5T2p0VGJLZmZGdkp1NU5FbkVCNkMvWmYzOXJqVlpMeFZ2OG1nMnJqNzd3OGhwQ055emxiWnkKM0FoVGQxbWtZbzJjWUZzVEhtTjNFN29oSnVILzRqazVVc0VycVFJREFRQUJBb0lCQVFDUjZKZm9jVkFnSFBzcAowWW1XRUhLTU5mY2ErTEFkL2VLd2puZ1JEVzVZL2FjQUV4anhMMS9TUEsvL2daRE13WGRDcForNE9UTjhPV1Z4CnB3T3pQRi9FYkdZUi9UU3grMUZKcjdaNW5OalJNRUsyNkkyTGttMXVuMHVmSmtEWDgwWTNyeHZSUlZmQmpkS0oKa24rTjV4ZkxVandFd2Nid1FZNTdQQVBQbjZLQnNtb0RaU1dBWUdhL3k5dGJmR05ScTZhR1FEdVo5bjB6WVlHbQo1allQZTVzMXYvN2RlbVNtaGRhSGQrRWxOTUtGUWI2WjczQ0k5ZW03aWxvTzY3QUlhelQyTVFvMnNrbTY2aThQClhDdDZlTG0rMEs2ZGorN0ZQN3U5clhEc3pjRTVSU3BVKzV1eklEQU50cXNHMlRvOXNjeGZsaTllK0d6RlhGT1kKUWI3cGd0d0JBb0dCQU5kcWFISEYwMUNnaVBpdEF6L2ppN2U1eC9UVlJDdURUKytWNXh0bkhBcWVJWE1FaFRIcApSTUVkSkpqNUJyV1FzdzB4eG5ZSU1kbHV5ZGl6K3JENzRENUJ1M1A5MFo1TFlOWXNpdklCNkQ5VFNaVEk3TWtrCkZkNll6NDIrdzN5S3IvYWp6bUVtK2tGMUlTWENOTXZ6UzlhNDQwK0VBYXFIQi9OalVTTkVGaWxSQW9HQkFPSnkKTVZhWXFaMnFLTFFpK0tibURoMDNhSmtTTGxUd1NmWS9KSmRWLzJKZkdMRmVQQ09zZGhYK2dWMXM3S2JrcWdteQpWRWZrUWozTy9EZkhCU2lhTkFFQnE1c0tnbkRlbXhnLzFBQ2RQUEMzZ1kxbGVQRjJJNmNRWG10UWtLQTVheDR2CkROWFlmN1dnUGluV0VsN3dmTUpKVkNxMzRPTUd6ekJETnlPVzdFYlpBb0dBV055NVp5MmZSV1JqL0ltS2pLRjIKY256K0FuNnpsMnVjM3cyc2YzNWliL0xaZzVQNnlpTWJUTHFUN1ZMVk5MTVRXYjhOeW9VSTQxUXppZVI4NXVPUQpscjRROFFGa3BuTWI2RjRKbDFtNEQ5OXd2Q0xDb3hyeXRwZTlEeEVCblcrc3RRYlB6UDRDUUZ4c0p5SmRHMEVyCktOR3VXNC91REFXVi93NGFXM3pyMDNFQ2dZQk1wcXJjelVCZEJrUlE5YVdGbVVvZHlhdTJaTmthRjF4eDVsM1UKZkYrK1JNSnZCNThEMUZVRWpPbnRYZm1kWkxuS0huczQrcU1SbVFiM09uOGNoMVlqSVJXZG5ha1oyOEJVTFFidQpUa3Rha0VOaVFYNzIvUzZFVnA0ZlpWNFBYbUJNRDFFZzhmQUk0djBuM0RiTHZFdisyQ09OY2tERm1JQjVyY2IwClhSb053UUtCZ1FERXR4Mk5UOHF4dnBuQUo5eXoxN3NsSzhEZ1JOSGxrWUVLUVdZbEgwc1F0VWErRThvZTk1Q2QKV01WQlRWWjhRTEZBK3dxZWZPZG1OLzFPcSt5azRJQWJmekEyT013MDVKUmtNK3hxZHBROEt4V3p2eXVvbDBUZgpiOW8zdW9GK2N5Zk95eFBZb0FOSUFHWW1VWkdrd09UMnJPaTNjVVJOSTlSbEZMNGJuZy9sMHc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=`

**Comment by nevalla** [comment]
To revert back to use `3.5` you need to remove `lens-cluster-store.json` from app resource folder. Based on Kubeconfig I don't see anything special why Lens 3.6.0 would not work. Do you see any error messages? Have you tried `3.6.2` already?  Is it having the same issue?

**Comment by fguiet** [comment]
Hi, 

Removing `lens-cluster-store.json` file from C:\Users\fguie\AppData\Roaming\Lens did the trick for me.
I reverted back to version `3.5.3`, version `3.6.3` does not run on my machine `Windows 10 family version 2004, 19041.508` ie when Lens version `3.6.3` is loading I get : "This application cannot be run on your PC"

Fred

**Comment by MarlezePot** [comment]
I'm experiencing the same issue, Lens was working fine on Friday when I signed off and this morning I opened Lens and (no error) just can't see any cluster anymore.  When trying to add the cluster again I'm getting the` 'Cannot read property 'kc' of undefined'` error.

`Lens 3.5.3 installed.`

I removed the `lens-cluster-store.json` file and that did not help in my case.

Upgraded to 3.6.3 and the cluster was there when I opened Lens :)

**Comment by mailbyms** [comment]
Guys，problem seems to be solved automaticly, 
here is the whole story:
3.5.1 worked fine with k8s 1.5.0 before auto-update to 3.6.0
3.6.0 failed to open cluster
back to 3.5.1, failed to add cluster
re-installed 3.6.0,  success to open clusters! Including those failed clusters added in 3.5.1

em, it's weird

**Comment by Drewfoust** [comment]
Was gettting ESOCKETIMEOUT errors with version 3.6.6 on win10Pro.
uninstalled and deleted all APPData values.
reinstalled 3.5.1 getting 'Cannot read property 'kc' of undefined'  when trying to add cluster config.

**Comment by mailbyms** [comment]
Al

**Comment by mailbyms** [comment]
All guys , finally  I know the reason why: 
Lens adds a context name restriction after 3.5.1, so after upgrade to new version, we need to re-add clusters again.

notes:

When adding a cluster, choose 'Paste as text', **You have to change the context name** !!!

e.g.

Orginal 
```
...
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes

```
Change to another name, like kubernetes3

```
...
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes3
current-context: kubernetes-admin@kubernetes3

```
Then click ‘select context’, choose kubernetes-admin@kubernetes3. Click 'add', done.

My lens is 3.6.4 now, and it works fine.
