### ISSUE TITLE
Menu Preferences shortcut

### ISSUE THREAD

**Issue by soyoo** [lensapp/lens#929]
current, it is "Ctrl+逗号"; is it should be "Ctrl+,"?

**Comment by soyoo** [comment]
screen print.
![lens](https://user-images.githubusercontent.com/16472297/93878153-2cb95600-fd0c-11ea-9e40-efaea02d85e5.jpg)

**Comment by Nokel81** [comment]
Is this still an issue? We have it set to `CtrlOrCmd+,`

**Comment by soyoo** [comment]
> Is this still an issue? We have it set to `CtrlOrCmd+,`

hi, It doesn't seem to have changed. My OS is Windows 10, simplified chinese version.
![lens](https://user-images.githubusercontent.com/16472297/112466071-6264f780-8da0-11eb-92cd-2bef69a12b53.jpg)

**Comment by Nokel81** [comment]
So this isn't just about chinese. It is any language and electron does the changing itself. It also seems to be the desired behaviour by electron (to localize the accelerators like with the rest of the system). I guess we could force `en_US` if we wanted too but I don't think we should. Therefore I am going to close this as won't fix.
