### ISSUE TITLE
Add ability to opt-out of data collection

### ISSUE THREAD

**Issue by yingchun79** [lensapp/lens#93]
**What would you like to be added**:
From Kontena's FAQ page:
> We collect data that you submit via kontena account registration.
We collect data about events that are happening in Lens app: application started, application stopped, logged in, logged out, cluster settings page open, cluster view open, cluster feature X installed, cluster feature X uninstalled, cluster feature X upgraded, terminal opened and kubernetes resource applied. There is no metadata related to these collected.
We are not collecting any kind of telemetry data from Lens app: for example we don't know how many clusters you might have, how many nodes you have, what is actually running in your cluster etc.

As a user, I would like the ability to opt-out of this data collection.

**Why is this needed**:
In some environments and teams, there's a strict policy of not participating in any data collection.

**Environment you are Lens application on:**

- Kubernetes distribution: vanilla on-prem
- Desktop OS: Mac

**Comment by miskun** [comment]
At the moment this is not possible and we don't have plans to disable data collection. It's the only way for the company behind the product to see how many users are actively using it. As reminder: no private data is collected. However, we see issues with certain Enterprise environments.

A workaround for this might be to use a build that we are making available for Enterprise IT departments. This build is primarily designed for big enterprise IT for easy software distribution, but among other things - it won't include any kind of tracking. Unfortunately, this build will require Enterprise license to work.

**Comment by jakolehm** [comment]
Fixed in 3.0.
