### ISSUE TITLE
Kubectl binary download blocks when opening a cluster dashboard

### ISSUE THREAD

**Issue by nevalla** [lensapp/lens#933]
**Describe the bug**
When opening a cluster dashboard first time, Lens will download kubectl binary matching to the cluster version. However, afaik the dashboard itself does not require kubectl binary. When opening the terminal, installing features or applying resources kubectl binary is needed and Lens will already download it on demand. So it seems that downloading kubectl binary is not necessary when opening the cluster dashboard.

**Comment by jakolehm** [comment]
I think it should be downloaded right after dashboard is opened. But instead of blocking everything it should be spawned to background.
