### ISSUE TITLE
Executing a kubectl command from inbuilt terminal triggers Bitdefender Antivirus

### ISSUE THREAD

**Issue by dragon2611** [lensapp/lens#934]
Lens 3.6.3 on windows, which was running quite happily until I dared run a kubectl command from the inbuilt terminal at which point Bitdefender decided kubectl.exe was malware along with helm3.exe, Lens.js, messages.js and even lens.lnk.

I'm pretty sure this is a bitdefender issue and will raise it with them.

**Comment by dragon2611** [comment]
Got confirmation based on the sample and logs I'd sent in that lens is not malware and the next bitdefender update should fix this detection.

**Comment by nevalla** [comment]
> Got confirmation based on the sample and logs I'd sent in that lens is not malware and the next bitdefender update should fix this detection.

👍 Thanks for reporting this to bitdefender!

**Comment by DarkMukke** [comment]
it is happening again, after install lens and try to open it it just deletes it
