### ISSUE TITLE
Makefile and parallel execution build issue.

### ISSUE THREAD

**Issue by zaggash** [lensapp/lens#936]
**Describe the bug**
The Makefile is not compatible with parallel execution.

**To Reproduce**
run the build with :
make -j8 build

**Expected behavior**
The build should run and finish without any error.

**Environment (please complete the following information):**
Add a MAKEFLAGS with "-j8"
Run a manual build of the app with `make build`
 
**Logs:**
```
[...]
yarn install v1.22.5
$ concurrently yarn:download:*
/bin/sh: concurrently: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [Makefile:13: download-bins] Error 127
make: *** Waiting for unfinished jobs....
[...]
```

**Workaround:**

I need to either unset my MAKEFLAGS variable or force it to `make -j1 build`

**Comment by zaggash** [comment]
To fix it, you could probably make good use of `.NOTPARALLEL`  
https://www.gnu.org/software/make/manual/make.html#index-_002eNOTPARALLEL

**Comment by nevalla** [comment]
I think the issue here is that `concurrently` package is missing.

**Comment by zaggash** [comment]
Hi @nevalla 
`concurrently` should actually be installed from the Makefile here:
```
install-deps:
	yarn install --frozen-lockfile
```


Because of the parallelization and the `-j8` not being supported, it starts multiple steps and failed.
We have 
```
$ concurrently yarn:download:*
/bin/sh: concurrently: command not found
```
because `concurrently` is needed in the next Makefile steps.

Give it a try, the reproduction is dead simple.

**Comment by nevalla** [comment]
This should work now as expected.
