### ISSUE TITLE
Connected to cluster but unable to list kubernetes resources

### ISSUE THREAD

**Issue by harindersingh** [lensapp/lens#939]
Using kubectl I can list pods, namespaces in a cluster. When I use Lens to connect to the same cluster/context, it shows it has connected but from Console(Developer Tools) I can see the following error:

```
electron/js2c/renderer_init.js:74 Uncaught (in promise) Error: Error invoking remote method 'cluster:activate': TypeError: Cannot read property '1' of null
    at EventEmitter.i.send.i.invoke (electron/js2c/renderer_init.js:74)
```

Note: This is in a VPN network. kubectl is working in the same VPN network and also able to run kubectl proxy on the same cluster to list resources using curl http://localhost:8001/api/v1/namespaces/<namespace>/pods). Lens is able to resources for docker-desktop.

**Environment (please complete the following information):**
- Operating System: macOS Cataline 10.15.4
- Lens: 3.6.3
- Electron: 9.1.2
- Chrome: 83.0.4103.122
- Installation method: brew cask install lens

**Expected behavior**
It should be able to list resources or else provide a detailed error about the situation.

**Logs:**
How can I get the logs? I tried to check in ~/Library/ApplicationSupport/Lens.

**Kubeconfig:**
kubeconfig file is correct as the required set of tasks(get pods, namespaces, logs) are accessible on the same cluster/context using kubectl.

**Comment by Nokel81** [comment]
Is this still an issue with 4.1.4?
