### ISSUE TITLE
CRDs updated with delay

### ISSUE THREAD

**Issue by xcrezd** [lensapp/lens#948]
**Describe the bug**
After update CRD resource, Lens shows the old values for ~ 5 minutes

**To Reproduce**
1. Deploy CRD resource
2. Go to Custom Resources list for CRD
1. See values
2. Update CRD resource
3. See old values for ~ 5min, then new one will be shown

**Expected behavior**
Update CRD values with minimum delay

**Environment (please complete the following information):**
- Lens Version: 3.6.4
- OS: Ubuntu
- AppImage

**Comment by Nokel81** [comment]
Is this still an issue in 4.1.4?
