### ISSUE TITLE
Error from server (Forbidden): pods "demo-6888488647-2zc4k" is forbidden: User "267596194370097065" cannot get resource "pods/exec" in API group ""  in the namespace "demo"

### ISSUE THREAD

**Issue by hundanLi** [lensapp/lens#950]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux): 
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
That means you have RBAC restrictions on your pods.
