### ISSUE TITLE
Paste kube config but no contexts colud select

### ISSUE THREAD

**Issue by AI-H** [lensapp/lens#952]
**Describe the bug**
paste $HOME/.kube/config   but no contexts could select

**To Reproduce**
1.  vim $HOME/.kube/config
2. copy config file as text
3. add cluster,chose Paster as text
4. paste   config file 
5. Slect contexts , but no contexts  could select

**Screenshots**

![image](https://user-images.githubusercontent.com/37956816/93986656-32b94080-fdb9-11ea-89f4-889a4aa838ef.png)

**Environment (please complete the following information):**
- Lens Version:   3.6.4
- OS: Windows

**Comment by dheerajinganti** [comment]
I am also facing the same issue. Not able to add new cluster. Existing ones are fine. Even the default config without pasting also doesn't seems to list context. So there is no way to add new cluster anymore.

Lens Version: 3.6.4
OS: MacOS Catalina (10.15.6)

**Comment by watermeion** [comment]
Me, too. seems some kind of bugs.

**Comment by nevalla** [comment]
Fixed in #969. If you want, you can test this fix in version [`3.6.5-rc.1`](https://github.com/lensapp/lens/releases/tag/v3.6.5-rc.1).
