### ISSUE TITLE
Text in Terminal in Windows is unreadable

### ISSUE THREAD

**Issue by mwyrembl** [lensapp/lens#953]
When I create a new terminal session in Lens for Windows and start to type, the text becomes unreadable:

![image](https://user-images.githubusercontent.com/5305613/93989924-c6bfe380-fd8a-11ea-9302-2ed162c40675.png)

I am using the following Lens version for Windows:
![image](https://user-images.githubusercontent.com/5305613/93990378-549bce80-fd8b-11ea-8f06-6369b2762dfa.png)

Microsoft Windows [Version 10.0.17763.1457]

**Comment by Nokel81** [comment]
Is this still a problem with 4.1.4?

**Comment by mwyrembl** [comment]
No it is solved now. Thank you.
