### ISSUE TITLE
Can not add new cluster

### ISSUE THREAD

**Issue by dheerajinganti** [lensapp/lens#955]
**Describe the bug**
Can not add new cluster with 3.6.4

**To Reproduce**
Not able to add new cluster. Existing ones are fine. Even the default config without pasting also doesn't seems to list context. So there is no way to add new cluster anymore.see below

**Expected behavior**
Able to add new cluster
**Screenshots**
![image](https://user-images.githubusercontent.com/56450649/94016373-a6fcdf80-fdcb-11ea-8c34-ea92620f7af4.png)

**Environment (please complete the following information):**
Lens Version: 3.6.4
OS: MacOS Catalina (10.15.6)

**Comment by nevalla** [comment]
Do you already have clusters with the same context names added to Lens app?

**Comment by dheerajinganti** [comment]
yes, i have multiple clusters with same context

**Comment by ghost** [comment]
The same for me. It always complains on the missed context. OS: MacOS 10.15.6 Lens: 3.6.4.
