### ISSUE TITLE
Error: Minified React error #31

### ISSUE THREAD

**Issue by ilikosha** [lensapp/lens#959]
Hi guys! after upgrade Lensapp from old version (i forgot what exactly version) to latest 3.6.4 i had issue
OS Win10 1909

> Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=TypeError%3A%20Failed%20to%20fetch&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
>     at e (http://9fda58a7-6f5b-4f4c-8ae5-d1ac5385ff49.localhost:56385/build/Lens.js:2:4215220)
>     at F (http://9fda58a7-6f5b-4f4c-8ae5-d1ac5385ff49.localhost:56385/build/Lens.js:2:4215320)
>     at P (http://9fda58a7-6f5b-4f4c-8ae5-d1ac5385ff49.localhost:56385/build/Lens.js:2:4215966)
>     at Object.toArray (http://9fda58a7-6f5b-4f4c-8ae5-d1ac5385ff49.localhost:56385/build/Lens.js:2:4216479)
>     at r.value (http://9fda58a7-6f5b-4f4c-8ae5-d1ac5385ff49.localhost:56385/build/Lens.js:2:5782644)
>     at http://9fda58a7-6f5b-4f4c-8ae5-d1ac5385ff49.localhost:56385/build/Lens.js:2:5783019
>     at http://9fda58a7-6f5b-4f4c-8ae5-d1ac5385ff49.localhost:56385/build/Lens.js:2:62034
>     at Array.map (<anonymous>)
>     at Proxy.forEach.Array.<computed>.hr.<computed> (http://9fda58a7-6f5b-4f4c-8ae5-d1ac5385ff49.localhost:56385/build/Lens.js:2:61989)
>     at r.value (http://9fda58a7-6f5b-4f4c-8ae5-d1ac5385ff49.localhost:56385/build/Lens.js:2:5782976)

How i can solve this problem?
Maybe lens has some debug logs for understanding shat exactly happen?
maybe OS dependencies or AntiVirus program or something else?

**Comment by ilikosha** [comment]
Additional info:

1. This error happen when i try to download  kubeconfig file from Service Account section.
3. k8s version is 1.19.2 and kubectl for lens 1.19.0

**Comment by vnikitov** [comment]
Simila issue on my side. 
I'm also not able also to see the content of the kubectl files. I can download them but they are empty.
Also, the error does not appear instantaneous (at least on my side).

**Comment by ilikosha** [comment]
Work around, i went back to version 3.5.2 and now everything works fine.
But why newer version works with problem?
