### ISSUE TITLE
Error in Internet disconnected environment

### ISSUE THREAD

**Issue by jax79sg** [lensapp/lens#96]
**Describe the bug**
After downloading the appimage and transferring to a standalone network where the cluster lives, the application requested access to the internet to create/login.

**To Reproduce**
1. Run AppImage
2. Encounter login screen (Skip login as there's no Internet)
3. Scroll menu to 'Connect to cluster'
4. Cannot click 'Connect to cluster'  (Button disabled)

**Expected behavior**
1. Run AppImage
2. Encounter login screen (Skip login as there's no Internet)
3. Scroll menu to 'Connect to cluster'
4. Click 'Connect to cluster'  and continue.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: Latest
- OS: [Ubuntu] 
- Installation method (AppImage in Linux):

**Comment by miskun** [comment]
At the moment this is not possible and we don't have plans to disable requirement for Kontena Account login. It's the only way for the company behind the product to know who is using the product and reach out to its users for feedback. However, we see issues with certain Enterprise environments.

A workaround for this might be to use a build that we are making available for Enterprise IT departments. This build is primarily designed for enterprise IT for easy software distribution, but among other things - it won't require Kontena Account login. Unfortunately, this build will require Enterprise license to work.

**Comment by jax79sg** [comment]
Ok thanks.
