### ISSUE TITLE
Clusters In Multiple Workspaces

### ISSUE THREAD

**Issue by danielbu-ibm** [lensapp/lens#960]
**What would you like to be added**:
The ability to have the same clusters in multiple workspaces

**Why is this needed**:
I work with many clusters and the workspace feature is great. I generally create workspaces for each product (They are large with many microservices, so have their own sets of clusters globally distributed) and within each of those is split into staging, pre-prod, prod etc. When I perform chaos testing for example I am usually working with a subset of the clusters. It would be useful for me to be able to create a workspace for this and add the clusters to it without needing to remove them from their primary workspace.

**Environment you are Lens application on:**

- Kubernetes distribution: IKS IBM Cloud
- Desktop OS: macOS Catalina

**Comment by jakolehm** [comment]
This is actually a regression. I'm pretty sure it was allowed with Lens 3.5. @nevalla wdyt?
