### ISSUE TITLE
cluster settings with explicit "save/commit/okay" button

### ISSUE THREAD

**Issue by mozai** [lensapp/lens#97]
**What would you like to be added**:
In File > Cluster Settings, some user input to commit/rollback the form fields, like the "Okay" and "Cancel" buttons in a dialog box.

**Why is this needed**:
Standard UX behaviour.  
- Give the user a sense that config settings are accepted.
- Give the user a "cancel/rollback" button if the user detects they entered bad data.
- Give the software an opportunity to validate user-inputted data and respond with suggested corrections  ie. if someone types "https://..." thinking they need to enter an ingress, but the field expects a service "$ns/$service:$port" description.

**Environment you are Lens application on:**
I think you meant to say "you are **using the** Lens application on" ? 
- Kubernetes distribution: n/a
- Desktop OS: Linux, AppImage
- Kontena Lens version: 2.6.3

**Comment by miskun** [comment]
The current approach is adopted from the way how (for example) VS Code is handling similar config / preference settings. All settings are saved on "blur". We can debate if this is good, bad or ugly but the current implementation is according to idea we originally had + it's not unique just for this app.

**Comment by mozai** [comment]
@jakolehm Why did you close this feature request?

**Comment by jakolehm** [comment]
@mozai sorry for missing an explanation while closing this. It was closed because settings is designed to work without save/commit/okay (see @miskun comment).
