### ISSUE TITLE
node-gyp 5.1.0 MacOS?

### ISSUE THREAD

**Issue by gustaveherbst** [lensapp/lens#979]
I have installed node-gyp 7.x globally, yet a make init is trying to us node-gyp 5.1.0. I have checked the package.json and it's not listed, where is this being pulled from or referenced? I need to updated it for the Mac.

I end up with this trying to compile

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1

However, Xcode is installed, 12 beta for BigSur. Thoughts? From what I have seen out there the remedy is suppose to be upgrading node-gyp. Again there is some reference to node-gyp 5.1.0 and would like to know where this is being referenced.

Thanks
DB

**Comment by Virifi-AI** [comment]
Resolved. If Xcode 12 Beta installed be sure to reset path, sudo xcode-select --reset

DB

**Comment by Nokel81** [comment]
We are now using node-gyp@7 so I think this can safely be closed.
