### ISSUE TITLE
kubectl exec not working while proxy configured

### ISSUE THREAD

**Issue by aaronsssya** [lensapp/lens#990]
**Describe the bug**
I have few clusters which is only allow proxy IP. When I perform Pod shell. I got 

error: unable to upgrade connection: error dialing backend: read tcp <my computer IP>:58315-><API SERVER IP>:443: read: connection reset by peer
Terminal will auto-close in 15 seconds ...

**To Reproduce**
1. configure proxy
2. go to pod
3. click Pod shell

**Expected behavior**
remote exec shell inside Pod

**Environment (please complete the following information):**
- Lens Version: 3.6.4
- OS: OSX
- Installation method: auto upgrade

**Comment by aaronsssya** [comment]
same issue in version 3.6.5

**Comment by nevalla** [comment]
Where did you configure the proxy?

**Comment by aaronsssya** [comment]
I configured proxy in the settings. When I new cluster, I add it.

**Comment by aaronsssya** [comment]
it working in version 3.6.6.
Thanks
