### ISSUE TITLE
YAML Templates in Create Resource dock tab

### ISSUE THREAD

**Issue by aleksfront** [lensapp/lens#995]
Create resource controls area should contain `Template` dropdown selector with list of predefined workloads. Clicking any of them would paste yaml template into editor.

![template dropdown](https://user-images.githubusercontent.com/9607060/94530522-e00dd780-0243-11eb-89b4-4851e7abe847.png)

**Comment by lucj** [comment]
That one would be so convenient ! Will this enhancement considered in a next release ?

**Comment by pashevskii** [comment]
I'll take the task

**Comment by aleksfront** [comment]
An implementation update. YAML templates should be configured in app preferences page by selecting package (or folder) containing all needed templates. Also, there's need to mix packages together, add or remove them. For example, we might have `k8s workloads` package available by default, and user might want to add `AWS resources` so they should be active together.

If more that one package active, they must be grouped by the name in the `React-Select` dropdown. See https://react-select.com/home#getting-started
