### ISSUE TITLE
Shell access to pods despite RBAC prohibited "pods/exec" 

### ISSUE THREAD

**Issue by antonmatsiuk** [lensapp/lens#997]
**Describe the bug**
Shell execution into pod works in Lens despite prohibited  RBAC "create" verb for "pods/exec" resource. At the same time, following kubectl command:
```
 kubectl exec -ti -n NAMESPACE_NAME POD_NAME sh 
```
for the same context (service account) shows proper access denied message:
```
Error from server (Forbidden): pods "POD_NAME" is forbidden: User "system:serviceaccount:default:SERVICE_ACCOUNT_NAME" cannot create resource "pods/exec" in API group "" in the namespace "NAMESPACE_NAME"
```

**To Reproduce**
1. Create a service account, clusterrole and clusterrolebinding from the file attached [rbac-test-accont.yml.zip](https://github.com/lensapp/lens/files/5299594/rbac-test-accont.yml.zip)
2. switch Lens to the attached service account
3. Try to log in into any pod 

**Expected behavior**
Lens prohibits shell access to pod  in case RBAC "create" verb is not alowed for "pods/exec" resource.

**Environment (please complete the following information):**
- Lens Version: Lens: 3.6.4
- OS: MacOS 10.15.5
- Installation method (e.g. snap or AppImage in Linux): brew 
- Azure AKS Cluster 1.17.9 with RBAC enabled

**Comment by nevalla** [comment]
I'm a bit lost here...pod shell is started via kubectl exec command so there should not be any difference. How do you switch Lens to attached service account?

**Comment by antonmatsiuk** [comment]
this is really weird, I deleted all the clusters in lens, created a new one with the attached SA and now it works as expected
